### ISSUE TITLE
It would be great to have documentation of the supported regexp commands

### ISSUE THREAD

**Issue by Derek61** [plk/biblatex#1010]
Documentation of the supported regexp commands would be great, either directly in the manual or as  a reference to whatever package supplies support for them.

**Comment by moewew** [comment]
I agree that it would be nice, but it would make the manual even longer. Currently the manual says

> Modify the contents of a field using standard Perl regular expression match
and replace.

I usually google "Perl Regex" if I want to know something, but it appears to me that https://perldoc.perl.org/perlre.html would be the first official place to look.

**Comment by moewew** [comment]
Added a short footnote about Perl regex documentation in https://github.com/plk/biblatex/commit/8671a03d3d692abe4c1732f5fd8d4765b759db3a. I think that's all we should and can reasonably do here.

**Comment by moewew** [comment]
There is a now a short note about this in the `biblatex` documentation of version 3.15 and above. Suggestions to improve this within the limits of our documentation are welcome.

**Comment by u-fischer** [comment]
While I quite agree that you can't describe all the perl regex stuff, there is nevertheless imho a documentation for the `\regexp` command itself missing. Currently you only see it in examples and in a rather cursory sentence saying `regular expressions can be escaped using the dedicated \regexp command` which doesn't make it very clear what escaping means here and why it is needed

Perhaps something like that

      \regexp{<regular expression>}

This command can be used with the `match` and `replace` key to pass a regular expression to biber. The argument is a normal perl regular expression (see ... ). Perl escape sequences like `\t` for a tab, `\n` for a newline, `\A` for the start of a string or `\d` for a digit can be used, without TeX trying to execute them as commands, as can be special characters like `^`, `_` or `{..}` and `#`. Only the `%` must be protected: to match a single `%` in the bib, use `\%` in the regular expression, a `\%` is matched  by `\\\%`. 

(hoping that I got it all right, I didn't test everything ;-))

**Comment by plk** [comment]
Added in DEV branch - thank you for the suggestion.
