### ISSUE TITLE
Should bibstring definitions (and other language changes) live in extras<language>?

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#1011]
I wondered about this a while ago in https://github.com/plk/biblatex/issues/964#issuecomment-583103675. I'm not saying we need to or should change anything here, but it somehow appears to me that `\captions<language>` would be much more appropriate for our language switcheroo than `\extras<language>`. In particular if we used `\captions<lang>` then there would be a real difference between `autolang=other,` and `autolang=other*,` which might be nice.

I'd love to hear people's thoughts on this.

**Comment by jspitz** [comment]
FWIW I tend to agree.

**Comment by moewew** [comment]
Thanks for the feedback. Maybe I should just try and implement a "captions" version for testing (if things look OK we can make the `\captions...` version the default and implement an option or another simple switch to get back to the `\extras...` behaviour.)

**Comment by moewew** [comment]
Hrmmm ... one thing I forgot (I thought about this before, so I should write it down now) is that we clean up after ourselves with `\noextras...`. I don't think there is a `\nocaptions...`, so that would be tricky.

In theory we could put our `extras` into `\extras...` and our strings into `\captions...` but that would result in really weird side-effects if only language extras are selected and not captions. So this is out.

**Comment by jspitz** [comment]
> In theory we could put our `extras` into `\extras...` and our strings into `\captions...` 

Yes, this would be the way to go.

> but that would result in really weird side-effects if only language extras are selected and not captions. So this is out.

I cannot follow this

**Comment by moewew** [comment]
> > but that would result in really weird side-effects if only language extras are selected and not captions. So this is out.
> 
> I cannot follow this

`biblatex` does not only have language-dependent strings. There are a few other things like the Oxford comma, date formatting etc. One well-known example is that `french.lbx` does (simplified!)
```
\DeclareBibliographyExtras{%
  \savecommand\mkbibnamefamily
  \protected\def\mkbibnamefamily#1{%
    \textsc{\textnohyphenation{#1}}}%
}
```
and then
```
\UndeclareBibliographyExtras{%
  \restorecommand\mkbibnamefamily
}
```
`\DeclareBibliographyExtras` goes into `\extrasfrench` and `\UndeclareBibliographyExtras` is added to `\noextrasfrench` to clean up any side effects afterwards.

Since there is no `\noextras...` equivalent to for `\captions...` these definitions can't go into `\captions...`  because we can't clean up after ourselves.

For all uses of `\UndeclareBibliographyExtras` in the `biblatex` core that I found this is probably not an issue as long as the language switching commands come with grouping that encloses the `\captions...` call. But at least theoretically we currently allow global assignments in `\DeclareBibliographyExtras` which would need a clean-up in `\UndeclareBibliographyExtras`. (I think I could come up with a simple example one I implemented the new `\captions...` idea.)

**Comment by jspitz** [comment]
I agree that such settings should go to `\extras` (date formatting and friends are also in `\extras` both in babel and polyglossia). `\captions` only holds string definitions that never need to be 'undone' since they simply get re-defined if needed.

So for biblatex, everything that localizes strings (basically all things `\bibstring` I suppose) should go to `\captions`, and everything that is more locale-specific should go to `\extras`.

**Comment by moewew** [comment]
But that would leave us with a very weird result. Take
```latex
\documentclass[french,british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}


\begin{document}
\autocite{sigfridsson}

\begin{otherlanguage}{french}
% switches \captions & \extras
\autocite{sigfridsson}
\end{otherlanguage}

\begin{otherlanguage*}{french}
% switches only \extras
\autocite{sigfridsson}
\end{otherlanguage*}

\printbibliography
\end{document}
```
Currently this gives
> ![(Sigfridsson and Ryde 1998)//(SIGFRIDSSON et RYDE1998)//(SIGFRIDSSON et RYDE 1998)](https://user-images.githubusercontent.com/6755835/84508415-85fffb00-acc2-11ea-8d24-2c1c9fe88dc0.png)

But if the bibstrings went to `\captions` and the other extras (e.g. `\mkbibnamefamily`) went into `\extras` we'd get

> ![(Sigfridsson and Ryde 1998)//(SIGFRIDSSON et RYDE1998)//(SIGFRIDSSON and RYDE 1998)](https://user-images.githubusercontent.com/6755835/84508575-c6f80f80-acc2-11ea-8dad-e7c5d91d2346.png)

which would look a bit odd. There is really no good way to separate `biblatex`-extras and `biblatex`-bibstrings.

**Comment by jspitz** [comment]
I see. It's odd that even font shapes are defined there, but there you have it.

**Comment by moewew** [comment]
Yeah, the redefinition of `\mkbibnamefamily` in the language extras is certainly an 'interesting' choice (not only does it cause confusion for quite some users, it also contests the notion that localisation is only translating of strings and a different date format), but there would be other examples where I think it is clearer that the things should live in `\extras` (Oxford comma, `\lbx@lfromlang`, ...).

**Comment by jspitz** [comment]
> Currently this gives
> 
> > ![(Sigfridsson and Ryde 1998)//(SIGFRIDSSON et RYDE1998)//(SIGFRIDSSON et RYDE 1998)](https://user-images.githubusercontent.com/6755835/84508415-85fffb00-acc2-11ea-8d24-2c1c9fe88dc0.png)

FWIW I get different results with polyglossia. With

```tex
% !TeX TS-program = xelatex
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{british}
\setotherlanguage{french}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}


\begin{document}
\autocite{sigfridsson}

\begin{otherlanguage}{french}
% switches \captions & \extras
\autocite{sigfridsson}
\end{otherlanguage}

\begin{otherlanguage*}{french}
% switches only \extras
\autocite{sigfridsson}
\end{otherlanguage*}

\printbibliography
\end{document}
```

I get (with current biblatex):

![image](https://user-images.githubusercontent.com/4538783/84592200-26c9f400-ae44-11ea-8901-91439319ddb9.png)

which is due to a typo in biblatex.sty:
```tex
\csgappto{inlinextras@bbl@#1}
```
should read
```tex
\csgappto{inlineextras@bbl@#1}
```
(note the missing _e_).

Having written this, what you want to achieve could probably be done in `polyglossia` by simply adding strings and the related locale stuff only to `\blockextras`, not `\inlineextras` (as it is now, inadvertently).

Alas, there is no such discrimination for `babel` AFAICS. But I might be wrong here.

**Comment by moewew** [comment]
Oh, thanks for spotting that typo. Fortunately this was already fixed in https://github.com/plk/biblatex/commit/b159f0ea158afa38a6e679f324355abcb03fd7fd.

**Comment by moewew** [comment]
The distinction between `\blockextras...` and `\inlineextras...` has always confused me, but I never looked at it more closely. If I understand correctly, though, there is only `\noextras...` (and not two different `\blocknoextras...`, `\inlinenoextras...`), so I'm not too sure what happens to `\UndeclareBibliographyExtras` if we only populate `\blockextras...`.

**Comment by jspitz** [comment]
Well, the distinction is useful exactly for cases such as this requested here.

If `\noextras` is properly defined, nothing bad should happen if you only populate `\blockextras` (otherwise we should have seen that probably in current biblatex).

**Comment by moewew** [comment]
If I'm not mistaken everything that the `biblatex` core and the core `.lbx` files do is indeed safe in that situation. It's even better than that because currently the `\UndeclareBibliographyExtras` calls we have are not needed anyway, since all language switching commands come with grouping and everything that `\DeclareBibliographyExtras` does is local.

The question is if there is a bona fide use case for global assignments that need to be cancelled explicitly by `\UndeclareBibliographyExtras`.

**Comment by moewew** [comment]
Let me know what you think of https://github.com/plk/biblatex/pull/1018.

**Comment by jspitz** [comment]
I think that's a valid approach. It's certainly more an expert-like thing.

If absolutely necessary, you could also try and convince at some point Javier and Arthur (or me) to implement something like `\nocaptions` (or maybe `\ifcaptions{language}`) in babel and polyglossia.

**Comment by moewew** [comment]
> If absolutely necessary, you could also try and convince at some point Javier and Arthur (or me) to implement something like `\nocaptions` (or maybe `\ifcaptions{language}`) in babel and polyglossia.

That's my backup plan in case it turns out that many people use something in the bibliography extras that needs real resetting in `\noextras...` and not just the grouping that we have anyway. For now I won't bother because I think `\nocaptions....` isn't entirely trivial to implement in the current setup (at least in `babel`).

**Comment by moewew** [comment]
Oh, there we have it. Just a few minutes later I find an example where we need `\nocaptions...` ...

```latex
\documentclass[british,french]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}


\begin{document}
\show\captionsfrench
\cite{sigfridsson}

\begin{otherlanguage}{british}
\cite{sigfridsson}
\end{otherlanguage}

\printbibliography
\end{document}
```

**Comment by moewew** [comment]
OK, that problem should be resolved with https://github.com/plk/biblatex/pull/1018/commits/db0b57087611155a88eb28442ac24aa7bab84af1.

I had to switch from the `beforeextras` `babel` hook to `afterreset` (#970), but hopefully that shouldn't be an issue.
