### ISSUE TITLE
minnames does not have as expected

### ISSUE THREAD

**Issue by RalfJung** [plk/biblatex#1014]
"minnames" is documented as 

> A limit affecting all lists of names (author, editor, etc.). If a list holds more than
hmaxnamesi names, it is automatically truncated to hminnamesi names. The hminnamesi
value must be smaller than or equal to hmaxnamesi. minnames is the master option which
sets both minbibnames and mincitenames.

So, when I am citing a paper with 7 authors (which is more than maxnames), I would expect the citation to look like "Firstauthor et. al.". But that is not what happens: for some papers, it still lists two author names, and for some even three. But that is only the case with biber as a backend; with bibtex, it cites the expected number of authors.

Here's an example for where it cites two authors:
```
@inproceedings{iris,
  author    = {Ralf Jung and
               David Swasey and
               Filip Sieczkowski and
               Kasper Svendsen and
               Aaron Turon and
               Lars Birkedal and
               Derek Dreyer},
  title     = {Iris: Monoids and Invariants as an Orthogonal Basis for Concurrent
               Reasoning},
  booktitle = {{POPL}},
  pages     = {637--650},
  year      = {2015},
  doi       = {10.1145/2676726.2676980},
}
```
And this one gets three:
```
@inproceedings{iris2,
  author    = {Ralf Jung and Robbert Krebbers and Lars Birkedal and
               Derek Dreyer},
  title     = {Higher-order ghost state},
  booktitle = {ICFP},
  pages     = {256--269},
  year      = {2016},
  doi       = {10.1145/2951913.2951943},
}
```
usepackage line:
```
\usepackage[backend=biber,uniquename=false,maxbibnames=10,minnames=1,minbibnames=10,citestyle=authortitle,bibstyle=ext-alphabetic]{biblatex}
```

**Comment by moewew** [comment]
You want `uniquelist=false`. See also https://tex.stackexchange.com/q/69028/35864.

The passage you quoted from the documentation goes on to say

>  Like `maxnames` the value of `minnames` can be overridden by `uniquelist`.

and the `maxnames` entry refers to the relevant sections of the docs explaining `uniquelist` in more detail

> Note that the `uniquelist` feature can locally override `maxnames`, see the documentation of
the `uniquelist` option in § 3.1.2.3 and § 4.11.4.

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber,
  citestyle=authortitle, bibstyle=ext-alphabetic,
  uniquename=false, uniquelist=false,
  maxbibnames=10,
  minnames=1, minbibnames=10,
]{biblatex}

\begin{filecontents}{\jobname.bib}
@inproceedings{iris,
  author    = {Ralf Jung and
               David Swasey and
               Filip Sieczkowski and
               Kasper Svendsen and
               Aaron Turon and
               Lars Birkedal and
               Derek Dreyer},
  title     = {Iris: Monoids and Invariants as an Orthogonal Basis for Concurrent
               Reasoning},
  booktitle = {{POPL}},
  pages     = {637--650},
  year      = {2015},
  doi       = {10.1145/2676726.2676980},
}
@inproceedings{iris2,
  author    = {Ralf Jung and Robbert Krebbers and Lars Birkedal and
               Derek Dreyer},
  title     = {Higher-order ghost state},
  booktitle = {ICFP},
  pages     = {256--269},
  year      = {2016},
  doi       = {10.1145/2951913.2951943},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\cite{iris,iris2}
\printbibliography
\end{document}
```
> ![Jung et al., ‘Iris: Monoids and Invariants as an Orthogonal Basis for Concurrent Reasoning’; Jung et al., ‘Higher-order ghost state’](https://user-images.githubusercontent.com/6755835/84167228-3f1dc580-aa76-11ea-9ca9-628268af6b5f.png)

`uniquelist` also plays a role in https://github.com/plk/biber/issues/320.

**Comment by RalfJung** [comment]
Yeah I just found `uniquelist` and am trying if that helps -- but according to my copy of the docs, `false` is its default.

**Comment by RalfJung** [comment]
> The passage you quoted from the documentation goes on to say

Not in my version, looks like I have outdated docs... *oops*

**Comment by RalfJung** [comment]
Yes `uniquelist=false` solves this, and I'll look into updating my local copies of the latex docs.^^

Thanks a lot!

**Comment by moewew** [comment]
> Yeah I just found `uniquelist` and am trying if that helps -- but according to my copy of the docs, `false` is its default.

Yes-ish. `uniquelist=false` is the package default. But styles may override it. In your case `citestyle=authortitle,` sets `uniquelist=true,`

This is explained in the section documenting the citation styles

> [`authortitle`] This style implements a simple author-title citation scheme. It will make use of the `shorttitle` field, if available. It is intended for citations given in footnotes. The style will set the following package options at load time: `autocite=footnote`, `uniquename=full`, `uniquelist=true`.

----

The note I quoted about `uniquelist` influencing `minnames` was added in https://github.com/plk/biblatex/commit/f199c0e9af2c8955c83fa44b6da916e48f31491f (two years ago) in response to https://github.com/plk/biblatex/issues/756.
