### ISSUE TITLE
autolang=hyphen string printed in front of citation

### ISSUE THREAD

**Issue by pcdi** [plk/biblatex#1015]
In the following MWE

```latex
\documentclass{article}

\usepackage{polyglossia}
\setdefaultlanguage{english}
\setotherlanguage{french}

\usepackage[autolang=hyphen]{biblatex}

\begin{filecontents}{\jobname.bib}
  @Book{FoucaultSurveillerPunir,
  author    = {Foucault, Michel},
  title     = {Surveiller et punir},
  date      = {1975},
  subtitle  = {La naissance de la prison},
  language  = {french},
  publisher = {Gallimard},
  location  = {Paris},
  langid    = {french},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

the language string used for `autolang`’s `hyphenrules` coming from `langid`, i.e. “french” in this case, is printed in front of the citation:

![Output preview](https://user-images.githubusercontent.com/4654151/84174815-5e6d2080-aa7f-11ea-9b50-053621d0b7af.png)

**Comment by moewew** [comment]
`hyphenrules` is no longer defined when `polyglossia` is used. 
```latex
\documentclass{article}

\usepackage{polyglossia}
\setdefaultlanguage{english}
\setotherlanguage{german}

\begin{document}
\parbox[t]{0pt}{\hspace{0pt}Donaudampfschifffahrtskapitän}
\showhyphens{Donaudampfschifffahrtskapitän}

\begin{hyphenrules}{german}
\parbox[t]{0pt}{\hspace{0pt}Donaudampfschifffahrtskapitän}
\showhyphens{Donaudampfschifffahrtskapitän}
\end{hyphenrules}
\end{document}
```
I reported it at https://github.com/reutenauer/polyglossia/issues/427.

Hopefully the `polyglossia` developers thing the environment useful enough that they bring it back. If not we will have to remove `polyglossia` support for that  option (`autolang=hyphen`).

**Comment by jspitz** [comment]
FYI polyglossia 1.50 has just been submitted to CTAN, so this can be closed.
