### ISSUE TITLE
Inconsistent dashes and styles when multiple languages are used

### ISSUE THREAD

**Issue by dustalov** [plk/biblatex#1017]
I found that the most recent versions of BibLaTeX (3.14) and Polyglossia (1.49) from TeX Live 2020 produce inconsistent dashes and styles in References when multiple languages are used.

![biblatex-url.pdf](https://user-images.githubusercontent.com/40397/85223994-c7ce2700-b3cf-11ea-8c3b-fa16261b35c9.png)

I expected the page numbers and the URL label to look exactly the same in both languages. The Russian version has a longer `\bibrangedash` compared to the one in the English version and the URL label is not in small-caps. Could you please let me know if it is possible to fix it?

<details><summary>MWE</summary>

```latex
\begin{filecontents*}{\jobname.bib}
@article{entry1,
  author  = {Doe, John},
  title   = {The quick brown fox jumps over the lazy dog},
  journal = {Journal},
  year    = {2020},
  pages   = {1--2},
  url     = {http://example.com/},
  langid  = {english},
}

@article{entry2,
  author  = {Иванов, Иван},
  title   = {В чащах юга жил бы цитрус? Да, но фальшивый экземпляр!},
  journal = {Журнал},
  year    = {2020},
  pages   = {1--2},
  url     = {http://example.ru/},
  langid  = {russian},
}
\end{filecontents*}

\documentclass[varwidth]{standalone}

\usepackage{fontspec}
\setmainfont{FreeSerif}
\setsansfont{FreeSans}
\setmonofont[Mapping=,]{FreeMono}

\usepackage{polyglossia}
\setmainlanguage{english}
\setotherlanguage{russian}

\usepackage[backend=biber,autolang=langname]{biblatex}
\addbibresource{\jobname.bib}

\begin{document}

\nocite{*}

\printbibliography

\end{document}
```
</details>

**Comment by moewew** [comment]
This is the expected result. With `autolang=langname,` you tell `biblatex` to typeset entries with a `langid` field in `\begin{<langid>}...\end{<langid>}`. Within that environment, the translation of the bibstrings ("in" vs "в", ...) and language extras (en-dash or em-dash for page ranges, ...) changes.

It is possible that earlier combinations of `biblatex` and `polyglossia` did not produce this result, but that would have been a bug. In recent versions, commpatibility between `biblatex` and `polyglossia` was improved, so that the results for `babel` and `polyglossia` should now be the same.

In case you have a font that has both Latin and Cyrillic characters you may want to consider dropping `autolang=langname`. In that case both entries will be set in English.

**Comment by plk** [comment]
For completeness, I should add that the experimental 4.0 branches of `biblatex` and `biber` are "multiscript" branches which allow language/script switching at a more granular level than an entire entry.

**Comment by dustalov** [comment]
Thank you both for quick responses! I use `autolang=langname` intentionally because it provides correct translation for bibstrings. I received the same result in Overleaf (TeX Live 2019), so it does not seem to be a bug.

I have never seen these long dashes in Russian bibliography before, so it confused me. Is there a way to enforce the dash and small-caps from English, while keeping the translation and everything else the same?

**Comment by moewew** [comment]
According to https://github.com/plk/biblatex/blame/dev/tex/latex/biblatex/lbx/russian.lbx `\bibrangedash` has been an em-dash in Russian for eight years. But you can certainly change that if you like.

Example with `libertinus` because I don't have the fonts from your MWE
```
\begin{filecontents*}{\jobname.bib}
@article{entry1,
  author  = {Doe, John},
  title   = {The quick brown fox jumps over the lazy dog},
  journal = {Journal},
  year    = {2020},
  pages   = {1--2},
  url     = {http://example.com/},
  langid  = {english},
}

@article{entry2,
  author  = {Иванов, Иван},
  title   = {В чащах юга жил бы цитрус? Да, но фальшивый экземпляр!},
  journal = {Журнал},
  year    = {2020},
  pages   = {1--2},
  url     = {http://example.ru/},
  langid  = {russian},
}
\end{filecontents*}

\documentclass{article}

\usepackage{libertinus}

\usepackage{polyglossia}
\setmainlanguage{english}
\setotherlanguage{russian}

\usepackage[backend=biber,autolang=langname]{biblatex}

\DefineBibliographyExtras{russian}{%
  \protected\def\bibrangedash{%
    \textendash\penalty\hyphenpenalty}%
}

\addbibresource{\jobname.bib}

\begin{document}

\nocite{*}

\printbibliography

\end{document}
```

**Comment by dustalov** [comment]
I suspect this em-dash came from the `biblatex` adaptation of the standard for bibliography called GOST, which is *very complex* ([ГОСТ Р 7.0.100–2018](https://www.rsl.ru/photo/!_ORS/5-PROFESSIONALAM/7_sibid/ГОСТ_Р_7_0_100_2018_1204.pdf), in Russian). They seem to not differentiate between em-dash and en-dash while using exclusively en-dash throughout the document. Thank you for the workaround, I need to think about sending a PR to `biblatex` to adjust this.

I noticed that the small-caps problem is caused by the fact that there is something wrong with the font I use ([gnu-freefont](https://ctan.org/pkg/gnu-freefont) in CTAN). When the language is `english`, `\textsc{doi}` produces `ᴅᴏɪ`, but when the language is `russian` it produces just `doi`. I think this issue is more related to Polyglossia rather than to `biblatex`. As a workaround, I can redefine the bibstrings.
