### ISSUE TITLE
Missing hook for memoir with refsection and appendix

### ISSUE THREAD

**Issue by daleif** [plk/biblatex#1019]
(Related to https://tex.stackexchange.com/q/550930/3929)

If memoir is used with the `refsection=chapter` option `biblatex` will patch  `\memchapinfo` and `\memchapstarinfo`.

But if an appendix is used, `memoir` actually uses  `\memappchapinfo` and `\memappchapstarinfo` instead (not sure why Peter Wilson chose that), and thus the patch is actually not used with in the appendix.

The the following seems to solve the problem, just added the two extra patches with the right names.

```
\def\blx@refpatch@chapter@memoir#1{%
  \apptocmd\memchapinfo{#1}
    {}{\blx@err@patch{\string\memchapinfo}}%
  \apptocmd\memchapstarinfo{#1}
  {}{\blx@err@patch{\string\memchapstarinfo}}%
  \apptocmd\memappchapinfo{#1}
    {}{\blx@err@patch{\string\memchapinfo}}%
  \apptocmd\memappchapstarinfo{#1}
  {}{\blx@err@patch{\string\memchapstarinfo}}%
}
```

**Comment by moewew** [comment]
Thanks for the report, should be fixed in https://github.com/plk/biblatex/commit/2e404bdfeff7212e9c801ea23e10a8476f6fe636.
