### ISSUE TITLE
A misplaced brace in \defbibenvironment{shorthand} definition causes extra vertical space

### ISSUE THREAD

**Issue by danielhrossi** [plk/biblatex#1020]
I was making a custom environment for shorthands and found a misplaced closing brace in \defbibenvironment{shorthand} definition, that causes extra vertical space between the list body and its heading.
Here's the code as it appears in section 4.2.2 of _The biblatex Package_ manual  (see `\hss}}}`):

> \defbibenvironment{shorthand}
	{\list%
		{\printfield[shorthandwidth]{shorthand}}%
		{\setlength{\labelwidth}{\shorthandwidth}%
			\setlength{\leftmargin}{\labelwidth}%
			\setlength{\labelsep}{\biblabelsep}%
			\addtolength{\leftmargin}{\labelsep}%\setlength{\itemsep}{\bibitemsep}%
			\setlength{\parsep}{\bibparsep}%
			\renewcommand*{\makelabel}[1]{##1\hss}}}
	{\endlist}
	{\item}

And here's the correction I had to do for being able to use it (see {\bibparsep}}%):

> \defbibenvironment{shorthand}
	{\list%
		{\printfield[shorthandwidth]{shorthand}}%
		{\setlength{\labelwidth}{\shorthandwidth}%
			\setlength{\leftmargin}{\labelwidth}%
			\setlength{\labelsep}{\biblabelsep}%
			\addtolength{\leftmargin}{\labelsep}%\setlength{\itemsep}{\bibitemsep}%
			\setlength{\parsep}{\bibparsep}}%
			\renewcommand*{\makelabel}[1]{##1\hss}}
	{\endlist}
	{\item}

**Comment by moewew** [comment]
Mhhh, the code you quote as incorrect
```latex
\defbibenvironment{shorthand}
  {\list
     {\printfield[shorthandwidth]{shorthand}}
     {\setlength{\labelwidth}{\shorthandwidth}%
      \setlength{\leftmargin}{\labelwidth}%
      \setlength{\labelsep}{\biblabelsep}%
      \addtolength{\leftmargin}{\labelsep}%
      \setlength{\itemsep}{\bibitemsep}%
      \setlength{\parsep}{\bibparsep}%
      \renewcommand*{\makelabel}[1]{##1\hss}}}
  {\endlist}
  {\item}
```
is (more or less) what's used in all standard styles.

I could not see any excess space in
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{sigfridsson,kant:kpv}

\printbiblist{shorthand}

\printbibliography
\end{document}
```
and adding the suggested
```latex

\defbibenvironment{shorthand}
  {\list
     {\printfield[shorthandwidth]{shorthand}}
     {\setlength{\labelwidth}{\shorthandwidth}%
      \setlength{\leftmargin}{\labelwidth}%
      \setlength{\labelsep}{\biblabelsep}%
      \addtolength{\leftmargin}{\labelsep}%
      \setlength{\itemsep}{\bibitemsep}%
      \setlength{\parsep}{\bibparsep}}%
   \renewcommand*{\makelabel}[1]{##1\hss}}
  {\endlist}
  {\item}
```
to that code does not change the output.

----

I had a look at some uses of `\makelabel` in the LaTeX kernel
```latex
\newenvironment{description}
               {\list{}{\labelwidth\z@ \itemindent-\leftmargin
                        \let\makelabel\descriptionlabel}}
               {\endlist}
```
```latex
\def\enumerate{%
  \ifnum \@enumdepth >\thr@@\@toodeep\else
    \advance\@enumdepth\@ne
    \edef\@enumctr{enum\romannumeral\the\@enumdepth}%
      \expandafter
      \list
        \csname label\@enumctr\endcsname
        {\usecounter\@enumctr\def\makelabel##1{\hss\llap{##1}}}%
  \fi}
```
```latex
\def\itemize{%
  \ifnum \@itemdepth >\thr@@\@toodeep\else
    \advance\@itemdepth\@ne
    \edef\@itemitem{labelitem\romannumeral\the\@itemdepth}%
    \expandafter
    \list
      \csname\@itemitem\endcsname
      {\def\makelabel##1{\hss\llap{##1}}}%
  \fi}
```
they all issue `\makelabel` redefinitions in the second argument of `\list` as we do currently.


Would it be possibly to share a short example document that reproduces the undesirable extra space with the current definition?

**Comment by danielhrossi** [comment]
Sorry, I cannot send the example, the error never showed up again while
I was trying to reproduce it. I tried yours, moewew, and it worked as
you said. So now I do not know what happened, it seems to be a
coincidence that I changed that brace and things went right. The dash
option in shorthands, which was not working either, now works. 

I close the issue then. 

El 2020/07/01 02:13, moewew escribió:

> Mhhh, the code you quote as incorrect
> 
> \defbibenvironment{shorthand}
> {\list
> {\printfield[shorthandwidth]{shorthand}}
> {\setlength{\labelwidth}{\shorthandwidth}%
> \setlength{\leftmargin}{\labelwidth}%
> \setlength{\labelsep}{\biblabelsep}%
> \addtolength{\leftmargin}{\labelsep}%
> \setlength{\itemsep}{\bibitemsep}%
> \setlength{\parsep}{\bibparsep}%
> \renewcommand*{\makelabel}[1]{##1\hss}}}
> {\endlist}
> {\item}
> 
> is (more or less) what's used in all standard styles. 
> 
> I could not see any excess space in
> 
> \documentclass[british]{article}
> \usepackage[T1]{fontenc}
> \usepackage[utf8]{inputenc}
> \usepackage{babel}
> \usepackage{csquotes}
> 
> \usepackage[style=authoryear, backend=biber]{biblatex}
> 
> \addbibresource{biblatex-examples.bib}
> 
> \begin{document}
> \cite{sigfridsson,kant:kpv}
> 
> \printbiblist{shorthand}
> 
> \printbibliography
> \end{document}
> 
> and adding the suggested
> 
> \defbibenvironment{shorthand}
> {\list
> {\printfield[shorthandwidth]{shorthand}}
> {\setlength{\labelwidth}{\shorthandwidth}%
> \setlength{\leftmargin}{\labelwidth}%
> \setlength{\labelsep}{\biblabelsep}%
> \addtolength{\leftmargin}{\labelsep}%
> \setlength{\itemsep}{\bibitemsep}%
> \setlength{\parsep}{\bibparsep}}%
> \renewcommand*{\makelabel}[1]{##1\hss}}
> {\endlist}
> {\item}
> 
> to that code does not change the output. 
> -------------------------
> 
> I had a look at some uses of \makelabel in the LaTeX kernel
> 
> \newenvironment{description}
> {\list{}{\labelwidth\z@ \itemindent-\leftmargin
> \let\makelabel\descriptionlabel}}
> {\endlist}
> 
> \def\enumerate{%
> \ifnum \@enumdepth >\thr@@\@toodeep\else
> \advance\@enumdepth\@ne
> \edef\@enumctr{enum\romannumeral\the\@enumdepth}%
> \expandafter
> \list
> \csname label\@enumctr\endcsname
> {\usecounter\@enumctr\def\makelabel##1{\hss\llap{##1}}}%
> \fi}
> 
> \def\itemize{%
> \ifnum \@itemdepth >\thr@@\@toodeep\else
> \advance\@itemdepth\@ne
> \edef\@itemitem{labelitem\romannumeral\the\@itemdepth}%
> \expandafter
> \list
> \csname\@itemitem\endcsname
> {\def\makelabel##1{\hss\llap{##1}}}%
> \fi}
> 
> they all issue \makelabel redefinitions in the second argument of \list as we do currently. 
> 
> Would it be possibly to share a short example document that reproduces the undesirable extra space with the current definition? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1] https://github.com/plk/biblatex/issues/1020#issuecomment-652195540
[2]

**Comment by moewew** [comment]
OK. If the problem appears again, please do not hesitate to post again here.
