### ISSUE TITLE
\addbibresource

### ISSUE THREAD

**Issue by hvoss49** [plk/biblatex#1026]
A % char between the optional argument and the mandatory one gives to an error:

```latex
\documentclass{article}
\usepackage{biblatex}

\iffalse
\makeatletter
\def\blx@addbib@i#1[#2]#3{%
  \begingroup
  \blx@hook@fileverb
  \blx@addbib@ii{#1}{#2}{#3}}
\makeatother
\fi

\addbibresource[location=remote]%
{https://ctan.org/tex-archive/macros/latex/contrib/biblatex/bibtex/bib/biblatex/biblatex-examples.bib}
\begin{document}

\nocite{*}
\printbibliography[type=online]
\end{document}
```

> 
> (/usr/local/texlive/texmf-dist/tex/latex/biblatex/biblatex.cfg
> File: biblatex.cfg 
> ))
> 
> ! LaTeX Error: Missing \begin{document}.
> 
> See the LaTeX manual or LaTeX Companion for explanation.
> Type  H <return>  for immediate help.
>  ...                                              
>                                                   
> l.14 {h
>      ttps://ctan.org/tex-archive/macros/latex/contrib/biblatex/bibtex/bib/bi...
> You're in trouble here.  Try typing  <return>  to proceed.

The macro `\blx@hook@fileverb` is called too early and % has another catcode.
Modifying the macro `\blx@addbib@i` to read the file argument _before_ `\blx@hook@fileverb`
is called, fixes the problem. Change `\iffalse` to `\iftrue`
Maybe that other bibfile names needs the original definition.

I am running lualatex with up-to-date TL2020

**Comment by moewew** [comment]
Thank you for reporting this issue.

Unfortunately, the suggested fix doesn't quite work because it doesn't 'deactivate' characters as expected. Check out (never mind that you don't have the `.bib` file)
```latex
\documentclass{article}
\usepackage{biblatex}

\iffalse
\makeatletter
\def\blx@addbib@i#1[#2]#3{%
  \begingroup
  \blx@hook@fileverb
  \blx@addbib@ii{#1}{#2}{#3}}
\makeatother
\fi

\addbibresource{~/test.bib}
\begin{document}
\nocite{*}
\printbibliography
\end{document}
```
with the current `biblatex` version the `.bcf` file contains
```xml
  <bcf:bibdata section="0">
    <bcf:datasource type="file" datatype="bibtex">~/test.bib</bcf:datasource>
  </bcf:bibdata>
```
with the suggested change we get
```xml
  <bcf:bibdata section="0">
    <bcf:datasource type="file" datatype="bibtex">\nobreakspace {}/test.bib</bcf:datasource>
  </bcf:bibdata>
```
which is not what we want.

Character codes aren't my forte, but I think we need to issue `\blx@hook@fileverb` before the argument is grabbed to make special characters safe. And that is the problem you ran into with `%` : The code also makes `%` into an 'other' character, so it no longer starts a comment. Hence, it is not ignored and grabbed as the argument. Chaos ensues.

A similar problem can be observed in
```latex
\documentclass{article}
\usepackage{url}

\begin{document}
\url%
{http://example.com}
\end{document}
```
`hyperref`'s `\url` doesn't error, but also doesn't do what you want, either
```latex
\documentclass{article}
\usepackage{hyperref}

\begin{document}
\url%
{http://example.com}
\end{document}
```

I can't see a way to get both things: Make `%` safe in the argument and allow it to be used without trouble as normal before the argument. I've learned to be careful with statements like "this can't be done", but it appears too tricky for me.

Unless somebody has an idea that lets us have our cake an eat it too, the only thing we can do is add a note to the docs about this (cf. also https://github.com/plk/biblatex/issues/586).

**Comment by hvoss49** [comment]
This works for me:

```
\documentclass{article}
\usepackage{biblatex}

\makeatletter
\def\blx@addbib@i#1[#2]#3{%
  \begingroup
  \blx@hook@fileverb
  \blx@addbib@ii{#1}{#2}{\detokenize{#3}}}
\makeatother

\addbibresource[location=remote]%
{https://hvoss.org/test_.bib}
\addbibresource{~/test.bib}
\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

**Comment by moewew** [comment]
Ah, I didn't think of that, but then macros don't get expanded. So
```latex
\documentclass{article}
\usepackage{biblatex}

\def\mypath{./}

\makeatletter
\def\blx@addbib@i#1[#2]#3{%
  \begingroup
  \blx@hook@fileverb
  \blx@addbib@ii{#1}{#2}{\detokenize{#3}}}
\makeatother

\begin{filecontents}[force]{\jobname.bib}
@book{appleby,
  author  = {Humphrey Appleby},
  title   = {On the Importance of the Civil Service},
  date    = {1980},
}
\end{filecontents}
\addbibresource{\mypath\jobname.bib}

\begin{document}
\nocite{*}
\printbibliography
\end{document}
```
fails.

**Comment by hvoss49** [comment]
Next try with all three different possibilities of loading the file.

```
\documentclass{article}
\usepackage{biblatex}

\def\mypath{./}

\makeatletter
\def\blx@addbib@i#1[#2]#{\blx@addbib@@i{#1}[#2]}%
\def\blx@addbib@@i#1[#2]{%
  \begingroup
  \blx@hook@fileverb
  \blx@addbib@ii{#1}{#2}}
\makeatother

\begin{filecontents}[force]{\jobname.bib}
@book{appleby,
  author  = {Humphrey Appleby},
  title   = {On the Importance of the Civil Service},
  date    = {1980},
}
\begin{filecontents}[force]{~/\jobname.bib}
@book{appleby2,
  author  = {Humphrey Applebyby},
  title   = {On the second Importance of the Civil Service},
  date    = {1988},
}
\end{filecontents}

\addbibresource{\mypath\jobname.bib}
\addbibresource{~/\jobname.bib}
\addbibresource[location=remote]%  
  {https://ctan.org/tex-archive/macros/latex/contrib/biblatex/bibtex/bib/biblatex/biblatex-examples.bib}

\begin{document}

\nocite{*}
\printbibliography
\end{document}
```

I am running the example in `~/Desktop` and all three different bib files are loaded sucessfully.

**Comment by moewew** [comment]
We're getting closer... This breaks
```latex
\documentclass{article}
\usepackage{biblatex}

\makeatletter
\def\blx@addbib@i#1[#2]#{\blx@addbib@@i{#1}[#2]}%
\def\blx@addbib@@i#1[#2]{%
  \begingroup
  \blx@hook@fileverb
  \blx@addbib@ii{#1}{#2}}
\makeatother


\addbibresource[location=remote]
{https://ctan.org/tex-archive/macros/latex/contrib/biblatex/bibtex/bib/biblatex/biblatex-examples.bib}

\begin{document}

\nocite{*}
\printbibliography
\end{document}
```
though, which was working before.

The question is whether more people would expect
```latex
\addbibresource[location=remote]%
{https://ctan.org/tex-archive/macros/latex/contrib/biblatex/bibtex/bib/biblatex/biblatex-examples.bib}
```
to work than
```latex
\addbibresource[location=remote]
{https://ctan.org/tex-archive/macros/latex/contrib/biblatex/bibtex/bib/biblatex/biblatex-examples.bib}
```

----

Your suggestion has the advantage that the number of spaces in the next line don't matter
```latex
\addbibresource[location=remote]%
{https://ctan.org/tex-archive/macros/latex/contrib/biblatex/bibtex/bib/biblatex/biblatex-examples.bib}
```
and
```latex
\addbibresource[location=remote]%
  {https://ctan.org/tex-archive/macros/latex/contrib/biblatex/bibtex/bib/biblatex/biblatex-examples.bib}
```
work just as well.

With the old code
```latex
\addbibresource[location=remote]
{https://ctan.org/tex-archive/macros/latex/contrib/biblatex/bibtex/bib/biblatex/biblatex-examples.bib}
```
would work, but
```latex
\addbibresource[location=remote]
  {https://ctan.org/tex-archive/macros/latex/contrib/biblatex/bibtex/bib/biblatex/biblatex-examples.bib}
```
wouldn't.

**Comment by hvoss49** [comment]
Hopefully the last try :-)  `\ifnextchar is used to drop all following % and spaces (thanks to Heiko)

```
\documentclass{article}
\usepackage{biblatex}

\makeatletter
\def\blx@addbib@i#1[#2]{%
  \begingroup
  \@ifnextchar\bgroup% killall spaces and %
  {\blx@hook@fileverb\blx@addbib@ii{#1}{#2}}%
  {\blx@hook@fileverb\blx@addbib@ii{#1}{#2}}%
}
\makeatother

\edef\TestBib{\detokenize{https://hvoss.org/~voss/test_.bib}}
\addbibresource[location=remote]\TestBib

\addbibresource[location=remote]{https://hvoss.org/~voss/test_.bib}

\addbibresource[location=remote]
    {https://hvoss.org/~voss/test_.bib}

\addbibresource[location=remote]%
    {https://hvoss.org/~voss/test_.bib}

\begin{document}

\nocite{*}
\printbibliography
\end{document} 
```

**Comment by moewew** [comment]
Yeah, that looks good and seems to work well with everything I could throw at it. Committed in https://github.com/plk/biblatex/commit/e37dc3eaf630154074fc455a63bb86993f261b75. Thank you very much.

**Comment by moewew** [comment]
`biblatex` 3.15 with the change is out now and available in MikTeX and TeX live. Fingers crossed that everything works as expected. If there are any issue with `\addbibresource` please report them in a new issue.
