### ISSUE TITLE
Set a label after  \printbibliography

### ISSUE THREAD

**Issue by rugk** [plk/biblatex#1036]
For the use case etc. see https://tex.stackexchange.com/q/558982/98645

TL;DR is: I would like to have a `\label` after/for the heading set by biblatex when it generates the bibliography, so I can refer to that.

It's best practice in LaTeX to have labels for all that headings, so I guess this should be done here too.

It may be adjustable with an option for `\printbibliography`.

**Comment by moewew** [comment]
I'm thinking about a `label` option for `\printbibliography`. Then one could say
```latex
\printbibliography[heading=bibnumbered, label=biblabel]
```
and `biblatex` would add `\label{biblabel}` after the heading.

It should be noted that a `\ref` to the label may not always result in good outcome if the heading is unnumbered, but that is the user's responsibility.

I'll push the code I've lined up for this to my fork or open a PR once the dust with the 3.15 release has settled.

**Comment by moewew** [comment]
Since this is only a small change I pushed it to `dev` for v3.16, see https://github.com/plk/biblatex/commit/853d8e92dd8cbfb2fd46b061b629fa6f6db4e4c4.

Example

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}
\usepackage{cleveref}

\addbibresource{biblatex-examples.bib}


\begin{document}
\autocite{sigfridsson}

\Cref{biblabel}

\printbibliography[heading=bibnumbered, label=biblabel]
\end{document}
```

**Comment by moewew** [comment]
`biblatex` v3.16 with the new feature is available on in both MikTeX and TeX Live. The MWE from above now gives the desired output.
