### ISSUE TITLE
Document the extended name format

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#1038]
As suggested by @u-fischer in https://chat.stackexchange.com/transcript/message/55331517#55331517, we probably should have some more examples for the extended name format also in the `biblatex` doc: That makes it easier to find

**Comment by plk** [comment]
Added in dev and replaced references to `biber` docs with internal references. I made this a fairly high-level section (3.4) as it's of obvious interest to users and is in fact a major attractive feature at least as important as related entries and sorting.
