### ISSUE TITLE
IAST Sanskrit Collation stopped working

### ISSUE THREAD

**Issue by ppasedach** [plk/biblatex#1042]
IAST Sanskrit collation via transliteration to Devanāgarī which used to work at some point does not work at all for me currently (TeX Live 2020). The following MWE should give an output in a similar order as that of the source file, but currently I get only Latin order, as in ABC.

```
\documentclass{article}
\usepackage{biblatex}
\addbibresource{\jobname.bib}

\begin{filecontents*}{\jobname.bib}

@misc{a,
title = {a},
}

@misc{ā,
title = {ā},
}

@misc{i,
title = {i},
}

@misc{ī,
title = {ī},
}

@misc{u,
title = {u},
}

@misc{ū,
title = {ū},
}

@misc{ṛ,
title = {ṛ},
}

@misc{ṝ,
title = {ṝ},
}

@misc{ḷ,
title = {ḷ},
}

@misc{ḹ,
title = {ḹ},
}

@misc{e,
title = {e},
}

@misc{ai,
title = {ai},
}

@misc{o,
title = {o},
}

@misc{au,
title = {au},
}

@misc{aṃ,
title = {aṃ},
}

@misc{aḥ,
title = {aḥ},
}

@misc{ka,
title = {ka},
}

@misc{kha,
title = {kha},
}

@misc{ga,
title = {ga},
}

@misc{gha,
title = {gha},
}

@misc{ṅa,
title = {ṅa},
}

@misc{ca,
title = {ca},
}

@misc{cha,
title = {cha},
}

@misc{ja,
title = {ja},
}

@misc{jha,
title = {jha},
}

@misc{ña,
title = {ña},
}

@misc{ṭ,
title = {ṭ},
}

@misc{ṭha,
title = {ṭha},
}

@misc{ḍa,
title = {ḍa},
}

@misc{ḍha,
title = {ḍha},
}

@misc{ṇa,
title = {ṇa},
}

@misc{ta,
title = {ta},
}

@misc{tha,
title = {tha},
}

@misc{da,
title = {da},
}

@misc{dha,
title = {dha},
}

@misc{na,
title = {na},
}

@misc{pa,
title = {pa},
}

@misc{pha,
title = {pha},
}

@misc{ba,
title = {ba},
}

@misc{bha,
title = {bha},
}

@misc{ma,
title = {ma},
}

@misc{ya,
title = {ya},
}

@misc{ra,
title = {ra},
}

@misc{la,
title = {la},
}

@misc{va,
title = {va},
}

@misc{śa,
title = {śa},
}

@misc{ṣa,
title = {ṣa},
}

@misc{sa,
title = {sa},
}

@misc{ha,
title = {ha},
}

@misc{kṣa,
title = {kṣa},
}

@misc{jña,
title = {jña},
}

\end{filecontents*}

\DeclareSortTranslit{
  \translit[title]{iast}{devanagari}
}

\begin{document}
\nocite{*}
\printbibliography
\end{document}

```

**Comment by plk** [comment]
The format of the `\translit` command changed a while ago:

```
\DeclareSortTranslit{
  \translit{title}{iast}{devanagari}
}
```

You can also specify to do this only for entries with particular `langids`

```
\DeclareSortTranslit{
  \translit[sanskrit]{title}{iast}{devanagari}
}

```

See the latest PDF docs.

**Comment by ppasedach** [comment]
With this change my old setup works again, thanks, but I fear that it is a bit fragile, kicking in basically when the title is the field according to which the sorting happens. In fact I have two `.bib` files, one for primary texts, one for secondary literature. I do already have a sourcemap adding a certain keyword to all entries from the first bib file, using this keyword or its absence to build my two bibliographies. In theory there could be an entry in the secondary bibliography which for some reason gets sorted according to its title, which would then happen according to Sanskrit alphabet, which might not be what I want at that point.

```
\DeclareSourcemap{
  \maps{
    \map{
      \perdatasource{bhv1.bib}
      \step[fieldset=keywords, fieldvalue=pri]
      \step[fieldsource=title, final]
      \step[fieldset=sortkey, origfieldval]
    }
  }
}

```

So I suppose I could add a line to that `\DeclareSortMap` construct adding a `langid`  all entries from `bhv1.bib`, and then use your second chunk of code instead of the first one, making it safer? In a way though I'd rather have it kind of as a argument to `printbibliography`. Or alternatively, could one at some place add a condition to do the transliterated sorting only when the entry has the required keyword?

**Comment by plk** [comment]
That's what the `langid` optional argument is really for as we want to transliterate based semantic information like language of the entry rather then their presence in a file. I would therefore recommend using a sourcemap to add the relevant `langid` too all entries in one of the files or perhaps arrange to have this `langid` in all relevant entries anyway.
