### ISSUE TITLE
Compound names cause errors

### ISSUE THREAD

**Issue by sneves** [plk/biblatex#1043]
Texlive 2020, updated to latest CTAN. Minimal example:

```

\begin{filecontents}{\jobname.bib}
@Misc{XXX,
    Author = {Jean{-}Pierre Blargh},
    Publisher = {Some Publisher},
    Title = {Some Title},
    Year = {2080}
}
\end{filecontents}

\documentclass{article}
\usepackage[style=numeric,backend=biber]{biblatex}
\addbibresource{\jobname.bib}
\begin{document}
\cite{XXX}
\printbibliography
\end{document}
```

This results in a compilation error,

```
! Extra }, or forgotten \endgroup.
l.29       }
```

Looking at the .bbl file, we see

```
      \name{author}{1}{}{%
        {{hash=2c2f69edba26ee42ec0a1829e9b40440}{%
           family={Blargh},
           familyi={B\bibinitperiod},
           given={Jean{-}Pierre},
           giveni={J\bibinithyphendelim }\bibinitperiod}}}%
      }
```
There's a mismatched `}` character there, which suggested the initial processing doesn't quite know how to handle the `{-}` sequence properly.

**Comment by josephwright** [comment]
Why is the `-` in braces in the first place?

**Comment by sneves** [comment]
Entries coming from, say, DBLP, do this by default. Like [this](https://dblp.org/rec/journals/micro/Goulding-HottaSVGAHANBBST11.html?view=bibtex) one.

**Comment by sieversMartin** [comment]
See https://github.com/plk/biber/issues/329

**Comment by sneves** [comment]
Ah, sorry, I managed to miss that one. Closing.
