### ISSUE TITLE
authoryear-comp: `\parencite` in `addendum` can produce unwanted `;'

### ISSUE THREAD

**Issue by CasperVector** [plk/biblatex#1046]
As the title, for instance
```latex
\begin{filecontents}{test.bib}
@book{test01, author = {Author1}, title = {Title1}, year = {2001}}
@book{test02, author = {Author2}, title = {Title2}, year = {2002}}
@book{test03,
	author = {Author3}, title = {Title3}, year = {2003},
	addendum = {\parencite{test01}, \parencite{test02},
		\parencite{test01}, \parencite{test02}}}
\end{filecontents}

\documentclass{article}
\usepackage[style = authoryear-comp]{biblatex}
\addbibresource{test.bib}
\begin{document}
\printbibliography
\nocite{*}
\end{document}
```
produces the addendum
```
(Author1 2001), (; Author2 2002), (; Author1 2001), (; Author2 2002)
```

**Comment by moewew** [comment]
That's basically the same issue discussed in https://github.com/plk/biblatex/issues/988 (and https://tex.stackexchange.com/q/397975/35864, https://tex.stackexchange.com/q/435162/35864): Citations in bibliography entries upset the punctuation tracker.

As mentioned in #988, I think I know a way to resolve this issue, but that may break other ('integrated') uses of `\cite` commands in the bibliography, so I don't think we can change anything here.

If you know you won't need style-'integrated' `\...cite...` commands in the bibliography you can try the redefinition of `\blx@citecmdinit` discussed in #988.

In any case I'd urge you to try and get rid of citations in bibliography entries. Sometimes it is possible to replace them with the `related` feature or set features.

**Comment by CasperVector** [comment]
Many thanks; I guess the `\mkbibcitesafe` approach in #988 will be a quick workaround.
