### ISSUE TITLE
Example involving CiteULike: to be deleted or, better, replaced

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#1054]
Since [CiteULike](https://web.archive.org/web/20190310145602/http://www.citeulike.org/news) is now closed down, it is worth to delete or, better, replace [the example involving it](https://github.com/plk/biblatex/blob/7bfa1b768690053bb75e14fad39e2ecad5f05b53/doc/latex/biblatex/biblatex.tex#L3677) in the documentation.

**Comment by plk** [comment]
If anyone has a nice, stable HTTPS .bib file somewhere we can reference?

**Comment by moewew** [comment]
I was thinking we could take `biblatex-examples.bib` on CTAN
```latex
\addbibresource[location=remote]{http://mirrors.ctan.org/macros/latex/contrib/biblatex/bibtex/bib/biblatex/biblatex-examples.bib}
```
That's at least partly under our control and CTAN are unlikely to change their generic URLs (or at least so I hope).

But the file is not served on HTTPS yet and the URL is quite long.

**Comment by moewew** [comment]
I went ahead and used the GitHub location of `biblatex-examples.bib` in https://github.com/plk/biblatex/commit/af1186dd647b9eab2385b0879a5a92b3d2fd538c.

It doesn't look great length-wise, but at least the link is true HTTPS and at least partly under our control.

**Comment by dbitouze** [comment]
Much shorter but maybe unusable (no `.bib` extension and may be considered as phishing or similar): https://git.io/JUpZL (thanks to https://git.io/).

**Comment by moewew** [comment]
Since https://git.io/JUpZL redirects to the raw file https://raw.githubusercontent.com/plk/biblatex/master/bibtex/bib/biblatex/biblatex-examples.bib and Biber follows up on the 302 Found returned by the server that works as well, but I'd rather have a 'readable' link than a shortened and unreadable one.
