### ISSUE TITLE
Biblatex 3.15a, casechanger=expl3, and latin1 encoding

### ISSUE THREAD

**Issue by dfussner** [plk/biblatex#1058]
When I use the standard LaTeX engine and the latin1 encoding, any
non-ASCII characters in titles create problems in a context where the
`titlecase` format is set to `\MakeSentenceCase{#1}` and the expl3 module
is in force. After many such characters, a space will disappear (see
MWE), and ü (u with umlaut) completely chokes LaTeX on my system,
requiring deletion of the .bbl. If `\MakeSentenceCase` isn't used
there's no issue, nor is there one with `casechanger=latex2e`.

Here's a MWE:

```
\documentclass[12pt]{article}
\usepackage[T1]{fontenc}
\usepackage{csquotes}
\usepackage[latin1]{inputenc}
\usepackage[french,american]{babel}
\usepackage[style=verbose-inote,bibencoding=latin1,backend=biber]{biblatex}
\DeclareFieldFormat{titlecase}{\MakeSentenceCase*{#1}}
\begin{filecontents}[overwrite]{\jobname.bib}
@book{knuth:ct:a,
  author       = {Knuth, Donald E.},
  title        = {Le Passé d'une Illusion},
  date         = {1984},
  maintitle    = {Computers \& Typesetting},
  volume       = {A},
  publisher    = {Addison-Wesley},
  location     = {Reading, Mass.}
}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}
\thispagestyle{empty}

\noindent\cite{knuth:ct:a}.

\printbibliography
\end{document}
```

Here's what it looks like on my system:

![mwe16](https://user-images.githubusercontent.com/5174434/95491861-21179180-0992-11eb-904e-80278613e5b5.png)

If I use unicode and XeLaTeX everything is fine.

Many thanks.

**Comment by moewew** [comment]
@josephwright Is `l3text` supposed to be able to handle `latin1`?

(Save as `latin1` or get it from [lttlo.txt](https://github.com/plk/biblatex/files/5352923/lttlo.txt))
```latex
\documentclass[12pt]{article}
\usepackage[T1]{fontenc}
\usepackage{csquotes}
\usepackage[latin1]{inputenc}

\usepackage{babel}
\usepackage{expl3}

\ExplSyntaxOn
\newcommand*{\test}{\text_titlecase:n}
\ExplSyntaxOff


\begin{document}
\test{Le Passé d'une Illusion}
\end{document}
```

**Comment by josephwright** [comment]
@moewew No: it's purely UTF-8. Life gets very tricky if you want to have encoding-specific mappings, as the whole of the 8-bit range (at least) is then not a simple situation. Moreover, the code was written for new documents: there's really no need for using other encodings today (at least not for cased languages).

**Comment by moewew** [comment]
Hrmpf, I feared as much. So we may have to think about enabling the `expl3` case changer only if we detect the document encoding as UTF8.

**Comment by moewew** [comment]
@josephwright I completely understand that you have to draw the line somewhere. Supporting only UTF-8 properly is definitely an understandable and sensible choice.

It's just a bit annoying for us, because that means we can't drop the `latex2e` case change code and are stuck with both code paths.

**Comment by josephwright** [comment]
@moewew I guess my point was we are talking about the case where someone is using `biblatex` from 2020; that means they should be in a position to use UTF-8. So it would not be unreasonable to say that updates require UTF-8.

@dfussner What's the reason for Latin-1 here?

**Comment by dfussner** [comment]
@josephwright  Some of my test files for biblatex-chicago are, for purely historical reasons (aka laziness), still in latin1, so when I was doing a round of pre-release testing I came across the issue, which is why it took me so long to stumble across it. I'm happy to warn users either to set casechanger=latex2e or use utf-8 -- at least there's a compatibility layer for people who, for one reason or another, have long-standing projects that aren't in Unicode. On the other hand, I guess @moewew is right that this requires continued maintenance of that compatibility layer. Which path is less onerous for the two of you who are doing the hard work?

**Comment by moewew** [comment]
As appealing as it would be to only (properly) support UTF-8 in future versions, I don't think this is anything we can do short- or even medium-term. People generally expect their documents to compile after updates, so telling them their old documents are no longer supported is bound to make many people unhappy.

@dfussner https://github.com/plk/biblatex/commit/316598708aa0847ba962e92d146529391db062ff changes the implementation of the default `casechanger=auto,` option value to only enable the new `expl3` case changer if the document is detected as UTF-8. If the document is not detected as UTF-8 or the `expl3` version is too old, we fall back to `casechanger=latex2e`.

**Comment by moewew** [comment]
Hrmm, turns out delaying loading the case changing code messes with catcodes more than I thought. See https://github.com/plk/biblatex/commit/c5c85ad606969bf4fa4b35231806de207a74e5a3, which ideally should not have been needed.

I'm not quite sure what to do. Ideally we'd load the case changer code after we parsed the options, but if people change the document encoding after loading `biblatex` we'd detect the wrong encoding.

**Comment by moewew** [comment]
If it only were the `@` catcode that is tricky we could probably cook something up that stores and restores the catcode when we load the case changing code, but `\ExplSyntaxOn` redefines a bunch of catcodes and I don't want to have to keep track of all of them.

**Comment by moewew** [comment]
https://github.com/plk/biblatex/commit/a4abc28fad769876fbd5e047153f0e77049516b7 tries to solve the issue by upgrading `blx-case-expl3` and `blx-case-latex2e` from `.def` to `.sty` files so we can use `\RequirePackage` (which means LaTeX does all the catcode stuff).

It doesn't feel great to use `.sty` and load these files, which are essentially submodules, as packages, but it solves the immediate problem.

If anyone has a better idea what to do here, I'd be happy to hear it. An alternative would have been to load the files not in `\AtBeginPreamble` but directly in `biblatex`, but then we wouldn't be able to detect any encoding declarations/changes after `biblatex` is loaded.

**Comment by u-fischer** [comment]
> If anyone has a better idea what to do here,

I just saw this issue, so here my 2cent:  while I think that it is sensible to still have fallback code for 8bit, I don't think that biblatex needs to catch every case. Imho you can require that the input encoding is set before biblatex is loaded and load your code based on this. To catch the  cases where documents don't follow this rule, you could add a test for the encoding at begin document, or when a \MakeXXXCase command is used the first time and then error or warn.

**Comment by moewew** [comment]
`biblatex` v3.16, which was released on 31. Dec 2020 and is available now in TeX live and MIkTeX, only uses `expl3` case changing code if the file is detected as UTF-8-encoded. The MWE from above thus falls back to the old case changing code and works fine again.

**Comment by moewew** [comment]
Because of https://tex.stackexchange.com/q/581409/35864 and https://github.com/plk/biblatex/issues/1090 we no longer load the case changing code that late (https://github.com/plk/biblatex/commit/15a62fb5bb227db5ef613aaa13778d92bd190f29). We guess the encoding twice and warn if it does not match.

I was tempted to make the message if the two guessed encodings do not match an error and not a warning, but I figured the error would be probably more frustrating for users here than only getting a warning.
