### ISSUE TITLE
Itemize spacing changes when biblatex authoryear is used with beamer documentclass

### ISSUE THREAD

**Issue by maaattes** [plk/biblatex#1061]
When I use the standard authoryear style which comes with the `biblatex` package in my beamer presentation, the spacing in my itemize environments changes. I'm using `beamer 2020/07/22 v3.59` and `biblatex 2020/08/23 v3.15a`.

MWE:
```tex
\documentclass{beamer}
\usepackage[style=authoryear,backend=biber]{biblatex}

\begin{document}
  \begin{frame}{Test}
    \begin{itemize}
      \item This is a very long sentence that spans several lines. This is a very long sentence that spans several lines. This is a very long sentence that spans several lines.
      \item This is a very long sentence that spans several lines. This is a very long sentence that spans several lines. This is a very long sentence that spans several lines.
      \item This is a very long sentence that spans several lines. This is a very long sentence that spans several lines. This is a very long sentence that spans several lines.
    \end{itemize}
  \end{frame}
\end{document}
```
![demo](https://user-images.githubusercontent.com/52661914/95772917-c8ac0100-0cbd-11eb-9cec-3833f5ff78f2.png)
(notice the hanging indent)

[This image shows the result I'm expecting](https://user-images.githubusercontent.com/52661914/95773042-0ad54280-0cbe-11eb-8ff2-7986f1108e4f.png)

**Comment by hvoss49** [comment]
It seems that biblatex pverwrites the value of `\labelwidth` which it shouldn't. A workaround:

```
\documentclass[professionalfonts]{beamer}
\typeout{>>>>>>>>>\the\labelwidth}% Look into the log file
\let\beamerLabelwidth\labelwidth
\usepackage{libertinus-otf}
\usepackage[autostyle]{csquotes}
\usepackage[style=authoryear]{biblatex}
\typeout{>>>>>>>>>\the\labelwidth}% Look into the log file
\setlength\labelwidth{16.425pt}

\begin{document}

  \begin{frame}{Test}
    \begin{itemize}
      \item This is a very long sentence that spans several lines. This is a very long sentence 
      that spans several lines. This is a very long sentence that spans several lines.
      \item This is a very long sentence that spans several lines. This is a very long sentence 
      that spans several lines. This is a very long sentence that spans several lines.
      \item This is a very long sentence that spans several lines. This is a very long sentence 
      that spans several lines. This is a very long sentence that spans several lines.
    \end{itemize}
  \end{frame}

\setlength\labelwidth{-3.05pt}
% for the bibliography

\end{document}
```

**Comment by moewew** [comment]
This looks very much like https://github.com/josephwright/beamer/issues/625.

**Comment by maaattes** [comment]
> This looks very much like https://github.com/josephwright/beamer/issues/625.

Ah, totally missed this one, sorry!

**Comment by moewew** [comment]
The issue is closed, so it is a little bit harder to find. I only knew where to look for it, since I had the same issue a few days ago.

A little more background: `beamer` patches a few bibliography-related things (for standard `thebibliography` as well as `biblatex`). In order to get things right, `beamer` uses the new file hooks to insert patches right after some style files are loaded. That's why the problem appears right when `biblatex` is loaded, but only in `beamer`.

**Comment by moewew** [comment]
`beamer` v3.60 with a fix for the issue is now available in TeX Live and MikTeX.
