### ISSUE TITLE
Incompatibility with pdfx package? 

### ISSUE THREAD

**Issue by thbtppl** [plk/biblatex#1065]
Hello,

I get an error when trying to use conjointly biblatex and the pdfx package:
```
/home/texlive/2020/texmf-dist/tex/latex/biblatex/biblatex.sty:2175: Text line contains an invalid character.
l.2175      \bgroup\nohyphenation#1\egroup^^^^200b}}
A funny symbol that I can't read has just been input.
Continue, and I'll forget that it ever happened.
```

A MWE is:

```
\documentclass[a4paper,12pt]{article}

\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[a-1b,mathxmp]{pdfx}
\usepackage{biblatex}

\begin{filecontents}{\jobname.bib}
@article{doe2016,
title   = {Water Is Wet},
author  = {Doe, John},
journal = {Journal of Water},
volume  = {1},
number  = {1},
pages   = {600--650},
date    = {2016}
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}

Hello, \textcite{doe2016}.

\printbibliography

\end{document}
```

The MWE compiles fine when the line loading pdfx is commented.

My configuration:
Package: biblatex 2020/08/23 v3.15a programmable bibliographies (PK/MW)
Package: pdfx 2019/02/27 v1.6.3 PDF/X and PDF/A support (CVR/HTH/RRM/PS)
TeX 3.14159265 (TeX Live 2020)
Ubuntu 19.10 x86_64

**Comment by thbtppl** [comment]
I've just found out the MWE works fine with pdfx on Overleaf with:

pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020)
Package: **biblatex 2019/12/01 v3.14** programmable bibliographies (PK/MW)
Package: pdfx 2019/02/27 v1.6.3 PDF/X and PDF/A support (CVR/HTH/RRM/PS)

**Comment by moewew** [comment]
See https://github.com/plk/biblatex/issues/1044 (and https://github.com/plk/biblatex/issues/1051). A workaround is shown in https://tex.stackexchange.com/q/564990/35864.

**Comment by moewew** [comment]
Since the MWE posted here compiles fine with the fix for #1044 applied or with the workaround from https://tex.stackexchange.com/q/564990/35864 I'm closing this as a duplicate issue of #1044.

If there is anything else, don't hesitate to comment below (so we can reopen this issue if necessary) or to open a new issue.

**Comment by thbtppl** [comment]
Is the workaround just adding '`\catcode30=12`' ? It didn't work for me.

**Comment by moewew** [comment]
Yes. You just need to make sure to add it in the right place. After `pdfx` but before `biblatex`.

The following works for me
```latex
\documentclass[a4paper,12pt]{article}

\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[a-1b,mathxmp]{pdfx}
\catcode30=12
\usepackage{biblatex}

\begin{filecontents}{\jobname.bib}
@article{doe2016,
title   = {Water Is Wet},
author  = {Doe, John},
journal = {Journal of Water},
volume  = {1},
number  = {1},
pages   = {600--650},
date    = {2016}
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}

Hello, \textcite{doe2016}.

\printbibliography

\end{document}
```

**Comment by thbtppl** [comment]
Ah ok my bad I didn't catch that. Thanks a lot and sorry for the duplicate issue!
