### ISSUE TITLE
Issues with \AfterPreamble

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#1066]
See https://tex.stackexchange.com/q/567911/35864

With the new hook system `\AfterPremable` (which is for example used in `\nocite`) does not always do what we expect it to.

```latex
\documentclass{article}

\LogHook{begindocument}
% comment out to make things work
\AtBeginDocument{\relax}
\LogHook{begindocument}

\usepackage{biblatex}
\addbibresource{biblatex-examples.bib}

\LogHook{begindocument}
\nocite{*}
\LogHook{begindocument}

\begin{document}
\cite{sigfridsson}

\printbibliography
\end{document}
```

We could look into using `\AfterEndPreamble`, but maybe there is more to this.

**Comment by u-fischer** [comment]
Hm, does the \nocite code assumes that it is executed after code added by biblatex to \AtBeginDocument? Because this is no longer garantied. E.g. if you do this:

~~~~
\documentclass{article}

\AddToHook{begindocument}{\relax}
\AddToHook{begindocument}[biblatex]{\show\y}
\AddToHook{begindocument}{\show\z}


\begin{document}
xxx
\end{document} 
~~~~

then \show\z is before \show\y. 

So I think you should add the nocite code to the biblatex label, to get it in order again:

~~~~
\def\blx@nocite#1{%
  \@bsphack
  \AddToHook{begindocument}[biblatex]{%
    \ifstrequal{*}{#1}
      {\blx@nocitation@all}
      {\blx@xsanitizeafter{\forcsvlist\blx@nocite@do}{#1}}}%
  \@esphack}

~~~~

**Comment by moewew** [comment]
Yes, the code assumes that `biblatex` has already done all of its `\AtBeginDocument` stuff.

Thank your for the suggestion. `\AddToHook{begindocument}[biblatex]` also appears to be working when it is called in the document body (that is to say when `\AddToHook{begindocument}[biblatex]{<code>}` is called between `\begin{document}` and `\end{document}` it just executes `<code>`). Is that something we can rely on? I couldn't find a mention of this in `lthook-doc`, but I haven't read all of it carefully, so it may well have slipped past me.

**Comment by PhelypeOleinik** [comment]
@moewew Yes, `begindocument` is a so-called one-time hook: once it's used, any further attempt to add code to it will result in the code being executed immediately.  This is the same behaviour as in previous releases.  Though it seems to be missing a note about this in the documentation for this hook.  I'll add something

> Yes, the code assumes that `biblatex` has already done all of its `\AtBeginDocument` stuff.

You don't need to assume that, you can make sure by adding the `\nocite` stuff to a different label, and declaring a rule (if that's what you need, of course):
```latex
\def\blx@nocite#1{%
  \@bsphack
  \AddToHook{begindocument}[biblatex/nocite]{%
    \ifstrequal{*}{#1}
      {\blx@nocitation@all}
      {\blx@xsanitizeafter{\forcsvlist\blx@nocite@do}{#1}}}%
  \@esphack}
%
\DeclareHookRule{begindocument}{biblatex/nocite}{after}{biblatex}
```

**Comment by u-fischer** [comment]
Yes, you can rely on the immediate excecution. begindocument is a "One time hook" and for this hooks it is documentated:

> With one-time hooks it this is handled slightly differently: After \UseOneTimeHook
has been called, any further attempts to add code to the hook via \AddToHook will simply
execute the code immediately.

**Comment by moewew** [comment]
Ah thanks, you two. 'One-time hook' was the secret word.

I also saw `\DeclareHookRule`, but I'm wondering if it might not be overkill because we can guarantee that the code will only be added to the hook after the code that it needs has been added. On the other hand we might as well use all the fancy stuff if it's there. (We'll have to carry round compatibility code for older kernel versions anyway.)

**Comment by moewew** [comment]
This should hopefully be fixed in https://github.com/plk/biblatex/commit/af8b4412931f323d286bf25ef6154559e71fff07.
