### ISSUE TITLE
lbx file for supporting basque language

### ISSUE THREAD

**Issue by azarketa** [plk/biblatex#1068]
To whom it may concern:

Given that the current biblatex version lacks the necessary support for the basque language, I attach the correspondent lbx file.
Please feel free to ask any concerns or modifying the file altogether.

[basque.txt](https://github.com/plk/biblatex/files/5517567/basque.txt)

**Comment by moewew** [comment]
Thank you very much. The following two lines look a bit suspicious
```latex
  translator       = {{{\lbx@sfromlang}\ itzulpenaaddcolon}{{\lbx@sfromlang}\ itz\adddot\addcolon}},%
  translators      = {{{\lbx@sfromlang}\ itzulpenaaddcolon}{{\lbx@sfromlang}\ itz\adddot\addcolon}},%
```
For one `itzulpenaaddcolon` should probably have been `itzulpena\addcolon`, but bibliography strings shouldn't end in punctuation commands like `\addcolon`.

`translator` and `translators` should just be the string 'translator'. It need/should not indicate the original language.

**Comment by azarketa** [comment]
Yes, you are right. Those lines are wrongly written. By the way, I have also changed a number of other lines that ended in the 
```\addcolon``` punctuation command. Thank you for warning me. Find the updated file attached.
[basque.txt](https://github.com/plk/biblatex/files/5519004/basque.txt)

**Comment by moewew** [comment]
Thanks.

Do you want to be credited in the documentation? If so, which name would you like to see there?

**Comment by azarketa** [comment]
Oh! Okay. I will go with Ander Zarketa-Astigarraga. Thank you for the
recognition.

Sincerely,

Ander

**Comment by moewew** [comment]
Thanks you very much. `basque.lbx` was added in https://github.com/plk/biblatex/commit/06abea804913a1dd7f200327d4a6124fe6eaf999.

**Comment by moewew** [comment]
`biblatex` v3.16 was released on 31 Dec. 2020 and is available now in both MikTeX and TeX live.

The following MWE shows a Basque document
```latex
\documentclass[basque]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear]{biblatex}

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite{sigfridsson,worman,nussbaum,ctan}

\printbibliography
\end{document}
```
