### ISSUE TITLE
\assignrefcontextentries by named refcontext 

### ISSUE THREAD

**Issue by u-fischer** [plk/biblatex#1073]
It is possible to give refcontexts names and to use this names to switch the refcontext. But it seems not to be possible to use the name in `\assignrefcontextentries`. Could the command be extended to support this? For example in the following example I would like to assign the contexts "global", "unsorted" and "byyeard" to all citations entries.

```
\documentclass{article}
\usepackage[style=numeric,defernumbers]{biblatex}
\addbibresource{biblatex-examples.bib}
\DeclareRefcontext{unsorted}{sorting=none}
\DeclareRefcontext{byyeard}{sorting=ydnt}
\begin{document}
%\assignrefcontextentries[sorting=ydnt]{*}
\textcite{doody}
\textcite{aristotle:anima}
\textcite{herrmann}
\printbibliography[title=default]
\textcite{doody}
\textcite{aristotle:anima}
\textcite{herrmann}
\newrefcontext{unsorted}
\printbibliography[title=unsorted]
\textcite{doody}
\textcite{aristotle:anima}
\textcite{herrmann}
\newrefcontext{byyeard}
\printbibliography[title=by name]

\end{document}
```

**Comment by plk** [comment]
Please try DEV 3.16 - I've added an optional argument for named refcontexts which the other optional key/value arg will override if desired. For backwards compat, the syntax is s little strange (optional arg with curly braces) but not too bad:

```
\DeclareRefcontext{byyeard}{sorting=ydnt}
\assignrefcontextentries[sorting=ydnt]{*} % explicit key/val
\assignrefcontextentries{byyeard}{*} % named refcontext
\assignrefcontextentries[sorting=none]{byyeard}{*} % named refcontext with specific overrides

```

**Comment by u-fischer** [comment]
I will try. But wouldn't a "meta" key `name=byyeard` work too?

**Comment by plk** [comment]
Yes, I thought about that too - might be worth looking at.

**Comment by plk** [comment]
Turns out some concerns I had about this are unfounded and so it is as you would expect now in 3.16 DEV:

```
\DeclareRefcontext{byyeard}{sorting=ydnt}
\assignrefcontextentries[name=byyeard, sorting=none]{*}
```

Any specific keyvals will override the settings from a named refcontext.

**Comment by u-fischer** [comment]
Nice. Does the global/default setup have a name?

**Comment by plk** [comment]
There is no actual defined named refcontext for the global defaults but `name=default`, that will do what you want there and I will add this to the docs.

**Comment by moewew** [comment]
`biblatex` v3.16 with this feature was released on 31 Dec 2020 and is available now in TeX live and MikTeX.
