### ISSUE TITLE
Patching footnotes failed warning with TeX4ht

### ISSUE THREAD

**Issue by pripple** [plk/biblatex#1078]
Hi, I am trying to convert a simple LaTeX article, using BibLaTeX footnote-dw citations to ODT using ooxelatex (because I need UTF-8 characters).

I am running into two issues, both involving a warning “Patching footnotes failed” – that’s why I put them together here, just in case only one of them helps to find the reason:

----------

**Issue 1:** In the ODT, citations are put out in text instead of footnotes (also, cross-references are not shown).

There is a warning shown that isn’t shown in the LuaLaTeX compile: Package biblatex Warning: Patching footnotes failed. Footnote detection will not work. — _Is this something that can be fixed on the BibLaTeX side? Might this be the reason for the described issue?_

As probably, there is something else involved, I have also posted this (with a different focus) at https://puszcza.gnu.org.ua/bugs/?492.

-----------

I tried HTML output to check where the issue is in the pipeline. In the HTML output, both citations are put in footnotes as expected (and also, cross-references show up correctly). In the HTML output, only another small issue arises:

**Issue 2:** In HTML, the final full stop in a footnote citation isn’t suppressed in circumstances where it _is_ correctly suppressed in the LuaLaTeX PDF output. 

The same warning is shown as mentioned above. _Might this be the reason at least for this secondly described issue?_

I am providing below a `mwe.tex` and, before that, three commands that show my two issues. I am using the current version (2020-11-23-10:05), generated from tex4ht-mkht.tex, as currently included in TeX Live and also the current version of BibLaTeX included in TeX Live, 3.15a (2020-08-23).

Thank you in advance for any direction with this! — Best regards, Lorenz

------------

The three commands:

`latexmk -pdf -pdflatex=lualatex mwe.tex` → Puts out everything as I expect it: Full sentence quotations with a full stop at the end in the suffix end in `.”` – other quotations end in `”.`

`mk4ht ooxelatex mwe.tex` → Doesn’t put out cites in footnotes, doesn’t put out cross-references.

`mk4ht htxelatex mwe.tex "html,fn-in"` → Doesn’t manage the final full stop as I expect it: Full sentence quotations with a full stop at the end in the suffix end in `.”.` (last full stop should be omitted) – other quotations end (as expected) in `”.`

------------

The `mwe.tex`:

```LaTeX
% !TEX encoding = UTF-8 Unicode
\documentclass{article}
\usepackage{csquotes}
\usepackage[style=footnote-dw]{biblatex}
\begin{filecontents}{\jobname.bib}
@article{my_article,
	author = {Doe, John},
	journal = {The \TeX 4ht Journal},
	number = {3},
	pages = {393–396},
	title = {A Bibliographer’s \TeX nic Inquiry},
	volume = {25},
	year = {1989}}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}

\section{Cites}

This is where I would like to have the full stop only \emph{inside} the curly quotes.\cite[See][3, consider especially: “It can be difficult to deal with full stops and curly quotes.”]{my_article}

This is where the full stop should go at the very end.\cite[See][4, “different situation”]{my_article}

\section{Footnotes}

Lorem ipsum dolor\label{dolor} sit amet.\footnote{Test with a \label{testnt} label.}

Lorem ipsum dolor (sicut \ref{dolor}) sit amet.\footnote{Exactly like in n.~\ref{testnt}.}

\end{document}
```

**Comment by pripple** [comment]
As documented in the issue at https://puszcza.gnu.org.ua/bugs/?492, with a better command, the HTML5 output is just fine: `make4ht -l mwe.tex "fn-in"` – output exactly as expected, equal to the PDF output. Also, with the better command `make4ht -l -f odt mwe.tex`, cross-references work in the ODT output. Still, also with the improved command, in the ODT output, the citations in the MWE are put inline instead of in footnotes. But as the HTML5 output is correct, I suspect it isn’t BibLaTeX that’s not cooperating here …

**Comment by moewew** [comment]
Phew, I was hoping you'd bring this to Michal's attention. He usually responds very quickly and almost always immediately has a fix for these sort of things up his sleeve.

`biblatex` itself does (essentially) nothing to make TeX4ht's live easier, so all the TeX4ht `biblatex` support is patched in on the TeX4ht side. That means that you usually have a much better chance of getting a useful answer if you report issues with `biblatex` that only apply to TeX4ht on the TeX4ht side.

**Comment by pripple** [comment]
So, Michal found out, there was a special line explicitly deactivating footnote citations with footnote-dw, just for ODT output. <strike>`\protected\long\def\mkfootnotecite#1{#1}`</strike> 😄🙈 [He has removed that line now.](http://svn.gnu.org.ua/viewvc/tex4ht/trunk/lit/tex4ht-ooffice.tex?r1=847&r2=848)
