### ISSUE TITLE
Romanian localization

### ISSUE THREAD

**Issue by mafsi** [plk/biblatex#1083]
Hi.
First of all let me thank you for your amazing work in maintain BibLaTeX. 
Romanian language is not present, therefore I want to start translate it in next few days. I need some advice from you before I start doing translation.
1. Is it necessary to escape Romanian characters: `Ș ș` | `Ț ț` | `Î î`  `Ă ă` ` Â â`? If so please advice how to do it since I'm new in this.
2. For a newbie I didn't understand very clear how to check if my translation is correct before submit it.
   >  Compiling the file will warn you about missing strings, and looking at the generated file will help you to proofread your translation.
   
   By this you mean simply run the file in TexWork: `PdfLaTex` > `Biblatex` > `PdfLaTex` > `PdfLaTex` > `PdfViewer` ?

Thanks a lot for you understanding and help. Please understand that I'm new in LaTex (~3weeks) and I hope that my questions didn't make you uncomfortable.

**Comment by moewew** [comment]
Thank you very much for considering to contribute to `biblatex`!

I trust you have seen https://github.com/plk/biblatex/wiki/Checklist-for-submitting-a-new-localisation-file-(.lbx)

If you want to see some real-world examples of how adding a new localisation went, have a look at https://github.com/plk/biblatex/issues/972, https://github.com/plk/biblatex/issues/867, https://github.com/plk/biblatex/issues/717, https://github.com/plk/biblatex/pull/780, https://github.com/plk/biblatex/pull/1060.

Now about your questions.

1. The older `.lbx` files use TeX-macro escapes for non-ASCII chars, e.g. `\"u` for `ü`. But usually those files don't have that many non-ASCII chars and they were written before UTF-8 became as popular as it is today in the LaTeX world (in fact UTF-8 became the default file encoding in LaTeX documents about two years ago). So with some newer files we just use the Unicode characters directly. In principle this is less portable, but I think we have a strong case to argue for only supporting Unicode here. (For some languages with non-Latin script UTF-8 is the only sane solution anyway). Ultimately, I'd say the decision is up to you: Do what you think works best for Romanian users (and in particular for you).

2. Download the file https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/examples/03-localization-keys.tex to your machine, put it into the same folder as the `romanian.lbx` you are working on. Change `\usepackage[english]{babel}` to `\usepackage[romanian]{babel}`. Then compile the file with the full compile sequence for a document with `biblatex` bibliography (which should be LaTeX, Biber, LaTeX, LaTeX, so the button you list look about right: Technically the second step isn't calling `Biblatex`, it should be running Biber, but some editors use `Bib(la)tex` as a shorthand).

If you have any more questions, ask away.

**Comment by mafsi** [comment]
Problems on line 162-163 and further:
>  editortrco       = {{editor, traducător\finalandcomma\ și comentator}%
                      {ed.,\addabbrvspace trad\adddot\finalandcomma\ și coment\adddot}},

And this gives me:

> editor, traducător, și comentator
> ed., trad., și coment.

We don't use comma before `and` only in cases we have emphatic adverb like this: `I saw Mary, John, and Alexander` <- `and` in this case in Romanian is not anymore conjunction but emphatic adverb.

Q: Can I remove `\finalandcomma\` from the string?

**Comment by moewew** [comment]
You can remove `\finalandcomma` from the string, it is only present in the English localisation files to make it possible to choose whether or not to use the Oxford comma. If there is no comparable notion in Romanian (i.e. if it is not a stylistic decision whether or not to put a comma before "and"), it is probably easier to drop it from the strings. In any case we will probably redefine `\finalandcomma` to do nothing in the localisation extras.

**Comment by mafsi** [comment]
I made a PR #1085
Thanks a lot for your help! If there is anything I have to change, please let me know!

**Comment by mafsi** [comment]
Thanks a lot for integrating  Romanian localisation for the next update.
I update my dev branch but how can I test it? in the same way with `03-localization-keys`?
I tried but is not working

**Comment by moewew** [comment]
Yeah, you should be able to check out `dev` and either copy all files to a single folder and run your examples there or use the procedure https://github.com/plk/biblatex#installation-from-github to install `biblatex`-dev locally.

With the current state of `dev`
```latex
\documentclass[romanian]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear]{biblatex}


\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite{sigfridsson}
ipsum \autocite{worman}
dolor \autocite{ctan}
sit \autocite{nussbaum}
amet \autocite{geer}

\printbibliography
\end{document}
```
shows
![CTAN (2006), CTAN, The Comprehensive TeX Archive Network, url: http://www.ctan.org (accesat în 1.10.2006).](https://user-images.githubusercontent.com/6755835/103521148-9521e280-4e78-11eb-98e5-8b90bf054920.png)
for me

What do you mean, by it is not working? What exactly did you try?

**Comment by mafsi** [comment]
I merged `upstream-dev` to my `dev` and put your test file here: `biblatex\tex\latex\biblatex\lbx\` (I'm on windows), but I still don't see `comma` and `în` in file produced. I see in only in yours. I guess I'll wait the update from MiKTeX, but I'm happy with what I saw in your example.

![ref](https://user-images.githubusercontent.com/61430691/103531758-a5df5200-4e92-11eb-95df-4f9f9c1c433d.png)

**Comment by moewew** [comment]
Your https://github.com/mafsi/biblatex/blob/dev/tex/latex/biblatex/lbx/romanian.lbx does not have all the definitions that Romanian `.lbx` has in the `dev` branch on this repository (https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/lbx/romanian.lbx). Presumably you resolved merge conflicts in your fork by letting your file versions prevail instead of taking the upstream files.

**Comment by mafsi** [comment]
@moewew thanks! Solved the problem.
Q: Since Romanian localisation is now on Biblatex can I assume that major styles( Chicago in special) will inherit translation? Because running a `\usepackage {biblatex-chicago}` i noticed some strings `cbyeditor` a.s.o that are not translated.
Should I go to BibLaTeX-chicago and do some translations as I did for BibLaTeX?

**Comment by moewew** [comment]
> Since Romanian localisation is now on Biblatex can I assume that major styles( Chicago in special) will inherit translation?

Yes and no. All contributed styles will inherit the bits of the standard `biblatex` localisation that they use. But some contributed styles like `biblatex-chicago` have additional strings that are not present in standard `biblatex` (like `cbyeditor`). Translations for those strings need to be provided to the style developers/maintainer directly.

**Comment by mafsi** [comment]
@moewew if I have some updates to make to Romanian localisation I will change the same file that I translated?

For ex I'm not sure, right now, how to solve the problem of `compiler`. I checked with some friends and usually the work of the compiler is made by a redactor, but on the frontmatter is displayed like this `editor, translator and selected texts by...`

I have the same problem on biblatex-chicago and right now I'm working on a version to match the best version, so I wanted to check with you - for consistency of the files - if those particular strings in `romanian.lbx` is the only ones that I have to change. I hope this will not interfere with strings that you added at the begining and the end of the file.
Thanks!

**Comment by moewew** [comment]
Yes, you can make changes to `romanian.lbx` as before. To avoid complications, it would be good to make sure that your version of the file is up-to-date with the current state of the file at https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/lbx/romanian.lbx

**Comment by mafsi** [comment]
> 
> 
> Yes, you can make changes to `romanian.lbx` as before. To avoid complications, it would be good to make sure that your version of the file is up-to-date with the current state of the file at https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/lbx/romanian.lbx

Thanks a lot!

**Comment by moewew** [comment]
`biblatex` 3.17 with `romanian.lbx` is on CTAN now and available in both TeX live and MikTeX

**Comment by mafsi** [comment]
> `biblatex` 3.17 with `romanian.lbx` is on CTAN now and available in both TeX live and MikTeX

Thanks. I have an issue though: https://tex.stackexchange.com/questions/633088/biber-biblatex-error-after-update
