### ISSUE TITLE
Apply patches from Debian

### ISSUE THREAD

**Issue by hpreusse** [plk/biblatex#1089]
In the Debian package of biber over the years a few patches accumulated, which should go to upstream. Mostly bugs in the generated manual pages and spelling errors in the code. Yes, the whatis entries are mostly just dummies, but the manual page becomes visible to apropos(1).

Consider to apply the patches. Thanks!
[debian.zip](https://github.com/plk/biblatex/files/5762324/debian.zip)

**Comment by plk** [comment]
Applied in DEV branch, thanks.
