### ISSUE TITLE
\supercite has no whitespace between reference numbers

### ISSUE THREAD

**Issue by etclub** [plk/biblatex#1102]
I am using `citestyle=numeric-comp`.
With \cite or \textcite, the reference numbers are shown like `[1, 3, 5]`, 
while for \supercite they are like `1,3,5`, no whitespace between reference numbers.
Is this inconsistence by purpose?

**Comment by moewew** [comment]
Yes, this is expected and documented

> `\supercite{<key>}` This command, which is only provided by the numeric styles, prints numeric citations as superscripts without brackets. It uses `\supercitedelim` instead of `\multicitedelim` as citation delimiter.

Of course you can easily change that with

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=numeric, autocite=superscript]{biblatex}

\renewcommand*{\supercitedelim}{\addcomma\space}

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite{sigfridsson,worman,geer}

\printbibliography
\end{document}
```

I'm guessing that the rationale for the change was that spaces after commas in superscripts create an appearance of too much empty space. You can see the same effect with `natbib`'s `super` option. (`cite`'s `super` option produces a smaller space after the comma by default, but has an option to completely suppress that space with `nospace`.)

**Comment by moewew** [comment]
I'm closing this issue, because this is documented behaviour that can be changed easily (and at least I can see some sense in it).
