### ISSUE TITLE
\textnohyphenation does not suppress hyphenation at explicit hyphen

### ISSUE THREAD

**Issue by sieversMartin** [plk/biblatex#1111]
Please note, that the following problem does occur in a specific document and yet I was not able to produce a MWE. However, I hope to get a general answer. Thank you.

As far as I understand `\textnohyphenation` is supposed to suppress all hyphenation, i.e. it reacts similar to setting `\hyphenpenalty` and `\exhyphenpenalty` to `10000`.

In the following example, however, the word `*hu̯ar-aϑa-` at the end of the third line is hyphenated at the `-`. When setting `\exhyphenpenalty=10000` at the beginning of the paragraph everything is fine, but I need a way to suppress hyphenation for small text passages at various places and would like to avoid additional mark-up like `\mbox{...}` here.   

![problem_textnohyphenation](https://user-images.githubusercontent.com/15111133/111615345-e63b4480-87e0-11eb-828a-7ca18ac18b2f.png)

**Comment by hvoss49** [comment]
\begin{hyphenrules}{nohyphenation}
With babel …. 
\end{hyphenrules}

Herbert

**Comment by sieversMartin** [comment]
@hvoss49 Thank you. Unfortunately this does not work here either. In fact, I tried different approaches found on the web, but none works here (within the paragraph).

**Comment by hvoss49** [comment]
Provide the paragraph as text

Herbert

**Comment by sieversMartin** [comment]
I managed to create a "minimal" example, which demonstrates the problem.

The original source uses the Brill font, which I removed. As this of course changed the result the problem can now be seen at `*-at\textsuperscript{h}a-`

Trying to use some alternative `\mynohyph{....}` definitions does not work while setting the `\exhyphenpenalty` at the beginning of the paragraph works as expected:

``` latex
% !TeX TS-program = lualatex
\documentclass{scrbook}
\usepackage{fontspec}
\usepackage[british]{babel}
\newcommand*{\rightwardsarrow}{→}

\RequirePackage[driver=none]{geometry}
\geometry{%
   paperwidth=155truemm,paperheight=235truemm,%
   top=19.75truemm,headsep=4.75truemm,%
   inner=20truemm,outer=20truemm,%
   lines=40%
}
\usepackage[autostyle]{csquotes}
\usepackage{biblatex}

% different approaches
%\newcommand{\mynohyph}[1]{#1}
%\newcommand{\mynohyph}[1]{\textnohyphenation{#1}}
\newcommand{\mynohyph}[1]{%
   \begin{hyphenrules}{nohyphenation}%
   #1%
   \end{hyphenrules}%
}

\begin{document}
%\exhyphenpenalty=10000% this works when not commented out
Kellens \& Pirart's second objection against Humbach's proposal is that the latter implies an uncommon derivation chain, with a derivative in -aϑa- serving as the basis for a further derivation by means of the suffix -ii-: \textit{*hu̯ar-} \rightwardsarrow\ \textit{*hu̯ar-aϑa-} \rightwardsarrow\ \textit{*hu̯ar-aϑ-i̯a-}. Kellens \& Pirart's scepticism against such a chain (\enquote{la suffixation serait terriblement compliquée}) seems exaggerated. Formations in \mynohyph{\textit{*-at\textsuperscript{h}a-}} are well-attested in Indo-Iranian, including a number of Avestan examples (Wackernagel \& Debrunner 1954:171 sqq.). Wackernagel \& Debrunner 1954: 173 consider a correlation between formations in \textit{*-at\textsuperscript{h}a-} with nominal and verbal stems in \textit{*-a-}, which provides a model for the derivation of \textit[sound]{*hu̯araϑa-} from PrIIr.\@ \textit[to resound]{*su̯ara-} (as attested in Ved.\@ \textit{svára-\textsuperscript{ti}}). And even if there are no further examples for \textit{iia}-derivatives from \textit{aϑa}-stems in particular, the assumption of such a derivation is trivial, given the ubiquity of this suffix as a means for forming denominal adjectives.

Test
\end{document}
```

Without setting `\exhyphenpenalty=10000`:

![result_before](https://user-images.githubusercontent.com/15111133/111630174-5e5e3600-87f2-11eb-8da5-527241cf1a20.png)


With  `\exhyphenpenalty=10000`:

![result_after](https://user-images.githubusercontent.com/15111133/111630172-5dc59f80-87f2-11eb-84e5-d04388e5f9ae.png)

**Comment by hvoss49** [comment]
A solution with the (German) shorthand „~

Herbert

\documentclass{scrbook}
\usepackage{fontspec}
\usepackage[ngerman,british]{babel}

\useshorthands{"}
\addto\extrasbritish{\languageshorthands{ngerman}}

\newcommand*{\rightwardsarrow}{→}

\RequirePackage[driver=none]{geometry}
\geometry{%
   paperwidth=155truemm,paperheight=235truemm,%
   top=19.75truemm,headsep=4.75truemm,%
   inner=20truemm,outer=20truemm,%
   lines=40%
}
\usepackage[autostyle]{csquotes}
\usepackage{biblatex}


\begin{document}

\textnohyphenation{% still allows hyphenation for words with - 
Kellens \& Pirart's second objection against Humbach's proposal is that the latter implies an 
uncommon derivation chain, with a derivative in -aϑa- serving as the basis for a further derivation 
by means of the suffix -ii-: \textit{*hu̯ar-} \rightwardsarrow\ \textit{*hu̯ar-aϑa-} 
\rightwardsarrow\ \textit{*hu̯ar-aϑ-i̯a-}. Kellens \& Pirart's scepticism against such a chain 
(\enquote{la suffixation serait terriblement compliquée}) seems exaggerated. Formations in 
\textit{*-at\textsuperscript{h}a-} are well"~attested in Indo-Iranian, including a number 
of Avestan examples (Wackernagel \& Debrunner 1954:171 sqq.). Wackernagel \& Debrunner 1954: 173 
consider a correlation between formations in \textit{*-at\textsuperscript{h}a-} with nominal and 
verbal stems in \textit{*-a-}, which provides a model for the derivation of 
\textit[sound]{*hu̯araϑa-} from PrIIr.\@ \textit[to resound]{*su̯ara-} (as attested in Ved.\@ 
\textit{svára"~\textsuperscript{ti}}). And even if there are no further examples for 
\textit{iia}"~derivatives from \textit{aϑa}-stems in particular, the assumption of such a 
derivation 
is trivial, given the ubiquity of this suffix as a means for forming denominal adjectives.}


Test
\end{document}

**Comment by sieversMartin** [comment]
As all of this is used within a template used by TeX beginners, I always try to avoid to many extra macros. However, it seems, that I may indeed need some more input magic ...

**Comment by moewew** [comment]
If I understand the examples correctly, then you have words containing hyphens which you do not want to break at the hyphens. I'm not sure if `\textnohyphenation` promises to do that. As I understand it, it should avoid introducing additional hyphens for line breaking. Braking at existing hyphens might be a bit of a grey area, but might be better than getting those pesky overfull/underfull boxes.

In general I would not recommend relying too much on `biblatex`'s version of a macro like `\textnohyphenation` outside of a bibliography/citation context. (I certainly wouldn't load `biblatex` just to get that macro.) Especially `\textnohyphenation` had some issues in the past (https://github.com/plk/biblatex/issues/772).

**Comment by moewew** [comment]
I'm going to close this for now. `\textnohyphenation` is certainly not a core feature of `biblatex` and for the moment I'm prepared to accept the output the macro gives as sensible. Of course I'm happy to revisit this if improved code is suggested, but for now I don't want to keep this around as something that needs looking at.
