### ISSUE TITLE
\ifciteseen broken? Print all author names on first citation and "et al." on subsequent citations.

### ISSUE THREAD

**Issue by ClaudiusL** [plk/biblatex#1115]
I think `\ifciteseen` might be broken in the current version of biblatex. I'm using biber 2.16 / biblatex 3.16.

The following MWE (adopted from [here](https://tex.stackexchange.com/a/48857/37118)) is supposed to print all author names on the first citation and "et al." on subsequent citations:

```
\documentclass{scrartcl}

\usepackage[backend=biber,citestyle=authoryear-comp,maxcitenames=2]{biblatex}
\addbibresource{\jobname.bib}

\begin{filecontents}{\jobname.bib}
@book{Key,
  author  = {Bar, Foo and Doe, John and Bean, Mister},
  title   = {I Really Don't Know},
  date    = {2021},
}
\end{filecontents}

% Print all author names on first citation (https://tex.stackexchange.com/a/48857/37118)
% Does not work properly: *always* prints all author names.
\usepackage{xpatch}
\xpatchbibmacro{textcite}
  {\printnames{labelname}}
  {\ifciteseen
     {\printnames{labelname}}
     {\printnames[][1-99]{labelname}}}
  {}
  {}

\begin{document}
\textcite{Key}

\textcite{Key}
\end{document}
```

Expected output:

> Bar, Doe, and Bean (2021)
> Bar et al. (2021)

Actual output:
> Bar, Doe, and Bean (2021)
> Bar, Doe, and Bean (2021)

Is this a biblatex issue?

**Comment by moewew** [comment]
You'll need to turn on the citation tracker with the option `citetracker=true,` for `\ifciteseen` to work correctly.

```latex
\documentclass{scrartcl}
\usepackage[
  backend=biber,
  style=authoryear-comp,
  maxcitenames=2,
  citetracker=true,
]{biblatex}

% Print all author names on first citation (https://tex.stackexchange.com/a/48857/37118)
% Does not work properly: *always* prints all author names.
\usepackage{xpatch}
\xpatchbibmacro{textcite}
  {\printnames{labelname}}
  {\ifciteseen
     {\printnames{labelname}}
     {\printnames[][1-99]{labelname}}}
  {}
  {}

\begin{filecontents}{\jobname.bib}
@book{Key,
  author  = {Bar, Foo and Doe, John and Bean, Mister},
  title   = {I Really Don't Know},
  date    = {2021},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\textcite{Key}

\textcite{Key}
\end{document}
```

Compare also the `biblatex` options `\usepackage[style=authoryear,citetracker=true,maxcitenames=1]{biblatex}` in the answer you linked.

**Comment by ClaudiusL** [comment]
Oh. My bad. Sorry for bothering you with this unecessary report.
I didn't pay enough attention to the first part of the SO answer (explaining `citetracker`) after reading that the approach from the first half of the answer (modifying `maxnames`) is not recommended.

Thank you!
