### ISSUE TITLE
Tabular bibliography. Biblatex (Biblatex-Gost)

### ISSUE THREAD

**Issue by vibro-pribor** [plk/biblatex#1125]
I need to output the bibliography as a table. Example:

![2021-04-19_09-17-14](https://user-images.githubusercontent.com/20474616/115339233-0037c080-a1ad-11eb-91a8-e3a0ef8e5516.png)

My biblatex Style [Biblatex-Gost](https://www.ctan.org/pkg/biblatex-gost)

```
\RequirePackage[style=gost-authoryear,% Base Style authoryear 
				backend=biber,%
				bibencoding=utf8,%
				texencoding=utf8,%
				hyperref=true,%


				sorting=none,				
				mcite=false, 
				doi=false, 
				singletitle=true, 
				labeltitle=true, 
				uniquename=true]{biblatex}

    @Reference{QR_160D,    
          heading        = {QR---160D},
          hyphenation    = {russian},
          title          = {Environmental conditions and test procedures for airborne equipment}
    }
    @Reference{ASTM_D2196_18,    
          heading        = {ASTM D2196---18},
          hyphenation    = {russian},
          title          = {Standard Test Methods for Rheological Properties of Non-Newtonian Materials by Rotational Viscometer}
    }
```

I am currently using this setting, but how to add the output of the horizontal lines of the table in it, I can not understand.

   ```
     \DeclareSourcemap{
        \maps[datatype=bibtex]{
            \map{
              \step[fieldsource=heading, final]
              \step[fieldset=shorthand, origfieldval]
            }
        }
    }  
    \newcommand{\reference}{%
      \par\begin{tabularx}{\textwidth}{>{\arraybackslash}m{0.30\textwidth}>{\arraybackslash}m{0.65\textwidth}}   
            \printfield{heading}     
          & \printfield{title} \clearfield{heading} \clearfield{title} \clearlist{specdata} \clearfield{pagetotal} %
            \clearfield{year} \clearlist{publisher} \clearlist{location} \clearfield{series} \clearfield{year}%
    }
    \newcommand{\patchdrivers}{%
      \xpretobibdriver{reference}{\reference}{}{}%
      \xapptobibdriver{reference}{\end{tabularx}}{}{}%  
    } 
    \defbibenvironment{tablebib}
      { \setlength{\parindent}{0pt}%
        \renewcommand*{\labelnamepunct}{}%
        \patchdrivers}
      {}
      {} 
    \newcommand*{\VPprintbibliography}{\printbibliography[env=tablebib]}

```

Related questions:
[tex.stackexchange.com](https://tex.stackexchange.com/questions/593569/tabular-bibliography-biblatex)

**Comment by moewew** [comment]
I posted an answer over at TeX.SX: https://tex.stackexchange.com/q/593569/35864.

Please note that the bug tracker here should ideally be reserved for bug reports and feature requests for core `biblatex`. We can't really provide general end-user support for everyone here. Questions like this one are usually much better asked over at TeX.SX or your favourite other LaTeX forum. Please also consider posting fully compilable example documents and not just snippets from the preamble. Compilable code makes things much easier since it means that everyone sees the same thing and no guessing needs to be involved to see what is going on.

**Comment by vibro-pribor** [comment]
Thank you for your reply

**Comment by moewew** [comment]
I'm guessing this question was resolved over at TeX.SX, so I'll close this here.
