### ISSUE TITLE
ids-field leads to unnecessary warnings in the log file

### ISSUE THREAD

**Issue by JaMeZ-B** [plk/biblatex#1144]
Consider the following MWE:
```latex
%!TeX program = lualatex
\documentclass{article}

\begin{filecontents}{literature.bib}
	@article{psc1,
		ids={BERW},
		author = {Boris Botvinnik and Johannes Ebert and Oscar Randal-Williams},
		title = {Infinite loop spaces and positive scalar curvature},
		journal = {Inventiones Mathematicae},
		year = {2017},
	}
\end{filecontents}

\usepackage[%
	backend=biber,
	style=alphabetic,
	]%
{biblatex}
\addbibresource{literature.bib}

\begin{document}
\cite{BERW} % – warnings in the log file
% \cite{psc1} % – no warnings
\printbibliography
\end{document}
```

I usually do my compiling with `latexmk` and I noticed, that citing the alternative key defined via the `ids`-field leads to the following warnings in the log file (towards the end; without matching warnings above):

```
LaTeX Warning: There were undefined references.


Package biblatex Warning: Please (re)run Biber on the file:
(biblatex)                test2
(biblatex)                and rerun LaTeX afterwards.
```

After cleaning up all auxiliary files and switching to the original key no such warnings show up in the log file (the pdfs are fine in both cases!).

This behaviour looks like a bug to me, which leads to many unnecessarily cascading LaTeX and biber calls by latexmk and thereby undermines its use.

**Comment by moewew** [comment]
Oh yes, I don't think that should be happening. Thank you very much for reporting this.

**Comment by moewew** [comment]
The rerun detection code did not take into account key aliases (via `ids`). That should be fixed in https://github.com/plk/biblatex/commit/500ab16f02fd78afb648f685183d99e3141b8371, which also makes sure that things are tracked per refsection and not globally.

**Comment by moewew** [comment]
`biblatex` 3.17 with a fix for this is available now in TeX live and MikTeX. There should no longer be spurious warnings in the example file shown in the first post.
