### ISSUE TITLE
titlecase field format not used in related entries

### ISSUE THREAD

**Issue by rzach** [plk/biblatex#1149]
In a related entry, the `title` field is not fed through `titlecase` even though it should.

Example attached. `titlecase` is set to display sentence cased & boldfaced; the title of the related `@inbook` entry in Peirce 1880 is not.
![Screenshot from 2021-06-06 10-13-26](https://user-images.githubusercontent.com/3122348/120931730-1d1e4980-c6b0-11eb-861c-4f761e880846.png)

[titlecase.zip](https://github.com/plk/biblatex/files/6604488/titlecase.zip)

**Comment by rzach** [comment]
See also https://github.com/moewew/biblatex-ext/issues/22

**Comment by moewew** [comment]
Yeah, this is exactly the same issue that caused https://github.com/moewew/biblatex-ext/issues/22.

I started looking into a solution in the standard styles, but I haven't yet found a solution that looks good/feels right *and* is as backwards compatible as possible.

**Comment by moewew** [comment]
One way to solve this would be https://github.com/moewew/biblatex/commit/981de7003a261b47925fe1083423c6823a428976, but the downside of this approach would be that we have two macros (`author` and `plain:author`) with the same definition where in most cases we would only need one (and where changes to `author` would no longer apply to `related` entries).

**Comment by moewew** [comment]
Resolved differently in https://github.com/plk/biblatex/commit/062946241f8ff6d0ed44f29d4d7a50e237fb0b84 by disabling `labeltitle` in `related:default`. We don't need any new macros that way, but of course this is not as robust against redefinitions of `author` as a copy.
