### ISSUE TITLE
(Maybe) Marathi localisation on the dev branch has a bug

### ISSUE THREAD

**Issue by niruvt** [plk/biblatex#1153]
I am not sure if this is known to the developers or not, also I am unsure whether this report qualifies as a bug or not, but the Marathi localisation on the dev-branch is not working.

(Right now as it is unreleased I cloned the repository, issued `obuild/build.sh install 3.17-dev $HOME/texmf`. Try running the example given below with a similar installation.)

```
\documentclass{article}
\usepackage{marathi}
\usepackage{biblatex}

\begin{filecontents}[overwrite]{test-bib.bib}
@article{निरंजन,
  author={निरंजन},
  title={भाषाभ्यासातील वाद व प्रवाद},
  journaltitle={आलोक मराठी नियतकालिक},
  pages={२-९},
  date={२०२१-०१-२४},
  series={१},
  note={बुलढाणा: वर्णमुद्रा प्रकाशन}
}
\end{filecontents}

\addbibresource{test-bib.bib}

\begin{document}
\cite{निरंजन}

\printbibliography
\end{document}
```

This results in some errors with the current dev-version. OTOH if I issue `git checkout 7f59831b81e2b0c80fe15bf77df524732f848681` (SHA of [the commit](https://github.com/plk/biblatex/commit/7f59831b81e2b0c80fe15bf77df524732f848681) when the localisation was first completed.) before installing the package, errors are gone. Maybe something has changed in the `.sty` or `.lbx` which is causing errors. Please look into the matter.

Thanks.

**Comment by moewew** [comment]
I get no error from this example when I compile it with the current `biblatex` `dev` branch (both with LuaLaTeX and XeLaTeX from MikTeX updated this morning on Win 10).

What kind of errors do you get? Can you please upload the complete `.log` file?

Or do you mean that the output is wrong? In that case, please explain what is wrong. I get

![grafik](https://user-images.githubusercontent.com/6755835/122907101-169bfd00-d353-11eb-90d4-cd529a4ca699.png)

**Comment by niruvt** [comment]
This is my `.blg`:

```
[0] Config.pm:311> INFO - This is Biber 2.16
[0] Config.pm:314> INFO - Logfile is 'test.blg'
[79] biber:340> INFO - === Sun Jun 27, 2021, 10:54:55
[94] Biber.pm:415> INFO - Reading 'test.bcf'
[173] Utils.pm:411> ERROR - Error: Found biblatex control file version 3.8, expected version 3.7.
This means that your biber (2.16) and biblatex (3.17-dev) versions are incompatible.
See compat matrix in biblatex or biber PDF documentation.
[173] Biber.pm:132> INFO - ERRORS: 1
```

In the output I cannot see the citation as well as the bibliography:

![Screenshot_2021-06-27_10-59-59](https://user-images.githubusercontent.com/54938729/123533917-debbfd80-d736-11eb-8461-040d7c406fd5.png)

For the TeX-log, please visit the following link: https://pastebin.com/RhMMYRXd

**Comment by moewew** [comment]
Ah yes, for the current `dev` branch of `biblatex` you will need the `dev` version of Biber as well. You can get it from https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/development/binaries/. (Neither `biblatex`-`dev` nor Biber-`dev` are available via `tlmgr`.)

**Comment by niruvt** [comment]
Ah! Okay. So this isn't a bug then.

So to be clear, for this code to work correctly we need `v2.17` of both `biblatex` and `biber`, right?

Not to hurry you up, but just out of curiosity, is there any tentative plan for the next release? 😄

**Comment by moewew** [comment]
You'll always need matching versions of `biblatex` and Biber. What the exact version numbers are varies (that's why there is a compatibility table in the manual). For `dev` versions the compatible versions are not mentioned in the manual because everything is still in flux, so you have to check back on SourceForge for a dev binary and use that if one is available.

**Comment by niruvt** [comment]
Okay. Thanks. I am closing this.
