### ISSUE TITLE
Can't use expl3 in bibmacros

### ISSUE THREAD

**Issue by dollodart** [plk/biblatex#1159]
I would like to use the expl3 l3sort utilities to sort (and then range compress) some citations (see issue #1138) passed to a bibmacro. However, I can't use the expl3 macros. The MWE is below. Seeing a problem with `expl3` load time at [TeX SE 581409](https://tex.stackexchange.com/questions/581409), I explicitly loaded `expl3` before biblatex, but this appears to be unrelated.

```
\documentclass{article}
%
\begin{filecontents}{mwe.bbx}
\newbibmacro*{mwe}{
\ExplSyntaxOn
\seq_new:N \l_foo_seq
\ExplSyntaxOff
}
%
\DeclareBibliographyDriver{myarticle}{
  \usebibmacro{mwe}
}
\end{filecontents}
%
\begin{filecontents}{mwe.dbx}
\DeclareDatamodelEntrytypes{myarticle}
\DeclareDatamodelEntryfields[myarticle]{}
\end{filecontents}
%
\begin{filecontents}{mwe.bib}
@myarticle{mwe}
\end{filecontents}
%
\usepackage[utf8]{inputenc}
\usepackage{expl3}
\usepackage[bibstyle=mwe,datamodel=mwe]{biblatex}
\addbibresource{mwe.bib}
%
\begin{document}

Test \cite{mwe}.

\printbibliography

\end{document}
```

Running latex->biber->latex gives

```
! Undefined control sequence.
\abx@macro@mybibmacro -> \ExplSyntaxOn \seq 
                                            _new:N \l _foo_seq \ExplSyntaxOff
```

If you move the `expl3` code outside the bibmacro in the bbx file, no error appears, but if you move it inside the driver, there is

```
! Undefined control sequence.
\blx@bbx@myarticle ...ro {mwe} \ExplSyntaxOn \seq 
                                                  _new:N \l _foo_seq\ExplSyn...
```

**Comment by josephwright** [comment]
This is the usual issue that catcode changes have to go _outside_ of the macro they apply to
```
\ExplSyntaxOn
\newbibmacro*{mwe}{
\seq_new:N \l_foo_seq
}
\ExplSyntaxOff
```

(BTW, usually you don't want `\<thing>_new:N` inside a macro called more than once.)

**Comment by moewew** [comment]
Yeah, it's the same when you try to use `@` in a macro name with `\makeatletter...\makeatother`. The `\makeatletter...\makeatother` must be outside of the macro definition (for these intents and purposes both bibmacro definitions and driver definitions count as macro definitions, so they will exhibit the same behaviour, many other things `biblatex` does like field formats are also macro definitions). See https://tex.stackexchange.com/q/201348/35864.

```latex
% works
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear]{biblatex}

\makeatletter
\def\my@const{myconst}

\renewbibmacro*{begentry}{%
  \my@const
}

\newcommand*{\foo}{%
  \my@const
}
\makeatother

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite{sigfridsson}
ipsum \foo

\printbibliography
\end{document}
```
vs
```latex
% DOES NOT WORK
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear]{biblatex}

\makeatletter
\def\my@const{myconst}
\makeatother

\renewbibmacro*{begentry}{%
  \makeatletter
  \my@const
  \makeatother
}

\newcommand*{\foo}{%
  \makeatletter
  \my@const
  \makeatother
}


\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite{sigfridsson}
ipsum \foo

\printbibliography
\end{document}
```
---
With `\ExplSynatxOn...\ExplSyntaxOff` it's the same story
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear]{biblatex}

\ExplSyntaxOn
\tl_const:Nn \c_myconst_tl {myconst}

\renewbibmacro*{begentry}{%
  \tl_use:N \c_myconst_tl
}
\ExplSyntaxOff

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite{sigfridsson}

\printbibliography
\end{document}
```

----

I don't think this is anything 'we' (`biblatex`) can or want to do anything about.

**Comment by dollodart** [comment]
OK, it is clear that the entire macro definition has to be parsed in order to be stored, and so the control sequences which change the catcodes aren't active during the time the macro definition is being tokenized. This isn't a bug but a necessary tokenization to store the macro definition before it is expanded somewhere, given that TeX assigns category characters permanently at tokenization. From TeXbook p. 39: "Once a category code has been attached to a character token, the attachment is permanent. For example, if character `{' were suddenly declared to be of category 12 instead of category 1, the characters `{1' already inside token lists of TeX would still remain of category 1; only newly made lists would contain `{12' tokens."
