### ISSUE TITLE
brackets in names 

### ISSUE THREAD

**Issue by u-fischer** [plk/biblatex#1160]
The LaTeX companion recommends to write names which are used abbreviated in the original publication eg as `author = "D[onald] E. Knuth"`  and mentions that bibtex alphabetizes such names  as if the brackets were not there. 

For biber / biblatex this seems not to case. So I tried to force this alphabetizing by using `sortname` but this had the rather curious effect that biber views the author on one side as different (as can be seen from the extrayear) but on the other side as identical (as can be seen from the sorting.

Is that the intended behaviour? What would be the correct way to input such name differences?

~~~~
\documentclass{article}
\usepackage[style=authoryear,dashed]{biblatex}
\begin{filecontents}[overwrite]{test-crossref.bib}
 @misc{don1,
 author={D[onald] Knuth}, title= {a},year=2010,sortname={Donald Knuth}}

 @misc{don2,
 author={D[onald] Knuth}, title= {b},year=2010,sortname={Donald Knuth}
 }

 @misc{don3,
 author={Donald Knuth}, title= {a},year=2010}

 @misc{don4,
 author={Donald Knuth}, title= {b},year=2010}
\end{filecontents}
\addbibresource{test-crossref.bib}
\begin{document}
\cite{don1,don2,don3,don4}
\printbibliography
\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/127063774-bbdcb37f-24fb-4b8b-9e04-1b2dc672408d.png)

**Comment by moewew** [comment]
I guess it would be a nice idea to have an option (global, per-entry and per-name) that tells Biber to strip the brackets before sorting and unique... calculations. Would that help?

The question is if all or only matching square brackets should be stripped and if that should happen at all levels or only those at brace-level 0 (and if stripping only at brace-level 0 would be easy to implement given we will likely use RegExp, which isn't awfully good at nesting).

**Comment by u-fischer** [comment]
I don't really know what are the "citing traditions" here. That is if a bibliography should show the names are they are on the book title, or if it should try to unify names if possible. Personally it would be okay for me, if D[onald] and Donald are handled as two different names, but the sorting in the bibliography should then put all D[onald] together and not intermixed with some Donald

**Comment by moewew** [comment]
I'm also not too sure about conventions here.

I think I can confidently say that I have never seen square bracketed name completions in any of the bibliographies of papers or books I have read, but of course that samples only a very specific community. I also don't think I've ever seen this suggested (by style guides or the like) before, but I could be wrong. (In fact it always bugged me that `xampl.bib` did this.)

I for one would generally unify names if I'm reasonably confident I'm doing the right thing. But if I was not too sure, I might try to work around this issue by using a style with name initials.

----

Normally, `biblatex` treats `D[onald]` and `Donald` as different names with different sorting
```latex
\documentclass{article}
\usepackage[style=authoryear,dashed]{biblatex}
\begin{filecontents}[overwrite]{\jobname.bib}
@misc{don1,
author={D[onald] Knuth}, title={a}, year=2010,
}
@misc{don2,
author={D[onald] Knuth}, title={b}, year=2010,
}
@misc{don3,
author={Donald Knuth}, title={a}, year=2010,
}
@misc{don4,
author={Donald Knuth}, title={b}, year=2010,
}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}
\cite{don1,don2,don3,don4}
\printbibliography
\end{document}
```
In the example above, you force only the sorting of both to use `Donald`, but the rest (unique... features and dashed function) are still based on the actual contents of the `author` field, which is different. So this is what I expected from the input. But I can definitely see that it would be useful to have the brackets dropped for all features except the printed name.

**Comment by plk** [comment]
This is what `nosort` is for - a `biber` option that has to be in a config file - put this in `biber.conf`:

```
<?xml version="1.0" encoding="UTF-8" ?>
<config>
  <nosort>
    <option name="setnames" value="[[]]"/>
  </nosort>
</config>
```

To strip all square brackets out for sorting purposes. Remove the `sortname` fields and you get:

<img width="573" alt="Screenshot 2021-07-27 at 9 47 pm" src="https://user-images.githubusercontent.com/1220851/127218229-bbca5738-a008-4c27-b183-0ac9b618f863.png">

**Comment by moewew** [comment]
But shouldn't stripping `[` and `]` cause all entries to be sorted together (`Donald Knuth`) as if the bracketed entries had an explicit `sortname = {Donald Knuth},`.

In the following MWE the nosort declaration changes nothing
```latex
\documentclass{article}
\usepackage[style=authoryear,dashed]{biblatex}

\DeclareNosort{
  % strip prefixes like 'al-' when sorting names
  \nosort{setnames}{\regexp{\A\p{L}{2}\p{Pd}}}
  % strip some diacritics when sorting names
  \nosort{setnames}{\regexp{[\x{2bf}\x{2018}]}}
  % strip square brackets
  \nosort{setnames}{\regexp{\[\]}}
}

\begin{filecontents}[overwrite]{\jobname.bib}
@misc{don1,
author={D[onald] Knuth}, title={a}, year=2010,
}
@misc{don2,
author={D[onald] Knuth}, title={b}, year=2010,
}
@misc{don3,
author={Donald Knuth}, title={a}, year=2010,
}
@misc{don4,
author={Donald Knuth}, title={b}, year=2010,
}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}
\cite{don1,don2,don3,don4}
\printbibliography
\end{document}
```

----

That said, even if nosort did what I expected, sorting is only part of what we need. We also need to worry about name hashes and unique... features. Presumably one would want the `[]` stripped for those purposes as well.

**Comment by plk** [comment]
Well, the regexp would have to be:

```
\documentclass{article}
\usepackage[style=authoryear,dashed]{biblatex}

\DeclareNosort{
  % strip prefixes like 'al-' when sorting names
  \nosort{setnames}{\regexp{\A\p{L}{2}\p{Pd}}}
  % strip some diacritics when sorting names
  \nosort{setnames}{\regexp{[\x{2bf}\x{2018}]}}
  % strip square brackets
  \nosort{setnames}{\regexp{[\[\]]}}
}

\begin{filecontents}[overwrite]{\jobname.bib}
@misc{don1,
author={D[onald] Knuth}, title={a}, year=2011,
}
@misc{don2,
author={D[onald] Knuth}, title={b}, year=2012,
}
@misc{don3,
author={Donald Knuth}, title={a}, year=2009,
}
@misc{don4,
author={Donald Knuth}, title={b}, year=2010,
}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}
\cite{don1,don2,don3,don4}
\printbibliography
\end{document}
```

and the result is correct:

<img width="370" alt="Screenshot 2021-07-29 at 6 57 pm" src="https://user-images.githubusercontent.com/1220851/127533626-78103b57-cf3a-46e0-8885-987d584e4282.png">

but the issue isn't really sorting but rather that what should be displayed - stripping the brackets for sorting (or using `sortname`) doesn't strip the brackets in the bibliography itself and so it's not clear what should be displayed. For everything to be "Donald Knuth", a sourcemap would be required and that would deal with all of the issues but you'd arguably lose data.

**Comment by u-fischer** [comment]
> and the result is correct:

The result looks like I think it should look (imho if people use different versions of names it is okay to view the authors as different). I also think that the nosort looks like the right handle for this. 
But you changed the example. In your example all the years are distinct and so improve the sorting. If I set back the years to be equal I get again a mix sorting like in my first screenshot.

**Comment by moewew** [comment]
Ah, OK, the missing square brackets explain it.

Now
```latex
\documentclass{article}
\usepackage[style=authoryear,dashed]{biblatex}

\DeclareNosort{
  % strip prefixes like 'al-' when sorting names
  \nosort{setnames}{\regexp{\A\p{L}{2}\p{Pd}}}
  % strip some diacritics when sorting names
  \nosort{setnames}{\regexp{[\x{2bf}\x{2018}]}}
  % strip square brackets
  \nosort{setnames}{\regexp{[\[\]]}}
}

\begin{filecontents}{\jobname.bib}
@misc{don1,
  author={D[onald] Knuth}, title={a}, year=2010,
}
@misc{don2,
  author={D[onald] Knuth}, title={b}, year=2010,
}
@misc{don3,
  author={Donald Knuth}, title={a}, year=2010,
}
@misc{don4,
  author={Donald Knuth}, title={b}, year=2010,
}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}
\cite{don1,don2,don3,don4}
\printbibliography
\end{document}
```
does what I would expect.

I guess it would be nice to have a similar option for name uniqueness features, so that `D[onald] Knuth` and `Donald Knuth` both are treated like `Donald Knuth` for `uniquename` (and friends).

**Comment by plk** [comment]
As far as I can tell, we'd need an option like `nosort` that only effects `fullhash` and `uniquename`. However, thinking about this, I can't think of a situation when this new option wouldn't be the same as `nosort` as otherwise strange things could happen. So, how about renaming `nosort` to something more general (with backwards compat) and use the same regexps in all of this?

**Comment by plk** [comment]
Try adding this in the preamble of the example above with 2.17/3.17 DEV:

```
\DeclareNonamestring{
  % strip square brackets
  \nonamestring{author}{\regexp{[\[\]]}}
}
```

<img width="440" alt="Screenshot 2021-07-29 at 11 16 pm" src="https://user-images.githubusercontent.com/1220851/127567041-cbd9aa33-5124-46c3-8430-44e25eb4c3a5.png">

Of course the undashed author in the bibliography will just be the first one in the sorting order and so may or may not have the brackets in there, depending, but that's normal.

**Comment by u-fischer** [comment]
Sorry got distracted. 

~~~~
\DeclareNonamestring{
  % strip square brackets
  \nonamestring{author}{\regexp{[\[\]]}}
}
~~~~

looks fine, imho.
