### ISSUE TITLE
(Hyper)Link the field and entry names in biblatex documentation

### ISSUE THREAD

**Issue by Flowdalic** [plk/biblatex#1163]
The main biblatex documentation (biblatex.pdf) would be much better accessible if field and entry names would link to their description.

**Comment by moewew** [comment]
Yeah, the documentation could need some love. For this change I don't quite see the cost-benefit analysis come out on top, so I don't think *I* would want to put too much time into this, but if you are willing to give this a shot, by all means do!

**Comment by plk** [comment]
I'm going to close this as I can't see much benefit in linking fields and entry types as this isn't that useful to know about as you are looking at the docs: such things are style-dependent anyway.
