### ISSUE TITLE
The less-than character cannot be used in the ids field

### ISSUE THREAD

**Issue by janniklasrose** [plk/biblatex#1170]
The below MWE shows that the less-than (`<`) character cannot be used in the `ids` field.

```tex
%TEST.tex
\documentclass{memoir}
\usepackage[backend=biber]{biblatex}

\begin{filecontents}{TEST.bib}
@ARTICLE{A_gt_B,
  author = {A1},
  title = {Working reference},
  ids = {A>B},
}
@ARTICLE{A_lt_B,
  author = {A2},
  title = {Failing reference},
  ids = {A<B},
}
@ARTICLE{B<C,
  author = {B},
  title = {Working too},
  ids = {B_lt_C},
}
\end{filecontents}
\addbibresource{TEST.bib}

\begin{document}
  \cite{A_gt_B}
  \cite{A>B}
  \cite{A_lt_B}
  %\cite{A<B} % This will fail!
  \cite{B<C} % This works!?
  \cite{B_lt_C}
  \printbibliography
\end{document}
```

If I typeset this with the `\cite{A<B}` line uncommented and using `latexmk -pdflatex TEST.tex`, latexmk keeps alternating between `pdflatex` and `biber`. The latter reports

> TEST.bcf is malformed, last biblatex run probably failed. Deleted TEST.bbl

every time after the first run

I am using biber 2.16 and biblatex 3.16.

**Comment by moewew** [comment]
Thank you very much for reporting this. If I understand correctly this was just an oversight in the code dealing with writing the alias to the `.bcf`. That should be fixed in https://github.com/plk/biblatex/commit/6be69ce151caf6d7fbd4924e70ce22ba48f34c22.

**Comment by janniklasrose** [comment]
Awesome, thanks for looking into this so quickly. I just tested the latest `dev` version and can confirm that it works.
