### ISSUE TITLE
"Incomplete \iffalse" error with both `backref` option, `greek` `babel`'s language and `hyperref`

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#1175]
(Disclaimer: I'm not sure whether `biblatex` is the culprit or not.)

When both:
-  `backref` option is loaded,
- `greek` is one of the `babel`'s languages loaded (even if it isn't the main one),
- the `hyperref` package is loaded,

references in the `\frontmatter` of a document lead to the error:

```
! Incomplete \iffalse; all text was ignored after line 17.
<inserted text> 
                \fi
```

(As an _unsatisfactory_ workaround, one can use `\backtrackerfalse/\backtrackertrue`.)

```latex
\documentclass[greek,english]{book}
\usepackage{csquotes}
\usepackage[backref]{biblatex}
\usepackage{babel}
\usepackage{hyperref}

\addbibresource{biblatex-examples.bib}

\begin{document}
\frontmatter
% \backtrackerfalse
\autocite{knuth:ct}
% \backtrackertrue
\mainmatter
\autocite{knuth:ct}
\printbibliography
\end{document}
```

**Comment by jspitz** [comment]
See also https://tex.stackexchange.com/a/619885 for a related discussion.

**Comment by jspitz** [comment]
> See also https://tex.stackexchange.com/a/619885 for a related discussion.

BTW the workaround proposed here works in the case here as well:
```tex
\AtBeginDocument{\robustify\ensureascii}
```

**Comment by jspitz** [comment]
Also related: latex3/babel/issues/170

**Comment by jspitz** [comment]
This MWE demonstrates that the problem is not in `biblatex`, but rather in `babel(-greek)` or `hyperref`/`backref`:
```tex
\documentclass[greek,english]{book}
\usepackage{babel}
\usepackage[backref=page]{hyperref}

%Workaround:
%\usepackage{etoolbox}
%\AtBeginDocument{\robustify\ensureascii}

\begin{document}
	\frontmatter
	\cite{article-minimal}
	\mainmatter
	\cite{article-minimal}
	\bibliographystyle{plain}
	\bibliography{xampl}
\end{document}
```
