### ISSUE TITLE
Improve help text for `--configfile` option

### ISSUE THREAD

**Issue by alexreg** [plk/biblatex#1177]
Currently, the help text for `--configfile` is the following.

```
       --configfile|-g [file]
           Use file as the configuration file for "biber" instead of looking in the default locations (see
           "biber" PDF manual). In tool mode, (--tool) the biber-tool.conf installed with Biber is always used
           to set default options if a user-defined config file is not specified. Use the --tool-config option
           to view the location of the default tool mode config file--copy this file and edit it to your
           requirements for use with this option in tool mode.
```

This is slightly misleading, as implies that the default files needs to be copied if you want to override some settings, where in reality the default `biber-tool.conf` is always read, and a local configuration specified with this option will provide additional/overridding settings. There is really no need at all to copy it locally. It is only useful to consult to see what the default settings are.

Also, small side point: `file--copy` reads a bit awkwardly, and should probably be `file -- copy`, to best represent a dash (and elsewhere in the man page too, if it exists).

**Comment by plk** [comment]
Fixed in `biber` dev branch.

**Comment by alexreg** [comment]
Thanks! Shall we close this then?

**Comment by alexreg** [comment]
Also, re the default locations, I had to Google them. I couldn't find them in the PDF manual, though perhaps I'm blind. Seems like it would be better suited to specify them in the man page in any case.

**Comment by plk** [comment]
Do you mean the tool mode config? It says in that `--configfile` help in the man page that you can see the location with `--tool-config`.

**Comment by alexreg** [comment]
No, I mean where it looks by default. To quote,

`instead of looking in the default locations (see "biber" PDF manual)`

I don't even see it described in the PDF manual, but even if it is, it seems better suited to the man page, no?

**Comment by plk** [comment]
Implemented in biber DEV branch.
