### ISSUE TITLE
Preserve case when setting field value

### ISSUE THREAD

**Issue by alexreg** [plk/biblatex#1178]
I have a source map like the following.

```latex
\DeclareSourcemap{
	\maps[datatype = bibtex]{
		\map[overwrite, foreach = {journal, journaltitle}]{
			\step[fieldsource = \regexp{$MAPLOOP}, matchi = {^Philosophy\ of\ Science$}, final]
			\step[fieldset = \regexp{$MAPLOOP}, fieldvalue = {{Philos. Sci.}}]
			\step[fieldset = issn, fieldvalue = {1539-767X, 0031-8248}]
		}
	}
}
```

The issue is that unlike when `journaltitle` is set direclty to `{{Philos. Sci.}}` in the `.bib` file, this solution does not preserve the case of the journal title, even though it correctly replaces the journal title with its abbreviation, per the source map. Is this a bug in biblatex, or do I need to do something special to preserve the case of `journaltitle` here?

**Comment by plk** [comment]
Hmm, I can't see to reproduce this - the following:

```
\begin{filecontents*}[overwrite]{\jobname.bib}
@article{test,
  journaltitle  = {Philosophy of Science}
}
\end{filecontents*}
\documentclass{article}
\usepackage[sorting=none]{biblatex}
\addbibresource{\jobname.bib}
\DeclareSourcemap{
	\maps[datatype = bibtex]{
		\map[overwrite, foreach = {journal, journaltitle}]{
			\step[fieldsource = \regexp{$MAPLOOP}, matchi = {^Philosophy\ of\ Science$}, final]
			\step[fieldset = \regexp{$MAPLOOP}, fieldvalue = {{Philos. Sci.}}]
		}
	}
}
\begin{document}
\cite{test}
\printbibliography
\end{document}
```

Gives me:

<img width="220" alt="Screenshot 2021-09-18 at 4 16 pm" src="https://user-images.githubusercontent.com/1220851/133891813-1dd39ca9-414f-4adb-af62-c0e8ca4ae1be.png">

which looks correct?

**Comment by alexreg** [comment]
How odd. That seems to work. I wonder what I'm doing differently...

Thanks for your reply.

**Comment by alexreg** [comment]
Okay, it seems this a conflict that involves the *bath* style and the *cellspace* package both doing odd things with biblatex. Here's a MRE.

```latex
\begin{filecontents*}[overwrite]{\jobname.bib}
@article{test,
	journaltitle = {Philosophy of Science},
}
\end{filecontents*}
\documentclass{article}
\usepackage[
	backend = biber,
	style = bath,
]{biblatex}
\usepackage{cellspace}
\addbibresource{\jobname.bib}
\DeclareSourcemap{
	\maps[datatype = bibtex]{
		\map[overwrite, foreach = {journal, journaltitle}]{
			\step[fieldsource = \regexp{$MAPLOOP}, matchi = {^Philosophy\ of\ Science$}, final]
			\step[fieldset = \regexp{$MAPLOOP}, fieldvalue = {{Philos. Sci.}}]
		}
	}
}
\begin{document}
\cite{test}
\printbibliography
\end{document}
```

I'll investigate a bit more (unless the solution is obvious to you) and probably report the issue to one of those package maintainers. Thanks for your help in any case.

**Comment by moewew** [comment]
The problem isn't `cellspace` as such, it is `xkeyval` (which `cellspace` loads). The problem can be reproduced in
```latex
\documentclass{article}
\usepackage{biblatex}

\usepackage{xkeyval}

\DeclareFieldFormat{titlecase}{\MakeSentenceCase*{#1}}

\DeclareSourcemap{
  \maps[datatype = bibtex]{
    \map[overwrite, foreach = {journal, journaltitle}]{
      \step[fieldsource = \regexp{$MAPLOOP}, matchi = {^Philosophy\ of\ Science$}, final]
      \step[fieldset = \regexp{$MAPLOOP}, fieldvalue = {{Philos. Sci.}}]
    }
  }
}

\begin{filecontents*}[overwrite]{\jobname.bib}
@article{test,
	journaltitle = {Philosophy of Science},
}
\end{filecontents*}
\addbibresource{\jobname.bib}

\begin{document}
\cite{test}
\printbibliography
\end{document}
```

`xkeyval` changes the key-value parsing and apparently strips (more) curly braces in places where standard `keyval` would not do so (footnote 8 on p. 11 of the [`xkeyval`](http://mirrors.ctan.org/macros/latex/contrib/xkeyval/xkeyval.pdf) documentation mentions a difference to `xkeyval`, there is a also mention of this fact in §1.7 *Comparison* in the [`expkv` documentation](http://mirrors.ctan.org/macros/generic/expkv/expkv.pdf)).

Indeed without `xkeyval` the `.bcf` contains
```xml
    <bcf:maps datatype="bibtex" level="user">
      <bcf:map map_overwrite="1" map_foreach="journal, journaltitle">
        <bcf:map_step map_field_source="$MAPLOOP" map_matchi="^Philosophy\ of\ Science$" map_final="1"/>
        <bcf:map_step map_field_set="$MAPLOOP" map_field_value="{Philos. Sci.}"/>
      </bcf:map>
    </bcf:maps>
```
but with `xkeyval` it has
```xml
    <bcf:maps datatype="bibtex" level="user">
      <bcf:map map_overwrite="1" map_foreach="journal, journaltitle">
        <bcf:map_step map_field_source="$MAPLOOP" map_matchi="^Philosophy\ of\ Science$" map_final="1"/>
        <bcf:map_step map_field_set="$MAPLOOP" map_field_value="Philos. Sci."/>
      </bcf:map>
    </bcf:maps>
```
So the braces and with it the case protection are gone.

If you load `xkeyval` (or a package that loads it) you can try adding more curly braces
```latex
\documentclass{article}
\usepackage{biblatex}

\usepackage{xkeyval}

\DeclareFieldFormat{titlecase}{\MakeSentenceCase*{#1}}

\DeclareSourcemap{
  \maps[datatype = bibtex]{
    \map[overwrite, foreach = {journal, journaltitle}]{
      \step[fieldsource = \regexp{$MAPLOOP}, matchi = {^Philosophy\ of\ Science$}, final]
      \step[fieldset = \regexp{$MAPLOOP}, fieldvalue = {{{Philos. Sci.}}}]
    }
  }
}

\begin{filecontents*}[overwrite]{\jobname.bib}
@article{test,
	journaltitle = {Philosophy of Science},
}
\end{filecontents*}
\addbibresource{\jobname.bib}

\begin{document}
\cite{test}
\printbibliography
\end{document}
```
works.


----

Please include a fully compilable example document that reproduces the issue you are asking about from the start in future questions. It saves us a lot of back-and-forth if the problem cannot actually be reproduced with standard settings (as was the case here).

**Comment by alexreg** [comment]
Yes, seems you're quite right. That solution of extra quoting works, thank you.
