### ISSUE TITLE
Wrong placement of comma in ieee style 

### ISSUE THREAD

**Issue by kayvax** [plk/biblatex#1179]
Hello everyone,
I have found that when using biblatex with ieee styling I get wrong placement of a comma after the title of bibliography item
![image](https://user-images.githubusercontent.com/6639788/134036989-726fa5db-9e1f-42c8-a2b6-572eaa5e9ae3.png)
Comma is consistently inserted in the title quotes.
I am using biblatex with 

`biber version: 2.15 `

```
pdflatex --version
pdfTeX 3.141592653-2.6-1.40.22 (TeX Live 2021/Arch Linux)
kpathsea version 6.3.3
Copyright 2021 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.03
```
If you need more info about my setup I will provide it.

**Comment by josephwright** [comment]
This issue should be reported against josephwright/biblatex-ieee, but it's going to be 'invalid' there: the IEEE style uses US-style punctuation, and that puts commas inside quotes in this situation.

**Comment by kayvax** [comment]
Thank you for clarifying. I was not aware about that.
