### ISSUE TITLE
"nottype=phdthesis" has no effect

### ISSUE THREAD

**Issue by rolfn** [plk/biblatex#1180]
In the following example document, `nottype=phdthesis` has no effect. The dissertation (label `XXX3`) appears in both partial bibliographies.
```latex
\listfiles
\begin{filecontents*}[overwrite]{\jobname.bib}
@article{XXX1,
  author       = {Author1},
  title        = {Article},
  journaltitle = {Journal},
  date         = {1966}
}
@book{XXX2,
  author       = {Author2},
  title        = {Book},
  date         = {1997}
}
@phdthesis{XXX3,
  author       = {Author3},
  title        = {Dissertation},
  institution  = {University},
  date         = {1994}
}
\end{filecontents*}
\documentclass[english]{article}
\usepackage{babel,csquotes}
\usepackage[style=numeric,bibencoding=utf8,backend=biber]{biblatex}

\addbibresource{\jobname.bib}

\begin{document}

\nocite{*}

\printbibliography[nottype=book,nottype=phdthesis,title={Articles only}]
\printbibliography[nottype=article,title={No articles}]  

\end{document}
```
I am using a recent "TeXLive" installation:
```
biber version: 2.16
biblatex.sty:  2020/12/31 v3.16
```
Greetings from Berlin

Rolf

**Comment by sieversMartin** [comment]
If you change `phdthesis` to `thesis` it works. This is probably due to the internal mapping of entry types.

**Comment by rolfn** [comment]
Yes you are right. But it's still a bit confusing ...

**Comment by rolfn** [comment]
I understand. What do you think of the following addition to §2.1.2?

> Note that this type of alias cannot be used directly for filtering in `\printbibliography`. You have to use the target entry type (e.g. "thesis" instead of "phdthesis") .

**Comment by moewew** [comment]
How about https://github.com/plk/biblatex/commit/a90d468728f42041ceca6c71f6c691da7c5b891d?

**Comment by rolfn** [comment]
It is fine that way.
