### ISSUE TITLE
@INCOLLECTION: Missing mandatory field 'editor' -- why?

### ISSUE THREAD

**Issue by rolfn** [plk/biblatex#1181]
In the following example I get this warning:
```
WARN - Datamodel: Entry 'XXX:2021' (xxx.bib): Missing mandatory field 'editor'
```

```latex
\listfiles
\begin{filecontents*}[overwrite]{\jobname.bib}
@INCOLLECTION{XXX:2021,
  author       = {Silie, Peter},
  title        = {Das Liebesleben der Maikäfer},
  date         = {2021},
  booktitle    = {Die lieben Käfer}
}
\end{filecontents*}
\documentclass[english]{article}
\usepackage{babel,csquotes}
\usepackage[style=numeric,bibencoding=utf8,backend=biber]{biblatex}

\addbibresource{\jobname.bib}

\begin{document}
\nocite{*}
\printbibliography 
\end{document}
```

The documentation (page 10) says for `@incollection`:
> Required fields: author, title, booktitle, year/date

Why is  field 'editor' missing?

**Comment by moewew** [comment]
Given that `@incollection` is really 'in a `@collection`' and `@collection` has a mandatory `editor`, `@incollection` should probably also have a mandatory `editor`. Thanks for the heads-up. Added in https://github.com/plk/biblatex/commit/b22e2e77adcaf45fd36f3e240709877f2c59eb91.

Note that the classification as required/optional in the documentation has no direct implication for styles. In fact styles don't know about this classification and the lists in the manual are only mirrored in the data validation code for Biber, which apart from printing warnings to users if so desired serves no additional purpose. See also https://github.com/plk/biblatex/issues/837#issuecomment-435201821 and https://github.com/plk/biblatex/issues/833#issuecomment-431573900 as well as https://tex.stackexchange.com/q/563609/35864.

**Comment by rolfn** [comment]
I understand. Thank you.

**Comment by moewew** [comment]
That said, [`btxdoc`](http://mirrors.ctan.org/biblio/bibtex/base/btxdoc.pdf) does not have `editor` as a required field for `@incollection`. I'm guessing most of the required fields were taken from there originally, so that might explain the omission.
