### ISSUE TITLE
Two references with consecutive serial numbers that should be connected are but not connected with "-"?

### ISSUE THREAD

**Issue by fu123456** [plk/biblatex#1194]
My system is Manjaro (Archlinux), texlive2019, my biblatex config is
```tex
\usepackage[backend=biber,style=gb7714-2015,gbfieldtype=true,gbpub=false,gbnamefmt=lowercase]{biblatex}
```
In the final pdf file generated by tex, I want to be that [12-13] instead of [12, 13], but actually, I got [12,13] for citing references.
The screenshot images are as follows
![biblatex_issue1](https://user-images.githubusercontent.com/22411577/141645510-35245ded-dc0c-47d3-9d62-88ddb50c877f.png)
:
![biblatex_issue2](https://user-images.githubusercontent.com/22411577/141645512-4e3f175f-21c4-4196-8bd4-3084b5f786d6.png)

**Comment by moewew** [comment]
`style=gb7714-2015,` is not part of core `biblatex` and thus neither maintained nor developed here. As far as I can tell it is part of `biblatex-gb7714-2015`, for which issues can be reported at https://github.com/hushidong/biblatex-gb7714-2015.

**Comment by fu123456** [comment]
Thanks.
