### ISSUE TITLE
biblatex messes up \includeonly mechanism of LaTeX

### ISSUE THREAD

**Issue by u-fischer** [plk/biblatex#1196]
LaTeX tries hard to keep track of counters for includes so that a document can be compiled with `\includeonly`. The  aux-files of the chapters of the following document also contains the values for refsection and refsegment and so normally this should work for them too:

~~~~
\@setckpt{chap1}{
\setcounter{page}{3}
\setcounter{equation}{0}
...
\setcounter{refsection}{1}
\setcounter{refsegment}{0}
....
}
~~~~

But in `\blx@refsection@i` biblatex then uses a TeX count `\blx@maxsection` to reset the `refsection` counter.:

~~~~
\def\blx@refsection@i[#1]{%
  \endgroup
  \global\advance\blx@maxsection\@ne
  \global\c@refsection\blx@maxsection
~~~~

 And a TeX count is  not part of the system and so citations get quite messed up as soon as one use `\includeonly`:

~~~~
\begin{filecontents}[overwrite]{chap1.tex}
\chapter{doody}

refsection: \therefsection

chapter: \thechapter

\cite{doody}

\printbibliography
\end{filecontents}


\begin{filecontents}[overwrite]{chap2.tex}
\chapter{aksin}

refsection: \therefsection

chapter: \thechapter

\cite{aksin}

\printbibliography
\end{filecontents}

\documentclass{report}

\usepackage[refsection=chapter,style=authoryear]{biblatex}
\addbibresource{biblatex-examples.bib}
%\includeonly{chap2} %activate that

\begin{document}

\include{chap1}

%\makeatletter \global\advance \blx@maxsection by 1 \makeatother
\include{chap2}

\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/144837393-8b375d27-5407-4dcb-9014-f467a09913f8.png)

**Comment by moewew** [comment]
Let me know if https://github.com/plk/biblatex/commit/cd27c0841ad83326d1c6a5b36ebab830020a3506, https://github.com/plk/biblatex/commit/c8085f60e67523705687c13f22a0674831c346eb and https://github.com/plk/biblatex/commit/d4cdfbef544677309be9ec9f605d522a7a248cdb look any better.

**Comment by u-fischer** [comment]
Sorry I nearly forget that. From the code it looks good, but I couldn't test it yet.

**Comment by moewew** [comment]
Cool. If you find any issues if/when you get around to testing the new version, just let us know here.

**Comment by moewew** [comment]
Urgh! Unfortunately, the MWE errors also with v3.17. I shall have to take a look at this again.

**Comment by u-fischer** [comment]
The fix I suggest here https://tex.stackexchange.com/a/634159/2388 should resolve that.

But I also think it would be good to check generally the use of counters and consider if they will work in an includeonly situation (I see a few \advance, not everyone need to be a problem but without looking it is difficult to say).

**Comment by moewew** [comment]
The example from https://tex.stackexchange.com/q/634143/35864 compiles fine with https://github.com/plk/biblatex/commit/86a98becfe2debcc5097aa5b0e51dd7b6839b150, where I moved back to TeX counts for counts that don't need to survive `\includeonly`. But I don't know if that was the only issue with the new code, so some more tests would be appreciated.
