### ISSUE TITLE
With `defernumbers`, wrong numeric labels in case of citation `\AtEndDocument`

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#1197]
In the following MCE, virtually two references are cited at the end of the document:

1. the first one is cited manually,
2. the second one is cited thanks to the `\AtEndDocument` hook (relying on `\AtEndDocument` or friends — such as `\AddToHook{enddocument}` — is mandatory in the case of a LaTeX class requiring a given citation automatically added at the end of the document).
```latex
\documentclass{article}
%
\usepackage[defernumbers]{biblatex}%
\addbibresource{biblatex-examples.bib}
%
\begin{document}
\printbibliography
\autocite{knuth:ct:a}%
% \AtEndDocument{\autocite{knuth:ct:b}}
\end{document}
```
Currently, the MCE works as expected but, as soon as the penultimate line is commented out, all the numeric labels are "0".

Several years ago, [I reported the very same problem on TeX.SE](https://tex.stackexchange.com/q/240318/18401) but the workarounds provided by Ulrike don't work anymore.

**Comment by dbitouze** [comment]
Okay, I found a solution based on `\AddToHook{env/document/end}`:
```latex
\documentclass{article}
%
\usepackage[defernumbers]{biblatex}%
\addbibresource{biblatex-examples.bib}
\AddToHook{env/document/end}{\autocite{knuth:ct:b}}
%
\begin{document}
\printbibliography
\autocite{knuth:ct:a}%
\end{document}
```

**Comment by moewew** [comment]
You need to make sure that your top-level code is executed before the `biblatex` stuff, e.g. with
```latex
\documentclass{article}
\usepackage[defernumbers]{biblatex}%
\addbibresource{biblatex-examples.bib}

\DeclareHookRule{enddocument}{citations}{before}{biblatex}

\begin{document}
\printbibliography
\autocite{knuth:ct:a}%
\AtEndDocument[citations]{\autocite{knuth:ct:b}}
\end{document}
```

-----

Looking at `source2e` it seems that `enddocument/afterlastpage` would be the more natural hook for `biblatex` to use instead of plain old `\AtEndDocument`/`enddocument`, so with https://github.com/plk/biblatex/commit/d031f347834c47866dd2ef70d6de8303f4fcd55e

```latex
\documentclass{article}
\usepackage[defernumbers]{biblatex}%
\addbibresource{biblatex-examples.bib}

\begin{document}
\printbibliography
\autocite{knuth:ct:a}%
\AtEndDocument{\autocite{knuth:ct:b}}
\end{document}
```

should work provided your LaTeX is new enough.

**Comment by dbitouze** [comment]
These two solutions work perfectly, and much better than mine! :smile:
