### ISSUE TITLE
Package biblatex Error: Language 'romanian' not found

### ISSUE THREAD

**Issue by TracyRage** [plk/biblatex#1200]
Hi everyone! 

The other day, I was trying to generate a document with custom romanian bibliography (RStudio). Specifically, I wanted to replace the _et al_ syntagm with _și colab_. Here is the preamble:

`title: other
documentclass: report
output: 
  pdf_document:
    latex_engine: xelatex
    number_sections: true
bibliography: references.bib
papersize: letter
toc: true
margin-top: 2cm
margin-bottom: 2cm
margin-left: 2.54cm
margin-right: 2cm
fontsize: 12pt
linestretch: 1.5
indent: true
header-includes:
- \usepackage{times}
- \usepackage{indentfirst}
- \usepackage[utf8]{inputenc}
- \usepackage[romanian]{babel}
- \usepackage{csquotes}
- \usepackage[backend=biber]{biblatex}
- \DefineBibliographyStrings{romanian}{andothers = {si colab}}
- \usepackage{fancyhdr}
- \pagestyle{fancy}`

However, I get this error:
`! Package biblatex Error: Language 'romanian' not found.`

Any ideas?

**Comment by moewew** [comment]
If you are using the current release version of `biblatex`, that is expected.

Support for Romanian was only added recently to the `dev` version and not yet to a release version.

**Comment by moewew** [comment]
If you need to compile a document with Romanian *now*, grab `romanian.lbx` from https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/lbx/romanian.lbx, drop it into your `.tex` direcory and add the `\NewBibliographyString` lines from the example below
```latex
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[romanian]{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear]{biblatex}

\NewBibliographyString{
  langromanian,
  summerN,winterN,autumnN,springN,
  summerS,winterS,autumnS,springS,
  Q1,Q2,Q3,Q4,S1,S2,
}
\DefineBibliographyStrings{romanian}{andothers = {si colab}}

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite{aksin}

\printbibliography
\end{document}
```

**Comment by TracyRage** [comment]
thanks, guys! like clockwork
