### ISSUE TITLE
Command \c@blx@sectionciteorder@1 already defined

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#1201]
The following MCE:
```latex
\documentclass{article}
%
\usepackage{biblatex}
\addbibresource{biblatex-examples.bib}
%
\begin{document}
\tableofcontents
\newrefsection%
\section{About \citeauthor{knuth:ct:a}}
\printbibliography
\end{document}
```
used to work nicely with:

- `biblatex`    2020/12/31 v3.16,
- `biber` 2.16,

but that's not the case with:

- `biblatex`  2022/01/16 v3.17,
- `biber` 2.17 (beta),

the error message being:
```
! LaTeX Error: Command \c@blx@sectionciteorder@1 already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.11 \section
             {About \citeauthor{knuth:ct:a}}
?
```

**Comment by moewew** [comment]
Thanks for reporting the error. Please have a look at https://github.com/plk/biblatex/commit/10e576925541f5ce73cb3a650bf25d8c8424d0f2.

**Comment by dbitouze** [comment]
> Thanks for reporting the error.

You're welcome!

>  Please have a look at [10e5769](https://github.com/plk/biblatex/commit/10e576925541f5ce73cb3a650bf25d8c8424d0f2).

It looks like this bug is fixed: thanks!
