### ISSUE TITLE
Strange error when using defernumbers=true and resetnumbers=true

### ISSUE THREAD

**Issue by gvdgdo** [plk/biblatex#1203]
I have a file with multiple bibliographies, each using `numeric` format and resetting the number to 1. The bibliographies use some filters and other conditions to select the entries to be printed in each bibliography.  When the first bibliography contains the command `resetnumbers=true` the compilation produces the following error. 

```
! Missing number, treated as zero.
<to be read again> 
                   t
l.52   ]
        
? 
! Undefined control sequence.
\GenericError  ...                                
                                                    #4  \errhelp \@err@     ...
l.52   ]
        
? 
! Undefined control sequence.
\GenericError  ...                                
                                                  \let \@err@               ...
l.52   ]
        
? 
! Undefined control sequence.
\GenericError  ...                                
                                                  \@empty \def \MessageBreak...
l.52   ]
        
? 
! Undefined control sequence.
\GenericError  ...                                
                                                     \endgroup 
l.52   ]
        
? 
! Undefined control sequence.
\GenericError  ...                                
                                                    #4  \errhelp \@err@     ...
l.52   ]
        
? 
! Undefined control sequence.
\GenericError  ...                                
                                                  \let \@err@               ...
l.52   ]
        
? 
! Undefined control sequence.
\GenericError  ...                                
                                                  \@empty \def \MessageBreak...
l.52   ]
        
? 
! Undefined control sequence.
\GenericError  ...                                
                                                     \endgroup 
l.52   ]
        
? 
```

The error disappears when `resetnumbers` is commented/removed.

Here is a (possibly non) minimal working example showing the issue. 

```
\documentclass{article}
\usepackage[
  style=numeric,
  defernumbers=true
  ]
{biblatex}

\addbibresource{biblatex-examples.bib}

\DeclareBibliographyCategory{test}
\DeclareBibliographyCategory{editorial}
\DeclareBibliographyCategory{skip}

\defbibfilter{book}{
  type=book or
  type=proceedings or
  category=editorial
}

\addtocategory{test}{
 springer
}

\addtocategory{editorial}{
 pines
}

\addtocategory{skip}{
 worman
}

\listfiles
\begin{document}
Test

%Books
\nocite{augustine}
\nocite{worman}

%incollection
\nocite{pines}

%article
\nocite{springer}
\nocite{yoon}

\printbibliography[
  filter=book,
  title={Books and Editorial Works},
  notcategory=test,
  resetnumbers=true] %comment this line to avoid the error

\printbibliography[
  type=article,
  resetnumbers=true,
  title={Articles},
  notcategory=skip]

\end{document}
``` 

Categories and filters seem to be essential to reproduce the error (though, did not investigate any further).

Here is the output to `\listfiles`

``` 
article.cls    2021/10/04 v1.4n Standard LaTeX document class
  size10.clo    2021/10/04 v1.4n Standard LaTeX file (size option)
biblatex.sty    2022/02/02 v3.17 programmable bibliographies (PK/MW)
pdftexcmds.sty    2020-06-27 v0.33 Utility functions of pdfTeX for LuaTeX (HO)
infwarerr.sty    2019/12/03 v1.5 Providing info/warning/error messages (HO)
   iftex.sty    2020/03/06 v1.0d TeX engine tests
 ltxcmds.sty    2020-05-10 v1.25 LaTeX kernel commands for general use (HO)
etoolbox.sty    2020/10/05 v2.5k e-TeX tools for LaTeX (JAW)
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
kvoptions.sty    2020-10-07 v3.14 Key value format for package options (HO)
kvsetkeys.sty    2019/12/15 v1.18 Key value parser (HO)
  logreq.sty    2010/08/04 v1.0 xml request logger
  logreq.def    2010/08/04 v1.0 logreq spec v1.0
  ifthen.sty    2020/11/24 v1.1c Standard LaTeX ifthen package (DPC)
     url.sty    2013/09/16  ver 3.4  Verb mode for urls, etc.
  blx-dm.def    2022/02/02 v3.17 biblatex localization (PK/MW)
blx-compat.def    2022/02/02 v3.17 biblatex compatibility (PK/MW)
biblatex.def    2022/02/02 v3.17 biblatex compatibility (PK/MW)
standard.bbx    2022/02/02 v3.17 biblatex bibliography style (PK/MW)
 numeric.bbx    2022/02/02 v3.17 biblatex bibliography style (PK/MW)
 numeric.cbx    2022/02/02 v3.17 biblatex citation style (PK/MW)
biblatex.cfg    
   expl3.sty    2022-02-05 L3 programming layer (loader) 
l3backend-pdftex.def    2022-01-12 L3 backend support: PDF output (pdfTeX)
blx-case-expl3.sty    2022/02/02 v3.17 expl3 case changing code for biblatex
  xparse.sty    2022-01-12 L3 Experimental document command parser
 english.lbx    2022/02/02 v3.17 biblatex localization (PK/MW)
   debug.bbl
```

**Comment by moewew** [comment]
Thanks for reporting this issue.

Unfortunately (or fortunately), I did not manage to reproduce the error with the MWE shown above. (See e.g. [Texlive.net](https://texlive.net/run?%5Cdocumentclass%7Barticle%7D%0A%5Cusepackage%5B%0A%20%20style=numeric,%0A%20%20defernumbers=true%0A%20%20%5D%0A%7Bbiblatex%7D%0A%0A%5Caddbibresource%7Bbiblatex-examples.bib%7D%0A%0A%5CDeclareBibliographyCategory%7Btest%7D%0A%5CDeclareBibliographyCategory%7Beditorial%7D%0A%5CDeclareBibliographyCategory%7Bskip%7D%0A%0A%5Cdefbibfilter%7Bbook%7D%7B%0A%20%20type=book%20or%0A%20%20type=proceedings%20or%0A%20%20category=editorial%0A%7D%0A%0A%5Caddtocategory%7Btest%7D%7B%0A%20springer%0A%7D%0A%0A%5Caddtocategory%7Beditorial%7D%7B%0A%20pines%0A%7D%0A%0A%5Caddtocategory%7Bskip%7D%7B%0A%20worman%0A%7D%0A%0A%5Clistfiles%0A%5Cbegin%7Bdocument%7D%0ATest%0A%0A%25Books%0A%5Cnocite%7Baugustine%7D%0A%5Cnocite%7Bworman%7D%0A%0A%25incollection%0A%5Cnocite%7Bpines%7D%0A%0A%25article%0A%5Cnocite%7Bspringer%7D%0A%5Cnocite%7Byoon%7D%0A%0A%5Cprintbibliography%5B%0A%20%20filter=book,%0A%20%20title=%7BBooks%20and%20Editorial%20Works%7D,%0A%20%20notcategory=test,%0A%20%20resetnumbers=true%5D%20%25comment%20this%20line%20to%20avoid%20the%20error%0A%0A%5Cprintbibliography%5B%0A%20%20type=article,%0A%20%20resetnumbers=true,%0A%20%20title=%7BArticles%7D,%0A%20%20notcategory=skip%5D%0A%0A%5Cend%7Bdocument%7D)).

Can you please verify that this exact example reproduces the error and maybe post the complete `.log` file (e.g. to https://gist.github.com/)?

**Comment by gvdgdo** [comment]
Yes,  it is the same example that produces the error. 

The log is at 

https://gist.github.com/gvdgdo/8d71253799fdd3040d3f6c1b4cc61602 <https://gist.github.com/gvdgdo/8d71253799fdd3040d3f6c1b4cc61602>

What was strange was my file worked properly two weeks ago, and not sure I did any update to my TeX installation since then.

**Comment by moewew** [comment]
Are you absolutely sure this is the MWE you posted? I still cannot reproduce any error. The `.log` suggests a corrupted `.aux` file. Please run LaTeX only once in a new, empty directory and post the resulting `.log` (which will not reference the `.aux`).

I can, however, reproduce errors of the form you initially quoted if I take your earlier example (from before the edits) with the U+FFFD characters in line 51. So maybe that is your issue?

```latex
\documentclass{article}
\usepackage[
  style=numeric,
  defernumbers=true
  ]
{biblatex}

\addbibresource{biblatex-examples.bib}

\DeclareBibliographyCategory{test}
\DeclareBibliographyCategory{editorial}
\DeclareBibliographyCategory{skip}

\defbibfilter{book}{
  type=book or
  type=proceedings or
  category=editorial
}

\addtocategory{test}{
 springer
}

\addtocategory{editorial}{
 pines
}

\addtocategory{skip}{
 worman
}

\listfiles
\begin{document}
Test

%Books
\nocite{augustine}
\nocite{worman}

%incollection
\nocite{pines}

%article
\nocite{springer}
\nocite{yoon}

\printbibliography[
  filter=book,
  title={Books and Editorial Works},
  notcategory=test,
  resetnumbers=true��
  ]

\printbibliography[
  type=article,
  resetnumbers=true,
  title={Articles},
  notcategory=skip]

\end{document}
```

**Comment by moewew** [comment]
Just to be on the safe side, I tested the (edited) MWE (without the U+FFFD) on Overleaf (which runs `biblatex` 3.16) and got the same output as on my local installation with `biblatex` v3.17. (In fact I checked with two local installs: one with MikTeX on Windows and one with TeX live on Ubuntu.)

**Comment by gvdgdo** [comment]
Thanks for your help. 

The problem is the U+FFFD character. 

So, the issue can be closed.
