### ISSUE TITLE
Missing journal after entryclone

### ISSUE THREAD

**Issue by ma-rapp** [plk/biblatex#1204]
For a split bibliography (similar to https://tex.stackexchange.com/questions/228310/biblatex-numbering-of-overlapping-bibliographies/236784#236784), I am copying the bib entries using entryclone. However, this results in a missing journal information.

**MWE**

```latex
\documentclass{article}

\usepackage[backend=biber]{biblatex}

\begin{filecontents}{\jobname.bib}
@article{test,
    Author = {Some Body},
    Title = {Great Work},
    journal = {Some Journal},
    Year = {2020},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\DeclareSourcemap{
    \maps[datatype=bibtex]{
        \map{
            \step[fieldsource=entrykey, match=\regexp{(.*)}, final]
            \step[entryclone={copy-$1}]
        }
    }
}

\begin{document}

\cite{copy-test}
\cite{test}

\printbibliography

\end{document}
```

Output:
![image](https://user-images.githubusercontent.com/17711336/154075125-7c7862eb-d99a-4572-8624-e8e913ce97e8.png)

**Versions**
I am using an up-to-date MikTeX with biber-windows-x64 2.17 and biblatex 3.17

**Comment by ma-rapp** [comment]
also reproducible on [TeXLive.net](https://texlive.net/run?%5Cdocumentclass%7Barticle%7D%0A%0A%5Cusepackage%5Bbackend=biber%5D%7Bbiblatex%7D%0A%0A%5Cbegin%7Bfilecontents%7D%7B%5Cjobname.bib%7D%0A@article%7Btest,%0A%20%20%20%20Author%20=%20%7BSome%20Body%7D,%0A%20%20%20%20Title%20=%20%7BGreat%20Work%7D,%0A%20%20%20%20journal%20=%20%7BSome%20Journal%7D,%0A%20%20%20%20Year%20=%20%7B2020%7D,%0A%7D%0A%5Cend%7Bfilecontents%7D%0A%5Caddbibresource%7B%5Cjobname.bib%7D%0A%0A%5CDeclareSourcemap%7B%0A%20%20%20%20%5Cmaps%5Bdatatype=bibtex%5D%7B%0A%20%20%20%20%20%20%20%20%5Cmap%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%5Cstep%5Bfieldsource=entrykey,%20match=%5Cregexp%7B(.*)%7D,%20final%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%5Cstep%5Bentryclone=%7Bcopy-$1%7D%5D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D%0A%0A%5Cbegin%7Bdocument%7D%0A%0A%5Ccite%7Bcopy-test%7D%0A%5Ccite%7Btest%7D%0A%0A%5Cprintbibliography%0A%0A%5Cend%7Bdocument%7D)

**Comment by moewew** [comment]
`journal` is a bit tricky. Technically the field does not exist in the data model. `journal` is remapped to `journaltitle` by the driver sourcemap. Because the driver sourcemap is executed after user-defined sourcemaps, your entry is copied before `journal` is mapped to `journaltitle` and the unknown field is dropped.

You can either use `journaltitle`
```latex
\documentclass{article}

\usepackage[backend=biber]{biblatex}

\begin{filecontents}{\jobname.bib}
@article{test,
  author       = {Some Body},
  title        = {Great Work},
  journaltitle = {Some Journal},
  year         = {2020},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\DeclareSourcemap{
  \maps[datatype=bibtex]{
    \map{
      \step[fieldsource=entrykey, match=\regexp{(.*)}, final]
      \step[entryclone={copy-$1}]
    }
  }
}

\begin{document}
\cite{copy-test,test}
\printbibliography
\end{document}
```
or explicitly execute the mapping before you go about copying the entry
```latex
\documentclass{article}

\usepackage[backend=biber]{biblatex}

\begin{filecontents}{\jobname.bib}
@article{test,
  author  = {Some Body},
  title   = {Great Work},
  journal = {Some Journal},
  year    = {2020},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\DeclareSourcemap{
  \maps[datatype=bibtex]{
    % copied from \DeclareDriverSourcemap in biblatex.def
    \map{
      \step[typesource=conference, typetarget=inproceedings]
      \step[typesource=electronic, typetarget=online]
      \step[typesource=www,        typetarget=online]
    }
    \map{
      \step[typesource=mastersthesis, typetarget=thesis, final]
      \step[fieldset=type,            fieldvalue=mathesis]
    }
    \map{
      \step[typesource=phdthesis, typetarget=thesis, final]
      \step[fieldset=type,        fieldvalue=phdthesis]
    }
    \map{
      \step[typesource=techreport, typetarget=report, final]
      \step[fieldset=type,         fieldvalue=techreport]
    }
    \map{
      \step[fieldsource=hyphenation,   fieldtarget=langid]
      \step[fieldsource=address,       fieldtarget=location]
      \step[fieldsource=school,        fieldtarget=institution]
      \step[fieldsource=annote,        fieldtarget=annotation]
      \step[fieldsource=archiveprefix, fieldtarget=eprinttype]
      \step[fieldsource=journal,       fieldtarget=journaltitle]
      \step[fieldsource=primaryclass,  fieldtarget=eprintclass]
      \step[fieldsource=key,           fieldtarget=sortkey]
      \step[fieldsource=pdf,           fieldtarget=file]
    }
    \map{
      \step[fieldsource=entrykey, match=\regexp{(.*)}, final]
      \step[entryclone={copy-$1}]
    }
  }
}

\begin{document}
\cite{copy-test,test}
\printbibliography
\end{document}
```

**Comment by ma-rapp** [comment]
Thanks a lot for the fast reply. Applying your suggested mapping steps resolved my issue.
