### ISSUE TITLE
biblatex 3.17 problems with addtocontents

### ISSUE THREAD

**Issue by fjbarthold** [plk/biblatex#1205]
After updating to biblatex 3.17, an error message occurred, i.e.

! Undefined control sequence.
<argument> \blx@err@patch 
                          {\addtocontents }
l.637   {\blx@err@patch{\addtocontents}}

The error vanished after commenting out the following lines in biblatex.sty
%\patchcmd\addtocontents
%  {\let\glossary\@gobble}
%  {\let\glossary\@gobble
%   \blx@contentssafe@citecommands}
%  {}
%  {\blx@err@patch{\addtocontents}}

Can you please comment on this issue.

**Comment by moewew** [comment]
Can you share a short example document that reproduces this error (ideally with as little code as possible), please? I have been using `biblatex` 3.17 in a variety of documents over the last weeks and have not encountered this problem yet.

The following document for example compiles fine for me
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear]{biblatex}

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite{sigfridsson}

\printbibliography
\end{document}
```

**Comment by fjbarthold** [comment]
Thank you for the quick reply.
Your example compiles fine for me, too. Maybe, any other package generates a side effect. Thus, I should trace this (not yet known) package. This might take a while.

**Comment by fjbarthold** [comment]
The package newclude.sty generates the problem, i.e. please add

\usepackage{newclude}

into your example to generate an error.

The issue is fixed for me by dropping newclude.sty from the list of packages.

**Comment by fjbarthold** [comment]
The newclude-package has a nice feature that \include can be nested.
It might be helpful to other users as well to guarantee the coexistence of biblatex and newclude.

**Comment by moewew** [comment]
I can reproduce the problem and will have a look at it. For now I notice that a document with `biblatex` and `newclude` compiles if `newclude` is loaded after `biblatex` (though I haven't checked if the features of `biblatex` for which it needs to patch `\addtocontents` work properly).

**Comment by moewew** [comment]
https://github.com/plk/biblatex/commit/d760385a2eb621d86177548772868cbf31ba663b attempts to fix this. I really hope there are not that many packages overwriting the kernel definition of `\addtocontents`. Otherwise we'll end up having to write patches for all of those. Maintaining them is going to be pretty painful.

**Comment by u-fischer** [comment]
> [d760385](https://github.com/plk/biblatex/commit/d760385a2eb621d86177548772868cbf31ba663b) attempts to fix this. I really hope there are not that many packages overwriting the kernel definition of `\addtocontents`. Otherwise we'll end up having to write patches for all of those. Maintaining them is going to be pretty painful.

Imho your fix overcomplicates. For the patching you don't need a long string, you can simply prepend to `\let\label` or even to the first `\let`:

~~~~
\documentclass{article}
\usepackage{etoolbox}
\makeatletter
\patchcmd\addtocontents
    {\let}
    {\blx@contentssafe@citecommands
     \let}
    {}
    {\togglefalse{blx@tempa}}%

\show\addtocontents
\begin{document}
xx
\end{document}
~~~~

(but beside that it would be better if newclude wouldn't overwrite a kernel definition, but as it is so old, there is probably no chance to correct that.)

**Comment by moewew** [comment]
I'll have a look at this in a few days.

**Comment by moewew** [comment]
Hmm. I don't really like the looks of just searching for `\let`, but I can see how that would be more universal. Committed in https://github.com/plk/biblatex/commit/c7ec93a46a0a93f29d8e963bf96f1fd5dde1be16.

Of course it would be nicer to avoid having to patch `\addtocontents` in the first place. I imagine many packages would be interested in adding something there.

**Comment by u-fischer** [comment]
using only `\let` is perhaps a bit daring, but `\let\label` should be quite safe and still avoid to have to do two patches. And yes, there should be probably be some hook to allow to extend the list.

**Comment by moewew** [comment]
So what's your suggestion: Should we search for `\let\label` or stick with just `\let` and see if we brake anything?
