### ISSUE TITLE
verbose-ibid: \textcite and \footcite handle ibid differently after a \footnote

### ISSUE THREAD

**Issue by u-fischer** [plk/biblatex#1208]
When a normal footnote is between two \autocite or \footcite commands, ibid is not used (as documented e.g. in verbose-trad1). The same is not true if \textcite is used. Is this the intended behaviour?

~~~~
\documentclass{article}
\usepackage[style=verbose-ibid,isbn=false]{biblatex}
\addbibresource{biblatex-examples.bib}

\textheight 6cm
\begin{document}
\textcite{doody} text\footnote{blub} \textcite{doody}

text\autocite{aksin} text\footnote{blub} text\autocite{aksin}

\end{document}
~~~~

Note that footnote 3 is ibid, while footnote 6 is not:

![image](https://user-images.githubusercontent.com/4047173/155577859-9875e661-ef81-47dd-a45a-d4adb6a04c78.png)

**Comment by moewew** [comment]
Thank you very much for reporting this issue. I think the problem is that we did not properly guard the footnote number saving code. This should work better with https://github.com/plk/biblatex/commit/796a1587c3e1d04569c4a11eaab87b3a0808d5f2.
