### ISSUE TITLE
Trad-alpha does not recognize type, eventtitle, eventtitleaddon, eventdate, venue.

### ISSUE THREAD

**Issue by tobiasBora** [plk/biblatex#1210]
This PR https://github.com/plk/biblatex/pull/688/files (linked with this issue https://github.com/plk/biblatex/issues/687) added support for eventtitle, eventtitleaddon, eventdate, venue in `@unpublished`. Unfortunately, these fields are not recognized in the `trad-alpha` style (which I prefer over the `alphabetic` style, for instance it does not print `et al` but the full list of authors). Would it be possible to support them in `trad-alpha` as well please? (or if it's not possible for backward compatibility reasons, create a new style that mimics `trad-alpha`)

Thanks!

**Comment by moewew** [comment]
`trad-alpha` is not one of the core `biblatex` styles and is not maintained here. You can (and should) report `biblatex-trad` issues at https://github.com/moewew/biblatex-trad/.

**Comment by tobiasBora** [comment]
Thanks!
