### ISSUE TITLE
Combining biblatex and babel leads to broken output

### ISSUE THREAD

**Issue by RalfJung** [plk/biblatex#1211]
After updating texlive, most of my documents stopped building properly -- citations will produce pretty broken output. I reduced the issue to the following MRE:
```
\documentclass[10pt,a4paper]{article}
\usepackage{babel}
\usepackage[backend=bibtex]{biblatex}

\addbibresource{bib.bib}

\begin{document}

\fullcite{iris}

\end{document}
```
With `bib.bib` being
```
@inproceedings{iris,
  author    = {Ralf Jung and
               David Swasey and
               Filip Sieczkowski and
               Kasper Svendsen and
               Aaron Turon and
               Lars Birkedal and
               Derek Dreyer},
  title     = {{Iris}: Monoids and Invariants as an Orthogonal Basis for Concurrent
               Reasoning},
  booktitle = {{POPL}},
  year      = {2015},
  doi       = {10.1145/2676726.2676980},
}
```
The produced document looks like

Ralf Jung **andothers**. “Iris: Monoids and Invariants as an Orthogonal Basis
for Concurrent Reasoning”. **in**POPL: 2015. doi: 10.1145/2676726.2676980

Notice the strange bold font, the missing space after "in", and the "andothers". I have the same problem with both backends (biber, bibtex).

The problem goes away when I remove the line that includes babel. I desperately need to submit some documents today, so I hope I can just get rid of babel, but that is of course not a proper solution.

My texlive is installed via Debian packages; texlive-latex-extra has version 2021.20220204-1.

**Comment by sieversMartin** [comment]
In vanilla TeX Live there is a backup and restore method. Could you do the same for your installation?

**Comment by RalfJung** [comment]
I don't think so, Debian just installs these files like any other package (and downgrading large families of Debian packages like Texlive is notoriously difficult).

I don't think I am relying on babel in any crucial way for the documents I need today, so it's probably fine. If I ever need to rebuild my PhD thesis though, this would become a problem. ;)

**Comment by RalfJung** [comment]
The default language is English, I think? I am loading babel because it is my understanding that this makes sense even for English-speaking documents.

Also, the same snippet of code worked fine in past versions of texlive.

However, adding `[english]` helps to get my document to build again, so thanks for that hint. :)

**Comment by moewew** [comment]
If you load no language with `babel`, `babel` will implicitly set the language to the artificial `nil`.
```latex
\documentclass{article}
\usepackage{babel}

\begin{document}
Lorem
\end{document}
```
informs you about this in the `.log` file
```
Package babel Info: You haven't specified a language. I'll use 'nil'
(babel)             as the main language. Reported on input line 4299.
```

When `biblatex` asks `babel` for the document language, `babel` returns `nil` and `nil` is not a language `biblatex` supports.
```latex
\documentclass{article}
\usepackage{babel}
\usepackage{biblatex}

\begin{document}
Lorem
\end{document}
```
warns quite clearly
```
Package biblatex Warning: Language 'nil' not supported.
(biblatex)                Using dummy definitions on input line 5.
```

The solution as Joseph pointed out is to load `babel` with a supported language option (e.g. `english`) or not to load it at all.

Since v3.15 `biblatex` no longer silently falls back to English for unsupported languages, instead it warns and produces output that makes it clear that user action is required. See https://github.com/plk/biblatex/issues/945.

**Comment by RalfJung** [comment]
I see, thanks for the explanation!

Unfortunately those warnings are lost in all the other LaTeX output. I have long given up trying to read the output of `pdflatex` since I don't understand most of it anyway... it is almost entirely noise, as far as I can tell. In this case I should have read it; it would literally have been the first time that the output would have been useful to me. :)

In this particular case it might have been better if biblatex outright error'd with a suitable message due to encountering an unsupported language, because error messages are shown properly in most LaTeX IDEs and the usual ways to invoke latex from the terminal. At least my IDE (emacs+auctex) did not show this warning in any useful way. `rubber -W all $filename` does not show any warnings for the above example either.

**Comment by moewew** [comment]
I don't think I want to make using an unsupported language an error, since in
```latex
\documentclass{article}
\usepackage{babel}
\usepackage{biblatex}

\begin{document}
Lorem
\end{document}
``` 
it is inconsequential. And there are a few more scenarios where the message would appear that otherwise produce perfectly acceptable output.

In this case we have to rely on users reading warning messages. The concept of warning messages exists for a reason. Frankly. I would have expected all IDEs for serious LaTeX work to have a way to display warnings.

**Comment by RalfJung** [comment]
:shrug: all I can say is that I have not seen good warning support in any interaction with LaTeX. `pdflatex` itself produces unreadable output. `latexmk` doesn't even try to make the raw output any more readable, and `rubber` tries but clearly doesn't recognize all warnings as such.

Including `bibltax` without using a single citation seems like an odd corner case to me, but you'll have a much better idea of how this package is used than I do.
