### ISSUE TITLE
Extra space in galician.lbx

### ISSUE THREAD

**Issue by username87654567** [plk/biblatex#1212]
There is a blank line in galician.lbx file at the end of file, line 551. This causes the package to crash.
If you remove that blank line it solves the problem

**Comment by moewew** [comment]
Thank you very much for reporting this. Should be fixed in https://github.com/plk/biblatex/commit/5cdb4486e0cad5cb98e16cb7f8fe7bc94d009700.

**Comment by moewew** [comment]
This should be resolved in `biblatex` v3.18 which was released a few days ago and is available in TeX Live and MiKTeX now.
