### ISSUE TITLE
empty cite doesn't issue a warning

### ISSUE THREAD

**Issue by u-fischer** [plk/biblatex#1216]
We got an issue that in standard latex \cite doesn't issue a warning if the argument is empty. https://github.com/latex3/latex2e/issues/790 and classified that as a bug. 

biblatex behaves similar. Depending on the style there is not even a visual clue that something is missing:

~~~~
\documentclass{article}
\usepackage[style=authoryear]{biblatex}

\addbibresource{biblatex-examples.bib}
\begin{document}

text \cite{} \cite{doody}

\end{document}
~~~~

**Comment by moewew** [comment]
What is the expected behaviour here? I'm guessing a warning. But what would be the document-level output? Usually `biblatex` prints the entry key in bold if it not found. Obviously that does not work here. We can just print one or two bold question marks instead. Or `<empty citation>` or...

**Comment by u-fischer** [comment]
Imho both is fine. The fix for the standard \cite gives a warning ``LaTeX Warning: Citation `' on page 1 undefined on input line 38.`` and prints  `[?]`.

**Comment by moewew** [comment]
Alright. Let me know what you think about https://github.com/plk/biblatex/commit/433e907befede89ded13c005ffe5fe6b8a1c0da7.
