### ISSUE TITLE
citation behaviour in ref context has changed?

### ISSUE THREAD

**Issue by u-fischer** [plk/biblatex#1217]
I get a different output from the following example in texlive 2020 (v3.16) and texlive 2021 (v3.17). Is that intended?

(I know how to force the 3.16 output if I wanted it, and have nothing against the new output, I only want to be sure what I should document here).

~~~~
\documentclass{article}
\usepackage[defernumbers]{biblatex}

\addbibresource{biblatex-examples.bib}
\DeclareRefcontext{byyear}{sorting=ynt,labelprefix=A}
\begin{document}
\cite{doody,herrmann}
\printbibliography[title=References]

\newrefcontext{byyear}
\cite{doody,herrmann}
\printbibliography[title=by year]
\end{document}
~~~~

## biblatex 3.16

![image](https://user-images.githubusercontent.com/4047173/158404342-fefd90eb-d8ad-443b-b06d-89ef0621c241.png)

## biblatex 3.17

![image](https://user-images.githubusercontent.com/4047173/158404601-e36120cb-b02a-46df-877f-6544a18ec13d.png)

**Comment by moewew** [comment]
Yes, I think the behaviour of v3.17 is more predictable and closer to what the documentation has said for a long time. See also https://github.com/plk/biblatex/issues/904. But I can't find an explicit issue/commit mentioning such a change, so I'm guessing it might have come with the changes for https://github.com/plk/biblatex/issues/1167.

Unless we get reports that the new behaviour breaks anything very badly, I think I'd like to stick with it.

**Comment by u-fischer** [comment]
well I don't find it bad, but I'm not sure if I could really derive the current behaviour from the documentation. On the whole I have the impression that for the default behaviour the current rule is simply "the label of last bibliography which actually showed the citation". E.g. if one filter the previous label is used:

~~~~
\documentclass{article}
\usepackage[defernumbers]{biblatex}

\addbibresource{biblatex-examples.bib}
\DeclareRefcontext{byyear}{sorting=ynt,labelprefix=A}
\begin{document}
\cite{doody,herrmann,cicero}
\printbibliography[title=References]

\newrefcontext{byyear}
\cite{doody,herrmann,cicero}
\printbibliography[title=by year,nottype=book]
\end{document}
~~~~

**Comment by moewew** [comment]
The documentation has

> By default, data for a citation is drawn from the reference context of the last bibliography in which it was printed.

but I admit that "last" might be ambiguous (I read it as: last in the document, but maybe one can read it as "previous").

**Comment by plk** [comment]
I agree this is somewhat confusing, (probably since the introduction of named refcontexts)? Technically, the 3.16 behaviour corresponds to the docs as, since the `.bbl` is read before typsetting, the first citations are "after" the "byyear" context bibliography and the second citations after the default context bibliography. Basically, the citation data has to be pulled from some bibliography list and the default decisions about this can't cope with guessing what is needed in many cases that use labels and multiple lists so I'm not sure it makes much difference what the defaults are since it can be corrected by the manual assignment macros (`\assignrefcontext*`). We could correct the documentation however and make it a bit clearer what the default are. I'm just not sure that the defaults will correspond to anything coherently describable in any useful terms since it depends on the specific refcontext options, whether we have repeated citations in multiple lists etc. - there are a lot of variable.

**Comment by u-fischer** [comment]
yes it is not quite clear if "last"  relates to the document or not. Imho also unclear is the example on page 103. It claims that the the same citation can have different labels, but actually with the current behaviour this shouldn't happen.

**Comment by plk** [comment]
Looking at this afresh, wouldn't what we want be the opposite of what you show as the 3.16 output? That is, `[1, 2]` for the first citations and `[A1, A2]` for the second? That would make the most sense as then the bibliography and citations would reflect the current refcontext?

**Comment by u-fischer** [comment]
Personally  I don't really see that refcontexts are bound to a region. That means I don't really see an use case for "sort in one chapter alphabetically and in the next by year" with fitting labels. 

Imho different sorting are more useful for things like global bibliography together with some special bibliographies with a different sorting like   "overview of articles sorted by year". In this scenario all labels for citations should come from the global bibliography. 

Imho assigning the citations by default the label of the last bibliography in which they are printed is ok. It is easy to understand and also easy to overwrite: If users want something else, they can assign the context explicitly.  

In my example it would look like this (and it shows also the problem if biblatex would reassign the context, as cicero has no label in the second context):

~~~~
\documentclass{article}
\usepackage[defernumbers]{biblatex}

\addbibresource{biblatex-examples.bib}
\DeclareRefcontext{byyear}{sorting=ynt,labelprefix=A}
\begin{document}
\assignrefcontextentries[name=default]{*}
\cite{doody,herrmann,cicero}
\printbibliography[title=References]

\newrefcontext{byyear}
\assignrefcontextentries[name=byyear]{*}
\cite{doody,herrmann,cicero}
\printbibliography[title=by year,nottype=book]
\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/158586215-afdbf5d3-f69f-49b2-ab30-ebb888604e87.png)

**Comment by plk** [comment]
That's fair enough - I suppose initially I was trying to think of the most general solution but that probably includes use-cases which aren't really ever going to materialise. There is always the option of using separate refsections anyway to really encapsulate citations and bibliography lists in the same overall context. So, as @moewew says, let's leave this as it is.
