### ISSUE TITLE
Comma or `}` mandatory (just) after the last item in `\addtocategory` lists?

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#1224]
As shown by the following MCE, comma or `}` are mandatory (just) after the last item in `\addtocategory` lists (`d` item not listed in the example): is it deliberate?

```latex
\begin{filecontents}{\jobname.bib}
    @article{a,
    author = {Author, A.},
    title = {AAA},
    date = {2022},
    journal = {Journal of A}}

    @article{b,
    author = {Buthor, B.},
    title = {BBB},
    date = {2022},
    journal = {Journal of B}}

    @article{c,
    author = {Cuthor, C.},
    title = {CCC},
    date = {2022},
    journal = {Journal of C}}

    @article{d,
    author = {Duthor, D.},
    title = {DDD},
    date = {2022},
    journal = {Journal of D}}
\end{filecontents}

\documentclass{article}
\usepackage{biblatex}

\DeclareBibliographyCategory{primary}
\DeclareBibliographyCategory{secondary}
\addtocategory{primary}{
  a,
  b,
}
\addtocategory{secondary}{
  c,
  d
}

\addbibresource{\jobname.bib}

\nocite{*}

\begin{document}

\printbibheading
\printbibliography[category=primary,heading=subbibliography,%
title={Primary Sources}]
\printbibliography[category=secondary,heading=subbibliography,%
title={Secondary Sources}]
\end{document}
```

![image](https://user-images.githubusercontent.com/1032633/163480640-f19b8794-d00e-4cac-9e15-d28cb0821d3e.png)

**Comment by moewew** [comment]
This is an artefact of the standard comma-separated-list handing in LaTeX and `etoolbox`. Spaces *after* commas/at the beginning of and entry are ignored, but spaces before commas/at the end of an entry are not ignored.

```latex
\addtocategory{secondary}{
  c,
  d
}
```
is the same as
```latex
\addtocategory{secondary}{ c, d }
```
and asks for `c` and `d<space>` to be added to the category.

I would just go for the trailing comma here, but if you don't want that and need the lcosing curly brace in the next line, you need a `%`
```latex
\addtocategory{secondary}{
  c,
  d%
}
```

You can observe the same effect in standard LaTeX
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}


\begin{filecontents}{\jobname.bib}
@book{elk,
  author    = {Anne Elk},
  title     = {A Theory on Brontosauruses},
  year      = {1972},
  publisher = {Monthy \& Co.},
  location  = {London},
}
\end{filecontents}


\begin{document}
Lorem
\cite{
  elk
}

\bibliographystyle{plain}
\bibliography{\jobname}
\end{document}
```

**Comment by dbitouze** [comment]
Is it worth to mention in the documention this artefact ?

**Comment by moewew** [comment]
If you have a suggestion for wording and also where to mention it, I'm all ears. We have a lot of commands that accept comma-separated lists and I definitely don't want to mention in in every command description. So it would have to be in a "central" place, but then it is unlikely that people find this information when they need it.
