### ISSUE TITLE
Write HTML from biblatex

### ISSUE THREAD

**Issue by tex-apprentice** [plk/biblatex#1231]
Is it possible to write HTML from biblatex? 

I am aware of the SX question:

   https://tex.stackexchange.com/questions/89560/how-to-export-biblatex-data-to-html

which was prematurely closed just when @JosephWright was suggesting a driver fot biblatex to output HTML and XML. This happened some 10 years ago ... so does such a driver exists now? 

I am also aware of this method:

   https://www.mail-archive.com/emacs-orgmode@gnu.org/msg133671.html

but that seems to be incredibly complex, specially since biblatex files seems to have all the information necessary. So, what would be the proper way to do this?

**Comment by moewew** [comment]
What is possible depends a lot on what exactly you have in mind when you say you want HTML from `biblatex` and what your use case is.

---

If we're talking about generating `biblatex` output in HTML, this is surprisingly difficult.

`biblatex` is a LaTeX package, so unless you run LaTeX in a way that produces HTML output, the only way `biblatex` could produce HTML output is by writing an HTML file "on the side" during the LaTeX run. Then you run into the issues discussed in https://github.com/plk/biblatex/issues/292. You essentially would have to make everything expandable or at least make reasonable chunks expandable (and those chunks would have to interact properly with all of `biblatex`'s advanced features like the punctuation buffer). In the current `biblatex` framework that is a huge ask and unlikely to happen without a major rewrite (though I can imagine that it would be possible to come up with something ad-hoc that works OK-ish enough for some simple applications).

An alternative would be to have LaTeX produce HTML output directly. Then `biblatex` could go on happily doing what it always does and LaTeX (or rather the "engine" you use to generate HTML from LaTeX code) would do the heavy lifting of producing the HTML output. That's more or less the `make4ht` route mentioned in your second link.

---

If your aim is to just take your `.bib` file that is optimised for `biblatex` (i.e. uses some of the more modern field that are traditionally not used in classical BibTeX `.bst` styles) and get HTML output in any style (not necessarily a style available in the `biblatex` world), then my first intuition would be to look into CSL styles. There are various implementation of CSL and I'm guessing there are some out there that can read `.bib` file and produce HTML. Maybe they can be configured to accept more `biblatex`-y input if they don't already. Or you look into the many `.bib` to HTML converters that seem to be out there and see how they cope with your files. Again there might be a chance to have them accept more `biblatex`-y input depending on their actual implementation.

**Comment by tex-apprentice** [comment]
We are talking about the first possibility, which is the only one that
produces the goodies of biblatex. After all when you see them, it is hard
to "unsee". Thanks for the link to #292, it looks really interesting.
