### ISSUE TITLE
Reenable \MakeUppercase/\MakeLowercase patch

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#1234]
The patches had to be disabled (https://github.com/plk/biblatex/pull/1233) due to changes in `\MakeLowercase` and `\MakeUppercase` in LaTeX (2022-06-01, specifically things break with PL4). See https://chat.stackexchange.com/transcript/message/61500435#61500435 and the following discussion.

Ideally we'd get a hook in the relevant commands so that we can apply our patches officially.

**Comment by lorenzoferron98** [comment]
Hi! Is there a workaround? I tried downgrade biblatex but nothing.

**Comment by moewew** [comment]
An emergency fix for `biblatex` (v3.18a) is already on CTAN and should land in TeX Live tomorrow. If you need a fix now, you can disable the error message with

```latex
\makeatletter
\def\blx@err@patch#1{}
\makeatother
```
but please remember to remove this line from your document as soon as you update tomorrow, as it disables all error messages.

Downgrading `biblatex` does not help since the problematic change was in the LaTeX core.

**Comment by lorenzoferron98** [comment]
> Downgrading biblatex does not help since the problematic change was in the LaTeX core.

I thought so.

Anyway I updated TeX Live this morning and then I compiled a document that yesterday worked I received this error. I check my current version of ```biblatek``` is v3.18 even if on CTAN is v3.18a. I don't know why ```tlmgr``` doesn't update ```biblatek```.

**Comment by moewew** [comment]
When you updated this morning you got version 2022-06-01-PL4 of the LaTeX kernel which triggers the patching failure.

TeX Live updates packages from CTAN once every night, the emergency release `biblatex` v3.18a (put together last night: https://github.com/plk/biblatex/pull/1233) got in just a few minutes too late and will only be available in TeX Live tomorrow.

**Comment by moewew** [comment]
`expl3` now has an interface to declare "case-changed commands" (https://github.com/latex3/latex3/issues/1108), but I think we'll wait for the LaTeX2e interface in https://github.com/latex3/latex2e/issues/889.

**Comment by josephwright** [comment]
@moewew  Give me a day or two and I should have team agreement on a LaTeX2e interface, then I can suggest an update for you. The plan is largely sorted, just need to finalise the detail.

**Comment by moewew** [comment]
A first attempt is at https://github.com/moewew/biblatex/commit/a10756447e498ddb0599817e7cb2dfba63371034.

@josephwright Is it OK to test for `\DeclareCaseChangeEquivalent` with `\ifundef` or is it preferable to use a format-date based approach?

**Comment by josephwright** [comment]
@moewew  Looks good. Ideally I'd use the format date, but I don't think we plan to rollback `\DeclareCaseChangeEquivalent` so using `\ifundef` should be safe. I'd go with the change here and this can be adjusted later if really needed.

**Comment by moewew** [comment]
Can we use the format date to distinguish between patch levels?

**Comment by josephwright** [comment]
@moewew  Generally no as patches are meant to deal with urgent fixes: the one here is unusual as it required an additional command to be added. I think the team position is that if one is used LaTeX YYYY-MM-DD then the latest patch is 'expected': if someone updates their LaTeX, it's reasonable to expect that includes the latest patch level.

All that said, if you want to be super-cautious then I'd check the format date *and* use `\ifundef`.

**Comment by moewew** [comment]
Thanks for the clarification. I guess I'll stick with `\ifundef` for now.

**Comment by moewew** [comment]
The effect of the patches are reenabled using the appropriate LaTeX interface in v3.18b.
