### ISSUE TITLE
biber wants to load libcrypt.so.1 but it is missing

### ISSUE THREAD

**Issue by Firestar-Reimu** [plk/biblatex#1247]
Arch Linux + TeX Live 2022, used `tlmgr` to update to latest biblatex

When I am using `biber`, it throws out:

```
error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
```

After searching for the web, it seems that Perl has throw out `libcrypt` and use `libxcrypt`

https://stackoverflow.com/questions/71171446/biber-wants-to-load-libcrypt-so-1-but-it-is-missing

https://tex.stackexchange.com/questions/493231/biber-missing-libcrypt-so-1-library-on-fedora

As there is no issue about this here, I want to know if you have done sth about this.

**Comment by plk** [comment]
Since you are using the non "binary" perl, you are at the mercy of the OS and would need either a perl linked against libcrypto or just install the compat package mentioned in that first link.

**Comment by moewew** [comment]
Biber issues should be reported at https://github.com/plk/biber/issues. Closing this for now, since there was no feedback. If more discussion in this issue is required, please open an issue at https://github.com/plk/biber/issues, so things are kept track of in the correct repository.
