### ISSUE TITLE
\AtNextRefsection

### ISSUE THREAD

**Issue by jspitz** [plk/biblatex#1248]
Hi all,

For an upcoming feature in `biblatex-publist`, I need a hook to insert code at the beginning of the next refsection (not all refsection, as in `\AtBeginRefsection`).

For the time being, I roll my own `\AtNextRefsection`, patching `\blx@refsection@i`. Maybe it should be implemented upstream.

What do you think?

(My code is upwards compatible in that it only defines the command if it does not exist yet)

**Comment by moewew** [comment]
Give https://github.com/plk/biblatex/commit/cca365b870fa6629d333bb32860aa05a11dd0f2a a spin.

**Comment by jspitz** [comment]
Thanks, looks good.

**Comment by plk** [comment]
Fixed in 3.19 release
