### ISSUE TITLE
Jump to related KEY does not work

### ISSUE THREAD

**Issue by hsvia** [plk/biblatex#1250]
Using the entry editor corresponding to the KEY1 
- in the TAB "other fields"
- in the line "Related"

Here I have added a bibtexkey belonging to an entry KEY2.
I get a bubble containing this key ==> that is fine
The BiBTeX source now contains a line:
related = {KEY2};   ==> that is fine

Now I want to use this bubble to jump to the entry of KEY2 ==> That does not work.
Nothing happens
I can add another bubble with KEY3 by typing text in the text-field to the right.
I can delete the bubble with a backspace.
I can do nothing else.
There is no popup menu or anything else when I click the bubble.

I am using:

```
JabRef 5.8--2022-10-31--e7c8535
Windows 10 10.0 amd64 
Java 18.0.2.1 
JavaFX 19+11

```

though the problem persists already a long time.

**Comment by moewew** [comment]
This looks like an issue to report at https://github.com/JabRef/jabref/issues.

**Comment by moewew** [comment]
As mentioned previously, I don't think this is a `biblatex` issue, so I'm closing this. If it is an issue with `biblatex`, please clarify the issue and we can reopen this,
