### ISSUE TITLE
The manual should explain the semantics of the `final` option to a `\DeclareSourcemap`'s `\step`s in a clearer, and more accurate way

### ISSUE THREAD

**Issue by EvanAad** [plk/biblatex#1253]
In the current version of the manual (v. 3.18b July 12 2022) the semantics of the `final` option to a `\DeclareSourcemap`'s `\step` are not collected in a single place, but have to be gathered from all over the place. Furthermore, some of the manual's explanations are misleading. For example, the following excerpt from p. 203 of the manual suggests that `final` aborts the current map when a `match` succeeds, whereas in fact it is the opposite: the maps aborts when the `match` fails.

`If fieldset is defined, then its value is 〈entryfield〉 which will be set to a value specified by further options. If overwrite is false for this step and the field to set already exists then the map step is ignored. If final is also true for this step, then processing of the parent map stops at this point." (p. 203 of the current version, 3.18b, July 12, 2022`

One way to clarify the semantics of `final` is by adding a table such as the one shown in the following TeX StackExchange answer: https://tex.stackexchange.com/a/666330/21685

**Comment by plk** [comment]
I have added a general description of the 'final' step to the documentation. That text that you give above seems not related you your comment however? The doc text doesn't say anything about `match`? The text if fairly clear - `final` means that an `overwrite` set to false won't overwrite and will stop at this point.

**Comment by moewew** [comment]
I guess the problem is that the step in question had both a `match` and a `fieldset`. A priori is not quite clear from the documentation whose `final` semantics prevail here (it could also be both).

**Comment by EvanAad** [comment]
You wrote: "The text if fairly clear - final means that an overwrite set to false won't overwrite and will stop at this point."
I agree with you that this is what the text lets the reader to understand. Now apply this without prejudice to the example I posted [here](https://tex.stackexchange.com/q/666305). How is one to predict the behavior of the following `step`?

```
\step [
            fieldsource=langid,
            match=english,
            fieldset=presort,
            fieldvalue=a,
            final
         ]
```
that the `map` will stop at this point, i.e. if the entry is matched to `english`, processing will stop at this point.

**Comment by EvanAad** [comment]
It is also unclear from the manual what does it mean for a `map` not to be processed anymore: does it mean that it won't be processed anymore for the current bibliographic entry, but will be considered again for the next entry? Or does it mean that it won't ever be processed anymore, essentially like deleting it from `maps` list? I realize it's the former intepretation that's the correct one, but I've come to this realization only by experimentation; the manual leaves this ambiguous.

**Comment by plk** [comment]
I see the point. There is precedence here which is in fact not documented. Generally, users just split such steps into multiple steps with more atomic semantics which also gives more granular control. I can document the precedence but I'm afraid this might be even more confusing?

I will add something explicit about the `map` skipping semantics of `final`. It is, as you say, that the `map` is skipped for that particular entry.

**Comment by EvanAad** [comment]
moewew wrote: " guess the problem is that the step in question had both a match and a fieldset. A priori is not quite clear from the documentation whose final semantics prevail here (it could also be both)."

But there the semantics of `final` w.r.t. to the `match` option is not documented at all. The bullet point that talks about `match` (the fourth bullet point on p. 203) doesn't mention `final` at all.

**Comment by EvanAad** [comment]
In my opinion the change that plk made to the documentation is not sufficient, and leaves the documentation misleading. plk wrote: "I can document the precedence but I'm afraid this might be even more confusing?" Yes, document the precedence. No, it won't make the documentation more confusing, it will make it less misleading, because as it stands now the documentation is misleading. In other words, it documents explicitly a behavior that is not consistent with observation. This is beyond *confusing*; it is *misleading*. When the documentation states in the `fieldset` bullet point " If `final` is also true for this step, then processing of the parent map stops at this point." but then the following step

\step [
            fieldsource=langid,
            match=english,
            fieldset=presort,
            fieldvalue=a,
            final
         ]

does not cause the processing of the parent map to stop when the entry's `langid` value is `english`, then the documentation explicitly described a behavior that is different than the actual one.

**Comment by plk** [comment]
The confusion here is that in the sentence you point out, the "also" is supposed to mean "in addition to `overwrite` being false". It's not too clear, admittedly. It should read "If `final` is also true when `overwrite` is false for this step". A `final` in a `fieldstep` only does something when `overwrite` is false.

**Comment by EvanAad** [comment]
plk, with your recent modification you have introduced another misdirection. The current development version of the manual reads:

`If \texttt{overwrite} is false for this step and the field to set already exists then the map step is ignored. If \texttt{final} is also true when \texttt{overwrite} is false for this step, then processing of the parent map stops at this point.
`

Since the second of these sentences repeat one of the conditions of the previous sentence, namely "\texttt{overwrite} is false", but does not repeat the other condition of the previous sentence, namely "the field to set already exists", the natural way to understand the second sentence is that if \texttt{overwrite} is false, then processing of the parent map stops, regardless of whether the field to set already exists or no.

If you wish to express the semantics you described in your recent comment: "A final in relation to a fieldset in a step only does something when overwrite is false and the field to set has a value." You need to either remove the condition "when \texttt{overwrite} is false for this step" from the second sentence:

`If \texttt{overwrite} is false for this step and the field to set already exists then the map step is ignored. **If \texttt{final} is also true, then processing of the parent map stops at this point.**`

or else to add to it the condition "the field to set already exists":

`If \texttt{overwrite} is false for this step and the field to set already exists then the map step is ignored. **If \texttt{final} is also true when \texttt{overwrite} is false for this step and the field to set already exists , then processing of the parent map stops at this point.**`

**Comment by plk** [comment]
I have clarified the first point as suggested. I don't see much ambiguity in the last example as the map should be aborted since the match fails and therefore the `fieldset` is irrelevant, along with the concomitant conditions for `overwrite`.
