### ISSUE TITLE
The bibliography's title is in English rather than in Hebrew when Hebrew is selected as the document's main language and English as its secondary language by passing options to the `babel` package

### ISSUE THREAD

**Issue by EvanAad** [plk/biblatex#1254]
I'm not sure if the following is a bug in `biblatex` or in `babel`. If I'm told it's not a bug in `biblatex`, I'll report it to the `babel` project.

***

The following LaTeX code was saved in `~/Test.tex`.

```
\begin{filecontents*}[overwrite]{\jobname.bib}
@book{shakespeare,
   author = {William Shakespeare},
   title = {Hamlet},
   year = {1600}
}
\end{filecontents*}

\documentclass{article}
\usepackage[bidi=basic,hebrew,provide=*]{babel}
\babelfont{rm}[Renderer=HarfBuzz]{FreeSans}

\usepackage{biblatex}
\addbibresource{\jobname.bib}
\begin{document}
\cite{shakespeare}
\printbibliography
\end{document}
```

Then the following commands were executed in the Terminal.

```
\> cd ~
\> lualatex Test
\> biber Test
\> lualatex Test

```
Consequently the file `~/Test.pdf` was generated. When opened in a PDF viewer, it displayed as follows, as expected. (Only the relevant part of the display was captured in the screenshot.)

![HebrewAsOption](https://user-images.githubusercontent.com/22092671/204080807-e3b609c2-b385-46c9-bb9d-d97f717fee44.gif)

I now rewrote the code as to set the document's main language to Hebrew using the `\babelprovide` command. I did so by replacing the `\usepackage ... {babel}` command shown above by the following two commands.

```
\usepackage[bidi=basic]{babel}
\babelprovide[import,main]{hebrew}
```
Compiling this yielded the same output as shown above, as expected.

I now added English as a secondary language, using the `\babelprovide` command, by adding the following line immediately under the two lines added in the previous step.

`\babelprovide[import]{english}`

Compiling this yielded the same output as shown above, as expected.

Finally, I rewrote the code as to specify both Hebrew and English as options to the `babel` package, by deleting both `\babelprovide` commands, and replacing the `\usepackage ... {babel}` command by the following:

`\usepackage[bidi=basic,english,hebrew,provide=*]{babel}`

The resulting PDF file now displayed as follows, which is unexpected!

![EnglishAsSecondaryLanguage](https://user-images.githubusercontent.com/22092671/204081190-938ff147-0b6d-41b6-bbfd-ac6eae2bf977.gif)

The surprising aspect is that the bibliography's title is now written in English instead of Hebrew, despite the fact that Hebrew is the document's main language, as mentioned in the first paragraph of section 1.2 *Multilingual documents* of the current version of the `babel` manual (v. 3.82, 2022/10/23):

> In multilingual documents, just use a list of the required languages as package or class options. The last language is considered the main one, activated by default.

If I replace `hebrew` by `russian` in the last example, the output is as expected:

![RussianAsMain](https://user-images.githubusercontent.com/22092671/204081479-ea133888-2c64-4b3d-9fdd-c55ebd9627c6.gif)

**Comment by u-fischer** [comment]
as the log tells you there is no hebrew.lbx and biblatex is falling back to dummy definitions. You will have to write a hebrew.lbx with suitable definitions.

**Comment by EvanAad** [comment]
u-fischer: As you can see from the first example, when Hebrew is set as the main language by passing it as a package option but English is not set as a secondary language, the Hebrew word for *Bibliography* is produced. However when English is set as a secondary language via the package options, the English word for *Bibliography* is produced. Why should the setting of English as a secondary language affect the output? If, before the `\printbibliography`, there were a `\selectlanguage{english}`, it would make sense. But there's no `\selectlanguage{english}` before the `\printbibliography`. This feels like a bug.

**Comment by moewew** [comment]
We rely on `babel` facilities like `\bbl@loaded` and `\bbl@main@language` to detect the used languages and main languages.

Unfortunately, these features do not appear to work correctly together with the new `babel` way of loading stuff via "provide".

```latex
\documentclass{article}
\usepackage[bidi=basic,hebrew,provide=*]{babel}
\babelfont{rm}[Renderer=HarfBuzz]{FreeSans}

\begin{document}
Lorem \bibname

\makeatletter X \bbl@loaded

Y \bbl@main@language\makeatother
\end{document}
```
>  ![X//Y hebrew](https://user-images.githubusercontent.com/6755835/205429290-864890a4-5933-4ff2-974e-e3ea7ca8f705.png)

```latex
\documentclass{article}
\usepackage[bidi=basic]{babel}
\babelprovide[import,main]{hebrew}
\babelfont{rm}[Renderer=HarfBuzz]{FreeSans}

\begin{document}
Lorem \bibname

\makeatletter X \bbl@loaded

Y \bbl@main@language\makeatother
\end{document}
```
>![X//Y hebrew](https://user-images.githubusercontent.com/6755835/205429304-bdbc245d-843a-4967-bd0b-0284fee44b30.png)


```latex
\documentclass{article}
\usepackage[bidi=basic]{babel}
\babelprovide[import,main]{hebrew}
\babelprovide[import]{english}
\babelfont{rm}[Renderer=HarfBuzz]{FreeSans}

\begin{document}
Lorem \bibname

\makeatletter X \bbl@loaded

Y \bbl@main@language\makeatother
\end{document}
```
> ![X//Y hebrew](https://user-images.githubusercontent.com/6755835/205429321-f8e11370-762d-4181-804a-764ab1279844.png)


```latex
\documentclass{article}
\usepackage[bidi=basic,english,hebrew,provide=*]{babel}
\babelfont{rm}[Renderer=HarfBuzz]{FreeSans}

\begin{document}
Lorem \bibname

\makeatletter X \bbl@loaded

Y \bbl@main@language\makeatother
\end{document}
```
> ![X english//Y hebrew](https://user-images.githubusercontent.com/6755835/205429333-6897c6c4-8bd4-43f6-a9cb-3ee273ae5d64.png)

We'd, however, rely on it looking roughly like this

```latex
\documentclass{article}
\usepackage[british,ngerman]{babel}

\begin{document}
Lorem \bibname

\makeatletter X \bbl@loaded

Y \bbl@main@language\makeatother
\end{document}
````
> ![X ngerman,british//Y ngerman](https://user-images.githubusercontent.com/6755835/205429459-fbc62fc6-b212-4b27-9437-8a762b95bf01.png)


----

I haven't fully tracked down what exactly is happening here when it comes to why in the last case we don't get the Hebrew bibliography heading. The bibliography heading is the only string that `biblatex` can inherit from `babel`. All other localisation strings must come from `biblatex`'s own `.lbx` files. So I'm guessing that in the first three cases, `biblatex` never tries to load any localisation and thus ends up being able to inherit `babel`'s bib heading. In the fourth case, `biblatex` does load the English localisation, whose definition prevail, because we don't have a `hebrew.lbx`.


I don't think we have to worry about that now too much, since the bibliography heading is the only thing `biblatex` could inherit from `babel` in terms of localisation strings. Everything else would have to come from a `.lbx`, which we don't yet have for `biblatex` as Ulrike rightly points out.

**Comment by EvanAad** [comment]
It appears then that there is indeed a bug, however not in `biblatex`, but in `babel`: when Hebrew is set as the main language, by whatever means, the `\bbl@loaded` macro isn't configured in a way that is consistent with the way it is configured when a European language is set as the main language. I'll report this to the `babel` project.

**Comment by EvanAad** [comment]
Upon further inspection, it appears that it is not the `hebrew` option that is responsible for the behavior of the `\bbl@loaded` seen in `moewew`'s comment above, but the `provide=*` option. If `hebrew` is replaced by `ngerman` in all four examples without any other change, the results are exactly the same as in the corresponding `hebrew` versions.

**Comment by EvanAad** [comment]
And yet, when `hebrew` is replaced by `ngerman` in the fourth example of my original post, the German word for "Bibliography" appears in the PDF output rather than the English word. How pecular.

```
\begin{filecontents*}[overwrite]{\jobname.bib}
@book{shakespeare,
   author = {William Shakespeare},
   title = {Hamlet},
   year = {1600}
}
\end{filecontents*}

\documentclass{article}
\usepackage[bidi=basic,english,ngerman,provide=*]{babel}
\babelfont{rm}[Renderer=HarfBuzz]{FreeSans}

\usepackage{biblatex}
\addbibresource{\jobname.bib}
\begin{document}
\cite{shakespeare}
\printbibliography
\end{document}
```

![Literatur](https://user-images.githubusercontent.com/22092671/205437623-4c324d87-ef4e-45e2-8963-9628bee99f49.gif)

**Comment by moewew** [comment]
That is explained by the results of

```latex
\documentclass{article}
\usepackage[bidi=basic,english,ngerman,provide=*]{babel}
\babelfont{rm}[Renderer=HarfBuzz]{FreeSans}

\usepackage{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \bibname

\makeatletter X \bbl@loaded

Y \bbl@main@language\makeatother

\autocite[380]{sigfridsson}

\printbibliography
\end{document}
```
![X english//Y ngerman](https://user-images.githubusercontent.com/6755835/205439929-5b631033-fdfa-4b81-8467-9e893a3c24a5.png)

While `ngerman` does not appear in the list of loaded languages, it is noted down as main language. Unlike `hebrew`, however, `biblatex` does have a `ngerman.lbx`, so that gets used here.

This just goes to show that the main issue for a Hebrew bibliography at the moment is that `biblatex` does not have a `hebrew.lbx`. The fact that in some constellations you get the Hebrew heading inherited from `babel` and sometimes not, shows that something is a bit off (and that probably needs looking at), but it is not the *main* obstacle here.

**Comment by EvanAad** [comment]
moewew: If you replace `ngerman` by `hebrew` in your last example code, the resulting PDF file shows `Y hebrew`, i.e. `hebrew` is reported as the main language. So it doesn't explain why the "Bibliography" word is not written in Hebrew when Hebrew is the main language, but is written in German when German is the main language.

In my opinion it is an important matter, because for simple bibliographies the most important aspect of the customization is the title of the bibliography.

**Comment by u-fischer** [comment]
> So it doesn't explain why the "Bibliography" word is not written in Hebrew when Hebrew is the main language, but is written in German when German is the main language.


biblatex doesn't know hebrew, so what you get for `\refname` is basically undefined as it uses as fallback whatever definition `\refname` got before---which can differ depending on your document as you discovered. So don't ignore the warning in the log! It tells you that hebrew.lbx is missing and you should correct that if you want to use biblatex with hebrew.
