### ISSUE TITLE
Purpose of biblatex-examples.bib?

### ISSUE THREAD

**Issue by aubertc** [plk/biblatex#1255]
I am sorry if this is documented somewhere, but could not find in the documentation or in this repository what is the exact purpose of [biblatex-examples.bib](https://github.com/plk/biblatex/blob/dev/bibtex/bib/biblatex/biblatex-examples.bib).

If its purpose is to showcase all the possibilities of BibLaTeX or to use it to test how various style displays entries, then I am afraid it is incomplete (for instance, there are no `software` entries).

I see that the `langid` or `indextitle` fields are present, that various accents occur, but there are no `crossref`s between books and inbook, for instance, no `proceedings`, etc.

**Comment by moewew** [comment]
I don't think the purpose of `biblatex-examples.bib` is documented anywhere.

I'd say it is supposed to be a `.bib` file that shows best practices (to some degree - it still uses ASCII escapes, when for most intents and purposes UTF-8 would be a better choice today) and a wide range of example entries. It is used to test some features of `biblatex` (in our test suite) and at the same time can serve as a first entry point for new users who want to learn by example.

I don't think there is an underlying assumption that the file covers all `biblatex` features and has an entry for every possible use case (that would be extremely tricky and make the file extremely large).
