### ISSUE TITLE
No space after bullet items in the documentation

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#1258]
In the documentation, some of the `itemize` lists look weird because there is no space after the bullet items. AFAICS, the affected lists are the ones within `\cmditem` in `ltxsyntax` environments. The first example is the list in the description of `useprefix`, currently (version 3.18b) page 73:

![screen-2022-12-13-14-07-53](https://user-images.githubusercontent.com/1032633/207326359-1bc9f2e7-067f-4f7d-9e9c-01422e53fe72.png)

**Comment by plk** [comment]
Should be fixed in 3.20 dev
