### ISSUE TITLE
Improve `\addbibresource`

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#1259]
It would be nice for `\addbibresource` to be improved in the following ways:

1. just as `\usepackage`, its argument should accept multiple resources (that share the `\addbibresource` option(s)),
2. the `.bib` extension should be the default one if not specified.

**Comment by zepinglee** [comment]
It's a reasonable feature and I'll prioritize this feature.

**Comment by moewew** [comment]
For many intents and purposes you can still use `\bibliography` if you think its behaviour is better. But the current behaviour of `\addbibresource` is explicitly documented and has been around for years, so I don't really want to change it and I don't really see the point.

A few points to note though: The current behaviour where we don't treat the argument as a comma-separated lists allows file names with commas without a problem. If we treat the argument as a comma-separated list, we'd have to disallow commas (which would probably be OK for most people, but would not be backwards compatible) and/or allow for a comma-escape (add curly braces around a file name containing commas, which could possibly have its own issues). As far as the file extension goes, I have the feeling that at some point there was hope `biblatex` would support different file formats (it did sort of support RIS input at some point, if I recall correctly), so enforcing the file extension made perfect sense to avoid confusion.

**Comment by dbitouze** [comment]
> For many intents and purposes you can still use `\bibliography` if you think its behaviour is better. But the current behaviour of `\addbibresource` is explicitly documented and has been around for years, so I don't really want to change it and I don't really see the point.
 
If the change is backward compatible, it doesn't matter that the current behaviour of `\addbibresource` is explicitly documented and has been around for years.

> A few points to note though: The current behaviour where we don't treat the argument as a comma-separated lists allows file names with commas without a problem. If we treat the argument as a comma-separated list, we'd have to disallow commas (which would probably be OK for most people, but would not be backwards compatible)

I guess people using commas in their filenames are:

- extremely few,
- even more in the minority among (La)TeX users,
- among the latter, even more in the minority among `bibatex` users.

> and/or allow for a comma-escape (add curly braces around a file name containing commas, which could possibly have its own issues).

Maybe this point is better handled by recent LaTeX versions.

> As far as the file extension goes, I have the feeling that at some point there was hope would support different file formats (it did sort of support RIS input at some point, if I recall correctly), so enforcing the file extension made perfect sense to avoid confusion.

Indeed but, even if `biblatex` would support file formats other than `.bib` ones, it would make sense for `\addbibresource` to suppose  `.bib` extension if none is supplied. And since `biblatex` will now quite surely never support other file formats, it makes even more sense.

**Comment by moewew** [comment]
> > For many intents and purposes you can still use `\bibliography` if you think its behaviour is better. But the current behaviour of `\addbibresource` is explicitly documented and has been around for years, so I don't really want to change it and I don't really see the point.
> 
> If the change is backward compatible, it doesn't matter that the current behaviour of `\addbibresource` is explicitly documented and has been around for years.
> 


True, but I can't see how a solution that makes `\addbibresource` accept a comma-separated list of files could be implemented in a backwards compatible way if at the moment we do allow a file named `a,b.bib`.

My point was also that so far people seemed content typing in the file name extension explicitly and using several `\addbibresource` calls or using `\bibliography`. I don't think there have been lots of complaints about this thus far.
