### ISSUE TITLE
Incorrect: German output format for time periods

### ISSUE THREAD

**Issue by Nine-Lives-Cat** [plk/biblatex#1268]
For my Bibliography I am using `\usepackage[style=apa, backend=biber, uniquename=false, uniquelist = false]{biblatex}`

I have several bib entries with an eventdate, e.g. `EVENTDATE = {2003-10-26/2003/10-29}`, however, the German output format in that case is not correct leading to `2003, 26. Oktober–29.` instead of `2003, 26.–29. Oktober`.

Is there an internal issue with the German formating of time periods within the same month?

**Comment by moewew** [comment]
`biblatex-apa` is a contributed style. Issues with that style should be reported at https://github.com/plk/biblatex-apa/issues.

Note that reports including a fully compilable example document (with a relevant `.bib` entry) are usually easier to process.
