### ISSUE TITLE
Bug when title ends with an uppercase letter

### ISSUE THREAD

**Issue by daniporr** [plk/biblatex#1271]
If the title of the paper ends with an upper case letter, then `In` is written as `in`.

This does not happen when the title ends with a lower case letter.

**Comment by moewew** [comment]
Can you please provide a minimal example document that shows your style setup along with an example `.bib` entry that reproduces the problem?

The following works fine for me
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear]{biblatex}

\begin{filecontents}{\jobname.bib}
@article{sigfridsson,
  author       = {Sigfridsson, Emma and Ryde, Ulf},
  title        = {Comparison of methods for deriving atomic charges from the
                  electrostatic potential and moments A},
  journaltitle = {Journal of Computational Chemistry},
  date         = 1998,
  volume       = 19,
  number       = 4,
  pages        = {377-395},
  doi          = {10.1002/(SICI)1096-987X(199803)19:4<377::AID-JCC1>3.0.CO;2-P},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
Lorem \autocite{sigfridsson}

\printbibliography
\end{document}
```
![Sigfridsson, Emma and Ulf Ryde (1998). ‘Comparison of methods for deriving atomic charges from the electrostatic potential and moments A’. In: Journal of Computational Chemistry 19.4, pp. 377–395.](https://user-images.githubusercontent.com/6755835/222245596-1608d384-96ca-422c-89cb-1f51631c5e88.png)

**Comment by moewew** [comment]
Thinking about this again, the only explanation for the effect described in the report that I can come up with is https://github.com/plk/biblatex/issues/1071.

@daniporr If you could verify that is indeed the case, we can close this report as a duplicate.

**Comment by daniporr** [comment]
Thank you for your quick and very detailed answer (apologies, I somehow missed it).

Your point makes total sense to me. That statement was in a template I was using and that I trusted, so I haven't double checked it.

Removing that statement solves the problem (and it does not really change the output).

Thank you very much for your help.
