### ISSUE TITLE
sorting of entries with two prefixes

### ISSUE THREAD

**Issue by u-fischer** [plk/biblatex#1272]
I'm not sure if I'm missing something simple, or if this is a bug. Why does biber/biblatex sort in the following example the `von der` prefix before  the `von` prefix? (I tried a number of options like sortcase be it didn't seem to change anything). 

~~~~
\begin{filecontents}[force]{testprefixsorting.bib}
@article{a,
author={Max von der Blub},
year={2023}}
@article{b,
author={Emma von Blub},
year={2023}}
@article{c,
author={Duck von {der Blub}},
year={2023}}
\end{filecontents}

\documentclass{article}
\usepackage[style=authoryear,useprefix]{biblatex} 

\usepackage[ngerman]{babel}
\usepackage[autostyle]{csquotes}
\addbibresource{testprefixsorting.bib}
\begin{document}
\cite{a} \cite{b} \cite{c}
\printbibliography
\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/224363321-13426ca0-4b9a-4d06-8c24-3ef849ccfa87.png)

**Comment by moewew** [comment]
Biber `--trace` shows
```
[591] Internals.pm:1157> DEBUG - Sorting object for key 'a' -> ["mm", "", "von derBlub    Max ", 2023, "", 0]
[591] Internals.pm:1157> DEBUG - Sorting object for key 'b' -> ["mm", "", "vonBlub    Emma", 2023, "", 0]
[592] Internals.pm:1157> DEBUG - Sorting object for key 'c' -> ["mm", "", "vonder BlubDuck", 2023, "", 0]
```
Apparently the prefix is added before the family name without a space for sorting purposes. Not sure if that is necessary. I suppose if Biber used a space here, the result would be slightly more intuitive in this example. Again not sure about the general repercussions of such a change.

**Comment by plk** [comment]
I was thinking about having prefix as a separate sorting key, which would fix this. Historically, it's just been prepended to the name, which is probably not the right thing to do in general. Will look at it.

**Comment by plk** [comment]
Please try with `biber` 2.20 DEV - should be addressed. I expanded the space-padding to prefices which probably should have been done a while ago.
