### ISSUE TITLE
Using citecounter causes "There were undefined references." Warning

### ISSUE THREAD

**Issue by mapfiable** [plk/biblatex#1276]
I am using Overleaf running the latest TeX Live version (2022). When using the `citecounter` option, `biblatex` produces the `There were undefined references.` and the `Package biblatex Warning: Please (re)run Biber on the file: output and rerun LaTeX afterwards.`

Interestingly, the same also happens when switching to another language that wasn't previously passed to the `babal` package (this has a simple fix of course, but maybe the issues are related).

```latex
\documentclass{article}
\usepackage[english]{babel}
\usepackage{csquotes}
\usepackage[citecounter=true, backend=biber]{biblatex}

\begin{filecontents}{\jobname.bib}
@misc{author2001,
  author = {Author, A. and Buthor, B. and C},
  year = {2001},
  title = {Alpha},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}

Some text \autocite{author2001}.

\printbibliography

% \begin{otherlanguage}{ngerman} 
% test
% \end{otherlanguage}{ngerman} 

\end{document}
```

**Comment by mapfiable** [comment]
I just realized I should add: by itself, this is of course not a big issue, but it is rather annoying if you *actually* are miss-referencing something somewhere, but will not realize or find it because of this.

**Comment by moewew** [comment]
AFAICT this has to do with https://github.com/plk/biblatex/issues/778 and https://github.com/plk/biblatex/issues/1072. Specifically with `citecounter` `biblatex` passes the counter to the `.bcf` file and request a Biber rerun. This Biber rerun may not result in any `.bbl` changes, but then the rerun detection asks for a rerun, because the hash comparison assumes that a Biber rerun must result in a file change.

Maybe we have to switch to filemoddate instead?

**Comment by moewew** [comment]
Just a thought: A way to resolve this with hashes would be to have Biber output the `citecounter` into it got from the `.bcf` also in the `.bbl`. Then the `.bbl` file hash would change even if the relevant contents of the `.bbl` do not change.

**Comment by plk** [comment]
But do we always get a citecounter in the `.bcf`?

**Comment by moewew** [comment]
Thing is: Can we get BibTeX to do the same? (Though we might not have to, since I think the whole `citecounter` business does not work there anyway...)

**Comment by moewew** [comment]
> But do we always get a citecounter in the `.bcf`?

I don't think so. Is that a problem? I guess if it would make things easier we could populate the citecounter with 0 if the feature is not actually active. (I haven't fully thought all of this through, to be fair. And it's getting a bit late for me, so I may have to come back to this in the next couple of days.)

**Comment by plk** [comment]
We are talking about putting the `citecounter` value in the `.bcf, not the option value and that might get a bit exciting when `citecounter=context` since that's (at least?) two different counters.

**Comment by moewew** [comment]
I haven't looked to closely at what exactly is going on, but I can see that when `citecounter` is enabled, something resembling a counter value is written to the `.bcf`. Then `biblatex` requests a Biber rerun, because this info might be used for sorting. If the new data does not change the `.bbl`, we get stuck in the loop.

As I said, I haven't checked what exactly `biblatex` writes to the `.bcf` here at the moment. But as far as I can tell the problem could be mitigated by making sure that the `.bbl` reflects the info from the `.bcf`, because that would force file changes even if all entry data otherwise stays the same.

**Comment by plk** [comment]
I think we'll need a MWE - I can't see anything called `citecounter` other than the datamodel reference for it being written to the `.bcf` for the above MWE.

**Comment by moewew** [comment]
I'm talking about the
```xml
    <bcf:citekeycount count="3">sigfridsson</bcf:citekeycount>
    <bcf:citekeycount count="1">worman</bcf:citekeycount>
    <bcf:citekeycount count="2">geer</bcf:citekeycount>
    <bcf:citekeycount count="1">nussbaum</bcf:citekeycount>
```
data that ends up in the `.bcf` in the following case
```latex
\documentclass{article}
\usepackage[english]{babel}
\usepackage{csquotes}
\usepackage[citecounter=true, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite{sigfridsson}
ipsum \autocite{worman,geer}
dolor \autocite{sigfridsson}
sit \autocite{nussbaum}
amet \autocite{sigfridsson,geer}

\printbibliography
\end{document}
```
but does not appear in the `.bcf` with `citecounter=false,`.

This data is consumed by Biber and relevant for stuff like `sorting=count,`.

Looking at the code, it appears to me that this is the in-text counter and that in case of `context` (where text and footnotes are counted separately) the footnote counter would be ignored.

**Comment by plk** [comment]
I see what  you mean now. Do you think we need to fix `citekeycount` to take into consideration footnotes too? We can add the count to every `\entry` in the `.bbl`:

```
\entry{u1}{misc}{}{<citecount>}
```

Could also be useful in biblatex too as part of an entry via the `.bbl`.

**Comment by plk** [comment]
You can try `biblatex` 3.20 and `biber` 2.20 from the DEV folder on Sourceforge - I have now put the citecounter (when the option is used in `biblatex`) in the `.bbl` which should help with this issue. We still need to decide whether this counter should be combined with the footnote counter for these purposes.

**Comment by moewew** [comment]
I don't really have an opinion on the footnote counter thing. Sorting by citecount is probably a really niche requirement anyway and I'm not sure if people who need it care about `citecounter=context,` vs `citecounter=true,`.

One thing we still need to check is how to deal with this for BibTeX. I don't think we can pass the number of citations to BibTeX, but we still need to keep the `.bbl` syntax in sync.

**Comment by plk** [comment]
In DEV, I just adjusted the `bibtex` `.bbl` to the new format but with no data in there so things should stay as they are in `bibtex`.
