### ISSUE TITLE
end bibliography command doesn't call \@doendpe

### ISSUE THREAD

**Issue by u-fischer** [plk/biblatex#1279]
LaTeX environments call at the end (before closing the group) `\@doendpe`:

~~~~
\@namedef{end }#1{%
  \romannumeral
    \IfHookEmptyTF{env/#1/end}%
        {\expandafter\z@}%
        {\z@\UseHook{env/#1/end}}%
    \csname end#1\endcsname\@checkend{#1}%
    \expandafter\endgroup\if@endpe\@doendpe\fi %<---------
    \UseHook{env/#1/after}%
    \if@ignore\@ignorefalse\ignorespaces\fi
}
~~~~

This allows e.g. lists to change the indentation of the following text depending on if an empty lines follows or not.

biblatex doesn't use a standard bibliography environment but defines the begin and end command manually, and doesn't call `\@doendpe` in this definition

~~~~
\def\blx@endbibliography{%
  \csuse{blx@endenv@\blx@theenv}%
  \blx@noitem
  \blx@locallabelwidth@finish
  \endgroup
  \blx@bibnote\blx@thepostnote
  \endgroup}
~~~~

This isn't much of a problem currently but it confuses and breaks the new code we added to automatically tag lists. So if would be nice if biblatex could adjust its definition. 

You should check if you also want add a `\par` which would force the indentation of following text, without it, text not separated by an empty line would not be indented.

~~~~
\DocumentMetadata{testphase=phase-III}
\documentclass{article}

\usepackage{biblatex}
\addbibresource{biblatex-examples.bib}

\makeatletter
%% without this change the example errors:
%\def\blx@endbibliography{%
%  \csuse{blx@endenv@\blx@theenv}%
%  \blx@noitem
%  \blx@locallabelwidth@finish
%  \endgroup
%  \blx@bibnote\blx@thepostnote
%  %\endgroup %remove
%  \expandafter\endgroup\if@endpe\@doendpe\fi %new
%  %\par %optional, forces indentation of text  behind
%}
\makeatletter

\begin{document}

\begin{center} abc \end{center}

\cite{doody}

\printbibliography 

xxx

\printbibliography xxx
\end{document}
~~~~

**Comment by moewew** [comment]
What exactly do we need here? Is it only `\if@endpe\@doendpe\fi` that we need to add?

Could there be a more official interface for this so that we could just say
```latex
\FlushOutEnvironment
```
instead of tracking the code LaTeX adds in the actual definition.

Logically, should this really go into `\blx@endbibliography` or should it rather be added to something like `blx@endenv@<environment name>`?

**Comment by u-fischer** [comment]
> Could there be a more official interface

hm. There is an official interface, it is called `\newenvironment` ;-)

If you look at the definition in latex.ltx that I mentioned above you can see that environments defined in the normal way do execute `\@doendpe` automatically. 


> Logically, should this really go into \blx@endbibliography or should it rather be added to something like blx@endenv@<environment name>?

I don't know where the second would be called.

**Comment by moewew** [comment]
> hm. There is an official interface, it is called `\newenvironment` ;-)

I was afraid you were going to say that. But I had to try.

I've had a very quick look at the code and I'm not sure if it's possible short-term to turn the macros into an environment.

----

`blx@endenv@<env name>` is called by `\blx@endbibliography` it's the end code of `blx@env@<env name>` called in `\blx@bibliography`. Those two commands are defined when you say `\defbibenvironment`. So logically I'd have thought that *this* is the bibliography environment.

**Comment by u-fischer** [comment]
> I've had a very quick look at the code and I'm not sure if it's possible short-term to turn the macros into an environment.

I didn't want to imply that you should. There is nothing wrong with implementing such an "internal" environment with low-level methods. It is also okay that your implementation leaves out things (e.g. the hooks that you don't need here). The only problem is that the code left also out the `\@doendpe` handling which at the time the code was written was simpler but which is now a problem as in the tagging code the switch is used for more than simply changing the indentation of the next paragraph. 

So you really only need to exchange the `\endgroup` by

~~~~
\expandafter\endgroup\if@endpe\@doendpe\fi
~~~~

or 

~~~~
\expandafter\endgroup\if@endpe\@doendpe\fi
\par
~~~~

The second will reinstate the current behaviour that the first paragraph after a bibliography is always indented.


> `blx@endenv@<env name>` is called by `\blx@endbibliography`. So logically I'd have thought that this is the bibliography environment.

Ah sorry, the csuse at the begin. Well yes, it is an environment too, but normally this is something like `\endlist` and so based on standard LaTeX environments which handles `\@doendpe`. The problem is your additional environment layer with the  `\endgroup`. As a simple example, this here would error with the tagging code too:

~~~~
\begingroup\begin{center} abc \end{center}\endgroup abc
~~~~

One would have to do it like this:
~~~~
\begingroup\begin{center} abc \end{center}\expandafter\endgroup\if@endpe\@doendpe\fi abc
~~~~

I'm rather sure that we will find more places where this will be a problem, but I ran onto biblatex first as I use it for the references in my documentation ...

**Comment by moewew** [comment]
A first attempt to fix this is at https://github.com/plk/biblatex/commit/2fdb63125d349c02b13559f0d0fcbe0cf8d11ad3. Please let me know what you think and give it a quick spin. (I tried to test on MikTeX, but I think some bits of the `latex-lab` package might be missing as I get an error about a missing file `glyphtounicode-cmex.tex` that I downloaded from the TeX Live package, and an error about `\DeclareInstanceCopy` being undefined, which I suppressed by supplying a dummy definition that does nothing. So I have no idea if what I ran has any connection to how things should be.)

**Comment by u-fischer** [comment]
Sorry this question somehow slipped through. The change to `\blx@endbibliography` is fine. 

The change to `\blx@endbiblist` is a good catch too. But be aware that the `\par` slightly changes the behaviour here: a simple `\printbiblist{article} xxxx`  (which internally doesn't use a list) would have printed the xxxx on the same line and now there is a paragraph break (imho that is quite sensible ...).

**Comment by moewew** [comment]
The tests were OK. The changes are in v3.20. So far no one has complained. We'll see...

**Comment by LSinev** [comment]
I am trying to debug (and make an MWE) an issue with a group of `\printbibliography` with custom bibenvironments with counters (like http://tex.stackexchange.com/a/66851) and suppressed heading and titles (with `{}`). Seems like some \par with skip added (like newline for every invisible heading).  For me a hotfix was setting every `\printbibliography` inside `\phantom{}`.
May this be caused by
> be aware that the \par slightly changes the behaviour here

this update?

**Comment by moewew** [comment]
Possibly. There is a change here with potential for changed output. If you can share an example document, I'll have a look at it. 

Note that headings probably shouldn't be suppressed with `title={},` but rather with `heading=none,`. (This may or may not make a difference in your case.)

**Comment by LSinev** [comment]
> If you can share an example document

[biblatex-refsection.zip](https://github.com/user-attachments/files/16740790/biblatex-refsection.zip)

Overleaf TeXLive 2023:
![2024-08-25 18 01 44 www overleaf com b7063f384cea](https://github.com/user-attachments/assets/36a1f8ad-5ece-44cc-94e5-9199046f13ea)


Overleaf TeXLive2024:
![2024-08-25 18 03 09 www overleaf com 147db6cd7759](https://github.com/user-attachments/assets/4e638b47-1b7e-4e11-9e0d-2483147825f2)
