### ISSUE TITLE
Add `keywords` and `notkeywords` to `\printbibliography`

### ISSUE THREAD

**Issue by omnv** [plk/biblatex#1283]
First, a big thank you. `biblatex` has been my go-to for such a wild array of situations of non-english bibliographies that it has become an invaluable tool. I believe I speak for many when I say that `biblatex` is essential for typesetting humanities and art studies as it's been for me. Keep rocking 🚀

## Proposal

- [ ] Add a `keywords` and `notkeywords` keys to the `\printbibliography` command.

### Background

Overall, there's different ways to approach this, and some of them may or may not make sense for the project. Feel free to pick the one that best align to `biblatex`'s scope and goals. The way we arrived to this are also shared, to provide ideas and solutions for authors.

***

Currently, we organize our bibliographies using statuses: _to-review_, _reviewed_; as well as different tags for library location. The options for storing this info in the `.bib` key entry are great, yet when printing bibliographies it involves repetitive keyword filtering, resulting in verbose commands.

When working with dozens of bibliographies that have to be structured in categories, one can approach it like the following:

```latex
\printbibliography[keyword={pdf}, notkeyword={nocite},
title={En PDF}, heading=subbibliography]

\printbibliography[keyword={up}, notkeyword={pdf}, notkeyword={nocite},
title={Library A}, heading=subbibliography]

\printbibliography[keyword={bv}, notkeyword={pdf}, notkeyword={nocite},
title={Library B}, heading=subbibliography]

\printbibliography[keyword={ao}, notkeyword={pdf}, notkeyword={nocite},
title={Library C}, heading=subbibliography]
```

To make the code more compact, we could make a custom wrapper:
```latex
\printbibS{pdf}{}{In PDF}
\printbibS{up}{pdf}{In Library A}
\printbibS{bv}{pdf}{In Library B}
\printbibS{ao}{pdf}{In Library C}
```

Code for the `\printbibS` command:
```latex
\NewDocumentCommand{\printbibS}{m m m}
  {
    \printbibliography[
      keyword={#1},
      keyword={#2},
      notkeyword={nocite},
      heading=subbibliography,
      title={#3}
    ]
  }
```

This could also be approached in a more sophisticated way, with the help of some expl3/latex3, that would allow us to keep things brief and compact:
```latex
\printbibE{pdf,rev}{nocite}{Review PDF}
\printbibE{up,rev}{pdf,nocite}{Review Library A}
\printbibE{bv,rev}{pdf,nocite}{Review Library B}
\printbibE{ao,rev}{pdf,nocite}{Review Library C}
```

Code for the `\printbibE` command:
```latex
\NewDocumentCommand \printbibE {m m m} {
  \seq_clear:N \l_tmpa_seq
  \tl_clear:N \l_tmpa_tl

  \seq_set_from_clist:Nn \l_tmpa_seq { #1 }
  \seq_set_from_clist:Nn \l_tmpb_seq { #2 }

  \seq_map_inline:Nn \l_tmpa_seq
    { \tl_put_right:Nn \l_tmpa_tl {keyword=##1,} }

  \seq_map_inline:Nn \l_tmpb_seq
    { \tl_put_right:Nn \l_tmpa_tl {notkeyword=##1,} }

  \tl_put_right:Nx \l_tmpa_tl
    { title={#3} }

  \expandafter \printbibliography \expandafter[\l_tmpa_tl]
}
```

We could also settle for a more complex implementation, that wraps `\printbibliography` and allows to use the proposed feature:
```latex
\printbibB[
    keywords    = {pdf, rev}
    notkeywords = {nocite}
    title       = {Review PDF}]
\printbibB[
    keywords    = {up, rev}
    notkeywords = {pdf, nocite}
    title       = {Review Library A}]
\printbibB[
    keywords    = {bv, rev}
    notkeywords = {pdf, nocite}
    title       = {Review Library B}]
\printbibB[
    keywords    = {ao, rev}
    notkeywords = {pdf, nocite}
    title       = {Review Library C}]
```

Code for the `\printbibB` command:
```latex
\NewDocumentCommand \printbibB { m }
  {
    \tl_clear:N \l_tmpa_tl

    \keys_set:nn {bibprint} {#1}

    \seq_map_inline:Nn \l_tmpa_seq
      { \tl_put_right:Nn \l_tmpa_tl {keyword=##1,} }

    \seq_map_inline:Nn \l_tmpb_seq
      { \tl_put_right:Nn \l_tmpa_tl {notkeyword=##1,} }

    \tl_put_right:Nx \l_tmpa_tl
      { title = \l_bibprint_title_tl }

    \expandafter \printbibliography \expandafter[\l_tmpa_tl]
  }

\keys_define:nn {bibprint}
  {
    keywords .code:n = {
      \seq_set_from_clist:Nn \l_tmpa_seq {#1}
    },

    notkeywords .code:n = {
      \seq_set_from_clist:Nn \l_tmpb_seq {#1}
    },

    title .tl_set:N = \l_bibprint_title_tl
  }

```

All this code will be not needed when the feature is supported.

## Use case

Adding `keywords` and `notkeywords` as an upstream feature would provide a more standardized and unified solution, providing a simpler and more efficient way to select bibliographies while reducing the need for personal macros. Take the following example:

```latex
\printbibliography[
    keywords    = {pdf, rev, tag},
    notkeywords = {nocite, ex},
    title       = {Review PDF}]
\printbibliography[
    keywords    = {up, rev, tag},
    notkeywords = {pdf, nocite, ex},
    title       = {Review Library A}]
\printbibliography[
    keywords    = {bv, rev, tag},
    notkeywords = {pdf, nocite, ex},
    title       = {Review Library B}]
\printbibliography[
    keywords    = {ao, rev, tag},
    notkeywords = {pdf, nocite, ex},
    title       = {Review Library C}]
```

Compared to the current approach:
```latex
\printbibliography[
    keyword    = {pdf},
    keyword    = {rev},
    keyword    = {tag},
    notkeyword = {nocite},
    notkeyword = {ex},
    title      = {Review PDF}]
\printbibliography[
    keyword    = {up},
    keyword    = {rev},
    keyword    = {tag},
    notkeyword = {pdf},
    notkeyword = {nocite},
    notkeyword = {ex},
    title      = {Review Library A}]
\printbibliography[
    keyword    = {bv},
    keyword    = {rev},
    keyword    = {tag},
    notkeyword = {pdf},
    notkeyword = {nocite},
    notkeyword = {ex},
    title      = {Review Library B}]
\printbibliography[
    keyword    = {ao},
    keyword    = {rev},
    keyword    = {tag},
    notkeyword = {pdf},
    notkeyword = {nocite},
    notkeyword = {ex},
    title      = {Review Library C}]
```

**Comment by plk** [comment]
Just to be clear, you are expecting here `(not)keywords` to be AND or OR? Currently multiple repeated `(not)keyword` are always ANDed but I suspect you want OR? I suspect the ideal would be that the csv of `(not)keywords` would be ORed and multiple `(not)keywords` would be ANDed.

**Comment by mnrvwl** [comment]
Excellent question. AND would be fantastic 💯  It's the same behaviour of multiple `keyword`, the behaviour of my macros, and what I mostly use. The OR behaviour could be named as `orkeywords = {apple, peaches}`.

If you want `keywords` to be OR by default, `andkeywords` could be used to select the AND behaviour, that'd be okay by me.

**Comment by plk** [comment]
I think `keywords` would be naturally and OR set - that is, any of those keywords would be included. AND seems a little odd. Most natural would be:

```
keywords={key1, key2}
keywords={key3, key4}
```

to mean "Either of `key1` or `key2` and also either of `key3` and `key4`. The AND is relatively easy to implement, the OR less so.

**Comment by mnrvwl** [comment]
Intersting! I see keywords as an array where I'm querying something that contains _all_ of the array elements. Regardless, I'm happy to have an AND too! Feel free to choose whatever name that best suits the project, you have a lot of experience with it. Whatever the behavior is fine as long as reflected in the docs 👍🏻

About OR, I don't know the codebase. How do you feel about adding a layer, that constructs strings and passes it to `\printbibliography`, like I did above?

**Comment by mnrvwl** [comment]
@moewew This is fantastic, thanks! I totally didn't know about it —one day I'll know all of the ~350 pages—. Custom filters are amazing, will start rewriting some stuff right now 🚀 At the same time I can see there's still benefit of exploring a higher-level syntax for both `\defbibfilter` and `\printbibliography`.

**Comment by plk** [comment]
I sometimes forget half the features in this beast ... I can see the case for csv for some common filters like keyword but let's see if the custom filters will do it for you.

**Comment by mnrvwl** [comment]
No worries! My use case was already covered by either writing a lot of keyword/notkeyword or by my own latex3 macros. I only thought it'd be interesting to have a more concise syntax to express the same and wanted to share it.
