### ISSUE TITLE
How to disable plural bibstrings

### ISSUE THREAD

**Issue by matteo339** [plk/biblatex#1284]
Biblatex uses many bibstrings in the singular or plural form automatically (e.g., regarding the `pages` field or `postnote` argument).

In Italian bibliographies the use of the plural form is not always welcome. For example, it is quite common to cite a page range in the format 'p. 56-71' instead of 'pp. 56-71'.

I would like to know if it is possible to inhibit this automatic mechanism in order to use only the singular form (obviously without changing every single bibstring in the localization file).

Matteo

**Comment by moewew** [comment]
Not really, no. The singular and plural strings are completely independent in the `.lbx` file syntax and (bib)macros essentially hard code the singular-plural selection https://github.com/plk/biblatex/blob/8e9e5641a68c596f46f13dde9b7f56e37d50db78/tex/latex/biblatex/biblatex.sty#L3440-L3447, https://github.com/plk/biblatex/blob/8e9e5641a68c596f46f13dde9b7f56e37d50db78/tex/latex/biblatex/biblatex.sty#L3467-L3481

https://github.com/plk/biblatex/blob/8e9e5641a68c596f46f13dde9b7f56e37d50db78/tex/latex/biblatex/biblatex.def#L2553-L2565

https://github.com/plk/biblatex/blob/8e9e5641a68c596f46f13dde9b7f56e37d50db78/tex/latex/biblatex/biblatex.def#L2567-L2585

You'd either have to redefine the relevant strings (which is more appropriate in my book) or modify all (bib)macros with a singular-plural distinction to use only the singular form (lots of work in possibly internal commands).

**Comment by matteo339** [comment]
Thank you for the quick response.

Surely the easiest way would be to redefine the (bib)strings. I would like to have a general pattern, though, so I would like to modify the relevant (bib)macros.

If I wanted to eliminate _tout court_ the use of the plural form, it doesn't seem particularly difficult to modify the macros above.

The problem is that I only want to inhibit the plural form when `abbreviate=true` (obviously it makes sense to cite a range of pages in the format 'p. 56-71', but not as 'page 56-71').

In the biblatex source codes I could not find anything about the `abbreviate` option.

It would be great if you could explain how to modify these four macros when `abbreviate=true`.

Matteo

PS: if this is not the right place to get answer to a specific need, I will post a help request on http://tex.stackexchange.com

**Comment by moewew** [comment]
If we are working within these parameters, I strongly believe the only semantically sane course of action is to redefine the relevant plural bibstrings.

If you redefine the bibmacros to ignore the singular/plural distinction you can never be sure that you have redefined all relevant places where these things pop up, because third-party styles could roll their own macros that distinguish singular and plural again. Especially with `\blx@mkpageprefix` and `\blx@mkpagetotal` you'd be redefining internal macros, whose definition might change.

The fact that you only want to change things if `abbreviate=true,` is active suggests that even in this context singular and plural are grammatically relevant concepts: The only thing you don't like is the abbreviated form of the plural string. You don't, as such, object to the singular-plural distinction. Redefining these macros in a way to ignore the singular/plural distinction will cause issues if you use languages that do have this distinction besides Italian in your document.

----

The `abbreviate` option is implemented as follows,

https://github.com/plk/biblatex/blob/8e9e5641a68c596f46f13dde9b7f56e37d50db78/tex/latex/biblatex/biblatex.sty#L15215-L15218

hence one way to check if it is enabled is to compare `\abx@str` to a macro with replacement text `abx@sstr`.

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear, abbreviate=false]{biblatex}

\makeatletter
\def\matteobbx@shortstring{abx@sstr}
\newcommand*{\IfBiblatexAbbreviates}{%
  \ifdefequal\abx@str\matteobbx@shortstring
}
\makeatother

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite{sigfridsson}

\IfBiblatexAbbreviates{T}{F}

\printbibliography
\end{document}
```

**Comment by matteo339** [comment]
First of all, thank you for your help.
> If you redefine the bibmacros to ignore the singular/plural distinction you can never be sure that you have redefined all relevant places where these things pop up, because third-party styles could roll their own macros that distinguish singular and plural again.

I'm creating a biblatex styles bundle built on your biblatex-ext bundle, so I'm sure I don't have conflicts with third-party styles (in this way I also have the opportunity to learn a lot of the biblatex macros/commands).

> Redefining these macros in a way to ignore the singular/plural distinction will cause issues if you use languages that do have this distinction besides Italian in your document.

You are absolutely right. In fact, I plan to create a global option - like `singularpage=true|false` - so that I can enable/disable the (bib)strings plural form when needed.

Below a mwe
```
% !TEX encoding = UTF-8 Unicode
% !TEX program = lualatex
% !BIB program = biber

\begin{filecontents}[overwrite]{\jobname.bib}
@MvCollection{cassese2003,
  date       = {2003},
  editor     = {Cassese, Sabino},
  title      = {Trattato di diritto amministrativo},
  location   = {Milano},
  publisher  = {Giuffrè},
  volumes    = {7},
}
@InCollection{caia2003,
  author    = {Caia, Giuseppe},
  booktitle = {Le funzioni di ordine. Le funzioni del benessere},
  title     = {L'ordine e la sicurezza pubblica},
  pages     = {281-305},
  volume    = {1},
  crossref  = {cassese2003},
}
\end{filecontents}

\documentclass{article}
\usepackage{polyglossia}
  \setmainlanguage{english}
\usepackage{csquotes}
\usepackage[style=authoryear]{biblatex}
  \addbibresource{\jobname.bib}

\makeatletter
\newtoggle{bbx:singular@abbrev}
\DeclareBibliographyOption{singularpage}[true]{\settoggle{bbx:singular@abbrev}{#1}}
\makeatother

\ExecuteBibliographyOptions{%
  abbreviate = true,
  singularpage = true, % personal option
}

\makeatletter

\def\matteobbx@shortstring{abx@sstr}
\newcommand*{\IfBiblatexAbbreviates}{%
  \ifdefequal\abx@str\matteobbx@shortstring}

\protected\long\def\blx@mkpageprefix#1[#2]#3{%
  \ifnumeral{#3}
    {\bibstring{#1}\ppspace}
    {\ifnumerals{#3}
      {\ifboolexpr{
        not test {\IfBiblatexAbbreviates}
        or
        ( test {\IfBiblatexAbbreviates} and not togl {bbx:singular@abbrev} ) }
        {\bibstring{#1s}}
        {\bibstring{#1}}%
        \ppspace}
      {\def\pno{\bibstring{#1}}%
        \def\ppno{\bibstring{#1s}}}}%
  \blx@mkpageprefix@i[{#2}]{#3}}

\protected\long\def\blx@mkpagetotal#1[#2]#3{%
  \ifnumeral{#3}
    {\setbox\@tempboxa=\hbox{%
        \blx@tempcnta0#3\relax
        \ifnum\blx@tempcnta=\@ne
          \aftergroup\@firstoftwo
        \else
          \aftergroup\@secondoftwo
        \fi}%
      {#2{#3}\ppspace\bibstring{#1}}
      {#2{#3}\ppspace\ifboolexpr{
        not test {\IfBiblatexAbbreviates}
        or
        ( test {\IfBiblatexAbbreviates} and not togl {bbx:singular@abbrev} ) }
        {\bibstring{#1s}}
        {\bibstring{#1}}}}
    {\def\pno{\bibstring{#1}}%
      \def\ppno{\bibstring{#1s}}%
      #2{#3}}%
  \endgroup}

\DeclareFieldFormat{volumes}{#1~\ifboolexpr{
  test {\IfBiblatexAbbreviates} and togl {bbx:singular@abbrev} }
  {\bibstring{volume}}
  {\bibstring{volumes}}}

\makeatother

\begin{document}
\autocite[294-299]{caia2003}
\printbibliography
\end{document}
```
Note that I chose to modify only the `blx@mkpageprefix` and `blx@mkpagetotal` macros. Furthermore, I checked the localization files: for this I also modified the `volumes` string format.

Matteo

**Comment by moewew** [comment]
As I said above, I believe this is the wrong approach semantically, but if it works for you, it works for you.

I'd just have created a variant of `italian.lbx`, called say `italian-sgpl.lbx`, that inherits everything except for the plural strings from `italian.lbx`. You can then select the desired behaviour with `\DeclareLanguageMapping{italian}{italian-sgpl}` in your document preamble. Almost like an option, but much cleaner in the implementation.
```latex
\documentclass[italian]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear]{biblatex}

\DeclareLanguageMapping{italian}{italian-sgpl}

\begin{filecontents}{italian-sgpl.lbx}
\InheritBibliographyExtras{italian}

\DeclareBibliographyStrings{%
  inherit          = {italian},
  volumes          = {{volumi}{vol\adddot}},
  pages            = {{pagine}{p\adddot}},
  columns          = {{colonne}{col\adddot}},
  lines            = {{righe}{r\adddot}},
  verses           = {{versi}{v\adddot}},
  pagetotals       = {{pagine}{p\adddot}},
  columntotals     = {{colonne}{col\adddot}},
  linetotals       = {{righe}{r\adddot}},
  versetotals      = {{versi}{v\adddot}},
  paragraphtotals  = {{paragrafi}{par\adddot}},
}
\end{filecontents}

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite[380]{sigfridsson}
ipsum \autocite[381-382]{sigfridsson}

\printbibliography
\end{document}
```

**Comment by matteo339** [comment]
As already written, I wanted to modify the (bib)macros because I wanted to create a general model that would apply to any language. However, I admit that this is not a real need, since my biblatex styles are designed for my own use. Therefore, I also think that the best solution is to customize the localization files.

See you soon,
Matteo

**Comment by moewew** [comment]
As discussed here, I don't think we want this as a core feature. But since you have your answer, I think we can close this as "won't fix".
