### ISSUE TITLE
How to disable `\citetitle` in the index

### ISSUE THREAD

**Issue by onmv** [plk/biblatex#1285]
The indexing options: `true`, `false`, `bib` and `cite` are really useful, but they have some limitations when it comes to trying to switch off `\citetitles` from appearing in the index. I did the following to accomplish it:

```latex
\DeclareCiteCommand{\citetitle} {
  \boolfalse{citetracker}
  \boolfalse{pagetracker}
  \usebibmacro{prenote}
} {
  \printfield[citetitle]{labeltitle}
} { \multicitedelim } { \usebibmacro{postnote} }
```

If there's a better way to accomplish this please let me know 💯

MWE:
```latex
\documentclass{report}

\usepackage[style=philosophy-verbose,backend=biber]{biblatex}
  \ExecuteBibliographyOptions{
    hyperref = true,
    indexing = cite,
    autocite = footnote
  }

  \begin{filecontents*}{test.bib}
    @book{aristotle:physics,
      author     = {Aristotle},
      title      = {Physics},
      publisher  = {G. P. Putnam},
      location   = {New York},
      date       = 1929
    }
  }
  \end{filecontents*}
  \addbibresource{test.bib}

  % Remove comment to get the desired index behavior:
  %
  % \DeclareCiteCommand{\citetitle} {
  %   \boolfalse{citetracker}
  %   \boolfalse{pagetracker}
  %   \usebibmacro{prenote}
  % } {
  %   % \ifciteindex{\indexfield{indextitle}}{}%
  %   \printfield[citetitle]{labeltitle}
  % } { \multicitedelim } { \usebibmacro{postnote} }

\usepackage{imakeidx}
  \makeindex[title={Authors Index}, columns=2]
\usepackage[hidelinks]{hyperref}
\usepackage{footnotebackref, bookmark}

\begin{document}
  This book \citetitle{aristotle:physics} [...]
  was relevant because \autocite[32-64]{aristotle:physics}

  \printbibliography
  \printindex
\end{document}
```

**Comment by moewew** [comment]
Yeah, if you don't want `\citetitle` to produce an index entry, then removing the entire `\ifciteindex` chunk from

https://github.com/plk/biblatex/blob/8e9e5641a68c596f46f13dde9b7f56e37d50db78/tex/latex/biblatex/biblatex.def#L2211-L2220

is certainly a good way.

Often options only give you higher-level control over things. For fine-grained control options would get messy and you are usually better off redefining the involved objects directly.

**Comment by onmv** [comment]
Thanks for the feedback! I'll close, it's an interesting idea for a higher level-option.

**Comment by moewew** [comment]
Within the current framework I cannot really see a sane and backwards-compatible way to implement an option to selectively disable indexing (for only certain bits) in specific commands. But that's not necessarily bad. I firmly believe that not everything has to be an option. Sure, options are convenient and easy to understand, but some interfaces just don't lend themselves to an option implementation. Of course if anyone has a useful idea here, please go ahead and share it.

As for adding this particular redefinition to the documentation: I can't really see a good place for it. It is generally understood that at some point you have to look at the code of the relevant commands and enshrining certain definitions in the documentation may give the wrong impression (styles are free to redefine `\citetitle` in a different way). (Plus the documentation is so long already that it is hard to find what you are looking for [unless you already know the answer].)

----

Please note that the redefinition as shown in the first post will introduce several undesired spaces.

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=philosophy-verbose,backend=biber]{biblatex}


\DeclareCiteCommand{\citetitle} {
  \boolfalse{citetracker}
  \boolfalse{pagetracker}
  \usebibmacro{prenote}
} {
  \printfield[citetitle]{labeltitle}
} { \multicitedelim } { \usebibmacro{postnote} }

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite{sigfridsson}

A\citetitle{sigfridsson}B

X\citetitle{aristotle:physics}Y

\printbibliography
\end{document}
```

You need to "hide" line ends with `%` and avoid space around curly braces.
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=philosophy-verbose,backend=biber]{biblatex}


\DeclareCiteCommand{\citetitle} 
  {\boolfalse{citetracker}% 
   \boolfalse{pagetracker}% 
   \usebibmacro{prenote}} 
  {\printfield[citetitle]{labeltitle}} 
  {\multicitedelim} 
  {\usebibmacro{postnote}} 

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite{sigfridsson}

A\citetitle{sigfridsson}B

X\citetitle{aristotle:physics}Y

\printbibliography
\end{document}
```

**Comment by onmv** [comment]
You're absolutely right. I had it surrounded by an `\ExplSyntaxOn`, `\ExplSyntaxOff` block that prevents from accidental spaces being inserted.
