### ISSUE TITLE
Probable bug: punctuation & polyglossia with english language

### ISSUE THREAD

**Issue by matteo339** [plk/biblatex#1286]
Below a mwe:
```
% !TEX encoding = UTF-8 Unicode
% !TEX program = lualatex
% !BIB program = biber

\begin{filecontents}[overwrite]{\jobname.bib}
@inbook{key,
  author = {Author},
  title = {Title},
  booktitle = {Booktitle},
}
\end{filecontents}

\documentclass{article}
\usepackage{polyglossia}
  \setmainlanguage{english}
\usepackage{biblatex}
  \addbibresource{\jobname.bib}

\begin{document}
\nocite{*}
\printbibliography
\end{document}
```
If a field is formatted in quotation marks (e.g. `title` into `@article`, `@inbook`, `@incollection`, etc.), then punctuation is put **inside** the quotation marks.
<img width="323" alt="Screenshot 2023-05-25 at 14 35 10" src="https://github.com/plk/biblatex/assets/111273603/588ffe36-1220-4863-9cd8-fb2df81286d8">
I am not sure if this happens only with English; however, it does not happen with other languages I have tried (like Italian, French, German, and Spanish).

Matteo

**Comment by matteo339** [comment]
Thank you for the clarification. I didn't catch this particular linguistic aspect.

Matteo

**Comment by moewew** [comment]
Alright. Closing this since it works as expected and advertised.
