### ISSUE TITLE
inaccuracy into reference manual

### ISSUE THREAD

**Issue by matteo339** [plk/biblatex#1289]
In section 2.2.4 (Custom Fields) `verb[a–c]` is defined as a _literal_ field instead of a _verbatim_ field.

<img width="764" alt="Screenshot 2023-06-14 at 12 22 34" src="https://github.com/plk/biblatex/assets/111273603/e8561f2d-4e6f-4cc7-b25e-6def4bb852e2">

Matteo

**Comment by plk** [comment]
Many thanks, fixed in DEV branch.
