### ISSUE TITLE
How to make `\citeauthor` to not add entries to `\printbibliography`

### ISSUE THREAD

**Issue by onmv** [plk/biblatex#1290]
I'd like to use `\citeauthor` as a way of mentioning the author when the work _per se_ is not being referenced, while automatically indexing each time it's mentioned. I've experimented redefining it with `\DeclareCiteCommand` and didn't get the wanted result.

```latex
\documentclass{article}

\usepackage[style=verbose]{biblatex}
  \ExecuteBibliographyOptions{
    hyperref = true,
    indexing = cite,
    autocite = footnote
  }
  \begin{filecontents*}{test.bib}
    @book{aristotle:physics,
      author     = {Aristotle},
      title      = {Physics},
      publisher  = {G. P. Putnam},
      location   = {New York},
      date       = 1929
    }
  }
  \end{filecontents*}
  \addbibresource{test.bib}
\usepackage{imakeidx}
  \makeindex[title={Authors Index}, columns=2]
\usepackage[hidelinks]{hyperref}

\begin{document}
  \noindent \citeauthor{aristotle:physics} [...]
  \printbibliography
  \printindex
\end{document}
```

Note: I posted the [question](https://tex.stackexchange.com/q/688837/297525) in TeX.se also, I was told to use `\begin{refsection}` and want to know if there's a better way. The reason I'm asking it here too is because the maintainers always gave me good feedback. If you'd rather me redirecting how-to's to TeX.se only I'd be happy too 🤍

**Comment by moewew** [comment]
This is a classical question for TeX.SX and in its current form not quite appropriate for the bug tracker, where we discuss bugs and feature requests. I have added a slightly longer discussion in TeX.SX and will close this here. (I know that the line between question and feature request is a fine one, but I feel that asking on TeX.SX and on the bug tracker at the same time is a bit much...)

**Comment by onmv** [comment]
Sounds good thx!
