### ISSUE TITLE
Command to print full name of author

### ISSUE THREAD

**Issue by claell** [plk/biblatex#1291]
I am aware of `\citeauthor`, but that only prints the last name of the author.

Are there already options for (or derivates of) that command to print the full (first and last) name of the author?

If not, can this be added?

**Comment by moewew** [comment]
`\citeauthor` is defined as

https://github.com/plk/biblatex/blob/8d3345f0735c23d6886cf1fb0cf6350b2c526253/tex/latex/biblatex/biblatex.def#L2189-L2198

and thus uses the `labelname` format, which is given as

https://github.com/plk/biblatex/blob/8d3345f0735c23d6886cf1fb0cf6350b2c526253/tex/latex/biblatex/biblatex.def#L959-L986

If you want a different output, you can just define it with an explicitly different name format - or you could redefine the `labelname` format if more cite-like commands should print full names.

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear]{biblatex}

\DeclareCiteCommand{\citeauthorfullname}
  {\boolfalse{citetracker}%
   \boolfalse{pagetracker}%
   \usebibmacro{prenote}}
  {\ifciteindex
     {\indexnames{labelname}}
     {}%
   \printnames[default]{labelname}}
  {\multicitedelim}
  {\usebibmacro{postnote}}

\addbibresource{biblatex-examples.bib}

\begin{document}
\autocite{sigfridsson}

\citeauthor{sigfridsson}

\citeauthorfullname{sigfridsson}

\printbibliography
\end{document}
```

**Comment by claell** [comment]
Thanks! I'll use that for now, then. Is there any chance that such options will be added to biblatex in the future, so one doesn't need to set up own commands for this?

**Comment by moewew** [comment]
No. I don't think we will add a new command for this. While `biblatex` defines a couple of helper `\...cite...` commands by default there was always the understanding that the core cannot define commands for all conceivable uses. Instead `biblatex` offers interfaces for users to define the commands they need themselves. In your case `\DeclareCiteCommand` and friends.

**Comment by claell** [comment]
Alright!

Then I'll close this at this stage with a working solution (thanks again for that)!
