### ISSUE TITLE
Possible bug with ISBN verification

### ISSUE THREAD

**Issue by pauloney** [plk/biblatex#1299]
I have a small file where the ISBN checking fails with the message:

````
WARN - ISBN '978-65-990528-9-7' in entry 'promenade:pt' is invalid - run biber with '--validate_datamodel' for details.

````

on TL 23, but it is a perfectly valid ISBN, as one can see [here](https://www.cblservicos.org.br/isbn/pesquisa/?page=1&q=978-65-990528-9-7&filtrar_por%5B0%5D=isbn&ord%5B0%5D=relevancia&dir%5B0%5D=asc]).

The code:

````
\begin{filecontents}{t.bib}
@book { promenade:pt,
    AUTHOR = {Ghys, Étienne},
     TITLE = {A singular mathematical promenade},
 PUBLISHER = {Editora do IMPA},
      YEAR = {2020},
     PAGES = {x+336},
      ISBN = {978-65-990528-9-7},
       url = {https://perso.ens-lyon.fr/ghys/articles/Passeio},
}
\end{filecontents}

\documentclass{report}

\usepackage{biblatex}
\addbibresource{t.bib}

\begin{document}

\nocite{*}
\printbibliography

\end{document}
````

**Comment by plk** [comment]
I can't seen to replicate this with 2.20 DEV at least - I get no warning and nothing if I use the datamodel validation either. Which version and command-line?

**Comment by pauloney** [comment]
pdflatex t
biber t

**Comment by plk** [comment]
Which version of biber?

**Comment by pauloney** [comment]
Biber 2.19

**Comment by moewew** [comment]
I can confirm that Biber 2.19 complains about this ISBN.

It is not unheard of that publishers mess up hyphens in ISBNs, though, see https://github.com/plk/biber/issues/384 (and linked discussions). The LOC formatter (https://www.loc.gov/programs/preassigned-control-number/isbn-converter/) seems to have issues with this ISBN as well.

It's also possible that the relevant block was only added by the ISBN agency so recently that our Biber versions were built with software where the block was not yet known (you can see the number of updates the ISBN data get in https://github.com/briandfoy/business-isbn-data/commits/master).

**Comment by plk** [comment]
@moewew - can you check with 2.20 DEV? It is fine for me with that version. Could be as you say - the ISBN data is newer in the library for 2.20

**Comment by moewew** [comment]
I grabbed the Windows 64bit binary from SF and still get the warning.

**Comment by plk** [comment]
Hmm, I wonder if this was therefore changed very recently. I can rebuild the 2.20 binaries and see?

**Comment by moewew** [comment]
Worth a try.

**Comment by plk** [comment]
2.20 win binaries should be updated now.

**Comment by moewew** [comment]
Just grabbed the updated Windows 64bit binary. Still no joy.

I had a look at the unpacked `Business::ISBN::Data` in the cache. It contains a `RangeMessage.xml` that does not agree with the one currently downloadable at https://www.isbn-international.org/range_file_generation#. Furthermore, its `Data.pm` has
```perl
$VERSION = '20191107';
```
where the current version of https://github.com/briandfoy/business-isbn-data/blob/master/lib/Business/ISBN/Data.pm has [`our $VERSION = '20230811.001';`](https://github.com/briandfoy/business-isbn-data/blob/369135d4e85cc3493874741585b048c57c4a9827/lib/Business/ISBN/Data.pm#L10).

Maybe the build farm has an outdated version of the package?

**Comment by plk** [comment]
Good point. Will update and try again.

**Comment by plk** [comment]
Updated all binaries with new ISBN data

**Comment by moewew** [comment]
The warning is gone in the Windows 64bit 2.20 DEV binary.

**Comment by pauloney** [comment]
Just a question before we close this one:

So it is really true that the way the ISBN is verified is not by algorithm, but by downloaded data from a certain(s) repository?

Would this make it nearly impossible to verify any freshly assigned ISBNs? 

Is there a way to independently, or even automatically, download the fresh data to keep one's TL instalation functional?

Many thanks!

**Comment by plk** [comment]
It's some XML file included with the `Business::ISBN` perl module ...

**Comment by briandfoy** [comment]
I'm just seeing this, and there's a few things to clear up as the maintainer of the Business::ISBN Perl module.

1. Publishers have mistakes in their own data. That was the impetus for the module. Those mistakes could be anything from simple keying mistakes, OCR errors, or mistakes from their own software. I have also run into some rogue ISBNs that the publisher wasn't assigned and used anyway.
2. The data for the valid group and publisher code *ranges* in Business::ISBN come directly from the ISBN Agency. It's not a list of assigned values, but of values that could be assigned. So yes, a valid ISBN is verified by algorithm. Checking that it is *assigned* is something different. There used to be a service called xISBN, but that shut down years ago. As noted in 1), publishers often don't have the best lists of what they've assigned.
3. The ISBN::Agency publishes the RangeMessage.xml file sporadically, but on a monthly sort of schedule so you should update data frequently. For Business::ISBN::Data, I have a GitHub workflow that checks every day, and I mostly release the same day that it discovers a new RangeMessage.xml. 
4. Business::ISBN::Data gives you several ways to update the data, as described in the docs:
4a. You could just update Business::ISBN::Data every day, and on most days it will just be "up to date": `cpan Business::ISBN::Data`
4b. Similarly, you could just download RangeMessage.xml every day. Somedays it will not have changed. You can set its location in the ISBN_RANGE_MESSAGE environment variable and Business::ISBN::Data will find it and use it. As a side note, all the stuff you'd do

**Comment by plk** [comment]
Thanks for the information @briandfoy - I think something in our docs referring to the env var possibility would be the best idea as we release only a few times per year and this the data file is set in stone to the releases but the env var would allow users to use an up-to-date version.

**Comment by pauloney** [comment]
Can anyone point to where this file resides (on the net) and in the local
structure? I was not able to locate either one.

I did "sudo cpan Business::ISBN::Data", and it seems that everything ran
all right, including termination with the message:

Fetching with LWP:
http://www.cpan.org/modules/03modlist.data.gz
Reading '/root/.cpan/sources/modules/03modlist.data.gz'
DONE
Writing /root/.cpan/Metadata
Business::ISBN::Data is up to date (20240308.001).

but when I run biber on a file with ISBN = 978-65-990528-3-5, I get the
message:

WARN - ISBN '978-65-990528-3-5' in entry 'LimaAL' is invalid - run biber
with '--validate_datamodel' for details.

despite the fact that this ISBN has been assigned four years ago, as you
can see here:

    https://www.cblservicos.org.br/isbn/pesquisa/

[image: Screenshot from 2024-03-10 13-39-59.png]

I would like to find out what is breaking and where.

Paulo Ney

**Comment by pauloney** [comment]
The file, I can see now is at:


https://raw.githubusercontent.com/briandfoy/business-isbn-data/master/lib/Business/ISBN/RangeMessage.xml

and it does includes the range for the problematic ISBN above, and it has
included it for some time. So I am wondering where does it go in the
BibLaTeX tree and why biber complains about the wrong ISBN.

Paulo Ney

**Comment by plk** [comment]
The best solution for an installed `biber` would be to get the file and then put it somewhere and point to it with the environment variable `ISBN_RANGE_MESSAGE`. In a binary `biber` installation, you could theoretically just search for the file in the `biber --cache` location and replace it but the environment variable method is likely a better solution.
