### ISSUE TITLE
"spurious" parentheses in authoryear styles

### ISSUE THREAD

**Issue by matteofg** [plk/biblatex#1301]
In authoryear styles, if the `year/date` field is not entered, "spurious" parentheses remain.
```
% !TEX encoding = UTF-8 Unicode
% !TEX program = lualatex
% !BIB program = biber

\begin{filecontents}[overwrite]{\jobname.bib}
@article{a,
  author = {Williams, Robert},
  title = {Title of the article},
  journaltitle = {Journaltitle},
}
\end{filecontents}

\documentclass{article}
\usepackage[style=authoryear]{biblatex}
  \addbibresource{\jobname.bib}

\begin{document}
\autocite{a}
\printbibliography
\end{document}
```
<img width="556" alt="Screenshot 2023-08-16 at 10 08 44" src="https://github.com/plk/biblatex/assets/111273603/aa84f59a-f391-4d21-9cb3-cabf897fcd69">

**Comment by plk** [comment]
Well, `year/date` is a required field for articles ... (p. 9 of the manual) and running `biber` with `--validate-datamodel` will tell you this.

**Comment by moewew** [comment]
See also the second part of the discussion in https://github.com/plk/biblatex/issues/793.

**Comment by matteo339** [comment]
I read the discussion [#793](https://github.com/plk/biblatex/issues/793).
In my opinion, if PL had wanted to emphasize the mandatory nature of the year/date field, the output of authoryear could have simply been as follows:

> Doe, Jane and John Due (). “Example title”. In: Topnotch Studies 4.1, pp. 1-13.

and not

> Doe, Jane and John Due (n.d.). “Example title”. In: Topnotch Studies 4.1 (), pp. 1–13.

The presence of (n.d) implies that the exception of an undated bibliographic entry was expected.

However, I have seen that in the `biblatex-ext` bundle, in the authortitle styles, the `{issue+date}` macro has been redefined by adding the appropriate conditional. So, for consistency, in `biblatex-ext` it would be desirable to do that for the authoryear styles as well (imho).

**Comment by moewew** [comment]
It may be more instructive to look at the output in a non-`authoryear` style, because those don't have to have the citation label after the author name. (For one, early versions of `biblatex` didn't have `nodate` at all. It was added in later.)

---

What `biblatex-ext` does is not immediately relevant for core `biblatex`. Bugs for `biblatex-ext` should be reported at https://github.com/moewew/biblatex-ext/issues.

**Comment by matteo339** [comment]
> What` biblatex-ext` does is not immediately relevant for core `biblatex`. Bugs for `biblatex-ext` should be reported at https://github.com/moewew/biblatex-ext/issues.

Of course -- it was my intention to do that as soon as this discussion was over.
