### ISSUE TITLE
Providing an AIMS Energy bibliography style as an option

### ISSUE THREAD

**Issue by Basmah1961** [plk/biblatex#1309]
Is it possible to include a new bibliography style as required by AIMS Energy? Their LaTeX template and bibliography sample is given in the following link
[https://www.aimspress.com/aimse/news/solo-detail/instructionsforauthors#File](url)

**Comment by moewew** [comment]
What @josephwright said. We simply wouldn't have the capacity to write (and maintain!) requested styles to the level of detail required for release with `biblatex` CTAN.
