### ISSUE TITLE
typo in documentation 

### ISSUE THREAD

**Issue by hvoss49** [plk/biblatex#1314]
page 68 of current TL23 documentation:

labeltitleyear=true, false                        default: false
Whether or not to provide the special field. extratitleyear, see §4.2.4 for details. Note that the specialfield labeltitle is always provided and this option controls rather whether labeltitle is used to generate extratitleyear information.

Shouldn't it be "labletitleyear",  instead of "labletitle". ?

**Comment by plk** [comment]
Many thanks Mr V, fixed in DEV.
