### ISSUE TITLE
How to encode multi-script authors?

### ISSUE THREAD

**Issue by yannis1962** [plk/biblatex#1332]
Hi,

until now I used the following code:

```
@BOOK{fang1981a,
   AUTHOR = {Fang, Guoyu and He, Zhiwu},
   AUTHOR_ORIGINAL = {方国瑜 and 和志武},
   AUTHOR_ORIGINAL+AN = {1=zh-Hans;2=zh-Hans},

```
to obtain

Fang, Guoyu [方国瑜] and Zhiwu He [和志武] (1981)

that is, to obtain first the transliteration and then the original author names, sorted according to the transliteration.

In the current biber-ms and biblatex-ms, this doesn't work anymore.

How should I modify the code to obtain the same result?

I'm using the following biblatex style:

```
\usepackage[natbib=true,style=authoryear-icomp-ms,maxcitenames=4,mincitenames=1,backend=biber-ms,uniquename=minfull]{biblatex-ms}
\renewcommand\bibnamedash{\mbox{\rule[.5ex]{15mm}{0.4pt}\space}}
\renewcommand\compcitedelim{;\space}
```

Please tell me what to use, to obtain the same result.

Thanks in advance,

**Comment by plk** [comment]
Have a look at the  example document on the multiscript branch:

https://github.com/plk/biblatex/blob/multiscript/doc/latex/biblatex/examples/98-multiscript.tex

Would also need to see a full MWE as you would have to modify some standard macros to get the results you note.

**Comment by plk** [comment]
Better suited to a TSE question.
