### ISSUE TITLE
How to make autocite/textcite work as footfullcite

### ISSUE THREAD

**Issue by etclub** [plk/biblatex#1333]
From the manual, I get that there is an option `autocite=footnote`.
But it only produce an reference number in the footnote with `\autocite{something}`.
What I want is to have the bibliography item  in the footnote instead, just like `\footfullcite{something}` does.
I wonder if it is possible to make autocite/textcite work as footfullcite.

**Comment by moewew** [comment]
Sure, you can set up `autocite` to produce `\footfullcite`. There is no predefined option for it, so you will have to do that yourself as follows
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear]{biblatex}

\DeclareMultiCiteCommand{\footfullcites}[\mkbibfootnote]{\footfullcite}{\multicitedelim}
\DeclareAutoCiteCommand{fullfootnote}[f]{\footfullcite}{\footfullcites}
\ExecuteBibliographyOptions{autocite=fullfootnote}


\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite{sigfridsson}
ipsum \autocite{worman}
dolor \autocite{geer}
sit \autocites{nussbaum}{moraux}
dolor \autocite{knuth:ct:b}

\printbibliography
\end{document}
```
Generally speaking I think that `\fullcite` and `\footfullcite` should be used sparingly, though, so if you find yourself using it very often, you might want to rethink your citation style or at least your implementation of that style. (The `verbose` styles have a full first citation and shortened subsequent citations.)

**Comment by etclub** [comment]
Well, it is required by my university to use `\fullcite` and `\footfullcite` in my thesis.
I tried your example. It works like a charm for `autocite`.
But for `textcite`, say
```
...
%sit \autocites{nussbaum}{moraux}
sit \textcites{nussbaum}{moraux}
...
```
those two bibliography items are not presented in the footnote.


BTW, I have little knowledge on style implementation. I will try to read the `verbose` style.

**Comment by moewew** [comment]
What's the expected outcome here for `\textcite`? Anyway, as it stands at the moment I feel that a question like this would be better asked at your favourite TeX forum (e.g. [TeX.SX](https://tex.stackexchange.com/)). The implementation of a specific citation style is "off-topic" for the bug tracker unless during the process you happen to find a bug or can formulate a request for a new and generally useful feature.

**Comment by etclub** [comment]
I upload the pdfs for comparison. One has `sit \autocites{nussbaum}{moraux}`, while the other has `sit \textcites{nussbaum}{moraux}`.
You will find that the two items of `\textcites{nussbaum}{moraux}` are missing in the footnote.
I expect that `\textcite` should work just like `\autocite` (the cited items show in the footnoot as well), besides the author names show in the text.

[test-textcite.pdf](https://github.com/plk/biblatex/files/13984229/test-textcite.pdf)

[test-autocite.pdf](https://github.com/plk/biblatex/files/13984227/test-autocite.pdf)

**Comment by moewew** [comment]
It's not generally the case that `\textcite` works just like `\autocite` but includes the author name, especially if you change the behaviour of `\autocite` with the `autocite` option. The `verbose` styles have implemented `\textcite` in a way that will show only the author name in the text and then add a footnote with a citation (full on first cite, shortened on subsequent cites). You can try and adapt that to your situation.

**Comment by etclub** [comment]
Well, I misunderstood the mechanism, as I thought `\textcite` would call (just like a function call) `\autocite`.
So it changes as `autocite` changes.

Thank you for your instruction, anyway.
