### ISSUE TITLE
Create a custom entry outside of the preamble

### ISSUE THREAD

**Issue by tobiasBora** [plk/biblatex#1336]
My goal is to dynamically generate automatically and insert `\href{https.//en.wikipedia.org}{Wikipedia}\cite{Wiki}` where the entry is defined as:
```
@online{Wiki,
    title        = {Wikipedia},
    author       = {Wikipedia},
    year         = 2024,
    url          = {https://en.wikipedia.org/},
}
```
when calling:
```
\addLink{https://en.wikipedia.org/}{Wikipedia}
```

So I tried to write a code like:
```
\documentclass[]{article}

\begin{filecontents}[noheader,overwrite]{main.bib}
@online{Wiki,
    title        = {Wikipedia},
    author       = {Wikipedia},
    year         = 2024,
    url          = {https://en.wikipedia.org/},
}
\end{filecontents}

\usepackage[
  style=alphabetic,% also 
  minalphanames=3,maxalphanames=4, % [Foo+99] -> [FBB+99].
  maxnames=99, % Do not put "et al". Sets maxbibnames, maxcitenames and maxsortnames.
  sortcites=true,
  %sorting=none,
  doi=false,
  url=false,
  giveninits=true, % Bob Foo --> B. Foo
  isbn=false,
  url=false,
  eprint=false,
  sortcites=false, % \cite{B,A,C}: [A,B,C] --> [B,A,C]
%backref=true, % [1] Title, blabla --> [1] Title, blabla (pages 1, 45, 56)
%% TODO: customize using https://tex.stackexchange.com/questions/36307/formatting-back-references-in-bibliography
]{biblatex}


\addbibresource{main.bib}%
\newcounter{myLinkCounter}
\setcounter{myLinkCounter}{1}
\NewDocumentCommand{\addLink}{O{}mm}{
  \edef\mylinkname{foo\themyLinkCounter}
  \DeclareSourcemap{
    \maps[datatype=bibtex]{
      \map{
        \step[entrynew=\mylinkname,entrynewtype=online,]
        \step[entrytarget=\mylinkname,fieldset=title,fieldvalue={#2}]
        \step[entrytarget=\mylinkname,fieldset=author,fieldvalue={#3}]
        \step[entrytarget=\mylinkname,fieldset=url,fieldvalue={#3}]
        \step[entrytarget=\mylinkname,fieldset=year,fieldvalue=2024]
      }
    }
  }
  %% I would like to be able to type:
  %\href{#2}{#3}\cite{\mylinkname}
  \stepcounter{myLinkCounter}
}
\usepackage{hyperref}

% Try to move this after preamble, it fails. Goal: this should also add \href and \cite automatically
\addLink{https://en.Foo.org/}{Fooentry}
\addLink{https://en.wikipedia.org/}{Wikipedia}
\begin{document}


% I need to cite at least one normal entry for this to work:
You can go to \cite{Wiki}
, \cite{foo1}\cite{foo2}.

\printbibliography

\end{document}
```
But unfortunately, I cannot move the `addLink` after the preamble. Any solution to create dynamically an entry after the the preamble?

**Comment by plk** [comment]
I think this is better suited to a TSE question.

**Comment by tobiasBora** [comment]
Why? This has no "good" answer so far. The only solution is to create programmatically a bib file, which seems quite dirty IMO.

**Comment by plk** [comment]
This is more of a very specific question about your particular requirements than a bug/enhancement report about the software and so is better suited to TSE. We can't really answer questions about your particular document issue here - it's meant for issues with the actual software.

**Comment by tobiasBora** [comment]
Sure, I do understand this, but my issue with the software is that it is not possible (at least without dirty hacks) to generate a new entry dynamically in the document. So unless I missed the relevant section in the documentation, I don’t see why it cannot qualify as a feature request for this software.

**Comment by moewew** [comment]
I guess it would have helped to establish context to link to https://tex.stackexchange.com/q/707370/35864.

It is a fair feature request to ask for a feature to generate an entry dynamically via something like sourcemapping from within the document (as opposed to just from the preamble), but then I guess this would essentially mean that `\DeclareSourcemap` would have to be allowed anywhere, which could get messy implementation-wise. From my point of view this is a "nice to have", but appears to be a fairly niche requirement (so if it is too difficult to implement then so be it).

**Comment by tobiasBora** [comment]
> I guess it would have helped to establish context to link to https://tex.stackexchange.com/q/707370/35864.

Yeah, good point.

> From my point of view this is a "nice to have", but appears to be a fairly niche requirement (so if it is too difficult to implement then so be it).

Sure, if it is too complicated to implement, I can understand, the above linked hacks can work otherwise for my use-cases.

**Comment by plk** [comment]
I did have a look at this and it's really too much of a change in the internals. The `.bcf` is preamble-only because it gets written during `\AtBeginDocument` and changing this to the end of the document has really complicated and nasty effects on citation tracking in the `.aux` file. Since it's a fairly niche requirement, we can't really change the internals for this, sorry.

**Comment by tobiasBora** [comment]
Ok, thanks a lot for your time and tries, I can live with the above hack then. ;-)
