### ISSUE TITLE
Wrong blx-dm.def banner

### ISSUE THREAD

**Issue by matteofg** [plk/biblatex#1338]
In `blx-dm.def` the code line `\ProvidesFile{blx-dm.def}[\abx@lbxid]` should be replaced with `\ProvidesFile{blx-dm.def}[\abx@cptid]`

IMHO

**Comment by plk** [comment]
This is a mistake, yes. I added a dedicated datamodel string  id as `cptid` is for the compat files. Thanks for noticing this.
