### ISSUE TITLE
Backref in color?

### ISSUE THREAD

**Issue by ego-thales** [plk/biblatex#1351]
Hello,

I'm looking to customize a bit my backrefs. I thought [this](https://tex.stackexchange.com/a/272166/225044) would do the trick,  but in my case, the backrefs are still black.

Is there a way to adapt the bibmacro?

Other question: where can I find definitions for `\printtext`, `\printlist`, etc...? It's really hard to navigate through the code as a total amateur.

Thanks in advance.
Cheers!

**Comment by moewew** [comment]
The linked answer works perfectly for me and colours the entire backref text. If it does not work for you, please show us a compilable example document that shows what you are doing and how it does not work for you.

At the moment, however, I feel this is definitely something for TeX.SX or another TeX forum and not for the bugtracker here.

----

You can find the documentation of `\printtext` and friends in the  `biblatex` documentation (e.g. https://github.com/plk/biblatex/blob/533b1ee6ab1d7b1b61d830125ebad6375204cf81/doc/latex/biblatex/biblatex.tex#L7864). The definitions are in `biblatex.sty`, but they are slightly obfuscated by the fact that many internal macros are defined using the `\blx@imc@...` prefix and only activated in relevant contexts (https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/biblatex.sty#L4479 and https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/biblatex.sty#L4848). In any case looking at the definition is probably overkill and not very helpful (or actively confusing) if you just want to use `\printtext` and friends.

**Comment by ego-thales** [comment]
> The linked answer works perfectly for me and colours the entire backref text. If it does not work for you, please show us a compilable example document that shows what you are doing and how it does not work for you.

Thanks for your answer! As it often happens, by making my MWE I figured out the culprit: it's an interaction with `hyperref`. Still, I can't get what I would like, I'll show below what I know how to do.

=====
I want to have citations in red, so I use this
```latex
\usepackage[colorlinks, citecolor=green]{hyperref}
\usepackage[backref, hyperref]{biblatex}
```
which gives
![image](https://github.com/plk/biblatex/assets/121242234/b82d6ec2-69a4-4cbc-a021-c4c5a687e005)
-----
I don't want the link to equation 1 to be red, so I use `linkcolor=lack` in `hyperref`
```latex
\usepackage[colorlinks, citecolor=green, linkcolor=black]{hyperref}
\usepackage[backref, hyperref]{biblatex}
```
which gives this
![image](https://github.com/plk/biblatex/assets/121242234/28b77720-01e5-4684-80bf-6d93b67bff66)
-----
So I try removing the `colorlinks` to avoid `hyperref` overriding the color from `biblatex`
```latex
\usepackage[citecolor=green, linkcolor=black]{hyperref}
\usepackage[backref, hyperref]{biblatex}
```
but then it doesn't even compile. Anyways, I suspect that I would lose the green color from citations if it worked
=====

So would you have any advice?

> At the moment, however, I feel this is definitely something for TeX.SX or another TeX forum and not for the bugtracker here.

I'm sorry you're probably right, I will soon close this "issue".

> You can find the documentation [...]

Thanks!

**Comment by ego-thales** [comment]
I found an ugly solution: I change locally the hyperref linkcolor using `{\hypersetup{linkcolor=red} [...]}` in my `pagerefformat` adapted from [here](https://tex.stackexchange.com/a/272166/225044).

If you have a cleaner approach, I'd be interested, but for the time being, I'll keep that.

Thanks again!

**Comment by moewew** [comment]
AFAICS (I would have to see a full example document to be absolutely sure) the problem here is that `hyperref`'s colouring feature overrides the text colour (because `hyperref`'s colours are more local here). If you don't want that setting `hyperref`'s link colour to the same as the text colour locally is definitely a sound solution and not at all ugly. What else would you do?

**Comment by ego-thales** [comment]
Ok, then I guess it's all good!

Thank you! :)
