### ISSUE TITLE
Package biblatex Warning: File 'brazilian-abnt-abnt.lbx' not found!

### ISSUE THREAD

**Issue by osmartormena** [plk/biblatex#1352]
I've just migrated from bibtex, and I must say that I'm not acquainted with biblatex inter workings. Anyways, I'm getting this warning:

```
Package biblatex Warning: File 'brazilian-abnt-abnt.lbx' not found!
(biblatex)                Ignoring mapping 'brazilian-abnt' -> 'brazilian-abnt-abnt'.
```

Despite the warning, everything is looking ok, to the best of my knowledge. I was able to found that 'brazilian-abnt.lbx' is properly located on my system. Although a quick search on biblatex and biblatex-abnt codebase didn't point to the root cause of the error: the appending of a second '-abnt' at the end of the filename.

Due to my scarce understanding of biblatex inner workings, I've also submitted this bug to the biblatex-abnt team.

**Comment by moewew** [comment]
See https://github.com/abntex/biblatex-abnt/issues/125.

AFAICS the problem is also discussed in https://github.com/abntex/biblatex-abnt/issues/35 and a fix (https://github.com/abntex/biblatex-abnt/pull/119) is already merged (but apparently not yet released to CTAN).

**Comment by osmartormena** [comment]
Thanks for the explanation. I'll mark the issue as closed, since it's related to the biblatex-abnt project.
