### ISSUE TITLE
Italian localization: ordinal number in long date format

### ISSUE THREAD

**Issue by matteofg** [plk/biblatex#1354]
In Italian language the first day of the month is an ordinal number. So that, the date (in long format) is written as follows:
- 1° gennaio, 2 gennaio, 3 gennaio, ...
- 1° febbraio, 2 febbraio, 3 febbraio, ...

See [here](https://books.google.com/ngrams/graph?content=1+gennaio%2C1°+gennaio&year_start=1940&year_end=2019&corpus=it-2019&smoothing=3&case_insensitive=true).

It is desirable to modify the `\mkbibdatelong` definition, similar to the definition into `french.lbx`.

**Comment by moewew** [comment]
Just to clarify: Does that mean that *only* the 1 gets the ordinal marker?

**Comment by matteofg** [comment]
> Does that mean that only the 1 gets the ordinal marker?

Yes, right

**Comment by moewew** [comment]
Thanks. According to the `babel-italian` documentation the marker is a superscript "o", is that what you had in mind? (When I first read the report it looked like a degree symbol to me.)

**Comment by matteofg** [comment]
> According to the `babel-italian` documentation the marker is a superscript "o", is that what you had in mind?

Yes, of cours!
sorry, my mistake... accomplice the Italian keyboard...

**Comment by moewew** [comment]
Thanks for clarifying that.

I just read that `babel-italian` also supports this format for `\today`, but that by default it is turned off (http://mirrors.ctan.org/macros/latex/contrib/babel-contrib/italian/italian.pdf, see the documentation of `\dateitalian` on  p. 5). So is this optional/a stylistic decision?

@fargiolas @matteocoder @eg9 You contributed to the Italian translations here. What's your take on this?

**Comment by fargiolas** [comment]
So far I couldn't find a strong reference about this. Serianni (VI.36) says both forms (1 and 1ᵒ) are allowed and it seems a matter of preference. No idea if some style guideline exists that may enforce one or the other form for specific documents.

**Comment by matteofg** [comment]
I too own the manual _Italian Grammar_ by Luca Serianni and confirm what @fargiolas wrote.

At this point, before closing the discussion, I would like to know how I can modify the `\mkbibdatelong` definition to achieve the purpose.

**Comment by moewew** [comment]
You can use the same approach as in `french.lbx`

```latex
\documentclass[italian]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear]{biblatex}

\makeatletter
\DefineBibliographyExtras{italian}{%
  \protected\def\mkbibdatelong#1#2#3{%
    \iffieldundef{#3}
      {}
      {\@bsphack % ignore day when auto-capitalizing month name
       \stripzeros{\thefield{#3}}%
       \ifnumequal{\thefield{#3}}{1}
         {\textsuperscript{o}}
         {}%
       \@esphack % ignore day when auto-capitalizing month name
       \iffieldundef{#2}{}{\nobreakspace}}%
    \iffieldundef{#2}
      {}
      {\mkbibmonth{\thefield{#2}}%
       \iffieldundef{#1}{}{\space}}%
    \iffieldbibstring{#1}
      {\bibstring{\thefield{#1}}}
      {\dateeraprintpre{#1}\stripzeros{\thefield{#1}}}}%
}
\makeatother

\begin{filecontents}[overwrite]{\jobname.bib}
@book{elk,
  author    = {Anne Elk},
  title     = {A Theory on Brontosauruses},
  date      = {1972-01-01},
  publisher = {Monthy \& Co.},
  location  = {London},
}
\end{filecontents}
\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite{sigfridsson,elk}

\printbibliography
\end{document}
```

**Comment by matteofg** [comment]
Thank you very much!
