### ISSUE TITLE
Automatic capitalized for datatype=key fields

### ISSUE THREAD

**Issue by matteofg** [plk/biblatex#1373]
Some fields, like `authortype`, `pubstate` and `type`, allows to use both localization bibstrings and "literal" content.

Localization bibstrings provide a checking mechanism (see macro `\blx@bibstring`), so they are printed in uppercase if necessary. But this does not happen if these types of fields contain arbitrary text.

Below a mwe:
```
\begin{filecontents}[overwrite]{\jobname.bib}
@book{test,
  author = {Smith, John},
  authortype = {xxx},
  title = {Title of the Book},
  location = {Location},
  publisher = {Publisher},
  year = {2023},
  pubstate = {yyy},
}
\end{filecontents}

\documentclass{article}
\usepackage[style=verbose]{biblatex}
\addbibresource{\jobname.bib}

\DeclareDelimFormat*{authortypedelim}{\newunitpunct}

\renewbibmacro*{addendum+pubstate}{%
  \printfield{addendum}%
  \newunit\newblock
  \printfield{pubstate}}

\begin{document}
\cite{test}
\printbibliography
\end{document}
```
I ask whether it is not appropriate to provide a checking mechanism even in the case of fields containing arbitrary text.

**Comment by moewew** [comment]
Combine `\ifcapital` and `\MakeCapital` as appropriate.

```latex
\documentclass{article}
\usepackage[style=verbose]{biblatex}

\DeclareFieldFormat{pubstate}{%
  \ifbibstring{#1}
    {\bibstring{#1}}
    {\ifcapital
       {\MakeCapital{#1}}
       {#1}}}

\DeclareDelimFormat*{authortypedelim}{\newunitpunct}

\renewbibmacro*{addendum+pubstate}{%
  \printfield{addendum}%
  \newunit\newblock
  \printfield{pubstate}}

\begin{filecontents}{\jobname.bib}
@book{test,
  author     = {Smith, John},
  authortype = {xxx},
  title      = {Title of the Book},
  location   = {Location},
  publisher  = {Publisher},
  year       = {2023},
  pubstate   = {yyy},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\cite{test}
\printbibliography
\end{document}
```

**Comment by matteofg** [comment]
Thanks, I already knew how to define a formatting directive like this.

The use of `\DeclareFieldFormat` may be suitable for fields like `type` and `pubstate`, but less so for fields used in more complex macros like `authortype` and `editortype` (and friends). Not to mention fields like `pagination` and `bookpagination`.

I would like to understand whether it is appropriate for biblatex to provide an automatic mechanism (via internal macros) as it currently does with bibstrings, without leaving the work to document authors.

**Comment by moewew** [comment]
It works the same for `authortype`, whose default field format is just `#1`.

```latex
\documentclass{article}
\usepackage[style=verbose]{biblatex}

\DeclareFieldFormat{pubstate}{%
  \ifbibstring{#1}
    {\bibstring{#1}}
    {\ifcapital
       {\MakeCapital{#1}}
       {#1}}}

\DeclareFieldFormat{authortype}{%
  \ifcapital
    {\MakeCapital{#1}}
    {#1}}

\DeclareDelimFormat*{authortypedelim}{\newunitpunct}

\renewbibmacro*{addendum+pubstate}{%
  \printfield{addendum}%
  \newunit\newblock
  \printfield{pubstate}}

\begin{filecontents}{\jobname.bib}
@book{test,
  author     = {Smith, John},
  authortype = {xxx},
  title      = {Title of the Book},
  location   = {Location},
  publisher  = {Publisher},
  year       = {2023},
  pubstate   = {yyy},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\cite{test}
\printbibliography
\end{document}
```

I don't think it is a good idea to try and inject capitalisation change via internal routes that are not visible in `\DeclareFieldFormat`. For one capitalisation changes of arbitrary text can be challenging (the `expl3` code is a great step forward here, but string manipulation is painful in LaTeX), so not having to change the capitalisation of arbitrary input unless the document author explicitly requests it is safer and more efficient. Plus all the ingredients are there for authors to use if they want to. Finally, many field contents do not require explicit capitalisation changes. And for cases like `pubstate`, `authortype` etc. the more convenient way is a bibstring anyway.

**Comment by matteofg** [comment]
Okay, thanks for the comments. For me the issue can be closed!
