### ISSUE TITLE
Differences among languages

### ISSUE THREAD

**Issue by pauloney** [plk/biblatex#1385]
I am finishing a long multilanguage bibliography and observed a few discrepancies among the way each language is treated -- which is normal, but one baffled me:

Almost all of them do the "insert" of the translator in Caps between two full stops. The exception been Romanian that does it lower-case in between commas. 

Being the only one, and asked around ... three romanian scientists here at Berkeley had never heard that Romanian was any different from other nearby languages, or that there was a specific preferred way. 

Is this coming from the LBX file? Is it intentional?

````
\begin{filecontents*}{\jobname.bib}
@book {knuth-pl,
    author = {Knuth, Donald E.},
     title = {Sztuka Programowania, T. 1: Algorytmy Podstawowe},
translator = {G. Jakacki},
   address = {Warszawa},
 publisher = {Wydawnictwa Naukowo-Techniczne},
      year = {2002},
     pages = {xxiv+679},
    langid = {pl},
}

@book {knuth-ro,
    author = {Knuth, Donald E.},
     title = {Arta programării calculatoarelor, V. 1: Algoritmi fundamentali},
translator = {Mihaela Târpa},
   address = {București},
 publisher = {Editura Teora},
      year = {2002},
     pages = {616},
    langid = {ro},
}
\end{filecontents*}

\documentclass{book}

\usepackage{polyglossia}
\usepackage{csquotes}
\setmainlanguage{english}
\setotherlanguage{polish}
\setotherlanguage{romanian}

\usepackage[autolang=other]{biblatex}

\addbibresource{\jobname.bib}

\begin{document}
\nocite{*}
\printbibliography

\end{document}
````

**Comment by moewew** [comment]
According to https://github.com/plk/biblatex/pull/1085 a comma (rather than a full stop) is the more grammatical choice. If you know people with a sufficient command of Romanian who think otherwise, please ask them to get in touch.

**Comment by pauloney** [comment]
Upon further digging into this we found out that the use is mixed, with a definite preference for using commas as the preferred separator -- and also -- a high chance that the occurrences of separation by dots coming from mimicing the English or using bibliographical styles prepared for English.

So we close this one.
