### ISSUE TITLE
The `editor` field is not typeset correctly and leads to compilation errors

### ISSUE THREAD

**Issue by LVrecar** [plk/biblatex#1391]
Hi,
I'm posting this as an issue here as I haven't seen it discussed on stackexchange or elsewhere.

I'm using TeXLive 2024, with biblatex 3.20 and biber 2.20 and I'm encountering an issue with the `editor` field

Using the following sample bib entry:
```
@inproceedings{citekey,
  title = {This is a title},
  booktitle = {book title},
  author = {Thor, A. U. and Smith, John},
  editor = {Test, Thisisa and This, Sois},
  date = {2024},
  volume = {12345},
  pages = {35--45},
  publisher = {Publisher Co Inc},
  doi = {10.1001/977-2-067-66987-2_13},
  langid = {english}
}
```
and citing it as normal (or using `\nocite{*}`), and then using `\printbibliography`.

I'm compiling using `lualatex` -> `biber˙` -> `lualatex` -> `lualatex` (issue also reproducible using `pdflatex`).

The following error appears on `lualatex`/`pdflatex` runs 2 and 3: (`\printbibliography` is on line 160 in my file):

```
! Missing number, treated as zero.
<to be read again> 
{
l.161 
    
? 
! You can't use a prefix with `the character ='.
<to be read again> 
=
l.161 
    
? 
! You can't use `\numexpr' in horizontal mode.
\int_gset:Nn #1#2->\tex_global:D #1=\__int_eval:w 
                                                  #2\__int_eval_end: 
l.161 
    
? 
```

You can keep hitting Enter and a PDF is produced, however the editors field is typeset incorrectly (see image below). 
![Screenshot_2](https://github.com/user-attachments/assets/931f7550-0680-4226-ab15-ae0edba3ee35)

The `0 =` shouldn't be there and I suspect that's what's causing the error during compilation. Removing the `editor` field from the bib entry also removes the error.

Is this a known issue and if yes, how can I resolve it?

Thanks!

**Comment by moewew** [comment]
Can you tell us which style you use? 

The entry works fine for me in the sense that the following document compiles without error (and without "0=") for me with all standard styles that I tried
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear]{biblatex}

\begin{filecontents}{\jobname.bib}
@inproceedings{citekey,
  title = {This is a title},
  booktitle = {book title},
  author = {Thor, A. U. and Smith, John},
  editor = {Test, Thisisa and This, Sois},
  date = {2024},
  volume = {12345},
  pages = {35--45},
  publisher = {Publisher Co Inc},
  doi = {10.1001/977-2-067-66987-2_13},
  langid = {english}
}
\end{filecontents}
\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite{sigfridsson,citekey}

\printbibliography
\end{document}
``` 
Can you share a fully compilable example document similar to this one?

**Comment by LVrecar** [comment]
I didn't specify the style, so it was `numeric`.

While preparing the MWE I also realised that the issue was in combination with an environment provided by another package I'm using. Using `\printbibliography` inside that environment is what broke things and simply moving it outside fixes the problem and everything compiles as normal.

Thanks for your help!
