### ISSUE TITLE
Option at the `biblatex` (and not `biber`)'s level to display only the DOIs for entries stipulating both the `doi` and the `url` fields

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#1401]
Bibliography collectors such as `Zotero` or `JabRef` often collect URLs in addition to DOIs when the latter are available. But for a printed bibliography, having both displayed is cumbersome.  So it would be handy if `biblatex` provided a (`\printbibliography`?) option which allowed us to display only DOIs (resp. URLs, depending on the author's preference) for entries stipulating both `doi` and `url` fields.

Unless I'm mistaken, this can be done at the `biber` level, but it's less practical than a `biblatex` option.

**Comment by dbitouze** [comment]
Sigh... I reopen this issue because, of course, `url=false` removes the URLs regardless the entries stipulate a `doi` field or not. here, I'd like an option that prints:

- the DOIs (resp. the URLs) only for entries stipulating both the `doi` and the `url` fields,
- the URLs for entries stipulating the `url` but not the `doi`,
- the DOIs for entries stipulating the `doi` but not the `url`.

**Comment by moewew** [comment]
Personally, I think the Biber solution is the cleanest and quickest and will always work regardless of the style you use
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear]{biblatex}

\DeclareSourcemap{
  \maps[datatype=bibtex]{
    \map{
      \step[fieldsource=doi,final]
      \step[fieldset=url,null]
    }  
  }
}

\begin{filecontents}{\jobname.bib}
@article{sigfridsson:both,
  author       = {Sigfridsson, Emma and Ryde, Ulf},
  title        = {Comparison of methods for deriving atomic charges from the
                  electrostatic potential and moments},
  subtitle     = {Both},
  journaltitle = {Journal of Computational Chemistry},
  date         = 1998,
  volume       = 19,
  number       = 4,
  pages        = {377-395},
  doi          = {10.1002/(SICI)1096-987X(199803)19:4<377::AID-JCC1>3.0.CO;2-P},
  url          = {https://example.edu/~sigfridsson/comparison.pdf}
}
@article{sigfridsson:doi,
  author       = {Sigfridsson, Emma and Ryde, Ulf},
  title        = {Comparison of methods for deriving atomic charges from the
                  electrostatic potential and moments},
  subtitle     = {DOI only},
  journaltitle = {Journal of Computational Chemistry},
  date         = 1998,
  volume       = 19,
  number       = 4,
  pages        = {377-395},
  doi          = {10.1002/(SICI)1096-987X(199803)19:4<377::AID-JCC1>3.0.CO;2-P},
}
@article{sigfridsson:url,
  author       = {Sigfridsson, Emma and Ryde, Ulf},
  title        = {Comparison of methods for deriving atomic charges from the
                  electrostatic potential and moments},
  subtitle     = {URL only},
  journaltitle = {Journal of Computational Chemistry},
  date         = 1998,
  volume       = 19,
  number       = 4,
  pages        = {377-395},
  url          = {https://example.edu/~sigfridsson/comparison.pdf}
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
Lorem \autocite{sigfridsson:both,sigfridsson:doi,sigfridsson:url}

\printbibliography
\end{document}
```

You can get a similar result that should work for most styles with `\AtEveryBibitem`
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear]{biblatex}

\AtEveryBibitem{%
  \iffieldundef{doi}
    {}
    {\clearfield{url}\clearfield{urlyear}}}

\begin{filecontents}{\jobname.bib}
@article{sigfridsson:both,
  author       = {Sigfridsson, Emma and Ryde, Ulf},
  title        = {Comparison of methods for deriving atomic charges from the
                  electrostatic potential and moments},
  subtitle     = {Both},
  journaltitle = {Journal of Computational Chemistry},
  date         = 1998,
  volume       = 19,
  number       = 4,
  pages        = {377-395},
  doi          = {10.1002/(SICI)1096-987X(199803)19:4<377::AID-JCC1>3.0.CO;2-P},
  url          = {https://example.edu/~sigfridsson/comparison.pdf}
}
@article{sigfridsson:doi,
  author       = {Sigfridsson, Emma and Ryde, Ulf},
  title        = {Comparison of methods for deriving atomic charges from the
                  electrostatic potential and moments},
  subtitle     = {DOI only},
  journaltitle = {Journal of Computational Chemistry},
  date         = 1998,
  volume       = 19,
  number       = 4,
  pages        = {377-395},
  doi          = {10.1002/(SICI)1096-987X(199803)19:4<377::AID-JCC1>3.0.CO;2-P},
}
@article{sigfridsson:url,
  author       = {Sigfridsson, Emma and Ryde, Ulf},
  title        = {Comparison of methods for deriving atomic charges from the
                  electrostatic potential and moments},
  subtitle     = {URL only},
  journaltitle = {Journal of Computational Chemistry},
  date         = 1998,
  volume       = 19,
  number       = 4,
  pages        = {377-395},
  url          = {https://example.edu/~sigfridsson/comparison.pdf}
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
Lorem \autocite{sigfridsson:both,sigfridsson:doi,sigfridsson:url}

\printbibliography
\end{document}
```

But you can also redefine the relevant bibmacros in the standard styles
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=authoryear, doi=true]{biblatex}

\renewbibmacro*{doi+eprint+url}{%
  \iftoggle{bbx:doi}
    {\printfield{doi}}
    {}%
  \newunit\newblock
  \iftoggle{bbx:eprint}
    {\usebibmacro{eprint}}
    {}%
  \newunit\newblock
  \ifboolexpr{togl {bbx:url}
    and (not togl {bbx:doi} or test {\iffieldundef{doi}} )}
    {\usebibmacro{url+urldate}}
    {}}

\begin{filecontents}{\jobname.bib}
@article{sigfridsson:both,
  author       = {Sigfridsson, Emma and Ryde, Ulf},
  title        = {Comparison of methods for deriving atomic charges from the
                  electrostatic potential and moments},
  subtitle     = {Both},
  journaltitle = {Journal of Computational Chemistry},
  date         = 1998,
  volume       = 19,
  number       = 4,
  pages        = {377-395},
  doi          = {10.1002/(SICI)1096-987X(199803)19:4<377::AID-JCC1>3.0.CO;2-P},
  url          = {https://example.edu/~sigfridsson/comparison.pdf}
}
@article{sigfridsson:doi,
  author       = {Sigfridsson, Emma and Ryde, Ulf},
  title        = {Comparison of methods for deriving atomic charges from the
                  electrostatic potential and moments},
  subtitle     = {DOI only},
  journaltitle = {Journal of Computational Chemistry},
  date         = 1998,
  volume       = 19,
  number       = 4,
  pages        = {377-395},
  doi          = {10.1002/(SICI)1096-987X(199803)19:4<377::AID-JCC1>3.0.CO;2-P},
}
@article{sigfridsson:url,
  author       = {Sigfridsson, Emma and Ryde, Ulf},
  title        = {Comparison of methods for deriving atomic charges from the
                  electrostatic potential and moments},
  subtitle     = {URL only},
  journaltitle = {Journal of Computational Chemistry},
  date         = 1998,
  volume       = 19,
  number       = 4,
  pages        = {377-395},
  url          = {https://example.edu/~sigfridsson/comparison.pdf}
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
Lorem \autocite{sigfridsson:both,sigfridsson:doi,sigfridsson:url}

\printbibliography
\end{document}
```

I will readily admit that none of these solutions are as slick as a simple option, but some of them come pretty close. I believe that not everything has to be an option as that could lead to a lot of options having to be implemented, documented and maintained. And new options don't automatically percolate through to contributed styles leaving users potentially confused or frustrated.

**Comment by dbitouze** [comment]
Thank you very much for all these detailed solutions! I understand your concerns, which I share, but in recent months more and more fellow LaTeX and `biblatex` users, who use tools such as Zotero or JabRef, have complained about this type of redundancy.

**Comment by moewew** [comment]
Hm, maybe then the message should be that users should be more aware of what good quality `.bib` data should look like. But especially if people use tools like JabRef or Zotero it should be easy to get the desired output: Just tell the tools to get rid of the URL if the entry has a DOI on export.

**Comment by dbitouze** [comment]
Yes, that's feasible at least with Zotero + BBT but the users often aren't aware of this feature.

Anyway, thanks!

**Comment by pauloney** [comment]
It is a real pity that people are still using URL and DOIs in print. What
sane person would make any use of it in a printed material. They are
supposed to be the underpinnings of the web and to be used to build links
and NOT to be displayed.

Displaying an URL or DOI in print is equivalent to walking around showing
your underwear!

**Comment by dbitouze** [comment]
@pauloney I don't see your point: having (either) the DOI or URL makes it easy for the reader (of the electronic version) of the document to be able to consult the reference of interest.

**Comment by pauloney** [comment]
The correct way to do it, is to build a link pointing to the DOI resolution
into the title. In this way the reader can just click on it to access the
resource and the gibberish never gets exhibited when printed.

**Comment by dbitouze** [comment]
> The correct way to do it, is to build a link pointing to the DOI resolution into the title.
> In this way the reader can just click on it to access the resource and the gibberish never gets exhibited when printed.

You should open an issue to suggest this to the `biblatex`'s team :wink:

**Comment by pauloney** [comment]
This already exists in biblatex for over a decade.

**Comment by pauloney** [comment]
I guess you mean the "default behaviour", and I agree with you, if no
particular "style" is chosen, then that should be the standard behaviour.

There are many fields used in `biblatex` that have non-standard use,
examples are:

key
copyright
contents
keywords
language
etc

and they are not normally displayed -- they are instead used to format the
value of other fields. For sure DOI and URL falls on that set.

The main developers of biblatex are worried about changing assumed
"default" behaviours of the past, but for sure, this is one that should be
changed.

**Comment by pauloney** [comment]
I have just opened an issue for that. I do feel like you that it should be
changed to be the default.

**Comment by dbitouze** [comment]
> I have just opened an issue for that. I do feel like you that it should be changed to be the default.

Thanks!
