### ISSUE TITLE
No line break in long titles

### ISSUE THREAD

**Issue by wjansen** [plk/biblatex#193]
Hi all, 

the title of a bibliography entry is not broken if it is very long. The reason is its underlining, probably by macro \underline. Proposed solution: use macro \uline of package ulem instead. (Loading ulem by myself does not help). 
Below is a real BibTeX entry showing the effect.

Regards
## WJ

@techreport{Longtitle,
  author={Elaine Barker and John Kelsey},
  title={Recommendation for random number generation using
    deterministic random bit generators (revisited)},
  institution={National Institute of Standards and Technology},
  year={2007}
}

**Comment by liar666** [comment]
Indded, \emph is redefinied by ulem. Using:
```
\usepackage[normalem]{ulem}
```
resolved the issue in my case
