### ISSUE TITLE
`\DeclareAutoCiteCommand` cannot doesn't work completely within the document body

### ISSUE THREAD

**Issue by danielshub** [plk/biblatex#202]
Within the document body, the `\DeclareAutoCiteCommand` macro updates `\autocite` but not `\autocites`. For example, with the following MWE I get the same output with `\footcite` and `\autocite` (as I expect), but the output of `\footcites` and `\autocites` is different.

```
\documentclass{article}
\usepackage[autocite=footnote]{biblatex}
\DeclareCiteCommand{\footcite}[\mkbibfootnote]{A}{B}{\multicitedelim}{}
\DeclareMultiCiteCommand{\footcites}[\mkbibfootnote]{\footcite}{\multicitedelim}
\DeclareAutoCiteCommand{footnote}{\footcite}{\footcites}
\bibliography{biblatex-examples.bib}
\begin{document}
\footcite{aksin}
\autocite{aksin}
\footcites{aksin}{aksin}
\autocites{aksin}{aksin}
\end{document}
```

I think `\DeclareAutoCiteCommand` should either be disabled in the document body or affect both `\autocite` and `\autocites`.

**Comment by moewew** [comment]
This was resolved in https://github.com/plk/biblatex/pull/761.
