### ISSUE TITLE
Unicode char \u8:́ not set up for use with LaTeX.

### ISSUE THREAD

**Issue by perstar** [plk/biblatex#203]
This document gives the error message "Unicode char \u8:́ not set up for use with LaTeX.".

```
\documentclass{article}
\usepackage[utf8]{inputenc}

\usepackage{filecontents}

\begin{filecontents}{\jobname.bib}
@misc{ref,
  author = {Mart{\'\i}},
}
\end{filecontents}

\usepackage{biblatex}
\addbibresource{\jobname.bib}

\begin{document}
\nocite{ref}
\printbibliography
\end{document}
```

Without the inputenc line this works. I don't understand where the strange character comes from. In the bbl file "{\'\i}" has been translated into "í", as compared to what happens without the inputenc line, but a bare "í" in the text is no problem.

**Comment by geniuszek** [comment]
seems like \'i works fine:

author = {Mart\'i}
