### ISSUE TITLE
\DeclareSourcemap seems to be usable only once

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#227]
biblatex's `\DeclareSourcemap` command seems to be usable only once in the preamble. While I was somewhat certain this was the case, I could not find anything in the documentation about that.

It might be useful to add a hint about that to the documentation or enable use of multiple `\DeclareSourcemap`s in the preamble (as a user I would prefer the latter option, of course :-)).

**Comment by moewew** [comment]
I just happened to come across this again. `\DeclareStyleSourcemap` is usable multiple times, so it seems at least theoretically possible that `\DeclareSourcemap` could also be used multiple times.

The changes required in `biblatex` seem minute. As far as I can see the only difference between the two is `\xappto` vs `\csxdef`.

https://github.com/plk/biblatex/blob/25dbb76d60ce0cb9c67597ae7b263a4d86bdaa27/tex/latex/biblatex/biblatex.sty#L11337-L11356

Of course I could not possibly comment on the difficulties in Biber. But again the differences between the two are minute

https://github.com/plk/biber/blob/61995e0771b36e9b86c56bfba135e2f9cade230c/lib/Biber/Input/file/biblatexml.pm#L94-L108

**Comment by plk** [comment]
The biblatex side is, as you say, trivial. The problem is the biber side. It would be possible by merging or looping but it's a bit of a pain and there is just no reason to have more than one of these since it's possible to list many independent maps in the same `\DeclareSourcemap`. The reason we needed more than one style map is due to nested styles and was an explicit request at some point as I recall ...

**Comment by moewew** [comment]
Mhhh, OK. I had hoped the only change necessary on the Biber side would be something similar to https://github.com/plk/biber/commit/8cb3545003cc64fae0936efca079404ab33401b2 and https://github.com/plk/biber/commit/2f3cfb83dce5df03a2793fd88701471f3300c829. While it is certainly possible to always have only one `\DeclareSourcemap` it is quite a bit more convenient to be able to have several. Of course I have no idea how hard this really is to implement and whether this could have performance impacts.

**Comment by plk** [comment]
Hmm, you may be right, it's coming back to me now. Try the 3.11/2.11 just uploaded.

**Comment by moewew** [comment]
Works brilliantly, thank you very much.
