### ISSUE TITLE
Supporting lists of uri

### ISSUE THREAD

**Issue by georgthegreat** [plk/biblatex#229]
Hi!

I'm trying to customise datamodel to support multiple urls.
I use the following mwe to test the feature:

``` \documentclass[10pt,a4paper]{article}

\RequirePackage{filecontents}

\begin{filecontents}{biblatex-dm.cfg}
\DeclareDatamodelFields[type=list,datatype=uri]{url}
\end{filecontents}

\RequirePackage[utf8]{inputenc}
\RequirePackage[T1,T2A]{fontenc}

\RequirePackage[czech,danish,english,french,german,italian,polish,portuguese,spanish,russian]{babel}
\RequirePackage[bibencoding=utf-8,backend=biber]{biblatex}

% adding support for URL list
\DeclareListFormat{url}{%
\ifnumequal{\value{listcount}}{\value{liststart}}%
{\mkbibacro{url}\addcolon\addspace}%
{\addcomma\addspace}%
TROLOLO #1}

% defining URL list printing format
\renewbibmacro*{url}{\printlist{url}}

\begin{filecontents}{\jobname.bib}
@book(
    book,
    author = {Joe First | Bob Third},
    title = {Book title},
    langid = {english},
    year = 2013,
    url = {http://www.example.com | http://www.google.com}
)
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

(should be biber-compiled with

```
@biber --listsep=\| --namesep=\| '--xsvsep=\s*\|\s*' -mssplit=# --validate_datamodel ${@:.pdf=}
```

From my point of view, specifying datatype=literal for url leads to ignorance of this field during pdf-compilation. Specifying datatype=uri makes biber to exit without any sensible error message.

Is it possible to use lists of uri's?

**Comment by drt24** [comment]
For the next person who finds this issue: My solution was:
in urls.dbx:

    \DeclareDatamodelFields[type=list, datatype=uri]{urls}
    \DeclareDatamodelEntryfields{urls}

In the preamble of the main .tex file: add datamodel=urls to the options to the biblatex package

    \RequirePackage[....,datamodel=urls]{biblatex}

And cause the urls list to be displayed:

    \DeclareListFormat{urls}{%
      \url{#1}%
      \ifthenelse{\value{listcount}<\value{liststop}}
        {\addcomma\space}
        {}}

    \renewbibmacro*{url}{\iffieldundef{url}{\printlist{urls}}{\printfield{url}}}
