### ISSUE TITLE
Croatian - proposed change

### ISSUE THREAD

**Issue by pauloney** [plk/biblatex#252]
The file croatian.lbx contains the line:

    in               = {{}{}},

which literally sets the empty string as the translation for the English proposition "in", as used in location. 

I suspect that this is an error because the translation of "in" (for both time and location) is "u" in Croatian, and I am proposing to change it to:

    in               = {{u}{u}},

The author of the file (Ivo Pletikosić) has not answered a request by e-mail, so I am here requesting that if you are a Croatian speaker or know the subject to weight in so we can decide for the best string. I am leaving the Issue open for a few days and make the change if no-one opposes it.

Paulo Ney

Disclaimer: I am NOT a Croatian speaker.

**Comment by ivankokan** [comment]
Why don't we align with definitions provided in babelbib package (https://www.ctan.org/pkg/babelbib)?

% \subsubsection{Croatian}
% \changes{1.30}{2010/01/06}{Added Croatian language}%
%    \begin{macrocode}
%<*croatian>
%    \end{macrocode}
%
% The language definition for Croatian was provided by
% Vedran Mileti\'c (vmiletic@inf.uniri.hr),
% Ivan Kokan (ivan.kokan@gmail.com), and
% Ivica Naki\'c (nakic@math.hr).
%
% \begin{macro}{\bibscroatian}
%    \begin{macrocode}
\newcommand\bibscroatian[1][croatian]{%
  \def\biblanguagename{#1}%
  \def\btxetalshort##1{\protect\foreignlanguage{#1}{i~ost##1{}}}%
  \def\btxetallong##1{\protect\foreignlanguage{#1}{i~ostali}}%
  \def\btxandshort##1{\protect\foreignlanguage{#1}{i}}%
  \def\btxandlong##1{\protect\foreignlanguage{#1}{i}}%
  \def\btxandcomma##1{}%
  \def\btxinlong##1{\protect\foreignlanguage{#1}{u}}%
  \def\btxinshort##1{\protect\foreignlanguage{#1}{u}}%
  \def\btxofseriesshort##1{\protect\foreignlanguage{#1}{iz}}%
  \def\btxinseriesshort##1{\protect\foreignlanguage{#1}{u}}%
  \def\btxofserieslong##1{\protect\foreignlanguage{#1}{iz}}%
  \def\btxinserieslong##1{\protect\foreignlanguage{#1}{u}}%
  \def\btxeditorshort##1{\protect\foreignlanguage{#1}{ur##1{}}}%
  \def\btxeditorlong##1{\protect\foreignlanguage{#1}{urednik}}%
  \def\btxeditorsshort##1{\protect\foreignlanguage{#1}{ur##1{}}}%
  \def\btxeditorslong##1{\protect\foreignlanguage{#1}{urednici}}%
  \def\btxvolumeshort##1{\protect\foreignlanguage{#1}{sv##1{}}}%
  \def\btxvolumelong##1{\protect\foreignlanguage{#1}{svezak}}%
  \def\btxnumbershort##1{\protect\foreignlanguage{#1}{br##1{}}}%
  \def\btxnumberlong##1{\protect\foreignlanguage{#1}{broj}}%
  \def\btxeditionshort##1{\protect\foreignlanguage{#1}{izd##1{}}}%
  \def\btxeditionlong##1{\protect\foreignlanguage{#1}{izdanje}}%
  \def\btxeditionnumshort##1##2{\btxnumeralshort{##1}~\btxeditionshort{##2}}%
  \def\btxeditionnumlong##1##2{\btxnumerallong{##1}~\btxeditionlong{##2}}%
  \def\btxchaptershort##1{\protect\foreignlanguage{#1}{pogl##1{}}}%
  \def\btxchapterlong##1{\protect\foreignlanguage{#1}{poglavlje}}%
  \def\btxpageshort##1{\protect\foreignlanguage{#1}{str##1{}}}%
  \def\btxpagelong##1{\protect\foreignlanguage{#1}{stranica}}%
  \def\btxpagesshort##1{\protect\foreignlanguage{#1}{str##1{}}}%
  \def\btxpageslong##1{\protect\foreignlanguage{#1}{stranice}}%
  \def\btxmastthesis##1{\protect\foreignlanguage{#1}{Magistarski rad}}%
  \def\btxphdthesis##1{\protect\foreignlanguage{#1}{Disertacija}}%
  \def\btxtechrepshort##1{\protect\foreignlanguage{#1}{Tehn.\ izvj##1{}}}%
  \def\btxtechreplong##1{\protect\foreignlanguage{#1}{%
      Tehni\v{c}ki izvje\v{s}taj}}%
  \def\btxmonjanlong##1{\protect\foreignlanguage{#1}{sije\v{c}anj}}%
  \def\btxmonfeblong##1{\protect\foreignlanguage{#1}{velja\v{c}a}}%
  \def\btxmonmarlong##1{\protect\foreignlanguage{#1}{o\v{z}ujak}}%
  \def\btxmonaprlong##1{\protect\foreignlanguage{#1}{travanj}}%
  \def\btxmonmaylong##1{\protect\foreignlanguage{#1}{svibanj}}%
  \def\btxmonjunlong##1{\protect\foreignlanguage{#1}{lipanj}}%
  \def\btxmonjullong##1{\protect\foreignlanguage{#1}{srpanj}}%
  \def\btxmonauglong##1{\protect\foreignlanguage{#1}{kolovoz}}%
  \def\btxmonseplong##1{\protect\foreignlanguage{#1}{rujan}}%
  \def\btxmonoctlong##1{\protect\foreignlanguage{#1}{listopad}}%
  \def\btxmonnovlong##1{\protect\foreignlanguage{#1}{studeni}}%
  \def\btxmondeclong##1{\protect\foreignlanguage{#1}{prosinac}}%
  \def\btxmonjanshort##1{\protect\foreignlanguage{#1}{sij##1{}}}%
  \def\btxmonfebshort##1{\protect\foreignlanguage{#1}{velj##1{}}}%
  \def\btxmonmarshort##1{\protect\foreignlanguage{#1}{o\v{z}u##1{}}}%
  \def\btxmonaprshort##1{\protect\foreignlanguage{#1}{tra##1{}}}%
  \def\btxmonmayshort##1{\protect\foreignlanguage{#1}{svi##1{}}}%
  \def\btxmonjunshort##1{\protect\foreignlanguage{#1}{lip##1{}}}%
  \def\btxmonjulshort##1{\protect\foreignlanguage{#1}{srp##1{}}}%
  \def\btxmonaugshort##1{\protect\foreignlanguage{#1}{kol##1{}}}%
  \def\btxmonsepshort##1{\protect\foreignlanguage{#1}{ruj##1{}}}%
  \def\btxmonoctshort##1{\protect\foreignlanguage{#1}{lis##1{}}}%
  \def\btxmonnovshort##1{\protect\foreignlanguage{#1}{stu##1{}}}%
  \def\btxmondecshort##1{\protect\foreignlanguage{#1}{pro##1{}}}%
  \def\Btxinlong##1{\protect\foreignlanguage{#1}{U}}%
  \def\Btxinshort##1{\protect\foreignlanguage{#1}{U}}%
  \def\Btxeditorshort##1{\protect\foreignlanguage{#1}{Ur##1{}}}%
  \def\Btxeditorlong##1{\protect\foreignlanguage{#1}{Urednik}}%
  \def\Btxeditorsshort##1{\protect\foreignlanguage{#1}{Ur##1{}}}%
  \def\Btxeditorslong##1{\protect\foreignlanguage{#1}{Urednici}}%
  \def\Btxvolumeshort##1{\protect\foreignlanguage{#1}{Sv##1{}}}%
  \def\Btxvolumelong##1{\protect\foreignlanguage{#1}{Svezak}}%
  \def\Btxnumbershort##1{\protect\foreignlanguage{#1}{Br##1{}}}%
  \def\Btxnumberlong##1{\protect\foreignlanguage{#1}{Broj}}%
  \def\Btxeditionshort##1{\protect\foreignlanguage{#1}{Izd##1{}}}%
  \def\Btxeditionlong##1{\protect\foreignlanguage{#1}{Izdanje}}%
  \def\Btxeditionnumshort##1##2{\btxnumeralshort{##1}~\Btxeditionshort{##2}}%
  \def\Btxeditionnumlong##1##2{\btxnumerallong{##1}~\Btxeditionlong{##2}}%
  \def\Btxchaptershort##1{\protect\foreignlanguage{#1}{Pogl##1{}}}%
  \def\Btxchapterlong##1{\protect\foreignlanguage{#1}{Poglavlje}}%
  \def\Btxpageshort##1{\protect\foreignlanguage{#1}{Str##1{}}}%
  \def\Btxpagelong##1{\protect\foreignlanguage{#1}{Stranica}}%
  \def\Btxpagesshort##1{\protect\foreignlanguage{#1}{Str##1{}}}%
  \def\Btxpageslong##1{\protect\foreignlanguage{#1}{Stranice}}%
  \def\Btxtechrepshort##1{\protect\foreignlanguage{#1}{Tehn.\ izvj##1{}}}%
  \def\Btxtechreplong##1{\protect\foreignlanguage{#1}{%
      Tehni\v{c}ki izvje\v{s}taj}}%
  \def\btxurldatecomment##1{\protect\foreignlanguage{#1}{, posje\'{c}eno ##1}}%
  \def\btxfnamespaceshort{\ }%
  \def\btxfnamespacelong{ }%
  \def\btxnumeralshort##1{\btxnumeraldot{#1}{##1}}%
  \def\btxnumerallong##1{\btxnumeraldot{#1}{##1}}%
%    \end{macrocode}
% Define how to print month and year in numeric format, e.\,g. MM/YYYY.
%    \begin{macrocode}
  \def\btxprintmonthyearnum##1##2{##1/##2}%
  \def\btxkeywordlanguage##1{{\protect\selectlanguage{#1}##1}}%
  \ifbbbblanguagenames
    \def\btxlanguagenameamerican{\protect\foreignlanguage{#1}{engleski}}%
    \def\btxlanguagenameaustrian{\protect\foreignlanguage{#1}{njema\v{c}ki}}%
    \def\btxlanguagenamebrazil{\protect\foreignlanguage{#1}{portugalski}}%
    \def\btxlanguagenamebrazilian{\protect\foreignlanguage{#1}{portugalski}}%
    \def\btxlanguagenamebritish{\protect\foreignlanguage{#1}{engleski}}%
    \def\btxlanguagenamebulgarian{\protect\foreignlanguage{#1}{bugarski}}%
    \def\btxlanguagenamecanadian{\protect\foreignlanguage{#1}{engleski}}%
    \def\btxlanguagenamecanadien{\protect\foreignlanguage{#1}{francuski}}%
    \def\btxlanguagenamecatalan{\protect\foreignlanguage{#1}{katalonski}}%
    \def\btxlanguagenamecroatian{\protect\foreignlanguage{#1}{hrvatski}}%
    \def\btxlanguagenameczech{\protect\foreignlanguage{#1}{\v{c}e\v{s}ki}}%
    \def\btxlanguagenamedanish{\protect\foreignlanguage{#1}{danski}}%
    \def\btxlanguagenamedutch{\protect\foreignlanguage{#1}{nizozemski}}%
    \def\btxlanguagenameenglish{\protect\foreignlanguage{#1}{engleski}}%
    \def\btxlanguagenameesperanto{\protect\foreignlanguage{#1}{esperanto}}%
    \def\btxlanguagenamefinnish{\protect\foreignlanguage{#1}{finski}}%
    \def\btxlanguagenamefrancais{\protect\foreignlanguage{#1}{francuski}}%
    \def\btxlanguagenamefrench{\protect\foreignlanguage{#1}{francuski}}%
    \def\btxlanguagenamefrenchb{\protect\foreignlanguage{#1}{francuski}}%
    \def\btxlanguagenamegerman{\protect\foreignlanguage{#1}{njema\v{c}ki}}%
    \def\btxlanguagenamegermanb{\protect\foreignlanguage{#1}{njema\v{c}ki}}%
    \def\btxlanguagenamegreek{\protect\foreignlanguage{#1}{gr\v{c}ki}}%
    \def\btxlanguagenamehebrew{\protect\foreignlanguage{#1}{hebrejski}}%
    \def\btxlanguagenamehungarian{\protect\foreignlanguage{#1}{ma\dj{}arski}}%
    \def\btxlanguagenameicelandic{\protect\foreignlanguage{#1}{islandski}}%
    \def\btxlanguagenameirish{\protect\foreignlanguage{#1}{irski}}%
    \def\btxlanguagenameitalian{\protect\foreignlanguage{#1}{talijanski}}%
    \def\btxlanguagenamelatin{\protect\foreignlanguage{#1}{latinski}}%
    \def\btxlanguagenamenaustrian{\protect\foreignlanguage{#1}{njema\v{c}ki}}%
    \def\btxlanguagenamengerman{\protect\foreignlanguage{#1}{njema\v{c}ki}}%
    \def\btxlanguagenamenorsk{\protect\foreignlanguage{#1}{norve\v{s}ki}}%
    \def\btxlanguagenamenynorsk{\protect\foreignlanguage{#1}{novonorve\v{s}ki}}%
    \def\btxlanguagenamepolish{\protect\foreignlanguage{#1}{poljski}}%
    \def\btxlanguagenameportuges{\protect\foreignlanguage{#1}{portugalski}}%
    \def\btxlanguagenameportuguese{\protect\foreignlanguage{#1}{portugalski}}%
    \def\btxlanguagenamerussian{\protect\foreignlanguage{#1}{ruski}}%
    \def\btxlanguagenamescottish{\protect\foreignlanguage{#1}{\v{s}kotski}}%
    \def\btxlanguagenameserbian{\protect\foreignlanguage{#1}{srpski}}%
    \def\btxlanguagenamespanish{\protect\foreignlanguage{#1}{\v{s}panjolski}}%
    \def\btxlanguagenameswedish{\protect\foreignlanguage{#1}{\v{s}vedski}}%
    \def\btxlanguagenameturkish{\protect\foreignlanguage{#1}{turski}}%
    \def\btxlanguagenameUKenglish{\protect\foreignlanguage{#1}{engleski}}%
    \def\btxlanguagenameUSenglish{\protect\foreignlanguage{#1}{engleski}}%
  \fi
}
%    \end{macrocode}
% \end{macro}
% Append the definitions to the language-calling commands.
%    \begin{macrocode}
\AtBeginDocument{%
  \ifbbbbfixlanguage
  \else
    \bbbbaddto{croatian}{bibscroatian}
  \fi
%    \end{macrocode}
% Switch on the change of case in titles for all Afrikaans dialects by
% appending \cs{btxifchangecaseoff} to \cs{extras}\meta{language}.
%    \begin{macrocode}
  \bbbbaddto{croatian}{btxifchangecaseoff}
}
%</croatian>
%    \end{macrocode}

**Comment by plk** [comment]
The .lbx files for biblatex are very specific to biblatex, codewise. We can't really change that.

**Comment by ivankokan** [comment]
I thought of using same terms for the same thing; not (just) to copy/paste the source code, but to re-use what can be re-used (in order to have things aligned as much as possible).

**Comment by plk** [comment]
even that's very difficult because the terms are keys which have to be declared globally in the .sty files. It would break a lot of user customisation and biblatex sytles potentially.

**Comment by plk** [comment]
I'm closing this as we would need a major lang interface overhaul to address this.
