### ISSUE TITLE
Problem with \rangelen

### ISSUE THREAD

**Issue by gvdgdo** [plk/biblatex#257]
It seems that `\rangelen` does not work as advertised in the example on page 194 of the manual.

It seems it works if the input is an explicit range (e.g., "10-15") but not if passed implicitly (e.g., `\thefield{pages}`)

Here is an MWE:

		\documentclass{article}
		\usepackage{filecontents}
		\usepackage{biblatex}
		\begin{filecontents}{\jobname.bib}
		@book{a,
		  title={Title},
		  author={Author, A},
		  year={2014},
		  pages={10-15}
		}
		@book{b,
		  title={Title},
		  author={Buthor, A},
		  year={2014},
		  pages={10-}
		}
		@book{c,
		  title={Title},
		  author={Cuthor, A},
		  year={2014},
		  pages={10}
		}
		\end{filecontents}
		\addbibresource{\jobname.bib}

		\DeclareBibliographyDriver{book}{
			(10-15)\rangelen{10-15}\\
			(10-)\rangelen{10-}\\ 
			(-10)\rangelen{-10}\\
			(10)\rangelen{10}\\
			\printfield{pages}: Number of pages reported by rangelen \rangelen{pages}\par
			Testing the example in the manual:
		 \ifnumcomp{\rangelen{\thefield{pages}}}
		   {=}
		   {1}
		   {add f}
		   {do nothing}.
		}

		\begin{document}
		\nocite{*}
		\printbibliography
		\end{document}

![screen shot 2014-07-19 at 8 22 20 am](https://cloud.githubusercontent.com/assets/1285907/3632679/0b1f1b9c-0eca-11e4-96e6-59f9b0380b23.png)

**Comment by u-fischer** [comment]
@JosephWright There is aproblem with the new definition of \rangelen in biblatex. Calls with open ranges e.g. `\rangelen{1-}` fail with `Missing $ inserted.`. As far as I can see the reason is that  & has catcode 3 (math shift) at the moment of the definition of rangelen + internal commands in biblatex2.sty

~~~~~
\documentclass{article}

\usepackage[]{biblatex}
 
\begin{document}
\rangelen{-1} 
\end{document}
~~~~~

**Comment by josephwright** [comment]
The issue is with `\ifblank`: fix in hand.

**Comment by jspitz** [comment]
> Joseph Wright has created a better implementation of `\rangelen` and there is a new macro `\frangelen` 

Is the documentation of `\rangelen` correct? Contrary to what is written here, it says it takes a ffield as parameter. Also, `\frangelen` does not seem to be documented at all.
