### ISSUE TITLE
Serial Articles -- Articles in Installments / relatedtype=serial

### ISSUE THREAD

**Issue by demai** [plk/biblatex#272]
Sometimes articles are published in installments, the different parts of the article not being independent articles, but constituting one longer article that is only split up into parts due to space constraints. Right now, it is not possible to reference such a publication with biblatex. What we need is something like this:

@article{serialarticle,
author = {John Doe},
title = {Long article split into parts},
journaltitle = {Journal for short articles only},
volume1 = {1},
pages1 = {1-15},
volume2 = {2},
pages2 = {10-30},
}

I guess that, as long as biblatex sticks to bibtex's datamodel, as opposed to xml, it won't be possible to assign multiple page and issue fields to one record.

So, for the moment it seems best to enter the entries as related entries:

@article{serialarticle,
author = {John Doe},
title = {Long article split into parts},
journaltitle = {Journal for short articles only},
related = {serialarticle-pt1;serialarticle-pt2},
relatedtype = {serial}, % NEW, does not exist yet
}

@article{serialarticle-pt1,
author = {John Doe},
title = {Long article split into parts [pt. 1]},
journaltitle = {Journal for short articles only},
volume = {1},
pages = {1-15},
}

@article{serialarticle-pt2,
author = {John Doe},
title = {Long article split into parts [pt. 2]},
journaltitle = {Journal for short articles only},
volume = {2},
pages = {10-30},
}

What is needed then is a new relatedtype serial that will omit all unneccessary data, like author, title, and journaltitle, and output only volume and page information. 

I could, of course, simply delete these fields in the database, but this makes database-entries less readable. In a few months, I might not remember what serialarticle-pt2 was exactly.

**Comment by plk** [comment]
We generally don't want specific solutions in the core since it is so extensible now. Closing this for now.
