### ISSUE TITLE
Language by field

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#274]
I have read the manual of v 4.0, and I have found no things. 

The langid field define the language of all the entry. But it's possible we have language which are not the same in differents fields. For example, in the case of a @incollection in english edited in a @collection in french : the language of the booktitle field should be french and title field should be english...

Should it be possible to add feature to allow to switch language/hyphenation between fields.

I imagine something like booktitle_langid, title_langid. In case of @crossref, the xxx_langid will follow the xxx source.

**Comment by maieul** [comment]
hi, 

do you have some news for this issue?

**Comment by plk** [comment]
Yes, I have refactored a lot of code in biber and I have to a bit more in biblatex still. It's a lot of work as I had to rethink the whole system.

**Comment by maieul** [comment]
ok, don't hesitate to ask me for test

**Comment by maieul** [comment]
hi, do you think to have time to work in it, or is it a dead project?

**Comment by plk** [comment]
I had done most of the biber work but I have currently no time to look into the biblatex part - I think we really need to find an active biblatex developer to help on this if you have any ideas ...

**Comment by maieul** [comment]
unfortunatly, I have no idea :-(. I have also a lot of thing to do in reledmac/reledpar, and I can understand you have no time. but I see noone.

**Comment by plk** [comment]
I will close this for now - this whole thing needs re-thinking.

**Comment by maieul** [comment]
I understand you close. All the conversation is quite complex. Maybe we could just open an issue with the conclusion on the last comments?
