### ISSUE TITLE
French, autocite and punctuation mark

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#278]
The `\autocite` command moves the following ponctuation mark before the footnote calling (when citation style use footnote). It's nice, but I think that,  if the French language is detected, it should be disabled by default : in french, the punctuation mark is always after the footnote calling (it's more logical ! the footnote is related to the sentence which finishes, not to the sentence which starts).

If you are afraid by breaking compatibility, juste close this issue.

**Comment by josephwright** [comment]
I see your point, but I'm not sure that the auto-behaviour should really be language-dependent (the whole business about `babel` conflating language and stylist issues). The logic has little to do with it: it's logical in English to put superscript refs. 'inside' a sentence but it looks bad and is only done by a subset of publishers! I'd say this is a 'WONTFIX' for that reason.

**Comment by maieul** [comment]
indeed, for french user, the superscripts refs outside is the bad ;-). I don't understand why the default behavior should be the English one...

**Comment by josephwright** [comment]
My point at least in part was that this is not a language thing: it's a style thing. Some publishers in English put superscripts before punctuation, others do not. Thus the behaviour is simply an arbitrary choice, which here is the one that looks better (visually).

**Comment by maieul** [comment]
ok, but in this case, could it be possible to have option for \autocite which disabe this correction (I won't speak about what typography is better... we don't agree)

**Comment by josephwright** [comment]
That's already done :-) `\DeclareAutoPunctuation{}` is the same as setting `autopunct=false` on loading, or you can construct a more nuanced list. As I say, my point about not linking to language is that this is really a style thing so should not be language-dependent. (`babel`, whilst clever and complex, makes this mistake far too often.)

**Comment by maieul** [comment]
oh, I forgotten it ;-) thanks
