### ISSUE TITLE
Biblatex + Memoir + hyperref - link targets too low

### ISSUE THREAD

**Issue by bendikro** [plk/biblatex#280]
I've encountered an issue described at [Stackexchange: Certain hyperlinks (memoir+hyperref) placed too low ](http://tex.stackexchange.com/questions/59359/certain-hyperlinks-memoirhyperref-placed-too-low) where some hyperref link targets are too low.

The first answer on Stackexchange proposes a fix by patching memoir, by removing `\phantomsection` statements that adds a hyperref target *after* the respective header.

However, I found that to fix the issue when using biblatex's `\printbibliography`, the biblatex code in `biblatex.def` must be changed.
As described in the second answer on Stackexchange, the issue lies in the `\defbibheading` definitons specific for when memoir is loaded such as https://github.com/plk/biblatex/blob/7dab6fa354a2b20c9ff4a6d3971aeb0cf68ab7e7/tex/latex/biblatex/biblatex.def#L1969

Why is the `\phantomsection` placed after the `\section*{#1}`? Is there an advantage to this compared to:
```LaTeX
\defbibheading{bibintoc}[\bibname]{%
\phantomsection
\chapter*{#1}%
\addcontentsline{toc}{chapter}{#1}%
\markboth{\memUChead{#1}}{\memUChead{#1}}}
```

**Comment by plk** [comment]
Any update on this?

**Comment by bendikro** [comment]
I never got a reply from Lars Mad­sen, so no updates on that.

**Comment by plk** [comment]
I'm closing this for now as we just don't have enough information to do anything sensible. It hasn't been raised again in over a year.
