### ISSUE TITLE
No support for editor of articles

### ISSUE THREAD

**Issue by SverreStausland** [plk/biblatex#286]
In my latest project, I've come across several articles in both books and journals that don't have an author, but an editor. As it stands now, biblatex doesn't support such cases, since ``editor`` always refers to the editor of the book or journal, and not to the editor of the article.

This is probably very rare in the sciences, but it's quite a common scenario in the humanities. Below is a real bibliography example:

@INCOLLECTION{daae1907,
	BOOKTITLE = "Historiske Samlinger",
	TITLE = "Breve til Rector Fredrik Moltke Bugge (1836--1844)",
	YEAR = "1907",
	EDITOR = "Ludvig Daae",
	LOCATION = "Christiania",
	NOTE = "Udgivne af Den Norske Historiske Kildeskriftkommission",
	PAGES = "173--223",
	PUBLISHER = "Jac. Dybwad",
	VOLUME = "2"}

This is an article in a book. The article is edited by Ludvig Daae, hence ``editor = "Ludvig Daae"``. The title translates into "Letters to president F.M.B. (1836-1844)", and this explains why there is nothing in the ``author`` field.

If this is compiled, then the output will put the title first in the bibliography, which is inappropriate. It will also indicate that Ludvig Daae is the editor of the book, which he is not.

\documentclass{article}
\usepackage[style = authoryear-comp]{biblatex}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@INCOLLECTION{daae1907,
	BOOKTITLE = "Historiske Samlinger",
	TITLE = "Breve til Rector Fredrik Moltke Bugge (1836--1844)",
	YEAR = "1907",
	EDITOR = "Ludvig Daae",
	LOCATION = "Christiania",
	NOTE = "Udgivne af Den Norske Historiske Kildeskriftkommission",
	PAGES = "173--223",
	PUBLISHER = "Jac. Dybwad",
	VOLUME = "2"}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}
\nocite{*}
\printbibliography
\end{document}

This entry should be listed as "Daae, Ludvig (ed.). 1907. "Breve til Rector Fredrik Moltke Bugge (1836-1844)". In: _Historiske Samlinger_. Vol. 2. [etc.]".

For reasons of semantic consistency, I think ``editor`` should behave like ``author``, i.e. it should always refer to ``title``. If the editor is the editor of the book or journal, then there should be a field ``journaleditor`` and ``bookeditor``, just as there are fields ``journaltitle`` and ``booktitle``.

If this is problematic for reasons of backwards compatibility, then I suggest to introduce a new field ``titleeditor``, and this should be accompanied by an option ``usetitleeditor = true/false`` in case it's better to list/sort an entry by the editor of the article rather than the author of the article (in those cases where there is both an author and an editor of an article, which is not the case in the example used above).

**Comment by aboruvka** [comment]
You can define new fields with biber. If you want `useeditor` to be handled by `in*` entry types the same way as standalone works, just use:

```latex
\renewbibmacro{author/translator+others}{%
  \usebibmacro{author/editor+others/translator+others}}
```
