### ISSUE TITLE
Misleading description of \DeclareBibliographyAlias

### ISSUE THREAD

**Issue by u-fischer** [plk/biblatex#290]
The documentation describes 

     \DeclareBibliographyAlias{alias}{entrytype}
       If a bibliography driver covers more than one entry type, this command may be used
       to define an alias. This command is optional. The entrytype argument may also
       be an asterisk. In this case, the alias serves as a fallback which is used if no specific
       driver for the entry type has been defined.

which imho is wrong or at least very misleading. It is not the *entrytype*  argument which may be an asterisk but the alias (standard.bbx contains the line `\DeclareBibliographyAlias{*}{misc}`. And then not *alias* is the fallback but the type in the (second) argument *entrytype*.  Imho it would be also a good idea to add a clarification that *entrytype* must be a known type for which a driver is defined and that *alias* is then using this driver.

**Comment by plk** [comment]
Thanks - this has been addressed in the Git DEV branch.
