### ISSUE TITLE
the way biblatex patchs `\l@dold@footnotetext` and some other command 

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#291]
Hi,

biblatex add `\toggletrue{blx@footnote}` to some command (l. 142 sq of biblatex.sty). 

That means that when using 

````latex
\documentclass{article}
\usepackage{eledmac}
\usepackage{biblatex} 
````

The `\l@doldold@footnotetext` means 

````latex
#1->\ifm@mfnmargin \marginpar {\def \baselinestretch {\m@m@footnote@spacing }\r
eset@font \foottextfont \protected@edef \@currentlabel {\csname p@footnote\endc
sname \@thefnmark }\color@begingroup \toggletrue {blx@footnote}\@makefntext {\i
gnorespaces #1}\color@endgroup }\else \insert \footins {\def \baselinestretch {
\m@m@footnote@spacing }\reset@font \foottextfont \@preamfntext \hsize \columnwi
dth \protected@edef \@currentlabel {\csname p@footnote\endcsname \@thefnmark }\
color@begingroup \@makefntext {\rule \z@ \footnotesep \ignorespaces {\foottextf
ont #1}\@finalstrut \strutbox }\color@endgroup }\fi \m@mmf@prepare
`````

As you can see, a ` \toggletrue {blx@footnote}` is add after the first `\color@begingroup` but not after the last. 

That cause problem (see http://tex.stackexchange.com/q/223388/7712). I have patched eledmac (https://github.com/maieul/ledmac/tree/issue232) to solve it, but I think this problem could happen with some other package...

**Comment by josephwright** [comment]
The patching done by `biblatex` is deliberately targeting a pretty small range of packages here. If you've fixed it at your end then I suspect that is the best plan.
