### ISSUE TITLE
more mainxxx field

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#294]
Hi,

if we have 

`````
@mvcollection{X,
  title={X},
  editor={name}
}
@collection{Y,
  title={Y},
  crossref={X},
  editor={other name}
}
@incollection{Z,
  title={Z},
  crossref={Z},
}
`````

Z as the field : 
- editor = "other name"
- title = "Z"
- booktitle ="Y"
- maintitle="X"

but there is field like "maineditor" equals to "name".

I think it should be nice. I am thinking about some collections in multiple volumes which has a general editor for all the connexion but particular editor for specific volumes. See http://www.sudoc.fr/149827350 (mvcollection) http://www.sudoc.fr/002886766 (collection)

**Comment by aboruvka** [comment]
The default data model isn't intended to be exhaustive - it represents an essential set of fields compatible with BibTeX. If you need these new name fields, just extend the data model with biber.
