### ISSUE TITLE
Spurious White Space After Undefined Citation Label in Numeric Styles

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#296]
In the following MWE a space is left after the undefined citation's label printed in bold and before the closing square bracket.

```TeX
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[backend=biber, style=numeric]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{lorem}
\end{document}
```
Adding a `%` after [Line 7376 in `biblatex2.sty`](https://github.com/plk/biblatex/blob/master/tex/latex/biblatex/biblatex2.sty#L7376) seems to take care of this problem.

**Comment by plk** [comment]
Many thanks, this is fixed in the dev branch.
