### ISSUE TITLE
feature request: means to create copies of entries with new keys on the fly

### ISSUE THREAD

**Issue by u-fischer** [plk/biblatex#297]
I'm currently fighting with "overlapping" bibliographies: I have to create bibliographies split by filters (easy) but where some entries can be in two or more of the bibliographies. And this leads to problems with the numbering 
http://tex.stackexchange.com/questions/228310/biblatex-numbering-of-overlapping-bibliographies
(which could be solved with labels and \ref) but also with the sorting: the real sorting should be "none", and so in the example in tex.sx `\cite{sarfraz,spiegelberg}\citer{spiegelberg,sarfraz}` should lead to different sortings in the two bibliographies. 

All this problems could be easily solved if I could somehow create a copy of some (or all) bib entries with a different bib-key: If there were a "rel-spiegelberg" and "rel-sarfraz" entry, everything would work smoothly.  

So I thought that the following extensions would be useful:

1. If biber could create (on-the-fly or permantly) a copy of a bib-file where a prefix is added to every entrykey.

2. If one the biblatex side one could trigger and load such a "prefix-bib" with `\addbibresource` or create them with a sourcemap. Naturally it must then be possible to "reload" a bib-file:

~~~~~
\addbibresource{biblatex-examples.bib}
\addbibresource[prefix=rel-]{biblatex-examples.bib}
~~~~~

A problem will be the handling of xrefs and crossref but as their values can be changed with sourcemaps (is this correct?) users who want to use prefixed entries should be able to adjust them to their needs. 

Ulrike Fischer

**Comment by plk** [comment]
I'm not sure this will be a good solution because then you'd have cloned entries with identical name/year etc. combinations which would increment extrayear, extratitleyear etc. Normally you have to isolate via refsections - that doesn't work for you?

**Comment by u-fischer** [comment]
Yes, extrayear etc is another problem. So such prefixed bibliographies should be used with much care. But in my case it wouldn't matter (as everything is numbered). (Imho they could be useful also to avoid duplicates when you have to combine bib-file from various sources).

I also looked into the refsection code and tried to figure out if it would be possible to assign my  \citer-commands to a specific refsection. But I couldn't find a suitable way.

**Comment by plk** [comment]
Ok, I'm looking into your suggested solution.

**Comment by u-fischer** [comment]
I had an idea how to use refsection for the problem: The `\citer` commands can store the keys in a growing (comma) list, and at the end I can then do

~~~~~
\begin{refsection}
\nocite{<list>}
\printbibliography
\end{refsection}
~~~~~

Combined with a \label/ref-system (if one can't get the number from aux)  to print out the numbers (and with correct settings of defernumbers and resetnumbers etc) of the `\citer` this should imho work  or do you see a flaw?

**Comment by plk** [comment]
That would probably work since refsections are in theory completely isolated from each other. However, I can also try to implement the other solution for you to try in DEV since it looks a bit cleaner?

**Comment by plk** [comment]
Let me know how you get on with your solution since I looked at the other "prefix" adding way and it is very complicated due to the way datasources are expected to be unique based on filenames.

**Comment by plk** [comment]
I have implemented something to try in biber DEV - you can now "clone" an entry using source mapping. The clone takes a prefix parameter which will be prepended to the entry key of the cloned entries. This creates a clone of every entry which is cited and found in the datasource. Try this in your pre-amble:

```
\DeclareSourcemap{
  \maps[datatype=bibtex]{
    \map{
      \perdatasource{biblatex-examples.bib}
      \step[entryclone={rel-}]
    }
  }
}
```

These clones still need to be cited otherwise they won't appear in the .bbl (for obvious reasons - it would mess up a lot of automatic labels etc. if they just appeared automatically). Does this help you with the original problem?

If I replace:

```
\citer{spiegelberg}
```
with

```
\citer{rel-spiegelberg}
```

along with using the sourcemap above and using your original TSE example, the numbering then looks ok to me.

**Comment by u-fischer** [comment]
The idea with the refsection + \nocite works. Currently I was looking in the code to find out how the numbering in refsections are handled to decide how to best reference such a numbering "from the outside". 

The Sourcemap-solution sounds very good  and much more comfortable, it is naturally very sensible that the entries don't appear in a bbl unless cited. I will test it asap and give feedback.

**Comment by u-fischer** [comment]
I tested it and it doesn't work correctly yet ;-(. The problem are entries cited *only* as rel-key: There are not found. E.g. 

~~~~~
\cite{shore,sarfraz,spiegelberg}
\citer{rel-spiegelberg,rel-springer}
~~~~~

Then rel-spiegelberg is good, but rel-springer not. Here a complete copy of my test file:

~~~~~
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[style=numeric,defernumbers,sortcites]{biblatex}
\DeclareBibliographyCategory{related}
\DeclareBibliographyCategory{main}

\DeclareCiteCommand{\cite}[\mkbibbrackets]
  {\usebibmacro{prenote}}
  {\addtocategory{main}{\thefield{entrykey}}%
   \usebibmacro{citeindex}%
   \usebibmacro{cite}}
  {\multicitedelim}
  {\usebibmacro{postnote}}

\DeclareCiteCommand{\citer}[\mkbibparens]
  {\usebibmacro{prenote}}
  {\addtocategory{related}{\thefield{entrykey}}%
   \usebibmacro{citeindex}%
   \usebibmacro{cite}}
  {\multicitedelim}
  {\usebibmacro{postnote}}

\addbibresource{biblatex-examples.bib}

\DeclareSourcemap{
  \maps[datatype=bibtex]{
    \map{
      \perdatasource{biblatex-examples.bib}
      \step[entryclone={rel-}]
    }
  }
}

\begin{document}
\cite{shore,sarfraz,spiegelberg}

\citer{rel-spiegelberg,rel-springer}

\printbibliography[category=main,title=Main List,resetnumbers]

\DeclareFieldFormat{labelnumberwidth}{\mkbibparens{#1}}
\printbibliography[category=related,resetnumbers,title=Related Documents]

\end{document}
~~~~~

**Comment by plk** [comment]
Well, "springer" was not cited so that's not so surprising - you can't clone something that wasn't cited as sourcemaps are applied to each entry retrieved from the data sources. Just add `\nocite{springer}` too.

**Comment by u-fischer** [comment]
> Well, "springer" was not cited so that's not so surprising - you can't clone something that wasn't cited as sourcemaps

Well it was surprising for me ;-). I thought the sourcemap would clone the complete bib and all the clones would be lurking around and waiting to be used. But with \nocite (and suitable uses of categories) it works fine. Thanks.

**Comment by plk** [comment]
The problem is that the sourcemapping is a loop over entries which were cited and then found in the data sources so you have to get the entries into the loop with some cite or nocite command. I think that isn't so bad and if it works for you know, that's good.
