### ISSUE TITLE
parencitedelim

### ISSUE THREAD

**Issue by pank** [plk/biblatex#298]
Hi,

For `authoryear` style (and I guess `biblatex-chicago`) it would be great to have something like `\textcitedelim` for `\parencite(s)`.   In some cases, (foo 1999, bar 2011, and baz 1994) may be nicer.

I tried to set `\multicitedelim` to `\textcitedelim`, but it seems `\iffinalcitedelim` only works for `\textcite` commands.

Thanks,
Rasmus

**Comment by aboruvka** [comment]
`\textcite` is intended for citations that form part of sentence, so its delimiters behave differently from the other citation commands. Parenthetical citations do not form a sentence, so the current behaviour is correct and reflects recommendations in most style guides. If you still want to do this, post a question at http://tex.stackexchange.com/.

Feature requests for contributed styles (like biblatex-chicago) should go to the style author. In this case, I have doubts that your request will be considered, as it violates the Chicago Manual of Style.
