### ISSUE TITLE
Negated version of \pertype

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#299]
In the spirit of [this question on stackexchange](http://tex.stackexchange.com/q/229428/) I was wondering if it is possible to support a negated version of `\pertype` in sourcemapping instructions. A step would then apply to all entries that are not of the specified type.

Taking this further, it seems to me that logically, the `\pertypes` are linked with an OR; could it be possible to allow more fine-grained control over the application of source mapping steps (I am thinking about an application where I want maps to apply to all BUT `@online` and `@misc`, for example) - much in the way of the various very complex `\ifboolexpr` one can come up with in other commands?

While the first part of my request seems quite feasible to me (one would probably only have to add another command and add another line of logic in Biber), the second one is more of a nice idea and probably much harder to achieve and implement properly.

**Comment by plk** [comment]
Good point. I have added `\pernottype` and since you specify multiple values of this (and also `\pertype`), you can have quite reasonable control now. You example would be:

```
\pernottype{online}
\pernottype{misc}
```

You can get this by pulling the DEV biblatex 3.0 and DEV biber 2.0

**Comment by moewew** [comment]
That's great, thank you very much.
