### ISSUE TITLE
\newrefcontext

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#301]
With biblatex 3.0, the sorting option for \printbibliography has been deleted and replaced by \newrefcontext. However, I don't understand how I could have the same bibliography with multiple sorting.

I have tried

https://github.com/maieul/biblatex-realauthor/blob/userealauthor/documentation/example.tex

But I obtain ./example.tex:26: Package biblatex Error: Nested 'refcontext' environment.

**Comment by plk** [comment]
You either need to close the refcontexts after each printbib with `\endrefcontext` or use the `\begin{refcontext}\end{refcontext}` environment - can you try that?

**Comment by maieul** [comment]
with \new � \ref it is not working https://github.com/maieul/biblatex-realauthor/commit/83229fc9cb2c8758998587cbf0d480344e41d448
with begin�end  it's working https://github.com/maieul/biblatex-realauthor/commit/b809d36976cd0c96c639b3049de9cba41cad4391 

in any case, the handbook is not full for this feature� there is no mention of closing.

**Comment by plk** [comment]
Ah, you are right, I think this is a bug. Can you pull 3.0 again and see what it does now? You should not have to use `\endrefcontext` - it should be automatic when the next `\newrefcontext` is found.

**Comment by maieul** [comment]
it's working.

**Comment by plk** [comment]
Ok, great, thanks for testing.

**Comment by maieul** [comment]
thank for coding.
