### ISSUE TITLE
usexxxname set to true

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#302]
Sorry, I forget one thing when test \usexxxname
With 3.0, the default setting is false, while it should be true, as for biblatex 2.0 userealauthor is set to true.

**Comment by plk** [comment]
They actually can't be true by default because of some internals - these custom names options are created after package load and so have to be false by default.

**Comment by maieul** [comment]
I don't understand. There are created after package load� but I can use them as package option...

**Comment by plk** [comment]
Yes, the problem is that all of the options and counters for names are created when the data-model is read (because what a "name" is, is defined by the data model) and this is after package load ...

**Comment by maieul** [comment]
I have conturned this limit by adding \ExecuteBibliographyOptions{userealauthor=true}  in the .bbx linked to the .dbx. https://github.com/maieul/biblatex-realauthor/commit/703d8b05e7005347915889a17686f16c7afb7ca0.

I think this point should be documented.

**Comment by plk** [comment]
Ok, yes, you can do that because the .bbx is loaded after the .dbx. I think many style authors use `\ExecuteBibliographyOptions` in the .bbx so this is a good standard way to do it.

**Comment by maieul** [comment]
I think this should be indicated in the handbook, because it's breaking compatibility. With version 2.0, a new name field is use by default in sorting schem which calls it, and not in new version. So the sorting will be bad. Except if user/dev add such line.

**Comment by plk** [comment]
Ok, I realised that I can do this and so custom name toggles will be by default true. You can also set them in the `\usepackage[]{biblatex}` call. I haven't updated biblatex on SF with this fix yet, will do so tonight.

**Comment by maieul** [comment]
ok. send me a message when done. I will do a try.

**Comment by plk** [comment]
It's uploaded

**Comment by maieul** [comment]
and it's working ;-) many thank.
