### ISSUE TITLE
Relax "preamble only" \addbibresource restriction

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#303]
Sometimes, you have to gather, in a single (main) source file, source (sub)files from several authors, some of them adding bib resources through `\addbibresource`. It would be convenient to let these commands in the subfiles but that's not currently possible as `\addbibresource` is "preamble only". Is this restriction structural? Would it be possible to get rid of it?

**Comment by plk** [comment]
@josephwright - do you have a sense about this? I had a quick look and I can't see anything obvious but if you remove the restriction, it fails to put the resource in the .bcf if it comes after the preamble.

**Comment by plk** [comment]
This is structural as far as I can see - how important is this?

**Comment by josephwright** [comment]
I'll see what I can come up with as I work on the backend issue: I'm going to be looking at a lot of the related code in the near future.

**Comment by dbitouze** [comment]
> how important is this?

In fact, I could manage thanks to `standalone` package with its `subpreambles` and `sort` options. 

The only trouble is when the subfiles are in subdirectories and imported thanks to `import`'s `\inputfrom` macro, because the latter and `\addbibresource` don't work together (but maybe this should be reported in another issue).
