### ISSUE TITLE
cites-command with emph inside []

### ISSUE THREAD

**Issue by ClintEastwood** [plk/biblatex#304]
It is no problem to use `\cite[\emph{xxx} yyy]{citekey1}`.
It is also no problem to use `\cite[\emph{xxx} yyy]{citekey1} and \cite[zzz]{citekey2}`.

But what does not work is:
`\cites[\emph{xxx} yyy]{citekey1}[zzz]{citekey2}`.

**Comment by maieul** [comment]
I don't reproduce this bug ;(

**Comment by moewew** [comment]
I cannot reproduce the bug either. Everything seems to work just fine.

```
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{biblatex}

\addbibresource{biblatex-examples.bib}

\begin{document}
It is no problem to use \cite[\emph{xxx} yyy]{sigfridsson}.
It is also no problem to use \cite[\emph{xxx} yyy]{sigfridsson} and \cite[zzz]{geer}.

But what does not work is:
\cites[\emph{xxx} yyy]{sigfridsson}[zzz]{geer}.
\end{document}
```

**Comment by aboruvka** [comment]
@moewew Thanks. I think you should take up Philip's offer to be a collaborator here. It would really help in managing all these issues.
