### ISSUE TITLE
entry sets and category filters

### ISSUE THREAD

**Issue by u-fischer** [plk/biblatex#305]
When the member of a set is added to a category but not the set the entry in a filtered bibliography is missing:

~~~~~
\documentclass{scrartcl}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[style=authoryear]{biblatex}
\addbibresource{biblatex-examples.bib}
\DeclareBibliographyCategory{test}
\begin{document}

\cite{set}
\cite{aksin} %member of set
\cite{angenendt}

\addtocategory{test}{aksin}
\addtocategory{test}{angenendt}

\printbibliography[category=test] %neither aksin nor set is shown, 
                                                    % I expected to see "set"

\end{document}
~~~~~

**Comment by plk** [comment]
Why do you expect "set" when you added only "aksin"? It works if you delete the citation of "set" but that seems strange and so I'm looking at it.

**Comment by plk** [comment]
Actually, this is expected I think. If you cite a set and a member of the set, only the set is added to the refsection and so the member isn't in the biblist to filter on for the category. Doing this works:

```
\cite{set}
\newrefsection
\cite{aksin} %member of set
\cite{angenendt}
```

Since you don't want the set in the bibliography in your example, you could also just not cite it since you don't need it.

**Comment by u-fischer** [comment]
> Why do you expect "set" when you added only "aksin"?

because of the citation: aksin has the same output as "set" (Herrmann et al. 2006). So it doesn't make sense to put aksin in the bibliography: you wouldn't find the entry when you follow the citation. So imho the only logical solution is add a set entry to a filter as soon as  a member is added.

**Comment by u-fischer** [comment]
> Actually, this is expected I think. If you cite a set and a member of the set, only the set is
> added to the refsection and so the member isn't in the biblist to filter on for the category.

 I understand why it happens but a suddenly missing entry is never expected ;-)

> Since you don't want the set in the bibliography in your example, you could also just not
> cite it since  you don't need it.

This is minimal example. In the real case the set was cited at a quite different place and it took me quite some time to figure out why in the subbibliography the member entry was missing.

**Comment by plk** [comment]
Actually the citation of aksin is "Aksin et al 2006" if you don't also cite the set which is correct otherwise you wouldn't be able to cite set members individually. However, this seems strange to me - citing aksin when the set is also cited should not cite the set.

**Comment by plk** [comment]
I think you are right about this - within a refsection, citing a set overrides a set member citation and so should do the same for category membership. Please pull 3.0 DEV - I think this is fixed.

**Comment by u-fischer** [comment]
> However, this seems strange to me - citing aksin when the set is also cited should not cite the set.

No, I disagree. This behaviour is logical: The citation must be so that one can identify the entry in the bibliography, and this entry starts with "Wolfgang A. Herrmann et al." If  there is a need to identify the individual entries better one can extend the style so that is something like  numeric with  the option subentry where you get numbers [2b]. If one uses sets one has to accept that the individual member is less visible. 

But documents can be quite large, are often written over a long time and sometimes even by various peoples. sets can be added to a bib (or dynamically to the document)  and be cited at anytime. One can't expect from users to check all the time if this affects some filtering done somewhere, sometime on some member (I didn't tested it but I guess filtering on keywords could have the same problem).

===============
Just seeing your comment ... I will check 3.0. dev  but not today.

**Comment by plk** [comment]
Can you check this? I would like to get this fix into the next release.

**Comment by josephwright** [comment]
@plk  Can who check it?

**Comment by plk** [comment]
Sorry, I meant @u-fischer, the OP.

**Comment by u-fischer** [comment]
Hello, sorry for the delay. It seems to work fine. I also checked a similar setup for keywords, but this seems to work already in the current version (but I didn't check dynamic sets).

**Comment by plk** [comment]
Thanks for checking. Dynamic sets are all done by biber and so I don't think there is a problem there.
