### ISSUE TITLE
Weird citations with authoryear citation style

### ISSUE THREAD

**Issue by erikfleischer** [plk/biblatex#311]
I am using biblatex in a fairly large document with lots of citations using the authoryear style both for citations and the bibliography. While most of the citations are produced ok, some show a strange mixture of the author names. This happens if the same author appears twice but with different co-authors earch time.

I have created a minimal example which produces two citations:

Schweitzer, Traxler, et al. 1993, Schweitzer and Maslen 2009

The biblatex settings are:

    \usepackage[
        style=authoryear,
        maxcitenames=1,
        mincitenames=1,
    ]{biblatex}

This is what I would exspect as citation:

Schweitzer et al. 1993, Schweitzer et al. 2009

My System:
Texlive 2014 on Windows 7
Biblatex Version 2.9a (24/06/2014)

Complete example:
```latex
\documentclass{article}

\usepackage[
	style=authoryear,
	maxcitenames=1,
	mincitenames=1,
]{biblatex}

\begin{filecontents}{\jobname.bib}
@Book{Schweitzer1993,
  Title                    = {Magnetlager},
  Author                   = {Gerhard Schweitzer and Alfons Traxler and Hannes Bleuler},
  Year                     = {1993},
}

@Book{Schweitzer2009,
  Title                    = {Magnetic Bearings},
  Author                   = {Gerhard Schweitzer and Eric Maslen},
  Year                     = {2009},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}
Citation: \cite{Schweitzer1993}, \cite{Schweitzer2009}
\printbibliography
\end{document}
```

**Comment by plk** [comment]
try setting `uniquelist=false` as an option too.

**Comment by erikfleischer** [comment]
Thanks for the quick help. That did the trick.
