### ISSUE TITLE
Is it still mandatory to specify the `.bib` extension?

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#313]
`biblatex`'s documentation (version 3.0) says:

- "Note that files must be specified with their full name, including the   extension. Do not omit the .bib extension from the filename." (p. 71)
- "With Biblatex, resources are specified in the preamble with `\addbibresource` using the full name with .bib suffix." (p. 106)

But the following MWE:
```latex
\documentclass{article}
\usepackage[backend=biber]{biblatex}
\usepackage{filecontents}
\begin{filecontents}{foo}
@misc{aaaa,
  title                    = {Aaaa}
}
\end{filecontents}
\addbibresource{foo}
\begin{document}
\autocite{aaaa}
\printbibliography
\end{document}
```
(which generates a bib file named `foo.tex`) works like a charm.

Hence:

- is it still mandatory to specify the `.bib` extension?
- is it safe to make use of another extension than `.bib` or `.tex`?

**Comment by plk** [comment]
Actually you need this if you want to find bib files in kpsewhich path - try an example which uses the TL installed "biblatex-examples.bib" file without the extension.

**Comment by dbitouze** [comment]
OK. If I understand well, the bib files may have any extension:
- in the case they are located in the same directory as the main `.tex` file,
- in the case they are not located in the same directory as the main `.tex` file as soon as their paths are specified.

**Comment by plk** [comment]
Yes, this should be the case as biber will just load whatever file name is specified.

**Comment by dbitouze** [comment]
OK, thanks.
