### ISSUE TITLE
Bibliography string '#1' undefined

### ISSUE THREAD

**Issue by johannesbottcher** [plk/biblatex#315]
If a string is undefined for a given language, this warning is issued. But it does not report the bib-key, as instead it reports the hash to be found in the bbl file. Luckily it prints the line number as well. >EDIT: this would be the `\printbibliography` line, so it is not really helpful.<

I think it would be easier for users to see the citekey. 

```
Package biblatex Warning: Bibliography string 'astitle' undefined
(biblatex)                at entry 'be4997a317b29ab58b939e0004088d04' on input 
line 10.
```

```latex
\documentclass[ngerman]{article}
\usepackage{babel}
\usepackage[bibstyle=standard]{biblatex}
\addbibresource{biblatex-examples.bib}
\begin{document}
this 
is 
a 
test
\fullcite{vangennep:related}
\end{document}
```

**Comment by aboruvka** [comment]
The hash is the entrykey for the related entry; its parent entrykey is not easily accessible at the warning level. Biber needs to ensure that all related entries can still be directly cited on their own, so it must generate alternative keys.

**Comment by johannesbottcher** [comment]
Ok, thank you.
