### ISSUE TITLE
Too many curly braces in author field cause trouble

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#316]
It seems that using three (!) pairs of curly braces in the `author` field wreaks havoc on one's documents.

Consider the following MWE that fails miserably with `biblatex` 2.9/Biber 1.9 (MikTeX hasn't yet been updated, so I could not check with the most recent versions, sorry).

    \documentclass{article}
    \usepackage{filecontents}
    \begin{filecontents*}{\jobname.bib}
    @article{BNC,
    Author = {{{British National Corpus}}},}
    \end{filecontents*}

    \usepackage{biblatex} 
    \addbibresource{\jobname.bib} 

    \begin{document}
    \nocite{*}
    \printbibliography
    \end{document}

I get a "Paragraph ended before \name was complete." error on the `{{hash=492fcea15240a16e3492124ac14fd819}{{{British\bibnamedelimb National\bibnamedelimb Corpus}}}{{B\bibinitperiod}{}{}{}{}{}{}}` line of the `.bbl` file.

**Comment by u-fischer** [comment]
It works fine in texlive 2015 (pretest) with the new biber and biblatex, so I think the bug has been resolved.

**Comment by moewew** [comment]
Indeed, I just checked with biblatex 3.0/Biber 2.0 and had no trouble running the code whatsoever. Sorry for the noise. The bug seems to be resolved (if eve there was any).
