### ISSUE TITLE
extended printbiblist to have more than one field as possible label

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#317]
The `\printbiblist` feature is very useful. However, there is one limit: it's work with only one field as label.

So if I want to have a list of shortseries and a list of shortjournal, I can do

`````
\printbiblist{shortseries}
\printbiblist{shortjournal}
`````

However, there is, as I know, now easy way to have a list which mix both of them.

**Comment by plk** [comment]
I'm afraid this is too difficult to implement - the name is used to determine many things internally - perhaps you can find some workaround on TSE?

**Comment by maieul** [comment]
ok. I have an idea. But it is complex ;-). It is a mix of my oldest method to produce such list.

**Comment by maieul** [comment]
For your information, I am currently preparing a biblatex-shortfields package, which solve this issue.
