### ISSUE TITLE
typo in handbook (‘labelfield’width)

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#318]
p. 227 of the CTAN handbook 

>‘labelfield’width 

should be

>labelfieldwidth  

shouldn't it ? (same in p.228)

**Comment by plk** [comment]
Actually, no, it's meant to be like that because the part in quotes is not literal - it represents the name of any field defined as a label field in the data model. Perhaps this is not clear?

**Comment by maieul** [comment]
maybe use the generic syntax <somefield> ?

**Comment by plk** [comment]
It is like that in the source, I am not sure why it comes out like that in the typeset version ...
