### ISSUE TITLE
Unexpected behaviour with sorting option, multiple ref context and biblist

### ISSUE THREAD

**Issue by gvdgdo** [plk/biblatex#319]
For a project I'm working on I have large bibliography files where he vast majority of entries are annotated (and the annotation can contain `\cite` commands). I have to list the title and note for the annotated entries and these are to be listed per year in reverse chronological order.  At the end I have to list a normal reference section with the annotated entries and the entries cited in the annotation (and cross-ref entries as well). The  references section uses standard alphabetic order.

For the annotate reverse chronological list I have created a biblist and a special driver for it citing the entry itself. 

Given that I  have no way to know in advance what are the entries to be included  in the first run  I include `\nocite{*}`, this include all the entries form  the bibtex database,  and the filter for the biblist does the job for me.  So for  the second run I no longer need `\nocite{*}`.

So the schema has the following workflow: `pdflatex -> biber -> pdflatex -> biber -> pdflatex` 

`\printbiblist` and `\printbibliography` are in the scope of the appropriate `\newrefcontext` with their sorting option. 

Here is the issue,  if biblatex includes `sorting=xxx` option where `xxx` is different from the sorting options given in the `\newrefcontext` commands, then, in the second pdflatex run no reference entry is printed,  and thus no citation exists for the second biber call.  Removing the sorting option solves the problem. 

Is this the intended behaviour? In my opinion it is counterintuitive, the references exist in the appropriate contexts in the `.bbl` file, and so they should be printed.

Here is  the complete MWE.

		\documentclass{article}

		\usepackage[backend=biber
			sorting=nyt, % this is the problematic line; commenting it solves the problem.
		]{biblatex}
		\usepackage{filecontents}

		\begin{filecontents}{\jobname.bib}
		@book{first,
			title = {First Title},
			author = {Author, Author},
			year = 2015,
			note = {note}
		}
		@book{second,
			title = {Second Title},
			author = {Duthor, Duthor},
			year = 2015,
			note = {note}
		}
		@book{third,
			title = {Third Title},
			author = {Buthor, Buthor},
			year = 2014,
			note = {note}
		}
		@book{fourth,
			title = {Fourth Title},
			author = {Cuthor, Cuthor},
			year = 2014,
			note = {note \cite{seventh}}
		}
		@book{fifth,
			title = {Fifth Title},
			author = {Euthor, Euthor},
			year = 2014,
		}
		@book{sixth,
			title = {Sixth Title},
			author = {Futhor, Futhor},
			year = 2015,
			note = {note}
		}
		@book{seventh,
			title = {Seventh Title},
			author = {Guthor, Guthor},
			year = 2014,
		}
		\end{filecontents}
		\addbibresource{\jobname.bib}

		\renewcommand{\thesubsection}{\arabic{subsection}}

		\DeclareBibliographyDriver{ggtype}{%
			\ifnumless{\thefield{year}}{\value{anno}}
			  {\section*{\printfield{year}}
				 \setcounter{subsection}{0}
				 \setcounter{anno}{\thefield{year}}}
			  {}
			\subsection[]{\thefield{title}}
			\printfield{note} \printfield{year}
			\cite{\thefield{entrykey}}
		}

		\DeclareBibliographyCategory{exclude}
		\addtocategory{exclude}{sixth}

		\DeclareBiblistFilter{ggtype}{
		 \filter[type=field,filter=note]
		}

		\defbibenvironment{ggtype}
		  {\newrefcontext[sorting=nty]}
		  {}
		  {}

		\newcounter{anno}
		\setcounter{anno}{2016}

		\begin{document}
		test
		\newrefcontext[sorting=ydnt]
		\IfFileExists{\jobname.bbl}{}{\nocite{*}}

		\printbiblist[heading=none,notcategory=exclude]{ggtype}
		\printbibliography
		\end{document}

**Comment by plk** [comment]
For the second run you do need the `\nocite{*}` otherwise this won't be written in the .bcf and biber will not look for anything. If I remove the IfFileExists test and just do `\nocite{*}`, it works after the two runs?

**Comment by gvdgdo** [comment]
what is odd is that if I remove the `sorting` option from the biblatex options, there is not need to have a \nocite{*} in the second run, the driver for the biblist generates `\cite`s, and without the sorting option they are written on the bcf file..

The solution you propose works for the MWE, but for my actual project it requires an extra biber/pdflatex round.

**Comment by plk** [comment]
This is strange but so is the use case ...  can look into it but can you also ask on TSE so other people can have some ideas? I am rather snowed under at the moment I'm afraid.

**Comment by gvdgdo** [comment]
No need to hurry (I know how to avoid the problem, remove the default sorting option.  By the way,  The schema/workflow in the MWE worked for Biblatex 2.9 and biber 1.9  (with the appropriate sorting option of \prinbiblist and \printbibliography, with and without the default sorting option).

OK, I’ll post on TSE (tough, the simplest answer is “remove the default ‘sorting’ option :-)

thanks anyway.
