### ISSUE TITLE
\ExecuteBibliographyOptions with same option to times bug

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#320]
Hi, 

suppose the following MWE example:
```latex
\documentclass{article}
\usepackage[citestyle=verbose-trad2]{biblatex}
\ExecuteBibliographyOptions[book]{usetranslator=false}
\ExecuteBibliographyOptions[book]{usetranslator=true}

\usepackage{fontspec}
\setmainfont{Linux Libertine O}
\bibliography{/Users/maieul/Documents/fac/these/these/biblio.bib}

\begin{document}

\cite{somebook}
\end{document}
````

this fails at the second run `invalid boolean value 'falseusetranslator`.

It could seems stupid to set `usetranslator=false` first and the `usetranslator=true` but such case can happen if we want to use somes bibliographic styles EXCEPT for the value of `usetranslator`.

**Comment by plk** [comment]
@josephwright - I am a bit snowed under at the moment - can you take a quick look at this? I suspect you will find out what the issue is a lot faster than me.

**Comment by u-fischer** [comment]
There is obviously a comma missing in some option list. Imho it should be added here:

~~~~~
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[citestyle=verbose-trad2]{biblatex}
\makeatletter
\def\blx@typeoptions#1#2{%
  \blx@addtypeopt{#2}%
  \csappto{blx@opts@type@#2}{#1,}}%<----

\ExecuteBibliographyOptions[book]{usetranslator=false}
\ExecuteBibliographyOptions[book]{usetranslator=true}

\addbibresource{biblatex-examples.bib}

\begin{document}

\cite{nietzsche:ksa1}
\end{document}
~~~~~~

**Comment by plk** [comment]
Careful or you will become a biblatex maintainer (we need some more ...). Yes, this looked suspicious to me and now I think about it, this should be an internal csv list I think. I will look at it now, many thanks.

**Comment by plk** [comment]
This fix works and is in the Git DEV branch, thanks.
