### ISSUE TITLE
\DeclareSourcemap disables sourcemaps in biber.conf

### ISSUE THREAD

**Issue by u-fischer** [plk/biblatex#321]
As has been discussed on tex.sx http://tex.stackexchange.com/questions/247739/handling-interference-between-biber-conf-and-declaresourcemap-of-biblatex:
If a document uses both a sourcemap in biber.conf and a \DeclareSourcemap the settings in biber.conf are ignored. There are no problems with \DeclareStyleSourcemap:

~~~~~
\documentclass{article}
\usepackage{biblatex}

\begin{filecontents*}{biber.conf}
<config>
  <sourcemap>
    <maps datatype="bibtex" map_overwrite="1">
      <map map_overwrite="1">
        <map_step map_field_set="journaltitle" map_field_value="confjournal"/>
      </map>
    </maps>
  </sourcemap>
</config>
\end{filecontents*}

\addbibresource{biblatex-examples.bib}

  \DeclareSourcemap{
      \maps[datatype=bibtex]{
        \map[overwrite]{
          \step[fieldset=author,fieldvalue={sourceauthor}]
      }
    }
  }

\DeclareStyleSourcemap{
      \maps[datatype=bibtex]{
        \map[overwrite]{
          \step[fieldset=title,fieldvalue={styletitle}]
      }
    }
  }


\begin{document}

Citing here: \cite{baez/article}

\printbibliography[sorting=none]

\end{document}
~~~~~

Is this a bug or is the documentation unclear?

**Comment by plk** [comment]
I think the docs are unclear - I added a comment to the TSE question. I'll update the docs.

**Comment by plk** [comment]
Actually, I had a quick look and this case should work and I even have comments about it in the code - it was a while ago. I will look into it.

**Comment by plk** [comment]
Please try biber 2.2 dev version on Sourceforge. This was a bug.
