### ISSUE TITLE
shorttitle inheritance

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#322]
In the handbook p.255 their is a problem : typographical error let think "shorttitle" is inherited in "don".

I profite to ask if it should not be nice to transform shorttitle to "mainshorttitle". In you think it is not need for standard style, does not matter.

**Comment by plk** [comment]
This was just a word-wrap issue - the previous line is wrapping. Fixed in DEV branch. I leave the decision whether to map shorttitle to mainshorttitle to @aboruvka.

**Comment by aboruvka** [comment]
I think leave as-is. The `shorttitle` field is intended for citation labels in author-title styles. So a new `mainshorttitle` field does not make much sense in the standard styles/default data model.
