### ISSUE TITLE
Biblatex 3.0 issue with \mkbibquote in .bib file

### ISSUE THREAD

**Issue by dfussner** [plk/biblatex#323]
When I use \mkbibquote inside a field in the .bib file, I get a series
of errors in the .log file when LaTeX starts to read the .bbl file.
The errors start with the following, though many more appear after it,
and with longer files LaTeX gives up:

! Undefined control sequence.
<recently read> \blx@usqcheck@ii 
                                 
l.52     \endentry

Some entries don't trigger this behavior, but the two in the MWE do,
and you can see an artifact of the errors in the list of references
sometimes, too, as below.

Looking at biblatex2.sty, the definition of \blx@usqcheck still calls
\blx@usqcheck@ii, which is nowhere defined.  Retrieving the definition
of the latter from version 2.9a of biblatex2.sty and inserting it into
the MWE clears the errors, and the output looks OK, at least at first
glance.  Closer inspection of the output in both cases, however,
reveals that the final closing quotes in the Donne entry aren't in
italic, while all others in that entry are.

Here's the MWE:

\documentclass[12pt]{article}
\usepackage{csquotes}
\usepackage[american]{babel}
\usepackage[style=authoryear]{biblatex}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@Article{lewis,
  author =	 {Lewis, Judith},
  title =	 {\mkbibquote{'Tis a Misfortune to Be a Great Ladie}},
  subtitle =	 {Maternal Mortality in the British Aristocracy,
                  1558--1959},
  journaltitle = {Journal of British Studies},
  shorttitle =	 {\mkbibquote{'Tis a Misfortune to Be a Great Ladie}},
  year =	 1998,
  volume =	 37,
  pages =	 {26--53}
}
@Book{donne:var,
  author =	 {Donne, John},
  editor =	 {Stringer, Gary~A.},
  title =	 {The \mkbibquote{Anniversaries} and the
                  \mkbibquote{Epicedes and Obsequies}},
  namea =	 {Stringer, Gary~A. and Pebworth, Ted-Larry},
  publisher =	 {Indiana University Press},
  maintitle =	 {The Variorum Edition of the Poetry of John Donne},
  year =	 1995,
  volume =	 6,
  location =	 {Bloomington},
  shorttitle =	 {\mkbibquote{Anniversaries} and \mkbibquote{Epicedes and
                  Obsequies}}
}
\end{filecontents}
\addbibresource{\jobname.bib}
% \makeatletter
% \def\blx@usqcheck@ii#1{%
%   \if\noexpand#1\relax
%     \blx@usqcheck@i\blx@tempa
%   \fi
%   \if\noexpand#1\noexpand\@let@token
%     \blx@usqcheck@i{\blx@usqcheck@iii\blx@tempa}%
%   \fi
%   \blx@usqcheck@ii}
% \def\blx@usqcheck@iii#1#2{#2#1}
% \makeatother
\begin{document}
\thispagestyle{empty}
\noindent
\cite{lewis}: \cite{donne:var}
\printbibliography
\end{document}

And here's the output on my system:

![mwe6](https://cloud.githubusercontent.com/assets/5174434/8435241/2328d19e-1f48-11e5-8301-f0c2af245f05.png)

Does anyone else see this?

Thanks.

**Comment by plk** [comment]
I haven't seen this but a first thing would be to post to tex.stackexchange.com first to verify if anyone has seen this before.

**Comment by moewew** [comment]
I can reproduce the problem with `biblatex 3`.
To me it also seems that in `biblatex2.sty` some of the relevant definitions are missing, one can either copy those from `biblatex1.sty` or an older version of biblatex. The code sems to have been removed in https://github.com/plk/biblatex/commit/523bf7695cb5b6aaed1664e7670b3a1381f23c3f in order to address https://github.com/plk/biblatex/issues/259.

The problem with the italic quotation seems to be the same as in https://github.com/plk/biblatex/issues/266. Regarding that issue, I presume one would have to somehow insert the format (italic or not) of the current field into `\blx@usoquote@i` and `\blx@usiquote@i`.

**Comment by plk** [comment]
@josephwright - I think this is probably in your area as I think #259 was your fix?

**Comment by josephwright** [comment]
@plk I see how this has happened :-) I'll fix if you let me know which branch to commit it to.

**Comment by plk** [comment]
Can go into the DEV branch, thanks.

**Comment by josephwright** [comment]
Should be sorted by https://github.com/plk/biblatex/commit/d7fd4e141e7a84f9dbbffe22bc49636f1615ceaa (where I've also brought the two `.sty` files into line).
