### ISSUE TITLE
Impossible to get biblatexml output format (Can't call method "autoflush")

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#324]
Hi,

I wanted to test `--output-format=biblatexml` `biber`'s option (what I never tested before). But, the following MWE:
```latex
\documentclass{article}
\usepackage[backend=biber]{biblatex}
\addbibresource{biblatex-examples.bib}
\begin{document}
\autocite{glashow}
\printbibliography
\end{document}
```
processed with `pdflatex` and then with `biber --output-format=biblatexml test.bcf` gives the following error:
```
INFO - This is Biber 2.1
INFO - Logfile is 'test.blg'
INFO - Reading 'test.bcf'
INFO - Found 1 citekeys in bib section 0
Can't call method "autoflush" on an undefined value at /tmp/par-6269746f757a65/cache-3308087a6406c1cdbb226c47854564a247f78657/9ce5ea9f.pm line 68.
```
The specified line contains:
```perl
  $of->autoflush;# Needed for running tests to string refs
```
and, as far I (don't) understand `Perl`, `$of` is defined by:
```perl
  my $of = IO::File->new($toolfile, '>:encoding(UTF-8)');
```
Do you see what's going on?

Thanks.

**Comment by plk** [comment]
You need to use tool mode (--tool) for biblatexml output - it only makes sense in this mode. I will add a warning to biber about this. Don't forget that in tool mode, you call the command on a .bib file, not a .bcf.

**Comment by dbitouze** [comment]
That does the trick: thanks!

I must admit I only read section 3.1.1 "The output-format option" of `biber`'s documentation where the example:
```
biber --output_format=bibtex test.bcf
```
doesn't involve `--tool` option.

**Comment by plk** [comment]
That's true - the bibtex output format can be run in both tool mode and normal mode with different results. biblatexml only really makes sense in tool mode ...
