### ISSUE TITLE
request for origbooktitle, etc.

### ISSUE THREAD

**Issue by ashinpan** [plk/biblatex#325]
The fields "origbooktitle, origbooksubtitle, etc." are not available for biblatex yet, but I think it is really necessary to have such fields. Let me argue using a scenario.

Suppose I am citing an article from an anthology translated into English from German. Accordingly:

1) In my bib file, I put the whole anthology as a collection entry, and the particular article I wish to cite as an incollection entry.

2)  I use a crossref field with the incollection entry to inherit appropriate data from the collection entry.   It means, for example, the "title" field from the collection will be inherited as "booktitle" for the incollection entry.

3) Now, suppose the original German anthology has its own German title. Accordingly, I enter the German title as "origtitle" field in the collection entry.

4) But there is no "origbooktitle" field available, so "origtitle" of the collection would be inherited as the "origtitle" of the incollection entry.

5) Therefore biblatex would understand, mistakenly,  the "origtitle" as that of the incollection, i.e., that of the paper to be cited even though it is the original title of the collection.

  This is why I argue for the fields like "origbooktitle, origbooksubtitle," etc.

**Comment by aboruvka** [comment]
Please give a concrete example with a bib file and desired output - either here or at the [TeX-LaTeX SE](http://tex.stackexchange.com/). This can likely be solved with existing biber features and is probably not suited for inclusion the default data model - which must generally cohere with both biber and bibtex.

**Comment by ashinpan** [comment]
Sample bib file
===========
@collection{bussmann,
	origlanguage = {German},
	editor = {Gregory Trauth and Kerstin Kazzazi},
	translator = {Gregory Trauth and Kerstin Kazzazi},
	title = {Routledge Dictionary of Language and Linguistics},
	origtitle = {Hadumod Bussmann Lexikon der Sprachwissenschaft},
	year = 2006,
	origyear = {1996},
	address = {London},
	publisher = {Routledge}
}

@incollection{bussmann:adjective,
	options = {useeditor=false,usetranslator=false},
	title = {Adjective},
	pages = {19-20},
	crossref = {bussmann}
}

Test.tex
========
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[style=mla,autocite=inline,language=english]{biblatex}
\addbibresource{mytest.bib}
\begin{document}
\autocite{bussmann:adjective}
\printbibliography
\end{document}

Output
========
(“Adjective”)

Works Cited

“Adjective”. Routledge Dictionary of Language and Linguistics. Ed. and trans. Gregory Trauth and Kerstin Kazzazi. London: Routledge, 2006. 19–20. Print. Trans. of “Hadumod Bussmann Lexikon der Sprachwissenschaft”. 1996.

**Comment by ashinpan** [comment]
If you look at the output bibliography, you can see the original title of the collection given in apostrophes, meaning that this is the original title of the incollection, not of the collection---biblatex has completely misunderstood the bib file. If there is a workaround using biber, I would really like to know.

**Comment by aboruvka** [comment]
And the desired output? I suspect you will need to resort to the biber-only related entries feature. This would offer a full solution - not workaround. Here PL discusses its motivation and why we won't continually add `orig*` fields to the data model:

http://sourceforge.net/p/biblatex/oldwiki/Linked_Entries/

Further details on related entries can be found in the biblatex manual. One thing to keep in mind is that the contributed mla style generally has not kept up with biblatex/biber development. So you will likely need to patch mla's bibliography drivers or get in touch with the mla author.

Considering all this, I suggest you follow-up on this issue at the TeX-LaTeX SE. All of the biblatex maintainers and the mla author answer questions there.
