### ISSUE TITLE
Bug in finnish.lbx with a fix

### ISSUE THREAD

**Issue by ahomansikka** [plk/biblatex#326]
$ diff -u /usr/local/texlive/2014/texmf-dist/tex/latex/biblatex/lbx/finnish.lbx new-finnish.lbx
--- /usr/local/texlive/2014/texmf-dist/tex/latex/biblatex/lbx/finnish.lbx	2013-10-28 00:52:35.000000000 +0200
+++ new-finnish.lbx	2015-07-19 14:00:54.293830538 +0300
@@ -74,7 +74,7 @@
   \renewbibmacro{in:}{%
     \iffieldequalstr{entrytype}{article}
       {}
-      {\bibstring{in}\setunit{\intitlepunct}}}%
+      {\printtext{\bibstring{in}\intitlepunct}}}%
 }
 
 \UndeclareBibliographyExtras{%

If you do not want to update your finnish.lbx you
can add this to your preamble

\DefineBibliographyExtras{finnish}{%
  \renewbibmacro{in:}{%
    \iffieldequalstr{entrytype}{article}
      {}
      {\printtext{\bibstring{in}\intitlepunct}}}%
}

**Comment by plk** [comment]
Applied to DEV branch, thanks.
