### ISSUE TITLE
Finnish translation, again

### ISSUE THREAD

**Issue by ahomansikka** [plk/biblatex#327]
My Finnish translation had a syntax error, since I did not test it properly. My bad.
This diff has one new translation and my bug fix on19 July 2015.

--- /usr/local/texlive/2014/texmf-dist/tex/latex/biblatex/lbx/finnish.lbx	2013-10-28 00:52:35.000000000 +0200
+++ new-finnish.lbx	2015-07-21 08:23:06.660627216 +0300
@@ -74,7 +74,7 @@
   \renewbibmacro{in:}{%
     \iffieldequalstr{entrytype}{article}
       {}
-      {\bibstring{in}\setunit{\intitlepunct}}}%
+      {\printtext{\bibstring{in}\intitlepunct}}}%
 }
 
 \UndeclareBibliographyExtras{%
@@ -93,14 +93,14 @@
   compilers        = {{koontaneet}{koontaneet}},% FIXME: unsure
   redactor         = {{toimittanut}{toim\adddot}},% FIXME: unsure
   redactors        = {{toimittaneet}{toim\adddot}},% FIXME: unsure
-% reviser          = {{}{}},% FIXME: missing
-% revisers         = {{}{}},% FIXME: missing
-% founder          = {{}{}},% FIXME: missing
-% founders         = {{}{}},% FIXME: missing
-% continuator      = {{}{}},% FIXME: missing
-% continuators     = {{}{}},% FIXME: missing
-% collaborator     = {{}{}},% FIXME: missing
-% collaborators    = {{}{}},% FIXME: missing
+  reviser          = {{toimittanut}{toim\adddot}},% FIXME: unsure
+  revisers         = {{toimittaneet}{toim\adddot}},% FIXME: unsure
+  founder          = {{perustaja}{perustaja}},
+  founders         = {{perustajat}{perustajat}},
+  continuator      = {{jatkaja}{jatkaja}},% FIXME: unsure
+  continuators     = {{jatkajat}{jatkajat}},% FIXME: unsure
+  collaborator     = {{avustaja}{avustaja}},% FIXME: unsure
+  collaborators    = {{avustajat}{avustajat}},% FIXME: unsure
   translator       = {{k\"a\"ant\"anyt}{k\"a\"ant\adddot}},
   translators      = {{k\"a\"ant\"anyt}{k\"a\"ant\adddot}},
   commentator      = {{kommentaarin kirjoittanut}{kommentaarin kirjoittanut}},
@@ -252,11 +252,11 @@
   byeditor         = {{toimittanut}{toim\adddot}},
   bycompiler       = {{koontanut}{koontanut}},
   byredactor       = {{toimittanut}{toim\adddot}},% FIXME: unsure
-% byreviser        = {{}{}},% FIXME: missing
-% byreviewer       = {{}{}},% FIXME: missing
-% byfounder        = {{}{}},% FIXME: missing
-% bycontinuator    = {{}{}},% FIXME: missing
-% bycollaborator   = {{}{}},% FIXME: missing
+  byreviser        = {{toimittanut}{toim\adddot}},% FIXME: unsure
+  byreviewer       = {{toimittanut}{toim\adddot}},% FIXME: unsure
+  byfounder        = {{perustanut}{perustanut}},% FIXME: unsure
+  bycontinuator    = {{jatkanut}{jatkanut}},% FIXME: unsure
+  bycollaborator   = {{yhteisty\"oss\"a}{yhteisty\"oss\"a}},% FIXME: Bad translation. Impossible to translate with one word.
   bytranslator     = {{\lbx@lfromlang k\"a\"ant\"anyt}{\lbx@sfromlang k\"a\"ant\adddot}},
   bycommentator    = {{kommentaarin kirjoittanut}{kommentaarin kirjoittanut}},% FIXME: unsure
   byannotator      = {{selityksin varustanut}{selityksin varustanut}},% FIXME: unsure
@@ -336,36 +336,36 @@
   and              = {{ja}{ja}},
   andothers        = {{et\addabbrvspace al\adddot}{et\addabbrvspace al\adddot}},
   andmore          = {{et\addabbrvspace al\adddot}{et\addabbrvspace al\adddot}},
-  volume           = {{volyymi}{vol\adddot}},
-  volumes          = {{volyymit}{vol\adddot}},
-  involumes        = {{tilavuusosaan}{tilavuusosaan}},% FIXME: unsure
+  volume           = {{volyymi}{vol\adddot}},% FIXME: Is {{osa}{osa}} a better translation?
+  volumes          = {{volyymit}{vol\adddot}},% Incorrect. Correct translation of "volumes" depends on context.
+% involumes        = {{}{}},% FIXME: missing. Finnish translation of "in 5 volumes" is "5 osassa".
   jourvol          = {{volyymi}{vol\adddot}},
   jourser          = {{sarja}{sarja}},
-% book             = {{}{}},% FIXME: missing
-% part             = {{}{}},% FIXME: missing
-% issue            = {{}{}},% FIXME: missing
+  book             = {{kirja}{kirja}},% FIXME: Literal translation of "book". Correct translation depends on context.
+  part             = {{osa}{osa}},% FIXME: unsure
+  issue            = {{numero}{numero}},% FIXME: unsure
   newseries        = {{uusi sarja}{uusi sarja}},
   oldseries        = {{vanha sarja}{vanha sarja}},
   edition          = {{painos}{painos}},
   reprint          = {{j\"alkipainos}{j\"alkipainos}},
   reprintof        = {{julkaistu aiemmin nimell\"a}{julkaistu aiemmin nimell\"a}},
   reprintas        = {{julkaistu uudelleen nimell\"a}{julkaistu uudelleen nimell\"a}},
-% reprintfrom      = {{}{}},% FIXME: missing
-% translationof    = {{}{}},% FIXME: missing
-% translationas    = {{}{}},% FIXME: missing
-% translationfrom  = {{}{}},% FIXME: missing
-% reviewof         = {{}{}},% FIXME: missing
-% origpubas        = {{}{}},% FIXME: missing
-% origpubin        = {{}{}},% FIXME: missing
-% astitle          = {{}{}},% FIXME: missing
-% bypublisher      = {{}{}},% FIXME: missing
+  reprintfrom      = {{julkaistu aiemmin nimell\"a}{julkaistu aiemmin nimell\"a}},% FIXME: unsure
+  translationof    = {{k\"a\"ann\"os teoksesta}{k\"a\"ann\"os teoksesta}},% FIXME: unsure
+  translationas    = {{k\"a\"annetty nimell\"a}{k\"a\"annetty nimell\"a}},% FIXME: unsure
+  translationfrom  = {{k\"a\"annetty kielest\"a}{k\"a\"annetty kielest\"a}},% Result is very bad Finnish.
+  reviewof         = {{arvostelu teoksesta}{arvostelu teoksesta}},% FIXME: unsure. Bad Finnish.
+  origpubas        = {{julkaistu ensi kerran nimell\"a}{julkaistu ensi kerran nimell\"a}},
+  origpubin        = {{julkaistu ensi kerran vuonna}{julkaistu ensi kerran vuonna}},
+  astitle          = {{nimell\"a}{nimell\"a}},% FIXME: unsure
+  bypublisher      = {{julkaissut}{julkaissut}},% FIXME: unsure
   page             = {{sivu}{s\adddot}},
   pages            = {{sivut}{s\adddot}},
   column           = {{palsta}{palsta}},% Here "sarake" is wrong!
   columns          = {{palstat}{palstat}},% Here "sarakkeet" is wrong!
   line             = {{rivi}{rivi}},
   lines            = {{rivit}{rivit}},
-  nodate           = {{n\adddot d\adddot}{n\adddot d\adddot}},%FIXME
+  nodate           = {{ei julkaisup\"aiv\"a\"a}{ei julkaisup\"aiv\"a\"a}},% FIXME: unsure
   verse            = {{s\"ae}{s\"ae}},
   verses           = {{s\"akeet}{s\"akeet}},
   section          = {{kohta}{kohta}},% Bad translation, but "pyk\"al\"a" is no better.
@@ -379,7 +379,7 @@
   chapter          = {{luku}{luku}},
   mathesis         = {{tutkielma}{tutkielma}},% FIXME: unsure
   phdthesis        = {{tohtorinv\"ait\"oskirja}{tohtorinv\"ait\"oskirja}},
-  candthesis       = {{kandidat}{kandidat}},% FIXME: unsure
+  candthesis       = {{kanditaatintutkielma}{kanditaatintutkielma}},% Literal translation of "Candidate thesis".
   resreport        = {{tutkimusraportti}{tutkimusraportti}},
   techreport       = {{tekninen raportti}{tekninen raportti}},
   software         = {{ohjelmisto}{ohjelmisto}},
@@ -387,15 +387,15 @@
   audiocd          = {{\"a\"ani-CD}{\"a\"ani-CD}},
   version          = {{versio}{versio}},
   url              = {{url}{url}},
-% urlfrom          = {{}{}},% FIXME: missing
+  urlfrom          = {{saatavilla osoitteesta}{saatavilla osoitteesta}},% FIXME: unsure
   urlseen          = {{viitattu}{viitattu}},
-% inpreparation    = {{}{}},% FIXME: missing
-% submitted        = {{}{}},% FIXME: missing
-% forthcoming      = {{}{}},% FIXME: missing
-% inpress          = {{}{}},% FIXME: missing
-% prepublished     = {{}{}},% FIXME: missing
+  inpreparation    = {{valmisteilla}{valmisteilla}},% FIXME: unsure
+  submitted        = {{l\"ahetetty}{l\"ahetetty}},% FIXME: unsure
+  forthcoming      = {{hyv\"aksytty julkaistavaksi}{hyv\"aksytty julkaistavaksi}},% FIXME: unsure
+  inpress          = {{painossa}{painossa}},% FIXME: unsure
+  prepublished     = {{esijulkaistu}{esijulkaistu}},% FIXME: unsure
   citedas          = {{jatkossa}{jatkossa}}, 
-% thiscite         = {{}{}},% FIXME: missing
+  thiscite         = {{t\"am\"a lainaus}{t\"am\"a lainaus}},% FIXME: unsure
   seenote          = {{katso viite}{katso viite}},
   quotedin         = {{lainattu teoksessa}{lainattu teoksessa}},
   idem             = {{idem}{id\adddot}},% It its not necessary to translate Latin phrases.
@@ -443,42 +443,42 @@
   basicdecember    = {{joulukuu}{joulukuu}},
   langamerican     = {{amerikanenglanti}{amerikanenglanti}},
   langbrazilian    = {{brasilianportugali}{brasilianportugali}},
-% langcatalan      = {{}{}},% FIXME: missing
-% langcroatian     = {{}{}},% FIXME: missing
-% langczech        = {{}{}},% FIXME: missing
+  langcatalan      = {{katalonia}{katalonia}},
+  langcroatian     = {{kroataia}{kroatia}},
+  langczech        = {{t\v{s}ekki}{t\v{s}ekki}},
   langdanish       = {{tanska}{tanska}},
   langdutch        = {{hollanti}{hollanti}},
   langenglish      = {{englanti}{englanti}},
-% langfinnish      = {{}{}},% FIXME: missing
+  langfinnish      = {{suomi}{suomi}},
   langfrench       = {{ranska}{ranska}},
   langgerman       = {{saksa}{saksa}},
   langgreek        = {{kreikka}{kreikka}},
   langitalian      = {{italia}{italia}},
   langlatin        = {{latina}{latina}},
   langnorwegian    = {{norja}{norja}},
-% langpolish       = {{}{}},% FIXME: missing
+  langpolish       = {{puola}{puola}},
   langportuguese   = {{portugali}{portugali}},
-% langrussian      = {{}{}},% FIXME: missing
+  langrussian      = {{ven\"aj\"a}{ven\"aj\"a}},
   langspanish      = {{espanja}{espanja}},
   langswedish      = {{ruotsi}{ruotsi}},
   fromamerican     = {{englannin kielest\"a}{englannin kielest\"a}},
   frombrazilian    = {{portugalin kielest\"a}{portugalin kielest\"a}},
-% fromcatalan      = {{}{}},% FIXME: missing
-% fromcroatian     = {{}{}},% FIXME: missing
-% fromczech        = {{}{}},% FIXME: missing
+  fromcatalan      = {{katalonian kielest\"a}{katalonian kielest\"a}},
+  fromcroatian     = {{kroatian kielest\"a}{kroatian kielest\"a}},
+  fromczech        = {{t\v{s}ekin kielest\"a}{t\v{s}ekin kielest\"a}},
   fromdanish       = {{tanskan kielest\"a}{tanskan kielest\"a}},
   fromdutch        = {{hollannin kielest\"a}{hollannin kielest\"a}},
   fromenglish      = {{englannin kielest\"a}{englannin kielest\"a}},
-% fromfinnish      = {{}{}},% FIXME: missing
+  fromfinnish      = {{suomen kielest\"a}{suomen kielest\"a}},
   fromfrench       = {{ranskan kielest\"a}{ranskan kielest\"a}},
   fromgerman       = {{saksan kielest\"a}{saksan kielest\"a}},
   fromgreek        = {{kreikan kielest\"a}{kreikan kielest\"a}},
   fromitalian      = {{italian kielest\"a}{italian kielest\"a}},
   fromlatin        = {{latinan kielest\"a}{latinan kielest\"a}},
   fromnorwegian    = {{norjan kielest\"a}{norjan kielest\"a}},
-% frompolish       = {{}{}},% FIXME: missing
+  frompolish       = {{puolan kielest\"a}{puolan kielest\"a}},
   fromportuguese   = {{portugalin kielest\"a}{portugalin kielest\"a}},
-% fromrussian      = {{}{}},% FIXME: missing
+  fromrussian      = {{ven\"aj\"an kielest\"a}{ven\"aj\"an kielest\"a}},
   fromspanish      = {{espanjan kielest\"a}{espanjan kielest\"a}},
   fromswedish      = {{ruotsin kielest\"a}{ruotsin kielest\"a}},
   countryde        = {{Saksa}{DE}},

**Comment by plk** [comment]
Can you email me the unified diff to philip [at] kime.org.uk or perhaps attach it again without markup? If you paste it without protecting it with a code block it is damaged.

**Comment by plk** [comment]
Sorry, can you send again? My mail system removed the attachment
