### ISSUE TITLE
refcontext documentation is misleading

### ISSUE THREAD

**Issue by u-fischer** [plk/biblatex#331]
In the example for the use of refcontext (3.6.11 Bibliography Contexts) the cite commands are repeated after the `\newrefcontext` command:

~~~~~~
\usepackage[sorting=nyt]{biblatex}
\cite{one}
\cite{two}
\printbibliography
\newrefcontext[sorting=yndt]
\cite{one}
\cite{two}
\printbibliography
~~~~~~

This gives the impression as if the refcontext only affects the "local" keys.  But as can be seen in this answer http://tex.stackexchange.com/a/258980/2388 the keys don't need to be repeated. And this example shows that the `\cite{sigfridsson}` inside a refcontext is actually global and shown in all bibliographies:

~~~~~~
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[sorting=none]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{herrmann}\cite{shore}\cite{aksin}

\printbibliography[title=Unsorted]

\begin{refcontext}[sorting=nty]
\cite{sigfridsson}
\printbibliography[title=Alphabetic]
\end{refcontext}

\begin{refcontext}[sorting=ynt]
\printbibliography[title=By year]
\end{refcontext}
\end{document}

~~~~~~

![refcontext](https://cloud.githubusercontent.com/assets/4047173/9108919/e285ae58-3c31-11e5-8d88-f41f42359dbd.PNG)

**Comment by plk** [comment]
Yes true, but the whole point of this was about citation data such as extrayear which you don't see in numeric styles. The citations themselves may be actually different when sorted differently inside different refcontexts. This is irrelevant in numeric schemes as they don't need visible data like extra*.

**Comment by u-fischer** [comment]
I tried various combinations and I couldn't see a difference in the extrayear when using a second (identical) set of \cite commands in the refsection. Even here the order of the first occurence of the cite commands wins:

~~~~~
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[style=authoryear,sorting=ynt]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\newrefcontext[sorting=none]
\cite{knuth:ct:b,knuth:ct:c}
\printbibliography


\newrefcontext[sorting=none]
\cite{knuth:ct:c,knuth:ct:b}
\printbibliography
\end{document}
~~~~~

I could see a difference when the cite commands are only in the refcontext:

~~~~~
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[style=authoryear,sorting=nyt]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\printbibliography
%\cite{knuth:ct:b,knuth:ct:c}

\newrefcontext[sorting=none]
\cite{knuth:ct:c,knuth:ct:b}
\printbibliography
\end{document}
~~~~~~

**Comment by plk** [comment]
Maybe it could be clearer in the docs. Consider the following and look at the output:

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[style=authoryear,sorting=ynt]{biblatex}
\addbibresource{biblatex-examples.bib}

\DeclareSortingScheme{yntd}{
  \sort{
    \field{presort}
  }
  \sort[final]{
    \field{sortkey}
  }
  \sort{
    \field[strside=left,strwidth=4]{sortyear}
    \field[strside=left,strwidth=4]{year}
    \literal{9999}
  }
  \sort{
    \field{sortname}
    \field{author}
    \field{editor}
    \field{translator}
    \field{sorttitle}
    \field{title}
  }
  \sort[direction=descending]{
    \field{sorttitle}
    \field{title}
  }
}


\begin{document}
\newrefcontext[sorting=ynt]
\cite{knuth:ct:b,knuth:ct:c}
\printbibliography

\newrefcontext[sorting=yntd]
\cite{knuth:ct:b,knuth:ct:c}
\printbibliography
\end{document}
```

**Comment by u-fischer** [comment]
Yes but this not what I mean. Remove in your example the second set of cite commands:

~~~~~
\begin{document}
\newrefcontext[sorting=ynt]
\cite{knuth:ct:b,knuth:ct:c}
\printbibliography

\newrefcontext[sorting=yntd]
%\cite{knuth:ct:b,knuth:ct:c}
\printbibliography
\end{document}
~~~~~

the output is identical (minus the cite commands) to your example. The second set of cites has no impact:

![withoutcite](https://cloud.githubusercontent.com/assets/4047173/9120942/84762c04-3c7f-11e5-9496-083deb59fef8.PNG)
 
![withcite](https://cloud.githubusercontent.com/assets/4047173/9120949/8d67081a-3c7f-11e5-93a7-d3bca0dfdf61.PNG)

**Comment by plk** [comment]
It's not supposed to have an impact on the bibliography. It's just that the citations themselves refer to different entries than the first one. 1986a refers to a different actual reference in each refcontext - that's the point.

**Comment by u-fischer** [comment]
Ok, I think I understand now why you added  this example to the docu. But imho it is confusing: people looking at this section would want first know "how do I get bibliographies with different sorting?" and "which cite commands fill this bibliographies?"

The finer point about  how this change labels and "pseudolabels" like extrayear is only the second step. Also I have doubts that \cite inside a refcontext will be used a lot. If I would use more than one sorting I would try to avoid to get confusing labels.

**Comment by plk** [comment]
I have updated the docs in the DEV branch as you suggest.
