### ISSUE TITLE
Accents handling consistency

### ISSUE THREAD

**Issue by postblue** [plk/biblatex#332]
In my work, I'm citing Marie Depussé's works (with an acute accent) and her name is correctly taken into account if she's declared as `author`. But when I put her name as `editor` or `foreword`, I have the "Argument of \UTFviii@three@octets has an extra }" error as said in #102.

* mce.tex
```tex
\documentclass[a4paper,11pt]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage[francais]{babel}
\usepackage[autostyle,babel=true]{csquotes}
\usepackage[backend=biber]{biblatex}
\bibliography{mce}

\begin{document}
\nocite{*}
\printbibliography
\end{document}
```
* mce.bib
```tex
@book{depusse:morts,
author = {Depussé, Marie},
title = {Les morts ne savent rien},
publisher = {Éditions P.O.L},
year = {2006},
address = {Paris},
pagetotal = {256},
}

@book{guattari:leros,
author = {Guattari, Félix},
title = {De Leros à La Borde},
foreword = {Depusse, Marie}, % should be Depussé, but "Argument of \UTFviii@three@octets has an extra }"
afterword = {Oury, Jean},
publisher = {Nouvelles Éditions Lignes},
year = {2012},
address = {Paris},
pagetotal = {96},
}

@book{oury:train,
author = {Oury, Jean},
title = {À quelle heure passe le train\dots},
subtitle = {Conversations sur la folie},
editor = {Depusse, Marie}, % should be Depussé, but "Argument of \UTFviii@three@octets has an extra }"
editortype = {collaborator},
publisher = {Calman-Levy},
series = {Petite bibliothèque des idées},
address = {Paris},
year = {2003},
pagetotal = {320},
}
```

The acute accent in Depussé's name is correctly handled if she's declared as the `author, but not in the other fields.

* Result:
![](https://i.imgur.com/DItKVns.png)

* Workaround:

Using the `safeinputenc` argument "solves" the issue. With a short bibliography like the one here, it's fine (but weird, as the same name is not handled the same way depending on the field), but on a much larger document with no warning, I get "Command \textquoteright invalid in math mode" (trying to isolate the issue, not done yet).

Nevertheless, I don't understand why Depussé's name doesn't need the `safeinputenc` argument as an `author`, but well as the others.

**Comment by plk** [comment]
If I run your example with PDFlatex, and using é in the name in the foreword of `guattari:leros`, I have no problems at all. It also works with LuaLaTeX for me. I suggest posting to tex.stackexchange.com and asking.

**Comment by postblue** [comment]
I forgot to tell the compilation command was `latexmk -pdf -synctex=1 mce.tex`
