### ISSUE TITLE
Alphabetic Labels: Better Control over Non-Alphanumeric Characters

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#333]
On behalf of [biblatex: label construction with apostrophe](http://tex.stackexchange.com/q/196160/35864) and [Ignore Spaces in Author Name](http://tex.stackexchange.com/q/224243/35864) over at TeX.SX I was wondering whether a more fine-grained control over non-alpha(numeric) characters in the alphabetic labels is possible.

An option to ignore certain characters (spaces in the example above) when creating labels or force certain characters (apostrophe or hyphen) - maybe even with an option to exempt those characters from the character count - seems to be beneficial. Maybe this could be implemented analogue to BIber's nosort and noinit features.

The MWE below shows the issues discussed in the linked questions
```
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[ngerman]{babel}
\usepackage{csquotes}
\usepackage{filecontents}
\usepackage[style=alphabetic, backend=biber]{biblatex}

\begin{filecontents*}{\jobname.bib}
@Article{DeLorca2015,
  Title   = {Article title},
  Author  = {De Lorca, Antonio},
  Journal = {Journal title},
  Year    = {2015}
}
@article{otoole_optical_2010,
  title =    {Optical computing for fast light transport analysis},
  pages =    {1-12},
  journaltitle = {ACM Transactions on Graphics (TOG)},
  series =   {SIGGRAPH ASIA '10},
  library =  {Seoul, South Korea},
  author =   {{O'Toole}, Matthew and Kutulakos, Kiriakos N},
  date =     2010,
  note =     {ACM ID: 1866165}
}
@article{OToole_2015,
 author = {O'Toole, Matthew},
 title = {Homogeneous Codes for Energy-efficient Illumination and Imaging},
 journal = {ACM Trans. Graph.},
 volume = {34},
 number = {4},
 date = {2015},
 issn = {0730-0301},
 pages = {35:1--35:13},
 doi = {10.1145/2766897},
} 
@article{lorem,
 author = {Ipsum Alpha-Beta},
 title = {Dolor Sit},
 journal = {Amet Journal},
 volume = {34},
 number = {4},
 date = {2015},
} 
\end{filecontents*}

\DeclareLabelalphaTemplate{
  \labelelement{
    \field[final]{shorthand}
    \field[compound=true]{labelname}
    \field{label}
  }
  \labelelement{
    \literal{\addnbthinspace}
  }
  \labelelement{
    \field[strwidth=2,strside=right]{year}
    %\field{year}
  }
}

\addbibresource{biblatex-examples.bib}
\addbibresource{\jobname.bib}

\begin{document}
   \cite{geer,vangennep,vazques-de-parga,brandt,DeLorca2015,otoole_optical_2010,OToole_2015,lorem}

  \printbibliography
\end{document}
```
It would be nice to have the option to see "O'Toole" and "Alpha-Beta" as well as "DeLorca".

**Comment by plk** [comment]
Good idea. Please try biblatex 3.1 and biber 2.2 dev versions. There is a new `\DeclareNolabel` macro which does just what you suggest. The default is the old hard-coded behaviour. It is documented in both the biblatex and biber PDF manuals (it can also be set in the biber .conf file like the other options).

**Comment by moewew** [comment]
Thank you very much, that was really quick!

I don't know if I did everything as intended, but

```
\listfiles
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[ngerman]{babel}
\usepackage{csquotes}
\usepackage{filecontents}
\usepackage[style=alphabetic, backend=biber]{biblatex}

\begin{filecontents*}{\jobname.bib}
@article{otoole_optical_2010,
  title =    {Optical computing for fast light transport analysis},
  pages =    {1-12},
  journaltitle = {ACM Transactions on Graphics (TOG)},
  series =   {SIGGRAPH ASIA '10},
  library =  {Seoul, South Korea},
  author =   {O'Toole, Matthew and Kutulakos, Kiriakos N},
  date =     2010,
  note =     {ACM ID: 1866165}
}
\end{filecontents*}

\DeclareLabelalphaTemplate{
  \labelelement{
    \field[final]{shorthand}
    \field[compound=true]{labelname}
    \field{label}
  }
  \labelelement{
    \field[strwidth=2,strside=right]{year}
  }
}

\addbibresource{\jobname.bib}

\DeclareNolabel{
  \nolabel{\regexp{}}
}

\begin{document}
  \nocite{*}
  \printbibliography
\end{document}
```

still gives me "OTooleKutulakos10" without the `'`.

I got Biber 2.2 from sourceforge and just used the newest version of `biblatex2.sty` from github here.

BTW: Maybe that was my error, but I changed the

    \DeclareNoinit{
      ...
    }

from the documentation to `\DeclareNolabel` as I assumed it was a copy-and-past remnant.

**Comment by moewew** [comment]
Aha! Now the directive appears in the `.bcf`. Obviously in the case above we get `<bcf:nolabel value=""/>`. Then Biber complains about  `Not an ARRAY reference at ... Biber.pm line 531` and aborts compilation.

**Comment by moewew** [comment]
Yes, it seems to work now, thank you very much. I will do some more tests and report back.

**Comment by plk** [comment]
Yes, this should be fixed now - you need to pull biblatex 3.1 and biber 2.2 again.

**Comment by moewew** [comment]
I guess I could see into the future there. Everything works as advertised now.

Just a nice-to-have: Would it be possible to exempt certain characters (regexs) from the `stwridth` count, such that a `\field[strwidth=3,strside=left]{labelname}` on "O'Toole" gives "O'To" instead of "O'T"?

**Comment by plk** [comment]
Do you think this could be the same as the `\DeclareNolabel` regexps or would it need to be different? I would have thought for consistency it might need to the same.

**Comment by moewew** [comment]
Mhhh, I would think for maximal flexibility it might be nice to have those two independent of each other. Maybe set the exceptions automatically to the same values as `\DeclareNolabel` but allow the user to override it if they wish to do so. One could then do really involved and weird things.

But I guess it depends on how easy it is to implement this.

**Comment by moewew** [comment]
Having thought about it for some time, I realise that of course these two options have to be independent to make sense. The characters ignored via `\DeclareNolabel` certainly cannot count against one's character limit, because they aren't there. And so this new option would just introduce other characters that are not dropped in the output but ignored for length calculation purposes.

**Comment by plk** [comment]
It's a bit tricky because of the auto-disambiguation settings. Dealing with optional characters in there is not easy.

**Comment by moewew** [comment]
Hmmm, yes, I suppose one would have to have one internal label with all the optional characters deleted and one for display, though then one might have problems with disambiguations, I agree. Though you could just warn users that this might happen when using this option.

**Comment by plk** [comment]
Actually, it could be done by recording the index of all such chars in the string, removing them and then adding back at the same index after disambiguation/truncation. Not trivial though.

**Comment by moewew** [comment]
That seems like a good way to go. Locating the characters in the original string and recording their positions should not be that hard, I would have thought (some regex search?). But for adding them back in one would somehow have to keep track how the label is created (at least for the variable width disambiguation); for fixed with, I guess checking whether the first occurrence of an ignored character is less than the obtained label width and if not, adding the first ignored back into its original position, and repeating this should do it.

**Comment by plk** [comment]
Please try biblatex 3.1 and biber 2.2 again. There is a new macro `\DeclareNolabelwidthcount` which declares regexps to ignore when calculating (fixed-width only) label part substrings.

**Comment by moewew** [comment]
Works like a charm! Thank you very much.

**Comment by moewew** [comment]
Sorry to bother you again. I have found one tiny problem with `\DeclareNolabelwidthcount`. If more than one ignored character appears in a label the characters are not added back correctly.

In the MWE below, where we ignore "o" and "r", the two letters are put back as "Wroma", correct would be "Worma"

```
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[ngerman]{babel}
\usepackage{csquotes}
\usepackage[style=alphabetic, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}

\DeclareNolabel{\nolabel{\regexp{\s}}}

\DeclareNolabelwidthcount{\nolabel{\regexp{[or]}}}

\begin{document}
  \cite{worman}

  \printbibliography
\end{document}
```

**Comment by plk** [comment]
Did you mean "[or]" or just "or" - the former replaces any occurence of "o" OR "r" not "AND" ...

**Comment by plk** [comment]
Ah no, it is a bug in fact anyway, rather subtle. They should have the same results.

**Comment by plk** [comment]
Please pull biber 2.2 again - I think this should be fixed.

**Comment by moewew** [comment]
Sorry for the confusion. The MWE as well as some other test cases I had running work flawlessly now.
