### ISSUE TITLE
Enable Use of \literal in all \DeclareLabel...

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#334]
With `\DeclareLabeldate` we can already use the `\literal` command to insert an arbitrary fall-back string when all other fields are empty and push comes to shove.

Would it be possible to include this option also for the `\DeclareLabelname` and `\DeclareLabeltitle` directives?

From what I have been able to understand, the change required to `biblatex2.sty` would probably encompass adding `\let\literal\blx@ordered@literal` and copying the code of `\blx@orderedld@field` and `\blx@orderedld@literal` (I even think this would allow to merge the commands `\blx@ordered@field` and `\blx@orderedld@field` as well as `\blx@orderedld@literal` and `\blx@ordered@literal` again, though I might be wrong here).
The changes to Biber, though, I can not so easily survey, I hope it would be enough to adapt `sub process_labelname` and `sub process_labeltitle` in `lib/Biber.pm` with the checks already present in `sub process_labeldate`.

A MWE might not be strictly necessary, but here you go

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[ngerman]{babel}
\usepackage[babel,german=quotes]{csquotes}
\usepackage{filecontents}
\begin{filecontents*}{\jobname.bib}
@BOOK{unbekannt,
  title = {Beispielbuch},
  year = {2000},
  address = {Berlin},
}
@ARTICLE{auchunbekannt,
  title = {Beispielaufsatz},
  journal = {Zeitschrift},
  year = {2001},
  volume = {7},
}
\end{filecontents*}
\usepackage[style=authoryear]{biblatex}

\addbibresource{\jobname.bib}

\DeclareLabelname{%
  \field{shortauthor}
  \field{author}
  \field{shorteditor}
  \field{editor}
  \field{translator}
  \literal{noauthor}
}

\begin{document}
Ein unbekannter Autor\footcite{unbekannt}, ein anderer unbekannter Autor.\footcite{auchunbekannt}
\printbibliography
\end{document}
```

Of course, the `\literal{noauthor}` there does not work.

**Comment by plk** [comment]
This is actually quite difficult because labelname is chosen by pointing to another name field and this is done before the fields are passed to any further macros, all of which expect a special format for a name field. The only real way to do this would be to conditionalise all name formatting on whether the name field is a special literal or not and this would be very messy. It's best done in styles where labelname is found to be empty I think.

**Comment by moewew** [comment]
Ahhh, too bad.
The `biblatex`-side of the implementation looked easy enough. But I got carried away with the idea and did not notice that problem....
