### ISSUE TITLE
Unexpected behaviour in \filteror

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#337]
[biblatex and \filteror to produce a combined list of abbreviations](http://tex.stackexchange.com/q/267425/35864) seems to have encountered a problem with `\filteror`.

In the following slightly more minimal example, the entry `sigfridsson` has a `doi` field, `baez/online` an `eprint` field and `worman` has neither of those fields.

```
\documentclass{article}
\usepackage[style=authoryear,backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}

\DeclareBiblistFilter{mylist}{
  \filteror{%
    \filter[type=field,filter=doi]
    \filter[type=field,filter=eprint]
  }
}

\begin{document}
\autocite{worman}
\autocite{sigfridsson}
\autocite{baez/online}
\printbiblist[env=bibliography]{mylist}
\end{document}
```
The MWE gives all three sources when printing the biblist, where I would expect `worman` to be omitted.

If one does not wrap the `\filter`s in a `\filteror` wrapper, the single filter works fine.

If apply both filters without `\filteror` I would have expected the filtering to be conjoined by an "and", but seemingly only the last filter takes effect.

Finally, the documentation confused my quite a bit when it gave the syntax as `\filter{type}{filter}` when `\filter[type=field,filter=doi]` seems to work as advertised and `\filter{field}{doi}` failed miserably.

**Comment by plk** [comment]
This filtering is done by biber and there were some bugs. Please try biber DEV 2.2 version from Sourceforge.

**Comment by moewew** [comment]
Thank you very much. All the filtering I could think of works exactly as advertised now.
