### ISSUE TITLE
Offer to create BibTeX-compatible bbl files

### ISSUE THREAD

**Issue by akerbos** [plk/biblatex#338]
One of the big reasons (maybe the biggest, or even the only one) that prevents people from moving to Biblatex is that many (academic) publishers refuse to support it; they want their "pastable" `.bbl`, period.

If at all possible, it would be great if Biblatex could (as an option) create such a file. I'm not sure what this entails, and what exactly that file would have to conform to. (Is any LaTeX code that generates the bibliography enough, or does it have to use the same commands as `bibtex`-generated files?) But it would definitely make the lives of authors who *want* to use Biblatex easier.

**Comment by plk** [comment]
This is completely impossible I'm afraid as the .bbl in biblatex plays a completely different role, a little like a sort of database rather than a typesetting document. There are answers to this sort of of issue on tex.stackexchange.com if you have a look.

**Comment by akerbos** [comment]
Well, it does not have to use the same name: it could be called `<document>_bibtex_compatible.bbl` or whatever. I am more than happy to rename it before uploading somewhere.

I am aware of some of the material on tex.SE. AFAIK, though, there is no way for getting a BibTeX-compatible bbl when using biblatex/biber.

**Comment by plk** [comment]
It's not a naming issue, it would be an entirely different output module for biber. Just about all of the important information about uniqueness, hashes etc. would be lost and there would be no way to manage such biblatex options. The bibliography and citations would likely be all broken.

**Comment by akerbos** [comment]
I don't see how *also* outputting such a file would break anything. I did not say that the bbl should be *used*, only produced! But well, I have no idea how biblatex and biber work so I'll shut up now.

**Comment by plk** [comment]
It could theoretically be done but what was output would be, in the context of a biblatex document, completely broken and useless I'm afraid.

**Comment by dbitouze** [comment]
@plk The point is almost no journal do accept `biblatex` and almost all journals that accept LaTeX do accept `.bbl` files. Hence it could be very helpful to use all `biblatex` features during the creation process and, just before sending the article to the journal, to be able to create a `.bbl` file corresponding to the `biblatex`'s output.

**Comment by aboruvka** [comment]
@dbitouze Why would you need biblatex/biber to implement a journal style? If they accept LaTeX documents, then either they provide the style file or the bst file easy enough to create without the need for any biblatex or biber features.

**Comment by akerbos** [comment]
@aboruvka Some want the bbl for their own purposes, independent of how the document gets built.

**Comment by dbitouze** [comment]
@aboruvka There are some features very useful: ibid trackers, `\citeauthor`, `\citetitle`, etc.

**Comment by aboruvka** [comment]
@dbitouze Useful, yes. Needed to implement journal styles (that tend to be very simple)? I would guess no.

@akerbos Under biblatex the bbl contains only bibliographic data; all bibliography/citation style formatting is specified and applied via the biblatex package. Asking for a bbl file that goes back to the bst way of doing things (that is, combining the data and format in bbl) is not only at odds with the way biblatex works, it is just not possible with a variety of features that biblatex makes possible.

There are at least two threads on this topic at Stack Exchange - one fairly recent. If you feel the need to discuss this topic further, please head over there.
