### ISSUE TITLE
Distinguish dropping and non-dropping prefixes (aka particles)

### ISSUE THREAD

**Issue by nickbart1980** [plk/biblatex#339]
Currently, `useprefix` can only be set per entry, not per individual author/editor etc.

This causes errors when different types of prefixes (aka “von”-parts, aka particles) are involved.

Example:

```latex
\documentclass{article}

\begin{filecontents}{test.bib}
@book{useprefix-true,
  author = {van Gogh, Vincent and von Humboldt, Sr., Alexander},
  options = {useprefix=true},
  title = {Title},
  date = {2015},
}

@book{useprefix-false,
  author = {van Gogh, Vincent and von Humboldt, Sr., Alexander},
  title = {Title},
  date = {2015},
}
\end{filecontents}

\usepackage[backend=biber, style=authoryear]{biblatex}
\addbibresource{test.bib}

\begin{document}
\renewbibmacro*{begentry}{\midsentence}

\cite{useprefix-true, useprefix-false}

\printbibliography

\end{document}
```

Actual output; both in-text citations are wrong:

> van Gogh and von Humboldt 2015; Gogh and Humboldt 2015
**References**
Gogh, Vincent van and Alexander von Humboldt Sr. (2015). Title.
van Gogh, Vincent and Alexander von Humboldt Sr. (2015). Title.

Correct output:

> van Gogh and Humboldt 2015
**References**
Gogh, Vincent van and Alexander von Humboldt Sr. (2015). Title.

Are there any plans to introduce the option of setting the `useprefix` flag per author rather than per entry, or, in other words, distinguishing between “dropping” and “non-dropping” particles like CSL does (see [CSL specs](http://docs.citationstyles.org/en/stable/specification.html#name))?

One way of achieving this without changing the existing conventions of biblatex too much could be to parse leading lowercase elements of the family name as non-dropping particles, and trailing lowercase elements of the given name as dropping particles. Example:

`author = {van Gogh, III, Vincent}` – `van` is non-dropping
`author = {’s-Gravesande, Goverdus}` – `’s-` is non-dropping
`author = {al-Hakim, Tawfiq}` – `al-` is non-dropping

`author = {Humboldt, Sr., Alexander von}` – `von` is dropping
`author = {Beethoven, Ludwig van}` – `van` is dropping
`author = {Medici, Lorenzo de’}` – `de’` is dropping

**Comment by plk** [comment]
This would require really tricky changes in the low-level C btparse library which biber users and is very unlikely. It's more likely that it will be supported in the biblatex XML format.
