### ISSUE TITLE
Parse apostrophes and hyphens in “von” parts like lowercase letters

### ISSUE THREAD

**Issue by nickbart1980** [plk/biblatex#340]
Apostrophes and hyphens in “von” parts are not parsed like lowercase letters and spaces, but they should.

Example:

~~~latex
\documentclass{article}

\begin{filecontents}{test.bib}
@book{plain,
  author = {in 't Gogh, Vincent},
  title = {Title (plain)},
  date = {2015},
}
@book{brace,
  author = {{in 't} Gogh, Vincent},
  title = {Title (brace)},
  date = {2015},
}
@book{nbsp,
  author = {in~'t Gogh, Vincent},
  title = {Title (nbsp)},
  date = {2015},
}
@book{van,
  author = {van Gogh, Vincent},
  title = {Title (van)},
  date = {2015},
}
@book{alhakim,
  author = {al-\relax Hakim, Tawfik},
  title = {Title (d'hakim)},
  date = {2015},
  options = {useprefix=true},
}
@book{dhakim,
  author = {d'\relax Hakim, Tawfik},
  title = {Title (d'hakim)},
  date = {2015},
  options = {useprefix=true},
}
\end{filecontents}

\usepackage[backend=biber, style=authoryear]{biblatex}
\addbibresource{test.bib}

\begin{document}
\renewbibmacro*{begentry}{\midsentence}

\cite{brace, nbsp, plain, van, alhakim, dhakim}

\printbibliography

\end{document}
~~~

Output:

> in ’t Gogh 2015; Vincent in ’t Gogh 2015; ’t Gogh 2015; Vincent van Gogh 2015; al- Hakim 2015; d’Hakim 2015
**References**
al- Hakim, Tawfik (2015). Title (d’hakim). 
d’Hakim, Tawfik (2015). Title (d’hakim). 
Gogh, Vincent in ’t (2015). Title (nbsp). 
Gogh, Vincent van (2015). Title (van).
in ’t Gogh, Vincent (2015). Title (brace). 
’t Gogh, Vincent in (2015). Title (plain).

So only in the entry with `in~'t` the prefix really gets parsed as a prefix, but at least the “plain” version should be, too.

Also `d'\relax ` succeeds in removing the following space, whereas `al-\relax ` doesn’t: Why?

My suggestion is to treat all apostrophes and hyphens (no other chars ever seem to go with prefixes) like additional lowercase letters, so typically no special markup is required.

I’d also suggest that parsing should not require a space between prefix and lastname; prefixes ending with apostrophes and hyphens should be allowed, too. (As in `author = {d'Hakim, Tawfik}` and `author = {al-Hakim, Tawfik}`)

**Comment by plk** [comment]
This is an issue with low-level bibtex parsing of names. It is very tricky to hack this into the current btparse library and hardly worth it as one can use the biblatexml XML format which gets round the issue of trying to parse names into parts like this. The bibtex way of splitting names really is a rather legacy and old-fashioned way of parsing names.
