### ISSUE TITLE
\printbibliography seems to undefine a lot of important things

### ISSUE THREAD

**Issue by logological** [plk/biblatex#343]
I have a document which needs to print two bibliographies in different styles.  However, after calling `\printbibliography` the first time, a lot of things break.  For example, neither the `refcontext` environment nor the `sorting` option exist any more.  Here are a couple minimal examples:
```latex
\documentclass{article}
\usepackage[backend=bibtex8]{biblatex}
\begin{document}
\printbibliography[heading=none]
\printbibliography[sorting=nyt]
\end{document}
```
Compiling the above with `pdflatex` produces the following error message:
```
! Package keyval Error: sorting undefined.
```

```latex
\documentclass{article}
\usepackage[backend=bibtex8]{biblatex}
\begin{document}
\printbibliography[heading=none]
\begin{refcontext}
\printbibliography
\end{refcontext}
\end{document}
```
Compiling the above with `pdflatex` produces the following error message:
```
! LaTeX Error: Environment refcontext undefined.
```

I'm using biblatex 3.0 with TeX Live 2015.

**Comment by plk** [comment]
None of those advanced features work without using biber as the backend - you are using bibtex8 which forces a completely different code path in biblatex.

**Comment by logological** [comment]
Which "advanced features" in particular are you referring to?  In the biblatex manual there is nothing in the description of the `\printbibliography` command which says it can't be used with bibtex8; ditto for `refcontext`, `heading`, and `sorting`.  Usually the Biber-only features are clearly marked as such with margin notes.

Perhaps the bug here is missing or incorrect documentation…?

**Comment by plk** [comment]
Yes, refcontext should be marked biber only. The `sorting` option for `\printbibliography` was always biber only and it's now been replaced by the sorting option of recontext anyway. I will correct this in the docs.
