### ISSUE TITLE
Named refsegments

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#344]
I have done some weird things with `refsegement`s recently and found that it would be really nice to know the (immutable) "name" of a `refsegment` in some cases.

Would it be possible to allow for `refsegment`s that can be assigned a fixed "name" so it is easier to refer to them later? Currently, I seem only be able to refer to the current segment and have to rely on counting to get the name of the other segments.

**Comment by plk** [comment]
I'm afraid that it's very hard to do this as the refsegments are all numbers internally and there are a lot of checks based on numbers to check about nesting etc.

**Comment by moewew** [comment]
Mhhh, too bad. Would it then be possible to change the `refsegment` number manually? So the user can be sure of the number.

**Comment by plk** [comment]
Would it be enough to have a user command to view the current segment label? It's usuall composed internally of the section+segment numbers I think.

**Comment by moewew** [comment]
Isn't that what `\therefsegment` does right now?

In the case I have in mind I would like to exclude the references cited in a particular section of the document from appearing in a `\printbibliography`. This can be done by filtering on `not segment=n`, but for that to work I need to know the segment number of the section I want ignored. In order to make this robust to changes in the document later on and not having to resort to having to count being able to set the name myself would be easier. But maybe there is an even better solution to what I'm trying to do.

**Comment by plk** [comment]
Perhaps ask on TSE? I suspect there is an easier solution ...

**Comment by moewew** [comment]
There is already a question on TeX.SX [Multiple reference lists using biblatex: how to remove duplicated entries?](http://tex.stackexchange.com/q/245971/35864) that asks exactly that. Sadly I'm the only one to have tried answering it. I was a bit dissatisfied with the filter I created because it relies on knowing the number of the segment to ignore `1`, so the solution feels a bit ad hoc.

**Comment by plk** [comment]
Maybe I misunderstand - bibfilters don't need to be in the preamble so you could do this which means you don't explicitly mention any segment numbers:

```
\documentclass{article}
\usepackage[backend=biber,defernumbers=true]{biblatex}
\addbibresource{biblatex-examples.bib}


\begin{document}
\begin{refsegment}
\defbibfilter{notother}{not segment=\therefsegment}
\section{Previous Track Record}
I am an acknowledged authority on aardvarks \cite{sigfridsson}.
\printbibliography[prefixnumbers=A,heading=subbibliography,segment=\therefsegment]
\end{refsegment}

\begin{refsegment}
\section{Research}
I will use the methods developed in \cite{sigfridsson} to address
the questions raised in \cite{geer}.
\printbibliography[heading=subbibliography,segment=\therefsegment,filter=notother]
\end{refsegment}    
\end{document}
```

**Comment by moewew** [comment]
Now that is clever, I didn't know that worked. Thank you very much.

I assume that (almost) all disadvantages of the numbering system can be used like that, so feel free to close this issue.

**Comment by u-fischer** [comment]
Regarding the original question. It is rather easy to label refsection (or in a similar way refsegment) with something like this:


~~~~~~
\begin{refsection}
\makeatletter
 \def\@currentlabel{\therefsection}\label{myrefsec}
\makeatother
...
\end{refsection}
...
\printbibliography[section=\getrefnumber{myrefsec}]
~~~~~~

**Comment by moewew** [comment]
@u-fischer  That is very clever as well, thank you very much.
