### ISSUE TITLE
Why remove sorting from \printbibliography?

### ISSUE THREAD

**Issue by Gwend4l** [plk/biblatex#345]
I was just wondering: why did the `sorting` option get removed from `\printbibliography`? I had found it quite useful to be able to split a bibliography and to have different sorting types.

`\newrefcontext` is a really cool feature, but it is not made to split a bibliography in different parts, hence it naturally creates problems when using it only to have different sorting orders (eg. inconsistent citation numbers).

Anyway, I was mostly being curious, since I can live without it, but I lost a feature that I liked :). Thanks for the work on biblatex.

**Comment by plk** [comment]
Can you give an example of what can't be done now? There should be no loss of functionality, just a syntax change ...

**Comment by Gwend4l** [comment]
Here is an example (xelatex+biber):
~~~~~~~~~~~~latex
\documentclass{article}

\usepackage{biblatex}

\begin{filecontents}{test.bib}
@MISC{ICCPR,
  title = {International Covenant on Civil and Political Rights},
  keywords = {treaty},
  howpublished = {adopted and opened for signature, ratification and accession 16 Dec. 1966, entered into force 23 Mar. 1976},
  note = {999 UNTS 171},
  addendum = {UN. Doc. A/RES/2200(XXI)},
  shortauthor = {ICCPR},
  year = {1976}
}

@MISC{BanjulCharter,
  title = {African (Banjul) Charter on Human and Peoples' Rights},
  keywords = {treaty},
  howpublished = {adopted and opened for signature, ratification and accession 27 June 1981, entered into force 21 Oct. 1986},
  note = {1520 UNTS 217},
  addendum = {OAU Doc. CAB/LEG/67/3 rev. 5},
  shortauthor = {Banjul Charter},
  year = {1986}
}

@MISC{RomeStatute,
  title = {Rome Statute of the International Criminal Court},
  keywords = {treaty},
  howpublished = {adopted and opened for signature, ratification and accession 17 July 1998, entered into force 1 July 2002},
  note = {2187 UNTS 3},
  addendum = {U.N. Doc. A/CONF.183/9},
  shortauthor = {Rome Statute},
  year = {2002}
}

@MISC{AmericanConvention,
  title = {American Convention on Human Rights},
  keywords = {treaty},
  howpublished = {adopted and opened for signature, ratification and accession 22 Nov. 1969, entered into force 18 July 1978},
  note = {1144 UNTS 123},
  shortauthor = {American Convention},
  year = {1978}
}
\end{filecontents} 

\DeclareBibliographyCategory{mycategory} 
\addtocategory{mycategory}{BanjulCharter}
\addtocategory{mycategory}{RomeStatute}

\addbibresource{test.bib}

\begin{document}

Citing ``International Covenant on Civil and Political Rights'' \cite{ICCPR}

Citing ``African (Banjul) Charter on Human and Peoples' Rights'' \cite{BanjulCharter}

Citing ``Rome Statute of the International Criminal Court'' \cite{RomeStatute}

Citing ``American Convention on Human Rights'' \cite{AmericanConvention}


\newrefcontext[sorting=ydnt]
\printbibliography[category=mycategory,title=My Category -- i want ydnt order]
\newrefcontext[sorting=nty]
\printbibliography[notcategory=mycategory,title=Not category -- i want nty order]

\end{document}
~~~~~~~~~~~~

Result:
![biblatex-example](https://cloud.githubusercontent.com/assets/1388961/10709936/547a02b4-7a41-11e5-82d6-3c5872a4d7ad.png)

I want to have two different sortings for the two parts of my bibliography, with all citations already made. What happens is that the reference counter gets confused because of the different ref contexts.

Hence I have twice the reference [2] in the list, and the citations made in the text are not correct either.

If I remember correctly, changing the sorting in `\printbibliography` did not change the whole ref context, and hence didn't cause these problems. I think?

**Comment by plk** [comment]
There are teo things here, firstly, you probably want to use the defernums option to biblatex and you also might want to put the relevant cite commands inside the refcontexts too.

**Comment by Gwend4l** [comment]
I've looked into defernums, and while it is better, it isn't what I'm looking for. And likewise, the problem is that I don't want to split my cite commands.

In a nutshell, I would like to have a complete document with lots of citations (that are put in two different biblatex categories), and at the end of the report I want to display each category with a different sort mode.

Maybe I'm doing something wrong?

**Comment by plk** [comment]
It would be best to post this to tex.stackexchange.com as is looks like a normal use case which should work but.

**Comment by thorade** [comment]
Sorry to comment on a closed issue: 
What would be the syntax now, is there an example?
Could not find one on SE or here:
https://ctan.org/tex-archive/macros/latex/contrib/biblatex/doc/examples

**Comment by plk** [comment]
See `\begin{refcontext}`/`\newrefcontext`

**Comment by moewew** [comment]
@thorade See for example the last code block above (https://github.com/plk/biblatex/issues/345#issuecomment-150804141). There are also quite some questions on TeX.SX (https://tex.stackexchange.com/q/361031/35864 to show only one with a bit of explanation). Please note that it can be risky to mix different sorting schemes (as explained in the linked question).
