### ISSUE TITLE
How to remove space between von and Last?

### ISSUE THREAD

**Issue by nickbart1980** [plk/biblatex#346]
How to remove space between von and Last?

`author = "d’\relax Ormesson, Jean"`, as recommended by TTB, does not seem to work for biblatex.

**Comment by dbitouze** [comment]
I don't see your point. In the following MWE, everything lokks okay:

```latex
\documentclass[french]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[autostyle]{csquotes}%
\usepackage[backend=biber,style=authoryear]{biblatex}%
\usepackage{filecontents}
\usepackage{babel}
%
\begin{filecontents}{\jobname.bib}
@Book{            foo,
  author       = {d'Ormesson, Jean},
  year         = {2015},
  title        = {The Title}
}
\end{filecontents}
%
\addbibresource{\jobname.bib}
\nocite{*}
\begin{document}
\printbibliography
\end{document}
```

**Comment by nickbart1980** [comment]
But with `author = {d'Ormesson, Jean}`, “d’” is not parsed as a “von” part. See example:

```
\documentclass[french]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[autostyle]{csquotes}%
\usepackage[backend=biber, style=authoryear]{biblatex}%
\usepackage{filecontents}
\usepackage{babel}
%
\begin{filecontents}{\jobname.bib}
@Book{            foo,
  author       = {d'Ormesson, Jean},
  year         = {2015},
  title        = {The Title}
}
@Book{            bar,
  author       = {de Ormesson, Jean},
  year         = {2015},
  title        = {The Title 2}
}
\end{filecontents}
%
\addbibresource{\jobname.bib}
\nocite{*}
\begin{document}
\printbibliography
\end{document}
```

Actual output:

> d’Ormesson, Jean (2015). *The Title.* 
Ormesson, Jean de (2015). *The Title 2.*

Expected output:

> Ormesson, Jean d’ (2015). *The Title.* 
Ormesson, Jean de (2015). *The Title 2.*

**Comment by nickbart1980** [comment]
I should add this is an issue since the Chicago Manual, e.g., calls for “d’Ormesson” in-text but “Ormesson, Jean d’” in the references list (assuming it’s a Dutch name here), and “al-Hakim” in-text but “Hakim, Tawfik al-” in the references list, so the “von” part *has* to be parsed, *and* (unless parsing is improved) the space needed in the database to ensure proper parsing has to be dealt with.

See also https://github.com/plk/biblatex/issues/340.

**Comment by plk** [comment]
Did you see the `\bibnamedelim` macros in the biblatex manual? Such spacing should be controlled in the style, not in the data.

**Comment by nickbart1980** [comment]
I’m aware of the `\bibnamedelim` macros – but then (a) the data would always have to contain a space between von and Last (e.g., `author = {d' Ormesson, Jean}`), and (b) `\bibnamedelimc` and `\bibnamedelimd` would have to be redefined *not* to insert whitespace if the preceding “von” part ends with `’`, `'`, or `-` – is that possible?

**Comment by plk** [comment]
This would involve changing really low-level bibtex name parsing rules. It's easier to just deal with it with a sourcemap. Try adding this to your preamble:

```
\DeclareSourcemap{
  \maps[datatype=bibtex]{
    \map{
       \step[fieldsource=author,
             match=\regexp{(\P{P})(\p{P})(\P{P})},
             replace=\regexp{$1$2\x20$3}]
    }
  }
}
```

**Comment by nickbart1980** [comment]
Ok, thank you: This would take care of *adding* a space between `von` and `Last` to the data. 

But the crucial bit would be to redefine `\bibnamedelimc` and `\bibnamedelimd` *not* to insert whitespace if the preceding “von” part ends with `’`, `'`, or `-` – is that possible?

**Comment by plk** [comment]
That's perhaps a good question for TSE - I'm not sure if that's possible without checking the code.

**Comment by nickbart1980** [comment]
Further testing shows that biblatex does *not* add a space after a dumb apostrophe (which I had not tried in my initial tests), but *does* after a smart apostrophe or a hyphen – so the question turns into: How can biblatex be fixed to treat smart apostrophes and hyphens like dumb apostrophes here?

MWE:

```
\documentclass{article}

\begin{filecontents}{\jobname.bib}
@book{orm-d,
  author = {d' Ormesson-Dumb, Jean},
  title = {Title: dumb apostrophe},
  date = {2015},
}
@book{orm-s,
  author = {d’ Ormesson-Smart, Jean},
  title = {Title: smart apostrophe},
  date = {2015},
}
@book{hak,
  author = {al- Hakim, Tawfik},
  title = {Title},
  date = {2015},
}
\end{filecontents}

\usepackage[backend=biber, style=authoryear]{biblatex}
\addbibresource{\jobname.bib}

\usepackage{fontspec}
\setmainfont{Times}

\makeatletter
\AtBeginDocument{\toggletrue{blx@useprefix}}
\AtBeginBibliography{\togglefalse{blx@useprefix}}
\makeatother

\begin{document}
\section*{Text}
\cite{hak, orm-d, orm-s}
\printbibliography
\end{document}
```

Output:

> **Text**
al- Hakim 2015; d’Ormesson-Dumb 2015; d’ Ormesson-Smart 2015
**References**
Hakim, Tawfik al- (2015). *Title.*
Ormesson-Dumb, Jean d’ (2015). *Title: dumb apostrophe.*
Ormesson-Smart, Jean d’ (2015). *Title: smart apostrophe.*

Expected:

> **Text**
al-Hakim 2015; d’Ormesson-Dumb 2015; d’Ormesson-Smart 2015
**References**
Hakim, Tawfik al- (2015). *Title.*
Ormesson-Dumb, Jean d’ (2015). *Title: dumb apostrophe.*
Ormesson-Smart, Jean d’ (2015). *Title: smart apostrophe.*

Note: Using xelatex/fontspec/Times since when processing my earlier MWE with pdflatex, the default font does not display the smart apostrophe at all. (Mac OS X 10.10.5, TeX Live 2015.)

**Comment by plk** [comment]
Interesting - I think that's a TSE question for certain.

**Comment by nickbart1980** [comment]
OK: https://tex.stackexchange.com/questions/275698/biblatex-how-to-remove-space-between-von-and-last

**Comment by nickbart1980** [comment]
There’s an answer at https://tex.stackexchange.com/questions/275698/biblatex-how-to-remove-space-between-von-and-last which looks very good. 

Could this be used to fix the biblatex package?

**Comment by plk** [comment]
Not really - it's the low-level C routines that would need to be changed to do anything serious in such cases and that's quite tricky as it changes standard bibtex semantics.

**Comment by nickbart1980** [comment]
I’m not talking about parsing and low-level C routines here – the TSE answer is about suppressing the addition of spaces after smart apostrophes and hyphens, the same thing biblatex does already for dumb apostrophes.

**Comment by plk** [comment]
Ah, you're right, sorry, I was thinking of the earlier issue. I'll have a look.

**Comment by nickbart1980** [comment]
> … that's quite tricky as it changes standard bibtex semantics.

There are differences between bibtex and biblatex already (see https://github.com/plk/biblatex/issues/236), so I don’t feel this would be too problematic. biblatex would merely no longer require a space (and the `\relax` recommended by TTB) after prefixes.

**Comment by moewew** [comment]
I have tried to make the solution I implemented on TeX.SX more user-friendly. The user command `\DeclarePrefChars` allows to specify characters after which `\bibnamedelimc` is dropped.

With the solution proposed below one would need to change `\ifpunctmark{'}` in the `name:` macros to `\ifprefchar`. There could be some problems with backwards compatibility, if people deviate from the standard in `\DeclarePrefChars` but don't switch to `\ifpunctmark{'}`.

```
\let\blx@prefchars\@empty

\def\blx@defprefchars@loop#1{%
  \ifx#1\relax
  \else
    \listadd{\blx@prefchars}{#1}%
    \expandafter\blx@defprefchars@loop
  \fi}

\def\blx@defprefchars#1{%
  \expandafter\blx@defprefchars@loop\detokenize{#1}\relax}

\newrobustcmd*{\DeclarePrefChars}{%
  \@ifstar
    {\blx@defprefchars}
    {\let\blx@prefchars\@empty
     \blx@defprefchars}}


\def\blx@namecodes{%
  \ifnum\sfcode`\A=\@m
  \else
    \blx@setazcodes
  \fi
  \def\do##1{\sfcode`##1=\blx@sf@apo}%
  \dolistloop\blx@prefchars
}

\protected\def\blx@imc@ifprefchar{%
  \ifhmode
    \begingroup
    \ifnum\spacefactor=\blx@sf@apo
      \endgroup
      \expandafter\expandafter
      \expandafter\@firstoftwo
    \else
      \endgroup
      \expandafter\expandafter
      \expandafter\@secondoftwo
    \fi
  \else
    \expandafter\@secondoftwo
  \fi}

\blx@regimcs{%
  \ifprefchar}
```

The standard is
```
\DeclarePrefChars{'}
```

with the new commands `name:last` would look like
```
\newbibmacro*{name:last}[4]{%
  \ifuseprefix
    {\usebibmacro{name:delim}{#3#1}%
     \usebibmacro{name:hook}{#3#1}%
     \ifblank{#3}
       {}
       {\ifcapital
          {\mkbibnameprefix{\MakeCapital{#3}}\isdot}
          {\mkbibnameprefix{#3}\isdot}%
        \ifprefchar{}{\bibnamedelimc}}}
    {\usebibmacro{name:delim}{#1}%
     \usebibmacro{name:hook}{#1}}%
  \mkbibnamelast{#1}\isdot}%
```

Again, I might be violating naming conventions here, plus some of the code might be streamlined quite a bit.

Finally, one could think about renaming `\blx@sf@apo` as we have somewhat broadened its scope now.

**Comment by plk** [comment]
Looks quite nice - I don't think we need to rename `\blx@sf@apo` as it does in fact refer to the code for an apostrophe.
