### ISSUE TITLE
\printunit handbook

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#347]
> The \printunit command is similar to \setunit except that ⟨punctuation⟩ persists in the buffer until the next \printtext, \printfield, \printlist, \printnames, or \bibstring command.

Maybe it is because I am no english native speaker, but it is difficult for me to understand well the difference with \setunit. 

Because with \setunit the punctuation won't be printed before the next \print*** command. So it is also "until the next". So what is the difference ? Does \printunit does not check the last \print*** command?

**Comment by moewew** [comment]
Maybe the docs are a bit misleading, probably it should read 

> ... until the next `\printtext`, `\printfield`, `\printlist`, `\printnames`, or `\bibstring` command *prints anything*.

The description for `\setunit` could also mention the fact that the buffer is overwritten more prominently.

Consider the difference in output of
```
\documentclass{article}
\usepackage[backend=biber, style=authoryear]{biblatex}

\addbibresource{biblatex-examples.bib}

\DeclareBibliographyDriver{article}{%
  \printfield{title}%
  \setunit{\addcomma\space}%
  \printfield{flogiston}%
  \setunit{\addcolon\space}% 
  \printtext{that was setunit}%

  \printfield{title}%
  \printunit{\addcomma\space}%
  \printfield{flogiston}%
  \setunit{\addcolon\space}% 
  \printtext{that was printunit}%
}

\begin{document}
\cite{sigfridsson}
\printbibliography
\end{document}
```

In the first case with `\setunit` the comma in the buffer is overwritten by the colon after it because the `\printfield` in between didn't do anything; but with `\printunit` the comma stays until finally punctuation is needed.

**Comment by plk** [comment]
@moewew - feel free to suggest documentation corrections and I'll do it.

**Comment by maieul** [comment]
Le 2015-10-30 18:30, moewew a écrit :
> Maybe the docs are a bit misleading, probably it should read
> 
>> ... until the next \printtext, \printfield, \printlist, \printnames,
>> or \bibstring command _prints anything_.
> 
> The description for \setunit could also mention the fact that the
> buffer is overwritten more prominently.
> 
> Consider the difference in output of
> 
> \documentclass{article}
> \usepackage[backend=biber, style=authoryear]{biblatex}
> 
> \addbibresource{biblatex-examples.bib}
> 
> \DeclareBibliographyDriver{article}{%
>  \printfield{title}%
>  \setunit{\addcomma\space}%
>  \printfield{flogiston}%
>  \setunit{\addcolon\space}%
>  \printtext{that was setunit}%
> 
>  \printfield{title}%
>  \printunit{\addcomma\space}%
>  \printfield{flogiston}%
>  \setunit{\addcolon\space}%
>  \printtext{that was printunit}%
> }
> 
> \begin{document}
> \cite{sigfridsson}
> \printbibliography
> \end{document}
> 
> In the first case with \setunit the comma in the buffer is overwritten
> by the colon after it because the \printfield in between didn't do
> anything; but with \printunit the comma stays until finally
> punctuation is needed.
> 
> --
> Reply to this email directly or view it on GitHub [1].
> 
> 	*
> 
> Links:
> ------
> [1] https://github.com/plk/biblatex/issues/347#issuecomment-152594790

So if I understand well, a \printunit can override a \setunit, but a 
\setunit can't override a \printunit ?

**Comment by moewew** [comment]
Now I have landed myself in the soup...

For `\setunit`
> The `\setunit` command is similar to `\newunit` except that it uses *<punctuation>*
instead of `\newunitpunct`. **Subsequent calls to `\setunit` or `\newunit` will overwrite the punctuation buffer.**

Then with `\printunit` it could be enough to say

> The `\printunit` command is similar to `\setunit` except that *<punctuation>*
persists in the buffer until the next `\printtext`, `\printfield`, `\printlist`, `\printnames`, or `\bibstring` command **(that prints anything) and is not overwritten by subsequent calls to `\setunit` or `\newunit`** .

**Comment by moewew** [comment]
If you don't think that is clear enough, a short explanation in §4.11.7 might also be useful.


> Punctuation inserted into the buffer by `\setunit` can be overwritten by subsequent calls to `\setunit`. The following code
```
\printfield{title}%
\setunit{\addcomma\space}
\printfield{edition}%
\setunit{\addperiod\space}
\printfield{note}%
```
results in 
>> Title, edition. Note

> if all fields exist. But if the `edition` field is missing, the first `\setunit` puts `\addcomma\space` in the buffer which is overwritten by the second `\setunit`'s `\addperiod\space`.
>> Title. Note

> With `\printunit` 
```
\printfield{title}%
\printunit{\addcomma\space}
\printfield{edition}%
\setunit{\addperiod\space}
\printfield{note}%
```
> the result in case of a missing `edition` field is
>> Title, Note

> Since the `\addcomma\space` inserted by `\printunit` cannot be overwritten by the following `\setunit`.

**Comment by maieul** [comment]
Le 2015-10-30 18:50, moewew a écrit :
> Now I have landed myself in the soup...
> 
> For \setunit
> 
>> The \setunit command is similar to \newunit except that it uses __
>> instead of \newunitpunct. SUBSEQUENT CALLS TO \SETUNIT OR \NEWUNIT
>> WILL OVERWRITE THE PUNCTUATION BUFFER.
> 
> Then with \printunit it could be enough to say
> 
>> The \printunit command is similar to \setunit except that __
>> persists in the buffer until the next \printtext, \printfield,
>> \printlist, \printnames, or \bibstring command (THAT PRINTS
>> ANYTHING) AND IS NOT OVERWRITTEN BY SUBSEQUENT CALLS TO \SETUNIT OR
>> \NEWUNIT .
> 

ok, it seems clearer to me. That what I was thinking by some test, but I 
was not sur (and decided, consquently, to use \setunit* which solve my 
problem).

**Comment by aboruvka** [comment]
`\printunit` was something I added, so I've revised its description. I don't think a long explanation is needed; there are many details in the documentation that are not explained and we probably shouldn't start here. If you want a longer explanation, I'd recommend posting over at Stack Exchange.
