### ISSUE TITLE
Support of multiple prefixes

### ISSUE THREAD

**Issue by koppor** [plk/biblatex#350]
I cite papers by "Wil van der Aalst" and I'd like to use the alphabetic style. When using the [LNI-style](https://www.gi.de/index.php?id=171), the label of the entry is `vdA01`. When using `alphabetic`, the label is `vAal01`. Is it possible to include the `d`, too? Meaning: `vdAa01` or `vdAal01`?

```
%file based on http://tex.stackexchange.com/a/21383/9075

\documentclass{article}

\usepackage[
  backend   = biber,
  style     = alphabetic,
  useprefix = true
]{biblatex}

\usepackage{filecontents}

\begin{filecontents}{\jobname.bib}
@misc{A01,
  author = {van der Aalst, Wil},
  year = {2001},
  title = {Alpha},
}
@misc{B02,
  author = {Buthor, B.},
  year = {2002},
  title = {Bravo},
}
\end{filecontents}

\addbibresource{\jobname.bib}
\nocite{*}

\begin{document}
Some text \autocite{A01,B02}.
\printbibliography
\end{document}
```

**Comment by plk** [comment]
Did you try to play around with `\DeclareLabelalphaTemplate`  (biblatex manual 4.5.4). It is designed to allow you to customise the label format yourself and there are options for such things.

**Comment by koppor** [comment]
No, I'll do. Sorry for not seeing it. :see_no_evil:

**Comment by koppor** [comment]
Follow up on http://tex.stackexchange.com/q/276168/9075.
