### ISSUE TITLE
Add a wrapper which allows to surround every citation command

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#353]
`\AtEveryCite{⟨code⟩}` lets us append the `⟨code⟩` to an internal hook executed at the beginning of every citation command.

But, even if a `\AtEveryCiteEnd{⟨code⟩}` command would exist (see https://github.com/plk/biblatex/issues/352), it may not be enough: sometimes, we need to surround every citation command with some macro (with argument), as pointed out [here](http://tex.stackexchange.com/q/276945/18401).

Hence, if we would like to surround every citation command with some `\mynicemacro{...}`, a `biblatex`'s command such as `\SurroundEveryCite{\mynicemacro}` would be nice.

**Comment by aboruvka** [comment]
The multi-citation commands take arbitrarily many arguments, so there is no way we can hook into its end or wrap around the citation. This request is too specialized to consider as a core feature. You can likely implement this for single citations using something like xparse.
