### ISSUE TITLE
\AtNextCite has trouble with wrapped cite macros

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#354]
This problem occurred in http://golatex.de/citep-funktioniert-nicht-t16276.html.

Apparently `\AtNextCite` does not work absolutely smoothly with `\cite` commands that have a wrapper code in their `\DeclareCiteCommand` (even if that wrapper code is empty)

Consider the following MWE

```
\documentclass[12pt,a4paper]{scrartcl}
\usepackage[utf8]{inputenc}
\usepackage[ngerman]{babel}
\usepackage[babel,german=quotes]{csquotes}
\usepackage[style=authoryear, natbib=true, backend=biber, maxcitenames=1, maxbibnames=99]{biblatex}

\addbibresource{biblatex-examples.bib}

\DeclareCiteCommand{\parencite}[]
  {\usebibmacro{prenote}}
  {\usebibmacro{citeindex}%
   \usebibmacro{cite}}
  {\multicitedelim}
  {\usebibmacro{postnote}}

\DeclareCiteCommand{\noparencite}
  {\usebibmacro{prenote}}
  {\usebibmacro{citeindex}%
   \usebibmacro{cite}}
  {\multicitedelim}
  {\usebibmacro{postnote}}

\begin{document}
\AtNextCite{\defcounter{maxnames}{999}}\parencite[223]{aksin}

\AtNextCite{\defcounter{maxnames}{999}}\noparencite[223]{aksin}
\end{document}
```
Where the first citation still displays only one name, while the second shows all names as experted.
The problem seems to be confined to the very special case of changing the `maxnames` counter, changing name fonts, for example seems fine.

When trying to track down the problem I noted that when commenting out `\blx@citeinit` in the definition of `\blx@defcitecmd@iii` it seems to work.
I'm not sure if getting rid of  the `\blx@citeinit` has negative repercussions, but since `\blxciteicmd` calls `\blx@citeinit` anyway, we are probably good removing it there. After all, `\blx@defcitecmd@ii` doesn't have an explicit `\blx@citeinit` either.

The following does therefore work

```
\documentclass[12pt,a4paper]{scrartcl}
\usepackage[utf8]{inputenc}
\usepackage[ngerman]{babel}
\usepackage[babel,german=quotes]{csquotes}
\usepackage[style=authoryear, natbib=true, backend=biber, maxcitenames=1, maxbibnames=99]{biblatex}

\addbibresource{biblatex-examples.bib}

\makeatletter
\long\def\blx@defcitecmd@iii#1[#2]{%
  \protected\long\csedef{blx@cite@#1}##1##2##3##4{%
    \begingroup
    %\blx@citeinit
    \unexpanded{#2}{\blxciteicmd{#1}{##1}{##2}{##3}{}}%
    ##4\endgroup}%
  \blx@defcitecmd@iv{#1}}
\makeatother

\DeclareCiteCommand{\parencite}[]
  {\usebibmacro{prenote}}
  {\usebibmacro{citeindex}%
   \usebibmacro{cite}}
  {\multicitedelim}
  {\usebibmacro{postnote}}

\DeclareCiteCommand{\noparencite}
  {\usebibmacro{prenote}}
  {\usebibmacro{citeindex}%
   \usebibmacro{cite}}
  {\multicitedelim}
  {\usebibmacro{postnote}}

\begin{document}
\AtNextCite{\defcounter{maxnames}{999}}\parencite[223]{aksin}

\AtNextCite{\defcounter{maxnames}{999}}\noparencite[223]{aksin}
\end{document}
```

**Comment by plk** [comment]
Makes sense - I have removed it and pushed a new 3.2 version - we'll see if there are any consequences we haven't noticed.

**Comment by moewew** [comment]
I was doing some tests to find out if the changes did any harm and came about another problem:
`\AtNextCite{\defcounter{maxnames}{999}}\parencite[223]{aksin,sigfridsson}` does not work ase expected either.

Apparently, this is because `\blx@resetdata` is called in `\blx@citeprint` if there is more than one citation. When removing that, the names work as expected. I do, however, believe that getting rid of that command will have other serious  consequences.

I am not sure if there is a way around this, inserting the `\AtEveryCite` hook multiple times as well as removing the part of `\blx@resetdata` where the name counters are reset both seem undesirable.
This is really only an issue for things that are reset in `\blx@resetdata`, the only interesting from a user perspective being name counters and item counters.

There is a work-around for the starred commands in `blx-natbib.def` though,

```
\newrobustcmd*{\AtEveryCitekeyLocal}{\appto\blx@hook@citekey}

\AtNextCite{\AtEveryCitekeyLocal{\defcounter{maxnames}{999}}}\parencite[223]{aksin,sigfridsson}
```

seems to work as expected.

**Comment by aboruvka** [comment]
Can we overturn this commit? Last time I studied the citation commands, I don't recall seeing any problems. The issue brought up here is related to the fact that `maxnames` is an entry specific-option and thus should be set with `\AtNextCitekey`.

**Comment by moewew** [comment]
`\AtNextCitekey` though of only applies to the very next entry which can be a problem when users expect the starred version of the `natbib` compatibility mode to act on all entries cited in that command.

In any case, `blx-natbib.def` needs fixing as `\citep*` and `\citet*` currently do not work as expected.

**Comment by aboruvka** [comment]
They once did, when `maxnames` wasn't entry-specific. A fix is in order, but more care is needed in changing any internals - PL rarely ever got things wrong at that level.

**Comment by plk** [comment]
@moewew - I'm happy to give you commit rights to the git repo - you are probably more competent than me to deal with some of the biblatex code stuff anyway.

**Comment by moewew** [comment]
I would feel honoured, but I don't think there is a lot I can bring to the table. I come across the occasional bug (very rarely is there really a bug at hand) and come up with some feature requests, in a few cases I also have a solution.
Those, however, happen often on a user-level, the innards of `biblatex2.sty` still largely escape my knowledge (as this issue here demonstrates again). Other ideas such as the one above, seem to work at first glance, but I cannot be sure about all use cases.

**Comment by aboruvka** [comment]
I added a new hook called `\AtEachCitekey` - basically your `\AtEveryCitekeyLocal`, but restricted to citations.
