### ISSUE TITLE
*.sty missing langjapanese and fromjapanese

### ISSUE THREAD

**Issue by Lenchik** [plk/biblatex#355]
https://github.com/plk/biblatex/commit/924a749965b9ce209ca320c5769130e3ed9ed259#commitcomment-14250637
https://github.com/plk/biblatex/commit/924a749965b9ce209ca320c5769130e3ed9ed259#commitcomment-14250668

After updating to 3.1 i've got errors:
```
File: russian.lbx 2015/10/21 v3.1 biblatex localization (PK/JW/AB)

! Package keyval Error: langjapanese undefined.

See the keyval package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.506 }
       
Try typing  <return>  to proceed.
If that doesn't work, type  X <return>  to quit.


! Package keyval Error: fromjapanese undefined.

See the keyval package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.506 }
```
I am not sure, but probably because ```langjapanese``` and ```fromjapanese``` not initiated in released version of [biblatex1.sty](https://github.com/plk/biblatex/blob/master/tex/latex/biblatex/biblatex1.sty) and [biblatex2.sty](https://github.com/plk/biblatex/blob/master/tex/latex/biblatex/biblatex2.sty)
If it is the only source of error, may be a good idea to modernize tests for such cases somehow.

**Comment by plk** [comment]
This is already fixed in the development version 3.2 on sourceforge.
