### ISSUE TITLE
Unexpected caps-protection behaviour

### ISSUE THREAD

**Issue by nickbart1980** [plk/biblatex#357]
I was trying to find out how to emphasize but not caps-protect a string in biblatex. `\emph{\relax Foo}` as recommended for bibtex by https://tex.stackexchange.com/a/140071/22851 does not work.

Very surprisingly, it seems in biblatex `{\emph{Foo}}` can be used to obtain an emphasized but non-caps-protected string, and either `\emph{Foo}` or `{{\emph{Foo}}}` for an emphasized *and* caps-protected string.

My question: From the developers’ point of view, is this the expected behaviour? In other words, is this a bug or a feature?

```
\documentclass[american]{article}
\usepackage[american]{babel}
\usepackage[autostyle]{csquotes}
\usepackage[backend=biber, style=apa]{biblatex}
\DeclareLanguageMapping{american}{american-apa}
\usepackage{fontspec}
\setmainfont{Linux Libertine}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
  @article{a,
  author       = {Doe, John},
  year         = {2015},
  title        = {Any {Foo} that appears uppercase is effectively protected
  – \emph{Foo}, {\emph{Foo}}, {{\emph{Foo}}}
  – \textbf{Foo}, {\textbf{Foo}}, {{\textbf{Foo}}}}
}
\end{filecontents}
%
\addbibresource{\jobname.bib}
\begin{document}
\cite{a}
\printbibliography
\end{document}
```

![screen shot 2015-11-08 at 11 30 01](https://cloud.githubusercontent.com/assets/2765811/11020095/1fb96886-860c-11e5-90a4-867add72f2ea.png)

See also https://tex.stackexchange.com/questions/276943/biblatex-how-to-emphasize-but-not-caps-protect/

**Comment by plk** [comment]
This is just one of the small differences between bibtex the program and the btparse library used by biber.

**Comment by moewew** [comment]
This should be fixed with the `expl3` case changing code.
