### ISSUE TITLE
Publisher field issues

### ISSUE THREAD

**Issue by eg9** [plk/biblatex#358]
The `publisher` field is treated as a list, split at `and` (I'm not sure why, but it's documented). However, the behavior when braced tokens appear is at least strange. Since bibliography manager such as Zotero add those silly braces, solving the issue about the missing “Mathematics” in example b should be important.

See http://tex.stackexchange.com/questions/279457/biblatex-publisher-is-truncated and discussion in comments.

    \documentclass{article}
    \usepackage[T1]{fontenc}                            
    \usepackage[utf8]{inputenc}    
    
    \usepackage[
      style=alphabetic
    ]{biblatex}
    
    \usepackage{filecontents}
    \begin{filecontents}{\jobname.bib}
    @book{meyer_matrix_2000a,
      location = {Philadelphia},
      edition = {Har/Cdr},
      title = {Matrix {Analysis} and {Applied} {Linear} {Algebra}},
      isbn = {978-0-89871-454-8},
      timestamp = {2015-11-18T21:19:25Z},
      publisher = {{Society} {for} {Industrial} and {Applied} {Mathematics}},
      author = {Meyer, Carl},
      date = {2000-06-01}
    }
    @book{meyer_matrix_2000b,
      location = {Philadelphia},
      edition = {Har/Cdr},
      title = {Matrix {Analysis} and {Applied} {Linear} {Algebra}},
      isbn = {978-0-89871-454-8},
      timestamp = {2015-11-18T21:19:25Z},
      publisher = {Society for {Industrial} and {Applied} {Mathematics}},
      author = {Meyer, Carl},
      date = {2000-06-01}
    }
    @book{meyer_matrix_2000c,
      location = {Philadelphia},
      edition = {Har/Cdr},
      title = {Matrix {Analysis} and {Applied} {Linear} {Algebra}},
      isbn = {978-0-89871-454-8},
      timestamp = {2015-11-18T21:19:25Z},
      publisher = {Society for Industrial and Applied Mathematics},
      author = {Meyer, Carl},
      date = {2000-06-01}
    }
    \end{filecontents}
    
    \addbibresource{\jobname.bib}
    
    \begin{document}
    
    
    \nocite{*}
    \printbibliography
    \end{document}

<img width="717" alt="screen shot 2015-11-22 at 17 14 51" src="https://cloud.githubusercontent.com/assets/302839/11324797/cbb6f3ca-913c-11e5-99dd-08cfed7e2c27.png">

**Comment by plk** [comment]
This isn't a bug. Publisher is by default a list field in biblatex and therefore split on "and". The usual way to avoid this is to use double braces `{{A and B}}`. You could also redefine the default data model to make publisher a non-list field or use a custom sourcemap to add the braces. This is best done by a question on tex.stackexchange.com.

**Comment by eg9** [comment]
Sorry to insist, but a bug is present: look at references a and b

**Comment by plk** [comment]
Yes, I realise now. This is fixed in biber 2.3
