### ISSUE TITLE
Enhancements to polyglossia interface

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#359]
Per [Change citation language temporarily](http://tex.stackexchange.com/q/280269/35864) `biblatex` seems to have trouble to load the correct bibstrings when using `polyglossia`.

Apparently there are some difficulties with `polyglossia` which made `\blx@langstrings` necessary. The command is, however, not invoked when `polyglossia` changes the language.

The fix I suggested in the answer

```
\apptocmd\select@@language{\blx@langstrings}
```

seems to bring things in line with the behaviour when using `babel`. (I do believe, though, that it is a bit of a kludge.)

MWE to play around with

```
\documentclass{article}        
\usepackage{polyglossia}
\setdefaultlanguage[variant=british]{english}
\setotherlanguage{german}
\usepackage{csquotes}
\usepackage[style=authoryear]{biblatex}
\addbibresource{biblatex-examples.bib}

\makeatletter
%\apptocmd\select@@language{\blx@langstrings}
\makeatother

\begin{document}
\today\ \cite{sigfridsson}

\foreignlanguage{german}{\today\ \cite{sigfridsson}}

\begin{german}
\today\ \cite{sigfridsson}
\end{german}

\today\ \cite{sigfridsson}
\end{document}
```

Alternatively, one could add a call to `\blx@langstrings` to maybe `\blx@citeinit` similar to how it is done in `\blx@bibliography`. The longer I think about it, the more convinced do I get that this is the better solution; but then I have no idea where exactly to place `\blx@langstrings` for proper effect.

**Comment by plk** [comment]
This is strange as I am sure this used to work. Perhaps polyglossia has changed. Anyway. I think you are right that this should be in `\blx@citeprint` since `\blx@langstrings` is null for babel anyway. I have updated bibaltex 3.2 DEV.

**Comment by moewew** [comment]
Thank you for the swift fix.

Playing around with the fix I noticed that `autolang=other` and `autolang=other*` behave differently (which I thought would not be the case from the docs) and even change behaviour based on the language. In the following example, the French citation does not change its language when using `other*`, but well if used with `other`. The same goes for the bibliography. (This happened even before the fix.)

```
\documentclass{article}        
\usepackage{polyglossia}
\setdefaultlanguage[variant=british]{english}
\setotherlanguage{german}
\setotherlanguage{french}
\usepackage{csquotes}
\usepackage[style=authoryear,language=auto,autolang=other*]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{sigfridsson,kowalik,brandt}

\foreignlanguage{german}{\cite{sigfridsson,kowalik,brandt}}

\begin{german}
\cite{sigfridsson,kowalik,brandt}
\end{german}

\cite{sigfridsson,kowalik,brandt}

\printbibliography
\end{document}
```

The same happened when using `babel` here.

If you can find the time you might want to have a look at [this question on TeX.SX](http://tex.stackexchange.com/q/279531/35864) I noted that in

```
\documentclass[11pt, a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[french, main=english]{babel}
\usepackage[autostyle=true]{csquotes}
\usepackage[style=numeric, backend=biber, maxbibnames=10, sorting=nyt, autolang=other]{biblatex}
\usepackage[top=2.2cm, bottom=2.5cm, left=2cm, right=2cm]{geometry}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@online{ITU_climate,
    langid      = {french},
    author      = {{International Telecommunication Union}},
    title       = {Rôle des télécommunications/technologies de l'information et de la communication en ce qui concerne les changements climatiques et la protection de l'environnement},
    year        = {2010},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\nocite{ITU_climate}

\printbibliography

\begin{otherlanguage}{french}
\showhyphens{Rôle des télécommunications/technologies de l'information et de la communication en ce qui concerne les changements climatiques et la protection de l'environnement}
\end{otherlanguage}
\end{document}
```

TeX does not want to break at words containing `'` though it should be when using `otherlanguage`, I understand. But then I don't know whether this really is a `biblatex` issue. French hyphenation seems to be in power, but the handling of special characters seems disabled.

**Comment by plk** [comment]
This is expected as polyglossia allows the babel environments and `otherlanguage*` is like `\foreignlanguage` which only switches hyphenation and extras but not dates, numbers etc (see page 6 of the babel docs). It's unfortunate that the polyglossia manual doesn't mention `otherlanguage*` but it does mention that it recognises the "lower-level" babel commands (section 3.1).

**Comment by plk** [comment]
The second issue seems to have been solved on TSE? When I run your MWE with luatex, it's fine, with pdftex, I see the issue ...

**Comment by moewew** [comment]
OK, I was confused because the `biblatex` docs say that 
> Please note that Biblatex treats `otherlanguage*` like `otherlanguage` but other packages may make a distinction in this case.

so I wasn't to sure about the intended behaviour
and the issue only arose with French, the German and English citations always adapt their language regardless of `other` or `other*` being used. So that looked a bit suspicious.

Re the second issue. The OP seemed happy with what I posted, but when I did further tests I noted that with `babel` and pdfLaTeX the hyphenation of words containing `'` wouldn't work in the bibliography, but they would show the right break-points in `\showhyphens`. I just found though that the actual hyphenation in the document does not work as expected either, so I was wrong blaming `biblatex`, sorry. Maybe it is a misunderstanding of what `otherlanguage` does? With `french` set to the main document language, hyphenation is fine again....

**Comment by plk** [comment]
I also suspect that polyglossias babel compatibility is not entirely correct in some cases, which can be confusing.

**Comment by moewew** [comment]
That could be one issue, yes.

The output of the first MWE is fishy though with both `babel` and `polyglossia` likewise.
Neither example changes the French citation to French, but the German and English citations are adapted to happily. With `babel` the surrounding language takes over, with `polyglossia` it's English - that is the only difference I noticed.

**Comment by plk** [comment]
This looks like a strange difference in the language environments and in particular with French. I wonder if something changed with polyglossia in recent versions. French seems to do strange things, as you say.

**Comment by moewew** [comment]
Of course my analysis that it was French above was flawed.

The trouble seems to be that with `autolang=other*` the language switching seems to work only if the selected language has been active in the document via `otherlanguage` or as main language. Otherwise a fall-back is used. With `autolang=other` it always works.

This is basically the case for both `babel` and `polyglossia`, the exact symptoms are are bit different though

```
\documentclass[spanish,french,german,ngerman,english,british]{article}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear,language=auto,autolang=other*]{biblatex}
\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{sigfridsson,kowalik,brandt,vazques-de-parga}

\foreignlanguage{german}{\cite{sigfridsson,kowalik,brandt,vazques-de-parga}}

\iffalse
\begin{otherlanguage}{ngerman}
\cite{sigfridsson,kowalik,brandt,vazques-de-parga}
\end{otherlanguage}

\begin{otherlanguage}{spanish}
\cite{sigfridsson,kowalik,brandt,vazques-de-parga}
\end{otherlanguage}
\fi

\cite{sigfridsson,kowalik,brandt,vazques-de-parga}

\printbibliography
\end{document}
```

upon removing the `\iffalse...\fi` the German and Spanish citations show the right localisations, the French never does because its language was never active.

**Comment by plk** [comment]
Do you mean by localisations the biblatex localisations or the general babel/polyglossia ones?

**Comment by moewew** [comment]
I'm talking about `biblatex`'s localisation, specifically the "and" bibstring in the citations, but the issue also occurs in the bibliography.

**Comment by plk** [comment]
Can you try this with the 3.2 dev version? I think I have this working for babel, just not yet for polyglossia.

**Comment by moewew** [comment]
`babel` works perfectly fine now.

**Comment by moewew** [comment]
I have finally found the problem with my second issue from above: the French hyphenation.

As so often is the case, the paragraph needs to end *within* the language environment for the `\lccode` statements in French extra to have the intended effect on line breaking.

So adding a `\par` inside `\blx@bibitem` does the job and seems to have no other effects besides enabling proper line breaking. Of course for inline language changes there is nothing we can do with `\par`.

```
\documentclass[11pt, a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[german, frenchb, main=english]{babel}
\usepackage[autostyle=true]{csquotes}
\usepackage[style=numeric, backend=biber, maxbibnames=10, sorting=nyt, autolang=other]{biblatex}
\usepackage[top=2.2cm, bottom=2.5cm, left=2cm, right=2cm]{geometry}

\usepackage{filecontents}
\begin{filecontents*}{\jobname.bib}
@online{ITU_climate,
    langid      = {french},
    author      = {{International Telecommunication Union}},
    title       = {Rôle des télécommunications/technologies de l'information et de la communication en ce qui concerne les changements climatiques et la protection de l'environnement},
    year        = {2010},
}
\end{filecontents*}
\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}

\makeatletter
\def\blx@bibitem#1{%
  \blx@ifdata{#1}
    {\begingroup
     \blx@getdata{#1}%
     \blx@bibcheck
     \iftoggle{blx@skipentry}{}{%
       \global\let\blx@noitem\@empty
       \blx@setoptions@type\abx@field@entrytype
       \blx@setoptions@entry
       \blx@thelabelnumber
       \blx@addprefixnumber
       \addtocounter{instcount}\@ne
       \csuse{blx@item@\blx@theenv}\relax
       \blx@initsep
       \blx@namesep
       \csuse{blx@hook@bibitem}%
       \blx@execute
       \blx@initunit
       \blx@anchor
       \blx@beglangbib
       \bibsentence
       \blx@pagetracker
       \blx@driver\abx@field@entrytype
       \blx@postpunct
       \par%<------ this is new
       \blx@endlangbib}%
     \endgroup}
    {}}
\makeatother

\begin{document}
\nocite{ITU_climate,sigfridsson,geer,wilde,cicero,worman}

A \fullcite{worman} B

\printbibliography
\end{document}
```

**Comment by plk** [comment]
I've added you as a "Collaborator" to the biblatex Git project so you can commit changes. Can you commit this to the DEV branch and I can upload a new version for people to try.

**Comment by plk** [comment]
I have submitted a patch to polyglossia to add `bbl@loaded` there too. It will be in the next release and the DEV 3.2 biblatex will recognise this.

**Comment by moewew** [comment]
The polyglossia thing is great news. (Now all we need to get right is detection of the language variant `;-)`)

I'm a bit hesitant to add the `\par` though, because it will break things for people that don't use a `list`-type environment for their bibliography.

**Comment by plk** [comment]
I submitted a patch to save a list of variants too. biblatex will try to load every lang and variant .lbx to make sure they are available.

**Comment by plk** [comment]
This is now in the releases biblatex 3.2 and is waiting on a polyglossia new release - it'll automatically pick up the changes in the new polyglossia when it's released.
