### ISSUE TITLE
Duplicate keys should be reported even if the corresponding entries don't belong to the same `.bib` file

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#360]
Duplicate keys are reported only if the corresponding entries belong to the same `.bib` file.

Indeed, biber compilation of the following MWE provides only the warning:

>WARN - Duplicate entry key: 'aut12' in file 'test-1.bib', skipping ...

whereas one could expect an extra one such as:

>WARN - Duplicate entry key: 'aut34' in files 'test-1.bib' and 'test-2.bib', skipping ...

```latex
\documentclass{article}
\usepackage[backend=biber]{biblatex}
\usepackage{filecontents}
%
\begin{filecontents}{\jobname-1.bib}
@Book{            aut12,
  author        = {LastName 1, FirstName 1},
  title         = {Title 1},
  publisher     = {Publisher 1}
}
@Book{            aut12,
  author        = {LastName 2, FirstName 2},
  title         = {Title 2},
  publisher     = {Publisher 2}
}
@Book{            aut34,
  author        = {LastName 3, FirstName 3},
  title         = {Title 3},
  publisher     = {Publisher 3}
}
\end{filecontents}

\begin{filecontents}{\jobname-2.bib}
@Book{            aut34,
  author        = {LastName 4, FirstName 4},
  title         = {Title 4},
  publisher     = {Publisher 4}
}
\end{filecontents}
%
\addbibresource{\jobname-1.bib}
\addbibresource{\jobname-2.bib}
%
\begin{document}
\autocite{aut12}
\autocite{aut34}
\printbibliography
\end{document}
```

**Comment by plk** [comment]
The problem here is that all entries are found after reading the first .bib and the second is not even read ...

**Comment by dbitouze** [comment]
Does it mean there's no hope?

**Comment by plk** [comment]
Well, this is really an edge case - the second file isn't needed at all and so there is no need to read it and so the duplicate can't be detected. It would be generally a waste of time in most use cases to process an entire bib file just to report duplicates.

**Comment by dbitouze** [comment]
For a single author, that's indeed an edge case. But, I stumbled upon this problem for a kind of proceedings with many authors, each of them with his own `.bib` file.

**Comment by plk** [comment]
I don't really want to change biber to read all .bib files even if it doesn't need to - the duplicate detection is just a side-effect convenience for users when possible. Biber's main role is to find the entries and process them ...

**Comment by dbitouze** [comment]
Sigh...
