### ISSUE TITLE
! You can't use `\relax' after \advance. <recently read> \blx@sectionciteorder@1

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#361]
Context:

- `biblatex` v3.1,
- `biber` v2.2.

The compilation of the following M(n)WE:
```latex
\documentclass{article}
\usepackage[backend=biber,refsection=section]{biblatex}
\addbibresource{biblatex-examples.bib}
\begin{document}
\tableofcontents
\section{Overview of \citetitle{companion}}
\printbibliography
\end{document}
```
fails with the error:
```
! You can't use `\relax' after \advance.
<recently read> \blx@sectionciteorder@1
```
This issue is similar to https://github.com/plk/biblatex/issues/240 but, while the latter is fixed, this one still arises.

Interestingly, this kind of code did work with older versions of `biblatex`/`biber`, as reported in comments of http://tex.stackexchange.com/q/238288/18401.

**Comment by plk** [comment]
This is quite strange - removing the `\tableofcontents` fixes this as does not having the `\citetitle` in the `\section`.

**Comment by dbitouze** [comment]
Indeed. Another way of fixing this is to make use of a "toc" title without any cite command: `\section{Overview of \citetitle{companion}}` → `\section[Foobar]{Overview of \citetitle{companion}}`.

But it may be desirable to have the citation in the table of contents.

**Comment by dbitouze** [comment]
The example above can be reduced to:
```latex
\documentclass{article}
\usepackage[backend=biber]{biblatex}
% \errorcontextlines=200
\begin{document}
% \tracingmacros=1
\defcounter {refsection}{1}\relax                       % from \jobname.toc
\contentsline {section}{\numberline {1}\cite {foo}}{1}  % from \jobname.toc
\end{document}
```
and inverting the two lines from `\jobname.toc` gets rid of the error.

I tried to track the error with `\tracingmacros` but that's beyond my knowledge.

**Comment by plk** [comment]
Please try biblatex 3.2 dev version -  I think this is fixed.

**Comment by dbitouze** [comment]
Indeed (just a minor warning because asynchronous `biber`'s version): many thanks for a so quick fix! Have you an idea about the next stable release' date?

**Comment by plk** [comment]
Not sure at the moment but probably fairly soon.
