### ISSUE TITLE
Separate package for capitalization

### ISSUE THREAD

**Issue by danielshub** [plk/biblatex#362]
I find the \MakeSentenceCase macro to be very useful and really like how it only operates on brace level 0. I have used the ideas from the macro to create a \MakeUpperCase macro that only operates on brace level 0 (because we all know LaTeX needs yet another way to make things uppercase). I use these macros outside of biblatex for formatting things like article titles and and section headings. Right now I have just copied the relevant bit of code from biblatex2.sty (lines 3165 to 3408) and use that in cases where the biblatex package is not loaded. Any chance of splitting that code off as a separate package that can be loaded separately from the biblatex package?

**Comment by plk** [comment]
Perhaps next year - I'm just about to release a new version  ...

**Comment by plk** [comment]
Do you want to do this and support the package in TeXLive? I don't have the time to make, document and support another package myself.

**Comment by plk** [comment]
I'm closing this for now but if you do abstract it out into a package and it goes into TL, I would use it in biblatex.
