### ISSUE TITLE
\ifprefchar with extra braces in name:first-last

### ISSUE THREAD

**Issue by kmaed** [plk/biblatex#364]
In biblatex.def, the bibmacro name:first-last is defined as
```
\newbibmacro*{name:first-last}[4]{%
...
    \ifprefchar{}
      {}
      {\ifuseprefix{\bibnamedelimc}{\bibnamedelimd}}}%
...
```

But \ifprefchar takes two arguments, not three.
I think the definition should be
```
\newbibmacro*{name:first-last}[4]{%
...
    \ifprefchar
      {}
      {\ifuseprefix{\bibnamedelimc}{\bibnamedelimd}}}%
...
```

In some cases, this inserts an extra space between the first and the last names.

**Comment by plk** [comment]
Many thanks - this is fixed in the 3.3 dev branch.
