### ISSUE TITLE
Inconsistent handling of en dashes in \textcite

### ISSUE THREAD

**Issue by logological** [plk/biblatex#366]
The biblatex manual implies that UTF-8 encoding in the .tex file is natively supported.  However, the `\textcite` command (and possibly others, for all I know) has inconsistent behaviour when processing en dashes encoded via TeX macros vs. UTF-8 strings.  Here is a minimal example with XeLaTeX:

```
\documentclass{article}
\usepackage{fontspec}
\usepackage{biblatex}
\addbibresource{biblatex-examples.bib}
\begin{document}
\textcite[2--8]{markey}
\textcite[2–8]{markey}
\end{document}
```

The first `\textcite` produces the text "Markey [1, pp. 2–8]" but the second one produces "Markey [1, 2–8]".

**Comment by moewew** [comment]
You can get the desired behaviour by issuing

```
\DeclareRangeChars*{–}
```

Maybe `–` should indeed be added to the default set of RangeChars (but I'm not sure if adding unicode characters could cause other trouble).

**Comment by logological** [comment]
So what was the resolution to this issue?  Has – been added to the default set of range characters?  If not, then has the documentation been corrected?  (In the BibLaTeX 3.4 documentation, §4.6.4 gives incorrectly "3–5" as an example of a string that will be treated as a range.  This should instead be "3-5" or "3--5", and it would also be a good idea to add a note that "3–5" does not work by default.)

**Comment by josephwright** [comment]
I'll take a look at this once I've dealt with a  few other things!

**Comment by plk** [comment]
@josephwright  - is this addressed by the unicode stuff you did for the other issue? If we now have those chars available, I see no reason not to include them as range chars?

**Comment by moewew** [comment]
The Unicode en-dash and em-dash are now RangeChars for engines that can deal with Unicode characters natively (XeTeX, LuaTeX). This is the best we can do for technical reasons. The method used to detect these characters can not be used for non-ASCII chars with pdfLaTeX. This was implemented in #665.

Testing, comments and feedback are appreciated.

**Comment by moewew** [comment]
We are planning to release the next version of `biblatex` shortly. Unicode engines should now also accept literal en-dashes. Non-Unicode engines still can only handle `--`.

Testing would be appreciated. You can either pull and install from `dev` or get the development version from https://sourceforge.net/projects/biblatex/files/development/.

**Comment by logological** [comment]
Today's development version works for me.  I tried all kinds of values for the postnote field, including Arabic and Roman pages and page ranges, as well as non-page ranges, and all the output was as expected.  Couldn't find any bugs.

**Comment by moewew** [comment]
@logological Very good. Thank you for checking. Just to be sure what exact version you tested: Did you pull from GitHub or did you use the development version or the 3.10 version from SourceForge?

**Comment by logological** [comment]
I pulled from the `dev` branch from GitHub.

**Comment by moewew** [comment]
Thank you for clarifying this. 3.10 with the relevant changes for this issue should land on CTAN fairly soon (if nothing goes wrong). The changes for #293 did not make it to 3.10.

https://github.com/plk/biblatex/commit/9ed28491871a131a874b5ff15e6b66575996edd1 changes the way the Unicode characters are added. So if anything breaks between 3.10 and 3.11 I (and specifically that commit) am to blame.
