### ISSUE TITLE
[minor bug] polyglossia 1.42.0 recommanded

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#367]
With this MWE
```
\listfiles
\documentclass{article}
\usepackage{polyglossia}
\usepackage{biblatex}
\setmainlanguage{french}
\begin{document}
s
\end{document}
```
I obtain 
> Package biblatex Warning: Upgrade package 'polyglossia' to >v1.42.0 recommended.

Despite http://ctan.org/pkg/polyglossia does not propose v > 1.42.0 and I am up to 1.42.0

**Comment by plk** [comment]
Polyglossia is about to be updated, according to the author ...
