### ISSUE TITLE
\addperiod fails after capital letters in Greek and Russian in xelatex

### ISSUE THREAD

**Issue by kia999** [plk/biblatex#368]
The issue is described in [Spurious punctuation in xelatex + biblatex + Cyrillic or Greek](http://tex.stackexchange.com/questions/230616/spurious-punctuation-in-xelatex-biblatex-cyrillic-or-greek) by Oleg Domanov almost a year ago. I've ran into a similar trouble.

**Comment by moewew** [comment]
Consider the following quite lengthy document adapted from Oleg's TeX.SX MWE

```
\RequirePackage{filecontents}
\begin{filecontents}{\jobname.bib}
@PUNCT{pat1,
  location = {W.},
  publisher = {U.},
  usere={w.},
  userf={u.},
  language = {english},
  hyphenation = {english},
  note = {W\the\spacefactor U\the\spacefactor\ and w\the\spacefactor u\the\spacefactor},
}
@PUNCT{pat2,
  location = {Ψ.},
  publisher = {Ω.},
  usere={ψ.},
  userf={ω.},
  language = {greek},
  hyphenation = {greek},
  note = {Ψ\the\spacefactor Ω\the\spacefactor\ and ψ\the\spacefactor ω\the\spacefactor},
}
@PUNCT{pat3,
  location = {Ш.},
  publisher = {Ж.},
  usere={ш.},
  userf={ж.},
  language = {russian},
  hyphenation = {russian},
  note = {Ш\the\spacefactor Ж\the\spacefactor\ and ш\the\spacefactor ж\the\spacefactor},
}
\end{filecontents}
\documentclass{article}
\usepackage{etoolbox}
\usepackage{ifxetex}
\usepackage{ifluatex}

\ifboolexpr{bool {xetex} or bool {luatex}}
  {\usepackage{fontspec}
   \defaultfontfeatures{Mapping=tex-text}
   \newfontfamily\greekfont{CMU Serif}
   \newfontfamily\cyrillicfont{CMU Serif}
   \usepackage{polyglossia}
   \setdefaultlanguage{greek}
   \setotherlanguages{english,russian}}
  {\usepackage[T1,T2A,LGR]{fontenc}
   \usepackage[utf8]{inputenx}
   \usepackage[english,russian,greek]{babel}}

\usepackage[autolang=other,backend=biber]{biblatex}

\addbibresource{\jobname.bib}

\DeclareBibliographyDriver{punct}{%
  \printfield{usere}\addperiod
  \printfield{userf}\addperiod
  \printlist{location}\addperiod
  \printlist{publisher}\addperiod
  \quad\printfield{note}\finentry}

\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

If run with XeLaTeX and LuaLaTeX the spacefactor after the capital Greek and Cyrillic letters is 999 (as you would expect after capital letters) instead of 1000. This confuses the punctuation tracker and makes `biblatex` think the `.` was a dot and not a period.

With `\blx@setazcodes` `biblatex` makes sure that the capital letters A to Z get a spacefactor of 1000 (just like lowercase letters). This would probably need to be done for all Unicode capital letters.

**Comment by moewew** [comment]
Maybe one could use the data from https://www.ctan.org/pkg/unicode-data to temporary reset all `\sfcode`s of "Lu" characters to 1000.

**Comment by josephwright** [comment]
As @moewew notes, what is needed here is a full setting of all of the `\sfcode` values. There are a couple of ways to do that: I need to think about performance.

**Comment by odomanov** [comment]
I confirm that the MWE I posted to tex.sx works fine with current DEV versions of biblatex and biber.

Thank you all. This was really quite annoying issue making the usage of biblatex with xelatex+cyrillic very tedious.
