### ISSUE TITLE
documentation: @preambles of .bib files

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#370]
In biblatex handbook, about `\RequiresBiber`, it is written:

> This command is intended for use in cbx/bbx files and in the @preamble of bib files.

Hoewever `@preamble` is not described anywhere else.

**Comment by josephwright** [comment]
It's a feature of `.bib` files, not sure if this needs to be covered separately by `biblatex`.

**Comment by maieul** [comment]
biblatex describe many .bib fields and entry ;-)

**Comment by plk** [comment]
@Preamble is quite a standard .bib feature and not that many people use it I think.
