### ISSUE TITLE
entryclone mapping step is broken for biblatex 3.3/biber 2.4

### ISSUE THREAD

**Issue by dcpurton** [plk/biblatex#377]
The following works with biblatex 3.2, but fails when running biber with biblatex 3.3.

biber throws the following error:

```
Can't call method "get_field" on an undefined value at /tmp/par-6463707572746f6e/cache-ab2aa2ece61cc988b50d107b05c5c3fad9d00256/inc/lib/Biber.pm line 3377.
```

MWE:

```
\documentclass{article}
\usepackage[backend=biber]{biblatex}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{ABC,
  author = {Grayson, Albert Kirk},
  title = {Assyrian and Babylonian Chronicles},
  location = {Locust Valley, NY},
  publisher = {Augustin},
  date = {1975}
}
\end{filecontents}
\addbibresource{\jobname.bib}
\DeclareSourcemap{
  \maps{
    \map{
      \step[entryclone={clone-}]
    }
  }
}
\begin{document}
\cite{ABC}
\cite{clone-ABC}
\end{document}
```

**Comment by plk** [comment]
Thanks for reporting this, it was a regression due to the new maploop/new functionality in biber 2.4. This is now fixed in biber 2.5 DEV on Sourceforge and regression tests are in place for the issue. You'll need biblatex 3.4 DEV from sourceforge with biber 2.5.

**Comment by Nhapsie** [comment]
Work with biblatex 3.2 and biber 2.3, and move on to next version only if necessary. This will avoid bugs that usually come with new version releases.

**Comment by dcpurton** [comment]
Thanks, this seems to be fixed in my tests.
