### ISSUE TITLE
Spurious spaces in \indexentry

### ISSUE THREAD

**Issue by Yveu** [plk/biblatex#378]
This issue is reproduced with biblatex version **3.3**.
When indexing=cite option is set, spurious spaces are written in .idx fil by biblatex.

The following MWE:

```
\documentclass[a4paper,12pt]{article}
\usepackage[utf8]{inputenc}
\usepackage{makeidx}
\usepackage{filecontents}
\usepackage[indexing=cite]{biblatex}

\begin{filecontents}{biblio.bib}
@BOOK{xxx,
  author = {Alland, Denis},
  title = {Title}
}
\end{filecontents}

\makeindex
\addbibresource{biblio.bib}

\begin{document}
\cite{xxx}
\printindex
\end{document}
```

generates the following .idx file contents:

```
\indexentry{Alland , Denis }{1}
\indexentry{Title@\emph  {Title}}{1}
```
In the name entry, I note two spurious spaces: one right after the family name "Alland" (and before a comma), and one another right after the given name "Denis".
In the title entry, two spurions spaces in a row, between the command name \emph and the following opening curly bracket "{".

**Comment by plk** [comment]
Can you try this with the 3.4 DEV version (which needs the biber 2.5 DEV version) - this is already fixed there.

**Comment by Yveu** [comment]
Thanks plk for the answer. I'll check it.
Have you already set a release date for version 3.4 ?

**Comment by plk** [comment]
No date yet - still a few things to work out.
