### ISSUE TITLE
\nosort broken

### ISSUE THREAD

**Issue by simifilm** [plk/biblatex#379]
AFAICS the \nosort functionality is broken with the latest additions. Consider the following example:

>  \begin{filecontents}{\jobname.bib}
>         @book{Voigt.A:1906a,
>         	Address = {Leipzig},
>         	Author = {Voigt, Andreas},
>         	Publisher = {Göschen'sche Verlagshandlung},
>         	Subtitle = {Dreihundert Vorträge},
>         	Title = {Die Sozialen Utopien},
>         	Url = {http://www.archive.org/details/diesozialenutop00voiggoog},
>         	Urldate = {2011-10-29},
>         	Year = {1906}}
> 	@book{schwarzbuch,
> 	Address = {Duckburg},
> 	Author = {Duck, Donald},
>  	title = {El Libro Negro Del Terror Nazi En Europa},
> 	 subtitle = {Testimonios de escritoresy artistas de 16 naciones},
> 	 Year = {2002}}
>         }
>         }
>         \end{filecontents}
>         \documentclass[fontsize=12pt,paper=a4,]{scrartcl}
>         \usepackage[utf8]{inputenc}
>         \usepackage[newcommands]{ragged2e} 
>         \usepackage[ngerman]{babel}
>         \usepackage[]{biblatex}
>         \addbibresource{\jobname.bib}
>         \DeclareNosort{\nosort{type_title}{\regexp{\AThe\s+}}}
>         \DeclareSortingScheme{title}{
>   \sort{
>     \field{presort}
>   }
>   \sort[final]{
>     \field{sortkey}
>   }
>   \sort{
>     \field{maintitle}
>     \field{sorttitle}
>       \field{title}
>   }
>   \sort{
> 	  \field{sorttitle}
>       \field{title}
> 	}
>         \sort{
>     \field{sortyear}
>     \field{year}
>   }
>   \sort{
>     \field[padside=left,padwidth=4,padchar=0]{volume}
>     \literal{0000}
>   }
> }
>         \begin{document}
>         \cite{Voigt.A:1906a}
>         \cite{schwarzbuch}
>         \newrefcontext[sorting=title]
>         \printbibliography
>         \end{document}

AFAICS, the `\DeclareNosort` declaration makes no difference.

This is with the latest builds of `biber` and `biblatex`.

**Comment by plk** [comment]
Before I try this - just one comment - the string "The" doesn't occur in any titles in the sample .bib although "Die" and "El" do ....

**Comment by simifilm** [comment]
You're of course right, but it doesn't work either `\DeclareNosort{\nosort{type_title}{\regexp{\ADie\s+}}}`. Looking at it, this actually seems to be a problem of `biber`. Using an older version of `biber` seems to work.

**Comment by plk** [comment]
Looking into it.

**Comment by plk** [comment]
Ah yes, this is because nosort is using the new datafield sets functionality and that hard-coded set "type_titles" is now configured by the `\DeclareDatafieldSet` in biblatex. There are default sets defined for the same names and title sets as before but they are called "setnames" and "settitles". So just replace "type_title" with "settitles".

**Comment by simifilm** [comment]
Ok, got it.
