### ISSUE TITLE
Support of URN

### ISSUE THREAD

**Issue by ghost** [plk/biblatex#38]
It would be great, if you could add support for URN (see RFC1737 and RFC2141).

I found a solution on the web using eprint and eprinttype fields:

``` latex
% use eprint for urn: example fields (bib-file)
% % eprint = {urn:nbn:de:bsz:100-opus-5191},
% % eprinttype = {urn},
% in your document preamble define
\DeclareFieldFormat{eprint:urn}{%
  URN\addcolon\space
  \ifhyperref
    {\href{http://www.nbn-resolving.org/#1}{\nolinkurl{#1}}}
    {\nolinkurl{#1}}}
```

(credit goes to Martin Weis: https://groups.google.com/forum/#!msg/de.comp.text.tex/D-EBL3OfIQE/yJW8gtLnEHMJ)

**Comment by pipping** [comment]
@0x815: What did they say?

**Comment by 0x815** [comment]
There are plans to create a global URN:NBN-Resolver but the project is delayed for an unknown period of time. I don't expect much movement in this topic for the next months or even year.

**Comment by ilippert** [comment]
@0x815: any update available?

**Comment by psisquared2** [comment]
A quick heads up because this is the second Google result for "biblatex urn". For `style=numeric`, I recommend using small capitals for "URN: " as follows:
```latex
\DeclareFieldFormat{eprint:urn}{%
	\textsc{urn\addcolon\space}
	\ifhyperref
	{\href{http://www.nbn-resolving.org/#1}{\nolinkurl{#1}}}
	{\nolinkurl{#1}}}
```
This is more in line with `url`, `isbn`, `doi`, etc.

**Comment by sim642** [comment]
I use the following:
```latex
\DeclareFieldFormat{eprint:urn:nbn}{%
  \mkbibacro{URN}\addcolon\space
  \ifhyperref
    {\href{https://nbn-resolving.org/#1}{\nolinkurl{#1}}}
    {\nolinkurl{#1}}}
```
Compared to the above, this has four improvements:
1. Uses `urb:nbn` as `eprinttype` instead of just `urn`. This requires being a bit more explicit in the bibliography but avoids the problem discussed above that https://nbn-resolving.org doesn't resolve arbitrary URNs.
2. Uses `\mkbibacro` instead of `\textsc` for the `URN` prefix. This is exactly how DOI, URL, etc prefixes are styled. It makes them consistently styled, even if the style is changed.
3. Uses HTTPS instead of HTTP.
4. Removes the unnecessary `www.` from the resolving URL.

**Comment by ilippert** [comment]
>     1. Uses `urb:nbn` as `eprinttype` instead of just `urn`. This requires being a bit more explicit in the bibliography but avoids the problem discussed above that https://nbn-resolving.org doesn't resolve arbitrary URNs.


Thank you for sharing!

Would you mind just explicating how "being a bit more explicit in the bibliography" could look like? I ask – in a way to substitute a stackexchange like question/answer exchange.

Maybe even share here in MWE?

**Comment by sim642** [comment]
For the example in the original issue, the explicitness is just the following change:
```diff
 eprint = {urn:nbn:de:bsz:100-opus-5191},
-eprinttype = {urn},
+eprinttype = {urn:nbn},
```
