### ISSUE TITLE
version number

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#380]
On CTAN, it is said that biblatex version is 3.4

cf http://www.pirbot.com/mirrors/ctan/macros/latex/contrib/biblatex/doc/biblatex.pdf

but it is in reality 3.3

Should it be possible to make a sort release of the handbook to avoid confusion ?

**Comment by plk** [comment]
Strange, thanks for pointing this out. I have fixed this on SF and asked the CTAN people to replace the file.
