### ISSUE TITLE
biblatex 3.3 / biber 2.4 break biblatex-manuscript-philology catalog feature

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#381]
Again a bug with biblatex 3.3 + biber 2.4, not with biblatex 3.2 + biber 2.3. It is not related to the name.

# 1. How biblatex-manuscript-philology works

We need to referts to some page of catalogs when describing a manuscript. As related field can not determine page number of the catalog, (cf http://tex.stackexchange.com/q/147252/7712), we use a special field called `catalog` where we put argument of citation command)
For example
````
 catalog={[xx]{key1}[yy]{key2}}
`````

When biber run for the first time .bib file, it add the `\cite` command (`\DeclareStyleSourcemap` feature)

So the .bbl file contains something like 

`````
\field{catalog}{\cites[334]{Lake1938}[161-164]{Richard857}[421-425]{Richard834}[673-676]{Ehrhard1.1}[80]{Batiffoll1891}}
``````

When LaTeX print the `catalogue` field, it add the entry cited in the .bcf file, and so at the second run of biber, these entry are added in .bbl. And so at the 3nd run of LaTeX, the "catalogue field" is printed.

That was working perfectly with biblatex 3.2 and biber 2.4
Here, I joine file compiled with
- biblatex 3.2
- biblatex-manuscripts-philology 1.7.0
- biber 2.3

[manuscript-ok-1.7.0.zip](https://github.com/plk/biblatex/files/176266/manuscript-ok-1.7.0.zip)

# 2.What wrong with biblatex 3.3

With biblatex 3.3, with the same technique, the catalog entry are indeed added in the .bbl file, but biblatex is not able to read them.

[biblatex-manuscript-philology-bad-1.8.0.zip](https://github.com/plk/biblatex/files/176289/biblatex-manuscript-philology-bad-1.8.0.zip)

See this example, compiled with 
- biblatex 3.3
- biblatex-manuscripts-philology 1.8.0
- biber 2.4

# Ps : Download versions of biblatex-manuscript-philology

https://github.com/maieul/biblatex-manuscripts-philology/tags

**Comment by plk** [comment]
I know why this is. You are doing really weird things - using citation styles and citations that don't appear in any bibliograhphy to typeset parts of a bibliography list. biblatex 3.3 internally formalised some things which makes such strange things break but I think I know how to make it work again as I've seen such tricks in other bug reports recently. Hopefully have a fix in 3.4 dev tomorrow.

**Comment by plk** [comment]
Was easier than I thought. SF is currently down so I can't update the release there but I will as soon as it comes back up.

**Comment by plk** [comment]
SF is back, upload is done

**Comment by maieul** [comment]
I will do test tomorrow morning ! Thanks you for reactivity !

**Comment by maieul** [comment]
It's work ! Many thank.
