### ISSUE TITLE
Add the ability to test if a title is unique

### ISSUE THREAD

**Issue by simifilm** [plk/biblatex#382]
In my style `biblatex-fiwi` the `\citefilm` will on repeated citations only output the name of a `@movie` (it also gives the director and the country of origin on first citation). This becomes a problem when you have several movies with the same name (which is, thanks to all the remakes, not so uncommon). 

At the moment, it's not possible to test whether a title is unique if the `labelname` are different; but for my case, `extratitle` and `extratitleyear` both don't do the trick. Would it make sense to add the ability to test whether a title is unique?

**Comment by plk** [comment]
Didn't we already add a `singletitle` field and `\ifsingletitle` test a while back?

**Comment by simifilm** [comment]
But `singletitle` depends on `labelname`. It only comes into play when `labelname` is either empty, or when it is the inly entry connected to `labelname`. In the case I am interested in here, `labelname` does exist, but it is not relevant for the test.

**Comment by plk** [comment]
Seems reasonable - it's added with option (global and per-type) `uniquetitle`. The corresponding test is `\ifuniquetitle`. See PDF doc. You'll need biblatex 3.4 and biber 2.5 from SF.

**Comment by simifilm** [comment]
Thanks a lot. Works perfectly.
