### ISSUE TITLE
Since biblatex 3.3, biblatex needs to be loaded after autonum (which not recommended)

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#383]
The following file:
```
\documentclass{article}
\usepackage{biblatex}
\usepackage{autonum}
\begin{document}
Foo.
\end{document}
```
used to compile like a charm until version 3.3. of `biblatex` but now fails:
```
! LaTeX Error: Command \ifempty already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.373    first\else second\fi oftwo\endcsname}
```
As a workaround, it is enough to load `biblatex` after `autonum` but that's not recommend, as said page 4 of the documentation of the latter:

>As other packages might break `autonum`, it should be loaded very late. 

(even after `hyperref` and `cleveref`).

Actually, the conflict comes more from `etextools` loaded by `autonum`:
```
\documentclass{article}
\usepackage{biblatex}
\usepackage{etextools}
\begin{document}
Foo.
\end{document}
```

but I wanted to let you know.

**Comment by plk** [comment]
Hmm, this is a pain. By accident I chose to define a new macro called `\ifempty` for 3.3 which conflicts with one in etextools. Any ideas @josephwright?

**Comment by plk** [comment]
I think I have a fix for this. I will look into using etextools in biblatex as it has a lot of nice expandable test stuff on top of etoolbox which will generally simplify a lot of code.

**Comment by plk** [comment]
Please try this with biblatex 3.4. I believe that this is fixed. I have removed the `\ifempty` macro and used the much nicer `\xifemtpy` from etextools.  biblatex will give an error if etextools is loaded beforehand now (because it needs to patch some internals first). This is consistent with what `autonum` needs.

**Comment by dbitouze** [comment]
I'll try it ASAP but I'm not sure relying on `etextools` is safe: see e.g. comments to [this egreg's answer](http://tex.stackexchange.com/a/220277/18401).

**Comment by plk** [comment]
I don't think those comments are particularly damning - I have worked around that `\forlistloop` issue as mentioned and as long as it's not loaded before biblatex (which autonum doesn't want anyway ...), we can get some really useful things from etextools.

**Comment by moewew** [comment]
Trouble is that `\xifemtpy` is based on `\pdfstrcmp` and so the command is not defined in XeLaTeX.

I also got nasty complaints by LuaLaTeX when I tried to run a document using `etxtools`

**Comment by plk** [comment]
biblatex detects this now and loads pdftexcmds and aliases `\pdfstrcmp` to `\pdf@strcmp` for lualatex.

**Comment by moewew** [comment]
Mhhh, I still share dbitouze's doubts, and must say that I find egreg's comment "Sorry, but `etextools` *is* buggy and its author abandoned it." a bit unsettling. But then I'm certainly no expect on TeX internals.

**Comment by moewew** [comment]
The additional code helps with XeTeX, but LuaTeX still throws an `! String contains an invalid utf-8 sequence.` error. See [TeX.SX's `etextools` throws error when run with LuaLaTex](http://tex.stackexchange.com/q/238542/35864) (where egreg repeats his warning).

I can see that some commands from `etextools` are nice, but then it might be a better idea to cherry-pick those and just steal the commands that are needed to avoid compatibility problems that come when loading the entire package

**Comment by plk** [comment]
Hmm, I will look into it, I fear you may be right.

**Comment by plk** [comment]
Try now, I stole what I needed from etextools.

**Comment by moewew** [comment]
It works now except for #384.

**Comment by plk** [comment]
Ok, I'll close this and we'll look into the other issue. I didn't realise xparse was messing about with `\pdf@strcmp`.

**Comment by dbitouze** [comment]
> Please try this with biblatex 3.4. I believe that this is fixed.

@plk Seems to be okay now: thanks!

**Comment by moewew** [comment]
Just in case someone is sent here by Google: please see #669 for `etextools` in `biblatex` version >= 3.8.
