### ISSUE TITLE
"There were undefined references" warning on every second TeX run

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#386]
The following MWE

```
\documentclass{article}
\usepackage[backend=biber]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{sigfridsson}
\printbibliography
\end{document} 
```
Produces a 

```
LaTeX Warning: There were undefined references.
Package biblatex Warning: Please rerun LaTeX.
```

warning block every second LaTeX run after the successfully Biber run.

I can consistently reproduce the following sequence of results with the up-to-date dev versions of both `biblatex` and Biber.

1. pdfLaTeX: "Citation `sigfridsson` undefined"
2. Biber
3. pdfLaTeX: "there were undefined references"
4. pdfLaTeX: no warnings
5. pdfLaTeX: "there were undefined references"

etc. etc.

 `biblatex` 3.3 and Biber 2.4 work just fine in that they produce no warnings from step 3 onwards.

A short look at the `.aux` file shows that it only contains the line
```
\abx@aux@defaultrefcontext{0}{sigfridsson}{nty/global/}
```
on every second run.

**Comment by plk** [comment]
Fixed.

**Comment by moewew** [comment]
I can confirm that the problem does not resurface with the brand-new dev version from sourceforge.
