### ISSUE TITLE
add `@standard` to the regular entry types

### ISSUE THREAD

**Issue by Mo-Gul** [plk/biblatex#388]
It would be nice if you could add the `@standard` entry type to the regular entry types. As default style I would recommend the one given at <http://www.beuth.de/de/hilfe/hilfezitierenvonnormen>.

(I am an engineer and have to cite standards quite often. If you need some entries to play around with, have a look at <http://tex.stackexchange.com/questions/300010/how-to-adapt-the-sorting-of-a-custom-type-standard-in-using-biblatex-biber>. If you need more entries of different standards please let me know, best via Email.)

Many thanks in advance, Stefan

**Comment by plk** [comment]
@aboruvka - this is your territory - what do you think?

**Comment by aboruvka** [comment]
General rule I have applied is, if the request calls for changes to the default data model or styles, it must: be encountered often (e.g. in a variety of disciplines) and require changes to internals to implement (i.e. need more than just existing biber-only features). I don't think either is met here, but feel free to reopen if this needs to be discussed further.
