### ISSUE TITLE
\hyphen preserves following spaces when used in an author field.

### ISSUE THREAD

**Issue by u-fischer** [plk/biblatex#389]
When I compile the following example the first \hyphen in the author field inserts a space in the output. 

![hyphenspace](https://cloud.githubusercontent.com/assets/4047173/13984141/afffeae8-f0f4-11e5-873b-0e6f81eb9e9b.PNG)

~~~~~~
\documentclass{scrbook}
\usepackage{biblatex}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\addbibresource{test.bib}

\begin{document}
\cite{testhyphen}
\printbibliography
\end{document}
~~~~~

~~~~~
@misc{testhyphen,
author={{Nordrhein\hyphen Westfalen Nordrhein\hyphen{}Westfalen}},
title={Nordrhein\hyphen Westfalen}
}
~~~~~

**Comment by plk** [comment]
Well spotted, when I looked at this, I realised it was a bug which had been in biber for years. Corrected with regression tests in 2.5 dev.
