### ISSUE TITLE
\MakeSentenceCase* and language

### ISSUE THREAD

**Issue by jspitz** [plk/biblatex#393]
I am not sure whether this is intentional or not, but  find it confusing and inconvenient.

`\MakeSentenceCase*` currently only considers the language of entries as specified via `LangID`. I think it should also consider the global language as set via language. E.g., in a German document with default language (`language=autobib`), all entries that are not explicitly marked via `LangID` are considered to be German (i.e., hyphenated via German rules). `\MakeSentenceCase*`, by contrast, considers those entries to be English, and lowercases them.

I know that non-marked entries are somewhat "language-agnostic", but then, they should probably be treated consistently for hyphenation and casing.

Alternatively, a global option to configure `\MakeSentenceCase*` behavior for non marked entries (or something such as "default lang ID") would be helpful.

**Comment by plk** [comment]
This seems reasonable, if there is no langid in the entry, to then check the default lang against the list defined with `\DeclareCaseLangs`.

**Comment by plk** [comment]
This is done in 3.4 DEV. I'm glad you mentioned it as it should have been picked up as part of #385. Please test and confirm.

**Comment by jspitz** [comment]
I suppose, in order to test, I need to use the dev versions of biblatex, biblatex-apa (the style where I faced the issue) and biber.
What is the recommended way to easily checkout biber dev? (I am on x64 linux).

**Comment by plk** [comment]
The DEV versions are all built and on Sourceforge - you can just download biber and drop it over your existing one and for biblatex, there is a TDS tree gzip which you can just unpack into your local texmf tree. Current biblatex-apa should work with 3.4 but if you have any problems, I can send you my dev version.

**Comment by dcpurton** [comment]
@plk: I know this is the wrong place to ask, but... :)

Will the next version of biblatex to appear in CTAN be 3.4 based of the current dev branch in git? If so, I'm confused about the status of the v.3.4 tag. Is this something that will ever be publicly release? Or can I ignore it and just make sure my style works with 3.3, and then keep up with the dev branch until your next release?

**Comment by jspitz** [comment]
Thanks. I had to change the `\ifempty`'s to `\ifdefvoid` in the recent `apa.bbx` version available fro github.

I can confirm that it works now as I'd expect it for German documents..

**Comment by plk** [comment]
The "v" is there to keep github happy about semantic versioning. Yes, the dev branch is what ends up as the next release and so that's what should be used for testing. I try to keep the development tag pointing to the latest commit but it sometimes lags behind a few. However, I always build and upload a packaged version into the Sourceforge development folder after dev branch updates.

**Comment by jspitz** [comment]
Small addition: Would it be possible to provide a test `\ifcaselang{true}{false}`? I am thinking of using for instance the macros provided by the titlecaps package to produce coherent title casing, but only in the languages that have the title casing/sentence casing distinction.

**Comment by plk** [comment]
Certainly, I'll do that today and let you know.

**Comment by plk** [comment]
This is done in 3.4 DEV.

**Comment by jspitz** [comment]
Thanks. I understand, however, that you have to enter manually a language to check. I had in mind a check if the currently active language is a caselang (e.g. in the context of a title format definition). Or is there something like a `\currentlang` macro that can be passed here? (I did not find such a thing in the manual, but I might have overlooked it)

**Comment by jspitz** [comment]
On a closer look, I see that I could probably do 
```
\DeclareFieldFormat{titlecase}{%
   \ifcaselang{\blx@languagename}{\titlecap{#1}}{#1}%
}
```

However, `\blx@languagename` is an undocumented, internal command, so it strikes me rather clumsy.

**Comment by plk** [comment]
Yes, and that doesn't switch automatically inside entries with `langid` set. However, give me a few minutes and there will be a public macro and the language argument to `\ifcaselang` will be optional.

**Comment by plk** [comment]
Try it now. The first argument to `\ifcaselang` is now optional and falls back on `\currentlang`, a new macro which tracks the internal movements of `blx@languagename`. This latter now tracks changes inside entries when swtiching based on `langid` with babel/polyglossia. Of course, you'll need to be using some setting for `autolang` and it won't track in cites without changing the default `language` option to `auto` since the default is just `autobib`.

**Comment by jspitz** [comment]
This is exactly what I had in mind, thank you. 

Since `\blx@languagename` now tracks `langid` settings, I understand that `\bbl@main@language` should now be used in order to check for the global language, right? In my style, I have defined a macro `\biling{<german>}{<english>}` which output either the first or the second argument depending on whether the bibliography is in an English or German text (for instance in addenda). Until now, I have used `\blx@languagename`, which won't work now, since the entries also have a `langid.`

**Comment by plk** [comment]
Used outside of an entry, `blx@languagename` should be ok but it is really used to track the language at the point of use. For general checking of document language, the babel/polyglossia interfaces should really be used, like `\bbl@main@language`. Let me know if you find any problems.

**Comment by moewew** [comment]
This came up in [MacTeX 2016 somehow broke a bbx](http://tex.stackexchange.com/q/315532/35864). Apparently `biblatex` now chokes on `\MakeSentenceCase*` if no document language is defined (if neither `babel` nor `polyglossia` are loaded)  *and* no `langid` field is present.

MWE with standard styles
```
\documentclass{article}
\usepackage{biblatex}

\usepackage{filecontents}
\begin{filecontents*}{\jobname.bib}
@online{elk,
  author   = {Anne Elk},
  title    = {Towards a Unified Theory on Brontosauruses},
  url      = {http://www.example.edu/~elk/bronto.pdf},
}
\end{filecontents*}

\DeclareFieldFormat{titlecase}{\MakeSentenceCase*{#1}}%

\addbibresource{\jobname.bib}
\begin{document}
\nocite{elk}

\printbibliography
\end{document}
```

**Comment by plk** [comment]
Strange - I have added fallback to "english" in the case when babel/polyglossia is not loaded. I thought that was already in there. Also, using the non-starred version of `\MakeSentenceCase` should work?

**Comment by plk** [comment]
In fact, I think someone changed `\MakeSentenceCase` to check the babel/polyglossia lang without checking to see if it was defined at all and there was no fallback to the generic default lang setting. I have added this now to 3.5.

**Comment by moewew** [comment]
Thank you for the swift response. It works just fine now.
You might want to mention in the documentation though that  `\blx@languagename` defaults to `english` so that a document is assumed to be in English if nothing indicating the contrary is found.
