### ISSUE TITLE
Can't build with new build script (without forking)

### ISSUE THREAD

**Issue by dcpurton** [plk/biblatex#397]
The latest changes to the build script mean that biblatex can't be built without forking since a `git push` command is included. I've been just cloning your repository directly in order to test and make sure my own style keeps up with your changes. I wonder if this could be modified somehow so it's still possible for an anonymous checkout to build.

**Comment by plk** [comment]
I thought that might be a problem - I've changed it now so that the git part only runs if you have an env var of "BIBLATEXDEV" set to 'true'.

**Comment by dcpurton** [comment]
Thanks!
