### ISSUE TITLE
Backwards compatibility for prefixnumber

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#399]
In version 3.4 `prefixnumber` field is going to be `labelnumber`. While using the old option gives a warning, using `\printfield{prefixnumber}` issues no warning, but silently does nothing. 

Would it be a good idea to create some kind of legacy alias that warns users of the old field name, yet still does the right thing for them? I'm a bit dubious about whether that is a good idea. Ideally it would not be needed because all styles would be updated and no-one would be using modifications in their own document. But the truth is that there is lots of code out there using `prefixnumber` that will just stop working properly without warning.

**Comment by plk** [comment]
I was also thinking about this but I'm not sure how many styles actually issue `\printfield{prefixnumber}` - it's only in numeric/alpha styles are there aren't many custom variants since they are relatively general anyway. There will be code which mentioned the `prefixnumbers` option but this will generate a warning anyway.

By the way, I did some profiling in biber and managed about a 100% speed increase in the 2.5 version uploaded last night - be aware if you are testing to see if you notice a difference - of course the difference is mostly noticebale on large .bib fles.

**Comment by moewew** [comment]
You are right that this is quite a niche problem. Many of the custom numeric styles on CTAN are maintained by Joseph Wright, so they are likely to keep up to speed with `biblatex`. I did not find lots of `\printfield{prefixnumber}` upon googling either, I had expected a bit more.

Still, the other warning does not quite cut it, as it will disappear if one just uses the new option in the right way even if the style can't handle `labelprefix`.

I came up with

```
\newrobustcmd*{\DeprecateFieldFor}[2]{%
  \csdef{abx@field@#1}{%
    \ifcsundef{abx@field@legacy@warning@#1@#2}{\blx@warning@noline{Field '#1' deprecated, using '#2' instead}}{}%
    \global\csdef{abx@field@legacy@warning@#1@#2}{}%
    \csuse{abx@field@#2}}}

\DeprecateFieldFor{prefixnumber}{labelprefix}
```
This does not deal with field formatting in last detail, but it makes sure old code continues to work while at the same time issuing a warning that `prefixnumber` is deprecated.

**Comment by plk** [comment]
I'm not sure `\abx@field@<oldfield>` would ever be called as that comes from `\field` which is generated by `biber` and `biber` won't write `\field{prefixnumber}` any more as of 2.5 anyway.

**Comment by moewew** [comment]
Doesn't `\printfield{<oldfield>}` call `\abx@field@<oldfield>`?

**Comment by plk** [comment]
Yes, my mistake, that's true. Ok, let's do that but perhaps make `\DeprecateFieldFor` internal as I can't see users needing it.

**Comment by plk** [comment]
I will also add corresponding commands `\DeprecateList` and `\DeprecateName` I think.

**Comment by plk** [comment]
Draft done in 3.4.

**Comment by jspitz** [comment]
> I was also thinking about this but I'm not sure how many styles actually issue \printfield{prefixnumber}

Here is one, for the record: http://www.ctan.org/pkg/biblatex-publist
And I have quite a bit more in my private tree. Since you never know what "private" styles people have. I would always opt for a salient warning if dataloss is possible.

**Comment by moewew** [comment]
You might want to add a note that because of how `\Deprecate...` is implemented one can only deprecate fields that do not exist any more in the data model.
`\DeprecateField{flobbel}{title}` works, but `\DeprecateField{language}{title}` has no effect.

Deprecation of names and lists is a bit more complicated, I believe, since one would have to properly define all the auxiliary commands as well. I couldn't quite get it to work, there are at least `c@<list/name>` and maybe even `blx@lih`/`blx@nih` to think about.

**Comment by plk** [comment]
I need to think about this - the only reliable way of doing this really is in the datamodel, it would mean making the `\Deprecate*` commands part of a datamodel declaration which makes sense really.

**Comment by plk** [comment]
This is much harder than imagined - it would need to mirror internals of etoolbox and latex to transparently migration calls to the new field name for lists/names. I don't think it's worth it. I favour emitting a warning and not trying to fall back on the new name.

**Comment by moewew** [comment]
I'd prefer a solution where we fall back to the old field, but I can see that this becomes quite difficult if it should be done properly via the data model (especially if we want to get the formatting right). That's why I was happy that hooking into the internal `abx@field@<fieldname>` seemed to work fairly well, but I can see now that this was a fluke. Even though we currently only need `\DeprecateField` it would probably be a weird decision to only provide that macro and not offering a solution for list and names.

**Comment by plk** [comment]
We still need the list/names ones because the internal macros we have to add to are named differently. I suppose we could define `\abx@{field,list,name}` together but users are use to the "field,list,name" distinction in other user-facing macros.
