### ISSUE TITLE
Spurious spaces in index of authors when using indexing=cite (biblatex 3.3.)

### ISSUE THREAD

**Issue by m-vogel** [plk/biblatex#400]
as far as I can see, biblatex produces spurious blanks in the index after the handling of names has been changed in v3.3. Here's a MWE:

`\documentclass{book}
\usepackage{imakeidx}
\usepackage{filecontents}
\usepackage[backend=biber,indexing=cite]{biblatex}

\makeindex[title=Index of Authors, name=autorenindex]

% modified def from biblatex_.def
\DeclareIndexNameFormat{default}{%
  \nameparts{#1}%
  \usebibmacro{index:name}%
    {\index[autorenindex]}%
    {\namepartfamily}%
    {\namepartgiveni}%
%    {}% L1
%    {}% L2
    {\namepartprefix}% generates spurious space L3
    {\namepartsuffix}% generates spurious space L4
}

\begin{filecontents}{general.bib}
@misc{C1,
  author = {Peter Pan},
  year = {1904},
  title = {The Art of Flying}
}
@misc{C2,
  author = {Thatcher, Margaret},
  year = {1984},
  title = {Selling England by the Pound}
}
\end{filecontents}
\addbibresource{general.bib}

\begin{document}

\citeauthor{C1}
\citeauthor{C2}

\printindex[autorenindex]
\end{document}`

The code produces: 

Pan , P. , 1 Thatcher , M. , 1

One can get rid of the spaces by commenting out L1 and L2 and commenting L3 and L4. But than name prefixes and suffixes will be lost. I never encountered such problems in biblatex 3.2. Is something wrong with my use of \DeclareIndexNameFormat or with biblatex?

Best, 
Matthias

**Comment by plk** [comment]
Can you try the development version 3.4 from Sourceforge? This was fixed a couple of weeks ago. You will need biber 2.5 dev version too if you are using biber.

**Comment by m-vogel** [comment]
Thanks! Since building a biber executable is beyond my skills, I will have to wait for the next update on ctan.

**Comment by plk** [comment]
You don't have to wait - I always upload binaries yo the dev folder on sourceforge for common Oses - you just need to use the latest biblatex dev version too, also on SF.

**Comment by m-vogel** [comment]
Thanks for the hint. I did try the new versions and everything is fine!

Best,
Matthias

Am Fr., 01.04.2016 um 13:59 schrieb plk:
