### ISSUE TITLE
Typo: file.bbx → ⟨file⟩.bbx, etc.

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#401]
E.g. page 46 of `biblatex`'s documentation, it's written e.g.:

> style=⟨file⟩
> Loads the bibliography style `file.bbx` and the citation style `file.cbx`. [...]

IMHO, should be:

> style=`⟨file⟩`
> Loads the bibliography style `⟨file⟩.bbx` and the citation style `⟨file⟩.cbx`. [...]

**Comment by plk** [comment]
Fixed, thanks.

**Comment by dbitouze** [comment]
AFAICS, you omitted the same trouble for `bibstyle` and `citestyle`. Sorry for not having been more explicit.

**Comment by plk** [comment]
Also fixed now.
