### ISSUE TITLE
Biblatex 3.3: \entrydata* can't recover fields cleared by .bbx driver

### ISSUE THREAD

**Issue by dfussner** [plk/biblatex#405]
When \blx@saveentry is called within \blx@imc@entrydata@i, usually at
the end of a .bbx driver, any fields cleared by that .bbx driver won't
receive "saved{field}" equivalents, making tests for them in the
related:* macros non-functional.  In related:multivolume, for example,
there's a test for whether "savededitor" and "editor" are the same,
but they can't be because "savededitor" is undefined, the "editor"
field of the main entry having been cleared in, I believe, all the
standard styles and probably most to all of the contributed ones.
This results in the "editor" being reprinted in all of the individual
volumes below the multivolume book, no matter whether it's the same or
a different editor in the relevant .bib entries.  My MWE and output
show this below.

If you move the \blx@saveentry call to the head of the driver, e.g.,
using AtEveryBibitem, then all of the fields are available for testing
in related macros, assuming those macros use the unstarred \entrydata.
Use of \entrydata* in the macro restores the current functionality,
with fields cleared by the .bbx driver no longer available.

Alternately, could one modify \clearfield in entries with a "related"
field, perhaps making it save cleared fields in another internal list
and having \blx@saveentry read that?

Here's the MWE:

\documentclass[12pt]{article}
\usepackage{csquotes}
\usepackage[american]{babel}
\usepackage[style=reading,backend=biber]{biblatex}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{knuth:ct:a,
  author       = {Knuth, Donald E.},
  title        = {The {\TeX} book},
  date         = 1984,
  maintitle    = {Computers \& Typesetting},
  volume       = {A},
  editor = 	 {Report, Bug},
  publisher    = {Addison-Wesley},
  location     = {Reading, Mass.}
}

@book{knuth:ct:related,
  author       = {Knuth, Donald E.},
  title        = {Computers \& Typesetting},
  date         = {1984/1986},
  volumes      = 5,
  publisher    = {Addison-Wesley},
  location     = {Reading, Mass.},
  editor = 	 {Report, Bug},
  related      = {knuth:ct:a},
  relatedtype  = {multivolume}
}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}
\thispagestyle{empty}
\noindent
\nocite{knuth:ct:related}
\printbibliography
\end{document}

And here's the output on my system:

![mwe7](https://cloud.githubusercontent.com/assets/5174434/14403593/10be809c-fe56-11e5-865b-80bc10350c4f.png)

Thanks.

**Comment by plk** [comment]
Well, spotted, thank you. This must be a long-standing bug since the implementation of the related feature. Please try biblatex 3.4 dev version from Sourceforge - I think this should be fixed. I had to use the `\clearfield` modification route because I don't want unintended side-effects of moving `\blx@saveentry` outside of its tightest enclosing group. You will need biber 2.5 from Sourceforge too.

**Comment by dfussner** [comment]
I'll try 3.4dev as soon as I get a spare moment -- many thanks indeed for your swift response.

**Comment by dfussner** [comment]
I've been testing 3.4dev and Biber 2.5, and while in many cases your fix seems just right, I'm now getting very peculiar behavior from some entries with "related" fields.  If I process (notice new style and also multiple keys in \cite command):

\documentclass[12pt]{article}
\usepackage{csquotes}
\usepackage[american]{babel}
\usepackage[style=verbose-note,backend=biber]{biblatex}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{knuth:ct:a,
  author       = {Knuth, Donald E.},
  title        = {The {\TeX} book},
  date         = 1984,
  maintitle    = {Computers \& Typesetting},
  volume       = {A},
  editor = 	 {Report, Bug},
  publisher    = {Addison-Wesley},
  location     = {Reading, Mass.}
}
@book{knuth:ct:related,
  author       = {Knuth, Donald E.},
  title        = {Computers \& Typesetting},
  date         = {1984/1986},
  volumes      = 5,
  publisher    = {Addison-Wesley},
  location     = {Reading, Mass.},
  editor = 	 {Report, Bug},
  related      = {knuth:ct:a},
  relatedtype  = {multivolume}
}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}
\thispagestyle{empty}
\noindent
\cite{knuth:ct:related,knuth:ct:a}
\printbibliography
\end{document}

the LaTeX run chokes with some messages like this:

! Extra }, or forgotten $.
<recently read> }
                 
l.33 \cite{knuth:ct:related,knuth:ct:a}
                                       
I've deleted a group-closing symbol because it seems to be
spurious, as in `$x}$'. But perhaps the } is legitimate and
you forgot something else, as in `\hbox{$x}'. In such cases
the way to recover is to insert both the forgotten and the
deleted material, e.g., by typing `I$}'.

! Argument of \listbreak has an extra }.

Then, further down, I get an Overfull \hbox with an enormous selection of fields from blx-dm.cnf attempting to make their way into the document, followed by 

! Argument of \etb@forlistloop@i has an extra }.
<inserted text> 
                \par 
l.33 \cite{knuth:ct:related,knuth:ct:a}
                                       
I've run across a `}' that doesn't seem to match anything.
For example, `\def\a#1{...}' and `\a}' would produce
this error. If you simply proceed now, the `\par' that
I've just inserted will cause me to report a runaway
argument that might be the root of the problem. But if
your `}' was spurious, just type `2' and it will go away.

Runaway argument?
isan|isbn|ismn|isrn|issn|issue|issuesubtitle|issuetitle|iswc|journals\ETC.

I get a slightly different version of this in biblatex-chicago, but the essentials are the same, and I know that document compiled in 3.3.  If you remove the "related" field from the knuth:related entry then the document compiles just fine.  To be honest, I had a look at biblatex_.sty and couldn't work out the cause -- if you need more information, like the full .log file, please let me know.

One last thing -- the dev version of Biber doesn't seem to respect the bibencoding option, and gives me a UTF8 .bbl file when I've asked for Latin1.  If I give the output-encoding option on the command line, it works fine.

Thanks.

**Comment by plk** [comment]
Just one quick thing - the biber issue, you know that biber's `--output-encoding` option corresponds to the bibaltex `texencoding` option and not `bibencoding`?

**Comment by plk** [comment]
Looks like it was an expansion issue due to verbose styles which do strange things in general. Try it again now with the newly uploaded 3.4.

**Comment by dfussner** [comment]
In all of my testing so far, the new 3.4dev does indeed fix the "related" issue -- many thanks!

As for the `biber` thing, you're quite right, `--output-encoding = texencoding`, but rather curiously I'm getting the same issue.  For many years I've set `inputenc` to `latin1`, then set `bibencoding` to `latin1` as well, and `biber` always worked.  Now, with 2.5dev and that setting, and with `texencoding` set to `latin1` or to `auto`, `biber` claims, in the .blg, that it's outputting a `latin1` .bbl, but when I use the `file` command on the .bbl it tells me it's `UTF8`, and LaTeX chokes on it.  (Viewing the file with `less` shows that it's UTF8, as well.)  With neither `bibencoding` nor `texencoding` set I have the same problem.  I have to use the `--output-encoding` switch to get a .bbl file that's `latin1` (`ISO-8859`, according to the `file` command).  Could something have changed in that area between 2.4 and 2.5?

**Comment by plk** [comment]
Can you try biber 2.5 just uploaded?

**Comment by dfussner** [comment]
Yes, the new biber returned the behavior to how it used to work -- many thanks again!

Just out of curiosity, are you aiming for any particular deadline for the release of 3.4, or will it be done when it's done?

**Comment by plk** [comment]
Do particular date yet but I would expect a week or so.
