### ISSUE TITLE
\printbibliography with segment picks up only cites issued before it

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#406]
Consider the following MWE with explicit `segment` in `\printbibliography`

```
\documentclass{article}
\usepackage[backend=biber]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{sigfridsson}
\printbibliography[segment=\therefsegment]
\cite{companion}
\end{document}
```

Only `sigfridsson` appears in the bibliography, `companion` is ignored.

Cf. [this comment on TeX.SX](https://tex.stackexchange.com/questions/303485/referencing-to-citation-in-a-refsection#comment735681_303488).

**Comment by plk** [comment]
Hmm, I doubt this ever worked - it would need .aux file support.

**Comment by plk** [comment]
Please try the latest 3.4 - I have put .aux file support in for refsegment tracking - simple solution but it seems to work.

**Comment by dcpurton** [comment]
Thanks, I'll check it out.

Regarding related entries, how can I *force* a related every to appear in the bibliography? Thus was my original reason for not being able to use writer `xref` or `related`.

**Comment by moewew** [comment]
Indeed, it seems to work very well. Thank you very much.
