### ISSUE TITLE
Support for Citation Style Language?

### ISSUE THREAD

**Issue by PieterO** [plk/biblatex#409]
As far as I'm aware, there is no way to easily use on the of the several thousand styles that are offered by the language, is it possible to add support so it is easily to specify the .csl file and have biblatex export to the same format?

This is definitely easier said than done and if there is a simple workaround that could be used instead, then thats fine by me. I've had a look around and not found anything that would easily work. Thanks.

**Comment by plk** [comment]
This is unlikely to happen I'm afraid - writing and supporting a bridge between styles written in latex and those written in CSL is far too hard. I remember having a discussion with the CSL people years ago - CSL is not really aimed at typesetting documents and doesn't have the details which biblatex users need. Styles in biblatex aren't declarative but much more tied to typesetting. If you look at the "Limitations of CSL" on the CSL cite, biblatex handles all of those limitations and price is a lot of complexity - I wrote the biblatex APA style and I know that complete automation of even the name list handling in APA 6th edition is just not possible in a declarative XML style format. The mismatch between biblatex and CSL styles is that between a dedicated, specialist tool that can do some things really well and and general purpose tool that does a lot more things but none of them as well as a specialist tool. This makes any sort of communication really tricky at a conceptual level, regardless of the technical challenge ... sorry.

**Comment by simifilm** [comment]
Just two cents from my side. While I absolutely see the problems of a `CLS`/`biblatex` bridge – I am actually not even sure how such a thing should work on a purely conceptual level –, `CSL` as such could certainly be implemented for `LaTeX`. Bruce d'Arcus, the original of `CSL`, envisioned such a thing from the start, and while `CSL for LaTeX` would not be able to offer all the typographic bells and whistles `biblatex` has – see plk's comment –, the possibility to use `CSL` styles in `LaTeX` would certainly be a nice thing. Alas, no one has yet come up with a port – much to my surprise and chagrin –, and such a project would certainly be completely outside the scope of `biblatex/biber`.
