### ISSUE TITLE
CTAN description mentions minimum version 

### ISSUE THREAD

**Issue by cbm755** [plk/biblatex#415]
On https://www.ctan.org/pkg/biblatex, I see the following false statement:

````
the present re­lease of BibLaTeX is de­signed to work with bibla­tex-biber ver­sion 0.9.6. 
````

And also this statement:
````
ver­sion 0.9 is re­quired (at least; re­fer to the notes for the ver­sion of bibla­tex-biber that you are us­ing). 
````

These statements then appear in texlive installations (e.g., [in Fedora](https://apps.fedoraproject.org/packages/texlive-biblatex)).  I didn't find this text in this repo... is it defined somewhere else?

I think it should just say something like "Development of biblatex and biber is closely coupled; biblatex requires a fairly recent version of biber, as noted in the release notes".

**Comment by plk** [comment]
I think it’s a separate thing sent to the CTAN maintainers - I’ve asked them how I update this, thank you for spotting it.

PK

> On 25 Apr 2016, at 8:10 pm, Colin Macdonald <notifications@github.com> wrote:
> 
> On https://www.ctan.org/pkg/biblatex, I see the following false statement:
> 
> the present re­lease of BibLaTeX is de­signed to work with bibla­tex-biber ver­sion 0.9.6. 
> 
> And also this statement:
> 
> ver­sion 0.9 is re­quired (at least; re­fer to the notes for the ver­sion of bibla­tex-biber that you are us­ing). 
> 
> These statements then appear in texlive installations (e.g., in Fedora). I didn't find this text in this repo... is it defined somewhere else?
> 
> I think it should just say something like "Development of biblatex and biber is closely coupled; biblatex requires a fairly recent version of biber, as noted in the release notes".
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> 

--
Dr Philip Kime
