### ISSUE TITLE
Biblatex 3.4dev [2016/05/07] \clearname{labelname} issue

### ISSUE THREAD

**Issue by dfussner** [plk/biblatex#419]
When I use `\clearname{labelname}`, it truncates the name field from
which the labelname was taken.  The following MWE, with a custom cite
command, shows how only the first name in an author field turns up
after the `\clearname{labelname}` call.  I spotted this in an earlier
dev version but it still happens in today's version from SourceForge.
(It affects a custom cite command in the Chicago style.)  Is it
intended that it should clear the whole of the field, or should it
leave such a field entirely alone?

Here's the MWE:

\documentclass[12pt]{article}
\usepackage{csquotes}
\usepackage[american]{babel}
\usepackage[style=verbose-note,backend=biber]{biblatex}
\DeclareCiteCommand{\testcite}
{}
{\printnames{author}%
  \clearname{labelname}%
  \setunit{\addsemicolon\addspace}%
  \printnames{author}}%
{}
{}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{knuth:ct:a,
  author       = {Knuth, Donald E. and Name, Second and Name, Third},
  title        = {The {\TeX} book},
  date         = 1984,
  maintitle    = {Computers \& Typesetting},
  volume       = {A},
  editor = 	 {Report, Bug},
  publisher    = {Addison-Wesley},
  location     = {Reading, Mass.}
}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}
\thispagestyle{empty}
\noindent
\testcite{knuth:ct:a}
\printbibliography
\end{document}

And here's the output on my system:

![mwe8](https://cloud.githubusercontent.com/assets/5174434/15093493/d1444c66-1481-11e6-8c97-0dc58ffe86ed.png)

Thanks.

**Comment by plk** [comment]
Thanks for this report - it was a subtle bug in fact - I would expect this not to touch the label name source field at all. Please can you try the current 3.4 dev version.

**Comment by dfussner** [comment]
Yes, that now looks exactly as I expected, in the standard styles and in Chicago.  Many thanks indeed!
