### ISSUE TITLE
Formatting of suffixes does not work as expected

### ISSUE THREAD

**Issue by michue** [plk/biblatex#420]
According to the documentation (page 104) I assumed `\mkbibnamesuffix` to change the format of a name suffix. This does not work.

Instead the legacy `\mkbibnameaffix` formats the suffix. Taking a look into `biblatex_.def` at line 839ff. reveals, that the bibmacros `name:given-family` and `name:family-given` still use the legacy macro.

The following MWE illustrates this issue

```TeX
\documentclass{report}

\RequirePackage[
   % Use the newest backend: biber
   backend=biber,
   % Use alphabetic style
   style=alphabetic
]{biblatex}

\begin{filecontents}{bibliography.bib}
@Article{Duckhausen,
author =    {von Duckhausen, Sr, Dagobert},
title =     {Lowercase Title},
journaltitle = {Miscellaneous Journal},
date =      {2016-05-10}
}
\end{filecontents}}
% Add the bibliography as only source
\addbibresource{bibliography.bib}

% The format of name suffix cannot be changed using
\renewcommand*{\mkbibnamesuffix}{\textit}
% but reacts to the legacy command
\renewcommand*{\mkbibnameaffix}{\textbf}

\begin{document}
\chapter{First Chapter}
Citation of working entry \cite{Duckhausen}.

% Suffix will be printed in bold font
\printbibliography
\end{document}
```

**Comment by plk** [comment]
Can you try the 3.4 dev version? I believe this is already fixed in this version. You will also need biber 2.5.

**Comment by michue** [comment]
Okay, using the dev version `\mkbibnamesuffix` works as expected, but is overwriten by a following definition of `\mkbibnameaffix`, such that the above MWE still yields the same result. (I assume, this has something to do with aliases)

But one thing I wonder about: When swapping the order of the both `\renewcommand`, the suffix is still printed bold. Only deleting the definition of `\mkbibnameaffix` yields the desired result of an italic suffix.

**Comment by michue** [comment]
Updated MWE:
```TeX
\documentclass{report}

\RequirePackage[
   % Use the newest backend: biber
   backend=biber,
   % Use alphabetic style
   style=alphabetic
]{biblatex}

\begin{filecontents}{bibliography.bib}
@Article{Duckhausen,
author =    {von Duckhausen, Sr, Dagobert},
title =     {Lowercase Title},
journaltitle = {Miscellaneous Journal},
date =      {2016-05-10}
}
\end{filecontents}}
% Add the bibliography as only source
\addbibresource{bibliography.bib}

% Uncomment this to get a bold suffix
%\renewcommand*{\mkbibnameaffix}{\textbf}

% The format can be changed using \mkbibnamesuffix, but is overwritten by a preceeding or following \mkbibnameaffix
\renewcommand*{\mkbibnamesuffix}{\textit}

\begin{document}
\chapter{First Chapter}
Citation of working entry \cite{Duckhausen}.

% Suffix will be printed in bold font
\printbibliography
\end{document}
```

**Comment by plk** [comment]
Is this really now a live issue? You will see in the log that there is a warning about `\makebibnameaffix` - the deprecation code is a bit complicated to retain backwards compat but I don't see anyone using both in a document, especially given that there are deprecation warnings in the log.

**Comment by michue** [comment]
It's no issue for me... just something I stumbled over while testing the new version.
Therefore I consider this as _"will be fixed in the next version"_
