### ISSUE TITLE
Before the common era (BCE/BC) and common era (CE/AD) date support.

### ISSUE THREAD

**Issue by JohnLukeBentley** [plk/biblatex#422]
## Overview

A request to add common era (BCE/BC) and common era (CE/AD)  support for all date fields.  This would entail supporting various input and display options.

My examples will focus on using `origdate` even though the suggestion applies to all date fields. For the most common scenario, when you need to reference an ancient work, is via a modern publication. 

I'm also illustrating this with  the `biblatex-chicago` package. I appreciate that is not biblatex native. However, it makes use of the biblatex native `origdate`, a field which none of the biblatex native styles make use of.

## Example
 Given

```biblatex
@book{plato_2004_republic,
	origdate = {-0379}, % Negative ISO 8601 dates are one more than the equivalent BCE form. 
	date = {2004-09-15},
	author = {Plato},
	title = {Republic},
	translator = {Reeve, C. D. C.},
	publisher = {{Hackett Publishing Company, Inc.}},
	location = {{Indianapolis}},
	edition = {3rd edition},
	isbn = {0-87220-737-4},
	pagetotal = {392},
	timestamp = {2016-05-17T14:15:38Z},
	langid = {english}
}
```
... and using ...

```latex
% "RequirePackage" when writing packages or classes, "UsePackage" when writing documents. 
\RequirePackage[authordate,
				backend=biber,
				sorting=nyt,
				backref=false,
				alldates=iso8601,
				cmsdate=on,
				annotation=true]{biblatex-chicago}
```

I might get, if this feature was supported ....

Citation:

From `Lorem ipsum dolor sit amet \autocite{plato_2004_republic}.` and with the `biblatex-chicago` package, using their `authordate` style with `cmsdate=on`:

> Lorem ipsum dolor sit amet (Plato 380 BCE). 

With `{biblatex-chicago}`'s option `cmsdate=both` I'd get

> Lorem ipsum dolor sit amet (Plato [380 BCE] 2004). 

Reference:

From  `\printbibliography`
> Plato. 380 BCE. *Republic*. 3rd edition. Translated by C. D. C. Reeve. Indianapolis: Hackett Publishing Company, Inc., 2004-09-15. isbn: 0-87220-737-4.

### Date parsing 

In my example, for the `origdate` field, I've chosen to use the ISO 8601 date format for BCE dates https://en.wikipedia.org/wiki/ISO_8601#Years

> To represent years before 0000 or after 9999, the standard also permits the expansion of the year representation but only by prior agreement between the sender and the receiver.[11] An expanded year representation [±YYYYY] must have an agreed-upon number of extra year digits beyond the four-digit minimum, and it must be prefixed with a + or − sign[12] instead of the more common AD/BC (or BCE/CE) notation; by convention 1 BC is labelled +0000, 2 BC is labeled -0001, and so on.

That is, in my example I use `origdate={-0379}` which would display as "380 BCE". That is, take minus one away from "-0379" then return the absolute to get "0380", before applying any further formatting (e.g. remove the leading zero and concatenate "BCE").

An argument could be made that biblatex should also support parsing something like `origdate={380 BCE}`. But I'd suggest if we wanted to support that we'd also want to support the ISO 8601 formatting as well, ISO 8601 being the priority to support given that it is *the* standard for representing dates.

### Abbreviations and periods: "BCE" or "B.C.E."?
The Chicago Manual of Style has this to say 

> 10.4 Periods with abbreviations ... 
> 3. Use no periods with abbreviations that appear in full capitals, whether two letters or more and even if lowercase letters appear within the abbreviation: VP, CEO, MA, MD, PhD, UK, US, NY, IL (but see rule 4). 

http://www.chicagomanualofstyle.org/16/ch10/ch10_sec004.html [paywall]

In it's [Q&A section on Abbreviations](www.chicagomanualofstyle.org/qanda/data/faq/topics/Abbreviations.html) [Free to access] it uses no periods when talking about these date abbreviations

> Q. Do you recommend the use of BCE (Before the Common Era) and CE (Common Era) instead of BC and AD?

Therefore it would be conventional to display these abbreviations without periods. E.g. Do this: "BCE"; Not this: "B.C.E.".

### BCE "before the common era" or BC "before Christ"?

And on that question my own preference is to use BCE, given both it's increasing popularity (since the 1980s) and it's repudiation of ties to Christianity. But making available an override switch to use "BC" will probably be necessary. For example for Christian writers who want to assert the Christian dating system.

More details at https://en.wikipedia.org/wiki/Common_Era 

### Are CE "Common era" (and AD "anno Domini") needed?

My own preference is just to use ISO 8601 dates. E.g.

Citation: 
> Lorem ipsum dolor sit amet (Epictetus 0125). 

Reference:
> Epictetus. 0125. *Enchiridion*. Translated by P. E. Matheson. 1916. http://www.sacred-texts.com/cla/dep/dep102.htm.

Others might prefer the traditional "125", without the leading zero. But whether an author wants the leading zero or not, they might still prefer an explicit "CE" (or "AD"), as in "0125 CE", to make it explicit to readers that this is not "0125 BCE".

That argues in favour of having a *.bib date field that accepts formats like

```
origdate={0125 CE}
origdate={0125 AD}
```

Therefore I propose all of the following formats be parsable ...

For 380 BCE
```latex
origdate={-0379} % Negative ISO 8601 dates are one more than the equivalent BCE form. 
origdate={0380 BCE}
origdate={0380 BC}
```

For 0125 CE
```
origdate={0125}
origdate={0125 CE}
origdate={0125 AD}
```

Of course, there should be the usual support for more specific dates, supplying a month, or a month and day. e.g.

```
origdate={-0379-06}
origdate={0380-06-23 BCE}
```

And there be the following kinds of display options: [-][Y]{1,4} [BCE|BC|CE|AD]

E.g.
```latex
-0379 % Negative ISO 8601 dates are one more than the equivalent BCE form. 
0380 BCE
0380 BC
380 BCE
380 BC

0125
0125 CE
0125 AD
125
125 AD
```

### What about circa dates?

That's an important and related issue. But it is a separate issue requiring a separate ticket.

Edit: Ninja edits for clarity; changed some of my examples wrongly displaying "379 BCE" when I intended "380 BCE".

**Comment by plk** [comment]
I have tried to implement true ISO8601 support in the past but the problem is that biblatex date formats have one crucial difference to ISO8601 which is that missing month/day (e.g. `date = {2010}`) should be undefined but ISO8601 dictates that they default to "1". Modules implementing ISO8601 for perl enforce this and so I have always implemented basic date parsing myself. To properly implement era support, I should really use a real ISO8601 module ... I can look into it again and see if there have been any changes.

**Comment by JohnLukeBentley** [comment]
Thanks Philip (I presume).

To repeat your essential points in my own words:

* Perl modules implementing ISO8601 strictly enforce the ISO8601 standard  [as they should].
* The ISO8601 standard allows for the entry of a year only, e.g. "2010", but defaults the absent month and day to "1" each (In effect "2010" gets treated as "2010-01-01").
* In a Biblatex context, in the case of the entry of a year only e.g. `date = {2010}`, the month and date need to be undefined.
* Quite apart from the issue of implementing Eras, you've found your custom datetime parsing solution hacky, in avoiding a Perl ISO8601 module due to the prior issues. So if you where to revisit datetime parsing, for a purpose like supporting Eras, you'd rather refactor the custom datetime parsing to use a Perl ISO8601 library - in order to make the code more robust.

If I've understood you correctly, all that is laudable. To think more about the implementation issue ...

The ISO8601 spec writers could well have had in mind that they want to support a popular way of representing datetimes internally to a programming language. Namely, as an ordinal.

If you represent a datetime as an ordinal, and you want to use that number to preserve sort ordering for most cases, then you need all dates, including dates where only the year is defined, to get default values for those parts that are undefined.

I know JavaScript is one language where dates are so represented internally as an ordinal. Specifically, as a number of milliseconds relative to zero at 1970-01-01 00:00:00 UTC. 

I don't know Perl, but from a look at a random Perl DateTime page, http://perlmaven.com/datetime (which, among other things, references https://metacpan.org/pod/DateTime), that looks to be the case in Perl also ...

> The epoch returns the number of seconds (of the given date) since the "epoch" which is 1970.01.01 00:00:00.

I've done some design spiking in JavaScript. Indeed I can reproduce the problem you describe ...

```javascript
var myDateYearOnly = new Date("2016");
var myDateFirstOfJan = new Date("2016-01-01");
```
Output ...
```
myDateYearOnly      2016-01-01T00:00:00.000Z
myDateFirstOfJan    2016-01-01T00:00:00.000Z
```

So natively JavaScript (and presumably Perl) doesn't store the inputted precision of the datetime. As a result the difference between "2016" and "2016-01-01" is lost.

Unless you can find a native or third party Perl Module to that also stores the inputted precision it might be that you'll have to continue to use custom date time handling. And one approach to doing that would be (I haven't examined your existing code, you may already be doing this kind of thing) to create a CustomDateTimeClass. In Javascript I've banged up a crude Example

```javascript
var DatePrecisionEnum = {
  year: 1,
  month: 2,
  day: 4,
  full: 8,
};

function CustomDateTimeClass(date, precision, expressAsEra) {
  
  this.realDate = date || new Date();
  this.precision = precision || DatePrecisionEnum.full;
  this.expressAsEra = expressAsEra || false;
  this.toString = toString;
  
  function toString() {
    var dateString = '';
    var eraString = '';
    switch (this.precision) {
      case DatePrecisionEnum.year:
        // format() as a custom function, not native javascript.
        dateString = this.realDate.format("yyyy");
        break;
      case DatePrecisionEnum.day:
        dateString = this.realDate.format("yyyy-MM-dd");
        break;
      case DatePrecisionEnum.full:
        dateString = this.realDate.toISOString();
        break;
      default:
        throw new Error('Unexpected case reached.');
    }
    if (this.expressAsEra && this.precision != DatePrecisionEnum.full) {
      eraString = (this.realDate.getFullYear() > 0) ? ' CE' : ' BCE';
    } 
    
    return dateString + eraString;
  } // toString
  
} // CustomDateTimeClass

// Call it
var platoRepublicWritten = new CustomDateTimeClass(
      new Date("-000379"), 
      DatePrecisionEnum.year, 
      true);

// Output
380 BCE
```

The essential advantage of this approach is that because you store a "realDate" as a property of the class, you can apply existing datetime (native or third party) Perl module functions to it. But you also get to store extra data against that realDate, in our case precision (the year only, year-month, year-month-date, etc) and whether the user intents this date to be displayed in Era format.

Naturally you'll have to flesh it out to provide all the DateTime detail you do: Date ranges and exposing to authors an interface for getting at parts of the date. And you'd also have to do some pre parsing ... E.g. Chopping up "-000379 BCE" in  "date={-000379 BCE}" (or "date={-000379 Era}" ?).

An incidental tip from my playing in Javascript (which might also apply to Perl). Negative dates required 6 places in addition to the negative sign. So "-000379" would parse and "-0379" would fail. That seems driven by what ISO 8601 requires ...

> An expanded year representation [±YYYYY] must have an agreed-upon number of extra year digits beyond the four-digit minimum, and it must be prefixed with a + or − sign
https://en.wikipedia.org/wiki/ISO_8601

In summary: if you can't find a native or third party Perl module to do everything, and I suspect you won't, then I commend to you (noting I don't know Perl):

* Creating a CustomDateTimeClass that stores realDate; precision; an Era flag; and whatever other data you may need;
* The Perl Module https://metacpan.org/pod/DateTime which has several Era formatting commands.
* The Perl Module https://metacpan.org/pod/DateTime::Format::ISO8601 for ISO8601 parsing.
* A random blogpost which looks like it might be a good reminder on how to do it all ... http://perlmaven.com/datetime. It also points to other DateTime modules.

Note I'll also be posting a request for Biblatex support for circa and other date ambiguities, as a seperate but related issue. The approach I've outlined above (a CustomDateTimeString) seems suitable for accommodating this too.

**Comment by plk** [comment]
This is in progress. It needs quite a lot of internal changes before the era functionality can be implemented as it needs sorting algorithm changes too which are quite hard. A couple of years ago I looked at all relevant Perl modules and had discussions with the DateTime maintainers about this but little happened. However, now I have subclassed `Date::Format::ISO8601` with a new `biber` module which provides the missing functionality for detecting missing data in the input and am refactoring the internals to use this module.

**Comment by JohnLukeBentley** [comment]
Outstanding Philip. Thanks.

Yeah, it sounds like the refactoring will be a big task and potentially take a great deal of time.

A heads up that from the documentation for https://metacpan.org/pod/DateTime::Format::ISO8601 it doesn't look like negative years are supported. Maybe negative year parsing is something you'll want to support in your child class (??).

I've just posted the issue: [Circa dates, circa date ranges, and question marked dates. #427](https://github.com/plk/biblatex/issues/427).

**Comment by plk** [comment]
I notice that `Date::Format::ISO8601` complies with ISO8601v2000 and not ISO8601v2004. This is why it doesn't deal properly with negative years. I will adapt the subclass for v2004 and have this working in development.

**Comment by JohnLukeBentley** [comment]
You are making short work of it. Great stuff.

Yes, Perl `DateTime` looks full featured.

It sounds like you have it in hand and everything is falling into place, despite the limitations of `Date::Format::ISO8601`. But if you come across any Date/time design issues that you'd like to bounce around with another, feel free to post back. I'll be happy to serve as a sounding board.

**Comment by plk** [comment]
Please try biblatex 3.5/biber 2.6, both on SF in their respective development folders. All of these requirements are now implemented. There are new localisation strings for both secular and christian strings and there are tests for authors to determine if a date came with BCE era. ISO8601v2004 formats are supported. See the PDF manual, section 2.3.8.

**Comment by JohnLukeBentley** [comment]
Thanks Philip. Outstanding work. I see your similar note about circa and uncertain dates.

However, I've not been able to get any results. I expect either:

* I'm not installing the development files correctly; and/or
* (Misunderstanding that) the support you've implemented is so far only for style authors, and I have to start hacking at a style to see results.

## Installation

I don't mean to drag you into an end user support session but on the installation side I've done the following (I'm on Win 10 Pro 64 bit, MikeTex, using TexStudio, generaly compiling with pdfLatex).

Updating to Biber 2.6:

* Downloaded: https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/development/binaries/Windows/biber-MSWIN64.zip.
* Unzipped and installed biber.exe at C:\Program Files\MiKTeX 2.9\miktex\bin\x64\biber.exe (old exe renamed to `biber.exe.back`)
* In Powershell `biber -v` returns `biber version: 2.6 (beta)`. So that looks good.

Updating to Biblatex 3.5:

* Downloaded: https://sourceforge.net/projects/biblatex/files/development/biblatex-3.5.tds.tgz
* Unzipped and copied all folders (biber, bibtex, doc, tex) into C:\Program Files\MiKTeX 2.9 . That is, thereby overwriting existing files.
* I then use MikTex Options (admin) to `Refresh FNDB` and `Update Formats`.
* However using MikTex Package Manager (Admin) and looking at the properties for the `biblatex` package I'm only getting version 3.4. **This seems like a clue**.

... And my minimum working example is not formatting BCE dates.

```latex
\documentclass{article}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{plato_republic,
	location = {{Indianapolis}},
	edition = {3rd edition},
	title = {Republic},
	isbn = {0-87220-737-4},
	pagetotal = {392},
	timestamp = {2016-05-29T05:23:10Z},
	langid = {english},
	publisher = {{Hackett Publishing Company, Inc.}},
	author = {Plato},
	translator = {Reeve, C. D. C.},
	date = {380 BC},
	origdate = {-390}
}
\end{filecontents}

\usepackage[citestyle=authoryear,bibstyle=authoryear]{biblatex}
			
\addbibresource{\jobname.bib}
\begin{document}
	Lorem \autocite{plato_republic}
	\printbibliography
\end{document}
```

I get

> Lorem (Plato 380)
> ...
> Plato (380). Republic. Trans. by C. D. C. Reeve. 3rd edition. Indianapolis: Hackett Publishing Company, Inc. 392 pp. isbn: 0-87220-737-4.

I also can't get your 96-dates.tex to work.

Am I doing something obviously wrong?

## Biblatex native styles.

Should I expect my minimum working example to return "380 BCE" formats, for the native authoryear styles; or should I be modifying an existing style using the commands in "4.6.2 Stand-alone Tests" of the PDF Manual?

**Comment by plk** [comment]
The standard style don't use this as yet as it's not clear about this year. The goal would be to get the 96-dates test to work first (which should be format with lualatex or xelatex and biber). However, it looks like you don't have the biblatex part installed yet - I don't use MikTeX so I suspect you unpacked the tds into the wrong place? Can you ask on TSE - that's a more likely place to get that aspect sorted out.

**Comment by JohnLukeBentley** [comment]
Given the discussion occurring in [Circa dates, circa date ranges, and question marked dates. #427 ](https://github.com/plk/biblatex/issues/427) I suggest closing this ticket and continuing both Era and Circa discussions there.
