### ISSUE TITLE
Change the default relatedoptions on a per type basis

### ISSUE THREAD

**Issue by dcpurton** [plk/biblatex#424]
It would be useful to have a way to change the default `relatedoptions` on a per type basis.

e.g., consider this pair of bib entries:

```TeX
@mvcollection{PG,
  title = {\mkbibemph{Patrologia Graeca}},
  editor = {Migne, J.-P.},
  volumes = {162},
  location = {Paris},
  date = {1857/1886},
  shorthand = {PG},
  options = {useeditor=false},
  sortkey = {Patrologia Graeca}
}
@classictext{gregory:orationestheologicae,
  author = {{Gregory of Nazianzus}},
  title = {Orationes theologicae},
  volume = {36},
  related = {PG}
}
```

I'm aiming for output like this:

`\autocite[4|12c]{gregory:orationestheologicae}`
<html>&#8195;&#8195;&#8195;</html>6. Gregory of Nazianzus, *Orationes theologicae* 4 (PG 36:12c).

`\printbiblist{shorthand}`
<html>&#8195;&#8195;&#8195;<html>PG<html>&#8195;&#8195;&#8195;</html>Patrologia Graeca. Edited by J.-P. Migne. 162 vols. Paris, 1857–1886

`\printbibliography`
Patrologia Graeca. Edited by J.-P. Migne. 162 vols. Paris, 1857–1886.

Now, much of this I can control in my style. I can set the `skipbib` option by default for `@classictext`

```TeX
\ExecuteBibliographyOptions[classictext]{skipbib}
```

And I can set an appropriate `relatedtype` using `\DeclareSourcemap` so the related entry is formatted correctly.

But if I try and set `relatedoptions={skipbib=false,skipbiblist=false}` for all `@classictext` entries using `\DeclareSourcemap` to ensure that `PG` appears in the list of shorthands and bibliography, I lose `useeditor=false`, and `PG` is incorrectly formatted in the bibliography and list of shorthands. There seems to be no way that I can access the `options` field of the entry pointed to by `related` in order to manually incorporate them into a final `relatedoptions`.

What is needed is something like this:

```TeX
\ExecuteBibliographyRelatedOptions[<entrytype, ...>]{<key=value, ...>}
```

By default, this would be set to `dataonly` for everything, e.g.,

```TeX
\ExecuteBibliographyRelatedOptions{dataonly}
```

But in my example above, I could include:

```TeX
\ExecuteBibliographyRelatedOptions[classictext]{dataonly,skipbiblist=false,skipbib=false}
```

Thoughts?

(Of course, I know that the desired output can be achieved at present simply by including all required options in `relatedoptions` in the `bib` file, but this is potentially confusing for an end user because it's not immediately apparent why you must include `useeditor=false` when this already appears in the `options` field of the clone source.)

**Comment by plk** [comment]
I have had only a quick look at what you are doing but isn't what you need just the `append` sourcemap funtionality so that only append to your `relatedoptions`? I believe there is such an example in the `biblatex` doc.

**Comment by maieul** [comment]
@dcpurton may I make a intervention in your problem? It seems me that, for the case of the PG, using the series field and short series field is more semanticly correct. 

For my own use, what I do is in my style file:

`````
\renewbibmacro*{series+number}{%
  \iffieldundef{shortseries}{\printfield{series}}{\printfield{shortseries}}%
  \setunit*{\addspace}%
  \printfield{number}%
  \newunit}
\DeclareBibliographyDriver{shortseries}{\printfield{series}}
`````

And to print the abreviation
````
\printbiblist{shortseries}
````

**Comment by dcpurton** [comment]
@maieul, you are right. The SBLHS does indeed state that it treats Patrologia Graeca as a series, not a multi-volume work (although it acknowledges the ambiguity). However, when the handbook shows what should appear in the list of abbreviations it includes full data from the book, not just Patrologia Graeca. This means that in the list of abbreviations, it functions much more like a multi-volume work (except with a roman title instead of emphasised).

If I use `series` and `shortseries` then I will get:

<html>&#8195;&#8195;&#8195;<html>PG<html>&#8195;&#8195;&#8195;</html>Patrologia Graeca

If I use `series` and `shorthand` then I will get:

<html>&#8195;&#8195;&#8195;<html>PG<html>&#8195;&#8195;&#8195;</html>Migne, J.-P., ed. 162 vols. Patrologia Graeca. Paris, 1857–1886

Hence I opted to use `title` with `\mkbibemph`.

@plk, I need to give this some more thought. It might not be worth doing anything. `append` doesn't do what I want.

**Comment by maieul** [comment]
I am very convinced that the SBLS is not good for patristic studies, as it can't manage some specific case, ad old book edited in article� but that is not the question here.

Maybe a solution could be to do something like

````
\DeclareBibliographyDriver{shortseries}{\fullcite{\thefield{shortseries}}
````

If you really want to keept PG as a `@mvcollection` (and for my it should be a `@mvbook`), you should use, I think, crossref/xref mechanism instead of related mechanism.

**Comment by dcpurton** [comment]
@maieul, if you are willing, can you offer some advice on these for me? It's not my area at all, so I'm just making best guesses based on the SBL handbook of style. Rather than using this thread, I'll start one for `biblatex-sbl`.
