### ISSUE TITLE
distinction between reprint and reedition

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#425]
The `orig<field>` allow us to show the original publication of a field.

Hoewever, standard style could make the distinction between reprint and reedition, with a dedicated field used as `\bibstring` instead of the default origpubin.

**Comment by JohnLukeBentley** [comment]
I'd just thought I'd mention what one style guide, *The Chicago Manual of Style, 16th Edition* has to say on this

> 1.26 What constitutes a new edition?

> Edition (as opposed to impression, or printing) is used in at least two senses. (1) A new edition may be defined as one in which a substantial change has been made in one or more of the essential elements of the work (e.g., text, notes, appendixes, or illustrations). As a general rule, at least 20 percent of a new edition should consist of new or revised material. A work that is republished with a new preface or afterword but is otherwise unchanged except for corrections of typographical errors is better described as a new impression or a reissue; the title page may include such words as “With a New Preface.” (2) Edition may be used to designate a reissue in a different format—for example, a paperback, deluxe, or illustrated version, or an electronic edition of a printed work—or under the imprint of a different publisher. A new edition is best designated on the title page: Second Edition, Third Edition, and so forth. Such phrases as “revised and expanded” are redundant on the title page, since the nature and extent of the revision are normally described in the prefatory material or on the cover.

http://www.chicagomanualofstyle.org/16/ch01/ch01_sec026.html (paywall)

> 14.150 New impressions and renewal of copyright

> The publication date must not be confused with the date of a subsequent printing or a renewal of copyright. Such statements on the copyright page as “53rd impression” or “Copyright renewed 1980” should be disregarded.

http://www.chicagomanualofstyle.org/16/ch01/ch01_sec026.html (paywall).

So generally citations and bibliographic entries target the edition, and disregard any reprint version of an edition. However, elsewhere Chicago mentions how you could include both edition and reprint information ...

> 14.119 Reprint editions and modern editions

> Books may be reissued in paperback by the original publisher or in paper or hardcover by another company. In bibliographic listings, if the original publication details—particularly the date—are relevant, include them. If page numbers are mentioned, give the date of the edition cited unless pagination is the same. The availability of a paperback or an electronic version (see 14.166), the addition of new material, or other such matters can be added as needed. Modern editions of Greek, Latin, and medieval classics are discussed in 14.256–66; modern editions of English classics in 14.267–68; online editions of books in 14.166–69.

> >  22\. Ernest Gowers, *The Complete Plain Words*, 3rd ed. (London: H.M. Stationery Office, 1986; Harmondsworth, UK: Penguin Books, 1987), 26. Citations refer to the Penguin edition.
>
> > 23\. Jacques Barzun, *Simple and Direct: A Rhetoric for Writers*, rev. ed. (1985; repr., Chicago: University of Chicago Press, 1994), 152–53.
> 
>>  Bernhardt, Peter. *The Rose’s Kiss: A Natural History of Flowers*. Chicago: University of Chicago Press, 2002. First published 1999 by Island Press.
>> Emerson, Ralph Waldo. *Nature*. 1836. Facsimile of the first edition, with an introduction by Jaroslav Pelikan. Boston: Beacon, 1985.
>>  Fitzgerald, F. Scott. *The Great Gatsby*. New York: Scribner, 1925. Reprinted with preface and notes by Matthew J. Bruccoli. New York: Collier Books, 1992. Page references are to the 1992 edition.
>>  National Reconnaissance Office. *The KH-4B Camera System*. Washington, DC: National Photographic Interpretation Center, 1967. Now declassified and also available online, http://www.fas.org/irp/imint/docs/kh-4_camera_system.htm.
>> Schweitzer, Albert. *J. S. Bach*. Translated by Ernest Newman. 2 vols. 1911. Reprint, New York: Dover, 1966. [Italics original]

http://www.chicagomanualofstyle.org/16/ch14/ch14_sec119.html (paywall)

Personally I have no motive for Biblatex to support reprint information. However, observe that Biblatex already has an `annotation` field which could be used, perhaps less than ideally, to specify reprint info.

The Bblatex `annotation` field comes from the Zotero `notes` field, if you happen to use that software. I imagine most reference management software has an analogous translation to the Biblatex '`annotation` field

**Comment by maieul** [comment]
the chicago style is an american convention. french use are different�

annotation is for personnal annotation on the works, not for meta data

**Comment by JohnLukeBentley** [comment]
Yes, as I wrote, Chicago is one style guide (among many). Many Americans use style guides apart from Chicago. The point in providing examples from a style guide is to show the possible forms that reprint metadata might take and how important reprint metadata is regarded.

It would be helpful, for example, if you were to provide examples from whatever French style guide you have in mind. 

According to the [biblatex package documentation](http://mirrors.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf)

> annotation .... This field may be useful when implementing a style for annotated bibliographies.
It is not used by all standard bibliography styles.

If your chosen biblatex style supports it you could use `annotation` for reprint metadata or almost any other kind of metadata (not already provided for with existing fields).

**Comment by aboruvka** [comment]
The standard styles aren't intended to exhaustively cover all of these special cases. You can use existing features with biber to obtain your desired results.
