### ISSUE TITLE
Trailing space in `\cite{}` argument with `defernumbers = true` makes all bibliography labels `0`

### ISSUE THREAD

**Issue by CasperVector** [plk/biblatex#429]
As the title:

```
\documentclass{article}
\usepackage{filecontents}
\usepackage[backend = biber, defernumbers = true]{biblatex}
\addbibresource{test.bib}

\begin{filecontents}{test.bib}
@book{test,
    author = {Author},
    title = {Title},
}
\end{filecontents}

\begin{document}
    \cite{test} \cite{pia } % "pia " replaced with "test " leads to the same output.
    \printbibliography
\end{document}
```

**Comment by plk** [comment]
I am tempted to class this as a user error. I'm not sure there is much we can do about this unless @josephwright has any ideas? The `\cite` stuff is quite heavily nested and I'm not sure stripping spaces is feasible. Perhaps we could just emit a fatal error instead?

**Comment by CasperVector** [comment]
This is definitely a user error, but the symptom is really obscure. I think a noisy warning might be appropriate :)

**Comment by plk** [comment]
@josephwright - can you see a way to emit a warning in general when any cite key contains a space? This would need to deal with CSV lists in cite commands which are allowed and which I assume can have leading/training spaces around the commas.

**Comment by DigNative** [comment]
I would like to add here that also undefined citations, i.e. if an entry in your bibliography databases is missing, leads to this issue when `defernumbers=true` is set.

**Comment by dfunke** [comment]
I encountered the same error as @DigNative, there should also be a warning emitted saying that no numbers could be assigned because of this

**Comment by plk** [comment]
A special warning is now generated for  undefined citations when `defernumbers=true` saying that labels cannot be generated and it says which citation needs correction.
