### ISSUE TITLE
Hack to filter duplicates fails in latest version

### ISSUE THREAD

**Issue by solehill** [plk/biblatex#430]
The code in [this answer on stackexchange](http://tex.stackexchange.com/a/58312) used to work to avoid repeating entries already contained in a previous refsegment. However, it seems to have no effect in the latest biblatex version.

The code is a bit of a hack and there may be more elegant ways to achieve the same thing, nevertheless, I don't understand why it should suddenly fail to work. Maybe it is related to the change from ifempty to ifdefvoid in version 3.4? I don't really know, but it would be nice to get this working again so my documents compile as intended.

**Comment by plk** [comment]
Looking quickly at the code, I see no reason why this wouldn't work but patching internals is never really a supported method to do anything. Can you ask this on TSE as I think you'd get a faster response as I'm in the middle of some biblatex development.

**Comment by solehill** [comment]
Sure, no worries.

Meanwhile, I at least figured out what caused the change in behavior. It was the addition of line 7847 in commit dab4c70 from Apr 13. Removing that one line fixes my problem, but I understand that it was put in to fix something else (namely #406 and #179).

**Comment by solehill** [comment]
I think I should close this here.

Nevertheless, although it is a bit of niche requirement, it would be nice to have this as an official feature. A simple option/flag that switches the behavior from including everything cited in the segment to only including entries that haven't been cited in previous segments. I would offer a patch, but I'm probably not sufficiently familiar with the code yet to produce one.

To be honest, I already struggle to understand why `\blx@auxwrite\@mainaux{}{\string\abx@aux@segm{\the\c@refsection}{\the\c@refsegment}{\detokenize{#1}}}%` has to be outside of the `\ifinlistcs{#1}{blx@segm@\the\c@refsection @\the\c@refsegment}` test rather than inside like the `\listcsgadd` command. So I should probably just leave this to the experts :-)
