### ISSUE TITLE
Missing delimcontext cbx@textcite

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#432]
Via [Unwanted comma between author and year using citet command](http://tex.stackexchange.com/q/312539/35864) on TeX.SX.

The two pass-structure of some `\textcite` implementations makes the delimiter context `cbx@textcite` necessary, it should behave exactly like `textcite`. Is there a way to alias the two? Otherwise we would need to add some lines to `biblatex.def` and warn the users about this special context in the docs.

**Comment by plk** [comment]
This is tricky. I don't like this using of `\DeclareCiteCommand` for internal commands like this. The best solution would be to stop doing this. It's not clear to me what `\textcite/\cbx@textcite` complication is actually doing - @josephwright - do you have any insight?

**Comment by moewew** [comment]
As far as I can see this two-pass structure allows to collect some additional information about the citation list before actually processing it. In `authoryear-icomp` that comes down to calculating `textcitetotal` for `\iffinalcitedelim`. Maybe that could be solved differently.

Another solution instead of aliasing would be to inject a manual call to `\delimcontext{textcite}` into the pre-code hook of `\cbx@textcite` to override the `cbx@textcite` context with `textcite`. (Of course custom styles would then have to follow suit.)

**Comment by plk** [comment]
Ok, I think this would be messy to solve in that way. I added a `\DeclareDelimcontextAlias` command to allow for context aliasing. The relevant styles now use this to set the alias for this case. This is in 3.5 DEV.

**Comment by moewew** [comment]
It works brilliantly, thank you very much.

Would it make sense to move the `\DeclareDelimcontextAlias{cbx@textcite}{textcite}` line to `biblatex.def` so other (custom) styles can benefit from it as well?

**Comment by plk** [comment]
That's what I did originally but I don't want to pre-judge whether such macro names would be used in custom styles for completely different reasons so I localised the alias to where it was needed. This also makes it more obvious *that* it's needed for people creating custom styles by copying existing ones.

**Comment by moewew** [comment]
Fair enough, though I think it is quite safe to assume that if `cbx@textcite` is used it is in the context of a `textcite` and thus the `textcite` delimcontext should apply.

**Comment by plk** [comment]
I think so too but I've been caught out by this sort of thing before ...
