### ISSUE TITLE
Pseudonymy in format of the name

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#433]
In antiquity, many books are placed under the name of a famous author. 
Until now, I mark them in the following form:
````
@book{XXX,
  Author={Pseudo-Augustin}
}
`````

However, as I have seen yo works on the form of the name, should be it possible to include the pseudepigrahic remarks.

It could provide to user setting like:
- typeset on the form `Pseudo-Author` or `Author (Pseudo)`
- chose if the pseudo-author must be:
-* printed in the middle of author work
-* printed in a entry call "pseudo-xxx"
-* printed in the end of the author work.

The pseudepigraphical status could be marked as dubious, with a question mark.

**Comment by plk** [comment]
You should be able to do this with the "Data Annotations" feature of 3.4+ - that's exactly what it was implemented for in fact. See section 3.6 in the manual.

**Comment by plk** [comment]
Alternatively, you could defined a custom name part "pseudo" - see the `93-nameparts` example file that comes with 3.5 DEV.

**Comment by maieul** [comment]
Ok, I will look. But for all the setting, I suppose it won't be added in the core ? In this case I will produce a "biblatex-pseudepigraph-works" to provides these setting easily.

**Comment by plk** [comment]
It's unlikely to be added to the core as it's too specialised and it should be possible all in a style.

**Comment by maieul** [comment]
ok
