### ISSUE TITLE
Getting the hash of a name field outside of \DeclareNameFormat

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#438]
According to biblatex handbook, the `hash` of of names can be get only on a `\DeclareNameFormat` command. Should it be possible to ad feature like `\hashname{<field>}` to be able to get it outside of a \DeclareNameFormat? 

In order to solve https://github.com/plk/biber/issues/128 without using `\printname`, which could make problem with `\setunit*`.

Maybe, for example, any `namefield` could have it own `xxxhash` produced by biber:

`````
\name{author}{1}{}{%
        {{hash=d9bafd434661af3e49fc660ccc58b415}{%
           family={{Prieur\bibnamedelimb de\bibnamedelimb Bolleville}},
           family_i={P\bibinitperiod}}}%
      }
      \name{realauthor}{1}{}{%
        {{hash=6888e07ac8440b3bea794b7843c4229c}{%
           family={Simon},
           family_i={S\bibinitperiod},
           given={Richard},
           given_i={R\bibinitperiod}}}%
      }
\strng{authorhash}{d9bafd434661af3e49fc660ccc58b415}
\strng{realauthorhash}{6888e07ac8440b3bea794b7843c4229c}
`````

**Comment by plk** [comment]
Please try 3.5/2.6. Now, for every name `X`, there is a field `Xnamehash` and `Xfullhash` available. The usual `namehash` and `fullhash` fields for the labelname are still available too.

**Comment by maieul** [comment]
the new hash system works. Thanks!
