### ISSUE TITLE
Crossref: block inheritance of a date range when the child has already a date

### ISSUE THREAD

**Issue by gracile-fr** [plk/biblatex#439]
Via [date range inherited from parent with crossref](http://tex.stackexchange.com/q/313574/82783)

In the following MWE, the `@article` has a `year` and the `@mvbook` has a date range, i.e. a `year` and an `endyear`. As a consequence, the article inherits a `endyear` from its parent but keeps its existing `year`, which is not overwritten (documentation § 4.5.11). (Also, in this specific example, because the new date range is inconsistent (1983-1983), Biblatex dismisses the `year` and only displays the delimiter and the `endyear`.)

I think that it would be more consistent that the child doest not inherit any year parts (year, endyear), when it has already a year. The fact that a multi-volumes book has a date range just reflects the fact that the different volumes have been published along the years, but in most cases each volume has a unique year of publication (not speaking of reprint, new edition, etc.)

````\begin{filecontents}{\jobname.bib}

@mvbook{mvbook,
  location = {London},
  title = {Multivolume},
  volumes = {2},
  author = {Jane Doe},
  date = {1982/1983}
}

@incollection{article1,
  location = {London},
  title = {Article},
  volume = {2},
  booktitle = {Multivolume},
  author = {Jane Doe},
  date = {1983},
  pages = {675--779},
  crossref = {mvbook}
}

\end{filecontents}

\documentclass[12pt,a4paper]{article}
\usepackage[utf8]{inputenc}

\usepackage[T1]{fontenc}

\usepackage{hyperref} % hyperliens PDF
\usepackage[style=verbose-trad2,backend=biber]{biblatex}

\addbibresource{\jobname.bib}

\begin{document}
Lorem ipsum\footcite{mvbook} dolor sit amet\footcite{article1}…


\newpage
\printbibliography
\end{document}
```

**Comment by dcpurton** [comment]
I ran into this too. I agree that it's confusing that date parts are inherited in this way.

**Comment by plk** [comment]
Please try the latest bibaltex 3.5 and biber 2.6 dev versions where I believe this is fixed. Child entries will now never inherit any Xdate parts when they already have any Xdate part already.

**Comment by gracile-fr** [comment]
Fixed thank you very much ! (just a little precision : what does Xdate stand for exactly ?)

**Comment by plk** [comment]
I just mean `date`, `origdate`, eventdate` etc.
