### ISSUE TITLE
\volcites prints \postnotedelim ahead of empty postnotes

### ISSUE THREAD

**Issue by CarlOrff** [plk/biblatex#440]
If I put items without postnote in a `\volcites` list, then the `\postnotedelim` still gets printed with these. See MWE:

    \begin{filecontents}{\jobname.bib}
        @BOOK{van:der:linde:1881,
            author = {van der Linde, Antonius},
            title = {Das erste Jahrtausend der Schachlitteratur (850--1880)},
            date = {1979},
            publisher = {Caissa Limited Editions},
            location = {Yorklyn, DE},
            origdate = {1881},
            origpublisher = {Julius Springer},
            origlocation = {Berlin},
            pagetotal = 112,
            language = {german},
            gender = {sm},
        }
        @BOOK{schmid:ant:1847,
            author = {Schmid, Anton},
            title = {Literatur des Schachspiels},
            date = {1975},
            location = {Leipzig},
            publisher = {Zentralantiquariat der Deutschen Demokratischen Republik},
            origdate = {1847},
            origlocation = {Wien},
            origpublisher = {Carl Gerold},
            language = {german},
            gender = {sm},
        }
        @BOOK{van:der:linde:1874,
            author = {van der Linde, Antonius},
            title = {Geschichte und Literatur des Schachspiels},
            date = {1981},
            publisher = {Olms},
            series = {Tschaturanga. Darstellungen und Quellen zur Geschichte des Schachspiels},
            number = {20},
            location = {Zürich},
            isbn = {3-283-00079-4},
            origpublisher = {Julius Springer},
            origlocation = {Berlin},
            origdate = {1874},
            forword = {Bijl, Christiaan M.},
            language = {german},
            gender = {sm},
        }
    \end{filecontents}
    \documentclass[]{article}
    \usepackage[utf8]{inputenc}
    \usepackage[T1]{fontenc}
    \usepackage[
        style=authoryear,
        backend=biber
    ]{biblatex}
    \addbibresource{\jobname.bib}

    \renewcommand{\multicitedelim}{|}
    \renewcommand{\volcitedelim}{:}
    \renewcommand{\postnotedelim}{!}

    \begin{document}

    \volcites{}{schmid:ant:1847}[]{2}[50--74]{van:der:linde:1874}{}{van:der:linde:1881}
    %%% Schmid 1975!|Linde 1981!Vol. 2:pp. 50–74|Linde 1979!

    \printbibliography

    \end{document}

**Comment by plk** [comment]
@aboruvka - one for you?

**Comment by aboruvka** [comment]
The volume argument is mandatory; it requires a non-empty argument. Otherwise a variety of issues can arise. See for example #263.

As a side note, MWEs should use the `\add*` commands as delimiters, to avoid spurious punctuation.
