### ISSUE TITLE
DeclareStyleSourcemap and RequireBibliographyStyle

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#441]
Please consider the enclosed files.

[pb-stylemap.zip](https://github.com/plk/biblatex/files/318246/pb-stylemap.zip)

There is a .bbx file which call an other .bbx file, to extend it. But as all of them use `DeclareStyleSourcemap`, only the last DeclareStyleSourcemap called is output on the <code>bcf:sourcemap</code> entry of the .bcf file.

**Comment by plk** [comment]
Yes, this will always happen. There are only 3 "levels" of map which are merged, driver (biblatex internal), style and user maps. It would be very complicated to merge multiple style maps.

**Comment by maieul** [comment]
may I suggest an alternative: DeclareStyleSourceMap could take an optional argument, which will identify the rule as unique.

So if we would have

````
\DeclareStyleSourceMap[<something>]{}
\DeclareStyleSourceMap[<something>]{}
````

Only the last `\DeclareStyleSourceMap[<something>]` will be output in the .bcf file, while

````
\DeclareStyleSourceMap[<something>]{}
\DeclareStyleSourceMap[<someotherthing>]{}
````

will be kept. So no need of merging multiple style maps

**Comment by plk** [comment]
Please try the latest 3.5/2.6 - this should allow you to call `\DeclareStyleSourcemap` multiple times and they will be applied in order of definition.

**Comment by maieul** [comment]
I have tried with real case use, and it works. Many thanks !
