### ISSUE TITLE
labelprefix does not allow to use numeric-comp style

### ISSUE THREAD

**Issue by lianne** [plk/biblatex#442]
I updated my TexLive distribution and I understood that the new biber/biblatex platform does not use _prefixnumber_ anymore. Instead the command **\newrefcontext** with the _labelprefix_ option should be used. Anyway in the previous version I used the citation style **numeric-comp** and now I read that with _labelprefix_ only the numeric citation style is allowed. Indeed, by leaving the option **citestyle=numeric-comp** for bib latex and by using _labelprefix_ I get only '0' whenever a cite command appears in the text (while the bibliography is correct). As soon as I modify to the option **citestyle=nuemric** everything works fine, even though I cannot compress the citations.
Is it posible to use both compressed numeric style and labelprefix?

**Comment by plk** [comment]
Please try the 3.5 development version (along with the 2.6 development version of biber, which is required) - I believe that this should be fixed now.
