### ISSUE TITLE
Is iftex a requirement for biblatex?

### ISSUE THREAD

**Issue by koefoed** [plk/biblatex#444]
It appears biblatex [requires](https://github.com/plk/biblatex/blob/c06b268347a9bd263e100479004aadc335e5694e/tex/latex/biblatex/biblatex.sty#L36) the package `iftex`, but it is not listed among the [requirements in the documentation](https://github.com/plk/biblatex/blob/c06b268347a9bd263e100479004aadc335e5694e/doc/latex/biblatex/README#L48).

Should `iftex` be a requirement for biblatex?
Or is it perhaps expected to be available from one of the other requirements?

**Comment by plk** [comment]
Actually it is no longer a requirement as is removed in the dev branch. Thank you for pointing it out.

**Comment by moewew** [comment]
What about the `pdftexcmds` and `xstring` packages? Are they needed? I think they were introduced when playing around with `etextools` and friends. (Not too sure about `xstring`, though.)

**Comment by plk** [comment]
xstring is certainly required and pdftexcmds is not currently needed but it might be soon.

**Comment by moewew** [comment]
So maybe at least `xstring` should be added to the list of required packages?

**Comment by plk** [comment]
Yes, this is done now.

**Comment by moewew** [comment]
Brilliant! Thanks.

**Comment by koefoed** [comment]
Thank you for your quick answers.
