### ISSUE TITLE
EDTF: incorrect in-text citations

### ISSUE THREAD

**Issue by nickbart1980** [plk/biblatex#445]
From the .tex file below, I get incorrect in-text citations, EDTF (but without any minus signs!) rather than CE/BCE format for the Julius Caesar item, and an extra “–0044“ for the other two.

![screen shot 2016-06-25 at 11 47 58](https://cloud.githubusercontent.com/assets/2765811/16356297/54487644-3ac2-11e6-937e-829301200f2f.png)

~~~
\documentclass{article}
\usepackage[autostyle]{csquotes}
\usepackage[backend=biber, style=authoryear, dateera=secular]{biblatex}
\usepackage{fontspec}
\setmainfont{Linux Libertine}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@online{      doe,
  author    = {Doe, John},
  date      = {2015},
  title     = {Title},
}
@online{      jc,
  author    = {Julius Caesar},
  date      = {-0099-07-11/-0043-03-13},
  title     = {My Life},
}
@book{        mos,
  author    = {Mosshammer, Alden A.},
  date      = {2008},
  title     = {The {Easter} Computus and the Origins of the {Christian} Era},
  location  = {Oxford},
  publisher = {Oxford Univ. Press},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}

Blah \autocite{jc, doe, mos}.

\printbibliography

\end{document}
~~~

**Comment by plk** [comment]
This was due to some rather thorny scoping things in compact cites. Was useful in cleaning some things up and putting in tests to catch this. Should be fixed now in latest 3.5. No need to update biber.

**Comment by nickbart1980** [comment]
Great. But months and seasons within the same year don’t look right yet:

![screen shot 2016-06-25 at 21 09 21](https://cloud.githubusercontent.com/assets/2765811/16358855/c81c8b3e-3b10-11e6-86bc-f743627efeb9.png)

~~~
\documentclass{article}
\usepackage[UKenglish]{babel}
\usepackage[autostyle]{csquotes}
\usepackage[backend=biber, style=authoryear, alldates=comp, dateera=secular ]{biblatex}
\usepackage{fontspec}
\setmainfont{Linux Libertine}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@online{      doe,
  author    = {Doe, John},
  date      = {2016-11/2016-12},
  title     = {Title: Months},
}
@online{      roe,
  author    = {Roe, Ron},
  date      = {2016-22/2016-23},
  title     = {Title: Seasons},
}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}

Blah \autocite{doe, roe}.

\printbibliography

\end{document}
~~~

**Comment by plk** [comment]
One of those is an open issue I have at the moment normally cites don't include months which looks odd in a range when only the mont differs. I assue the "comp" format should compress the years in such a case.

**Comment by plk** [comment]
Try again now. Seasons are now treated like months by the `dateabbrev` package option too.

**Comment by nickbart1980** [comment]
Ok, looks good with my MWE as is, i.e. with `UKenglish`:

![screen shot 2016-06-26 at 09 45 09](https://cloud.githubusercontent.com/assets/2765811/16361281/535e2af4-3b7a-11e6-9a42-6991792708d7.png)

… but if I remove this, or use `english`, `USenglish`, or `american` instead, I get:

![screen shot 2016-06-26 at 09 39 48](https://cloud.githubusercontent.com/assets/2765811/16361266/9d404b4e-3b79-11e6-8440-c8ea1fad332b.png)

**Comment by plk** [comment]
Ah, yes, `english.lbx` is the only one which redefined the standard range macros. Should be fixed now.

**Comment by plk** [comment]
Should all be fixed. The facility to suppress ordinals is already in I see - just do this in your preamble:

```
\DefineBibliographyExtras{UKenglish}{%
  \renewcommand*{\mkbibordinal}[1]{#1}%
}
```

**Comment by nickbart1980** [comment]
Ok, looks good, incl. suppressing ordinals.

**Comment by nickbart1980** [comment]
One more in-text citation issue:

~~~
\documentclass{article}
\usepackage{color}
\usepackage[UKenglish]{babel}
\usepackage[autostyle]{csquotes}
\usepackage[style=authoryear, alldates=comp, dateera=secular, datezeros=false, dateeraauto=1000 ]{biblatex}
\usepackage{fontspec}
\setmainfont{Linux Libertine}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@online{      jc,
  author    = {Julius Caesar},
  date      = {-0099-07-11/-0043-03-13},
  title     = {My Life},
}
@online{      tha,
  author    = {{Thales of Miletus}},
  date      = {-0584-05-22},
  title     = {I’m predicting a solar eclipse for today =
               Wed 28 May 585 BCE Julian},
}
\end{filecontents}
\addbibresource{\jobname.bib}
\DefineBibliographyExtras{UKenglish}{%
  \renewcommand*{\mkbibordinal}[1]{#1}%
}
\begin{document}

\section*{Text}

Blah \autocite{jc, tha}. \\
Blah \autocite{jc}.      \\
Blah \autocite{tha}.

\printbibliography

\end{document}
~~~

Output:

![screen shot 2016-06-27 at 11 04 39](https://cloud.githubusercontent.com/assets/2765811/16376303/157294f2-3c4f-11e6-9506-257b6ae97cf0.png)

Expected:

> Blah (Caesar 100–44 BCE; Thales of Miletus 585 BCE).

Note that the output for Thales is incorrect *only* when using `\autocite{jc, tha}`; not for ` \autocite{jc}` … `\autocite{tha}`.

**Comment by plk** [comment]
That was a typo, fixed in git dev.
