### ISSUE TITLE
EDTF output format: minus signs, range separators, etc.

### ISSUE THREAD

**Issue by nickbart1980** [plk/biblatex#447]
~~~
\documentclass{article}
%\usepackage[UKenglish]{babel}
\usepackage[autostyle]{csquotes}
\usepackage[style=authoryear, alldates=edtf]{biblatex}
\usepackage{fontspec}
\setmainfont{Linux Libertine}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@online{      jc,
  author    = {Julius Caesar},
  date      = {-0099-07-11/-0043-03-13},
  title     = {My Life},
  url       = {http://gov.rome},
  urldate   = {0123-07-31/0123-08-01},
}
@online{      cle,
  author    = {Cleopatra},
  %date      = {-0068-uu-uu/-0029-08-10},
  date      = {-0068/-0029-08-10},
  title     = {My Life},
}
@online{      aug,
  author    = {Augustus},
  date      = {-0062-09-21/0014-08-17},
  title     = {My Life: 23 Sep 63 BCE – 19 Aug 14 CE (Julian)},
}
@online{      cal,
  author    = {Caligula},
  date      = {0012-08-29/0041-01-22},
  title     = {My Life},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}

\section*{Text}

Blah \autocite{jc, cle, aug, cal}.

\printbibliography

\end{document}
~~~

Output:

![screen shot 2016-06-26 at 10 20 45](https://cloud.githubusercontent.com/assets/2765811/16361524/a0d2254e-3b82-11e6-9f5c-080bf6921176.png)

Expected:

> Blah (Caesar –0099/–0043; Cleopatra –0068/–0029; Augustus –0062/0014; Caligula 0012/0041).

and

> Augustus (–0062-09-21/0014-08-17). […]

I.e., “/” as a range separator in in-text citations; and a genuine minus sign (or en-dash, “–”) for negative dates everywhere (ISO 8601 clearly distinguishes minus signs from hyphens).

Other issues:

- Using `-0068-uu-uu` as Cleopatra’s birth date results in no date being rendered at all:

	> Cleopatra. *My Life.*

- Using `UKenglish` leads to an error:

	~~~
	! Undefined control sequence.
	<argument> \bibdateeraprefix 
	                             
	l.43 Blah \autocite{jc, cle, aug, cal}.
	                                       
	? 
	~~~

**Comment by plk** [comment]
All corrected apart from the Cleopatra date  - this won't work because "unspecified" 5.2.2  dates are expanded to ranges and so a range including such a date won't parse at all. 

`xxxx-uu-uu -> xxxx-01-01/xxxx-12-31`

plus 'datedayinyear' would be true.
