### ISSUE TITLE
biblatex 3.4 w/bibtex breaks on long "url" entries (regression)

### ISSUE THREAD

**Issue by nanoant** [plk/biblatex#449]
I just upgraded to TeXLive 2016 from 2015. Now I have biblatex 3.4 (bbl files 2.7), previously there was biblatex 3.1 (bbl files 2.5). Since the upgrade I cannot anymore compile some tex files. Fortunately I nailed it down to simple case, a bib file containing long URL.

Take this example:

1. `biblatex-url-bug.tex`

    ~~~latex
\documentclass{article}
\usepackage[backend=bibtex]{biblatex}
\bibliography{biblatex-url-bug}
\begin{document}
  Just citing~\cite{national2012performance}
\end{document}
    ~~~

2. `biblatex-url-bug.bib`

    ~~~latex
@book{national2012performance,
  title     = {{NEMA NU 2}: Performance measurements of positron emission
               tomographs},
  author    = {National Electrical Manufacturers Association and others},
  year      = {2012},
  publisher = {National Electrical Manufacturers Association},
  url       = {https://www.nema.org/Standards/Pages/Performance-Measurements-of-Positron-Emission-Tomographs.aspx},
}
    ~~~

When compiling with TeXLive 2016 I get following error:
~~~
(./biblatex-url-bug.aux) (./biblatex-url-bug.bbl
! Use of \blx@bbl@verbadd@i doesn't match its definition.
l.43     \verb
~~~

The erroneous line 43 is here:
~~~
42    \verb{url}
43    \verb
44  https://www.nema.org/Standards/Pages/Performance-Measurements-of-Positr
45    \verb on-Emission-Tomographs.aspx
46   \endverb
~~~

Running on TeXLive 2015 the bbl output contains no line break after `\verb`:
~~~
42    \verb{url}
43    \verb https://www.nema.org/Standards/Pages/Performance-Measurements-of-Positr
44    \verb on-Emission-Tomographs.aspx
45   \endverb
~~~

For some reason TeXLive 2016 breaks after `\verb` causing `biblatex` error. Honestly I am not sure if it is biblatex fault, because bibtex is generating this output, but on other hand TeXLive 2015 and 2016 have exactly the same version of bibtex.

I would appreciate some feedback what is exactly going on here. And also as it is pretty nasty regression (it took me 2 hours to nail it down to simple tests case), to provide and publish some hotfix.

**Comment by josephwright** [comment]
Please see http://tex.stackexchange.com/questions/311426/bibliography-error-use-of-blxbblverbaddi-doesnt-match-its-definition-ve

**Comment by nanoant** [comment]
Wow.. thanks for such an instant response!
