### ISSUE TITLE
Spacing issues in dates output

### ISSUE THREAD

**Issue by nickbart1980** [plk/biblatex#450]
In the following example, there’s an extra space between “1888” and “)” in “References”:

~~~
\documentclass{article}
\usepackage[UKenglish]{babel}
\usepackage[autostyle]{csquotes}
\usepackage[style=authoryear, alldates=comp, dateera=secular]{biblatex}
\usepackage{fontspec}
\setmainfont{Linux Libertine}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@report{      doe,
  author    = {Doe, John},
  date      = {1777-07-17/1888-08-28},
  title     = {Title},
}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}

\section*{Text}

Blah \autocite{doe}.

\printbibliography

\end{document}
~~~

![screen shot 2016-06-29 at 13 17 03](https://cloud.githubusercontent.com/assets/2765811/16451582/74f22fbe-3df3-11e6-9ea1-3b88685e5d42.png)

I’m not seeing this space with `\usepackage[UKenglish]{babel}` removed.

I’m also not seeing this space with `date = {1888-08-28}`.

And I’m not seeing this space with `alldates=long` either – however, here I get “28th Aug. 1888” which dosn’t seem “long” really.

And another spacing issue: In the following example, the “CE”s in “… BCE–… CE” dates have ever so slightly more space in front of them than they do in the other dates.

~~~
\documentclass{article}
\usepackage[autostyle]{csquotes}
\usepackage[style=authoryear, alldates=comp, dateera=secular, datezeros=false, dateeraauto=1000]{biblatex}
\usepackage{fontspec}
\setmainfont{Linux Libertine}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@article{      doe,
  author    = {Doe, John},
  date      = {0014},
}
@online{      aug,
  author    = {Augustus},
  date      = {-0062-09-21/0014-08-17},
  title     = {My Life},
}
@online{      tib,
  author    = {Tiberius},
  date      = {-0041-11-14/0037-03-14},
  title     = {My Life},
}
@online{      cal,
  author    = {Caligula},
  date      = {0012-08-29/0041-01-22},
  title     = {My Life},
}
@online{      cla,
  author    = {Claudius},
  date      = {-0009-07-30/0054-10-11},
  title     = {My Life},
}
@online{      ner,
  author    = {Nero},
  date      = {0037-12-13/0068-06-07},
  title     = {My Life},
}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}

{\raggedleft

Blah \autocite{doe}.

Blah \autocite{aug}.

Blah \autocite{cal}.

Blah \autocite{cla}.

Blah \autocite{ner}.

Blah \autocite{tib}.

}
\end{document}
~~~

![screen shot 2016-06-29 at 13 10 59](https://cloud.githubusercontent.com/assets/2765811/16451450/aa70cc5a-3df2-11e6-8748-a43a56b121a5.png)

**Comment by plk** [comment]
Should be fixed now (need to get both biblatex and biber).

**Comment by nickbart1980** [comment]
Looks good indeed now.

**Comment by nickbart1980** [comment]
A few more issues, this time with “ymd” output:

- Minus sign missing in the dates of “References” items (Augustus, Caesar, Plato, Thales)
- Extra space before closing round brackets in the dates of “References” items
- Unaesthetic combination of dash and minus sign in in-text citations, e.g., “Caesar −99–−43”
	- Since a forward slash is used as range separator in “References”, it would seem best to use it in in-text citations, too.
	- Alternatively, adding a thin or half-width space before and after the dash in case it is followed by a minus sign might work (like in math mode: `$-99 - -43$).
	- However, whatever range separator is used, I feel it should be the same in both in-text citations and “References”.

Output:

![screen shot 2016-07-07 at 12 50 51](https://cloud.githubusercontent.com/assets/2765811/16651100/5b525644-4431-11e6-9178-9041d250f86b.png)

Source:

~~~
\documentclass{article}
\usepackage[autostyle]{csquotes}
\usepackage[style=authoryear, alldates=ymd,  dateera=astronomical, datezeros=false, dateeraauto=1000, datecirca, dateuncertain, julian]{biblatex}
\usepackage{fontspec}
\setmainfont{Linux Libertine}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}

@online{      plato,
  author    = {Plato},
  date      = {-0424~/-0346~},
  title     = {My Life},
  addendum  = {Textbooks: 428/427 or 424/423 – 348/347 BCE; here we simply use 425 – 347 BCE},
}
@online{      jc,
  author    = {Julius Caesar},
  date      = {-0099-07-11/-0043-03-13},
  title     = {My Life},
  addendum  = {Textbooks: 13 July 100 – 15 March 44 BCE Julian},
}
@online{      aug,
  author    = {Augustus},
  date      = {-0062-09-21/0014-08-17},
  title     = {My Life},
  addendum  = {Textbooks: 23 Sep 63 BCE – 19 Aug 14 CE Julian},
}
@online{      cal,
  author    = {Caligula},
  date      = {0012-08-29/0041-01-22},
  title     = {My Life},
  addendum  = {Textbooks: 31 August 12 – 24 January 41 CE Julian},
}
@online{      tha,
  author    = {{Thales of Miletus}},
  date      = {-0584-05-22},
  title     = {Blog post: Solar eclipse today!},
  addendum  = {Textbooks: Wed 28 May 585 BCE Julian},
}
@book{        sch,
  author    = {Hartmann Schedel},
  date      = {1493-07-21},
  title     = {Liber Chronicarum},
  publisher = {Anton Koberger},
  location  = {Nuremberg},
  addendum  = {Textbooks: 12 July 1493 CE Julian},
}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}

\section*{Text (ymd/astro/jul<1582)}

Blah \autocite{tha}. \\
Blah \autocite{plato}. \\
Blah \autocite{jc}. Compare spaces in math mode: $-99 - -43$ \\
Blah \autocite{aug}. \\
Blah \autocite{cal}. \\
Blah \autocite{sch}.

\printbibliography

\end{document}
~~~

**Comment by plk** [comment]
Thanks for testing this - should be fixed now. I also noticed the ugly dash/minus conflict - I think settling on slash for ymd or edtf is better.

**Comment by plk** [comment]
Looks like a new dependency in 5.24 builds - should be fixed now if you pull biber again.

**Comment by nickbart1980** [comment]
Ok, biber works again, and the output looks good.

**Comment by simifilm** [comment]
@plk If I understand this correctly, the idea is that `biblatex` should print a thin space, if a minus year follows a range dash. But this does not seem to work properly. At least in tests with `biblatex-fiwi` I always get the space, even when there is no dash in sight.

**Comment by plk** [comment]
Hmm, is this with the latest version?

**Comment by simifilm** [comment]
Yes.
