### ISSUE TITLE
No need for  "csquotes missing" message when using XeLaTex

### ISSUE THREAD

**Issue by buhtz** [plk/biblatex#451]
I use XeLaTeX and everytime I use biblatex I got this message

```
Package biblatex Warning: 'babel/polyglossia' detected but 'csquotes' missing.
(biblatex)                Loading 'csquotes' recommended.
```

I see no technical reason for that when using XeLaTeX. `csquotes`does some nice tweaks sometimes usefull and sometimes needed when using non-unicode LaTeX. But I see no reason for it when using XeLaTeX.

So would you add a check for XeLaTeX before printing this warning.

Just to be clear: Of course I know the documentation and how you reason the use of csquotes. But it doesn't cound if you use XeLaTeX. You can get the current language from polyglossia. I also would prefere a centralized solution to store the which-quotes-in-which-language-informations. So you could load csquotes inside biblatex yourself if you really need it.
Another (more unicode like) solution could be to allow the user to give the quotes as an option to biblatex.

An XeLaTeX user write the quotes as they are in unicode.  `„german“`

```
\usepackage[oquote=„,
            cquote=“]
           {biblatex}
```

**Comment by josephwright** [comment]
This warning has always been present and I am reluctant to alter PL's original position.

**Comment by josephwright** [comment]
Note that one can argue for/against logial mark up of quotes irrespective of the engine in use.

**Comment by plk** [comment]
I agree with @josephwright  here, I don't think it warrants an engine specific warning.
