### ISSUE TITLE
Literal in the 'year' field (biblatex 3.5)

### ISSUE THREAD

**Issue by odomanov** [plk/biblatex#453]
I use a literal in the 'year' field for non standard date specifications like "1898 or 1901". This's been working fine so far, but fails with biblatex 3.5 (I used the DEV version from SF). The MWE below yields error with pdflatex, but works fine with xelatex/lualatex. Is this supposed to work?

The problem is with non-latin symbols in the field. I experimented with `\foreignlanguage` etc. but didn't succeed. 

```latex
\RequirePackage{filecontents}
\begin{filecontents*}{\jobname.bib}
  @BOOK{b1,
    author = {Author1},
    title = {Title},
    year={[1838 или 1899]},
    langid={russian},
  }
\end{filecontents*}
\documentclass[english,russian]{article}
\usepackage{iftex}
\ifPDFTeX
    \usepackage[T1,T2A]{fontenc}
    \usepackage[utf8]{inputenc}
\else
    \usepackage{fontspec}
    \usepackage{xecyr}
    \setmainfont[Ligatures=TeX]{CMU Serif}
    \setsansfont[Ligatures=TeX]{CMU Sans Serif}
    \setmonofont[Ligatures=TeX]{CMU Typewriter Text}
\fi

\usepackage{babel}

\usepackage[backend=biber,
language=auto,  
autolang=other,
style=authoryear,
]{biblatex}
\addbibresource{\jobname.bib}

\begin{document}
\autocite{b1} \cite{b1}
\printbibliography
\end{document}
```

**Comment by plk** [comment]
I'm glad you spotted this. It was quite tricky and uncovered some problems in labeldatesource handling which needed to be corrected. It should be ok now on the 3.5/2.6 dev branches of biblatex/biber.

**Comment by odomanov** [comment]
Thank you, it's great to know. I suppose it was tricky. But it's indeed fixed.

Just for information. I passed a bunch of my rather poorly formed .bib files through the dev version --- to test the `biblatex-gost` style. I needed to adapt the style to cope with incompatibilities but otherwise everything was fine.
