### ISSUE TITLE
relatedtype={reprintas} linebreaks with multiple related items

### ISSUE THREAD

**Issue by postblue** [plk/biblatex#455]
The bib items are these:

```latex
@book{Wing:handicaps,
title = {The handicaps of autistic children},
author = {Wing, Lorna},
publisher = {National Society for Autistic Children},
address = {London},
date = {1982},
related = {Wing:Spectrum, Wing:continuum},
relatedtype  = {reprintas},
}

@book{Wing:Spectrum,
title = {Autistic spectrum disorders: an aid to diagnosis},
author = {Wing, Lorna},
publisher = {National Autistic Society},
address = {London},
date = {1993},
}

@book{Wing:continuum,
title = {Autistic continuum disorders: an aid to diagnosis},
author = {Wing, Lorna},
publisher = {National Autistic Society},
address = {London},
date = {1996},
}
```

But, I have a linebreak instead of the second "reprinted as" field (here, the bibliography, but in the cites too).

![capture d ecran de 2016-08-02 19-52-57](https://cloud.githubusercontent.com/assets/696539/17339120/bc5928fa-58ea-11e6-8227-18a0ee2d75d4.png)

But it works if I split the reprintas arguments between the two items:

```
@book{Wing:handicaps,
title = {The handicaps of autistic children},
author = {Wing, Lorna},
publisher = {National Society for Autistic Children},
address = {London},
date = {1982},
related = {Wing:Spectrum},
relatedtype  = {reprintas},
}

@book{Wing:Spectrum,
title = {Autistic spectrum disorders: an aid to diagnosis},
author = {Wing, Lorna},
publisher = {National Autistic Society},
address = {London},
related = {Wing:continuum},
relatedtype  = {reprintas},
date = {1993},
}

@book{Wing:continuum,
title = {Autistic continuum disorders: an aid to diagnosis},
author = {Wing, Lorna},
publisher = {National Autistic Society},
address = {London},
date = {1996},
}
```

![capture d ecran de 2016-08-02 19-56-59](https://cloud.githubusercontent.com/assets/696539/17339259/5e851670-58eb-11e6-8ed0-3a668a584bc9.png)

**Comment by plk** [comment]
I believe that the default setup for related fields doesn't deal with multiple `reprintedas` - I think it's best to ask on TSE.

**Comment by moewew** [comment]
The default delimiter between two related entries is `\adddot\par\nobreak`, you can change that to `\renewcommand*{\relateddelim}{\addperiod\space}`. Then at least your example will look OK, but `knuth:ct:related` from `biblatex-examples.bib` will look different (it loses its "table-like" structure).

**Comment by moewew** [comment]
@plk Maybe we could also make the `\relateddelim` dependent on the `relatedtype` like `\DeclareFieldFormat{related:...}` and `\DeclareFieldFormat{relatedstring:...}`.

**Comment by plk** [comment]
@moewew - could you suggest a patch?

**Comment by moewew** [comment]
Are you OK with the suggested approach of using the CS `relateddelim:<relatedtype>`, as in `\csdef{relateddelim:<relatedtype>}{\addperiod\space}`?

**Comment by moewew** [comment]
I have added https://github.com/plk/biblatex/pull/488. Check out if you like it and whether the `relateddelim:<relatedtype>` approach doesn't add a new layer of confusion.

**Comment by plk** [comment]
I have manually incorporated the changes into `biblatex` 3.7. I dropped the `:` in the macro name as this makes it confusing for users who then can't use `\newcommand` as normal. Can you try it and see? I also didn't add any defaults - it will just fall back on `\relateddelim` by default as otherwise we'd probably have to add defaults for all related types and since these are user-definable, that would be impossible.

**Comment by moewew** [comment]
Works just fine. I liked the visual separation of the colon, but I can definitely see the downside of the `\csdef` solution.

I don't think we'd have to set defaults for all types; after all there is support for some types out of the box, and we'd only have to acknowledge these as non-default. But in the interested of backwards compatibility not adding new defaults is probably a good idea anyway.
