### ISSUE TITLE
Range fields parsing

### ISSUE THREAD

**Issue by odomanov** [plk/biblatex#456]
In the example below the second entry doesn't print the `pages` field although the first does. That's because in the second case `biblatex` reports that the field is malformed and just skips it. I'd say that in both cases the field is malformed. Besides, in general I'd expect that malformed fields should be printed as-is, not skipped. What is the algorithm behind this?

The example demonstrate the problem with the `pages` field, but I actually ran into it when I changed the type of `volume` and similar fields to `range`. So it concerns the parsing of range fields in general. 

````latex
\RequirePackage{filecontents}
\begin{filecontents*}{\jobname.bib}
  @BOOK{b1,
    author = {Author},
    title = {Title},
    _volume = {Lek.~1-13},
    pages = {Sheets~1-5}
  }
  @BOOK{b2,
    author = {Author},
    title = {Title},
    _volume = {Lek. 1-13},
    pages = {Sheets 1-5}
  }
\end{filecontents*}
\documentclass{article}

\usepackage[backend=biber]{biblatex}
\addbibresource{\jobname.bib}

\begin{document}
\nocite{*}
\printbibliography
\end{document}
````

**Comment by plk** [comment]
Fixed in biber 2.6 DEV - could you try it?

**Comment by odomanov** [comment]
Yes, fixed, thank you.
Also fixed some of my other problems :)

**Comment by maieul** [comment]
@odomanov : I think in your case, you should use the pagination field to define "sheet" pagination.

**Comment by odomanov** [comment]
Thank you. But this is just an example to demonstrate the issue with range fields parsing. I actually had problems not with pages, but with fields like volumes etc.
