### ISSUE TITLE
Case conversion: {\emph{Foo}} in initial position rendered as “FOO”

### ISSUE THREAD

**Issue by njbart** [plk/biblatex#459]
```
\documentclass{article}
\usepackage[american]{babel}
\usepackage[backend=biber, style=apa]{biblatex}
\DeclareLanguageMapping{american}{american-apa}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@article{01, author = "01", 
title =    "Blah \emph{Foo} {\emph{Foo}} {{\emph{Foo}}}",
}
@article{02, author = "02", 
title =    "{\emph{Foo}} {\emph{Foo}} {\emph{Foo}}",
subtitle = "{\emph{Foo}} {\emph{Foo}} {\emph{Foo}}"
}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

Output: see https://www.sharelatex.com/project/57b7457ce9322dac1d08166b

01 clarifies that only `{\emph{Foo}}`, but not `\emph{Foo}` or `{{\emph{Foo}}}` can be used for an italicised but, regarding case conversion, unprotected string.

02 shows that `{\emph{Foo}}` in an initial position in title and subtitle is rendered as “FOO”.

Expected, of course: “Foo”.

Fixing this manually might be possible in some cases, but for any kind of automated conversion (this came up in connection with [zotero-better-bibtex](https://github.com/retorquere/zotero-better-bibtex/issues/541)), this inconsistency is highly problematic, and a fix on the biblatex side would be much appreciated.

**Comment by moewew** [comment]
I don't think I'll manage to resolve this issue in the current case change framework, but we are hoping to switch to `expl3` for the next release. See #960.

With https://github.com/plk/biblatex/compare/dev...moewew:rebl3txt the MWE produces

> 01. (n.d.). Blah Foo foo Foo.
>02. (n.d.). Foo foo foo: Foo foo foo.

![Blah Foo foo Foo.//Foo foo foo: Foo foo foo.](https://user-images.githubusercontent.com/6755835/82122987-3a2b6600-9797-11ea-99c0-32dfdaf88265.png)

**Comment by moewew** [comment]
`biblatex` 3.15 with the new `expl3` case changing code has been released and is available now in MikTeX and TeX live.

The MWE now produces the result shown in my comment above.

I'm closing this issue since it is resolved in the `expl3` code and unlikely ever to be resolved with the (now legacy) `latex2e` case changing code.
