### ISSUE TITLE
Enhance polyglossia support

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#460]
Because it came up in https://github.com/plk/biblatex/issues/427, which being very long now is rightfully closed, again I thought I'd open a ticket for discussions on `polyglossia` support.

I'll just repost my comment from there

> `\xpg@loaded` and `\xpg@vloaded` seem OK.
> 
> The problem, however, is that even in `\blx@mkautolangpoly` language settings are loaded with `\bbl@main@language`, and that variable does not seem to hold the language variant with `polyglossia`. Ideal would be a backwards-`babel`macro that holds the language (+variant) in `babel`-speak and a macro that holds the `polyglossia`language and variant.

Relevant is https://github.com/reutenauer/polyglossia/issues/154

Maybe with proper variant detection, we could revisit https://github.com/plk/biblatex/issues/264

**Comment by bastien-roucaries** [comment]
According to chicago manual of style:
15.50 Patents or other documents cited by more than one date Cite patents and other documents that include more than one date as follows (note that the year of issue is repeated to avoid ambiguity).

Christensen, Godtfred Kirk. Toy building set. U.S. Patent 3,597,875 filed November 18, 1968, and issued August 10, 1971.

**Comment by jspitz** [comment]
See also reutenauer/polyglossia#226

**Comment by jspitz** [comment]
The next polyglossia version stores variants in `\languagevariant` and `\mainlanguagevariant`.
I figure this will not fully satisfy biblatex, since naustrian and austrian both have variant = austrian (the spelling option does further discrimination), so we ultimately need either `\babelname` and/or BCP-47 tags.

**Comment by jspitz** [comment]
And as of https://github.com/reutenauer/polyglossia/commit/60339eb2cba3e0e69d98bce4a21dcdd89c90aff4, polyglossia has `\babelname` and `\mainbabelname`

Does this give you the information you need?

**Comment by moewew** [comment]
@jspitz Thanks for the effort. That looks really good! (I tried using the new interface in https://github.com/moewew/biblatex/commit/d12f8a045ab5dc1d768b6b6bbd5e65968fb9b699 [https://github.com/moewew/biblatex/tree/polyglossia] and things seem to work well.)

We need a bit more than simple access to babel names of main, active and loaded languages, though. One other very important thing for us is to populate `\extras<language>` at the moment we populate `\extras<babellang>`, is there a chance `polyglossia` could automatically execute the correct `\extras` or offer an interface that makes executing extras for `babel`-equivalents easier? I discussed this in more depth at https://github.com/reutenauer/polyglossia/issues/226#issuecomment-525827940 and https://github.com/reutenauer/polyglossia/issues/226#issuecomment-526030447 with @bastien-roucaries.

**Comment by jspitz** [comment]
With "populating" do you mean something like
```tex
\addto\captionsngerman{%
<biblatex additions/redefinitions>
}
```
?

**Comment by jspitz** [comment]
OK, never mind, I see you explained rather well in https://github.com/reutenauer/polyglossia/issues/226#issuecomment-526030447

**Comment by jspitz** [comment]
OK, I have pushed an attempt to my fork at https://github.com/jspitz/polyglossia/commit/cf6cd54794a252c9ef7c6a505368927773976b43

What this provides are hooks that are executed after `\blockextras@<lang>`, `\inlineextras@<lang>` and `\noextras@<lang>`, respectively, if the respective babelname matches, namely:

* `\blockextras@bbl@<babelname>`
* `\inlineextras@bbl@<babelname>`
* `\noextras@bbl@<babelname>`

(the `@bbl` qualifier is to prevent clashes as in `german` [babelname] and `german` [polyglossia name])

The respective commands are not defined by default, and we check their existence before executing them. This means you wouldn't use `\gappto`, but simply `\def`, or probably better:
```tex
\providecommand\blockextras@bbl@<babelname>
\gappto\blockextras@bbl@<babelname>
```
Would this fit your needs?

**Comment by jspitz** [comment]
> The respective commands are not defined by default, and we check their existence before executing them. This means you wouldn't use `\gappto`, but simply `\def`, or probably better:
> 
> ```
> \providecommand\blockextras@bbl@<babelname>
> \gappto\blockextras@bbl@<babelname>
> ```

I see now that \gappto defines the command if it does not exist. Neat. So
```tex
\gappto\blockextras@bbl@<babelname>
```
should do.

**Comment by jspitz** [comment]
FYI I have now completed this approach in https://github.com/jspitz/polyglossia/commit/1d78eb98494c456e6604cd9b9c03fbf256ac3201 by adding similar hooks `\captions@bbl@<babelname>` and `\date@bbl@<babelname>`. Even if biblatex does not need this, I am sure there are packages that will.

**Comment by moewew** [comment]
Brilliant! That makes things a lot easier for us. https://github.com/plk/biblatex/commit/8db14c03546c0f6075c06ecf07089b921ca8b8ca uses the new `babel`-extras.

I still need to iron out a few warnings about hyphenation patterns that `biblatex` produces, maybe that also needs an interface ... But then we should be set.

**Comment by jspitz** [comment]
Excellent. I merged the commits into polyglossia master.
Let us know if more things need to be done.

**Comment by moewew** [comment]
Great. Thank you!

As I mentioned above I'm having a few troubles with hyphenation  (`\l@<language>`) in LuaLaTeX at the moment, I'll try to find out what is going wrong there next weekend, hopefully.

**Comment by jspitz** [comment]
Note that there is currently work going on in that area in polyglossia, so it might be that the problem is on our side. So please keep us informed.

**Comment by moewew** [comment]
I don't yet fully understand why it happens, but maybe you can help me.

`biblatex` has a command
```latex
\def\blx@hyphexcept#1#2{%
  \ifcsundef{l@#1}
    {\blx@warn@nohyph{#1}}
    {\begingroup
     \language\csname l@#1\endcsname\relax
     \hyphenation{#2}%
     \endgroup}}
```
and uses it as
```latex
\blx@hyphexcept{<babel language>}{<word>}
```
Apparently that doesn't always quite work for `ngerman` when it is an `otherlanguage`.

```latex
\documentclass{article}
\usepackage{polyglossia}
\usepackage{csquotes}
\usepackage[style=authoryear,]{biblatex}

\setdefaultlanguage[variant=british]{english}
\setotherlanguage{german}
% even with
%\setotherlanguage[spelling=new]{german}


\addbibresource{biblatex-examples.bib}


\begin{document}
  \autocite{sigfridsson}

\begin{german}[spelling=new]
  \autocite[372]{sigfridsson}
  \fullcite{markey}
\end{german}

  \printbibliography
\end{document}
```

But it is no issue of `ngerman` is the main language
```latex
\documentclass{article}
\usepackage{polyglossia}
\usepackage{csquotes}
\usepackage[style=authoryear,]{biblatex}

\setdefaultlanguage[spelling=new]{german}
\setotherlanguage[variant=british]{english}

\addbibresource{biblatex-examples.bib}


\begin{document}
  \autocite{sigfridsson}

\begin{english}[variant=british]
  \autocite[372]{sigfridsson}
  \fullcite{markey}
\end{english}

  \printbibliography
\end{document}
```
Mhhh...

**Comment by jspitz** [comment]
I think I understand what is going on: With `\setdefaultlanguage`, the language is also set (`\AtBeginDocument`), and thus the hyphenation patterns are created. With `\setotherlanguage`, on the other hand, the language is set only if it is really used (with the first `\selectlanguage` or equivalent in the command).

Would it be possible to postpone the biblatex check so that it is only executed if `\extras...` is issued?

**Comment by jspitz** [comment]
Another possibility that might work is to use `\xpg@ifdefined{#1}` rather than `\ifcsundef{l@#1}` with polyglossia. This function calls `\polyglossia@luatex@load@lang` with luatex before it checks the existence of the pattern, and this function does:

```tex
\def\polyglossia@luatex@load@lang#1{%
  % if \l@#1 is not properly defined, call lua function newloader(#1),
  % and assign the returned number to \l@#1
  \polyglossia@check@ifdefined:NF {#1}
    {
      \expandafter\chardef\csname l@#1\endcsname=
        \directlua{ tex.sprint(polyglossia.newloader'#1') }\relax
    }
}
```

**Comment by moewew** [comment]
Mhhh, the hyphenation exception come from the `.lbx` files

https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/lbx/ngerman.lbx

each `.lbx` is only read once, executing the hyphenation exception every time `\extras` is used seems a bit over the top.

**Comment by moewew** [comment]
Oh, `xpg@ifdefined` looks good. Let me check if that works.

**Comment by moewew** [comment]
Thank you again. That seems to have done it. https://github.com/moewew/biblatex/commit/26ad1d024203556a1101fce94edb1f3145299ba3.

**Comment by jspitz** [comment]
Just a brief heads-up: `polyglossia 1.45 (2019/10/27)` with babelname support has been submitted to CTAN and will be on the servers soon.

**Comment by moewew** [comment]
`biblatex` 3.14 has been released and works together quite well with `polyglossia` v1.45 or above (I tested with v1.46). Thanks for the great help, everyone.
