### ISSUE TITLE
\DeclareNameAlias{default}{someStyle} ignored within Alias-hierarchy

### ISSUE THREAD

**Issue by dklinger** [plk/biblatex#462]
I don't know if this is a bug as I'm new to biblatex. But in my opinion, somethins going wrong here:

I would like to overwrite the "default"-Alias to use {family-given} instead of {given-family}, so I used this code-snippet:
`\DeclareNameAlias{default}{family-given}`
But this only works for the first author name. To enforce {family-given} on the second, third...author names I also have to use:
`\DeclareNameAlias{author}{family-given}`

In my opinion, this should not be necessary, as there is already a Name-Alias which maps {author} to {default} within the file biblatex.def:
`\DeclareNameAlias{author}{default}` => line 853

From a programmers perspective I think that overriding the {default}-Alias, which I am doing with my first approach, should also override the {author}-Alias as it (the {author-Alias}) is referencing the {default-Alias} which is overwriten by my code.

Kind Regards, Daniel

**Comment by moewew** [comment]
Mhhhh, I would have this expected to work. Can you show a short example document that we can compile (an [MWE - follow the link for more help](http://meta.tex.stackexchange.com/q/228/35864)) that exhibits this behaviour?

Note that in some styles the authors/editors/translators are printed in the `sortname` format (a setting of the style's `.bbx`) and not in `default` format (as give in `biblatex.def`).

**Comment by dklinger** [comment]
Hah, my fault. I'm using authoryear and, as you said, this style is using sortname instead of deafult.
Thanks a lot.
