### ISSUE TITLE
Issues with \DeclareLabeldate

### ISSUE THREAD

**Issue by simifilm** [plk/biblatex#464]
I still try to get my head around the `\DeclareLabeldate mechanism: I think I get it now, but there are two things which strike me as odd.

First, the documentation doesn't seem to be correct about the default definition. `biblatex.pdf` gives the following default definition:

```\DeclareLabeldate{%
  \field{date}
  \field{eventdate}
  \field{origdate}
  \field{urldate}
  \literal{nodate}
}
```

But `biblatex.def` has the following:

```\DeclareLabeldate{%
  \field{date}
  \field{eventdate}
  \field{origdate}
  \field{urldate}
  \field{year}
  \literal{nodate}
}
```

The actual definition in `biblatex.def` seems odd to me. I don't get why `year` comes so late here. I understand that `biblatex` generally prefers `date` over `year`, but I think in most cases – especially if you are coming from traditional `BibTeX`– `year` will be the relevant field. I have many book entries with `year` and `origdate` entries and the current setup leads to `biblatex` preferring the latter over the former which is wrong. In fact,  I can think of no situation where `year` – if it exsists – should not be the preferred publication date compared to things like `origdate` or `eventdate`.

**Comment by plk** [comment]
Hmm, I need to check the dev branch. I think you are right about the order. It is important that year comes after date but probably not after other date fields. Dates have had a major overhaul for 3.5 and are now EDTF level 1 compliant. Times are also now supported.

**Comment by moewew** [comment]
A short test seems to suggest this is only relevant if the `year` field does not parse as a year. Still `year` should probably come right after `date` in those situations.
Cf. the following MWE

```
\documentclass[british]{article}
\usepackage{filecontents}
\begin{filecontents*}{\jobname.bib}
@article{elk1,
  author   = {Anne Elk},
  title    = {A Theory on Brontosauruses},
  journal  = {Foo Journal},
  year     = {foo},
  urldate  = {1992-07-07},
}
@article{elk2,
  author   = {Anne Elk},
  title    = {A Theory on Brontosauruses},
  journal  = {Foo Journal},
  year     = {1997},
  urldate  = {1992-07-07},
}
@article{elk3,
  author   = {Anne Elk},
  title    = {A Theory on Brontosauruses},
  journal  = {Foo Journal},
  date     = {1998},
  urldate  = {1992-07-07},
}
\end{filecontents*}
\usepackage{babel}
\usepackage{csquotes}
\usepackage[backend=biber, style=authoryear]{biblatex}

\DeclareLabeldate{%
  \field{date}
  \field{year}
  \field{eventdate}
  \field{origdate}
  \field{urldate}
  \literal{nodate}
}

\addbibresource{\jobname.bib}
\begin{document}        
  \cite{elk1,elk2,elk3}
  \printbibliography
\end{document}
```

if you comment out the `\DeclareLabeldate` declaration the entry with year "foo" is treated as having its `urldate` as year.

**Comment by simifilm** [comment]
@moewew Maybe I did something wrong when I adapted my own style `biblatex-fiwi`, but with the current definition in `biblatex.def` I had year from `origdate` printed all over my bibliography. Once I adapted the definition and moved `year` up, everything was fine again.

**Comment by moewew** [comment]
Oh yes sorry, you are absolutely right. Even if the year parses correctly it does not take precedence. `\field{year}` definitely needs to be moved up. I have removed the confusing post.

**Comment by plk** [comment]
Should be fixed in latest 3.5 DEV.

**Comment by simifilm** [comment]
Not the subject of this bug report, but is there a timeline for the next release. This version has been in the making for quite some time?

**Comment by plk** [comment]
Quite soon I think, perhaps a week or so?

**Comment by moewew** [comment]
If you have a release schedule in mind you might want to notify comp.text.tex so style developers know the new version with the announced required changes is about to be released. (I think in the past there wasn't even the CTAN update notifier on comp.text.tex. That could also help.)
