### ISSUE TITLE
Checking the author in the uniquework test

### ISSUE THREAD

**Issue by odomanov** [plk/biblatex#465]
Imagine that we have only two entries, both with the same `title`, the one is `@book` with an `author` and the other is `@collection` with no author. Then the `\ifuniquework` test is false for the latter, although it should rather be true. Is it a bug?

I actually need a criterion in an authoryear style for whether I need to print the date to disambiguate things. In the example above I don't. But if in addition I have another `@collection` with the same title, I do need the date for disambiguation. And I cannot decide between these situations in biblatex.

This is an MWE to play with.
````latex
\RequirePackage{filecontents}
\begin{filecontents*}{\jobname.bib}
@BOOK{stb1a,
  author       = {Aaaa1},
  title        = {Tttt1},
  year         = {1900},
}

@COLLECTION{stc2,
  title        = {Tttt1},
  year         = {1950},
}

% @COLLECTION{stc22,
%   title =        {Tttt1},
%   year =         {1990},
%   edition =      {2},
% }

\end{filecontents*}
\documentclass{article}
\usepackage[textwidth=12cm]{geometry}

\usepackage[backend=biber,
style=authoryear,
singletitle,uniquetitle,uniquework,
]{biblatex}
\addbibresource{\jobname.bib}

\renewbibmacro{finentry}{%
  \printtext[bold]{\hfill
    singletitle:\ifsingletitle{Y}{N}
    uniquetitle:\ifuniquetitle{Y}{N}
    uniquework:\ifuniquework{Y}{N}}}

\begin{document}
\nocite{*}
\printbibliography
\end{document}
````

**Comment by plk** [comment]
It's not a bug - the issue is that `uniquework` is only set if there is a labeltitle and a labelname. There is no way to distinguish those two items really since they are basically identical apart from the years - you could add the date if `uniquework` is false and labeltitlesource or labelnamesource is missing?

**Comment by odomanov** [comment]
Sorry, I don't quite understand. 
Just for clarification. I have a `@collection` and 2 cases: 

1) there is another `@collection` with the same title -- so I need the year for disambiguation, since citations are, say, (Title, 1900) and (Title, 1910) -- so I can't omit year; 

2) there is a `@book` with an author and with the same title -- so I don't need the year to disambiguate, since the citations are like (Title, 1900) and  (Author, 1900) -- so I can omit year and just print (Title). 

I can't see how labeltitlesource and labelnamesource can help. They are the same in both cases.

PS By the way, I couldn't find documentation about labeltitlesource and labelnamesource.

**Comment by plk** [comment]
You mean that you need some test which is entrytype sensitive?

**Comment by odomanov** [comment]
I think it's a bit more complicated. 
When the title is used for the label (that is in author-year styles when the author is missing) I need to know if this title uniquely identifies the publication. So the test should be true when there is no other `@collection`, `@proceedings`, etc with the same title, irrespective of the existence of `@article`, `@book`, `@incollection`, etc with this title. In short, it should check the uniqueness _only_ among publications without authors. I'm not sure that simple entrytype sensitiveness is enough here.

I hope this clarifies the thing a little bit, sorry for the mess.

**Comment by odomanov** [comment]
More exactly perhaps, the test should check the uniqueness of the `labeltitle` among records without `labelname`.

**Comment by plk** [comment]
I have added documentation about `labelnamesource` and `labeltitlesource`. Thinking about the other issue.

**Comment by plk** [comment]
I have added a test `\ifuniquebaretitle` which is like `\ifuniquetitle` but only applies to entries with no `labelname` - can you try it? (3.5 DEV version and biber 2.6 DEV version).

**Comment by odomanov** [comment]
Thanks a lot. A quick test shows that it works fine. I'll try to use it in "real life".
