### ISSUE TITLE
add support to linguex package 

### ISSUE THREAD

**Issue by nicolai-rostov** [plk/biblatex#466]
Hi,

Would it be possible for `biblatex` to support the `linguex` package, please? The linguex package redefines `\@footnotetext` in order to support numbered examples in footnotes. This redefinition breaks `biblatex`' support for *ibid* and *ibidem* as it prevents `biblatex` from patching footnotes.

There is an ongoing discussion of how this could be (easily?) achieved at http://tex.stackexchange.com/a/327725/22435 . According to egreg,

> 
the biblatex team [...] need to patch `\predefinedfootnotetext` in the case the [`linguex`] package is loaded, just like they provide for some other case in which the command to patch is different.

As I understand it from another answer by moewe, in order to support `linguex`, `biblatex` would need to patch `\predefinedfootnotetext` by prepending `\toggletrue{blx@footnote}` to whatever it is that it expands to.

Thank you

**Comment by plk** [comment]
Please try biblatex 3.5 DEV version (you'll need biber 2.6 DEV version too) - I have added a patch for `linguex`.

**Comment by nicolai-rostov** [comment]
It works. With the patch from commit `9b9c7fb`, I get *ibid* footnotes, and no warnings at compile time, when using `biblatex` with `linguex`. 

Thank you.
