### ISSUE TITLE
calling multiple bibcheck

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#467]
Actually, if I do 

```
\printbibliography[bibcheck=check1,bibcheck=check2]
````

only the check2 is checked, the check1 is ignored.

Should it be possible to allow such possibility of calling multiple bibcheck. 

I know that we could merge the two check in one but:
1. Sometime, the two check have not at all the same semantic.
2. if we have complex bibcheck, merging them is complex and could be a source of bug

**Comment by plk** [comment]
I see your point but having multiple bibchecks is quite complicated and generally everything can be done in one bibcheck since it is arbitrary code ...
