### ISSUE TITLE
New date features documentation

### ISSUE THREAD

**Issue by jspitz** [plk/biblatex#473]
I have had some problems when implementing the (cool!) new date features, and I think it is a mixture of documentation glitches and (probably) unimplemented features, but maybe also my own ignorance. So please excuse this rather confuse ticket.

As to the documentation: it is stated that the new date tests
```
\if<datetype>dateera
\if<datetype>datecirca
\ifdate‘datetype’uncertain
```
can be used with other than the standard dates if `<datetype>` is exchanged with the given datetype "(date, urldate, eventdate etc.)". However, it strikes me that the following description (no double date) would be correct:
```
\if<datetype>era
\if<datetype>circa
\if<datetype>uncertain
```
Since `\iforigdatecirca` works, while `\iforigdatedatecirca` does not.

Next, if I am not missing something, `\enddateuncertainprint` and friends are not yet documented. I figure that this is accompanied by `\<datetype>enddateuncertainprint`, right?

Finally -- again, if I am not missing something --, there does not seem to be a working implementation of `\<datetype>circaprint` and friends, right? I needed the code below to make it work:

```
% These seem to be missing in biblatex
\iftoggle{blx@datecirca}{%
     \protected\def\origdatecircaprint{%
       \iforigdatecirca{\bibstring{circa}\printdelim{datecircadelim}}{}}%
     \protected\def\origenddatecircaprint{%
       \iforigenddatecirca{\bibstring{circa}\printdelim{datecircadelim}}{}}%
     \protected\def\origdatecircaprintedtf{%
       \iforigdatecirca{\textasciitilde}{}}%
     \protected\def\origenddatecircaprintedtf{%
       \iforigenddatecirca{\textasciitilde}{}}}

\iftoggle{blx@dateuncertain}{%
     \protected\def\origdateuncertainprint{%
       \iforigdateuncertain{\bibdateuncertain}{}}%
     \protected\def\origenddateuncertainprint{%
       \iforigenddateuncertain{\bibdateuncertain}{}}}
%%
```

**Comment by plk** [comment]
You are right, there are some documentation omissions and errors, I will correct these and re-publish 3.5. I will update here.

**Comment by plk** [comment]
Actually, they will be in the 3.6 DEV branch since I realise that 3.5 has already hit CTAN.

**Comment by plk** [comment]
Actually, the documentation is correct as `<datatype>` is only the prefix before the string `date` for any datamodel date fields. So, it contains, by default `event`, `orig`, `url` and the empty string `` for the `date` field.

**Comment by plk** [comment]
The `\datecircaprint` calls `\ifdatacirca` which is aliased to `\if<datatype>datecirca` in all date printing routines and so it will automatically pick up the right datatype. So you shouldn't need `\<datatype>datecircaprint`.

**Comment by jspitz** [comment]
> Actually, the documentation is correct as <datatype> is only the prefix before the string date for any datamodel date fields. So, it can be by default event, orig, url and the empty string for the date field.

Well, the description is at least not very clear (I had to consult the sty file to find out the real meaning). Probably spell out in the docs that the _prefix_ is meant (or even better, use `<dateprefix>` rather than `<datetype>`). Also,  `\ifdate‘datetype’uncertain` should be `\if<datetype>dateuncertain`

**Comment by plk** [comment]
True - this is done now where `<datetype>` first appears in the documentation for dataparts. You are right about the other typo which should be corrected now in 3.6 DEV.

**Comment by jspitz** [comment]
> The \datecircaprint macro calls \ifdatacirca which is aliased to \if<datetype>datecirca in all date printing routines and so it will automatically pick up the right datetype. So you shouldn't need \<datatype>datecircaprint.

I am not sure what you mean by "date printing routines". I was trying to use the commands in some macro definitions in cbx and bbx files, such as the following one, which is called from within the cite:`labelyear+extrayear` macro if the `origyear` field is defined. In this context, the \*print macros all refer to the unprefixed date:

```
\newbibmacro*{cite:origyear}{%
  \ifdefstring\blx@dateformat@origdate{edtf}
       {}
       {\origdatecircaprint}%
  \dateeraprintpre{origyear}%
  \mkyearzeros{\thefield{origyear}}%
  \iffieldsequal{origdateera}{origenddateera}{}
       {\dateeraprint{origyear}}%
  \origdateuncertainprint%
  \ifdefstring\blx@dateformat@origdate{edtf}
       {\origdatecircaprintedtf}
       {}%
  \iffieldundef{origendyear}{}{%
    \iffieldsequal{origyear}{origendyear}{}
        {\ifdefstring\blx@dateformat@origdate{edtf}
          {\slash}% strict EDTF
          {\ifnumequal{\thefield{origyear}}{\thefield{origendyear}-1}{\slash}{\bibdaterangesep}%
           \origenddatecircaprint}%
         \dateeraprintpre{origendyear}%
         \mkyearzeros{\thefield{origendyear}}%
         \origenddateuncertainprint%
         \ifdefstring\blx@dateformat@origdate{edtf}
           {\origenddatecircaprintedtf}
           {}%
         \dateeraprint{origendyear}}%
  }%
}
```

**Comment by jspitz** [comment]
Well, OK, I see now. `\printorigdate`. Much easier. Sorry for the noise.

**Comment by plk** [comment]
Right, exactly.
