### ISSUE TITLE
Multiple related entries having different relationship types

### ISSUE THREAD

**Issue by koppor** [plk/biblatex#475]
Sections 3.4 "Related Entries" and 4.5.1 "Related Entries" of the biblatex manual list how to use related entries. It reads that I can provide multiple keys at `related`, but only one relationship type at `relatedtype`.

One example given is

```
@MVBook{key1,
...
related = {key2,key3},
relatedtype = {multivolume},
...
}
```

What if I want to have
```
@Article{key1,
...
related = {key2, key3, key4}
relatedtype = {extends, cites, cites}
}
```

Is that possible? If not, this is fine for me, just wanted to know. Then, I have to come up with another solution to store different relations in bibtex.

In the [JabRef](https://www.jabref.org/) [team](https://github.com/orgs/JabRef/teams/developers), we have a longer discussion ongoing at https://github.com/koppor/jabref/issues/14 and a UI for displaying related entries at https://github.com/JabRef/jabref/pull/1637.

**Comment by plk** [comment]
Greetings, no this is currently not possible - only one relatedtype is allowed.
