### ISSUE TITLE
How to handle multiple eprint ids

### ISSUE THREAD

**Issue by tobiasdiez** [plk/biblatex#476]
Currently biblatex supports the `eprint` field (and the related fields like `eprinttype`) in order to specify a single ID to an online databases (like arXiv). However, an entry could have more than one ID. For example, a preprint was put on the arXiv, it was published by jstor (jstor-id) and later reviewed on MathSciNet (MR-Review number). How should these IDs be represented in biblatex?

Background: I'm one of the developers of [JabRef](https://github.com/JabRef/jabref) and we are planing to improve the connection to online databases. For example, complete bibliographic information or find citation metrics. For this it is often important to know the identifier. So this is more a theoretic question how JabRef should write multiple IDs.

**Comment by plk** [comment]
Can you ask this initially on tex.stackexchange.com so it can be discussed?

**Comment by maieul** [comment]
maybe, we could allow defining generic field just by a simple command. Instead of having eprint + eprinttype, we would have MR + Jstor field, and we will define by a simple command which field would be  printed ? It is the perspective I have adopted for bibatex-claves.

**Comment by moewew** [comment]
I'm not sure how multiple eprinttypes could be implemented in `biblatex`, but right now it is easy enough to promote eprints to real fields. See for example may answers to [BibTeX fields for DOI, MR, Zbl and arxiv?](http://tex.stackexchange.com/q/151628/35864) and [Biblatex and Pubmed/Pubmed Central IDs](http://tex.stackexchange.com/q/155532/35864) on TeX.SX.

Correct me if I'm wrong. But if one wanted multiple eprints in the same field, that would have to be made a list (does a verbatim list even exist? What would be the separator? What if the separator is part of the eprint identifier? - DOIs for example contain all sorts of evil things at times.) and the list handler would have to refer to the `eprinttype` and in some cases even `eprintclass`. Then these lists would have to populated in a way to make sure that the right type and class get mapped to the right `eprint` item.

**Comment by plk** [comment]
Verbatim lists are supported.
