### ISSUE TITLE
cite:labelyear+extrayear does not localise date fields in certain situations

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#478]
Consider the following MWE where `labelyear` becomes a localisation string from the `pubstate` field.

```
\documentclass[ngerman]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage{babel}
\usepackage{csquotes}
\usepackage{filecontents}
\begin{filecontents*}{\jobname.bib}
@Article{Flecker_inpress,
  author       = {Flecker, Manuel and Lipps, Johannes and Broisch, Manuela},
  title        = {Geophysikalische Untersuchungen im sog. \emph{comitium} am Forum von Pompeji},
  journaltitle = {Kölner und Bonner Archaeologica},
  shortjournal = {KuBA},
  pubstate     = {inpress},
}
\end{filecontents*}

\usepackage[backend=biber, style=authoryear]{biblatex}
\addbibresource{\jobname.bib}

\DeclareLabeldate{%
  \field{date}
  \field{year}
  \field{eventdate}
  \field{origdate}
  \field{urldate}
  \field{pubstate}
  \literal{nodate}
}

\begin{document}
\cite{Flecker_inpress}

\printbibliography
\end{document}
```

![dudududujhshhshhshs](https://cloud.githubusercontent.com/assets/6755835/18660941/84f33226-7f13-11e6-930a-085434e26012.png)

You will find that in the bibliography the string `inpress` is nicely translated to "im Druck", but in the citation we're left with "inpress".

AFAIK this is because in `cite:labelyear+extrayear` we have a call to plain `\thefield{labelyear}` and not `\printfield{labelyear}` and so the format `\DeclareFieldFormat{labelyear}{\ifbibstring{#1}{\bibstring{#1}}{#1}}` from `biblatex.def` is  not applied.
```
     \mkyearzeros{\thefield{labelyear}}%
```

Of course `\mkyearzeros{\printfield{labelyear}}` does not work for adding zeros.
And I'm not sure if adding `\mkyearzeros` to the field format would be a viable solution: `\DeclareFieldFormat{labelyear}{\ifbibstring{#1}{\bibstring{#1}}{\mkyearzeros{#1}}}` together with using just `\printfield{labelyear}%` in `cite:labelyear+extrayear` seems to work. (But then we would apply `\mkyearzeros` more often than before. Would that be a problem?)

BTW: Shouldn't the longer code from `cite:labelyear+extrayear` also be used in the mergedate formats from `authoryear.bbx`?

**Comment by plk** [comment]
Hmm, well, spotted. I didn't notice as in my APA style tests this works but that's because I use `\printfield`. `\mkyearzeros` should be idempotent so adding it to the format may be ok. I will try it and run the test suite.

**Comment by plk** [comment]
Try the 3.7 biblatex release in the DEV folder on SF - it passes the test suite with `\mkyearzeros` put into the format.

**Comment by moewew** [comment]
Looks good.

One thing I noted though is that `\bibdateeraprefix` defaults to `\textminus` which requires an additional package (`textcomp`?) and will cause errors without it.

In the following MWE you will find that the circa marker appears in different places. (Also you probably don't want it to cause a capitalisation of the "v." in "v. Chr.")
``` 
\documentclass[ngerman]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage{babel}
\usepackage{csquotes}
\usepackage{filecontents}
\begin{filecontents*}{\jobname.bib}
@BOOK{plato,
   AUTHOR = {Plato},
   TITLE  = {Meno},
   DATE = {-0379?~}
}
\end{filecontents*}

\usepackage[backend=biber, style=authoryear, dateera=christian, dateuncertain=true]{biblatex}
\addbibresource{\jobname.bib}

\begin{document}
\cite{plato}

\printbibliography
\end{document}
```

What I fail to understand is why `cite:labelyear+extrayear` looks so complicated now, while all other bibmacros have stayed nearly the same. Does that mean that other places where dates are printed lack some of the new features? Or why does `cite:labelyear+extrayear` have to go the long way?

**Comment by plk** [comment]
`cite:labelyear+extrayear` underlays a lot of higher level macros and date formats are much more complex in `authoryear` styles. I am still not sure about the merge formats. Are you sure about `\textminus`? The `96-dates.tex` test file uses this and doesn't load `\textcomp`. I think I have fixed the capitalisation issue with 3.7.

**Comment by moewew** [comment]
If I try to run my MWE from above with the option `dateera=christian,` removed I get the error `!Undefined control sequence. \bibdateeraprefix ->\textminus` when I compile with pdfLaTeX. Your file uses `fontspec`, so I assume it is compiled with XeLaTeX/LuaLaTeX. And indeed if `fontspec` is loaded `\textminus` is known.

OK, I still can't see exactly why `cite:labelyear+extrayear` can't default to, say, `\printlabeldateextra`. I'd have thought if `cite:labelyear+extrayear` was complicated, so would be `date+extrayear` (and vice versa). But maybe I can't think of examples where the two would differ, because I haven't really understood the new date features in depth.
It just puzzles me that `cite:labelyear+extrayear` looks so daunting now and uses quite low-level stuff while everything else stayed nice and tame (why can't `cite:labelyear+extrayear` use higher-level stuff?).

**Comment by plk** [comment]
The citation commands are not very language specific in format and only7 print the year but the date formats (which are behind `\print*date`) are more heavily localised and much more specific in content. I doubt they could share the same code. I didn't realise about `\textminus` in PDFTeX Hmm, that's a bit of a pain - there was a lot of discussion about the best thing for negative dates.

**Comment by moewew** [comment]
Ahhh, OK. I wonder if it was worth wrapping that in a higher-level command (with option for modification)...

Yes, minuses in text mode are a pain in general (see [Is there a designated symbol for the negative sign in, say, -16?](http://tex.stackexchange.com/q/79141/35864) on TeX.SX for example). Maybe we have to go with an en-dash after all, but you could test if `\textminus` is defined and if so use that.

**Comment by plk** [comment]
3.7 fixes the `\textminus` issue - defaults to `\textendash` when not defined now. I'm not sure about wrapping the cite commands as I can't think where else they would be useful. Custom styles would almost certainly need to modify the low-level details anyway?

**Comment by moewew** [comment]
Yes, thank you. A minor quibble though: It's not non PDF-TeX, it's additional packages that provide the command (`textcomp` for pdfLaTeX, `fontspec` for LuaLaTeX/XeLaTeX - since the latter is recommended, it will almost always be loaded, `textcomp` less so).

I guess I just object to so many low-level commands in the `.cbx`. But I take your point.
