### ISSUE TITLE
Manual: wrong version number?

### ISSUE THREAD

**Issue by nickbart1980** [plk/biblatex#479]
The most recent http://mirrors.ctan.org/macros/latex/contrib/biblatex/latex/biblatex.sty contains `\def\abx@date{2016/09/17}
\def\abx@version{3.6}`.

whereas http://mirrors.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf has “Version 3.5 September 14, 2016”.

Shouldn’t this be “3.6”, too?

**Comment by plk** [comment]
Yes, it should. That's odd.
