### ISSUE TITLE
[handbook] DeclareStyleSourcemap applied before inheritance

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#484]
In order to solve #482, I try to manage with 

`````
\DeclareStyleSourcemap{%
  	\maps[datatype=bibtex]{%
  		\map[overwrite=false]{%
  			\pertype{book}%
			  \pertype{collection}%
			  \pertype{proceedings}%
			  \pertype{reference}%
			  \step[fieldsource=maintitle]
			  \step[origfieldval,fieldset=sorttitle]%
  			}%
    }
}
````` 

But that does'not work if the `maintitle` field is inherited, as that is applied before inheritance.

I think a paragraph which will summarize the step used by biber would be nicefull.

For example:
1. Source Mapping
2. Inheritance
3. Sorting

**Comment by plk** [comment]
Actually, this is already on p.8 of the biber manual ...

**Comment by maieul** [comment]
you are right;-) 
I forget to many time to read the biber handbook.
I think we could close this issue.

**Comment by plk** [comment]
I added a comment to the `biblatex` docs too.
