### ISSUE TITLE
`sortcites` does not work with multiple bibliographies

### ISSUE THREAD

**Issue by DigNative** [plk/biblatex#491]
I noticed that the `sortcites` option of BibLaTeX does not work as expected (i.e. multiple citations are not sorted numerically ascending) when using multiple bibliographies. Please consider the following MWE:

    \documentclass{article}

    \begin{filecontents}{example.bib}
        @article{ahu61,
           author={Arrow, Kenneth J. and Leonid Hurwicz and Hirofumi Uzawa},
           title={Constraint qualifications in maximization problems},
           journal={Naval Research Logistics Quarterly},
           volume={8},
           year=1961,
           pages={175-191},
           keywords={A}
        }

        @book{ab94,
           author={Charalambos D. Aliprantis and Kim C. Border},
           year={1994},
           title={Infinite Dimensional Analysis},
           publisher={Springer},
           address={Berlin},
           keywords={B}
        }
    \end{filecontents}

    \usepackage[defernumbers=true, sortcites=true]{biblatex}
    \addbibresource{example.bib}

    \begin{document}

        Multiple citations \cite{ab94,ahu61} in wrong order.

        \section*{References, Part A}
        \printbibliography[heading=none, keyword={A}]
        
        \section*{References, Part B}
        \printbibliography[heading=none, keyword={B}]

    \end{document}

I think this is a bug in BibLaTeX and would appreciate any investigation.

**Comment by plk** [comment]
This looks correct - the default sorting scheme is `nty` and therefore the cites should be sorted in name order.

**Comment by DigNative** [comment]
Thank you very much for looking over the MWE and for your reply. I may have gotten the sense of `sortcites` wrong, but my intention is to sort multiple citations within one `\cite` command numerically ascending, no matter what sorting scheme for the bibliography is being used (similar to what the `cite` package does). According to the documentation this could be achieved with the `sortcites` option, which works in case only one bibliography is used throughout the document. However, when using multiple bibliographies, the numeric citation labels are not sorted anymore, as demonstrated with the above MWE.

How do I achieve a numerically ascending sorting of the citation label in this case?

**Comment by plk** [comment]
Hmm, this is very tricky. Since you are using `defernumbers` and split bibliographies,  this isn't really possible since the labels are generated very late in processing. Sorting by numeric label in general, especially with `defernumbers` isn't really possible currently and it has never been requested as you never need/want to do this for the bibliography. For sorting citations, you can either order the citations as you want or sort by any sorting scheme you like but that doesn't include sorting by label as sorting schemes are for bibliographies and as I mentioned, it is never useful to do this by label.

**Comment by DigNative** [comment]
Thank you again for your answer. I am not sure if we got each other right, so just to clarify: My use case would be to have multiple bibliography sections (e.g. split by topic) while using `defernumbers` to ensure a continuous ascending numerical numbering across the entries in the bibliography sections. The sorting in these bibliography sections is being done with a standard sorting scheme, e.g. the author names in ascending alphabetical order.

Now, when I want to cite multiple entries in the bibliography sections at once, I would wish that the citation labels printed in the text are sorted numerically ascending, no matter in what specific order I put the individual cite keys into the `\cite` macro. Here is an example:

    Lorem ipsum dolor sit amet, consectetur [1, 3, 4] (produced with \cite{ak, aj, ra})
    adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
    ex ea commodo consequat.

    References
    
        Topic A                                             {cite key}
        
            [1] Andrews, J.: "A meaningful title".          {aj}
            [2] Carlson, R.: "Another title".               {cr}
            [3] Richards, A.: "I am not very creative".     {ra}
            
        Topic B
        
            [4] Aalborg, K.: "Completely different topic".  {ak}
            [5] Young, S.: "Now I am finished".             {ys}

Is this also the use case you described? I don't think that this use case is uncommon when using multiple bibliography sections.

I could imagine (without knowing the internals of BibLaTeX) that it should be possible to sort these labels one run after the labels to the bibliography entries have been assigned with the additional run for `defernumbers`.

**Comment by plk** [comment]
Can you ask this on tex.stackexchange.com? I am not sure if this has been asked before and I can't quite remember. If nothing turns up, I think it may need a new feature.

**Comment by DigNative** [comment]
After some research, I found [this question on tex.stackexchange.com](https://tex.stackexchange.com/questions/273313/biblatex-sort-cites-via-number-split-bibliography), which describes pretty much the same situation. The solution given here is to use `\DeclareSourcemap` to instruct Biber to presort the bibliography entries according to the desired division of the bibliography in the document. I tried to compile examples for this.

### Without Presorting

**Without presorting** the situation is like this (the bold characters after each bibliography entry show the cite keys used within the bib file; the bib file used is located at the bottom of this comment):

    \documentclass{article}
    \usepackage[
        defernumbers=true,          % continuous numbering across bibliography sections
        sortcites=true,             % sort citations if multiple entry keys are passed
                                    %   to a citation command, e.g. \cite{a,b,c}
        citestyle=numeric-comp      % compact variant of numeric, which prints a list
                                    %   of more than two consecutive numbers as a range
    ]{biblatex}
    \addbibresource{example.bib}
    
    % to show the corresponding entry keys after the individual
    % entries within the bibliography
    \renewbibmacro{finentry}{\finentry\space\textbf{(\thefield{entrykey})}}

    \begin{document}

        \textbf{Examples:}
        \begin{itemize}
            \item Multiple citations \cite{c,d,f,a,i,h} not sorted numerically ascending;
                  should be \verb|[2--4, 8--10]|.
            \item Multiple citations \cite{d,f,a,i,h} not sorted numerically ascending;
                  should be \verb|[2--4, 8, 10]|.
        \end{itemize}

        \nocite{*}
        \section*{References, Part A}
        \printbibliography[heading=none, keyword={A}]
        
        \section*{References, Part B}
        \printbibliography[heading=none, keyword={B}]

    \end{document}

![without_presort](https://cloud.githubusercontent.com/assets/1613087/19019547/382b9a6e-888c-11e6-8f9b-5a1d40da2dd9.png)

### With Presorting Using Biber

**With presorting** using `\DeclareSourcemap` I get the following result:

    \documentclass{article}
    \usepackage[
        defernumbers=true,          % continuous numbering across bibliography sections
        sortcites=true,             % sort citations if multiple entry keys are passed
                                    %   to a citation command, e.g. \cite{a,b,c}
        citestyle=numeric-comp      % compact variant of numeric, which prints a list
                                    %   of more than two consecutive numbers as a range
    ]{biblatex}
    \addbibresource{example.bib}
    
    % to show the corresponding entry keys after the individual
    % entries within the bibliography
    \renewbibmacro{finentry}{\finentry\space\textbf{(\thefield{entrykey})}}
    
    \DeclareSourcemap{
      \maps[datatype=bibtex]{
        \map{
          \step[fieldsource=keywords, match={A}, final]
          \step[fieldset=presort, fieldvalue = {A}]
        }
        \map{
          \step[fieldset=presort, fieldvalue = {B}]
        }
      }
    }

    \begin{document}

        \textbf{Examples:}
        \begin{itemize}
            \item Multiple citations \cite{c,d,f,a,i,h} sorted numerically ascending and
                  compressed; expectation \verb|[2--4, 8--10]| met.
            \item Multiple citations \cite{d,f,a,i,h} sorted numerically ascending and
                  compressed; expectation \verb|[2--4, 8, 10]| met
        \end{itemize}

        \nocite{*}
        \section*{References, Part A}
        \printbibliography[heading=none, keyword={A}]
        
        \section*{References, Part B}
        \printbibliography[heading=none, keyword={B}]

    \end{document}

![with_presort](https://cloud.githubusercontent.com/assets/1613087/19019568/dd62bfd0-888c-11e6-8e6f-afdc26486ff7.png)

### Concluding Remarks

With this workaround it seems to be possible to achieve the desired behavior; however, I am using complex filters (defined with `\defbibfilter`) in my documents to assign individual bibliography entries to certain bibliography sections. I am not sure if it is possible/how easy it is to transfer this logic to a presort directive for `\DeclareSourcemap`. Anyway, it would double the effort since one would have to double the logic both for `\defbibfilter` and for `\DeclareSourcemap`.

I would prefer a solution without having such kind of double effort.


### example BibTeX database

    @INPROCEEDINGS{a,
        author = {Kishore Papineni and Salim Roukos and Todd Ward and Wei-Jing Zhu},
        title = {BLEU: A method for automatic evaluation of machine translation},
        booktitle = {In Proceedings of the 40th Annual Meeting on Association for Computational Linguistics},
        year = {2002},
        pages = {311--318},
        keywords = {A}
    }

    @INPROCEEDINGS{b,
        author = {D D Clark},
        title = {The design philosophy of the DARPA internet protocols},
        booktitle = {in ACM SIGCOMM},
        year = {1988},
        pages = {106--114},
        keywords = {B}
    }

    @INPROCEEDINGS{c,
        author = {Muthu Muthukrishnan},
        title = {Data Streams: Algorithms and Applications},
        booktitle = {of Foundations and Trends in Theoretical Computer Science. Now Publishers Inc},
        year = {2005},
        keywords = {B}
    }

    @ARTICLE{d,
        author = {R Koenker and G Basset},
        title = {Regression Quantiles},
        journal = {Eco- nometrica},
        year = {1978},
        number = {46},
        pages = {33--50},
        keywords = {A}
    }

    @MISC{e,
        author = {Michael Wilkinson Institute and Michael H. F. Wilkinson},
        title = {FIRST PUBLISHED IN ANNALS OF IMPROBABLE RESEARCH, VOL. 8, NO. 4, PP. 6-7 1 Zero-Tolerance Math: A Defense of "No Math"},
        year = {},
        keywords = {B}
    }

    @ARTICLE{f,
        author = {R M Neal},
        title = {Markov chain sampling methods for dirichlet process mixture models},
        journal = {Journal of Computational and Graphical Statistics},
        year = {2000},
        number = {9},
        pages = {249--265},
        keywords = {A}
    }

    @ARTICLE{g,
        author = {K P Birman},
        title = {The process group approach to reliable distributed computing},
        journal = {Communications of the ACM},
        year = {1993},
        number = {36},
        pages = {37--53},
        keywords = {A}
    }

    @ARTICLE{h,
        author = {Joxan Jaffar and Michael J Maher},
        title = {Constraint logic programming: A survey},
        journal = {Journal of Logic Programming},
        year = {1994},
        number = {19},
        pages = {581},
        keywords = {B}
    }

    @INPROCEEDINGS{i,
        author = {M J Wainwright and M I Jordan},
        title = {Graphical models, exponential families, and variational inference},
        booktitle = {Foundations and Trends R© in Machine Learning},
        year = {2008},
        keywords = {B}
    }

    @MISC{j,
        author = {K Train},
        title = {Discrete choice methods with simulation},
        year = {2003},
        keywords = {A}
    }

**Comment by plk** [comment]
You might try asking on TSE about this specific case - I'd rather not put extra things in the core which a are edge cases unless there is a real need.

**Comment by moewew** [comment]
Mhhh, I believe it is easy enough to solve this problem for 'simple' split bibliographies (e.g. those split by type, keyword, ...), but if things become more complicated one has to try and recreate the filters/checks with Biber's sourcemapping as @DigNative rightly remarks. I don't think that is a particularly nice solution.

**Comment by DigNative** [comment]
As requested, I opened up [a question on TeX.SX](https://tex.stackexchange.com/questions/332234/biblatex-citation-sorting-with-split-bibliographies-and-filters).

**Comment by plk** [comment]
I'll close this for now until there is a reply on TSE.

**Comment by DigNative** [comment]
There is not a single comment on TeX.SX since I posted the question more than a week ago. I don't expect any replies there.

**Comment by plk** [comment]
I expect there will be - it's a complex question but there are some dedicated experts there who usually take the time to answer when the have a chance. It is very rare that a question so comprehensively described is not answered.
