### ISSUE TITLE
Extended name format: abbreviating “Philippe” to “Ph.”

### ISSUE THREAD

**Issue by nickbart1980** [plk/biblatex#492]
To abbreviate a first name such as “Philippe” to “Ph.”, the traditional recommendation is to use `author = {Dubois, {\relax Ph}ilippe}` (e.g., http://tug.ctan.org/info/bibtex/tamethebeast/ttb_en.pdf). This does work with biblatex/biber (see the “Dubois” entry).

With the new extended name format, `author = {family=Duchamp, given=Philippe, given-i=Ph}` should be expected to work, but this gives “P. h.” (see the “Duchamp” entry).

 → Anything wrong with the syntax I used?

Finally, trying `author = {family=Dumas, given={\relax Ph}ilippe}` crashes with

~~~
Runaway argument?
{{{uniquename=0,hash=89de0feff45392f22daa185973c94330}{family={Dumas}\ETC.
! Paragraph ended before \name was complete.
<to be read again> 
                   \par 
l.76 
~~~

 → Shouldn’t this work just like the “Dubois” entry?

MWE:

~~~
\documentclass{article}
\usepackage[backend=biber, style=authoryear, giveninits=true]{biblatex}
\usepackage{fontspec}
\setmainfont{Linux Libertine}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{dubois,
  author = {Dubois, {\relax Ph}ilippe},
}
@book{duchamp,
  author = {family=Duchamp, given=Philippe, given-i=Ph},
}
@book{dumas,
  author = {family=Dumas, given={\relax Ph}ilippe},
}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}
\cite{dubois, duchamp}
%\cite{dumas}
\printbibliography
\end{document}
~~~

Output:

![screen shot 2016-10-07 at 19 37 18](https://cloud.githubusercontent.com/assets/2765811/19201482/8eaf92ac-8cbd-11e6-93c7-9841a52a5ba8.png)

**Comment by plk** [comment]
This was a bug. You can do this now with biber 2.7 DEV and biblatex 3.7 DEV by using the usual brace protection:

`author = {family=Duchamp, given=Philippe, given-i={Ph}},`
