### ISSUE TITLE
Label date not localized in biblatex 3.6

### ISSUE THREAD

**Issue by CarlOrff** [plk/biblatex#494]
If I do the following minimal example the nodate string is evaluated in the bibliography but not in the label. And it doesn't help if I \DeclareLabeldate myself.

    \documentclass{article}
    \begin{filecontents*}{\jobname.bib}
    @Online{test,
    author         = {Author, Andrew},
    title         = {Title},
    location = {Somewhere},
    }
    \end{filecontents*}
    \usepackage[style=authoryear]{biblatex}
    \addbibresource{\jobname.bib}

    \begin{document}
    \autocite{test}
    \printbibliography
    \end{document}

**Comment by plk** [comment]
I believe that this is already fixed in biblatex 3.7/biber 2.7 - can you try these?

**Comment by CarlOrff** [comment]
It's seems not so easy to install biber into a Windows TexLive. But if you are aware of this, I wait. Thanks for your efforts.

**Comment by plk** [comment]
It is easy to install - you can ask on tex.stackexchange.com - such installation has already probably been described there.

**Comment by CarlOrff** [comment]
Works in 3.7.

Sorry, I wasn't aware that there are two different Windows binaries. Simply had the wrong one.
