### ISSUE TITLE
New DOI URLs

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#495]
Via http://latex-community.org/forum/viewtopic.php?f=50&t=28552

Apparently the DOI people have changed the URLs for DOI resolution. The new preferred URL drops the `dx` part: `http://doi.org/10.1000/demo_DOI`. The servers also support HTTPS and so I'd propose to link to `https://doi.org/10.1000/demo_DOI`. See https://www.doi.org/doi_handbook/3_Resolution.html

The new `doi` format would look like this
```
\DeclareFieldFormat{doi}{%
  \mkbibacro{DOI}\addcolon\space
  \ifhyperref
    {\href{https://doi.org/#1}{\nolinkurl{#1}}}
    {\nolinkurl{#1}}}
```

**Comment by plk** [comment]
Fixed on DEV branch.

**Comment by moewew** [comment]
Thank you very much.
