### ISSUE TITLE
Biblatex ignores \DeclareLanguageMapping if variant does not inherit strings

### ISSUE THREAD

**Issue by Dabsen** [plk/biblatex#496]
As has already been noted in issue #40 , it seems biblatex will ignore language variants 
if they do not inherit from the main language. More precisely, a directive like
`\DeclareLanguageMapping{french}{french-humanities}`
will have no effect if french-humanities.lbx does not contain explicit inheritance directives like
`\DeclareBibliographyStrings{
inherit = {french},
[…]
}`
My impression (based on latex compilation output) is that if there is inheritance, biblatex loads french.lbx *before* french-humanities.lbx and all goes well, whereas without inheritance, biblatex will end up loading french.lbx anyway, but *after* french-humanities.lbx, thereby overriding any changes. This behavior is counter-intuitive and should be documented, as trying to create a variant by copying the whole original file and altering it is bound to fail.

**Comment by plk** [comment]
I have modified the doc in the DEV branch to say that the inheritance should be used. There is really no need to redefine the whole language file anyway and I don't think anyone ever does this.
