### ISSUE TITLE
\namepart[use=false]{prefix} doesn’t seem to work in Label definition

### ISSUE THREAD

**Issue by georgd** [plk/biblatex#497]
I’m trying to disable name prefixes in label creation but it doesn’t work with `\namepart[use=false]{prefix}` as I’d have assumed from reading the manual. It does, however, with `\namepart[pre=true,strwidth=0]{prefix}`.

MWE:

```latex
\documentclass{scrartcl}
\usepackage{filecontents}
\begin{filecontents*}{\jobname.bib}
 @Book{Go10,
  author    = {Johann Wolfgang von Goethe},
  title     = {Farbenlehre},
  year      = {1810},
  volumes   = {2},
  publisher = {Cotta},
  location  = {Tübingen},
}
\end{filecontents*}
\usepackage[           
  backend=biber,
  style=alphabetic
]{biblatex}
% Don't use prefixes in labels
\DeclareLabelalphaNameTemplate{
  \namepart[use=false]{prefix} % this doesn't work!?
%   \namepart[pre=true,strwidth=0]{prefix}
  \namepart{family}
}
\addbibresource{\jobname.bib}
\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

**Comment by plk** [comment]
Actually, the correct setting for what you want is `use=true`. The `use` option on a namepart X determines whether the `\namepart` obeys the biblatex option `useX`. So, since the biblatex `useprefix` option in your example is false, setting:

`\namepart[use=true]{prefix}`

makes the namepart obey `useprefix=false` ...

**Comment by georgd** [comment]
Ok, It’s not very clear from the documentation.  
I  came across the problem in a style that uses `useprefix=true`. According to your explanation there really `\namepart[use=false]{prefix}` should remove prefixes from label construction but it doesn’t (`\namepart[use=true]{prefix}` doesn’t either).  

Here again a MWE:
```latex
\documentclass{scrartcl}

\usepackage{filecontents}
\begin{filecontents*}{\jobname.bib}
 @Book{Go10,
  author    = {Johann Wolfgang von Goethe},
  title     = {Farbenlehre},
  year      = {1810},
  volumes   = {2},
  publisher = {Cotta},
  location  = {Tübingen},
}
\end{filecontents*}
\begin{filecontents*}{test.bbx}
 \ProvidesFile{test.bbx}
 \RequireBibliographyStyle{alphabetic}
 \ExecuteBibliographyOptions{%
  useprefix     = true,
 }
  % Don't use prefixes in labels
 \DeclareLabelalphaNameTemplate{
  \namepart[use=false]{prefix} % this doesn't work!?
%   \namepart[pre=true,strwidth=0]{prefix}
  \namepart{family}
 }
 \endinput
}
\end{filecontents*}
\begin{filecontents*}{test.cbx}
 \ProvidesFile{test.cbx}
  \RequireCitationStyle{alphabetic}
 \endinput
\end{filecontents*}

\usepackage[           
  backend=biber,
  style=test
]{biblatex}
\addbibresource{\jobname.bib}

\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

Also, shouldn’t the declaration `\namepart[strwidth=0]{prefix}` alone have the same effect?

**Comment by plk** [comment]
The example you give is also correct: you've just said "add a prefix, ignoring the useprefix global option". It's quite simple really, if you don't want prefices in labels, just delete the `\namepart...{prefix}` completely from the specification. The `use` option is just there to allow prefices to be controlled by the global `useprefix` option.

**Comment by georgd** [comment]
Thank you, now I’m enlightened. It’s indeed much simpler than I thought. But why does the `strwidth=0` option not have this effect?

**Comment by plk** [comment]
That could be considered a bug but I never envisaged anyone would try to suppress a namepart by doing that because really, you should just remove that namepart from the specification ...

**Comment by georgd** [comment]
Of course. Thank you very much!
