### ISSUE TITLE
\ifgiveninits ignores option

### ISSUE THREAD

**Issue by CarlOrff** [plk/biblatex#501]
The \ifnamepartinits tests always return true here, even in biblatex 3.7 (10-17).

    \documentclass{article}
    \begin{filecontents*}{\jobname.bib}
    @Book{augustine,
    hyphenation   = {american},
    author    = {Augusteine, Robert L.},
    title         = {Heterogeneous catalysis for the synthetic chemist},
    shorttitle    = {Heterogeneous catalysis},
    publisher     = {Marcel Dekker},
    location      = {New York},
    edition={5}
    }
    \end{filecontents*}
    \usepackage[style=authoryear-ibid,giveninits=false,familyinits=false]{biblatex}
    \addbibresource{\jobname.bib}
    \usepackage{xpatch}

    \xpretobibmacro{author}{\ifgiveninits{TRUE }{FALSE }}{}{}
    \xapptobibmacro{author}{\iffamilyinits{ TRUE}{ FALSE}}{}{}

    \begin{document}
    \autocite{augustine}
    \printbibliography
    \end{document}

**Comment by moewew** [comment]
This could be a problem with the definitions of the `...inits` options. In `biblatex.sty` we find
```
\def\do#1{%
  \newtoggle{abx@bool@#1inits}%
  \appto\blx@blxinit{%
    \csdef{if#1inits}{\iftoggle{abx@bool@#1inits}}%
    \appto\blx@TE@hook{%
      \csdef{if#1inits}{\blx@TE{\iftoggle{abx@bool@#1inits}}}}}%
  \DeclareBibliographyOption[boolean]{#1inits}[true]{%
    \toggletrue{abx@bool@#1inits}%
    \toggletrue{abx@bool@xinits}}}
\abx@donameparts
```

That is the option will always toggle to true regardless of the value.

I suggest
```
\def\do#1{%
  \newtoggle{abx@bool@#1inits}%
  \appto\blx@blxinit{%
    \csdef{if#1inits}{\iftoggle{abx@bool@#1inits}}%
    \appto\blx@TE@hook{%
      \csdef{if#1inits}{\blx@TE{\iftoggle{abx@bool@#1inits}}}}}%
  \DeclareBibliographyOption[boolean]{#1inits}[true]{%
    \settoggle{abx@bool@#1inits}{##1}%
    \ifstrequal{##1}{true}
      {\toggletrue{abx@bool@xinits}}
      {}}}
\abx@donameparts
```

I will do some testing tomorrow and if things work out, I can submit a pull request.

**Comment by plk** [comment]
Yes, this looks like a bug - if you can test it, that would be good.

**Comment by moewew** [comment]
Will do some more investigating tomorrow. I suspect the fix should be right, but I'm not entirely sure about whether it does the best thing for `abx@bool@xinits`.

**Comment by plk** [comment]
Hmm, xinits is tricky as is should be true if _any_ *inits options are true but false only if _all_ are false.

**Comment by moewew** [comment]
Logically, the suggested code above should do the right thing for `xinits` assuming that there is no other way to toggle inits on than the option and that initially everything defaults to false.

Wait, there is one caveat: If we have set the same option to `true` before and now set it to `false` (while all other nameparts are already `false`) that would mean `xinits` remains `true`.
At first I thought that to be a minor issue, but it definitely isn't. We need a way around that.

**Comment by moewew** [comment]
Since `xinits` is basically an OR over all `*inits` we could go with

```
\def\do#1{%
  \newtoggle{abx@bool@#1inits}%
  \appto\blx@blxinit{%
    \csdef{if#1inits}{\iftoggle{abx@bool@#1inits}}%
    \appto\blx@TE@hook{%
      \csdef{if#1inits}{\blx@TE{\iftoggle{abx@bool@#1inits}}}}}%
  \DeclareBibliographyOption[boolean]{#1inits}[true]{%
    \settoggle{abx@bool@#1inits}{##1}%
    \togglefalse{abx@bool@xinits}
    \def\do####1{\iftoggle{abx@bool@####1inits}{\toggletrue{abx@bool@xinits}}{}}
    \abx@donameparts
  }}
\abx@donameparts
```

Here of course `xinits` is re-calculated every time an `*inits` option is used. It might be a better idea to only calculate `xinits` once and for all at the end of the preamble or only the once it is needed in that hook. 

I will hopefully be able to wrap the second suggestion up in a pull request soon.

**Comment by plk** [comment]
Yes, great. I also assumed it would require a loop for xinits.

**Comment by moewew** [comment]
Note that the pull request just added only calculates `xinits` in `\AtEndPreamble` where it is needed. The last code suggestion above re-calculates `xinits` all the time a `*inits` option is used.

**Comment by moewew** [comment]
Oh, yes you were quick to comment.

I think it is the only way to really get things right here.

**Comment by moewew** [comment]
@CarlOrff Can you confirm that the new version of `biblatex` 3.7 fixes the issue (PLK has already uploaded the fixed version to sourceforge as well)?

**Comment by CarlOrff** [comment]
Yes, looks good! Thank you very much for your efforts!

**Comment by plk** [comment]
Thanks @moewew.
