### ISSUE TITLE
sorting scheme: option by entrytype

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#502]
Hi, 

In my thesis, thesis, I have around 3718 entries. But as I use for some specifiy entries (`@manuscript`) a specific sorting scheme, I have finally a big .bbl file with 7436 entry, and, added to the main text of my thesis, that make a ouput with `[main memory size=5000000]`. 

I have read #463, but it works only with \newrefsection, and I don't want to have new refsection, as the entry on the final bibliography depend of the main text.

Here, for example, what I do in my final bibliography

```
\begin{refcontext}[sorting=manuscripts]
\manuscriptsupprimepages
\printbibliography[title={Manuscrits},subtype=ms,check=ms_principaux]
\end{refcontext}
\printbibliography[title={Textes sur Barnabé},subtype=Barnabé,check=principal]
```

the best way to solve my problem would be to create a mixt sorting scheme, which will make myseflf to use only one refsection, which is better.

But should not be possible to have the possibility to add, in the sorting scheme, a way to conditionnate sorting to the type of entry.

Typically, I would need:
- sorting system for @manuscript entries
- sorting system of other type entries

**Comment by plk** [comment]
This has been discussed before - sorting schemes which differ between entrytypes is really not a good idea as you would potentially be comparing fields with different datatypes at certain points and that will not work with a strongly typed sorting system (which is the best type and which is what biber uses). It will really complicate things a lot at the very best.

**Comment by maieul** [comment]
Yes, I agree on this point. You are right, and that what is my problem for mixing my two sorting scheme --- but fortunately, it seems there is no commond field between the different datatype, except location, but it could be use after that.

In this case, a way to solve my problem of to big bbl file, except increasing memory, could be to have a mecanism to make basic filter of entry directly in the .bbl file, depending of the refcontext

for example \newrefcontext[type=manuscript] will we add in my specific sorted list ONLY the @manuscript entries

**Comment by plk** [comment]
This is quite complicated to do. I have not looked at it because memory is rarely an issue these days ...

**Comment by maieul** [comment]
for now, I have avoided the problem using `main_memory = 7999999` in my texmf.cnf. As LuaLaTeX as dynamic allocation of memory, it could be also a solution. But for big bibliography, the problem could still occur with XeLaTeX of pdfLaTeX
