### ISSUE TITLE
day disappeared from printed bibliography

### ISSUE THREAD

**Issue by LeonMeier** [plk/biblatex#505]
Consider the following input. 

File test.tex:
`\documentclass{book}
\usepackage[backend=biber]{biblatex}
\addbibresource{biblio.bib}
\begin{document}
Let's cite: \cite{Author-Title-misc,Author-Title-online,Author-Title-unpublished}.
\printbibliography
\end{document}
`

File biblio.bib:
`@misc{Author-Title-misc,
  title = {Title},
  author = {Author},
  year = 2010,
  month = jan,
  day = 1
}

@online{Author-Title-online,
  title = {Title},
  author = {Author},
  year = 2010,
  month = jan,
  day = 1,
  url={http://www.heise.de},
}

@unpublished{Author-Title-unpublished,
  title = {Title},
  author = {Author},
  year = 2010,
  month = jan,
  day = 1
}
`

The compilation goes via pdflatex and biber (version 2.6).

- Compiling with an old pdflatex version 3.14159265-2.6-1.40.16 (TeX Live 2015) and biblatex 2015/04/19 v3.0 gives us the three day numbers 1 in the bibliography.

- Compiling with a newer pdflatex version 3.14159265-2.6-1.40.17 (TeX Live 2016) and biblatex 2016/09/17 v3.6 gives us no day number in the bibliography.

A bug? I did not find that a note on a change of behavior wrt. "day" in the biblatex documentation.

**Comment by plk** [comment]
The date handling is now EDTF compliant and the `day` field was never really officially supported. `year` and `month` are also considered legacy now and you should use the `date` field.

**Comment by LeonMeier** [comment]
Ok, thanks!
