### ISSUE TITLE
Change \DeclarePrefChars default to ', ’, and -

### ISSUE THREAD

**Issue by njbart** [plk/biblatex#506]
I'd like to suggest changing the `\DeclarePrefChars` default setting from `\DeclarePrefChars{'}` to `\DeclarePrefChars{'’-}`, i.e., adding smart apostrophe and hyphen. 

Data sources might use the smart apostrophe instead of the dumb one, and the hyphen is another punctuation character appearing between a name prefix and a family name after which no space must be inserted.

**Comment by plk** [comment]
@aboruvka - @josephwright  - any comments?

**Comment by plk** [comment]
This is reasonable and done in the dev branch.

**Comment by moewew** [comment]
This caused problems with certain non-Unicode engines (#659) and did not even work properly with pdfLaTeX (but did not cause an error there).

`’` is now a PrefChar only for Unicode engines that can deal with this properly.
