### ISSUE TITLE
Style authoring. Authoryear native style changes to better support small overrides in custom styles?

### ISSUE THREAD

**Issue by JohnLukeBentley** [plk/biblatex#513]
I'm attempting to author my own biblatex style and have an issue setting this up properly.

My aim is to make some small modifications to what the `authoryear` style achieves. I *have* been successful by:

1.  Copying ...

    "C:\Program Files\MiKTeX 2.9\tex\latex\biblatex\bbx\authoryear.bbx"
    "C:\Program Files\MiKTeX 2.9\tex\latex\biblatex\cbx\authoryear.cbx"

    To (and renaming them)

    "C:\MyDevFolder\authoryear-jlb.cbx" % "jlb" are my initials.
    "C:\MyDevFolder\authoryear-jlb.bbx"

2.  Altering the \ProvidesFile command in each of these files, respectively:

    \ProvidesFile{authoryear-jlb.cbx}
    \ProvidesFile{authoryear-jlb.bbx}

    ... and ....

3.  Modifying my Tex source file biblatex option to `style=authoryear-jlb`.

That is, when I merely copy all the code in authoryear* files and make small changes. 

While that works, the problem with that approach is that it is not going to pick up on most of the improvements or bug fixes made to the native `authoryear` style. I'd rather base my style on `authoryear` and just have my small code changes override it in the limited relevant areas. That way improvements to the native  `authoryear` style that I don't override are (probably) going to flow through to me for free.

And indeed it appears Biblatex is architectured to allow this sort of thing, chiefly through the `\RequireBibliographyStyle` and `\RequireBibliographyStyle` commands. 

So I can also successfully alter my authoryear-jlb.cbx so that it only contains a small override of `authoryear` ....

    \ProvidesFile{authoryear-jlb.cbx}
    [\abx@cbxid]

    \RequireCitationStyle{authoryear}

    \newbibmacro*{cite:labelyear+extrayear}{%
      \printtext{TEST TEXT} % my custom code goes here
    }
    \endinput

That works as expected: any modifications to the native `authoryear.cbx` are now going to flow through to my `authoryear-jlb.cbx`, excepting for the `cite:labelyear+extrayear` macro in virtue of my redefining it.

However, when I attempt to override the native `authoryear` style in my `authoryear-jlb.bbx` it doesn't work ....

    \ProvidesFile{authoryear-jlb.bbx}
    [\abx@bbxid]

    \RequireBibliographyStyle{authoryear}

    % merge date with date label
    \def\bbx@opt@mergedate@compact{%
      \renewbibmacro*{date+extrayear}{%
      % JLB Start *********************%
      % My custom code goes here. E.g.
      \printtext{Test} 
      % JLB End   *********************
      \renewbibmacro*{date}{}%
      \renewbibmacro*{issue+date}{%
        \iffieldundef{issue}
          {}
          {\printtext[parens]{\printfield{issue}}}%
        \newunit}}

    \endinput

... When I run my source tex file my custom `\def\bbx@opt@mergedate@compact` (in `authoryear-jlb.bbx`)  appears to be ignored and, rather, the native `authoryear`  `\def\bbx@opt@mergedate@compact`  command appears to run.

Would it be necessary, or desirable, for you @plk (as biblatex maintainer) to change mergedate commands (`\def\bbx@opt@mergedate@compact` above, for example), in the native `authoryear` style, to be implemented as `\newbibmacro`s, rather than `def`s, so that I can override them using `\renewbibmacro`? 

Or am I missing a basic overriding technique with respect to `def`s and the sequence in which biblatex loads files?

Edit: Grammar.
Edit: Added "(in `authoryear-jlb.bbx`)".

**Comment by moewew** [comment]
In general this already works, you just run into a particularity of the implementation for the `mergedate` option.

If you look closely at what you are doing in your `.bbx`, you'll find that you define a macro (`\bbx@opt@mergedate@compact`) that *upon execution* redefines several bibmacros in a way that you seem appropriate. Note that the changes are only applied once the macro is executed. As a matter of fact that macro is already defined in `authoryear.bbx`, so you overwrite the original definition of said macro.

The `\bbx@opt@mergedate@<mo>` macro is executed whenever you have `\ExecuteBibliographyOptions{mergedate=<mo>}` or load the package with the option `mergedate=<mo>`. In `authoryear.bbx` you will find such a directive (you'll find `\ExecuteBibliographyOptions{labeldateparts,sorting=nyt,pagetracker,mergedate}`, which because of some other peculiarities comes down to (for `mergedate` at least) `\ExecuteBibliographyOptions{mergedate=compact}`), which means that `\bbx@opt@mergedate@compact` is executed. But at that point you have yet not overwritten the macro definition. So indeed you get the old code from `authoryear.bbx`.

It should work for you if you simply insert an explicit `\ExecuteBibliographyOptions{mergedate=compact}` *after* your redefinition of `\bbx@opt@mergedate@compact`. Because then your new stuff is executed.

If you don't really care about keeping the `mergedate` option alive you could alternatively, just leave out the `\def\bbx@opt@mergedate@compact` bit and redefine the involved macros `date+extrayear` and friends directly.

Note that your code example some closing curly brace is missing (probably after your `% JLB End   *********************` block).

Furthermore, you probably don't want to keep the `[\abx@cbxid]`, which means that your modified files identify themselves with the current `biblatex` version but rather something like `[2016/11/16 v 1 JLB's modification to authoryear.cbx]`.

**Comment by JohnLukeBentley** [comment]
Thanks @moewew, everything you've written makes sense and teaches me a great deal.  The relevant `\ExecuteBibliographyOptions` command after my redefinition now makes it all work.

I was missing a curly brace. That was an error only in the copying of my example. Sorry for that. 

Thanks for the other tips: the proper version string; and the possibility to bypass `mergedate` altogether.

I now regret not posting this on Stack Exchange, given the issue was at my end. But, for the sake of having one place to complete the enquiry,: what's the best practice for creating and referencing a set of commands common to both `custom.bbx` and `custom.cbx`? In other words, I'm looking for the proper place for  my global `\newbibmacro`s (or `\newcommand`s or `\def`s).

I'm not clear if I should: 

* Create a `biblatex-custom.def`; or
* Use latex native commands like  \include; or
* Create a package; or
* Just include the set of commands in `custom.bbx` which I also reference from `custom.cbx` (I have this way of doing it working); or
* I'm missing a biblatex specific include command.

**Comment by moewew** [comment]
Any of the ways you describe is valid. (I think there was even a question on TeX.SX about that once, [Biblatex.cfg vs .cls vs .sty](http://tex.stackexchange.com/q/296732/35864)) (Use `\input` instead of `\include`, though.) I wouldn't create a package, but it is possible, see `biblatex-chicago`, which is a package in its own right (loaded with `\usepackage{biblatex-chicago}`), but practically a thin wrapper around `biblatex`. 

The most appropriate method depends on your needs and the nature of your modifications.

**Comment by JohnLukeBentley** [comment]
It's chiefly about commands (including macro's) that I'm creating from scratch rather than those that I'm overriding. I'll be calling those self-created commands from those "original" biblatex commands that I'm overriding. My actual code is more complex but conceptually, at the moment, I have something like ...

authoryear-jlb.bbx

    \ProvidesFile{authoryear-jlb.bbx}
    [2016/11/16 v1.0 JLB's modification of authoryear.bbx]

    \RequireBibliographyStyle{authoryear}
  
    % Global self-created command example 1
    \newcommand{\jlb@testnewcommand}{%
      \printtext{AAAAAAAAA}
    }

    % Global self-created command example 2
    \newbibmacro{jlb@testnewbibmacro}{%
      \printtext{BBBBBBBBB}
    }

    % merge date with date label (an original biblatex command I'm overriding)
    \def\bbx@opt@mergedate@compact{%
      \renewbibmacro*{date+extrayear}{
       % Calling self-created commands
        \jlb@testnewcommand
        \usebibmacro{jlb@testnewbibmacro}
      }

    % Necessary to ensure the mergedate commmand run here rather than in authoryear.bbx
    \ExecuteBibliographyOptions{mergedate=compact}

    \endinput

authoryear-jlb.cbx

    \ProvidesFile{authoryear-jlb.cbx}
    [2016/11/16 v1.0 JLB's modification of authoryear.cbx]

    \RequireCitationStyle{authoryear}

    % (an original biblatex command I'm overriding)
    \renewbibmacro*{cite:labelyear+extrayear}{%
        % Calling self-created commands
        \jlb@testnewcommand
        \usebibmacro{jlb@testnewbibmacro}
    }%

    \endinput

Authouryear-Jlb-Mwe.tex

    \documentclass{article}
    
    \usepackage[
      style=authoryear-jlb,
    ]{biblatex}
    
    \addbibresource{MyReferences.bib}
    
    \begin{document}
    \nocite{*}
    \printbibliography
    \end{document}

That is, my custom commands `jlb@testnewcommand` and `jlb@testnewbibmacro` are defined in `authoryear-jlb.bbx` and run in both `authoryear-jlb.bbx` and `authoryear-jlb.cbx`. That works fine. And, as you suggest, structuring it this way is nothing to lose sleep over.

However, it would be neater to keep global commands in a separate file. And from the previous list of candidate techniques that's the only technique I can get working. Recall these files are installed in (notionally) `"C:\MyDevFolder\` rather than `C:\Program Files\MiKTeX 2.9\tex\latex\` (perhaps I need to install them to `C:\Program Files\MiKTeX 2.9\tex\latex\bibaltex-authoryear-jlb`??).

I would rather keep it is a mere style (as for biblatex-phys or biblatex-apa) rather than a separate package (as for biblatex-chicago) as I like the idea that all you have to do is change `newstyle` in `\usepackage[...style=newstyle , ...]{biblatex}`. So I'm with you when you write "I wouldn't create a package".

So here's an example of how I attempt to do this using (taking one of your suggestions in your link) a *.sty file ...

C:\MyDevFolder\authoryear-jlb.sty

    \ProvidesFile{authoryear-jlb.sty}
    [2016/11/16 v1.0 JLB's commands common to authoryear-jlb]

    % Moving the global commands from authoryear-jlb.bbx to here...

    \newcommand{\jlb@testnewcommand}{%
      \printtext{AAAAAAAAA}
    }

    \newbibmacro{jlb@testnewbibmacro}{%
      \printtext{BBBBBBBBB}
    }

    \endinput

But that goes wrong. I get a fatal error.

As is, my authoryear-jlb.sty is coded on the assumption that biblatex will recognize it in virtue of the .sty extension. This assumption is proven to be wrong. Perhaps I'm missing the right commands to put in authoryear-jlb.sty to have it recognized by biblatex; or fundamentally misunderstanding the role and structure of a .sty file. I do suspect I'm missing something noobishly basic.

Using biblatex.cfg also would seem to be a misuse of that kind of file. I take it to be for "per user" configurations rather for "per module" (such as a set of style files would count) configurations.

**Comment by moewew** [comment]
Of course `biblatex` doesn't just find your `.sty` file and loads it out of the blue. It only loads `.bbx` and `.cbx` files depending on the `(bib/cite)style` options.

I am not aware of a style-"global" option, i.e. a `<style>.def` solution that would get loaded alongside `<style>.bbx` and `<style.cbx>`. Thinking about it, enabling such a thing would probably create more problems than it would solve. Just define your macros in the `.bbx` (normally that is the more verbose of the two files) and use them in the `.cbx` if you must.

**Comment by JohnLukeBentley** [comment]
Thanks.

Here's where my confusion arose for `.sty` files in particular. I had been taking `.sty` to stand for "style" and to represent a biblatex specific file type ... exclusively for biblatex styles. Looking at the existence of `\tex\latex\biblatex-chicago\biblatex-chicago.sty` reinforced that faulty notion. 

Since I've previously created my own package (following instructions at https://en.wikibooks.org/wiki/LaTeX/Creating_Packages) I should have recalled that `packagename.sty` files are general-to-latex (or tex?) file types for packages. Something that you need, therefore, to load with `\usepackage{packagename}`. Once that's understood one can now understand `biblatex-chicago.sty` role in breaking biblatex conventions (by being loaded through `\usepackage{biblatex-chicago}` rather than `\usepackage[style=chicago]{biblatex}`).

> I am not aware of a style-"global" option, i.e. a &lt;style&gt;.def solution that would get loaded alongside &lt;style.bbx&gt; and &lt;style.cbx&gt;. Thinking about it, enabling such a thing would probably create more problems than it would solve.

I'll take your word that there are particulars that make this difficult. And given that implementing  a `<style.def>` solution is not straightforward I'm certainly happy to go with ....

> Just define your macros in the .bbx (normally that is the more verbose of the two files) and use them in the .cbx if you must.

Certainly this way of doing things presents no special problems. Perhaps, in the pending Quick Start Guide, Author section, a convention could be suggested (but not enforced) to include globals at the top of the .bbx file. With you it seemed natural to put them in .bbx rather than .cbx.

So I consider the current issue closed in terms of answering my initial enquiry. But perhaps the thread could be left open as a marker for basic content to be addressed in the Quick Start Guide, Author section. I'll leave it up to you or @plk to formally close the thread or leave it open.

Thanks again for your help.
