### ISSUE TITLE
Ellipsis (\dots) not being recognised as dot(s) with fontspec

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [plk/biblatex#514]
Following a recent discussion on Stackexchange (http://tex.stackexchange.com/questions/340478/biblatex-equivalent-to-adddot-or-isdot-for-ellipsis/340612?noredirect=1#340612), we seem to have stumbled on a `fontspec` related issue in BibLaTeX. It seems that ellipsis (`\dots`), while they are recognised as dots with pdflatex (allowing for usage with `\isdot` and such other commands), are not with `fontspec` (a workaround was proposed by moewe). 
I add a MWE to demonstrate the issue. If you compile it, you will see (footnote 5) that `\isdot` did not work and we get a fourth . after the ellipsis :

    \documentclass{article}

    \usepackage[french]{babel}
    \usepackage{fontspec}
    %\usepackage[utf8]{inputenc}
    %\usepackage[T1]{fontenc}

    \usepackage{filecontents}

    \begin{filecontents}{\jobname.bib}
    @book{akkerman_studien_1937,
	    title = {Studien zum Karlmeinet: der dritte Abschnitt der Kompilation und sein Verh\"{a}ltnis zum ersten},
	    shorttitle = {Studien zum Karlmeinet},
	    author = {Jan Akkerman},
	    year = {1937}
    }

    @article{dupont_2002,
	    title = {Les chansons de geste: sous-titre particulièrement long que l'on va oublier},
	    volume = {28},
	    shorttitle = {Les chansons de geste},
	    journal = {Revue de philologie romane},
	    author = {Dupont, Jean},
	    gender = {sm},
	    year = {2002},
	    pages = {3--22}
    }

    \end{filecontents}

    \usepackage[babel]{csquotes}
    \usepackage[backend=biber, 
		       style=test]{biblatex}

    \addbibresource{\jobname.bib}

    %Fix for fontspec suggested by moewe on Stackexchange, http://tex.stackexchange.com/questions/340478/biblatex-equivalent-to-adddot-or-isdot-for-ellipsis/340612?noredirect=1#340612
    %\makeatletter
    %\protected\def\blx@imc@forceisdot{\spacefactor\blx@sf@dot}
    %\blx@regimcs{\forceisdot}
    %\makeatother

    \DeclareFieldFormat[book]{citetitle}{\textit{#1}\printtext{\dots}\isdot}

    \DeclareFieldFormat[article]{citetitle}{\mkbibquote{#1\printtext{\dots}\isdot\midsentence}}

    \begin{document}

    \footcite{akkerman_studien_1937} %OK

    \footcite{dupont_2002} %OK 

    \footcite[p.~50]{akkerman_studien_1937} %OK

    \footcite[p.~50]{dupont_2002} %OK

    \footcite{akkerman_studien_1937} %NOT OK

    \footcite{dupont_2002} %OK

    \printbibliography

    \end{document}

**Comment by moewew** [comment]
@josephwright Would it be safe to 'manually' give the ellipsis the dot spacefactor via
```
\def\blx@setfrcodes{%
  \ifnum\sfcode`\A=\@m
  \else
    \blx@setazcodes
  \fi
  \sfcode`\,=\blx@sf@comma
  \sfcode`\;=\blx@sf@semicolon
  \sfcode`\:=\blx@sf@colon
  \sfcode`\.=\blx@sf@period
  \sfcode`\!=\blx@sf@exclam
  \sfcode`\?=\blx@sf@question
  \ifx\Umathcode\undefined
  \else
    \sfcode`\…=\blx@sf@dot
  \fi
}
```
Is ` \ifx\Umathcode\undefined` a safe method to detect Unicode capabilities? And if that is OK, is it OK to assign the factor like this?

**Comment by moewew** [comment]
My tests suggest that pdfLaTeX gives `\dots` a sfcode of 1006, i.e. `\blx@sf@period`, so I changed the code to be consistent with that.

I actually think, `\blx@sf@dot` would be more appropriate here, but at least then all engines behave the same.

@josephwright Do you have any comments about the implementation I suggested? Is that an acceptable way of doing things?

**Comment by moewew** [comment]
I would like to look at this again in the light of #665.

@josephwright Any comments about the suggested implementation? Or is there something better we could do?

**Comment by moewew** [comment]
There is https://github.com/moewew/biblatex/commit/5de1c77d639e4fdea5506bfdb3c90ec63be8c35c now. This should bring XeLaTeX and LuaLaTeX in line with pdfLaTeX.

**Comment by moewew** [comment]
5de1c77 has been merged to dev. Testing, comments and hints are appreciated.

**Comment by moewew** [comment]
We are planning to release the next version with a fix for this shortly.

Testing would be appreciated. You can either pull and install from `dev` or get the development version from https://sourceforge.net/projects/biblatex/files/development/.

**Comment by moewew** [comment]
3.10 has been released to CTAN and is in TeX live and MikTeX already. Now the ellipsis dots behave exactly the same with pdfLaTeX and XeLaTeX/LuaLaTeX.
