### ISSUE TITLE
backref per entrytype does not work

### ISSUE THREAD

**Issue by simifilm** [plk/biblatex#519]
The `backref` option seems not to be settable per entrytype as described in the manual. See the following MWE:

> \documentclass{article}
> \usepackage{fontspec}
> \setmainfont{TeX Gyre Pagella}
> \usepackage[]{biblatex}
> \usepackage{filecontents}
> \begin{filecontents*}{bib.bib}
> @book{Marzin.F:1982,
> 	Address = {Frankfurt a.\,M.},
> 	Author = {Marzin, Florian F.},
> 	Publisher = {Peter Lang},
> 	Subtitle = {Eine Gattungsstudie},
> 	Title = {Die phantastische Literatur},
> 	Year = {1982}}
> \end{filecontents*}
> \addbibresource{bib.bib}
> \ExecuteBibliographyOptions[book]{backref=true}
> \begin{document}
> \cite{Marzin.F:1982}
> \printbibliography
>  \end{document}

As soon as I remove the `entrytype` from `\ExecuteBibliographyOptions`, everything works.

**Comment by plk** [comment]
I don't think this is settable per-type - the main matrix at the end of the manual (Appendix E) says that it isn't ... is there somewhere it says it is?

**Comment by simifilm** [comment]
Ah, sorry, I was looking properly. Is it somehow possible to set the `backref` option for one bibliography and deactivate for another?

**Comment by plk** [comment]
Hmm, not sure - best ask first on TSE ... I think it's local to refsections?
