### ISSUE TITLE
Bulgarian support

### ISSUE THREAD

**Issue by kiganev** [plk/biblatex#522]
Hi,
I started using biblatex only a couple of weeks ago but I already very much like its power and flexibility. However, I am missing support for Bulgarian. Is work on providing such support ongoing, and if not, how could I help in this respect (translations, etc.)?

**Comment by moewew** [comment]
Currently Bulgarian is not amongst the list of supported languages. And I'm not aware of anyone working on Bulgarian support at the moment.

If you would like to help have a look at the old wiki on sourceforge: https://sourceforge.net/p/biblatex/oldwiki/Adding_lbx_Files/
See also [What is the most appropriate way to configure biblatex for use with an unsupported language?](http://tex.stackexchange.com/q/200932/35864) on TeX.SX.
There you can find out about the `.lbx` files.

**Comment by kiganev** [comment]
Thank you very much for your reply. I have already started building the Bulgarian lbx file using the Russian one as a basis. I will post again when I am ready.

**Comment by kiganev** [comment]
Just finished translating for the the Bulgarian lbx file. Please find it packed together with a text file containing answers on Bibliography Extras:

[bg.zip](https://github.com/plk/biblatex/files/706564/bg.zip)

**Comment by plk** [comment]
@moewew  - can you add this to the dev branch?

**Comment by kiganev** [comment]
Seems that I don't have push privileges for the lbx folder. Or should I put it somewhere else?

**Comment by plk** [comment]
Oh, it's alright, I will add to the dev branch - can you let me know your full name so I can add you to the acknowledgements?

**Comment by kiganev** [comment]
It's Kaloyan Ganev. And, thanks for you help!

**Comment by plk** [comment]
Can you give me strings for "langbulgarian" and "frombulgarian"? I will add these to all language files.

**Comment by kiganev** [comment]
langbulgarian      = {{български}{бълг\adddot}},
frombulgarian    = {{от български}{от\addabbrvspace бълг\adddot}},

**Comment by plk** [comment]
All committed to DEV branch and 3.8 dev version is uploaded, many thanks.

**Comment by rkandilarov** [comment]
Many thank to @kiganev for the contribution, I was planning to rise the issue when I finish my PHD :).

Writing just to note that up to now I'm successfully using this Bulgarian version of biblatex https://github.com/vgvassilev/biblatex-iso690 , which was done few years ago when other bulgarians come to the same issue: https://github.com/plk/biblatex/issues/160 . Luckily somebody not  lazy to sent properly the issue to the DEV team, after finding self-working patch :)!

So again, great thanks to  @kiganev :+1: !

**Comment by vgvassilev** [comment]
Is now my biblatex-iso690 obsolete or we still should propose a patch?
