### ISSUE TITLE
Datamodel validation doesn't take new time fields into account

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#523]
Per: http://tex.stackexchange.com/q/347372/35864
Biber doesn't validate entries with hour, minute or second fields. It seems as though `blx-dm.cfg` is missing `\DeclareDatamodelEntryfields` for these fields.

**Comment by plk** [comment]
I have added the time fields to some more types in the default data model which make sense.

**Comment by moewew** [comment]
Thank you very much. Would it make sense to add all `urldate` parts to all types? Would it maybe make sense to add all date part fields for all entry types by default (whether it makes sense to have an hour for a `@book` entry or not) much in the same way as `orig...` is enabled for all types?

**Comment by plk** [comment]
Yes, I have done this. Also added `url` as a global field or `urldate` makes no sense ...
