### ISSUE TITLE
Changing sorting leads to unclear error

### ISSUE THREAD

**Issue by josephwright** [plk/biblatex#524]
As reported in http://tex.stackexchange.com/questions/347416/empty-bibliography-after-changing-style-to-chem-acs, swapping the sort order after an initial Biber run gives the rather unhelpful error 
```latex
(./<name>.bbl
! Undefined control sequence.
<argument> \blx@tempa 
                      
l.<line>\endrefsection
```
At the very least, a more helpful message should result.

**Comment by plk** [comment]
Hmm, not obvious how to handle this - do you have any ideas?

**Comment by josephwright** [comment]
@plk Yup, that's my job on the `biblatex` team: deal with tricky TeX issues :)
