### ISSUE TITLE
General language mapping

### ISSUE THREAD

**Issue by jspitz** [plk/biblatex#525]
Some styles such as` biblatex-apa` or `biblatex-mla` ship a set of alternative `*.lbx` files that have to be used instead of the stock set (such as `english-apa.lbx`). Currently, users need to map each individual language file via `\DeclareLanguageMapping` in the preamble.
Since this is rather inconvenient, I wonder if there couldn't be a more general solution to this problem on the upstream level, e.g. either of:

- biblatex first looks for `<lang>-<style>.lbx` and falls back to `<lang>.lbx` if the former does not exist

- provide a general mapping macro such as `\DeclareMappingPrefix{-apa}` that can be used by such style files in order to set a global mapping

**Comment by moewew** [comment]
That is an interesting idea. Currently a few packages that also ship their own `.lbx` solve this by having `\DeclareLanguageMapping` in their `.bbx` (or elsewhere), an example is `biblatex-chicago`, another `biblatex-dw`. But of course this requires manual work by the maintainer.

**Comment by plk** [comment]
Can you try 3.8 DEV version? There is a new macro which can be used in styles `\DeclareLanguageMappingSuffix` - see the PDF documentation.

**Comment by jspitz** [comment]
Looks good. Thank you!
