### ISSUE TITLE
91-sorting-schemes.tex example not working as it should?

### ISSUE THREAD

**Issue by dcpurton** [plk/biblatex#526]
When I build the `91-sorting-schemes.tex` example file both the citation list and the bibliography are sorted according to the `nyt` sorting scheme.

If this is intended then what is the point of this example and how do the package options `sortcites,sorting=ynt` affect things? I would have thought that the citation list should be sorted according to `ynt` and the bibliography according to `nyt`.

**Comment by plk** [comment]
Hmm, I think this is a bug. Looking at it.

**Comment by plk** [comment]
Please see 3.8 DEV version - this should be fixed now.

**Comment by dcpurton** [comment]
Yep, that looks like what I'd expect. Thanks!
