### ISSUE TITLE
Additional nameparts in indexname

### ISSUE THREAD

**Issue by simifilm** [plk/biblatex#529]
To handle pseudonyms, I defined additional name parts like this in a .dbx file:

`\DeclareDatamodelConstant[type=list]{nameparts}{prefix,family,suffix,given,trueprefix,truefamily,truesuffix,truegiven} `

This works flawlessly for `\DeclareNameFormat`, but I cannot seem to access the new name elements with `\DeclareIndexNameFormat`. Before coming up with a MWE (which would be rather complicated), I wanted to ask wether I am missing something here and the new name elements should be normally available in for index names or wether this does indeed not work (yet).

**Comment by plk** [comment]
I think it should work - the default is defined using the new macros:

```
\DeclareIndexNameFormat{default}{%
  \usebibmacro{index:name}
    {\index}
    {\namepartfamily}
    {\namepartgiven}
    {\namepartprefix}
    {\namepartsuffix}}

```

**Comment by simifilm** [comment]
Sorry, my mistake. I mixed up the various name formats.
