### ISSUE TITLE
[VERBOSE STYLE] Missing Italics in titles of books

### ISSUE THREAD

**Issue by Doc73** [plk/biblatex#530]
From some time, the titles of books and other similar items are no longer in italics with the verbose style, despite the provided documentation .

Here is a sample code:
```tex
% !TeX program = xelatex
% !TeX encoding = UTF-8
% !TeX spellcheck = it_IT

\begin{filecontents}{biblio.bib}
@Article{Berti1966,
  author       = {Berti, Ernesto},
  journaltitle = {Studi Classici e Orientali},
  pages        = {210--220},
  title        = {Contributo allo studio dei manoscritti platonici del Critone},
  volume       = {15},
  date         = {1966},
}

@Book{Baldi2013,
  author    = {Baldi, Davide},
  location  = {Turnhout},
  publisher = {Brepols Publishers},
  title     = {Etymologicum Symeonis Γ-Ε},
  date      = {2013},
  number    = {79},
  series    = {«Corpus Christianorum. Series Graeca»},
}
\end{filecontents}

\documentclass[11pt,a4paper]{book}
\usepackage{libertine}

\usepackage[%
	backend=biber,%
	bibstyle=verbose,%
	citestyle=authoryear, %
	]{biblatex}
\addbibresource{biblio.bib}

\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

Thank you very much in advance

**Comment by moewew** [comment]
I can't reproduce the problem with the current release version 3.7. I get both 'EtymologicumSymeonisΓ-Ε' and 'Studi Classici e Orientali' in italics/`\emph` as expected. 

See
![sjhsadjkhasjkhsd](https://cloud.githubusercontent.com/assets/6755835/22259050/1e607c94-e264-11e6-8c25-121c2b18e4d0.png)

Note that neither the `series` field nor the `title` field of an `@article` are expected to appear in italics.

**Comment by Doc73** [comment]
It's very strange.... I have all in regular, with the same versione 3.7.

![regular](https://cloud.githubusercontent.com/assets/1306260/22259218/bed5776a-e264-11e6-9266-6a4703903cbc.png)

Maybe is this issue related with fontspec v. 2.5c issue [254](https://github.com/wspr/fontspec/issues/254)?

**Comment by moewew** [comment]
Could be, my `fontspec` is from MikTeX and might be a bit behind, I have `fontspec.sty    2016/02/01 v2.5a Font selection for XeLaTeX and LuaLaTeX`. Please check with standard pdfLaTeX, if the problem doesn't persist, it's not `biblatex`'s fault.

**Comment by Doc73** [comment]
Ok!
I did a bit better: I downloaded the latest version of fontspec from github, compiled the sources and.... all went fine!
You could close this issue!
Anyway, thank you very much for your assistance! 👍

**Comment by moewew** [comment]
OK, glad it works for you now.

**Comment by wspr** [comment]
Sorry all for the inconvenience. Update for fontspec has now been sent to CTAN.
