### ISSUE TITLE
\usedriver disables \newblock in biblists

### ISSUE THREAD

**Issue by odomanov** [plk/biblatex#531]
`\usedriver` sets `\newblock` to `\relax`. This makes sense in citations, but it is also used in biblists (like shorthands, etc) where this is rather undesirable. Is it possible to disable `\newblock` only in citations? Or to have an option for that?

**Comment by plk** [comment]
I am not sure about making a new option for this - it seems very specific. Perhaps we can default the init block to something backwards compatible. Can you put a MWE here with both citations and bib entries?

**Comment by moewew** [comment]
Maybe - I haven't thought this through - we need two commands, one to call the driver in a citation context and one to call it in a bibliography context.
Alternatively, we can make `\usedriver` context-aware, but in order to maintain backwards compatibility, that would probably have to be governed by an option.

**Comment by plk** [comment]
I think we'd want to make it context-aware somehow or to make newblock definable. `\usedriver` has an init block which we could default?

**Comment by odomanov** [comment]
This is an MWE. 
In `biblatex-gost` newblock is defined as emdash, and as you see the output is different in the shorthands list and in the bibliography.

`\usedriver` has an initialisation option, so the newblock can be restored when the `\usedriver` is called within a shorthands environment. Perhaps setting newblock to `\relax` may be moved to the definition of this environment.

And it seems that I was wrong, this concerns only shorthands, not other biblists. I thought that `\printshorthands` is simply defined through `\printbiblist`. 

~~~latex
\RequirePackage{filecontents}
\begin{filecontents}{\jobname.bib}
@BOOK{book,
 author = {Author},
 title = {Long Long Title},
 shorthand={B},
 shorttitle={Title},
 location = {Location},
 year = {2016},
}
\end{filecontents}
\listfiles
\documentclass{article}
\usepackage[T1,T2A]{fontenc}
\usepackage[utf8]{inputenc}
% \usepackage{babel}
      
\usepackage[%
  language=auto,      
  autolang=other,
  style=gost-authoryear,
]{biblatex}
\addbibresource{\jobname.bib}

\begin{document}
\nocite{*}
\printshorthands
\printbiblist{shorttitle}
\printbibliography
\end{document}
~~~

**Comment by moewew** [comment]
Yes, making the init block user-configurable might be the best way to go.

@odomanov `\printshorthands` uses the `shorthands` driver which is defined as
```
\DeclareBibliographyDriver{shorthand}{%
  \usedriver
    {\DeclareNameAlias{sortname}{default}}
    {\thefield{entrytype}}%
  \finentry}
```
so it uses `\usedriver`. But there is no `shorttitle` driver (as you can see from the warning in the `.log`), so there we get the default driver.

**Comment by odomanov** [comment]
Ah, this is why I couldn't find the `shorttitle` driver --- there is no such thing.
So this only concerns the `shorthand` driver.

**Comment by plk** [comment]
See the documentation for `\printbiblist` - this automatically creates drivers. In fact the shorthand driver is created by this - `\printshorthand` is just an alias to the much more general `\printbiblist` interface since a few versions ago.

**Comment by plk** [comment]
@moewew  - do you have any time to look at this?

**Comment by moewew** [comment]
I hope to look at this later this week. If I forget to, you may have to nudge me again.

**Comment by odomanov** [comment]
@plk Just to clarify. Does this mean that all fields declared as `\DeclareLabelname` or `\DeclareLabeltitle` must have their driver? Why then the .log says that there is no driver for `shorttitle` --- and for `shortauthor` as I've just checked?

**Comment by plk** [comment]
If you see page 81 of the PDF doc, you'll see an example for `shortjournal` which also applies to `shorttitle`. The driver isn't automatically created but the list filter and list environment are.

**Comment by odomanov** [comment]
Oh, indeed, thank you. I confused bib driver and bib environment.

**Comment by moewew** [comment]
I'm looking into this at the moment. The current definition is

```
\protected\def\blx@imc@usedriver#1#2{%
  \begingroup
  \let\finentry\blx@finentry@usedrv
  \let\newblock\relax
  \let\abx@macro@bibindex\@empty
  \let\abx@macro@pageref\@empty
  \csuse{blx@hook@bbxinit}#1%
  \delimcontext{bib}%
  \blx@beglangbib
  \blx@driver{#2}%
  \blx@endlangbib
  \endgroup}
```

The plan was to move some of the default initialisation code to a user/developer-definable macro, `blx@hook@usedriver` or `blx@usedriver@init`, say. Then we'd only call on that macro in the init part of `\usedriver`. In particular you could use the new init code to branch on citations/bibliography.

Now I'm not quite sure which bits we should 'externalise' to the new init block. Surely `\let\newblock\relax` should end up there, but at least
```
  \let\finentry\blx@finentry@usedrv
  \let\newblock\relax
  \let\abx@macro@bibindex\@empty
  \let\abx@macro@pageref\@empty 
```
also seem useful there. I can also see why one would put
```
  \csuse{blx@hook@bbxinit}%
  \delimcontext{bib}%
```
there.

Any input?

**Comment by plk** [comment]
Anything really needed which overwriting would break shouldn't be in there I think otherwise we have to have the default in the manual which could look a bit unpleasant for people with all those internal macros. Perhaps a new user-space macro is needed to initialise the internal one which would populate this?

**Comment by moewew** [comment]
OK, I believe
```
  \let\finentry\blx@finentry@usedrv
  \let\newblock\relax
  \let\abx@macro@bibindex\@empty
  \let\abx@macro@pageref\@empty 
```
would then be a sensible default. (It doesn't even look *that* scary, so could be included in the documentation.)

I assume that we'd define some `\AtUsedriver`-user-level macro to populate `blx@hook@usedriver`. (Would the names be appropriate?)

**Comment by plk** [comment]
Yes, I think that's good - the name reflects the particular use case well.

**Comment by moewew** [comment]
One problem is that if we populate `\blx@hoof@usedriver` with a default, we would have to offer a way to clear/overwrite the defaults. Currently none of the `\At...` hooks needs or has this. It would be possible to include a starred version that clears the hook before appending. What do you think?

**Comment by plk** [comment]
Then we can just provide a macro to set/replace the hook but not one that simply adds?

**Comment by moewew** [comment]
I have defined a starred version that overrides the previously set hook, but that would make the macro special amongst the `\At...` family of macros.

**Comment by moewew** [comment]
There is a first suggestion in https://github.com/plk/biblatex/pull/533. In my tests, things worked as expected, but thorough testing would be appreciated.

**Comment by odomanov** [comment]
Works fine in the setup like this:
~~~latex
\AtUsedriver*{%
  \ifcitation{\let\newblock\relax}{}
  \let\finentry\blx@finentry@usedrv
  \let\abx@macro@bibindex\@empty
  \let\abx@macro@pageref\@empty}
~~~
A little bit scary, yes))) But fine.

**Comment by egorpugin** [comment]
Hi,

I'm seeing the error below on the latest miktex (xelatex+biber+biblatex-gost).
I didn't change anything, just opened my old paper after updating miktex stuff.
Is it somehow related to this ticket? Any workarounds?

```
! Missing number, treated as zero.
<to be read again> 
                   \relax 
l.27 \Bibliography
                  
A number should have been here; I inserted `0'.
(If you can't figure out why I needed to see a number,
look up `weird error' in the index to The TeXbook.)
```

**Comment by odomanov** [comment]
It's unlikely that it's related, since the changes have not released yet. Do you use the development version of biblatex?

**Comment by moewew** [comment]
@egorpugin Are you using the development revisions or the release versions from CTAN? Anyway, you may want to ask about this on TeX.SX (http://tex.stackexchange.com/questions/tagged/biblatex) with a proper [MWE](http://meta.tex.stackexchange.com/q/228/35864).

**Comment by egorpugin** [comment]
Yes, it seems my issue is not related to this one. Sorry for bothering.
