### ISSUE TITLE
Mandatory field 'publisher' for book

### ISSUE THREAD

**Issue by kiryph** [plk/biblatex#532]
according to http://tug.ctan.org/info/bibtex/tamethebeast/ttb_en.pdf#page=14 books should have a publisher field (mandatory).

However, right now biber/biblatex consider 'publisher' as an optional field for books. See the documentation
http://mirrors.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf#page=7
and ` $ biber --tool -V mybib.bib` does not complain about a missing mandatory field for
```bib
@Book{Love:1944,
  title     = {Treatise on mathematical theory of elasticity},
  author    = {Love, A E H},
  edition   = {4. ed., unabridged and unaltered republ. of the 1927 ed.},
  isbn      = {9781107618091},
  pages     = {643},
  year      = {1944},
}
```

Should I change this only on my end in https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/blx-dm.def#L1362-L1366, or do you want to change the default?

**Comment by plk** [comment]
You may want to discuss this on TSE - the biblatex data model is not identical to the bibtex data model. You can always just add a constraint in a config file if you want this but I suspect there were good reasons for this.

**Comment by kiryph** [comment]
Can you show me a minimal config file to just add 'publisher' as a constraint for books?

**Comment by plk** [comment]
You can try:

```
\DeclareDatamodelConstraints[book]{
  \constraint[type=mandatory]{
    \constraintfield{publisher}
  }
}
```

**Comment by kiryph** [comment]
So I would add this to my tex file right? I was thinking of a file which biber checks. The motivation is that I want to run biber as a validation tool for my bib file. Is there something as well?

**Comment by plk** [comment]
See page 173 of the PDF doc - there are several places you could put this, but not in your .tex

**Comment by kiryph** [comment]
If I got it right,
> To summarise, the data model is determined by adding to the data model from each of these locations, in order:
> `blx-dm.def→`
> `<datamodel option>.dbx →`
> `<style option>.dbx →`
> `<citestyle option>.dbx and <bibstyle option>.dbx →`
>        `biblatex-dm.cfg`

I create the file `~/mylatexproject/biblatex-dm.cfg` in my latex project with 
```
\DeclareDatamodelConstraints[book]{
  \constraint[type=mandatory]{
    \constraintfield{publisher}
  }
}
```
Now running `$ biber --tool --validate-datamodel mybib.bib` should warn about a missing publisher? Unfortunately, it doesn't work

```
~/Manuscripts/thesis master*
❯ cat mybib.bib
@Book{Love:1944,
  title     = {Treatise on mathematical theory of elasticity},
  author    = {Love, A E H},
  edition   = {4. ed., unabridged and unaltered republ. of the 1927 ed.},
  isbn      = {9781107618091},
  pages     = {643},
  year      = {1944},
}

~/Manuscripts/thesis master*
❯ cat biblatex-dm.cfg
\DeclareDatamodelConstraints[book]{
  \constraint[type=mandatory]{
    \constraintfield{publisher}
  }
}

~/Manuscripts/thesis master*
❯ biber --tool -V mybib.bib
INFO - This is Biber 2.7 running in TOOL mode
INFO - Logfile is 'mybib.bib.blg'
INFO - Looking for bibtex format file 'mybib.bib'
INFO - Decoding LaTeX character macros into UTF-8
INFO - Found BibTeX data source 'mybib.bib'
INFO - Overriding locale 'en_US' defaults 'variable = shifted' with 'variable = non-ignorable'
INFO - Overriding locale 'en_US' defaults 'normalization = NFD' with 'normalization = prenormalized'
INFO - Sorting list 'none/global/' of type 'entry' with scheme 'none' and locale 'en_US'
INFO - No sort tailoring available for locale 'en_US'
INFO - Writing 'mybib_bibertool.bib' with encoding 'UTF-8'
INFO - Output to mybib_bibertool.bib
```

Do you know what is wrong?

**Comment by plk** [comment]
You are running in tool mode which doesn't do validation. Tool mode doesn't involve biblatex at all, it is for transforming .bib data. If you run as `biber -V myfile` it works.

**Comment by kiryph** [comment]
Well, this returns
```
❯ biber -V mybib.bib
INFO - This is Biber 2.7
INFO - Logfile is 'mybib.bib.blg'
ERROR - Cannot find control file 'mybib.bib.bcf'! - did you pass the "backend=biber" option to BibLaTeX?
INFO - ERRORS: 1
```

**Comment by plk** [comment]
biber does not run on the .bib file in non-tool mode. It runs on the .bcf file generated by biblatex. You can omit the extension of the .bcf.

**Comment by kiryph** [comment]
Well, that's the problem. I wanted to use biber just to validate the bib file without any latex document. I guess I can't use it this way.

**Comment by plk** [comment]
In fact you can. You have to use a custom `biber.conf` file which can be in the same directory as your document or specified by the `--configfile` argument. This should be a copy of the default tool mode config file with any additions you need. It is essentially a stand-alone .bcf file. I have attached an working version.

`biber --tool -V mybib.bib`

[biber-tool.conf.zip](https://github.com/plk/biblatex/files/747867/biber-tool.conf.zip)

**Comment by kiryph** [comment]
Thanks for your effort. As far as I can see the zip archive is the original one (https://raw.githubusercontent.com/plk/biber/dev/data/biber-tool.conf) extended by the publisher constraint:
```diff
❯ git diff --no-index biber-tool-orig.conf biber.conf
diff --git a/biber-tool-orig.conf b/biber.conf
index cdbce23..a741893 100644
--- a/biber-tool-orig.conf
+++ b/biber.conf
@@ -1718,6 +1718,12 @@
         <field>gender</field>
       </constraint>
     </constraints>
-  </datamodel>
+    <constraints>
+      <entrytype>book</entrytype>
+      <constraint type="mandatory">
+        <field>publisher</field>
+      </constraint>
+    </constraints>
+</datamodel>
 </config>
```
After renaming the file in the zip archive to `biber.conf`, `biber -V --tool mybib.bib` now emits a warning about the missing publisher field.
