### ISSUE TITLE
Translating "pages"

### ISSUE THREAD

**Issue by perstar** [plk/biblatex#534]
The translation unit "pages" is used in different ways. This example:
```
\documentclass{article}
% \usepackage[swedish]{babel}
\usepackage[abbreviate=false]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{westfahl:space, companion}
\printbibliography
\end{document}
```
yields "[1] Michel Goossens, ..., Addison-Wesley, 1994. 528 pages.
[2] Gary Westfahl ... Greenwood, 2000, pages 55–65."

For companion "pages" comes from "pagetotal" in the bib file, and for westfahl:space "pages" comes from "pages" in the bib file. At least for Swedish I would like different translations. (Now "pages" is "{{sidorna}{s\adddot}}" which is fine for "pages" but for the pagetotal use it should be "sidor" instead of "sidorna". I suspect some other languages also want to differentiate between these.

**Comment by perstar** [comment]
It's the same with translation unit "page". It is also used both for "pages" and "pagetotal" when the value is 1, and might need to be different. (But "pagetotal = 1" isn't be common, of course!)

**Comment by moewew** [comment]
Mhhh, I had a look. If we were to introduce a new `pagetotal`/`pagestotal` field we would need to translate that in all `.lbx`s.

@plk There are two ways I see here:
1. Just define new strings `pagetotal` and `pagestotal` and use them in `\mkpagetotal`. We would then have to add the strings to all `.lbx`s. It is probably not safe to assume we can copy over `page` and `pages`.
2. Make `\mkpagetotal` check if a `page(s)total` string is defined, if yes take it, if no take `page(s)`. That would retain the status quo for many languages and those that need change could do it.

I tend towards option (1) because it feels right, but from a practical point of view (2) is probably preferable.

**Comment by plk** [comment]
I'm happy for option 1. It's not that hard to define new strings. Just remember to put them in `biblatex.sty`, all `.lbx` files and the doc.

**Comment by moewew** [comment]
OK, will see what I can do. Maybe I can get a pull request ready later today.

**Comment by moewew** [comment]
Problem is, we would need `total` bibstrings for all default pagination types (`page`, `column`, `line`, `verse`, `section`, `paragraph`). So would end up with twelve new strings.

**Comment by plk** [comment]
Well, adding bibstrings is still a relatively easy way to solve this I think.

**Comment by moewew** [comment]
BTW: Would you be OK with the slightly unintuitive name scheme `pagetotal` vs `pagetotals`? That would allow us to keep code changes minimal.

**Comment by plk** [comment]
Yes, as long as it's documented, I don't think it's too bad.

**Comment by moewew** [comment]
I was just doing the German strings and noticed that https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/lbx/german.lbx#L381 'section' is translated as 'Paragraph' and 'paragraph' as 'Abschnitt'. I would have switched the two. It has been this way since 1.7 apparently.

**Comment by moewew** [comment]
There is now https://github.com/plk/biblatex/pull/546. I have retained the original German strings.

**Comment by pauloney** [comment]
The word "paragraph" has evolved in several languages (English, Portuguese,
Spanish and others...) to mean a short group of sentences separated by a
full-stop. In French (and German) they preserve the original meaning of
some 200 years ago which is a full "section".

The translations are correct.

Paulo Ney

**Comment by moewew** [comment]
@pauloney  Thanks. I'm a native German speaker and only ever use 'Paragraf' when referring to law texts. I would probably use 'Abschnitt' for 'mormal' texts.

**Comment by dbitouze** [comment]
As in French:
- `page` is the same as `pagetotal`,
- `pages` is the same as `pagetotals`,
- etc.

it could be nice if it would be possible to reuse the 1st ones in the 2nd ones in order to not duplicate the information and simplify maintenance.

**Comment by moewew** [comment]
@dbitouze  Thank you very much. `french.lbx` has been updated (https://github.com/plk/biblatex/pull/548).

AFAIK there is no aliasing interface for `bibstrings` yet, so we can't just say 'take `pagetotal` and if that is not available just use `page`' at the moment. We could have done that in `\mkpagetotal`, but that would have made the macro more fiddly.

**Comment by moewew** [comment]
@perstar This has now been implemented. Could you have a look at `pagetotal` and friends https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/lbx/swedish.lbx#L350 and suggest the correct translation?

**Comment by moewew** [comment]
@perstar Any news about the Swedish translations for `pagetotal` and friends?

**Comment by moewew** [comment]
@perstar Sorry to bother you again. `pagetotal` and friends have now been implemented. If you could have a look at the `.lbx` and suggest the correct translations that would be great.

**Comment by perstar** [comment]
Here they are, untested (so if I made a stupid paren error I didn't notice it).


pagetotal        = {{sida}{s\adddot}},
pagetotals       = {{sidor}{s\adddot}},
columntotal      = {{spalt}{sp\adddot}},
columntotals     = {{spalter}{sp\adddot}},
linetotal        = {{rad}{r\adddot}},
linetotals       = {{rader}{r\adddot}},
versetotal       = {{vers}{v\adddot}},
versetotals      = {{verser}{v\adddot}},
sectiontotal     = {{paragraf}{\S}},
sectiontotals    = {{paragrafer}{\S}},
paragraphtotal   = {{paragraf}{\S}},
paragraphtotals  = {{paragrafer}{\S}},

**Comment by moewew** [comment]
Thank you very much. I have committed the suggested changes, see https://github.com/plk/biblatex/commit/b1347695797819eb2cfe4cd7942a54e4b7cef182.

**Comment by plk** [comment]
@moewew - shall we close this now?
