### ISSUE TITLE
bbx:translator in authoryear.bbx

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#536]
Is there any reason why [line 240 of `authoryear.bbx`](https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/bbx/authoryear.bbx#L240) reads `\usebibmacro{translator+othersstrg}` instead of `\usebibmacro{#1}` (cf. line 217 in `bbx:editor` and [line 111 in `authortitle.bbx`](https://github.com/plk/biblatex/blob/dc93dd8372c64fe827513867d7cc53cf89182090/tex/latex/biblatex/bbx/authortitle.bbx#L111)) effectively wiping out the difference between the two macros `translator` and `translator+others`. Is that intentional? [Blame](https://github.com/plk/biblatex/blame/dc93dd8372c64fe827513867d7cc53cf89182090/tex/latex/biblatex/bbx/authoryear.bbx) shows that it has been this way since the initial 1.7 commit.

**Comment by plk** [comment]
I can't see any reason for that and 1.7 is a long time ago. Feel free to change it in DEV and I'll run the test suite.

**Comment by moewew** [comment]
OK, I have made the change. (https://github.com/plk/biblatex/commit/bb75d1fa89b2adda0ac180f0a92d7b1895a23709)

**Comment by plk** [comment]
All tests pass, looks ok.
