### ISSUE TITLE
Undefined control sequence \abx@field@localnumber

### ISSUE THREAD

**Issue by ti-s** [plk/biblatex#538]
I can reproduce the error with the following steps:

1.  Start with the following document `bibtest.tex`:
```
\documentclass{article}

\usepackage[
backend=biber, 
defernumbers = true
]{biblatex} 

\addbibresource{test.bib}

\begin{document}
	\cite{A} \cite{B}
	\printbibliography
\end{document}
```
and the following `test.bib` file:
```
@article{A,
    author = {A},
    title = {A},
    journal = {A},
    pages = {1},
    year = {2017},
}
```

2. `pdflatex bibtest.tex && biber bibtest && pdflatex bibtest.tex && pdflatex bibtest.tex`
3. Add to `test.bib`:
```
@article{B,
    author = {B},
    title = {B},
    journal = {B},
    pages = {2},
    year = {2017},
} 
```
4. `pdflatex bibtest.tex && biber bibtest && pdflatex bibtest.tex`

The last run of `pdflatex` stops with
```
! Undefined control sequence.
<argument> ...xt@context }{\abx@field@localnumber 
                                                  }
```
In this MWE, rerunning step 4 does not error but citation `B` occurs in the pdf with empty brackets `[]` until I delete the auxiliary files and rerun again.

In my actual document, I sometimes get errors like the following on all subsequent runs:
```
! Missing number, treated as zero.
<to be read again> 
                   \relax 
l.129 \cite{key}
```
The error occurs both with texlive 2015 (biblatex 2016/03/03 v3.3) and texlive 2016 (biblatex 2016/12/05 v3.7)

This might be a related issue: https://github.com/plk/biblatex/issues/238

**Comment by plk** [comment]
This isn't surprising - using `defernumbers` does complex things with the `.aux` file and so when you add new things to the `.bib`, you should delete all intermediary files, particularly the `.aux` file and re-run. Most editors have an option to delete all intermediary files. If you do this after adding to the `.bib` and re-run the compilation process, it's fine. This is mentioned in the documentation for `defernumbers` in the PDF manual for biblatex.

**Comment by ti-s** [comment]
In the documentation, I only found the warning that the `.aux` file has to be deleted when the `defernumbers` option itself is changed, not when the `.bib` file is modified. 

I had only a very quick look at the code, but maybe something like changing
```
{\abx@field@localnumber}}%
```
in line https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/biblatex.sty#L7042 into

```
{\ifundef\abx@field@localnumber{\blx@warning@noline{It may be necessary to delete auxiliary files. See documentation of the defernumbers option}}{\abx@field@localnumber}}}%
```
could work to help people unfamiliar with biblatex?

**Comment by plk** [comment]
I hav changed to the `defernumbers` documentation to be more inclusive about the sorts of changes which require `.aux` file deletion when using this option.
