### ISSUE TITLE
Complement/update bibstrings for Brazilian

### ISSUE THREAD

**Issue by gusbrs** [plk/biblatex#542]
I'm a native Brazilian and user of biblatex. In looking biblatex's brazilian.lbx file, I've noticed some gaps in the bibstrings.
So perhaps I can be useful.

I suggest the following inclusions/updates of the bibstrings for brazilian:

    % candthesis       = {{}{}},% I really don't know what this is, if you tell me, I can try to provide a string.
    url              = {{endere\c{c}o}{endere\c{c}o}}, % I've shortened the long form, it's more in line with the other languages and "electronic" is not really necessary.
    urlfrom          = {{dispon\'ivel em}{disp\adddot em}},
    prepublished     = {{pr\'e-publicado}{pr\'e-publ\adddot}}, % sounds fine to me, uncommented
    langcatalan      = {{catal\~ao}{catal\~ao}},
    langczech        = {{tcheco}{tcheco}},
    langestonian     = {{estoniano}{estoniano}},
    langpolish       = {{polon\^es}{polon\^es}},
    langslovene      = {{esloveno}{esloveno}},
    fromcatalan      = {{do catal\~ao}{do catal\~ao}},
    fromczech        = {{do tcheco}{do tcheco}},
    fromestonian     = {{do estoniano}{do estoniano}},
    frompolish       = {{do polon\^es}{do polon\^es}},
    fromslovene      = {{do esloveno}{do esloveno}},
    countryeu        = {{Uni\~ao Europeia}{EU}}, % new orthography
    countryep        = {{Uni\~ao Europeia}{EP}}, % new orthography
    patenteu         = {{patente europeia}{pat\adddot\ europeia}}, % new orthography
    patreqeu         = {{pedido de patente europeia}{ped\adddot\ de pat\adddot\ europeia}}, % new orthography
    circa            = {{circa}{ca\adddot}},
    spring           = {{primavera}{primavera}},
    summer           = {{ver\~ao}{ver\~ao}},
    autumn           = {{outono}{outono}},
    winter           = {{inverno}{inverno}},

I'd also like to suggest the addition, if possible, of the following bibstrings, with corresponding values:

    organizer        = {{organizador}{org\adddot}},
    organizers       = {{organizadores}{orgs\adddot}},
    byorganizer      = {{organizado por}{org\adddotspace por}},

The reason for this is that publishers in Brazil use "editor" or "organizador" somewhat interchangeably, and there is need to follow the publisher's terminology (I explained it in more detail in a question in TeX.SX [http://tex.stackexchange.com/questions/359344/create-new-editorial-role-organizer-in-biblatex](http://tex.stackexchange.com/questions/359344/create-new-editorial-role-organizer-in-biblatex)).
If you find this a good idea, I can of course provide strings for the combined roles as well.

**Comment by plk** [comment]
Greetings, I have added these - can you also put here one for "frombulgarian" which is a new string in the dev branch? The new strings - can you open a separate issue for these as I have to think about it since new strings need adding to every lbx file.

**Comment by plk** [comment]
Also, you can email me your name so that I can add you to the thanks list in the documentation.

**Comment by gusbrs** [comment]
Hi plk,

I've opened the issue suggesting bibstrings for Brazilian Portuguese (
https://github.com/plk/biblatex/issues/542).
As you asked, my name is Gustavo Barros.

Best regards,
Gustavo.

**Comment by gusbrs** [comment]
Sure I can.

    frombulgarian  = {{do b\'ulgaro}{do b\'ulgaro}},

Supposing there is also a `langbulgarian`, this would be:

    langbulgarian  = {{b\'ulgaro}{b\'ulgaro}},

As a matter of fact, if new strings come about in the future, you can contact me, and I'll be glad to provide them for Brazilian Portuguese if I can.
Regarding the `candthesis` string, I came up with something, which is a generic denomination to a work presented at the end of some formation step, resulting in a degree:

    candthesis  = {{trabalho de conclus\~ao}{trab\adddotspace de conc\adddot}},

perhaps this sorts the issue.

As for the suggested new organizer strings, I'll open another issue later. Thanks for considering.
And I can send you my name, of course, but I'm not sure where I could get your e-mail or contact you privately.

**Comment by moewew** [comment]
In
```
urlfrom          = {{dispon\'ivel em}{disp\adddot em}}
```
there is *no* space between 'disp.' and 'em' in the short string. Is that intended?

Most other strings in `brazilian.lbx` have a space after dots (with `\adddotspace` `op\adddotspace cit\adddot`, `{eds\adddotspace e trads\adddot`, `red\adddotspace por` or with `\adddot\ ` `{ed\adddotspace e introd\adddot\ por}`). The only other exceptions are

- `nodate = {{sem\space data}{s\adddot d\adddot}},`
- `annodomini       = {{depois de Cristo}{d\adddot C\adddot}},`
- `beforechrist = {{antes de Cristo}{a\adddot C\adddot}},`
- `patentfr = {{patente francesa}{pat\adddot francesa}}`

where the first three are understandable as the abbreviations are very short and the fourth is probably a typo (compare with `patenteu = {{patente europeia}{pat\adddot\ europeia}},`). Can you confirm that?

**Comment by gusbrs** [comment]
@moewew, you are quite correct, the lack of space is unintended in `urlfrom`. I do agree that the lack of space is granted, for their shortness, in `nodate`, `annodomini`, and `beforechrist`. But it sure is missing in `patentfr`. I would thus further suggest:

    urlfrom  = {{dispon\'ivel em}{disp\adddotspace em}}
    patentfr = {{patente francesa}{pat\adddotspace francesa}}

(I don't really know which is more adequate between `\adddotspace` or `\adddot\`, but a space is indeed required in both cases in my view).

**Comment by moewew** [comment]
Thank you for having a look. I have changed the strings accordingly. (I used  `pat\adddot francesa`, though, because it looked nicer in the `.lbx` as all other strings around it used the same.)

I don't think there should be a difference between `\adddotspace` and `\adddot\ ` in `biblatex`, but I can't be entirely sure.

**Comment by moewew** [comment]
@gusbrs Could you have a look at https://github.com/plk/biblatex/commit/b72238bcc449c32cac3043a397511987dae66a56 and comment on the use of 'em' in the bibstring?

**Comment by gusbrs** [comment]
@moewew , done!

**Comment by moewew** [comment]
This should be done for now with the commits already mentioned (https://github.com/plk/biblatex/commit/4c172bd3e85e6250e0e2b8f49be725ee883a976e, https://github.com/plk/biblatex/commit/9ea45e9f477ddf2291ec6acfa793aecbf5c78779) and #583.
