### ISSUE TITLE
"organizer" bibstrings for brazilian

### ISSUE THREAD

**Issue by gusbrs** [plk/biblatex#543]
Hi,
for reasons related to publishers' practices in Brazil (explained below) I'd like you to consider the possibility of adding bibstrings for an "organizer" editorial role to the Brazilian language localization file. Namely: 

    organizer        = {{organizador}{org\adddot}},
    organizers       = {{organizadores}{orgs\adddot}},
    byorganizer      = {{organizado por}{org\adddotspace por}},

The reason for the request is that, in Brazil, publishers do not employ a single term to refer to the "main responsible" for a collected work with several authors, which in English is referred to as the "editor". I know at least three terms to be used by publishers for the purpose: "organizador", "editor", and "coordenador" (resp. organizer, editor, coordinator). The most frequent of the three is indeed "organizer". "Editor" is a regular one, and "coordinator" is a rarer bird, but appears once in a while.

In any case, even though what each of these different names entails is probably very similar, from the point of view of giving a precise reference, one should stick to the denomination the publisher used. But within `biblatex` this is somewhat complicated, because there is no corresponding editorial role, with associated strings, to use. The inclusion of the suggested strings would, by itself, allow one to cite/reference properly for the case using the entryfield `editortype = {organizer},`.

I understand that the strings would have to be added to every lbx file (given @plk's comment on issue #542), which would complicate things, especially if combined roles (organizer +translator +introducion +afterword etc) come into consideration (sure, the three suggested strings would go a long way by themselves!).
I really don't know if this affects other languages or countries. Though I've met before "organizer" for books in Spanish. And indeed there are ways to deal with the issue (e.g. this TeX.SX question: [http://tex.stackexchange.com/questions/359344/create-new-editorial-role-organizer-in-biblatex](http://tex.stackexchange.com/questions/359344/create-new-editorial-role-organizer-in-biblatex)). But the availability of the strings would be very welcome.

**Comment by plk** [comment]
I have added these strings  to the 3.8 dev version - please have a look.

**Comment by gusbrs** [comment]
The addition is really appreciated, thank you. As this is my first interaction here, I have a question of etiquette. Is it for me to close the issue as an "answer accepted" in TeX.SX, or for developers to do so when you consider the issue to be complete?

**Comment by gusbrs** [comment]
@plk I took a closer look at the commit, as you requested. I'm not from Portugal and don't have any close contact with their publishing industry, but I'd say it would be safe to use the strings for Brazilian  for `portuguese.lbx` as well. At least in preliminary fashion (perhaps commented with `% to be checked by native speaker`). Technically the language is the same. We do not call the language "Brazilian" in Brazil, but simply "Portuguese". There are international agreements between Portuguese speaking countries to avoid divergence, and so on. What sure does vary is usage (and accent of course). What I mean by it being "safe" is that those strings will certainly be clearly understood for what they stand, but they might not be the habitual term for the purpose.

**Comment by gusbrs** [comment]
I just noticed one more thing. I think it would be well to include in the documentation `organizer` as a supported editorial role for the `editortype` field.

**Comment by moewew** [comment]
I can do that. Do you have a description of the 'organizer' role? Cf. §2.3.6 *Editorial Roles*, where we probably also want to list `organizer`.

**Comment by gusbrs** [comment]
Thanks for noticing, I'd forgotten about that. As I mentioned, the distinction between "editor" and "organizer" is not very clear, as far as I get it. It's more a question of terminology than of content. But I would go with something like the description of `compiler`. Thus: "Similar to `editor` but used if the task of the editor is mainly organizing." Would this be ok?

**Comment by moewew** [comment]
OK, it doesn't sound too exciting to my untrained ears, but if that best describes the role.

**Comment by gusbrs** [comment]
I think it is a fair and "no fuss" description, it should get the job done. Better perhaps than a truer one as "Just another word for `editor` for countries with issues of lack of standardization." Well, this is perhaps unfair, for I can see where the trouble probably came from. The word "editora" (feminine for "editor") is the one we use to refer to the publisher. Most likely, many publishers end up using some other word, mainly "organizer", to refer to what in the English language is referred to as "editor" to avoid confusion. But many end up using the more common internationally word "editor" anyway, not only in translated books. If you have the curiosity, I can send a cover page which uses the same word (editor) for both things and some with "organizers" as well. But, anyway, if you feel a more flaring description is due, I can sure try to come up with something else.

**Comment by moewew** [comment]
Oh no it's fine. It's probably more the fact that such a term as 'organizer' exists that I dislike than the description itself. I'm a bit wary of adding roles that seem to have little relevance for other languages.

**Comment by gusbrs** [comment]
Well, in this I must trust you (developers) to judge from the wider perspective you have. In the request I made, I never claimed this suggested editorial role meant something different from what I just described and neither that the same issue arose in other languages. I also recognized that there were ways around it (as suggested by you in TeX.SX). Still, I can assure you it is relevant for those who depend on `brazilian.lbx`. But I can certainly see your point. If you happen to reconsider the case, I'll be sad, but will no doubt understand.

**Comment by moewew** [comment]
Well, in the past the developers (amongst which I don't really count myself) have often taken a conservative stance towards inclusion of new 'features' (for lack of a better word), especially those that have limited application (in this case being *probably* limited to a few languages) and/or are easily solved (as shown on TeX.SX). And I happen to like that approach.

Introducing a new bibstring means that one needs to give meaning to it across languages.

I neither want to reconsider the introduction of this new bibstring nor do I see it to be my call to decide such things. My earlier comments were specifically about my failing to understand what an 'organizer' is (in other languages; i.e. how would it be translated into languages that don't have an account of using that role), what describes her role best (other than 'is sometimes used instead of 'editor' in Brazilian') and my conservative stance on including new strings. (Though I will admit I just added twelve new bibstrings in #534 - so that worked out great.)

**Comment by plk** [comment]
Well, I can see that it makes sense for events - then naturally there might be an "organiser".

**Comment by moewew** [comment]
Mhh yes, that is the only thing I could really think of.

**Comment by gusbrs** [comment]
I feel somewhat lost in translation here. I don't have much to add beyond what I said above. But, perhaps some concrete examples might be useful.

Here is one example with organizer:
![organizer1](https://cloud.githubusercontent.com/assets/19410606/24589117/5c1ae9bc-17ab-11e7-99f2-67aed57153e9.jpg)

Here is another one:
![organizer2](https://cloud.githubusercontent.com/assets/19410606/24589127/871e325e-17ab-11e7-9b68-8fe6bd6d10bd.jpg)

Here is an example with editor (notice the term "editora" for the publisher below):
![editor](https://cloud.githubusercontent.com/assets/19410606/24589128/905ec072-17ab-11e7-8f8b-28c088a7e9a6.jpg)

Here is an example with coordinator:
![coordinator](https://cloud.githubusercontent.com/assets/19410606/24589130/97251a3c-17ab-11e7-8430-36d3d51758f2.jpg)

Sure, if the strings are kept under the rationale that they are pertinent for events, they are equally welcome and equally useful. (One would have to consider then, if the changes made to documentation are the adequate ones).
But anyway, when I said I trust your judgment, I really meant it. As an user for some time, I've really come to appreciate and respect the work you guys do here. So I would as well resent if the suggested changes resulted in more nuisance than benefits.
