### ISSUE TITLE
beamer and \newrefsection: entry \blx@keyaliases@1 not found

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#544]
Consider the following MWE using the `beamer` document class
```
\documentclass{beamer}
\usepackage[backend=biber]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\newrefsection
\nocite{sigfridsson}
\printbibliography
\end{document}
```
When Biber is run on the `.bcf` it complains:

> `WARN - I didn't find a database entry for '\blx@keyaliases@1 ' (section 0)`

and rightfully so, seeing that the `.bcf` contains 

```
  <!-- CITATION DATA -->
  <!-- SECTION 0 -->
  <bcf:bibdata section="0">
    <bcf:datasource type="file" datatype="bibtex">biblatex-examples.bib</bcf:datasource>
  </bcf:bibdata>
  <bcf:section number="0">
    <bcf:citekey order="1">\blx@keyaliases@1 </bcf:citekey>
  </bcf:section>
  <!-- SECTION 0 (cont.) -->
  <bcf:section number="0"> 
```

I could only reproduce the problem with `beamer` and `\newrefsection`.

**Comment by moewew** [comment]
OK, I think I have chased down the problem a bit
`biblatex` patches `\addtocontents` to set the `refesction` counter whenever it writes something

https://github.com/plk/biblatex/blob/5169d2a64777090aa29d38df7543301f5c8b876b/tex/latex/biblatex/biblatex.sty#L418-L423

This is a problem if `beamer` is used because then this is done for the `.nav` file as well. The `.nav` file is read in a way that the redefinition of `refsection` leaks out, causing problems and wrongly set `refsection`s later on.

I'm not sure what the solution should be though. Should we stop adding the right counter to `\addtocontents` (probably not, this will upset citations in the toc)? Should/Can we do a more selective patch? Could `beamer` do anything about this? @josephwright

**Comment by moewew** [comment]
Solved on the `beamer` side by reading the `.nav` file in a group. This prevents the wrong counter initialisation from spilling over into the document. https://github.com/josephwright/beamer/issues/442, https://github.com/josephwright/beamer/pull/443, https://github.com/josephwright/beamer/commit/615901bfde6ffe4123ea8809328b74d8cd0673ef

**Comment by dbitouze** [comment]
I stumbled upon [a similar issue](https://tex.stackexchange.com/q/632318/18401) with the `microtype` package.

**Comment by moewew** [comment]
I can't reproduce the issue with the dev versions (`biblatex` 3.17/Biber 2.17), which are to be released to CTAN in the hopefully very near future (we're only waiting for the FreeBSD biber binary to be built). So let's wait until after the 3.17 release. If the problem resurfaces then, please open a new issue.
