### ISSUE TITLE
\DeclareFieldFormat{url} has no effect

### ISSUE THREAD

**Issue by marcodaniel** [plk/biblatex#545]
Hello,

based on a question of TeX.StackExchange http://tex.stackexchange.com/questions/361414/link-button-instead-of-complete-url-in-bibliography I noticed that the declaration by `\DeclareFieldFormat{url}` has no effect. For me the macro `{url}` should be changed.

At the moment the you have the following line in the dev-branch:
https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/biblatex.def#L2679

```LaTeX
\newbibmacro*{url}{\printfield{url}}
```
I think the correct definition should be

```LaTeX
\newbibmacro*{url}{\printfield[url]{url}}
```

**Comment by moewew** [comment]
Mhhh, normally `\printfield` should pick up the default format automatically. That is, `\printfield{url}` should already use the format defined for `url`. I checked with the MWE in your answer and could get the correct result even when I commented out the `\newbibmacro*{url}` line.

**Comment by marcodaniel** [comment]
Indeed now it works :-( I don't know what happened. Sorry for interruption.
