### ISSUE TITLE
\ifnumeral chokes on a single Cyrillic letter

### ISSUE THREAD

**Issue by eg9** [plk/biblatex#559]
Consider the example file

    %\errorcontextlines=1000
    \documentclass{article}
    
    \usepackage[utf8]{inputenc}
    \usepackage[T2A]{fontenc}
    \usepackage[russian]{babel}
    
    \usepackage{biblatex}
    
    \begin{document}
    
    \makeatletter
    \blx@imc@ifnumeral{Н}{\typeout{numeral}}{\typeout{not numeral}}
    \blx@imc@ifnumeral{О}{\typeout{numeral}}{\typeout{not numeral}}
    \blx@imc@ifnumeral{П}{\typeout{numeral}}{\typeout{not numeral}}
    \blx@imc@ifnumeral{н}{\typeout{numeral}}{\typeout{not numeral}}
    \blx@imc@ifnumeral{о}{\typeout{numeral}}{\typeout{not numeral}}
    \blx@imc@ifnumeral{п}{\typeout{numeral}}{\typeout{not numeral}}
    \makeatother
    
    \end{document}

As far as I understand, `\blx@imc@ifnumeral` becomes `\ifnumeral` in certain contexts. However this produces an error with `О` (U+041E CYRILLIC CAPITAL LETTER O), but no other Cyrillic letter.

Source: http://tex.stackexchange.com/questions/362762/biblatex-a-problem-with-cyrillic-О-in-cite

The error message:

    ! Missing ) inserted for expression.
    <to be read again> 
                       (
    l.14 \blx@imc@ifnumeral{О}
                               {\typeout{numeral}}{\typeout{not numeral}}

When the code in the TeX.StackExchange question is reduced to

    \cite[О]{A}

the error message is (with a high value for `\errorcontextlines`)

    ! Missing ) inserted for expression.
    <to be read again> 
                       (
    \dec@de@UTFviii ...((`#1-"E0)\else \ifnum `#1>"BF(
                                                      (`#1-"C0)\else \ifnum `#1>...
    
    \decode@UTFviii ...the \numexpr \dec@de@UTFviii #1
                                                      \relax )))))\@empty 
    \UTFviii@splitcsname ... \decode@UTFviii #2\relax 
                                                      })
    <argument> ...i@splitcsname \string \u8:?? \relax 
                                                      \MessageBreak not\space se...
    
    \PackageError ...s \@spaces }{Package #1 Error: #2
                                                      }{See the #1 package docum...
    
    \UTFviii@defined ...\space with\space LaTeX}\@eha 
                                                      \else \expandafter #1\fi 
    <to be read again> \edef \blx@tempa {??
                                           }
    \blx@ifnum ...t \uppercase {\edef \blx@tempa {#2}}
                                                      \ifx \blx@tempa \@empty \a...
    
    \blx@mkpageprefix #1[#2]#3->\ifnumeral {#3}
                                                {\bibstring {#1}\ppspace } {\ifn...
    <argument> ...sname abx@field@postnote\endcsname }
                                                      \blx@endunit 
    \@secondoftwo #1#2->#2
                          
    \blx@citeprint ...estcite \@gobble }\blx@postcode 
                                                      \fi \blx@endlangcite \endg...
    
    \etb@forlistloop@i ...&->\ifblank {#2} {} {#1{#2}}
                                                      \ifblank {#3} {\listbreak ...
    
    \blx@citei@cite ...{postnote}#4}\blx@citeloop {#3}
                                                      \endgroup 
    \mkbibbrackets ...lx@setsfcodes \bibopenbracket #1
                                                      \bibclosebracket \endgroup 
    \blx@cite@cite ...lxciteicmd {cite}{#1}{#2}{#3}{}}
                                                      #4\endgroup 
    l.36 \cite[О]{A}.

making it clear that `\ifnumeral` is the culprit.

**Comment by plk** [comment]
This is another UTF8 issue with pdflatex - with lualatex it's fine. I am loathe to mess about with `\ifnumeral` for this since there is a workaround and the long term change to a utf8 aware engine for everyone is inevitable.

**Comment by moewew** [comment]
Mhhh, the problem is really that with pdfLaTeX
```
\uppercase{О}
```
throws an error, while its Cyrillic friends `П` and others are OK.

**Comment by moewew** [comment]
It seems as though in general `\uppercase`/`lowercase`'ing of Cyrillic letters might be a bit of a risk.
See

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[T2A]{fontenc}

\def\procchar#1{#1--\uppercase{#1}--\lowercase{#1}\par}

\begin{document}
\procchar{А}\procchar{а}\procchar{Б}\procchar{б}\procchar{В}\procchar{в}
\procchar{Г}\procchar{г}\procchar{Д}\procchar{д}\procchar{Е}\procchar{е}
\procchar{Ё}\procchar{ё}\procchar{Ж}\procchar{ж}\procchar{З}\procchar{з}
\procchar{И}\procchar{и}\procchar{Й}\procchar{й}\procchar{К}\procchar{к}
\procchar{Л}\procchar{л}\procchar{М}\procchar{м}\procchar{Н}\procchar{н}
\procchar{О}\procchar{о}\procchar{П}\procchar{п}\procchar{Р}\procchar{р}
\procchar{С}\procchar{с}\procchar{Т}\procchar{т}\procchar{У}\procchar{у}
\procchar{Ф}\procchar{ф}\procchar{Х}\procchar{х}\procchar{Ц}\procchar{ц}
\procchar{Ч}\procchar{ч}\procchar{Ш}\procchar{ш}\procchar{Щ}\procchar{щ}
\procchar{Ъ}\procchar{ъ}\procchar{Ы}\procchar{ы}\procchar{Ь}\procchar{ь}
\procchar{Э}\procchar{э}\procchar{Ю}\procchar{ю}\procchar{Я}\procchar{я}
\end{document}
```

As I understand it we need `\uppercase` to perform our `\blx@ifnum` checks
https://github.com/plk/biblatex/blob/63eef9e398d923c43a2f90ab1e24a240c892e049/tex/latex/biblatex/biblatex.sty#L2748-L2788

Any idea what we should do to get this right @eg9?

**Comment by eg9** [comment]
`\uppercase` is definitely wrong with non ASCII characters.

**Comment by moewew** [comment]
That's not brilliant. `\ifnumerals` and friends rely on `\uppercase` to process text input.

Since we are stuck with LaTeX2e we can't use `\tl_upper_case:n` (plus, I don't know if it would give us what we need anyway).

**Comment by perstar** [comment]
Is it not possible to roll your own `\uppercase` and `\lowercase` that takes the argument apart like the one in the answer at [https://tex.stackexchange.com/questions/342257/make-uppercase-of-result-of-strleft-with-cyrillic-argument](url)?

**Comment by moewew** [comment]
@perstar Thanks for looking into this. I'm not sure, however, if that would help us. I'm no TeX wizard and I certainly can't say I understand what the answer you linked to does exactly, but here we are not really looking for a macro that turns letters into their actual uppercase counterparts. `\uppercase` is rather used as a sly trick to remove certain characters from the argument.

**Comment by moewew** [comment]
All `biblatex`-related examples in this tread seem to work with a current LaTeX installation. So I guess this was fixed by changes beyond out control. The relevant code in `biblatex.sty` has not changed and it still doing `\uppercase` on its input.
