### ISSUE TITLE
Userdefined DOI-links when using hyperref

### ISSUE THREAD

**Issue by buhtz** [plk/biblatex#563]
When using `hyperref` package `biblatex` generates for all entries with DOIs links to `https://dx.doi.org/`.

It would be very nice if it would be possible to modify that.

First of all it would be nice if you could give me a hint, where in the code this happens. I am not able to find the correct location. ;)

**Comment by moewew** [comment]
You can already change that. The relevant code is
```
\DeclareFieldFormat{doi}{%
  \mkbibacro{DOI}\addcolon\space
  \ifhyperref
    {\href{https://doi.org/#1}{\nolinkurl{#1}}}
    {\nolinkurl{#1}}}
```

If you need more help, you can ask over on your favourite TeX help site (e.g. https://tex.stackexchange.com/).

**Comment by buhtz** [comment]
Great. I didn't understand the complete code.
Is there a need to modify the original biblatex code.
Couldn't I just call `\DeclareFieldFormat{doi}...` again in my own tex file. Can I overwrite it kind of?

**Comment by moewew** [comment]
You do not have to modify any of the files that come with `biblatex`, and indeed it is a bad idea to do so. You can just drop the redefinition into the preamble of your `.tex` file and this will overwrite the default setting.

For example
```
\DeclareFieldFormat{doi}{%
  \mkbibacro{DOI}\addcolon\space
  \ifhyperref
    {\href{https://example.edu/doi/#1}{\nolinkurl{#1}}}
    {\nolinkurl{#1}}} 
```
will still display the DOIs as before but link them to `https://example.edu/doi/...`.

If you have any more questions, please consider asking over at TeX.SX (https://tex.stackexchange.com/questions/tagged/biblatex).
