### ISSUE TITLE
autolang=hyphen with polyglossia

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#564]
Via https://tex.stackexchange.com/q/365562/35864 on TeX.SX.

The MWE 
```
\documentclass[a4paper]{article}
\usepackage{polyglossia}
\setdefaultlanguage[variant=american]{english}
\setotherlanguage{german}
\usepackage{csquotes}
\usepackage[style=verbose-ibid,autolang=hyphen,backend=biber]{biblatex}
\addbibresource{biblatex-examples.bib}
\begin{document}
Here I cite Sigfridsson\autocite{sigfridsson} and Spiegelberg\autocite{spiegelberg}.
\printbibliography
\end{document}
```

Shows that `biblatex` still switches the language even in `hyphenrules` (which should not happen).

This seems to be caused by https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/biblatex.sty#L5489 where the language strings are loaded explicitly regardless of the environment.

**Comment by moewew** [comment]
I see you already merged the change.

I could not run comprehensive tests, so we should definitely keep an eye on this change.

**Comment by plk** [comment]
I am running my test suite now

**Comment by plk** [comment]
Test suite passes and output is identical to before - I can't vouch for the test docs covering this particular case specifically however ...

**Comment by moewew** [comment]
Good, I feared as much. Do some of them even use `polyglossia`? `babel` is unaffected by the problem and the fix.

**Comment by plk** [comment]
Polyglossia support was quite a theme a while ago and it took quite some effort to put it in ...

**Comment by moewew** [comment]
That's good then, if the documents contain a bit of playing around with it, we should be good. (Is the test suite included in the repository? How do you run it?)

**Comment by plk** [comment]
You can run `obuild/build.sh test` - see that script. To actually test the output of this against the reference PDFs (`obuild/build.sh testoutput`), you need to have perl with the `CAM::PDF` module installed ...

**Comment by moewew** [comment]
OK thanks. Maybe I will play around with the test suite if I can find the time.

**Comment by plk** [comment]
@moewew - can we close this now?

**Comment by moewew** [comment]
I think so, yes.

**Comment by bendix3** [comment]
Sorry to bother you, but this issue does not seem to be fixed, at least for me. Am I missing something?

**Comment by plk** [comment]
@bendix3 - are you using the 3.8 development version of biblatex (which needs the 2.8 development version of biber if you use biber).

**Comment by bendix3** [comment]
I'm not, just the standard Tex Live distribution. I'll remember to read the readme next time. So when will the development versions get to CTAN, if I may ask? Because we work on projects as a team, getting everyone to install the development version is not practical. Thanks!

**Comment by plk** [comment]
We are currently working to close some outstanding tickets before a new release. Hopefully in a week or so.
