### ISSUE TITLE
date fields with day cause warnings for @online entries

### ISSUE THREAD

**Issue by languitar** [plk/biblatex#571]
The biblatex manual states that `date` is preferred over `year` due to the support for more fine-grained specifications. However, when building a bibliography with the following entry:

```
@online{Wikipedia2017,
 date = {2016-12-20},
 organization = {Wikipedia},
 title = {Resource contention},
 url = {https://en.wikipedia.org/w/index.php?oldid=755891262},
 urldate = {2017-04-26}
}
```
I see the following warning:

> thesis.bbl: [biblatex] Biber reported the following issues with 'Wikipedia2017': - Datamodel: Entry 'Wikipedia2017' (thesis.bib): Invalid field 'day' for entrytype 'online'. (page 1)

Could this have a similar cause as #523?

**Comment by moewew** [comment]
Can you check with the development version? PLK did some more restructuring of `blx-dm.def` in the light of #523. With the current development version things should in theory be better and in a short test on my machine I got no warning with the new `blx-dm.def.

**Comment by languitar** [comment]
Are there any instructions available how to update to that version?

**Comment by moewew** [comment]
See https://github.com/plk/biblatex/blob/dev/README.md Normally you would download the devopment versions of `biblatex` and Biber from sourceforge (https://sourceforge.net/projects/biblatex/files/ and https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/). Then you would unpack `biblatex` in your local TeX tree and Biber somewhere in your path.

Here, however, it should be enough to get https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/blx-dm.def from github and put it in the same directory as your example document. You just need to remember you put it there and delete it afterwards (at least after a `biblatex` update).

**Comment by languitar** [comment]
Ok, the warning is gone with the new def file. Thanks!
