### ISSUE TITLE
Normalise translatorstrng and translator+otherstrg

### ISSUE THREAD

**Issue by ivalb** [plk/biblatex#572]
The _translatorstrg_ and _translator+othersstrg_ macros from _biblatex.def_ do not use any format to wrap the string. Suppose that we want to redefine _editortype_, for example, via
`\DeclareFeldFormat{editortype}{\mkbibparens{#1}}`
Of course this redefinition does not affect the entries with only a translator (plus _usetranslation_ option), like _vizedom:related_ from biblatex-examples.bib.
Since the _editor_ and the _translator_ has a similar role, bibliographically speaking, I would expect the same format. Here is a MWE:

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}

\usepackage[backend=biber,style=authoryear]{biblatex}
\addbibresource{biblatex-examples.bib}

\DeclareFieldFormat{editortype}{\mkbibparens{#1}}

\begin{document}

\textcite{vizedom:related,gaonkar}

\printbibliography

\end{document}
```

The possible solutions to this issue could be:
1) to define a new field format: _translatortype_
2) to use _editortype_ inside the _translatorstrg_ and _translator+othersstrg_ macros:
```
\renewbibmacro*{translatorstrg}{%
  \printtext[editortype]{%
    \ifboolexpr{
      test {\ifnumgreater{\value{translator}}{1}}
      or
      test {\ifandothers{translator}}
    }
    {\bibstring{translators}}
    {\bibstring{translator}}}}
\renewbibmacro*{translator+othersstrg}{%
  \ifboolexpr{
    test {\ifnumgreater{\value{translator}}{1}}
    or
    test {\ifandothers{translator}}
  }
  {\def\abx@tempa{translators}}
  {\def\abx@tempa{translator}}%
  \ifnamesequal{translator}{commentator}
  {\appto\abx@tempa{co}%
    \clearname{commentator}}
  {\ifnamesequal{translator}{annotator}
    {\appto\abx@tempa{an}%
      \clearname{annotator}}
    {}}%
  \ifnamesequal{translator}{introduction}
  {\appto\abx@tempa{in}%
    \clearname{introduction}}
  {\ifnamesequal{translator}{foreword}
    {\appto\abx@tempa{fo}%
      \clearname{foreword}}
    {\ifnamesequal{translator}{afterword}
      {\appto\abx@tempa{af}%
        \clearname{afterword}}
      {}}}%
  \printtext[editortype]{\bibstring{\abx@tempa}}}

```

**Comment by moewew** [comment]
Would you also be OK with a `editortype` format? For some reason I cannot really explain, I prefer not to use `editor...` in `translator...` macros. Other than that I agree with your request. I will prepare a pull request and @PLK can merge if he thinks that this warrants inclusion into the kernel.

**Comment by moewew** [comment]
A first suggestion is in #573.

While we are at it. Do you think it would make sense to make the separator between `editor` and editorstring in
```
\printnames{editor}%
\setunit{\addcomma\space}%
\usebibmacro{editor+othersstrg}%
\clearname{editor}
```
user-definable? Same with
```
\setunit{\addcomma\space}%
\usebibmacro{authorstrg}
```
and
```
\printnames{translator}%
\setunit{\addcomma\space}%
\usebibmacro{translatorstrg}%
```

**Comment by plk** [comment]
I don't see any reason not to add more user options like this as long as they are backwards compatible and documented. Do we need to use the newer context sensitive mechanism for this?

**Comment by moewew** [comment]
Good point about the context sensitive mechanism. Not all delimiters use it at the moment, I had a discussion on TeX.SX about that a few days ago (https://tex.stackexchange.com/a/365461/35864). I'd like to see more punctuation use it, but we probably need to be careful.

**Comment by ivalb** [comment]
@moewew
(1) For me translatortype is perfect
(2) Yes, it make sense to make the separatore between editor and editorstrg user-difinable. In fact is what I did in the last version of biblatex-philosophy. I used \DeclareDelimFormat but I am not sure if it really needs to be context sensitive. This is required particularly if you redefine editortype as above with \mkbibparens, which makes the comma unnecessary:
John Done (ed.) (1990):  better for me
John Done, (ed.) (1990)

**Comment by moewew** [comment]
Would you say that `editortypedelim` or `editorstrgdelim` is the more appropriate name? I think I prefer the new `\DeclareDelimFormat` approach.

**Comment by moewew** [comment]
I have submitted #574 with `editortypedelim`, if you think `editorstrgdelim` is a more appropriate name, I will push a new commit to the branch renaming the delimiters.

**Comment by plk** [comment]
I am happy to go with whichever name you prefer - you are more on top of this issue than I am ...

**Comment by moewew** [comment]
OK, I'll wait for @ivalb to have a say on the issue. We can change the name as long as we haven't released anything.

**Comment by ivalb** [comment]
OK for me. Besides, editortypedelim is more self-explanatory then editorstrgdelim
