### ISSUE TITLE
Wrong strings for Portuguese

### ISSUE THREAD

**Issue by eg9** [plk/biblatex#578]
The `bycollaborator` strings in `brazilian.lbx` and `portuguese.lbx` are wrong

    > ack 'em colabora' /usr/local/texlive/2016/texmf-dist/tex/latex/biblatex/
    /usr/local/texlive/2016/texmf-dist/tex/latex/biblatex/lbx/brazilian.lbx
    257:  bycollaborator   = {{em colabora\c{a}\~o com}{em col\adddotspace com}},

    /usr/local/texlive/2016/texmf-dist/tex/latex/biblatex/lbx/portuguese.lbx
    257:  bycollaborator   = {{em colabora\c{a}\~o com}{em col\adddotspace com}},

In both cases it should be

    colabora\c{c}\~ao

Reference: https://tex.stackexchange.com/questions/367677/mangled-output-of-accented-characters-with-biblatex-chicago-and-babel-brazilian

**Comment by plk** [comment]
Changed in DEV branch, thanks.
