### ISSUE TITLE
Missing / corrected strings for portuguese.lbx

### ISSUE THREAD

**Issue by gusbrs** [plk/biblatex#582]
At @moewew 's request ([plk/biblatex@b72238b](https://github.com/plk/biblatex/commit/b72238bcc449c32cac3043a397511987dae66a56)) I provide missing strings for `portuguese.lbx`. I also took a general look and did sanity checks in the strings set. As I'm Brazilian and not Portuguese, I refrained from intervening when not strictly necessary. The proposed additions/corrections were made only in cases of missing strings or clear errors. I believe these strings should be fine, but in cases which I was less sure of language use, I left a "FIXME: check" as a comment.

    thiscite         = {{especialmente}{esp\adddot}},% FIXME: check
    langbulgarian    = {{b\'ulgaro}{b\'ulgaro}},
    langjapanese     = {{japon\^es}{japon\^es}},
    langslovak       = {{eslovaco}{eslovaco}},
    frombulgarian    = {{do b\'ulgaro}{do b\'ulgaro}},
    fromjapanese     = {{do japon\^es}{do japon\^es}},
    fromslovak       = {{do eslovaco}{do eslovaco}},
    organizer        = {{organizador}{org\adddot}},
    organizers       = {{organizadores}{orgs\adddot}},
    byorganizer      = {{organizado por}{org\adddotspace por}},
    countryep        = {{Uni\~ao Europeia}{EP}},% FIXME: check
    pagetotal        = {{p\'agina}{p\adddot}},
    pagetotals       = {{p\'aginas}{pp\adddot}},
    columntotal      = {{coluna}{col\adddot}},
    columntotals     = {{colunas}{cols\adddot}},
    linetotal        = {{linha}{l\adddot}},
    linetotals       = {{linhas}{ll\adddot}},% FIXME: check
    versetotal       = {{verso}{v\adddot}},
    versetotals      = {{versos}{vv\adddot}},% FIXME: check
    sectiontotal     = {{se\c{c}\~ao}{\S}},
    sectiontotals    = {{se\c{c}\~oes}{\S\S}},
    paragraphtotal   = {{par\'agrafo}{par\adddot}},
    paragraphtotals  = {{par\'agrafo}{pars\adddot}},
    inpreparation    = {{em prepara\c{c}\~ao}{em prep\adddot}},
    reviewof         = {{resenha de}{res\adddotspace de}},% FIXME: check
    byreviewer       = {{resenhado por}{res\adddotspace por}},% FIXME: check
    prepublished     = {{pr\'e publicado}{pr\'e pub\adddot}},% FIXME: check
    patentfr         = {{patente francesa}{pat\adddot\ francesa}},

Most of the cases are of missing strings. But `inpreparation` and `reviewof` had accented non-ascii characters. `reviewof` and `byreviewer` had "avaliado/avaliador" as values which refers to a "peer-reviewer" of a journal. But that's not the meaning `biblatex` attributes to these strings, which is a published review of a work, what is better conveyed in Portuguese by "resenha/resenhado". `prepublished` had a gender issue and `patentfr` had a missing space.
In case any issues or doubts remain, please let me know.

**Comment by moewew** [comment]
The changes are now in #584. I'd appreciate if you went through them to check I didn't make a mistake when copy-and-pasting. 

Again `organizators` has an 's' in the plural abbreviation. Is that intended? Note that `portuguese.lbx` is a bit inhomogeneous with respect to 's' in plural abbreviation (I assume the situation is similar to Brazilian). I don't want to force you to go through the whole thing here again, just a short word on whether you prefer 'org' or 'orgs' is fine.

**Comment by gusbrs** [comment]
@moewew , Thank you. I'll check #584 soon.
As I explained in [plk/biblatex@b72238b](https://github.com/plk/biblatex/commit/b72238bcc449c32cac3043a397511987dae66a56), yes the 's' in `organizers` is intended. And, yes, you are right in saying that the abbreviated plurals are inhomogeneous and also the abbreviated form of "commentator" and related forms is not standardized. It is the same situation as with `brazilian.lbx`. Certainly one of them was heavily used as the base of the other. For me, it would not be a problem at all to do a more general clean up in `portuguese.lbx`. The question is whether it would be appropriate for me, being Brazilian and not so sure of the uses there, to do it. My feeling is that `portuguese.lbx` could indeed be improved. But I might as well unconsciously introduce some other problems. Still, I do believe some standardization would indeed be granted. Given these caveats if you wish me to do it, I'll do it with pleasure.

**Comment by moewew** [comment]
Thank you very much again. Regarding `portuguese.lbx` feel free to do whatever you feel comfortable and competent to do. Overhauling `portuguese.lbx` is not on top of my list of priorities.

**Comment by gusbrs** [comment]
@moewew , it is I who thank you (all) very much. Regarding `portuguese.lbx` I understand that you let the call to me. I thought it over and, to the best of my knowledge and judgement, I do thing it is a good idea to standardize the treatment of abbreviated strings, which is clearly an issue in `portuguese.lbx`. Another reason to do so is that `portuguese.lbx` was very close to `brazilian.lbx`, especially in the role strings involved in this issue, in which I'd say they were almost, if not literally, identical. I'll proceed carefully and get back to you soon.

**Comment by gusbrs** [comment]
@moewew , as promised, an updated version of `portuguese.lbx` in line with our previous discussion can be found at: [https://gist.github.com/gusbrs/ff337c416baa186294f4bc17824c755c](https://gist.github.com/gusbrs/ff337c416baa186294f4bc17824c755c).
