### ISSUE TITLE
\DeclareFieldFormat and spaces between arguments

### ISSUE THREAD

**Issue by eg9** [plk/biblatex#586]
A code such as

    \DeclareFieldFormat{field} {pre #1 post}

fails. Note the space between the two arguments.

Minimal example:

    \begin{filecontents}{\jobname.bib}
      @book{author_book,
      title = {Book's title},
      author = {Author, Some},
      location = {The City},
      publisher = {Publisher},
      date = {2005},
      file = {filename},
    }
    \end{filecontents}
    
    \documentclass{article}

    \usepackage{biblatex}
    
    \AtEveryBibitem{%
        \printfield{file}\addspace
    }
    
    \addbibresource{\jobname.bib}
    
    \begin{document}
    
    \nocite{*}

    % space between the arguments
    \DeclareFieldFormat{file} {pre #1 post}
    
    \printbibliography

    % no space between the arguments
    \DeclareFieldFormat{file}{pre #1 post}
    
    \printbibliography
    
    \end{document}

The output is

![screen shot 2017-05-31 at 14 00 43](https://cloud.githubusercontent.com/assets/302839/26631082/bbe54e32-4609-11e7-83af-c39b9170f346.png)

I suspect other commands similar to `\DeclareFieldFormat` suffer from the same issue.

Reference: https://tex.stackexchange.com/questions/372405/how-to-expand-argument-1

**Comment by plk** [comment]
`\Declare*Format` have rather complicated meta-macros at their top-level definitions which probably are the cause of this.

**Comment by plk** [comment]
I doubt that this can be solved easily given how convoluted the macros that underlie these user-facing macros are. I think it would be better to just put a comment in the docs about this as it's hardly a major imposition on users.

**Comment by plk** [comment]
I have put a comment in the docs about this. It is very hard to fix due to the convoluted definitions of these macros and it's not a huge problem.
