### ISSUE TITLE
Act more robust with outdated package versions

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#587]
A common problem is that users have outdated versions of packages loaded by `biblatex`, this causes at times not immediately obvious errors.

A recent example is an outdated `xstring` package: https://tex.stackexchange.com/q/370927/35864

From experience the problem is very prominent with outdated `babel` (especially `\bbl@loaded`).

For the `\bbl@loaded` issue we could check if the command is defined before using it.

For `xstring` and other packages (not sure which) we could at least use the optional date argument to `\RequirePackage` so that a warning is produced, alternatively we can throw a real error  as is done for `etoolbox`.

**Comment by plk** [comment]
I have added tests for `xstring` and `babel` - can you have a look? I chose the version of babel one after the deprecation notices for the package which should be ok. `xstring` hasn't changed for years as haven't the other packages I think.

**Comment by moewew** [comment]
Looks good. Ideally we would have taken the version of `babel` that introduced `\bbl@loaded`, but I could not find out which version that was.

We probably need to add `etextools` to the list of incompatible packages. I don't quite understand what `etextools` does exactly, but it messes with list handling in such a way that some loops fail. This is a bit weird since I didn't think `etextools` would redefine `etoolbox` internals.

**Comment by plk** [comment]
I couldn't find that version for babel either but everything before 3.9q is deprecated and I think it was before that. I tried to use `etextools` for some things but as you say, it does really strange things with lists. I added an incompat warning for it.

**Comment by moewew** [comment]
It seems the problem with `etextools` is that it redefines `\forlistloop` from `\forlistloop{<handler>}{<listmacro>}` (`etoolbox`) to `\forlistloop{<listmacro or expanded list>}\do{<...#1...>}` (`etextools`). These two definitions are completely incompatible.

I have added a short line in the docs about this: https://github.com/plk/biblatex/commit/75f4f8232182e9bfe6cf729a44957feeb1e76738

**Comment by moewew** [comment]
Here is an interesting one. 

```
\documentclass{article}
\usepackage{polyglossia}
    \setdefaultlanguage{english}
\usepackage[style = authoryear]{biblatex}

\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{sigfridsson}
\end{document}
```
complains about
```
! Package biblatex Error: Outdated 'babel' package.
```
even though `babel` is not loaded. Does `polyglossia` pretend to be `babel`? Even if `polyglossia` should not do that, we probably need to drop 
https://github.com/plk/biblatex/blob/f294293855ebf496adf01c93e26762638fe21677/tex/latex/biblatex/biblatex.sty#L64-L73
to avoid serious problems for users.

**Comment by moewew** [comment]
There are at least two possible solutions.

1. Check for `\bbl@loaded` directly when it is used and only then issue a warning if it is undefined (could be upgraded to an error if you prefer).
2. Modify the `\@ifpackagelater{babel}{2016/04/23}` test above to avoid being fooled by `polyglossia`.

@plk What would you prefer? I'm always torn between throwing a warning or an error. I have code in the pipeline for both.

**Comment by plk** [comment]
Option 2 seems nicer as it gets the test done early.

**Comment by moewew** [comment]
OK. Pushed the changes to dev. I decided to also move the check to `\AtEndPreamble` (https://github.com/plk/biblatex/commit/d7ae9b20437afddce817a01ab7d8153df31f9d55)

**Comment by dbitouze** [comment]
>We probably need to add `etextools` to the list of incompatible packages.

That's a bit rude: the packages `changelayout`, `autonum`, `concepts`, `chemschemex`, `ribbonproofs`, `getfiledate` load it.

**Comment by josephwright** [comment]
@dbitouze But it is basically broken!

**Comment by moewew** [comment]
`etextool` breaks our list handling. When it is loaded together with `biblatex` things fall apart, so I'd rather issue a useful error than an obscure one caused by `etextools`' redefinitions.

**Comment by dbitouze** [comment]
@josephwright I know it is nowdays broken, deprecated, not advised, etc. :) But isn't possible to just prevent `etextools` redefinition of `\forlistloop` in case it is loaded? For instance, that's what `autonum` does:

```latex
\RequirePackage{etoolbox}
[...]
\let\autonum@etoolbox@forlistloop\forlistloop
\RequirePackage{etextools}
\let\forlistloop\autonum@etoolbox@forlistloop
```

and any of the other packages that load  `etextools` make use of `\forlistloop`.

**Comment by moewew** [comment]
Ping back to https://github.com/plk/biblatex/issues/669. I'm thinking about deprecating the `noerroretextools` option for a more primitive mechanism. Please leave comments about this in https://github.com/plk/biblatex/issues/669.
