### ISSUE TITLE
\iffieldxref{labeltitle} when the main entry has no title.

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#588]
Hi, suppose the following things:
- a @book entry without title
- a @inbook entry with title, with crossref to the @book entry. 

- `\iffieldxref{title} return false, as expected.
- `\iffieldxref{labeltitle} return true, which is not the expected result. 

Cf the MWE

```
\documentclass[twoside,11pt]{article}

\usepackage{filecontents}
\begin{filecontents}{biblio.bib}



@book{CCSG26,
	Editor = {Van Deun, Peter and Jacques Noret},
	Number = {26},
	Series = {Corpus Christianorum Series Graeca},
	Shortseries = {CCSG},
	Title = {Hagiographica Cypria}}


@bookinbook{BHG226,
	Author = {{Alexandre de Chypre}},
	Bhg = {226},
	Crossref = {CCSG26},
	Pages = {83-122},
	Title = {Laudatio Barnabae},}


@book{MGH_SS_9,
	Series = {Monumenta Germania Historica Scriptores (in folio)},
	Shortseries = {MGH SS},
	Volume = {9}}

@book{AnnalesZwetlenses,
	Crossref = {MGH_SS_9},
	Editor = {Wilhem Wattenbach},
	Pages = {677-684},
	Title = {Annales Zwetlenses (1-1349)}}

\end{filecontents}
\usepackage[citestyle=verbose-trad2,mincrossrefs=0,citereset=section]{biblatex}
\bibliography{biblio}
\begin{document}

\section{Good}

\renewbibmacro{begentry}{%
  \iffieldxref{title}{oui}{non}%
}

\makeatother
 \cite{AnnalesZwetlenses}
 
 \cite{BHG226}

\section{Wrong}
\renewbibmacro{begentry}{%
  \iffieldxref{labeltitle}{oui}{non}%
}
 \cite{AnnalesZwetlenses}
 
 \cite{BHG226}

\section{Turn around}

 \makeatletter
 \renewbibmacro{begentry}{%
  \entrydata{\thefield{crossref}}{%
  	\savefield{labeltitle}{\labeltitle@crossref}%
  }%
  \ifboolexpr{
     test{\iffieldxref{labeltitle}} 
     and test{\ifnameequals{labeltitle}{\labeltitle@crossref}}%
     }%
    {oui}{non}%
}

 \cite{AnnalesZwetlenses}
 
 \cite{BHG226}



\end{document}
```

**Comment by moewew** [comment]
This is an interesting one.

As far as I can tell it comes from the fact that `labeldate` is a dynamic field coupled with how the comparison is done.

Essentially `biblatex` saves the content of the child entry and then gets the data from the parent entry -with `\getdata` that means that in the current context all fields now come from the parent. Then it compares the relevant field of the parent entry with the saved data from the child. Now `\getdata` simply stores the contents of the fields in the respective macros. It does not undefine macros for fields that are empty - as they don't appear in the `.bbl`. So in this special situation where field contents get overwritten (provided the new ones are non-empty) we run into a problem if the new fields are empty - nothing will be overwritten and the old content will prevail. That was already identified as a problem, so we find `\csundef{abx@field@#1}` in the code that makes sure to clear the old content of the field to compare before the new contents of the parent are imported. The problem is that in this case `labeltitle` is a virtual field that dynamically uses several possible other fields as source. So we would have to clear all relevant fields before proceeding. This is not done at the moment.

**Comment by plk** [comment]
This is correct - I suspect the solution is fairly simple - use the `\abx@dorfields` and `\abx@dornames` macros to clear these dynamic fields too - @moewew - perhaps you can try this?

**Comment by moewew** [comment]
OK, here is a possible fix

Instead of only deleting the (one relevant) field with `\csundef{abx@field@#1}` we use the full `\blx@resetdata`:

```
\def\blx@iffieldxref#1#2{%
  \begingroup
  \letcs\blx@tempa{abx@field@#2}%
  \letcs\blx@tempb{abx@field@#1}%
  \csundef{abx@field@#1}%
  \blx@getdata{\blx@tempa}%
  \blx@imc@iffieldequals{#1}\blx@tempb
    {\aftergroup\@firstoftwo}
    {\aftergroup\@secondoftwo}%
  \endgroup}
```
becomes
```
\def\blx@iffieldxref#1#2{%
  \begingroup
  \letcs\blx@tempa{abx@field@#2}%
  \letcs\blx@tempb{abx@field@#1}%
  \blx@resetdata
  \blx@getdata{\blx@tempa}%
  \blx@imc@iffieldequals{#1}\blx@tempb
    {\aftergroup\@firstoftwo}
    {\aftergroup\@secondoftwo}%
  \endgroup}
```

**Comment by moewew** [comment]
I have put together pull request #590. Please test this thoroughly, I suspect @maieul has quite some interesting test cases for `\iffieldxref` and friends.

**Comment by maieul** [comment]
I will try to do test this week-end. Please send me an email monday if I didn't do.

**Comment by maieul** [comment]
Hi, I have tried the pull requets #590 with the previous MWE. I get 

<code>
(/Users/maieul/Library/texmf/tex/latex/biblatex/biblatex.cfg))
! Missing number, treated as zero.
</code>

**Comment by maieul** [comment]
(I get it before the \addbibresource / \bibliography command)

**Comment by moewew** [comment]
Ah yes. If you just download the files from dev you get errors, because the files have no version information in `biblatex.sty`. You could try copying over the first few lines of `biblatex.sty` from the current release.

**Comment by maieul** [comment]
Ok. I tried with this MWE + a real case use. All is fine (but I have only one case if `\iffieldxref` in my styles.

**Comment by moewew** [comment]
Brilliant. Thanks for following up on this. Theoretically, there should be no problem with the patch. And a few tests I ran brought up no problems, either. I think we can merge.

**Comment by maieul** [comment]
For reledmac, I have found a way to make test to be sure there is no breaking change. I have a script which 
1. Export .pdf example to a series of .png files
2 Comparer these .png file with the other one, and make an error if one pixel or more have changed. 

It is quite long to execute, but I am sur it's working.

**Comment by plk** [comment]
I have merged and updated 3.8 DEV. I think we should release very shortly. I already have a test suite like that which compares PDFs like that.

**Comment by maieul** [comment]
nice !

**Comment by moewew** [comment]
PLK also has some test suite in place. The danger is always that your test cases don't cover everything. As far as I can see `\iffieldxref` and friends are not very widely used and I'm not sure about the test suite.

**Comment by plk** [comment]
We don't test anywhere near everything in detail - @josephwright was looking into a real test suite using expl3 and I have a basic framework in place for this but there were structural issues with testing package and biber last time I looked.

**Comment by moewew** [comment]
@plk  Before we release, I would like to at least fix the easy bits of `mergedate`. Cf https://github.com/plk/biblatex/issues/540 and https://github.com/plk/biblatex/issues/520 But I'm not sure how to tackle this. In a way `mergedate` is a bit overwhelmed by the new date system.
