### ISSUE TITLE
Ukrainian localization for BibLaTeX

### ISSUE THREAD

**Issue by sergiokapone** [plk/biblatex#589]
I had created ukrainian.lbx for BibLaTeX, How can I add it to package?
[ukrainian.lbx.txt](https://github.com/plk/biblatex/files/1056945/ukrainian.lbx.txt)

**Comment by sergiokapone** [comment]
[ukrainian.lbx.txt](https://github.com/plk/biblatex/files/1056940/ukrainian.lbx.txt)

**Comment by moewew** [comment]
Thank you very much for your time to translate the strings.

In the last few weeks some more strings have been introduced that were not included in the last release of `biblatex`. Could you also have a look at those?  Cf. https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/lbx/english.lbx and https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/lbx/russian.lbx

You can check your translations and find missing ones by using the test document https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/examples/03-localization-keys.tex Just switch the language to Ukranian and make sure the `.lbx` is in the same folder. Missing keys will throw a warning and will be highlighted in bold.

**Comment by sergiokapone** [comment]
Oh! Thank your for answer. I have added missing strings and the 03-localization-keys.tex  compiled without warnings.
[ukrainian.lbx.txt](https://github.com/plk/biblatex/files/1057261/ukrainian.lbx.txt)

**Comment by moewew** [comment]
Thank you again. Do you want to appear amongst the translators in the docs? If so, please tell me your name.

**Comment by sergiokapone** [comment]
Yes, let I be appear in amongst the translators. My name is Sergiy M. Ponomarenko.
Portion of small corrections: 
[ukrainian.lbx.txt](https://github.com/plk/biblatex/files/1057286/ukrainian.lbx.txt)

**Comment by moewew** [comment]
Thank you very much.

I have added two new strings `fromukrainian` and `langukrainian` could you also translate those?

**Comment by moewew** [comment]
BTW: You may also want to look at making `csquptes` support Ukrainian: https://github.com/josephwright/csquotes

**Comment by sergiokapone** [comment]
--- ukrainian ---
langukrainian  = {{українська}{укр\adddot}},
fromukrainian = {{з української}{з\addabbrvspace укр\adddot}},

--- russian ---

langukrainian  = {{украинский}{укр\adddot}},
fromukrainian = {{с украинского}{з\addabbrvspace укр\adddot}},

**Comment by moewew** [comment]
Thank you. This has been added.

**Comment by moewew** [comment]
Oh. Hang on. Don't we want 'с укр' in the abbreviated form of `fromukrainian` in Russian?

**Comment by sergiokapone** [comment]
Sorry, yes, in Russian correct "с укр"

**Comment by moewew** [comment]
Thanks. I have corrected the string.
