### ISSUE TITLE
Why is year a field and not a datepart?

### ISSUE THREAD

**Issue by equaeghe** [plk/biblatex#595]
In the manual, I see that `year` is a `field`, whereas `month` is a `datepart`; I would expect both to be `datepart`s. Is this also the case in the biblatex code? If so, is there a reason for this?

(I am just curious, but do not have a practical reason for asking. So feel free to treat this as low priority.)

**Comment by plk** [comment]
Yes, this is by design because year can also be a standalone field for backwards compat with traditional bibtex.

**Comment by equaeghe** [comment]
But `month` is also traditional BibTeX, no?

**Comment by plk** [comment]
Ah, I see the confusion. `year` is only a literal when explicitly given, as is `month`. I will change the docs for 3.8 to reflect this.
