### ISSUE TITLE
provide field for file type and file size of URL

### ISSUE THREAD

**Issue by lemzwerg** [plk/biblatex#596]
I think it would be beneficial if biblatex provided a new field to set the file type of a URL, for example 'pdf' or 'MS-Excel'.  Such a field could be positioned directly after the link (in parentheses).

Similarly, another field could give the size of the link, to be used mainly for large files.

**Comment by plk** [comment]
I doubt that this would be used much by most people. If you want it - you can add it yourself - the datamodel is completely customisable.

**Comment by moewew** [comment]
If you need help defining these new fields yourself, you can ask over at TeX.SX (https://tex.stackexchange.com/tags/biblatex/)
