### ISSUE TITLE
Provide documentation as a docset for dash/zeal/dasht

### ISSUE THREAD

**Issue by languitar** [plk/biblatex#600]
It would be really cool if the documentation of biblatex was available as a docset for common documentation browsers like [Zeal](https://zealdocs.org/) or [dash](https://kapeli.com/dash).

There is some advice online how to generate such a docset: https://kapeli.com/docsets

**Comment by moewew** [comment]
Mhhh, natively the documentation is in LaTeX. And I didn't find a way to convert LaTeX into docset. So I assume this would take quite a lot of work to get right (especially if one wants to use the features of docset properly).

Is there precedence of a LaTeX package providing such a docset? Would you be up to port and to maintain the docset version of the documentation?

**Comment by languitar** [comment]
No, unfortunately not. Only latex itself has a docset. I suspect it would be easier if the documentation was generated from a dtx file, where automatic processing is easier.

Maybe the special commands in the biblatex documentation for documenting certain aspects could be patched to write out some kind of structured information but this also sounds tedious and is by no means general.

Another road could be to convert the whole documentation to sphinx, which could still generate a LaTeX-based PDF, but also HTML, man pages etc. There is an importer for sphinx-based documentation for docsets.

**Comment by plk** [comment]
I think I may close this because, having a look at the reST language etc. it would be a huge job to convert the `biblatex` PDF doc, especially the tables and code snippets. I will consider this for a "quick start" document however, which we badly need ...
