### ISSUE TITLE
Sorting of braced (corporate) authors with alphabetic style and BibTeX

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#601]
Via https://tex.stackexchange.com/q/372093/35864

Consider the MWE
```
\documentclass{article}
\RequirePackage{filecontents}

\begin{filecontents}{\jobname.bib}
@online{a,
author = {{Albert}},
title = {Title},
}

@book{b,
author = {Bernd},
title = {Title},
}

\end{filecontents}

\usepackage[style=alphabetic, backend=bibtex]{biblatex}
\addbibresource{\jobname.bib}
\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

The sorting I get is
> [Ber] Bernd. Title.
[Alb] Albert. Title.

`Bernd` sorts before `{Albert}`. So it seems that with `alphabetic` braces are not stripped before sorting. 
Indeed, in the `.bbl` we get `\field{labelalpha}{Ber}` and `\field{labelalpha}{{Alb}}` as well as `\field{sortinit}{B}` and `\field{sortinit}{{A}}`. So `Bernd` sorts under `B` and `{Albert}` under `{{A}}`.

With `style=authortitle` the sorting is as expected. Sorting with Biber is good as well.

**Comment by plk** [comment]
Perhaps @josephwright could have a look since it's about bibtex.

**Comment by josephwright** [comment]
OK, I'll take a look :)

**Comment by moewew** [comment]
We can almost get away with adding `purify` in

https://github.com/plk/biblatex/blob/8d925e4e3128fe82ea714ffa901ba07079d52ba6/bibtex/bst/biblatex/biblatex.bst#L2628-L2629

to make things read

            { labelalpha purify 'sortkey.alpha := }
            { labelalpha normalize extraalpha #4 pad.number * purify 'sortkey.alpha := }

That would certainly get rid of the unnecessary braces for sorting. But it also removes the `alphaothers` in case that is non-alphanumeric which could be a annoying for
```latex
\documentclass{article}
\RequirePackage{filecontents}

\begin{filecontents}{\jobname.bib}
@online{a,
author = {{Albert}},
title = {Title},
year = {1990},
}
@online{a3,
author = {{Albert}},
title = {Title},
year = {1989},
}
@online{a1,
author = {{Albert}},
title = {Title},
year = {1991},
}
@online{a2,
author = {{Albert} and others},
title = {Title},
year = {1990},
}

@book{b,
author = {Bernd},
title = {Title},
}

\end{filecontents}

\usepackage[style=alphabetic, backend=bibtex]{biblatex}
\addbibresource{\jobname.bib}

\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

So I came up with
```
FUNCTION {labelsort:alph:reverse} {
  ctrl:labelalpha
    { last.extra "2" =
        { "1" 'extraalpha := }
        'skip$
      if$
      extraalpha 'last.extra :=
      labelalpha empty$
        'skip$
        { extraalpha empty$
            { labelalpha ctrl.alphaothers "ZZZETALzzz" str:replace purify "ZZZETALzzz" ctrl.alphaothers str:replace 'sortkey.alpha := }
            { labelalpha ctrl.alphaothers "ZZZETALzzz" str:replace purify "ZZZETALzzz" ctrl.alphaothers str:replace extraalpha #4 pad.number * 'sortkey.alpha := }
          if$
        }
      if$
    }
    'skip$
  if$
}
```
not very elegant, but it should do the job if the work was not written by people with initials `ZZZETALzzz`...

**Comment by josephwright** [comment]
The style of the `.bst` would be to have that fixed string as a variable: it would then be possible if required to provide a way to alter it from the TeX side.

**Comment by josephwright** [comment]
@moewew Working on it ... almost at the station ;)

**Comment by moewew** [comment]
Cool. Have a pleasant ride.

**Comment by moewew** [comment]
Just for reference, there is a Biber-only feature called `\sortalphaothers` that essentially takes the role of my `ZZZETALzzz` for Biber.

**Comment by josephwright** [comment]
@moewew Approach looks reasonable to me: the standard sign being `+` is otherwise an issue.

**Comment by moewew** [comment]
Very well, I put together https://github.com/plk/biblatex/pull/763. Another pair of eyes going over those changes would be appreciated.

**Comment by josephwright** [comment]
@moewew I'll take a look shortly

**Comment by moewew** [comment]
@josephwright Brilliant, thank you.
