### ISSUE TITLE
Unnecessary brackets around extrayear

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#603]
Via http://texwelt.de/wissen/fragen/20499/biblatex-eliminieren-der-klammer-um-kleinbuchstaben-hinter-jahreszahl

```
\documentclass[ngerman]{scrartcl}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}
\usepackage[style=authoryear, backend=biber]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@online{Grundprinzipien,
    author = {FSC},
    title = {Die Regeln für den Wald. 10 Grundsätze -- weltweit},
    url = {http://www.fsc-deutschland.de/de-de/der-fscr/prinzipien},
    urldate = {2017-07-31}
}

@report{FSC2017,
    title = {Facts and figures},
    type = {Report},
    institutions = {FSC International},
    date = {2017-07-04},
    url = {https://ic.fsc.org/file-download.facts-figures-july-2017.a-2020.pdf},
    urldate = {2017-07-12},
    author = {FSC}
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}
\autocite{Grundprinzipien,FSC2017}

\printbibliography
\end{document}
```
produces
> FSC (2017a). Facts and figures. Report. url: https://ic.fsc.org/file-download.
facts-figures-july-2017.a-2020.pdf (besucht am 12.07.2017).
– (2017[b]). Die Regeln für den Wald. 10 Grundsätze – weltweit. url: http://www.fsc-
deutschland.de/de-de/der-fscr/prinzipien (besucht am 31.07.2017).

The second entry has a unnecessary pair of square brackets around the `extrayear`.

**Comment by moewew** [comment]
I have put together #604 as a fix. The code worked fine in all my tests, but there was an explicit warning in the comments not to check `labelyear`. I'm not sure whether that warning is obsolete, seeing that the exact contents of the field has changed quite a bit during the date/time restructuring.

**Comment by plk** [comment]
I'm not sure that fix will work because `labelyear` can come from an arbitrary field which might not be a number and then we get an error. Also, `labelyear` can be a range by that point and range markers aren't generally expandable and so the test fails.

**Comment by moewew** [comment]
Did the test suite pass? I did a few more tests even with nonsense settings and the output looked OK.

**Comment by plk** [comment]
Hmm, it seems to be ok, I wonder if there was a change in the core which makes certain unexpandable things ok with such macros. I have committed this and we can close.
