### ISSUE TITLE
\DeclareLanguageMappingSuffix behaviour if files are not found

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#612]
Consider the following MWE that calls on an non-existing suffix.
```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[ngerman]{babel}
\usepackage{lmodern}
\usepackage[T1]{fontenc}
\usepackage[style=authoryear,backend=bibtex]{biblatex}

\addbibresource{biblatex-examples.bib}

\DeclareLanguageMappingSuffix{-archaeologie}

\begin{document}
\cite{sigfridsson,geer}

\printbibliography
\end{document}
```
This produces an error for me that reads
```
Package biblatex Warning: Language 'ngerman' not supported.
(biblatex)                Using fallback language 'english' on input line 12.


! Package biblatex Error: Language 'english' not found.
```
Ideally the code above would not give an error at all, would issue a warning that the suffixed file could not be found and would load the non-suffixed `ngerman.lbx` instead.

-------

OK, I have never really understood those language mappings in the first place.
Suppose that `english-glapa.lbx` exists and I do `\DeclareLanguageMappingSuffix{-glapa}` in a document with main language `ngerman`.
Then with
```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[ngerman]{babel}
\usepackage{lmodern}
\usepackage[T1]{fontenc}
\usepackage[style=authoryear,backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}

\DeclareLanguageMappingSuffix{-glapa}

\begin{document}
\cite{sigfridsson,geer}

\printbibliography
\end{document}
```
I get only the warning
```
Package biblatex Warning: Language 'ngerman' not supported.
(biblatex)                Using fallback language 'english' on input line 12.

(english-glapa.lbx (english.lbx) (american.lbx)) (ngerman.lbx (german.lbx))
```
and the file uses `ngerman.lbx` in the end.

**Comment by plk** [comment]
Done - please try the latest 3.8 DEV version.

**Comment by moewew** [comment]
Thank you. Looks good now.

**Comment by moewew** [comment]
I think there could be a problem with the `\gdef` in https://github.com/plk/biblatex/commit/cc92b78df640e897c87f30ec3258c606df9d4ac1#diff-16278952f4b76d5e95d8f96a5081c2e2R4838.

While trying to come up with an example that shows undesired behaviour I noticed that only the main language is mapped. 

With
```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[english,ngerman]{babel}
\usepackage{lmodern}
\usepackage[T1]{fontenc}
\usepackage[style=authoryear,backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}

\DeclareLanguageMappingSuffix{-glapa}


\begin{document}
\cite{sigfridsson,geer}

\printbibliography
\end{document}
``` 
I get
```
Package biblatex Info: Trying to load language 'ngerman-glapa'...
Package biblatex Info: ... file 'ngerman-glapa.lbx' found.
 (ngerman-glapa.lbx
File: ngerman.lbx 2017/08/14 v3.8 biblatex localization (PK/JW/AB)
Package biblatex Info: Trying to load language 'german'...
Package biblatex Info: ... file 'german.lbx' found.
 (german.lbx
File: german.lbx 2017/08/14 v3.8 biblatex localization (PK/JW/AB)
))
Package biblatex Info: Trying to load language 'english'...
Package biblatex Info: ... file 'english.lbx' found.
 (english.lbx
File: english.lbx 2017/08/14 v3.8 biblatex localization (PK/JW/AB)
```
So for English we load `english.lbx` and not `english-glapa.lbx`.

**Comment by plk** [comment]
Can you try it now? Should be fixed - seems there was a `\gdef` elsewhere that was causing trouble too.

**Comment by moewew** [comment]
I still have one problem.
Assume `ngerman-glapa.lbx` exists and `dutch-glapa.lbx` does not.
Then
```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[ngerman,dutch]{babel}
\usepackage{lmodern}
\usepackage[T1]{fontenc}
\usepackage[style=authoryear,backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}

\DeclareLanguageMappingSuffix{-glapa}


\begin{document}
\cite{sigfridsson,geer}

\printbibliography
\end{document}
```
obviously warns about not finding `dutch-glapa.lbx` and falls back to `dutch.lbx` (good!), but it then goes on to load only `ngerman.lbx` and not as I expected `ngerman-glapa.lbx`.

**Comment by plk** [comment]
Hmm, ok, this is quite tricky. Looking at it.

**Comment by plk** [comment]
I think I have it now - can you try it again? Well, your case works but I have found an even more obscure thing with the APA style and how this impacts the `\mkrelatedstring` macro. More investigation.

**Comment by plk** [comment]
This is quite hard when it is extended to apply to all loaded files because of the recursion inherent in language definitions. For example, in the APA style, I have `-apa` versions for most languages but these usually just add some strings and then load the original language which shouldn't have the suffix applied. However, a new language which is not part of `.lbx` recursion should have it applied ...

**Comment by plk** [comment]
Ok, I think I have a stable solution now and you can try it. I disable suffix addition when recursively loading language files in `\InheritBibliographyStrings`, `\InheritBibliographyExtras` and via the `inherit` keyword in `.lbx` files. This doesn't prevent using the suffix to load multiple languages that are explicitly requested however.

**Comment by moewew** [comment]
Thank you very much. It looks good now. I noticed that I get the warning about the missing mapping multiple times, would it be possible to write it to the `.log` only once?

**Comment by plk** [comment]
Can you try it now. Some very strange behaviour with lists and language keys - probably encoding related. I also added to the documentation to make more explicit where the suffices are checked.

**Comment by moewew** [comment]
The MWEs work as expected. There are no duplicate warnings any more. Everything looks very good now. Thank you.
