### ISSUE TITLE
Document biblatex's behaviour for handling entries with duplicate keys

### ISSUE THREAD

**Issue by logological** [plk/biblatex#613]
Biblatex allows the user to include more than one bibliography using the `\addbibresource` command.  The documentation appears to be silent as to what happens when two resources contain an entry with the same citation key.  Presumably this is always up to the backend to sort out, but it would be useful to state this explicitly (say, in §3.7.1).  See also plk/biber#181.

**Comment by plk** [comment]
That's a fair point - I've added this to the docs.
