### ISSUE TITLE
Order of  `citekey` entries in `.bcf` file is non-deterministic for keys using `ids`

### ISSUE THREAD

**Issue by ziggystar** [plk/biblatex#618]
I have observed that those cites that refer to an entry using an alternative key, defined via `ids`, all appear at the end of the list of `citekey`s within the `bcf` file, and in a different order on each run of `lualatex`. This means that the `bcf` file changes on each run of `lualatex`, and `latexmk` cannot terminate the built.

I'm using biblatex version 3.7. If you require a minimal example, I will try to produce one on request.

**Comment by moewew** [comment]
A minimal example would be really appreciated. It would allow us to investigate the issue in more detail and might give a good start for a regression test. Am I right in assuming that your use Biber as backend?

**Comment by ziggystar** [comment]
@moewew Yes, I'm using biber. It's possible that biber is introducing the nondeterminism. I investigated it a bit myself, and apparently the keyaliases get into the process through the `bbl` file, and then get written out into the `bcf` file again. I did not understand from the comments why this is necessary, this even happens if not the alias, but the primary key gets used. So I had to remove all `ids` fields form my bibliography, as it is not enough to use the primary keys within the document.

I'll try to make a minimal example tomorrow.

**Comment by ziggystar** [comment]
# Reproducible example

The following document reproduces the bug. `latexmk` usually runs forever. There is probably a small chance that the order stays the same between runs.

The nondeterminism is introduced by runnig `pdflatex`, so it's not `biber`. But you have to run `biber` first at least once, I think. Then you can run `pdflatex` and observe that the order of the `citekey`s within the `bcf` file changes on each run.

The data of the entries shouldn't matter, though I tried first with minimal `@misc` entries and it didn't produce the bug. Maybe I made a mistake.

```
\documentclass{article}

\usepackage[backend=biber]{biblatex}
\begin{filecontents*}{main_biber.bib}
@InProceedings{Bacchus2002,
  author       = {Bacchus, Fahiem and Dalmao, Shannon and Pitassi, Toniann},
  title        = {Value elimination: Bayesian inference via backtracking search},
  booktitle    = {Proceedings of the Nineteenth conference on Uncertainty in Artificial Intelligence},
  year         = {2002},
  ids          = {bacchus2002value},
}
@InCollection{Bidyuk2003,
  author         = {Bidyuk, Bozhena and Dechter, Rina},
  title          = {Cycle-cutset sampling for Bayesian networks},
  booktitle      = {Advances in Artificial Intelligence},
  year           = {2003},
  ids            = {bidyuk2003cycle},
}
@InBook{Biere2009,
  author    = {Biere, Armin},
  title     = {Handbook of satisfiability},
  year      = {2009},
  publisher = {Ios PressInc},
  chapter   = {Model Counting},
  ids       = {Biere2009b},
}
@InProceedings{Bouchard2009,
  author       = {Bouchard, Guillaume and Zoeter, Onno},
  title        = {Split variational inference},
  booktitle    = {Proceedings of the 26\textsuperscript{th} Annual International Conference on Machine Learning},
  year         = {2009},
  ids          = {bouchard2009split},
}

@InProceedings{Boutilier1996,
  author       = {Boutilier, Craig and Friedman, Nir and Goldszmidt, Moises and Koller, Daphne},
  title        = {Context-specific independence in Bayesian networks},
  booktitle    = {Proceedings of the Twelfth international conference on Uncertainty in artificial intelligence},
  year         = {1996},
  ids          = {boutilier1996context},
}

\end{filecontents*}

\addbibresource{main_biber.bib}

\begin{document}
    \parencite{bacchus2002value}
    \parencite{bidyuk2003cycle}
    \parencite{Biere2009b}
    \parencite{bouchard2009split}
    \parencite{boutilier1996context}
    \printbibliography
\end{document}

```

**Comment by ziggystar** [comment]
I'll post the bug at `biber`'s project.
