### ISSUE TITLE
User level macro to check if cited

### ISSUE THREAD

**Issue by Skillmon** [plk/biblatex#620]
Basically a user level implementation of the command `\blx@ifentryseen@global` would be useful, imho.

**Comment by plk** [comment]
There already is - `\ifentryseen`?

**Comment by moewew** [comment]
`\ifentryseen` is like many other commands not a user-level command and can only be used from 'within `biblatex`'.

```
\makeatletter
\let\userifentryseen\blx@imc@ifentryseen
\makeatother
```
makes it globally available under the name `\userifentryseen` (to void name clashes with `\ifentryseen`).

I'm not sure exactly why `\ifentryseen` is not user-level, seen that it is independent of the currently processed entry unlike most *Stand-alone Tests* of §4.6.2

**Comment by plk** [comment]
According to the log, it was added a bit later than the other tests in §4.6.2 and so this may have just been an oversight - I am fine with making it user-visible since, as you say, it doesn't depend on entry context.

**Comment by Skillmon** [comment]
Yes/no. There is `\ifentryseen` but this one can only be used in citation context. Consider the following MWE my feature request:

```
\documentclass[]{article}

\usepackage{biblatex}
\addbibresource{biblatex-examples}

\begin{document}
\ifentryseen{angenendt}{yes}{no}
\cite{angenendt}
\ifentryseen{angenendt}{yes}{no}
\end{document}

```

**Comment by moewew** [comment]
There are also `\ifentrykeyword`, `\ifentrycategory`, `\ifentryinbib` that are all not dependent on the processed entry. It would need a bit of testing and thought, but maybe those could be made user level as well.

**Comment by plk** [comment]
It isn't clear to me why any of these would be useful outside of entry processing? @Skillmon - do you have a use case?

**Comment by moewew** [comment]
My worry it the moment is that some of the commands at least depend on the current `refsection`. Maybe some of these also have problems when they are executed at certain points in the document where data has not been read properly.

If there is a need to check if an entry was cited outside of a `biblatex` context I could imagine it would also be useful to check for keywords or if the entry appears in the bibliography.

**Comment by Skillmon** [comment]
@plk I do have a use case, but it's a rather complicated one, I guess. Basically I make tweaks at `beamer`. I have to know prior to executing the cite command whether it was used already or not, because the execution order of how `beamer` manages frame contents and how I tweaked some stuff into `beamer` would otherwise clash.

**Comment by moewew** [comment]
The necessary changes are https://github.com/moewew/biblatex/commit/9878e678933a18f10e4a6e6a687ad9edccfbc110 in https://github.com/moewew/biblatex/tree/ifentryseen

**Comment by plk** [comment]
Ok - this looks fine - I suppose we need some minor doc changes, also documenting those commands in section 3?

**Comment by moewew** [comment]
Is there a good place for those commands in §3? Or can we just leave them in §4 and add a note that they can be used as user-level commands as well?

**Comment by plk** [comment]
That's an option but I suppose that people who just want to use biblatex as a user don't look in section 4. Perhaps a new section in 3 called "Bibliography Entry tests".

**Comment by moewew** [comment]
The unfortunate by-effect of moving the explanations to §3 would mean that we probably can't explain the commands by 'A variant of `\ifciteseen` which takes an entry key as its first argument' because `\ifciteseen` hasn't been explained yet.

**Comment by plk** [comment]
I thought rather duplicating them in section 3 with references between them and more user-oriented comments.

**Comment by moewew** [comment]
OK, if you have an idea I'd be grateful if you could take care of the documentation. I always feel a bit overwhelmed when I try to deal with it.

Do you want me to submit a pull request or merge the suggested code directly?

**Comment by plk** [comment]
Of course - I'll do the docs - just merge directly and I'll pull.

**Comment by moewew** [comment]
Thank you. I have merged https://github.com/plk/biblatex/commit/9878e678933a18f10e4a6e6a687ad9edccfbc110 into `dev`.

**Comment by Skillmon** [comment]
Thank you for your effort, you two :)
