### ISSUE TITLE
Package xkeyval Error: <key> undefined in families `blx@lbx'.

### ISSUE THREAD

**Issue by sergiokapone** [plk/biblatex#628]
After OS reinstall I get an error
Package xkeyval Error: <key> undefined in families `blx@lbx'.
<key> = organizer
           = organizers
           = byorganizer
and some other
for ukrainian
My TeXlive installation updated to the last versions.

**Comment by moewew** [comment]
You are most likely running `biblatex` (>=3.7), but `ukrainian.lbx` contains strings defined in version 3.8.

Until 3.8 comes out you can add `\NewBibliographyString` to your preamble for each of the undefined keys.
So you would need at least
```
\NewBibliographyString{organizer}
\NewBibliographyString{organizers}
\NewBibliographyString{byorganizer}
\NewBibliographyString{byorganizers}
```
and a few others.
Once 3.8 is released this is not needed any more.

**Comment by sergiokapone** [comment]
Ok, thank you. I have another solution, I put corrected .lbx in TEXMFHOME

**Comment by moewew** [comment]
OK, just remember to delete your local (corrected) `.lbx` when `biblatex` is updated. Otherwise your file will hide the actual `ukrainian.lbx`.

**Comment by moewew** [comment]
Can we close this issue here or is there anything else?

**Comment by sergiokapone** [comment]
Yes, you can
