### ISSUE TITLE
\blx@mkautolangpoly makes assumption about _ catcode

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#629]
Via https://tex.stackexchange.com/q/393365/35864

`\blx@mkautolangpoly` assumes that the global (correct) catcode of `_` is 8 (a reasonable assumption) https://github.com/plk/biblatex/blob/d0e866e1ee99027bbad5d530f8bd5b14f593fb6e/tex/latex/biblatex/biblatex.sty#L5550-L5617
The catcode is temporarily changed with
https://github.com/plk/biblatex/blob/d0e866e1ee99027bbad5d530f8bd5b14f593fb6e/tex/latex/biblatex/biblatex.sty#L5556
to 11 and then at the end
https://github.com/plk/biblatex/blob/d0e866e1ee99027bbad5d530f8bd5b14f593fb6e/tex/latex/biblatex/biblatex.sty#L5616
back to 8.

But there are certain situations where we should not assume that the global catcode of `_` is 8, it could be 12 as in the TeX.SX question.

We should in general be careful about assuming correct catcodes.

**Comment by plk** [comment]
@josephwright - do you have a suggestion? I believe the catcode change mentioned was yours as without it we couldn't get polyglossia integration to work at all. Can we just save its value and reset back to the old value instead of 8?

**Comment by moewew** [comment]
Ideally we would work with grouping so that we only set the catcode of `_` to 11 within a group and outside it remains the same. We just need to make sure that we don't hide other assignments in a group so they become unusable, then.

**Comment by moewew** [comment]
There is https://github.com/moewew/biblatex/commit/0319c90a1d6ed8d1307d23d8f9fe606e6735abd6 now. The approach taken there is to save the original catcode of _ and restore it afterwards. I'm not sure if this is the proper way to do it. A similar approach is taken in `inputenc.sty` which makes me hope it is kosher. I could not get a solution with grouping to work since we use `\pretocmd` and I did not find a way to break out of the group then.

Comments by someone knowledgeable and testing would be appreciated.

**Comment by plk** [comment]
I don’t see a problem with this - sometimes the grouping is impossible to track when things can be patched.

**Comment by moewew** [comment]
OK, I can submit a pull request if you want.

**Comment by plk** [comment]
Please do, yes.
