### ISSUE TITLE
Typo in german docu "Zitierfehle"

### ISSUE THREAD

**Issue by buhtz** [plk/biblatex#632]
I can not find the german version of the biblatex docu here in the repo. Where can I find it?

There is a simple typo in a `\subsection` heading. `Zitierfehle` (`be`) is missing.

**Comment by plk** [comment]
We don't have a german version in the repo - that must have come from someone else ...

**Comment by buhtz** [comment]
Of course I know because I told you that the german version isn't in the repo. ;)

**Comment by plk** [comment]
Sorry, I should have been clearer - we don't maintain a German version of the doc - I have no idea where you found it but it must be some third-party ...

**Comment by moewew** [comment]
The German documentation is not maintained here. https://ctan.org/pkg/translation-biblatex-de

The [README](http://mirrors.ctan.org/info/translations/biblatex/de/README) states: 
> Please, send an email to Christine_Roemer@t-online.de, if you have done proposals for improvements.
