### ISSUE TITLE
Control Referencing and Sorting of Set Subentries

### ISSUE THREAD

**Issue by lcnittl** [plk/biblatex#635]
I believe it would be nice to have a feature, that controls the inclusion of set subentries and furthermore apply the `sorting` option to them. Currently (from my observation) the set subentries are (1) always shown in the references as soon as the @set is cited, and (2) sorted as stated in the set's `entryset` field.

Taking a set from the `biblatex-examples.bib`

    @set{set,
      entryset     = {herrmann,aksin,yoon},
      annotation   = {A \texttt{set} with three members. The \texttt{crossref} field
                      in the \texttt{@set} entry and the \texttt{entryset} field in
                      each set member entry is needed only when using BibTeX as the
                      backend},
    }

Now in a MWE:

    \documentclass{article}
    
    \RequirePackage[english]{babel}
    \RequirePackage{csquotes}
    \RequirePackage[backend=biber,subentry=true,sorting=none]{biblatex}
    
    \addbibresource{biblatex-examples.bib}
    
    \begin{document}
      Examples for catalysis are described in \autocite{set}, with a focus on palladium in \autocite{aksin} and carbene chemistry in \autocite{herrmann}.
      \printbibliography
    \end{document}

The current output is: ... [1] ... [1b] ... [1a] ... .
And [1c] is also listed in the references.

This takes away some flexibility, as it's not very nice to have the letters in a wrong order. The bibliography would therefore have dependencies on the tex file (a quite undesired behaviour...).

An optimized output should look like:  ... [1] ... [1a] ... [1b] ... .
And no listing of [1c] in the references.

I don't know if this is possible to achieve or if it is wanted also by other users, but I think it would further enhance `biblatex` (which is already an amazing tool).

**Comment by moewew** [comment]
The whole `@set` implementation has been revised in version 3.8 (not yet released, see #470), but your assumptions and observations are still valid even with the new implementation.

A `@set` is always a collection of all of its members. What you want seems to amount to turn `@set` into a collection of only its explicitly cited members. Currently the order within a set is explicitly determined at definition time - sorting (within) a `@set` is not implemented.

**Comment by plk** [comment]
Isn’t this what dynamic sets were designed for? They are defined in the document, not tge data source.

**Comment by lcnittl** [comment]
@moewew 

> A @set is always a collection of all of its members. What you want seems to amount to turn @set into a collection of only its explicitly cited members.

Yes. My idea was, that a `@set` behaves like a bibliography, and it's members like the entries from the latter. Therefore only explicitly cited members would show up in the reference list, and also would be sorted in citation order (with `sorting=off`).

@plk 

> Isn’t this what dynamic sets were designed for? They are defined in the document, not tge data source.

Don't dynamic sets show exactly the same behavior? Of course it is now defined in the document and therefore more flexible, but still, when changing citation order one has to take care to also reorder the references in the dynamic set definition.

    \documentclass{article}
    
    \RequirePackage[english]{babel}
    \RequirePackage{csquotes}
    \RequirePackage[backend=biber,subentry=true,sorting=none]{biblatex}
    
    \addbibresource{biblatex-examples.bib}
    
    \defbibentryset{set:dynamic}{glashow,salam,weinberg}
    
    \begin{document}
      Examples for catalysis are described in \autocite{set:dynamic}, with a focus on palladium in \autocite{salam} and carbene chemistry in \autocite{glashow}.
      \printbibliography
    \end{document}

Would again yield: ... [1] ... [1b] ... [1a] ... .
And [1c] is also listed in the references.

The question is, if this behavior is wanted if `sorting=none` is active, and why all subentries are "nocited", so that they behave completely different to normal entries (which are not sorted, and not showing up in the references if not cited). And if one would like to have some subentries in the references, they could always be added with `\nocite{<subentry>}`, instead of auto adding them when citing the @set.

**Comment by plk** [comment]
Have you tried the `sortcites` option?

**Comment by lcnittl** [comment]
With the two examples given above, neither `sortcites=false` nor `sortcites=true` changes the output.

**Comment by plk** [comment]
@moewew - I have created a Project to prepare for 3.8 release - please have a look at it and add anything you think we need. One think for you to do is to proof the wiki release notes to see if you agree with them and think anything else need adding.

**Comment by plk** [comment]
I am not convinced about only having explicitly cited members of a set in the references. The whole point of a set is citing a lot of things at once. If you only want some set members to appear when you cite a set, then really what should be done is to redefine the set or define another one. We created dynamic sets precisely to make this easier as I remember.

The sorting issue is more convincing and I'll have to think about how this might be achieved.

**Comment by plk** [comment]
Sorting of set members is now implemented in biblatex 3.8/biber 2.8. There is a new global biblatex option `sortsets` which if set to `true` will sort set members according to the sorting template for the reference context in which they occur. It is false by default so as not to surprise users who expect the old behaviour or sorting according to the datasource defined order.

**Comment by moewew** [comment]
I copied a paragraph from the wiki to CHANGES.org and am happy with both now.

**Comment by lcnittl** [comment]
As the documentary already includes it:
I'm having problems to use `sortsets=true` in `biblatex` version 3.8a (rev: 45702).

```
\documentclass{article}

\RequirePackage[english]{babel}
\RequirePackage{csquotes}
\RequirePackage[backend=biber,subentry=true,sorting=none,sortsets=true]{biblatex}

\addbibresource{biblatex-examples.bib}

\defbibentryset{set:dynamic}{glashow,salam,weinberg}

\begin{document}
  Examples for catalysis are described in \autocite{set:dynamic}, with a focus on palladium in \autocite{salam} and carbene chemistry in \autocite{glashow}.
  \printbibliography
\end{document}
```

Compilation of this yields error: `Package keyval Error: sortsets undefined. \blx@processoptions`

Thanks anyways for the fast implementation!

**Comment by plk** [comment]
@lcnittl - can you run (assuming linux/OSX/cygwin):

```
fgrep sortsets `kpsewhich biblatex.sty`
```

**Comment by moewew** [comment]
@lcnittl http://tug.org/pipermail/tex-live/2017-November/040777.html and http://tug.org/pipermail/tex-live/2017-November/040779.html together with https://tex.stackexchange.com/a/399942/35864 make me think that your `version 3.8a (rev 45702)` is in fact the downgraded version 3.7.

There were a few problems building Biber binaries, so Biber is not yet on 2.8 on CTAN and TeX live, this caused problems, so the went back to `biblatex` 3.7 for the time being.
