### ISSUE TITLE
Datetime. Sorting down to time level for mutliple works by author.

### ISSUE THREAD

**Issue by JohnLukeBentley** [plk/biblatex#639]
At the moment bibliographic entries can be conventionally sorted with the biblatex option `sorting=nyt`. That is, by name, year, title.

That works well for entries with (the traditional) year level precision. However, for entries with day or time level precision the sorting may be inadequate.

See [Gist-Biblatex-Tester-DateTimeSorting-Mwe.tex](https://gist.github.com/JohnLukeBentley/7ee885777ded29d6ae1933afda111ce8#file-gist-biblatex-tester-datetimesorting-mwe-tex).

Observe that in bibliography ("References") the entries don't sort down to day or time level.

I suggest that for the `sorting` option (see Section 3.1.2 Preamble Options, biblatex.pdf, p44) wherever a "y" symbol appears then that effect a sorting down to time level. That may warrant deprecating, or adding to, the "y" symbol: to point to "sorting down to time level" rather than "sorting down to year level". Perhaps, for example, "s" for "sorting down to the second".

**Comment by plk** [comment]
This would be easy to change - just change the sortingtemplate for `nyt` to include time fields but since this is likely to be a niche requirement, I think we can just leave this up to users to do since there are macros to allow them to do this.

**Comment by moewew** [comment]
See for example https://tex.stackexchange.com/q/46868/35864

I would only sort by `month` and `day` if they can be explicitly seen in the date label. I don't think this needs to be the default and it could seriously impact backwards compatibility.

**Comment by plk** [comment]
There shouldn't be any backwards compatibility issues for changing sorting templates like that as missing fields are just ignored but you are right that if the information used isn't visible anywhere, it would confuse people.

**Comment by moewew** [comment]
Yes, but it could change the sorting for entries with a month.

**Comment by plk** [comment]
It wouldn't matter much if that were added as another sorting step after year, for example, it would just tune the in-year sorting. But I don't think it makes sense to change the default templates as they have always been year only, even down to the (admittedly arbitrary) template names.

**Comment by JohnLukeBentley** [comment]
For the sake of those rocketing in via google see [Gist-Biblatex-Tester-DateTimeSorting-Mwe-Solution.tex](https://gist.github.com/JohnLukeBentley/9978b50c124de8017d385d0f1bcafcf1).

Compared to the original gist:

* `\DeclareSortingTemplate{nst}` was added.
* The `sorting` option in `\PassOptionsToPackage{` was changed to `sorting=nst`.

`\DeclareSortingTemplate{nst}` was created by: 

* Copying the latest version of `\DeclareSortingTemplate{nyt}{` from `biblatex.def`; and 
* Marrying it with the datetime component sorting code form found in the [stackexchange example](https://tex.stackexchange.com/a/46879) @moewew pointed to. That is, by repeating the code form for month and day in that example for hour, minute, and second.

Gist-Biblatex-Tester-DateTimeSorting-Mwe-Solution.tex only tests sorting down to the minute, but if you added entries that were second relevant ... that should also work. 

@plk wrote
> There shouldn't be any backwards compatibility issues for changing sorting templates like that as missing fields are just ignored but you [moewew] are right that if the information used isn't visible anywhere, it would confuse people.

Yeah that points to: if a sorting scheme like 'nyt' was changed to sort down to the second, without changing the 'y' symbol, then a user could see their title sorting as broken (where second level datetimes happened to be ordered in a way that didn't correspond to title ordering). So that would count against redefining the 'y' symbol to sort down to second level.

But what about adding a new set of schemes to native biblatex that use the 's' symbol, for a scheme like 'nst'? ...

> ...  likely to be a niche requirement ...  But I don't think it makes sense to change the default templates  ....

Perhaps also recalling previous conversations it seems like you have in mind that the new datetime precisions finer than a year are to be regarded as something that native biblatex supports but, just as for something like `origdate`, not supported by the standard styles (nor default set of options). The standard styles (and default set of options) being those that try to stick closely to convention. 

On that basis your disinclination to change the default sorting schemes makes sense to me. And if the conventions changed in the future (e.g. the emergence of a genre of writing analyzing twitter, email, or sms debates) then biblatex is solidly placed, in virtue of the current (and new) datetime support, to adapt to those conventions.

So thanks @plk and @moewew to pointing to a solution I can use for my own purposes. I'm persuaded there's no need to change the default sorting schemes. This thread is properly closed.
