### ISSUE TITLE
Inconsistency of \smartof with French language

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#641]
The compilation of `03-localization-keys.tex` points out an inconsistency of `\smartof` with French language: for instance, the `byeditor` key, defined as:
```latex
byeditor         = {{sous la direction \smartof}{sous la dir\adddotspace\smartof}}
```
leads to the following long and short strings:
- "sous la direction d’"
- "sous la dir. de"

whereas it should give the same `\smartof` "de":
- "sous la direction de"
- "sous la dir. de"

**Comment by moewew** [comment]
Do the strings give different results in practice, though?

**Comment by dbitouze** [comment]
>I think this is just an artefact of how `03-localization-keys.tex` works.

Indeed, the MWE below leads to the expected `byeditor` string.

I'm not sure to understand how these `\lsmartoftext` and `\ssmartoftext` actually work. Do you consider make the relevant changes in the `03-localization-keys.tex` file?

```latex
\documentclass[french]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage[a4paper]{geometry}
\usepackage[autostyle]{csquotes}
\usepackage[backend=biber]{biblatex}
\usepackage{babel}

\addbibresource{biblatex-examples.bib}

\begin{document}
\nocite{westfahl:space}
\printbibliography
\end{document}

```

**Comment by dbitouze** [comment]
>Do you consider make the relevant changes in the 03-localization-keys.tex file?

I mean, replace:  
```latex
\newcommand{\lsmartoftext}{A}
\newcommand{\ssmartoftext}{B}
```

by:

```latex
\ifdefstring{\languagename}{french}{%
  \newcommand{\lsmartoftext}{B}%
  \newcommand{\ssmartoftext}{B}%
}{%
  \newcommand{\lsmartoftext}{A}%
  \newcommand{\ssmartoftext}{B}%
}     
```

**Comment by moewew** [comment]
I'd rather not change that in `03-localization-keys.tex`. The status quo allows us to check `smartof` before a vowel and a consonant, it allows us to detect if we introduced breaking changes for smartof. If it annoys you, you can always do `\renewcommand{\lsmartoftext}{B}` in your local copy.

Basically `\lsmartoftext` pretends that the word following a long form of the bibstring starts with the letter `\lsmartoftext`. `\ssmartoftext` does the same for the short forms.

**Comment by dbitouze** [comment]
I see.
