### ISSUE TITLE
`obuild/build.sh` script should provide a `uninstall` "target".

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#643]
https://github.com/plk/biblatex#installation tells us how to install a development version, e.g. from `github` and in our personal `texmf` root, thanks to the `obuild/build.sh` script.

The problem is, this script installs lots of files in different directories and that's a pain to retrieve and remove them when we don't want to use the development version anymore (e.g. when the next release will be available via TeX Live or MiKTeX).

Hence, `obuild/build.sh` script should IMHO provide a `uninstall` "target".

**Comment by plk** [comment]
That sounds reasonable - this is now added to the script in 3.8

**Comment by dbitouze** [comment]
Thanks.

`obuild/build.sh help`:

- "Examples" list mentions `obuild/build.sh uninstall ~/texmf/`
- "Usage" list doesn't mention "uninstall": too bad! :)

**Comment by plk** [comment]
Fixed.
