### ISSUE TITLE
Datetimes. Extradate and multiple works by author in same range.

### ISSUE THREAD

**Issue by JohnLukeBentley** [plk/biblatex#644]
## Problem Summary

The problem is where to position the `extradate` component (the alphabetic `a`, `b`, `c`) that index multiple works by an author in the same date range. That is, should the output look like:

* `(Charles 1998b-04-03/1999-06-01)`;
* `(Charles 1998-04-03/1999b-06-01)` (My recommendation);  
* `(Charles 1998-04-03/1999-06-01b)`; or
* Something else

?

With the more common case, showing (or having at input) years only, the examples look like:

* `(Adams 2001b/2003)`;
* `(Adams 2001/2003b)`; or
* Something else

## Test file

A testing file for this issue: [Gist-Biblatex-Ranges-MutlipleWorksByAuthorInSameRange.tex ](https://gist.github.com/JohnLukeBentley/9f3ad4f462751b95a95f9ddff7813e3e).

## Discussion

Moewew wrote:
> So `/2006`, `2006/`, `2005/2006`, `2006/2007` and `2006/2008` can all coexist without anyone getting any `extradate`. I think this is a sensible approach since it avoids to throw around `extradate`s where they are not needed. That means that the `extradate` 'belongs' to both the start and end year.

That's better than my suggestion to have `extradate` belong to the start year.

And therefore, as you and have @plk have suggested, when there is a need to display an `extradate` (because the author has multiple works with the same year range) and `labeldate=year` then the `extradate` ought go at the end of the two years: `(2006/2007a)`

When `labeldate=ymd`,  and displaying a YYYY-MM-DD (or more precise) formatted datetime, where should the `extradate` go (you ask)?

For the sake of being able to stare at example possibilities you folk already have in mind (and assuming that range years, not range datetimes, determine the `extradate` value) ...

Possibility 1: after the end date:
* `(2003-06-06/2004-06-03a)`
* `(2003-01-01/2004-07-07b)`

Possibility 2: after the end year:
* `(2003-06-06/2004a-06-03)`
* `(2003-01-01/2004b-07-07)`

As you @moewew correctly note,  if `extradate` goes after the end date that wrongly implies that whole dates, rather than merely the years, determine the `extradate` value.

That, then, would seem to leave possibility 2, after the end year. This could be understood as follows:

It would be consistent with designating that the range years determine the `extradate` and so the `extradate` goes after the last year in that range. So possibility 2 looks ~~similar~~ suitably analogous to what happens if you toggled to `labeldate=year` ...

* `(2003/2004a`)
* `(2003/2004b)`

The understanding continues ... an `extradate` after a year, even with a YYYY-MM-DD output date, would be consistent with the look already decided upon in non-date range circumstances. See my "Barker, Anne" image a few posts up with output like ...

    Barker, Anne (2016a-02-24). “China Sends ...

On the separate but related issue of the new `extradatescope` .... If I understand the intentions behind `extradatescope` it is to report on the `\DeclareExtradate` settings, to reveal whether the `extradate` value is determined by a year (the default) or datetime precisions finer than a year. 

That would seem to be helpful down the track (perhaps quite soon) with certain edge cases, but moewew seems correct that it doesn't help with the default case: when  `extradate` is determined by the years of the date range. But I hope my exemplifications above help with the default case.

**Comment by plk** [comment]
I have begun to look at the ISO8601:2016 changes on the "iso8601" branch and uploaded a DEV version of 2.9/3.9 which implement this. The syntax changes are intrusive enough that I don't think that providing backwards compat will be a good idea. I don't think that this is necessary either as they are edge-case features and only recently introduced. Plus the old syntax will not be related to any standard. This means, specifically:

  - The "unspecified" marker "u" is now "X"
  - An approximate+uncertain date is now indicated with "%" rather than "?~"
  - Open dates are now marked with ".." instead of "open" or blank
    start/end dates.
  - Unknown dates are now indicated by blank start/end dates rather than "unknown" or "*"

This is all implemented in the DEV version and the incompatibilities mentioned in the CHANGES.md file.

**Comment by JohnLukeBentley** [comment]
I'm actually part way through a large draft posting on these very issues, having read ISO8601:201x myself. As @moewew previously suggested I'll open a new thread on this. Mostly this would be expressing what you already understand, as you've written above. But I prefer to spill some ink on it in order to get it clear into my thick head ... and to provide us an opportunity to meditate a bit more on the issues.

As a sneak preview and to respond to what you've written above .... At this point of my draft thinking we might want to come to our own conclusions about what ought be in a EDTF spec (on the issues you mention and a few others) and then lobby ISO. 

For example, we might want to hold that, for conceptual reasons, blank is better suited to represent open rather than unknown (and you @plk might have got it conceptually right the first time, when choosing blank for open in Biblatex). As another example, we might want to hold that "%" for uncertain+approximate is crazy talk given that "?\~" is far more human readable (given a prior stipulation of what "?" and "~" mean individually).

However, if we wanted to accept the draft ISO8601:201x as is, then I think you've got the only way out: backward compatibility becomes impossible in virtue of the change in meaning for blank. (And you might want to throw in a biblatex compile WARN whenever blank is used, to flag the change for users).

**Comment by moewew** [comment]
It is a bit unfortunate, but this time I don't harbour strong resentments against breaking backwards compatibility. I suspect that the group of users that are impacted by this change is quite small. And we can at least point to a standard to explain why we require certain input.

The only question is when we choose to make the transition to ISO. It will probably take a bit of time until everything is wrapped up on the ISO side. But the longer we wait, the longer input that will become deprecated with ISO will be accepted by Biber (creating precedence). On the other hand, there is no guarantee that the draft ISO will be ratified as is now.

**Comment by JohnLukeBentley** [comment]
@plk Which CHANGES.md file?

I'm not seeing a relevant description in ...
* https://github.com/plk/biber/blob/dev/Changes; or
* https://github.com/plk/biber/blob/iso8601/Changes; or
* https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES.org

**Comment by plk** [comment]
Sorry, check DEV branch now - was a local change I hadn't pushed.

**Comment by JohnLukeBentley** [comment]
Thanks. Got it https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES.md, under "Release notes for version 3.9".

**Comment by moewew** [comment]
Closing this for now. I think we can accept the current output as not entirely unreasonable. If there is the desired to argue for a different format this should ideally be done in a new issue with specific examples. The current system has the advantage that it is already implemented and not too complex and gives good output in most use cases (day-precision citation dates are thank god still not very popular).

**Comment by JohnLukeBentley** [comment]
After a long hiatus I'm hoping to get back into datetime formats in general, datetime formats in biblatex generally then thence into the weeds of specific edge cases like this one. 

Particularly now that, for good or ill, the current [EDTF](http://www.loc.gov/standards/datetime/edtf.html) has stabilized, and should be reflected in the published (as at 2019-02-25) ISO:8601:2019 (I haven't verified this ... apparently my purchasing of the DIS version isn't good for the published version).

So I haven't reviewed/tested "the current output" for this case just yet. But I'll be betting that you are right that is is not entirely unreasonable.
