### ISSUE TITLE
Make  `.lbx` definitions able to depend from the language's package (`polyglossia` or `babel`) loaded

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#645]
The `french.lbx` file defines `number` as:
```latex
number           = {{num\'ero}{n\textsuperscript{o}}},
```
This definition may be right for `polyglossia` but not for (`frenchb`) `babel` since the latter provides the abbreviation of "number" as its `\no` macro which gives a different (though close) layout from `n\textsuperscript{o}`.

Would it be possible for (some) `.lbx` definitions to depend from the language's package (`polyglossia` or `babel`) loaded at the document level?

**Comment by moewew** [comment]
`.lbx` files can be loaded even if the currently active `babel`/`polyglossia` language is not the same. So it would not be enough to test if `babel` is loaded, we would also have to test if `french` is the active language. It would probably be easier to test if `\no` is defined.

But there is a different, much bigger problem. The bibstring `number` is not a macro. It is usually used as `\DeclareFieldFormat{number}{\bibstring{number}~#1}`, if `\bibstring{number}` now expands to `\no` we don't get the desired result. If we wanted to use `\no` in the bibstrings, we would have to change how bibstrings are used and implemented.

So I think at the moment, the status quo is the best we can do without messing around with the internals of bibstrings. If you really insist on `\no`, just use `\DeclareFieldFormat{number}{\no{#1}}`.

**Comment by dbitouze** [comment]
>The bibstring number is not a macro. It is usually used as` \DeclareFieldFormat{number}{\bibstring{number}~#1}`

I'm puzzled: a grep on `\DeclareFieldFormat{number}` in the  `biblatex` root directory returns a single instance:

```latex
\DeclareFieldFormat{number}{#1}% number in a series
```

(in `tex/latex/biblatex/biblatex.def`).

**Comment by moewew** [comment]
That's why I wrote 'usually'. `\bibstring{number}` is not used by the standard styles at all, but if it were, I assume it would work just like `volume`, for which we have `\DeclareFieldFormat{volume}{\bibstring{volume}~#1}`.

**Comment by dbitouze** [comment]
If the standard styles just use `\DeclareFieldFormat{number}{#1}`, why standard `.lbx` don't define `number` just as:

```latex
number           = {{}{}},
```

**Comment by moewew** [comment]
We are talking two different levels here.

One is the `.lbx`. In the `.lbx` all bibstrings are translated into the relevant language. Not all bibstrings need to be used in the end, but they are there should you want to.

It is then up to the style to use the bibstring (as is the case for `volume`) or not do so (as is the case for `number`). The user could always decide that they want to see 'number' printed out and request that with `\DeclareFieldFormat{number}{\bibstring{number}~#1}`. 

So the short answer is: Because 'number' is not '' in French, but 'numéro'.

**Comment by dbitouze** [comment]
>It is usually used as `\DeclareFieldFormat{number}{\bibstring{number}~#1}`, if `\bibstring{number}` now expands to `\no` we don't get the desired result.

But the following seems to be OK.

```latex
\documentclass[french]{article}
\usepackage{iftex}
\ifPDFTeX
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\else
\usepackage{fontspec}
\usepackage{polyglossia}
\setdefaultlanguage{french}
\fi
\usepackage{csquotes}
\usepackage{biblatex}

\addbibresource{biblatex-examples.bib}

\DefineBibliographyStrings{french}{%
  number = {\ifcsdef{FBmedkern}{\no}{n\textsuperscript{o}\kern+.1em}}
}
\DeclareFieldFormat{number}{\bibstring{number}#1}

\begin{document}
\nocite{padhye}
\printbibliography
\end{document}
```

> It would probably be easier to test if `\no` is defined.

Because relying on `\no` defined or not gives strange result, I relied above on the maybe more `frenchb` specific macro `\FBmedkern`.

**Comment by moewew** [comment]
Yes I thought about something similar as well. But conceptually I don't quite like that. 

Normally, the bibstrings don't bring their own space (`\kern+.1em`) and are not macros (`\no`).
As I said, the 'normal' use of `\bibstring{number}` would be
```
\DeclareFieldFormat{number}{\bibstring{number}~#1}
```
(or similar, crucially, however, with a space).  So if you want `\no`, I think you should go for
```
\DeclareFieldFormat{number}{\no{#1}}
```

**Comment by dbitouze** [comment]
>Normally, the bibstrings don't bring their own space (`\kern+.1em`)

That's necessary in such a case because `\no` already contains the ad hoc horizontal space (which is less than `~)`.

>and are not macros (`\no`)

But they contain macros (`\adddot`, `\lbx@lfromlang`, \smartof, `\adddotspace`, etc.).

>As I said, the 'normal' use of `\bibstring{number}` would be `\DeclareFieldFormat{number}{\bibstring{number}~#1}`

But, as said, `~` is a too big space for French typographic rules in such a case.

>So if you want `\no`, I think you should go for `\DeclareFieldFormat{number}{\no{#1}}`

The problem is, suppose this is for a style supposed to be used with both `babel` and `polyglossia` (the latter not providing -- right -- `\no`).

**Comment by moewew** [comment]
I know that it is necessary in this case, the point I was trying to make was that a bibstring never ends with a space. It is always assumed that the field format or whatever the bibstring is used adds the necessary space after the string.
I see that the space in `\DeclareFieldFormat{number}{\bibstring{number}~#1}` is not what you want, but the point I was trying to make is that bibstrings never bring their space with them, it is supplied by the field format.

bibstrings may indeed contain macros, but they should normally not be macros themselves, i.e. they should not take an argument. (An exception might be the special 'smart' commands. But even there, the macros don't format the argument, they just act according to its value.)

> The problem is, suppose this is for a style supposed to be used with both babel and polyglossia (the latter not providing -- right -- `\no`).

OK, suppose we were to use 
```
\DefineBibliographyStrings{french}{%
  number = {\ifcsdef{FBmedkern}{\no}{n\textsuperscript{o}\kern+.1em}}
}
\DeclareFieldFormat{number}{\bibstring{number}#1}
```
then this solution would work for French, but not for any other language, since all other language's definitions of `number` don't bring their own space and require
`\DeclareFieldFormat{number}{\bibstring{number}~#1}` instead.

**Comment by dbitouze** [comment]
>I see that the space in `\DeclareFieldFormat{number}{\bibstring{number}~#1}` is not what you want, but the point I was trying to make is that bibstrings never bring their space with them, it is supplied by the field format.

I see.

>bibstrings may indeed contain macros, but they should normally not be macros themselves, i.e. they should not take an argument.

It was probably not clear enough, but `\no` doesn't take any argument.

>[...] this solution would work for French, but not for any other language, since all other language's definitions of `number` don't bring their own space and require
`\DeclareFieldFormat{number}{\bibstring{number}~#1}` instead.

Sigh... so no way to solve this problem?

**Comment by moewew** [comment]
Oh, sorry I got confused and thought `\no` took an argument, so my points about macros don't apply, but those about spaces still hold.

> Sigh... so no way to solve this problem?
Well, at the moment I see a few options that would all lead to something less desirable (in my opinion) than the status quo

1. Use something like `number = {\ifcsdef{FBmedkern}{\no}{n\textsuperscript{o}\kern+.1em}}` for French and don't change all the other languages. You'd then use `\DeclareFieldFormat{number}{\bibstring{number}#1}`.
    - This would result in in an inconsistency between French and all other languages. `\DeclareFieldFormat` would have to be language specific, since all other languages don't bring a space in the definition of `number` and need it added in `\DeclareFieldFormat`

2. Add spaces to all `number` bibstrings.
   - You could then use `\DeclareFieldFormat{number}{\bibstring{number}#1}` for all languages. But the behaviour of `number` would be terribly inconsistent with that of all other bibstrings.

Inconsistencies are bad. All bibstrings should work the same way for all languages.

The status quo, you'll recall is that the bibstring `number` is not used anyway. So if you wanted to use the bibstring you would have to change the field format anyway. I'd suggest that in that case you simply do `\DeclareFieldFormat{number}{\no#1}`. If you are concerned about `polyglossia`, simply check if `\no` is defined and provide a replacement if not. You don't have to involved bibstrings.

**Comment by dbitouze** [comment]
> I'd suggest that in that case you simply do `\DeclareFieldFormat{number}{\no#1}`.

The problem is, this would give the same result for both `abbreviate=true` and  `abbreviate=false`.

**Comment by moewew** [comment]
Yes, it is not exactly ideal. It also doesn't deal with different languages (it does not automatically switch to English or Dutch).

If you are writing a bibliography style it should be possible to come up with something like
```
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[french]{babel}
\usepackage{csquotes}
\usepackage[style=authoryear, abbreviate=true]{biblatex}

\usepackage{iflang}

\addbibresource{biblatex-examples.bib}

\makeatletter
\providecommand*{\no}{n\textsuperscript{o}\kern+.1em}
\DeclareFieldFormat{number}{%
  \ifboolexpr{test {\ifcsstring{abx@str}{abx@sstr}} and test {\IfLanguageName{french}}}
    {\no}
    {\bibstring{number}~}%
  #1}
\makeatother

\begin{document}
\nocite{padhye}
\printbibliography
\end{document}
```

**Comment by dbitouze** [comment]
In order to sum up this discussion, something the following could be used:

```latex
\documentclass[french]{article}
\usepackage{iflang}
\usepackage{iftex}
\ifPDFTeX
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\else
\usepackage{fontspec}
\usepackage{polyglossia}
\setdefaultlanguage{french}
\fi
\usepackage{csquotes}
\usepackage{biblatex}

\addbibresource{biblatex-examples.bib}

\DeclareFieldFormat{number}{%
  \ifboolexpr{test {\ifcsstring{abx@str}{abx@sstr}} and test {\IfLanguageName{french}}}%
  {\ifcsdef{FBmedkern}{\no}{n\textsuperscript{o}\kern+.1em}}%
  {\bibstring{number}~}%
  #1%
}

\begin{document}
\nocite{padhye}
\printbibliography
\end{document}
```

**Comment by moewew** [comment]
Yes.

Would you say we can close this issue, or do you have an idea what `biblatex` should do to make things easier?

**Comment by dbitouze** [comment]
>Would you say we can close this issue, or do you have an idea what `biblatex` should do to make things easier?

I'm hoping something easier for style authors: I guess a few of them would be aware of such strange requirements of French typography which should IMHO deferred to the `french.lbx` file which is the only one French typography aware people will think to look at/review.

**Comment by moewew** [comment]
I'm open for suggestions. I can't think of something useful that could be done, but if you have something in mind, fire away.

**Comment by dbitouze** [comment]
>if you have something in mind, fire away.

Unfortunately, nothing in mind (about this, I mean ;) My knowledge of `biblatex` is too low to think about things such as hard coded spaces in `\DeclareFieldFormat{number}{\bibstring{number}~#1}`.

**Comment by moewew** [comment]
To answer the question in the title: There are standard ways to check if a package is loaded. And those could be used here as well (`\@ifpackageloaded`), you just need to keep in mind that `polyglossia` pretends to be `babel`. I believe it is outside the scope for `biblatex` to define commands that test for `polglossia` or `babel`. For what it is worth I don't think the `.lbx` files should depend on the language package, they *should* just contain translations. (I know that they do not only contain translations and get involved in style decisions as well, but that is a different matter.)

Other than that I think we saw that in the current framework there is no simple way to deal with `\no` in `.lbx` files if it requires different spacing than usual. Macros with arguments (though `\no` is not one of them) are also not really supported. I don't see that changing without a complete rewrite of the `.lbx` system.

I'm closing this as "won't fix" for now. If there are any ideas to resolve this issue, we can reopen this issue and discuss them.
