### ISSUE TITLE
Bad revision number in documentation

### ISSUE THREAD

**Issue by polgab** [plk/biblatex#647]
The 3.8 revision is out (2017-11-04). But the title in 'biblatex.pdf' (the documentation) is always "Version 3.7"...

**Comment by dbitouze** [comment]
>The 3.8 revision is out

Not sure: only few files have been updated. But that's true the `CHANGES.org` file contains the release notes for version 3.8.

**Comment by plk** [comment]
This was an annoying mistake - I double checked that and I'm not sure how that happened. It has been corrected and re-submitted to CTAN.

**Comment by LukasCBossert** [comment]
sorry, didn’t looked in the closed issues.
