### ISSUE TITLE
url=false still shows visite on

### ISSUE THREAD

**Issue by skanskan** [plk/biblatex#650]
`\usepackage[maxbibnames=2,style=chicago-authordate,backend=b‌​iber, url=false, doi=false, isbn=false]{biblatex} 
`
Doesn't show the website but it's still showing "visited on 11/07/2017". 
How can I get rid of it?

**Comment by plk** [comment]
There are several ways but it's better to ask this on tex.stackexchange.com - you will get a quick reply with examples.

**Comment by skanskan** [comment]
I thought it was a bug

**Comment by plk** [comment]
Let's discuss it on tex.stackexchange.com first as I'm not sure what to make of this yet.

**Comment by moewew** [comment]
This is a style issue and you use `chicago-authordate`. You will have to report these issues to the maintainer of the `biblatex-chicago` package.

**Comment by skanskan** [comment]
I've created the issue https://tex.stackexchange.com/questions/400384/how-to-disable-biblatex-showing-visited-on-on-the-references
