### ISSUE TITLE
CHANGES.org unreadable on http://www.tug.org/svn/texlive/

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#652]
Probably because of the `.org` extension, `CHANGES.org` is unreadable on http://www.tug.org/svn/texlive/, e.g. when clicking on "text changed" on the line "trunk/Master/texmf-dist/doc/latex/biblatex/CHANGES.org" of the page http://www.tug.org/svn/texlive?view=revision&revision=45764.

By contrast, no problem when clicking on "text changed" on the line "trunk/Master/texmf-dist/source/bibtex/biber/Changes" of the page http://www.tug.org/svn/texlive?view=revision&revision=45763.

So, a `.md` extension (`Org` is able to export in `Markdown`) or no extension would be better for the changes file.

**Comment by plk** [comment]
Ok, I'll change the extension, thanks.
