### ISSUE TITLE
Add bathesis as type for @thesis

### ISSUE THREAD

**Issue by einemarc** [plk/biblatex#660]
I noticed that there are keys for PhD and Master's theses for the entry type `@thesis`, but not one for Bachelor's theses. It would be a nice enhancement if the key _bathesis_ (as an expression equivalent to the term "Bachelor's thesis".) could be added.

Thank you for maintaining and improving biblatex. I couldn't work without it!

**Comment by moewew** [comment]
Thank you for the suggestion.
```
\NewBibliographyString{bathesis}
\DefineBibliographyStrings{englisch}{
  bathesis = {Bachelorarbeit},
}
\DefineBibliographyStrings{german}{
  bathesis = {Bachelor's thesis},
}
```
should be enough. Then `bathesis` in the `type` field will be automatically recognised.

I'm not sure if this warrants inclusion into the `biblatex` core. It can be implemented and extended easily enough by users themselves. If we were to include this, this would have to be translated by the localisation maintainers in order to be useful.

Do you have any indication that this would be a widely applicable feature? I can see that people cite PhD theses (at least in Germany these need to be published), and maybe even master's theses. But I'm not sure if the majority of bachelor theses is even publicly available.

**Comment by einemarc** [comment]
Thank you for the custom code. Very useful.

I'd say that bachelor's theses are still rarely published and therefore also rarely cited. But I would argue that basically the same is true for master's theses. With institutional repositories (e. g. edoc servers, usually of academic institutions) and services such as Zenodo, more and more theses are available/published, and therefore also bachelor's theses. (If this is a good thing and contributes to better science is, of course, another question.)

I am not sure if this feature would be widely applicable. I just thought, if there is an entry type for theses, why not have keys for all the usual theses types (regardless of their assumed quality or availability)?

A case for which I could see regular use is an academic who wants to catalog and make a list of all the theses he/she has supervised. Of course, you could customize (as you suggested) or simply manually put _Bachelor's thesis_ (or the equivalent in another language) in the `type` field of each entry.

**Comment by moewew** [comment]
@plk What is the `biblatex` policy about requests such as this? Similar requests about new sorting schemes, entry types or new fields have been turned down.

**Comment by plk** [comment]
Normally, I wouldn’t but since this is an extension if already existing subtypes - I’m open to it.

**Comment by moewew** [comment]
If you are not on to it already, I can have a look at this later today or tomorrow.

**Comment by plk** [comment]
I’ll leave it to you - we’reback on the usual process o changing the dev branch.

**Comment by moewew** [comment]
The `bathesis` bibstring was added in 23d1470.

For the short English translation I went with 'BA thesis' in analogy to 'MA thesis'. Is that right? I could not find authoritative English language resources about Bachelor's theses.

**Comment by moewew** [comment]
@einemarc You can test the development version from https://sourceforge.net/projects/biblatex/files/development/ That version supports the `bathesis` bibstring (at the moment it is translated only for a few languages: English and German).

The new version of `biblatex` is going to be released fairly soon.

**Comment by einemarc** [comment]
Thank you, for including the function as well as for the update.
