### ISSUE TITLE
ibidpage documentation is ambiguous

### ISSUE THREAD

**Issue by wujastyk** [plk/biblatex#668]
The ibidpage documentation is found in the files at ../texmf-dist/doc/latex/biblatex/examples .  Looking at 53-style-authoryear-icomp-biber.pdf, for example, the doc says

> The scholarly abbreviation ibidem is sometimes taken to mean both ‘same au-
thor + same title’ and ‘same author + same title + same page’ in traditional
citation schemes. By default, this is not the case with this style because it
may lead to ambiguous citations.

It isn't clear what "this is not the case" refers to, since the first sentence gives two equal alternatives.  Which is not the case?

Further, the whole thing is unclear to me.  My understanding is that Ibidem is used when the citation is identical (author, title, page all the same).  Idem is used when the reference is to a different page of the same source (author and title are the same, page different).  This distinction does not emerge from the Biblatex documentation.  However, there are varying interpretations of idem and ibid and recent editions of the standard style guides (Oxford, Chicago) are tending to deprecate the use of either.

**Comment by moewew** [comment]
Duplicate of #667
