### ISSUE TITLE
Again problems with autonum

### ISSUE THREAD

**Issue by christianlupus** [plk/biblatex#669]
I already found issue #383. According to that, biblatex+autonum should work together. Unfortunately this is not correct for my installation. I will give a very minimalistic example:

    \documentclass[a4paper,10pt]{article}
    \usepackage{biblatex}
    \usepackage{autonum}
    \begin{document}
    Test
    \end{document}

As soon as one comments out either of the packages, compiling is working well. For both packages I get a message in the logs:

	(/opt/hd/texlive/2017/texmf-dist/tex/latex/biblatex/biblatex.sty
	...
	(/opt/hd/texlive/2017/texmf-dist/tex/latex/biblatex/biblatex.cfg))
	(/opt/hd/texlive/2017/texmf-dist/tex/latex/autonum/autonum.sty
	(/opt/hd/texlive/2017/texmf-dist/tex/latex/etextools/etextools.sty
	(/opt/hd/texlive/2017/texmf-dist/tex/latex/etex-pkg/etex.sty

	Package etex Warning: Extended allocation already in use.
	(etex)                etex.sty code will not be used.
	(etex)                To force etex package to load, add
	(etex)                \RequirePackage{etex}
	(etex)                at the start of the document.
    
    ...
    
	! Package biblatex Error: Incompatible package 'etextools'.

	See the biblatex package documentation for explanation.
	Type  H <return>  for immediate help.
	...                                              
							
	l.5 \begin{document}

It seems that biblatex tries to load the etextools package at the end of the preamble at `\begin{document}`. Of course then the autonum package has already loaded etextools at this time.

I am using the actual TeXlive 2017 version of all packages (updated a few minutes ago).

**Comment by moewew** [comment]
@plk Do you have an opinion about what we should do here?

`etextools` breaks some of `etoolbox`'s macros and thus our internals. egreg mentions on TeX.SX that `etextools` is buggy and abandoned by its author (https://tex.stackexchange.com/a/238553/35864, https://tex.stackexchange.com/a/285953/35864, https://tex.stackexchange.com/questions/220268/biblatex-and-autonum-dont-work-together/220277#comment517465_220268).

I'm not sure how much of a deal-breaker bailing out if `etextools` is used is for end users. So far we only had this issue and @dbitouze  #587 saying we are a bit rude doing this. Considering how generally people seem to suggest not using `etextools` that is probably not too many complaints to change my mind.

I don't think there is a clean way to detect `etextools` an recover our old definitions. And I certainly don't want `biblatex` to load `etextools` only to make sure that the commands we need can be restored safely.

**Comment by christianlupus** [comment]
I will ask the author to do so. I do not know if he will do so. If he does this might save quite some problems. 
My other suggestion is a flag in biblatex that allows to ignore `etextools`. Then I could restorr the necessary macros.

**Comment by plk** [comment]
I would rather not try to deal with `etextools` - I tried this during the major changes in 2016 and it broke a lot of things.

**Comment by myshevchuk** [comment]
My work (several >100kB documents) relies on the chemschemex package (dozens if not hundreds uses of chemschemex commands), which depends both on etextools and autonum. I would rather switch to bibtex or suspend using the bibliography at all for a while than, well there is no than. Would it be please, please possible to incorporate a kind of a temporary workaround flag option that would allow not to enforce throwing the error during compilation, be the bibliography broken, before a solution is found? I will try to contact the chemschemex author or dig and dive into the package myself.

**Comment by moewew** [comment]
I'm open for an (undocumented perhaps?) option to disable the package incompatibility error.

But in that case users would be solely responsible to restore the macros needed for `biblatex` to work. (At the moment only `\forlistloop`, I believe). I will try to think of a way to help them along, I will only implement that if it does not get too messy for `biblatex`.

Suggestions are of course welcome.

@myshevchuk Thank you very much for your feedback. Even if we don't throw an error immediately, there are some clashes between `etooolbox` and `etextools` that can be sorted out easily.

**Comment by moewew** [comment]
At https://github.com/plk/biblatex/compare/dev...moewew:etextools there is an implementation of a `noerroretextools` option. It would have to be set at loading time and would turn the error when `etextools` is loaded into a warning. The user would be responsible to make sure `\forlistloop` is back to `etoolbox`'s definition when `biblatex` is loaded (and later on as well).

@plk What do you think of such an option? Should it be documented?

**Comment by plk** [comment]
I can imagine it's a useful option for package developers and yes, I think it should be documented so it doesn't become a strange and unknown bit of code ... you could make it clear that it's basically for package developers.

**Comment by christianlupus** [comment]
This seems to me to be useful. I did not (yet) check out the dev version and tried it out however. But it would for sure be a workaround for the problem. Thank you so far.

**Comment by moewew** [comment]
OK, there is a bit of documentation for this option now.

We _could_ restore 
```
\renewcommand*{\forlistloop}[2]{%
  \expandafter\etb@forlistloop\expandafter{#2}{#1}}
```
when `etextools` is detected. Is that something we should do?

**Comment by plk** [comment]
I don't think so - I think this would break a lot of biblatex things. As I remember, this is exactly what broke when I first tried to use etextools.

**Comment by moewew** [comment]
OK, see #670.

No attempts are made to restore macro definitions. This has to be done by the user.

**Comment by myshevchuk** [comment]
Just tried the dev version, everything's working. Thank you so much @moewew! What is the expected misbehavior? I haven't checked vigorously but everything seems to be intact. I load biblatex closer to the beginning of the preamble, just after input and font options, and before autonum and chemschemex. Would this suffice, as I don't experience any problems so far?

**Comment by moewew** [comment]
The exact problems depend on the order in which you load the packages. `autonum` already restores the definition of `\forlistloop`  that `biblatex` needs. So if `autonum` is the first package to load `etextools` things should be OK. If, however, you load `chemschemex` before `autonum`, you have to restore `\forlistloop` yourself.

You can see the problem in a document where you load only `chemschemex` and not `autonum`.

**Comment by josephwright** [comment]
I know I've said this before, but `etextools` is really not usable: any packages requiring it have the same issue ...

**Comment by myshevchuk** [comment]
`Chemschemex` throws an error when `autonum` is not loaded explicitly before it. I spent an hour some time ago to figure this out after having "cleaned" my preamble of unnecessary or redundant packages thinking `autonum` was one of them. I guess it was this issue. @josephwright, not advocating for `etextools`, I lack understanding of such internals, but what is the expected misbehavior? From my standpoint as an end user, I don't see any problems. Everything is compiling, numeration's in place, nothing's missing. Could you please elaborate, why for example `chemschemex` should not be usable? On the other hand, I was amused when I opened the `etextools` manual. It's such a fancy, colorful and vivid document. The author must be a very enlightened person!

**Comment by moewew** [comment]
@myshevchuk 

For me
```
\documentclass{article}
\usepackage[backend=biber, style=numeric, noerroretextools=true]{biblatex}
\addbibresource{biblatex-examples.bib}

\usepackage{chemschemex}
\usepackage{autonum}

\begin{document}
\parencite{sigfridsson}
\printbibliography
\end{document}
```
throws an error.

But
```
\documentclass{article}
\usepackage[backend=biber, style=numeric, noerroretextools=true]{biblatex}
\addbibresource{biblatex-examples.bib}

\usepackage{autonum}
\usepackage{chemschemex}

\begin{document}
\parencite{sigfridsson}
\printbibliography
\end{document}
```
works.

It does not really matter how early `biblatex` is loaded as
```
\documentclass{article}
\usepackage{autonum}
\usepackage{chemschemex}

\usepackage[backend=biber, style=numeric, noerroretextools=true]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\parencite{sigfridsson}
\printbibliography
\end{document}
```
still works, but
```
\documentclass{article}
\usepackage{chemschemex}
\usepackage{autonum}

\usepackage[backend=biber, style=numeric, noerroretextools=true]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\parencite{sigfridsson}
\printbibliography
\end{document}
```
throws an error.

**Comment by myshevchuk** [comment]
@moewew, yes this is what I was experiencing some time ago. I had to figure it out myself then and the answer was not readily googlable. Though stupidly simple, it took me about an hour then. Anyway although a little bit off-topic, I hope it will be of help for future users. Thank you once again!

**Comment by moewew** [comment]
@myshevchuk This only works because the developer of `autonum` has taken some measures to prevent `etextools` to rename `\forlistloop`. Other packages might not and in that case the user has to do that herself. See https://tex.stackexchange.com/q/220268/35864, https://tex.stackexchange.com/q/49556/35864

**Comment by moewew** [comment]
@christianlupus @myshevchuk We are planning to release the next version with `noerroretextools` shortly.

Testing would be appreciated. You can either pull and install from `dev` or get the development version from https://sourceforge.net/projects/biblatex/files/development/.

**Comment by christianlupus** [comment]
@moewew I just cloned the dev branch. Unfortunately I did not yet understand how to install correctly. In the docs something like `obuild/build.sh install <version> <texmf root>` is mentioned. Which version must be set here? I will test as soon as I get it running.

**Comment by christianlupus** [comment]
I used the command with `version`=`3.10`. This worked for me. Then, the MWE with autonum (as well as my tex document I am writing at the moment) worked straight out of the box. I will see if any problems will arise. Up to now, everything works.

**Comment by moewew** [comment]
It might be easier to get the dev version to sourceforge if you don't want to use the install script (I have never used it).

Do you mean to say that your document worked even without setting `noerroretextools=true`?

**Comment by christianlupus** [comment]
No, sorry, the `noerroretextools=true` was needed. Otherwise a message from etextools was thrown that something went wrong (see above).

**Comment by moewew** [comment]
@christianlupus Ah, brilliant. Then everything is working as expected. Thanks for testing!

**Comment by myshevchuk** [comment]
>  myshevchuk commented 6 days ago •
> Just tried the dev version, everything's working. Thank you so much @moewew!

Thanks once again! 

For reference:
Linux: obuild/build.sh install dev ~/texmf
Mac: obuild/build.sh install dev ~/Library/texmf
texlive, specifically biber, must be updated accordingly (to version 2.9 as far as I remember)

**Comment by christianlupus** [comment]
At least, version 2.9 (from texlive 2017) is working as far as I can tell. I close this issue here, might be reopened if the problem persists.
Thank you very much for your quick help, @moewew @plk  !

**Comment by moewew** [comment]
I'm thinking about (effectively) removing the `noerroretextools` option and replace the option by a more primitive mechanism instead. If you want to disable the error and demote it to a warning, you will then have to define the command `blx@noerroretextools` before you load `biblatex`, this is probably easiest done for end users with
```
\usepackage{etoolbox}
\cslet{blx@noerroretextools}\empty
\usepackage[backend=biber,style=authoryear]{biblatex}
```
or
```
\makeatletter
\let\blx@noerroretextools\@empty
\makeatother
\usepackage[backend=biber,style=authoryear]{biblatex}
```
I appreciate that this is more complicate than a simple option, but this makes things slightly easier from the implementation side.

Currently, `biblatex` checks for incompatible packages in `\AtEndPreamble`. For some incompatibilities it is too late at that point. Try loading `natbib` before `biblatex`: You'll get an error about `\bibhang` and a few more. If you load `etextools` without restoring `\forcsvloop` you'll also get cryptic errors instead of a proper error that tells you that `etextools` is incompatible.
I would like to also test for incompatible packages at the beginning of the package to catch some of these problems earlier with a proper and helpful error message.
Naturally, not everything is set up at the beginning of the package, in particular the option handling code follows much later. So we need to be able to demote the `etextools` error without resorting to options.

The new incompatibility checking I'm thinking about will still not be able to catch things like
```
\usepackage{biblatex}
\usepackage{natbib}
```
but at least it catches
```
\usepackage{natbib}
\usepackage{biblatex}
```

Thoughts?

**Comment by josephwright** [comment]
Sounds sensible: I guess you'll go for running the checks at the start of loading `biblatex` and again `\AtBeginDocument`? (That's what I do for similar cases.)

**Comment by josephwright** [comment]
@moewew I should probably do something at the `etoolbox` end: I can do some stuff to look for `etextools`, but perhaps also a 'code level' interface that `biblatex` can rely on (given a sufficiently-new `etoolbox`)?

**Comment by moewew** [comment]
@josephwright Thanks for the comment. Indeed that is more or less the case (`biblatex` uses `\AtEndPreamble` instead of `\AtBeginDocument`, but I guess that does not matter too much), see https://github.com/moewew/biblatex/commit/2dc6071ad23a1849210ac1c76748e45f17f6aa16.

**Comment by moewew** [comment]
@josephwright What did you have in mind? I assume it would be quite hard for `etoolbox` to detect `etextools` in all situations and take appropriate action. What do you mean by 'code level' interface, a new 'namespace' for certain commands so that `biblatex` can be reasonably certain that they have not been meddled with?

**Comment by josephwright** [comment]
@moewew Yes, something like a simple `\let\etoolbox@forlistloop\forlistloop` (better name welcome), then it could be restored by `biblatex` or used directly (and where of course you can check for it and just copy `\forlistloop` if necessary).

**Comment by moewew** [comment]
Mhhh, I'm not overly keen on introducing an additional layer of internal names here, but I assume it would make things safer. We would have to think about backwards compatibility with old `etoolbox`, though. Experience has told me we can't expect everyone to have `etoolbox` or `babel` up to date.

**Comment by josephwright** [comment]
@moewew  The alternative is to check for the correct form of the command: this is a 'pure `biblatex`' solution:
```latex
\RequirePackage{etoolbox}
\ifdefprotected\forlistloop
  {\def\blx@forlistloop#1#2{\expandafter\etb@forlistloop\expandafter {#2}{#1}}}
  {\let\blx@forlistloop\forlistloop}
```
Of course, this relies on internals of `etoolbox`, but I'm not about to change them. One could combine both approaches:
```latex
\ifdef\etoolbox@forlistloop
  {\let\blx@forlistloop\forlistloop}
  {\ifdefprotected\forlistloop
    {\def\blx@forlistloop#1#2{\expandafter\etb@forlistloop\expandafter {#2}{#1}}}
    {\let\blx@forlistloop\forlistloop}}
```
so you only use a 'local' definition as a final fall-back,

**Comment by josephwright** [comment]
@moewew Of course, I'm assuming you then use `\blx@forlistloop` inside `biblatex` ...

**Comment by moewew** [comment]
Once we get started doing this for one command, I'd feel the urge to do that for all `etoolbox` commands. But then the code would get uglier, ... so that urge would have to be repressed.

At least saving `\forlistloop` from `etextools` like this is something we should seriously consider.

**Comment by moewew** [comment]
https://github.com/plk/biblatex/pull/751 was merged today. That means that the option `noerroretextools` will not work as before from the next version onwards. Users who must at all costs load `etextools` now need to define the macro `\blx@noerroretextools` before loading `biblatex`, for example

```
\usepackage{etoolbox}
\cslet{blx@noerroretextools}\empty
\usepackage{biblatex}
```

The user is responsible to make sure that `\forlistloop` and all other `etoolbox` macros used by `biblatex` have their original `etoolbox` definition and not their incompatible `etextools` definition.

Sorry for removing a previously defined and at least semi-documented option. But the new code makes testing against compatibility problems easier and I hope that `etextools` is not used that extensively by developers that the impact will not be disastrous.

**Comment by moewew** [comment]
`biblatex` 3.12 has been released and is available in MikTeX and TeX live 2018.

The option `noerroretextools` has been removed. The example in the first post can now be run as follows
```
\documentclass[a4paper,10pt]{article}
\usepackage{etoolbox}
\cslet{blx@noerroretextools}\empty
\usepackage{biblatex}
\usepackage{autonum}
\begin{document}
Test
\end{document}
```
