### ISSUE TITLE
Newer versions of biblatex fail to switch font encodings in a multilingual @entryset

### ISSUE THREAD

**Issue by alex-shpilkin** [plk/biblatex#675]
After the recent CTAN update, the following no longer works ([test case](https://github.com/plk/biblatex/files/1594154/encofail.txt)):

- Import inputenc with `utf8`, fontenc with `T2A,T1` and babel with `russian,english`, setting the main document language to T1-encoded English with T2A-encoded Russian possible as an `otherlanguage`;
- Import biblatex with `backend=verbose-trad1,autolang=other,backend=biber`;
- Define two entries in the bibliography, one with `langid=english` and the other with `langid=russian` and Cyrillic characters, and an entryset containing both of them (in whichever order);
- Invoke `\parencite` inside the document to (try to) get an inline citation referring to the entryset.

The error message from pdflatex indicates that the font encoding was not switched from T1 to T2A. The encoding is switched correctly if an individual entry and not the entryset is cited.

**Comment by moewew** [comment]
Thank you very much for reporting this bug.

For the benefit of the avid reader, here is the MWE again
```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[T2A,T1]{fontenc}
\usepackage[russian,english]{babel}
\usepackage{csquotes}
\usepackage[style=verbose-trad1,autolang=other,backend=biber]{biblatex}
\usepackage{filecontents}

\bibliography{\jobname}
\begin{filecontents}{\jobname.bib}
@book{berezin1987introduction,
  title         = {Introduction to superanalysis},
  author        = {Berezin, F A},
  editor        = {Kirillov, Alexandre},
  translator    = {Niederle, Jiří and Kotecký, Roman},
  year          = {1987},
  origlanguage  = {russian},
  langid        = {english},
  publisher     = {Springer Netherlands},
  doi           = {10.1007/978-94-017-1963-6},
  isbn          = {978-90-277-1668-2},
}
@book{berezin2013vvedenie,
  title         = {Введение в~суперанализ},
  author        = {Березин, Феликс Александрович},
  note          = {Под~ред. Д.~А.~Лейтеса и А.\,А.~Кириллова с~дополнениями
                   Д.\,А.~Лейтеса, В.\,Н.~Шандера и~И.\,М.~Щепочкиной},
  edition       = {2},
  year          = {2013},
  langid        = {russian},
  publisher     = {МЦНМО},
  isbn          = {978-5-4439-0229-6},
}
@set{berezin-vvedenie,
  entryset      = {berezin2013vvedenie,berezin1987introduction}
}
\end{filecontents}

\begin{document}
Here's some text in English with a~citation in Russian \parencite{berezin-vvedenie}.

\printbibliography
\end{document}
```

Just out of interest are you sure this used to work in older versions? I had a look and the relevant code has not been changed much for years.

I have submitted #676 which should fix this, but I could not test it thoroughly, so it is only a pull request.

**Comment by alex-shpilkin** [comment]
@moewew Well, I can say the MWE and my original longer document compile successfully with biblatex 3.7 dated 2016/12/05 and biber 2.7, might of course be a fortunate coincidence. (Note that one of the reasons for the long-winded bibliography entries in the MWE was to require that the font encoding be switched _back_ to T1 due to things like ý in the second entry. The `\printbibliography` you added is not required.)

Re #676, I confirm that I can no longer reproduce this problem with the changes. By the way, did you really mean to the sequence in `\blx@entryset` (line 4279–4298) to be `begunit`, `beglangbib`, `endunit`, `endlangbib` (_i.e._ violating nesting?).

**Comment by moewew** [comment]
Aha. There were minute changes in 3.8 that I had overlooked, because I had assumed you had updated from 3.8 to 3.9.

Thanks for pointing out the nesting error. It has been fixed.
