### ISSUE TITLE
biblatex warning if fancyhdr and \@mkright is used

### ISSUE THREAD

**Issue by u-fischer** [plk/biblatex#685]
I get a warning with this document:

```
\documentclass[]{article}
\usepackage{fancyhdr}
\pagestyle{fancy}
\usepackage{biblatex}

\begin{document}
\makeatletter \@mkright{abc}
\end{document}
```

~~~
Package biblatex Warning: package incompatibility detected!
(biblatex)                \@mkbothit neither \markbothnor any
(biblatex)                kind of two arguments gobbling,
(biblatex)                e.g., \@gobbletwo.
(biblatex)                So I don't known, what to do
(biblatex)                with \@mkright.
(biblatex)                Nevertheless, \markright will be
(biblatex)                used on input line 17.
~~~

`fancyhdr` defines ` \def\@mkboth{\protect\markboth}` so it looks as if the test in biblatex.def `\ifx\@mkboth\markboth`  is wrong. 

The issue is related to issue  https://github.com/plk/biblatex/issues/627 where the warning seems to have been introduced. 

In my real document I got the warning, as the document uses fancyhdr together with a KOMA class. I know that this is discouraged but I would prefer not to have to rewrite everything. 

```
\documentclass[listof=leveldown]{scrreprt}
\usepackage{fancyhdr}
\pagestyle{fancy}
\usepackage{biblatex}

\begin{document}
\listoffigures
\end{document}
```

**Comment by moewew** [comment]
Thank you for reporting this issue.

You know much more about these things than I do. So I'd be glad for any hints towards a solution. Would you think it is a good idea to additionally test if `\@mkboth` is `\protect\markright`? Or would that just shift the issue?

I'm beginning to think it was not that good an idea to provide a macro that `biblatex` should have no involvement in, such as `\@mkright`.

**Comment by u-fischer** [comment]
Imho @komascript  will know more about this stuff. But my two cents: I would define some biblatex specific command like \bib@markright and use this, and it can then be defined as \@mkright if \@mkright is defined or something else if not.

**Comment by moewew** [comment]
Since `\@mkright` is only used for KOMA headings anyway, we might as well not define it at all and copy the KOMA definitions directly. Initially I had hoped we could keep the heading definitions, short, readable and with user-level commands so that they can easily be modified. But we are probably past that already.

**Comment by moewew** [comment]
Have a look at the `rmmkright` branch: https://github.com/moewew/biblatex/tree/rmmkright

I have removed our definition of `\@mkdouble` and `\@mkright`, and went back to a slightly more convoluted definition of the headings lifted from 3.24 of KOMA script.

**Comment by u-fischer** [comment]
> Initially I had hoped we could keep the heading definitions short, readable and with user-level commands so that they can easily be modified.

I think you could move some of the burden to the class if you moved the class specific code out of the headings:

~~~~
\defbibheading{bibliography}[\biblatex@heading@bibname]{% e.g. \refname
    \biblatex@heading@bibliography@mainheading{#1}% e.g. \section
    \biblatex@heading@bibliography@mainmark{#1}% e.g. \@mkright
    \biblatex@heading@bibliography@maintoc{#1}% e.g. \addcontentsline
    }

\defbibheading{subbibintoc}[\biblatex@heading@bibname]{%
    \biblatex@heading@subbibintoc@mainheading{#1}% 
    \biblatex@heading@subbibintoc@mainmark{#1}%
    \biblatex@heading@subbibintoc@maintoc{#1}%
}

and so on
~~~~

You could then document this commands for class writers and tell them they that if they provide definitions biblatex will not overwrite them. You will naturally nevertheless have to add all the existing definitions for the koma classes and memoir, but imho in a year or so they can be removed. 

Imho it would be also useful if \printbibliography wouldn't hardcode the default heading with `\def\blx@theheading{bibliography}`, but would do something like `\def\blx@theheading{\biblatex@heading@default}`. Then it would be easier for a class to switch from `bibliography` to e.g. `bibintoc`.

**Comment by moewew** [comment]
Thanks to Markus Kohm we already have something like this going for KOMA script. We essentially hand full control over the heading back to KOMA. It might be nice to have this as a general interface for class developers.

Your point about letting the class choose `\blx@theheading` is interesting as well. That would in a way be a different approach. Currently we put all class customisations into the default `bibliography` heading; but of course we could also ask developers to choose the correct heading for the job.

**Comment by moewew** [comment]
I have submitted pull request #686 to fix the issue at hand now. But I'm very open to discuss a new scheme to offer an interface for better compatibility with document classes.

**Comment by moewew** [comment]
#686 Fixes the immediate issue here. Closing this for now. If anything comes up again, please comment here and we can reopen this.

If anyone would like to discuss ideas for an interface for class files to control the heading, please head over to #693.
