### ISSUE TITLE
About the separator between related entries

### ISSUE THREAD

**Issue by hushidong** [plk/biblatex#694]
from the doc ,we know that the generic separator between the data of multiple related entries is `\relateddelim` (bblatex.pdf page 114,234). 

but in the example below, the separator is added after the first related entry, but not after the main entry:

    \documentclass[twoside]{article}
    \usepackage{xcolor}
    \usepackage{hyperref}
    \usepackage[backend=biber,style=authoryear]{biblatex}
    \usepackage{filecontents}
    \begin{filecontents}{\jobname.bib}
    @Book{orig--,
      Title                    = {Test},
      Address                  = {Address},
      Author                   = {A and B and C},
      Publisher                = {Publisher},
      Year                     = {2013},
      related                  = {Yi2013--,Yi2014--}
    }
    @Book{Yi2013--,
      Title                    = {Supersonic and hypersonic nozzle design},
      Address                  = {BeiJing},
      Author                   = {Yi, S H and Zhao, Y X and He, L and Zhang, M L},
      Publisher                = {National Defense Industry Press},
      Year                     = {2013}
    }
    @Book{Yi2014--,
      Title                    = {Supersonic and hypersonic nozzle design},
      Address                  = {BeiJing},
      Author                   = {Yi, S H and Zhao, Y X and He, L and Zhang, M L},
      Publisher                = {National Defense Industry Press},
      Year                     = {2014}
    }
    \end{filecontents}
    \addbibresource{\jobname.bib}

    \begin{document}
    related entries\cite{orig--}

    \printbibliography
    \end{document}

 
![default](https://user-images.githubusercontent.com/20421795/35388923-b252180a-0210-11e8-88bd-4a5803f18f5c.png)

here the separator between the first and second related entry is `\relateddelim` but none between the main entry and the first entry. but the example in biblatex.pdf has a `\relateddelim` ,like this:
![default](https://user-images.githubusercontent.com/20421795/35389063-292d54e4-0211-11e8-85b2-38fdfcd6c188.png)

so i check the related macro in standard.bbx, :

	\newbibmacro*{related}{%
	  \ifboolexpr{ test {\iffieldundef{related}} or test {\ifrelatedloop} }
		{}
		{\usebibmacro{begrelated}%
		 \def\bbx@tempa{}%
		 \setcounter{bbx:relatedtotal}{0}%
		 \def\do##1{%
		   \entrydata{##1}{%
			 \ifrelatedloop
			   {}
			   {\stepcounter{bbx:relatedtotal}%
				\gappto{\bbx@tempa}{##1,}}}}%
		 \docsvfield{related}%
		 \restorefield{related}{\bbx@tempa}%
		 \ifnumgreater{\value{bbx:relatedtotal}}{0}
		   {\listcsxadd{bbx:relatedloop}{\strfield{entrykey}}%
			\iffieldundef{clonesourcekey}
			  {}
			  {\listcsxadd{bbx:relatedloop}{\strfield{clonesourcekey}}}%
			\setcounter{bbx:relatedcount}{0}%
			\def\do{%
			  \stepcounter{bbx:relatedcount}%
			  \ifnumgreater{\value{bbx:relatedcount}}{1}
				{\ifcsundef{relateddelim\strfield{relatedtype}}
				  {\printtext{\relateddelim}}
				  {\printtext{\csuse{relateddelim\strfield{relatedtype}}}}}
				{}}%
			\ifbibmacroundef{related:\strfield{relatedtype}}
			  {\appto{\do}{\usebibmacro{related:default}}}
			  {\appto{\do}{\usebibmacro*{related:\strfield{relatedtype}}}}%
			\iffieldformatundef{related:\strfield{relatedtype}}
			  {\def\bbx@tempa{related}}
			  {\def\bbx@tempa{related:\strfield{relatedtype}}}%
			\iffieldformatundef{relatedstring:\strfield{relatedtype}}
			  {\def\bbx@tempb{relatedstring:default}}
			  {\def\bbx@tempb{relatedstring:\strfield{relatedtype}}}%
			\printtext[\bbx@tempa]{%
			  \usebibmacro{begrelatedloop}%
			  \iffieldundef{relatedstring}
				{\ifboolexpr{
				   test {\ifnumgreater{\value{bbx:relatedtotal}}{1}}
				   and
				   test {\ifbibxstring{\thefield{relatedtype}s}}
				 }
				   {\printtext[\bbx@tempb]{%
					  \bibstring[\mkrelatedstring]{\thefield{relatedtype}s}}}
				   {\iffieldbibstring{relatedtype}
					  {\printtext[\bbx@tempb]{%
						 \bibstring[\mkrelatedstring]{\thefield{relatedtype}}}}
					  {}}}
				{\iffieldbibstring{relatedstring}
				   {\printtext[\bbx@tempb]{%
					  \bibstring[\mkrelatedstring]{\thefield{relatedstring}}}}
				   {\printfield[\bbx@tempb]{relatedstring}}}%
			  \docsvfield{related}%
			  \usebibmacro{endrelatedloop}}}%
		   {}%
		 \usebibmacro{endrelated}}}

if i change `\ifnumgreater{\value{bbx:relatedcount}}{1}` to `\ifnumgreater{\value{bbx:relatedcount}}{0}` , then an separator added. so I ask if this code `\ifnumgreater{\value{bbx:relatedcount}}{1}` is a mistake in writting or a special treatment for some intents.

**Comment by moewew** [comment]
Mhhh, I suppose that is intended. The documentation says

> The separator between the data of multiple related entries

So it seems natural that the separator is not printed before the first `related` entry.

**Comment by hushidong** [comment]
but see the example in biblatex.pdf page 114, before the first related entry there is a linebreak.

**Comment by moewew** [comment]
Yup, but that is specifically created with
```
\DeclareFieldFormat{related:multivolume}{\par\nobreak#1}
```

**Comment by hushidong** [comment]
ok ,I  get it ,thank you very much!

**Comment by moewew** [comment]
Mhhh. I think we should probably have a customisable punctuation command to be printed just before the `related` entries. It shouldn't be the same as `\relateddelim` for backwards compatibility reasons as well as for conceptual reasons. But I think it would make sense to have one.

Suggestions for a natural name are welcome.

**Comment by hushidong** [comment]
a `\prerelateddelim` ?

**Comment by moewew** [comment]
There is https://github.com/plk/biblatex/pull/704 now. I went with `begrelateddelim`, but I will happily choose another name if you think it is more appropriate.
