### ISSUE TITLE
arXiv links use http (not https)

### ISSUE THREAD

**Issue by Socob** [plk/biblatex#699]
It would be nice if the arXiv links generated by biblatex could use the https protocol (instead of http). As far as I can tell, arxiv.org redirects any http traffic to https anyway. The relevant line in the code seems to be this one:

https://github.com/plk/biblatex/blob/5936adba211ab1e547ac5fe59e0836ca7ff6b316/tex/latex/biblatex/biblatex.def#L469

**Comment by moewew** [comment]
Thank you for the request.

I have pushed a commit to that effect.

**Comment by moewew** [comment]
Done in `biblatex` 3.11.
