### ISSUE TITLE
Weird reference numbering with multiple bibliographies

### ISSUE THREAD

**Issue by kaefer3000** [plk/biblatex#701]
Hi,

I get awkwardly numbered papers by using two bibliographies that are sorted differently, MWE:
```latex
\documentclass{article}
\usepackage{filecontents}
\begin{filecontents}{ref.bib}
@article{p1,
  author = {A. Uthor},
  title = {Paper 1},
  year = {2018}}
@article{p2,
  author = {C. Uthor},
  title = {Paper 2},
  year = {2018}}
@misc{p3,
  author = {A. Uthor},
  title = {Paper 3},
  year = {2017}}
@misc{p4,
  author = {A. Uthor},
  title = {Paper 4},
  year = {2016}}
\end{filecontents}

\usepackage[style=numeric, sorting=none, backend=biber]{biblatex}
\addbibresource{ref.bib}

\begin{document}

Citing paper 1 and 4~\cite{p1,p4}, paper 2 and 3~\cite{p2,p3}, and paper 2 and 4~\cite{p4,p2}.

\section*{Paperlist 1, non-misc papers, not ordered}

\printbibliography[heading=none,nottype=misc]

\section*{Paperlist 2, misc papers, nty-ordered}

\begin{refcontext}[sorting=nty]
\printbibliography[heading=none,type=misc]
\end{refcontext}

\end{document}
```
Here, reference number 3 is assigned twice. You can play around with citation orderings and author names such that sometimes you get overlapping numbering schemes, sometimes not. I do not know what the desired behaviour should be: All numbers only assigned once, or both lists starting with 1, I would be fine with any, even with the latter, because I use footnotes to cite papers of the un-sorted category.

Cheers!

**Comment by plk** [comment]
In such cases, you probably want to use the option `defernumbers=true`. If you add this, your example looks ok.

**Comment by kaefer3000** [comment]
Thanks!

This does not solve my original problem, though. I have two classes of references, one is cited as footnotes, the others in a references section. If I use the derefnumbers option, then all footnotes have number 0 because they never appeared in any bibliography. The references in the references section are numbered consequtively though.

**Comment by plk** [comment]
That's a good question to ask on tex.stackexchange.com ...
