### ISSUE TITLE
Strange interplay between packages

### ISSUE THREAD

**Issue by projekter** [plk/biblatex#703]
I encountered a very intricate chain of package dependencies that lead to an invalid `bcf` file. MWE:
```LaTeX
\documentclass{article}

\usepackage{verbatim}
\immediate\newwrite\testwrite
\usepackage{fontspec}
\usepackage{biblatex}
\usepackage{tikz}
\usepackage{scrlayer-notecolumn}

\begin{document}
   \cite{bib:test}
\end{document}
```

This is as much as I could reduce the issue. If you comment out any of the lines in the preamble, everything works. However, with all these packages and the `\newwrite`, both LuaLaTeX (`1.07.0`) and XeLaTeX (`3.14159265-2.6-0.99998`), both on `MiKTeX 2.9.6550 NEXT 64-bit` create a `bcf` file where the last two lines read
```XML
  <bcf:section number="0">
    <bcf:citekey order="1">bib:test</bcf:citekey>
```
The section and also the root node are never closed. And interestingly, the lines that are missing in the file are printed to `stdout` instead.
Probably this is not an issue of `biblatex`, but of any of the other packages; but since I don't know which, I start by reporting it here.

**Comment by moewew** [comment]
Thank you very much for reporting this strange issue.

I don't know if I can get to the bottom of this in the next days, but I will try.

**Comment by moewew** [comment]
Just in case I forget about this, or get stuck.

This still reproduces the problem
```
\documentclass{article}
\makeatletter
\newread\verbatim@in@stream
\newwrite\testwrite
\usepackage{fontspec}
\usepackage{biblatex}
\usepackage{tikz}
\RequirePackage{scrlayer}

\scrlayerInitInterface
  \newwrite\tf@slnc
  \AtBeginDocument{%
    \if@filesw
      \immediate\write\@auxout{%
        \noexpand\csname slnc@initwrite\noexpand\endcsname
      }%
    \fi
  }%
\scrlayerAddToInterface\slnc@initwrite
{%
  \newcommand*{\slnc@initwrite}{%
    \immediate\closeout\slnc@file
    \immediate\openout\tf@slnc\jobname.slnc
  }%
}

  \newread\slnc@file
  \immediate\openin\slnc@file \jobname.slnc

\begin{document}
   \cite{bib:test}
\end{document}
```

**Comment by moewew** [comment]
Mhh, we don't really need `fontspec`, one test is enough
```
\documentclass{article}
\makeatletter
\newread\verbatim@in@stream
\newwrite\testwrite

\RequirePackage{xparse}
\ExplSyntaxOn
\file_if_exist:nTF {tuenc.def}{}{}
\ExplSyntaxOff
\usepackage{biblatex}
\usepackage{tikz}
\RequirePackage{scrlayer}

\scrlayerInitInterface
  \newwrite\tf@slnc
  \AtBeginDocument{%
    \if@filesw
      \immediate\write\@auxout{%
        \noexpand\csname slnc@initwrite\noexpand\endcsname
      }%
    \fi
  }%
\scrlayerAddToInterface\slnc@initwrite
{%
  \newcommand*{\slnc@initwrite}{%
    \immediate\closeout\slnc@file
    \immediate\openout\tf@slnc\jobname.slnc
  }%
}

  \newread\slnc@file
  \immediate\openin\slnc@file \jobname.slnc

\begin{document}
   \cite{bib:test}
\end{document}
```

**Comment by moewew** [comment]
Here is a truly minimal example
```
\documentclass{article}
\newread\reada
\newread\readb
\newread\readc
\newwrite\writea
\usepackage{biblatex}
\usepackage{scrlayer-notecolumn}
\begin{document}
   \cite{bib:test}
\end{document}
```

I suspect the following bits of `scrlayer-notecolumn`
```
\documentclass{article}
\makeatletter
\newread\reada
\newread\readb
\newread\readc
\newwrite\writea

\usepackage{biblatex}
%\show\blx@bcfout

\RequirePackage{scrlayer}

\scrlayerInitInterface
  \newwrite\tf@slnc
  \AtBeginDocument{%
    \if@filesw
      \immediate\write\@auxout{%
        \noexpand\csname slnc@initwrite\noexpand\endcsname
      }%
    \fi
  }%
\scrlayerAddToInterface\slnc@initwrite
{%
  \newcommand*{\slnc@initwrite}{%
    \immediate\closeout\slnc@file
    \immediate\openout\tf@slnc\jobname.slnc
  }%
}

  \newread\slnc@file
  %\show\slnc@file

\begin{document}
   \cite{bib:test}
\end{document}
```

**Comment by moewew** [comment]
I'm pretty sure this is an issue with `scrlayer-notecolumn`, so I have opened a thread at the German KOMA-Script forum https://komascript.de/node/2162.

**Comment by komascript** [comment]
@moewew Indeed, this is a bug in `scrlayer-notecolumn`. Until the next KOMA-Script release you can use the following workaround after loading `scrlayer-notecolumn`:

    \usepackage{xpatch}
    \makeatletter
    \xpatchcmd{\slnc@openwrite}{\closeout}{\closein}{}{}
    \makeatother

See https://komascript.de/comment/5720#comment-5720.

**Comment by projekter** [comment]
Thanks for this quick resolution.
