### ISSUE TITLE
Incompatibility with enotez

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#707]
```latex
\documentclass{scrartcl}
\usepackage{enotez}

\let\footnote\endnote

\usepackage[style=authoryear-icomp,notetype=endonly,autocite=footnote,backend=biber]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\footcite{sigfridsson}
\printendnotes
\end{document}
```
will always call for a Biber re-run.

I think I chased down the problem to the following cause:
The lists `\blx@cites` and `\blx@lastcites` are normally filled with the detokenized citekeys (all catcode 12). The detokenization step for the citekeys is hidden deep in internals and . But due to the fact that with `enotez` the citation is written to the `.aux` file in slightly expanded form, the macros that normally do the detokenization have already processed the citation and so the citekey is not detokenized any more when it is read from the `.aux`.

This causes a discrepancy between `\blx@cites` (citations from endnotes not detokenized) and `\blx@lastcites` (all detokenized)  triggering the re-run warnings.

**Comment by moewew** [comment]
**First idea**
Replace 
https://github.com/plk/biblatex/blob/a6a67349b842b7084d5dcabd0ad79db74beb2c76/tex/latex/biblatex/biblatex.sty#L9194-L9197
with
```
\def\blx@citation#1#2{%
  \ifbool{citerequest}
    {\expandafter\expandafter\expandafter\blx@citation@entry
       \expandafter{\detokenize{#1}}{#2}}
    {}}
```
to make sure that the citation key is *always* detokenized.

@josephwright  Any comments?

**Comment by moewew** [comment]
**Another idea**

Replace

https://github.com/plk/biblatex/blob/a6a67349b842b7084d5dcabd0ad79db74beb2c76/tex/latex/biblatex/biblatex.sty#L9281

with
```
\protected\def\blx@citeloop#1{%
  \expandafter\blx@citeloop@i\expandafter{\detokenize{#1}}}
\protected\def\blx@citeloop@i#1{%
```

**Comment by moewew** [comment]
@plk If there is nothing more on the Biber to do list I would like to release `biblatex` 3.11/Biber 2.11 as soon as possible.

Maybe you can start the Biber build process and we pack up `biblatex` 3.11 as soon as the Biber 2.11 binaries are all set and done. Then we can push both to CTAN at the same time.

**Comment by plk** [comment]
Ok, this is started. SF has some file upload issues currently and so I'll likely finish it tomorrow and ask the builders of the other platforms to upload tomorrow. It usually takes a few days after that for them to complete.

**Comment by moewew** [comment]
Great. Thank you very much.

**Comment by moewew** [comment]
Ah. Just in case you notice the test failing, that should be due to the addition of the Latvian bibstrings to `03-localization-keys.tex`. All other files should be fine.

**Comment by moewew** [comment]
Sent off another announcement to comp.text.tex. Have you already packed up `biblatex` 3.11 or is there still time to tweak the readme a bit? (If yes, I will push the changes to master directly and then merge to dev.)

**Comment by plk** [comment]
Can't do anything until SF is back up. I have merged everything to master for biblatex and biber so change master and merge to dev until ready ...

**Comment by moewew** [comment]
Good.

**Comment by plk** [comment]
@moewew - for information, SF has extensive issue due to their recent upgrades and we can't upload anything currently. They will let me know when it's fixed but from experience this could be a week or more.
