### ISSUE TITLE
Inappropriate strings with dates in French

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#711]
The MCE in the end of this issue gives wrong results in French:

1. **"visité le 18-30 septembre 2016"**: should be "visité du 18 au 30 septembre 2016" (while the first date range "18-30 septembre", displayed alone -- without "visité le" -- is acceptable). Analog for "visité le 18 septembre-29 octobre 2017" and "visité le 18 septembre 2016-29 novembre 2017,
1. **"visité le septembre 2016"**: should be "visité en septembre 2016".
1. **"visité le 2016"**: should be "visité en 2016".

In other words, French language would require:

- different `urlseen` strings depending on the context,
- different `\bibrangedash` macro depending whether the date (range) is displayed alone or preceded by some string (here the `urlseen` one).

AFAICS, that's not easily feasible in the current state of `biblatex`...

```latex
\documentclass{article}
\usepackage[french]{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, mergedate=false, urldate=comp, dateabbrev=false]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{elk1,
  author         = {Anne Elk},
  title          = {On the Theory of Brontosauruses},
  date           = {1972-09-18},
  url            = {https://example.com},
  urldate        = {2015-09-18},
}
@book{elk2,
  author         = {Anne Elk},
  title          = {On the Theory of Brontosauruses},
  date           = {1973-09-18/1973-09-30},
  url            = {https://example.com},
  urldate        = {2016-09-18/2016-09-30},
}
@book{elk3,
  author         = {Anne Elk},
  title          = {On the Theory of Brontosauruses},
  date           = {1974-09-18/1974-10-29},
  url            = {https://example.com},
  urldate        = {2017-09-18/2017-10-29},
}
@book{elk4,
  author         = {Anne Elk},
  title          = {On the Theory of Brontosauruses},
  date           = {1974-09-18/1975-11-29},
  url            = {https://example.com},
  urldate        = {2016-09-18/2017-11-29},
}
@book{elk5,
  author         = {Anne Elk},
  title          = {On the Theory of Brontosauruses},
  date           = {1974-09},
  url            = {https://example.com},
  urldate        = {2016-09},
}
@book{elk6,
  author         = {Anne Elk},
  title          = {On the Theory of Brontosauruses},
  date           = {1974},
  url            = {https://example.com},
  urldate        = {2016},
}
\end{filecontents}

\addbibresource{\jobname.bib}
\nocite{*}
\begin{document}
\cite[7]{elk1}
\printbibliography
\end{document}
```

**Comment by moewew** [comment]
@plk In case we can fix this quickly, can this still make it to 3.11?

**Comment by moewew** [comment]
Never mind. There is probably not going to be a quick fix for this anyway.

At the moment the `.lbx` files are not great when it comes to context-sensitive output. It would require a re-write of the entire localisation scheme for more flexibility to get this going properly (but of course I can't exclude the possibility that there is a trick to get this to work).

Fortunately, the only sensible input for a `urldate` is `YYYY-MM-DD` day (no range, day-level precision). And this is where 'visité le' works just fine. Incidentally German has the same problem 'besucht am' only really works for non-range `YYYY-MM-DD` dates. The English version 'visited on' also sounds awkward if  not followed by `YYYY-MM-DD`. If you insist on something that works for all possible (but rather useless) date input formats, you should probably translate `urlseen` with 'access date'.

All in all, I don't think this is a pressing issue and I think it makes more sense to approach this from a broader perspective of reworking the entire localisation scheme, but I don't see that happening soon (see also #708, #710 where we had great fun getting Latvian context-sensitive dates working). If you or anyone else reading this has a good idea for the issue at hand, however, suggestions will be greatly appreciated. And if something else comes up that shows the deficiencies of the current localisation scheme, I would not mind a heads-up at all.

**Comment by dbitouze** [comment]
I won't have time to look at workarounds in the next months and, as you said, probably not a pressing issue. So I would wait for a possible entire rework of the localization scheme.

**Comment by moewew** [comment]
Good, I'll leave this open for the time being.

> So I would wait for a possible entire rework of the localization scheme.

While this rework is certainly 'on the list', it is definitely not something I see happening any time soon, it is definitely something for the long term. So people reading this shouldn't get their hopes up too high. Suggestions are of course welcome.

**Comment by moewew** [comment]
I think we can close this now. This is a general problem that affects other languages as well, but it is very unlikely to surface since a `urldate` should only even be a simple date with at least day precision. A fix here would be much more complex than the small gain we'd get.
