### ISSUE TITLE
Error message confusing in case of no .bcf file

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#712]
If a `.tex` file (say `test.tex`) like the one below, is processed with `biber` while there is no corresponding `.bcf` file, the following error message is emitted:

>ERROR - Cannot find control file 'test.bcf'! - did you pass the "backend=biber" option to BibLaTeX?

But this is a bit confusing since the trouble comes from the lack more of `(pdf)latex` compilation than "backend=biber" option, `biber` being now the default backend.

```latex
\documentclass{article}
\usepackage{biblatex}
\addbibresource{biblatex-examples.bib}
\nocite{*}
\begin{document}
Foo.
\printbibliography
\end{document}
```

**Comment by plk** [comment]
I'll change the error to remove that part in biber 2.11 which will be released soon.
