### ISSUE TITLE
Locally add field (shorthand) to entry

### ISSUE THREAD

**Issue by demai** [plk/biblatex#716]
Let's say I have a large bibfile master.bib. In a given document I want to add shorthands to a certain number of entries *without* changing the bibfile itself. At the moment, I think this is not possible but would it be possible implement something like this? I was thinking about a command like this: `\addfieldtoentry{key}{field}{value}`; or even more advanced:

```
\patchentry{key}{
\addfield{field}{value}
}
```

**Comment by plk** [comment]
This is already possible, plus a lot more along the same lines using the `sourcemapping` feature which dynamically modifies the data as it is read, without changing the source files. See the `\DeclareSourcemap` command in the biblatex PDF documentation which has many examples. You can also ask this on tex.stackexchange.com and will get everything you need in terms of a specific solution.
