### ISSUE TITLE
About the punctuation after title with beamer class

### ISSUE THREAD

**Issue by hushidong** [plk/biblatex#735]
About the punctuation after title with beamer class

I have two problem, the first is:

What is the difference between `bibmacro*{title}` and a user defined `bibmacro*{titleuser}` wih beamer class. In the following example, there is an additional space after the dot followed the title, when I use `bibmacro*{title}`, but none when using `bibmacro*{titleuser}`.

And when I set beamer color template, the entry with `bibmacro*{title}` takes effect, but the one with `bibmacro*{titleuser}` does not. 

This indicates that something was redefined by beamer class, how can I cancel it if I still want to use the `bibmacro*{title}` to get the right punctuation and space?

	\documentclass{beamer}
	\mode<presentation>
	\usepackage{graphicx}
	\usepackage{xcolor}
	\usepackage{listings}
	\usepackage[backend=biber,style=numeric]{biblatex}
	\renewcommand{\bibfont}{\scriptsize}
	\usepackage{filecontents}
		\begin{filecontents}{\jobname.bib}
		@Book{Yi2014--,
		  Title                    = {Test},
		  Address                  = {Address},
		  Author                   = {Yi and B and C},
		  Publisher                = {Publisher},
		  Year                     = {2014}
		}
	@Inbook{MARTIN1996-85-96,
	  Title                    = {Control of electronic resources in Australia},
	  Author                   = {G MARTIN},
	  Bookauthor               = {L W PATTLE and B J COX},
	  Booktitle                = {Electronic resources},
	  Date                     = {1996},
	  Pages                    = {85-96},
	  Publisher                = {The Haworth Press},
	  Booktitleaddon           = {selection and bibliographic control},
	  Location                 = {New York}
	}
	\end{filecontents}
		\addbibresource{\jobname.bib}

	\DeclareFieldFormat{title}{#1}
	\DeclareFieldFormat[inbook]{title}{#1}%\isdot\addperiod\nopunct\unspace

	\setbeamercolor{bibliography entry author}{fg=red}
	\setbeamercolor{bibliography entry title}{fg=green}

	\renewbibmacro*{titleuser}{%
	  \ifboolexpr{%
		test{\iffieldundef{title}}%
		and%
		test{\iffieldundef{subtitle}}%
	  }%
		{}%
		{\printtext[title]{%
		   \printfield[titlecase]{title}%
		 }
		 %\newunit
	}%
	}

	\DeclareBibliographyDriver{book}{%
	  \usebibmacro{bibindex}%
	  \usebibmacro{begentry}%
	  \usebibmacro{author/editor+others/translator+others}%
	  \setunit{\printdelim{nametitledelim}}
	  \newunit\newblock
	  \usebibmacro{title}%
	  \newunit\newblock
	  \usebibmacro{publisher+location+date}%
	  \newunit\newblock
	  \usebibmacro{finentry}
	}

	\DeclareBibliographyDriver{inbook}{%
	  \usebibmacro{bibindex}%
	  \usebibmacro{begentry}%
	  \usebibmacro{author/translator+others}%
	  \setunit{\printdelim{nametitledelim}}
	  \newblock
	  \usebibmacro{titleuser}%
	  \newunit\newblock
	  \usebibmacro{publisher+location+date}%
	  \newunit\newblock
	  \usebibmacro{finentry}
	}

	\begin{document}

	\begin{frame}{reference}
	ref\cite{Yi2014--,MARTIN1996-85-96}
	\end{frame}

	\begin{frame}{reference}

	\printbibliography[heading=bibliography]

	\end{frame}

	\end{document}

the problem can also be testified when  I add a `\nopunct` in the title format, and the entry with `bibmacro*{titleuser}` indeed removes the dot after title but the entry with `bibmacro*{title}` does not.

	\documentclass{beamer}
	\mode<presentation>
	\usepackage{graphicx}
	\usepackage{xcolor}
	\usepackage{listings}
	\usepackage[backend=biber,style=numeric]{biblatex}
	\renewcommand{\bibfont}{\scriptsize}
	\usepackage{filecontents}
		\begin{filecontents}{\jobname.bib}
		@Book{Yi2014--,
		  Title                    = {Test},
		  Address                  = {Address},
		  Author                   = {Yi and B and C},
		  Publisher                = {Publisher},
		  Year                     = {2014}
		}
	@Inbook{MARTIN1996-85-96,
	  Title                    = {Control of electronic resources in Australia},
	  Author                   = {G MARTIN},
	  Bookauthor               = {L W PATTLE and B J COX},
	  Booktitle                = {Electronic resources},
	  Date                     = {1996},
	  Pages                    = {85-96},
	  Publisher                = {The Haworth Press},
	  Booktitleaddon           = {selection and bibliographic control},
	  Location                 = {New York}
	}
	\end{filecontents}
		\addbibresource{\jobname.bib}

	\DeclareFieldFormat{title}{#1\nopunct}
	\DeclareFieldFormat[inbook]{title}{#1\nopunct}%\isdot\addperiod\nopunct\unspace

	\setbeamercolor{bibliography entry author}{fg=red}
	\setbeamercolor{bibliography entry title}{fg=green}

	\renewbibmacro*{titleuser}{%
	  \ifboolexpr{%
		test{\iffieldundef{title}}%
		and%
		test{\iffieldundef{subtitle}}%
	  }%
		{}%
		{\printtext[title]{%
		   \printfield[titlecase]{title}%
		 }
		 %\newunit
	}%
	}

	\DeclareBibliographyDriver{book}{%
	  \usebibmacro{bibindex}%
	  \usebibmacro{begentry}%
	  \usebibmacro{author/editor+others/translator+others}%
	  \setunit{\printdelim{nametitledelim}}
	  \newunit\newblock
	  \usebibmacro{title}%
	  \newunit\newblock
	  \usebibmacro{publisher+location+date}%
	  \newunit\newblock
	  \usebibmacro{finentry}
	}

	\DeclareBibliographyDriver{inbook}{%
	  \usebibmacro{bibindex}%
	  \usebibmacro{begentry}%
	  \usebibmacro{author/translator+others}%
	  \setunit{\printdelim{nametitledelim}}
	  \newblock
	  \usebibmacro{titleuser}%
	  \newunit\newblock
	  \usebibmacro{publisher+location+date}%
	  \newunit\newblock
	  \usebibmacro{finentry}
	}

	\begin{document}

	\begin{frame}{reference}
	ref\cite{Yi2014--,MARTIN1996-85-96}
	\end{frame}

	\begin{frame}{reference}

	\printbibliography[heading=bibliography]

	\end{frame}

	\end{document}

	
The second question is:

I want to change the punct after title, e.g. change the "." to  "//". The method I used has two steps:
* step1: add `\nopunct` for title format to delete the dot after the title
* step2: add `\printtext{//}` in the driver

According to the result, the entry with `bibmacro*{titleuser}` meet my need, but the entry with `bibmacro*{title}` does not, i.e. there is a dot before "//". But in texlive2015 and texlive2016 the entry with `bibmacro*{title}` also results what I want, in contrast to the texlive2017. After update biblatex to v3.10 it is the same. Why does it raise this problem? the update of biblatex or the update of beamer class ? Is there any measure can be take if I still want to use `bibmacro*{title}`?

NOTE that this problem is raised with beamer class, and with article class there is no problem. 

	\documentclass{beamer}
	\mode<presentation>
	\usepackage{graphicx}
	\usepackage{xcolor}
	\usepackage{listings}
	\usepackage[backend=biber,style=numeric]{biblatex}
	\renewcommand{\bibfont}{\scriptsize}
	\usepackage{filecontents}
		\begin{filecontents}{\jobname.bib}
		@Book{Yi2014--,
		  Title                    = {Test},
		  Address                  = {Address},
		  Author                   = {Yi and B and C},
		  Publisher                = {Publisher},
		  Year                     = {2014}
		}
	@Inbook{MARTIN1996-85-96,
	  Title                    = {Control of electronic resources in Australia},
	  Author                   = {G MARTIN},
	  Bookauthor               = {L W PATTLE and B J COX},
	  Booktitle                = {Electronic resources},
	  Date                     = {1996},
	  Pages                    = {85-96},
	  Publisher                = {The Haworth Press},
	  Booktitleaddon           = {selection and bibliographic control},
	  Location                 = {New York}
	}
	\end{filecontents}
		\addbibresource{\jobname.bib}

	\DeclareFieldFormat{title}{#1\nopunct}
	\DeclareFieldFormat[inbook]{title}{#1\nopunct}%\isdot\addperiod\nopunct\unspace

	\setbeamercolor{bibliography entry author}{fg=red}
	\setbeamercolor{bibliography entry title}{fg=green}

	\renewbibmacro*{titleuser}{%
	  \ifboolexpr{%
		test{\iffieldundef{title}}%
		and%
		test{\iffieldundef{subtitle}}%
	  }%
		{}%
		{\printtext[title]{%
		   \printfield[titlecase]{title}%
		 }
		 %\newunit
	}%
	}

	\DeclareBibliographyDriver{book}{%
	  \usebibmacro{bibindex}%
	  \usebibmacro{begentry}%
	  \usebibmacro{author/editor+others/translator+others}%
	  \setunit{\printdelim{nametitledelim}}
	  \newunit\newblock
	  \usebibmacro{title}%
	  \printtext{\texttt{//}}
	  %\newunit\newblock
	  \usebibmacro{publisher+location+date}%
	  \newunit\newblock
	  \usebibmacro{finentry}
	}

	\DeclareBibliographyDriver{inbook}{%
	  \usebibmacro{bibindex}%
	  \usebibmacro{begentry}%
	  \usebibmacro{author/translator+others}%
	  \setunit{\printdelim{nametitledelim}}
	  \newblock
	  \usebibmacro{titleuser}%
	  \printtext{\texttt{//}}
	  %\newunit\newblock
	  \usebibmacro{publisher+location+date}%
	  \newunit\newblock
	  \usebibmacro{finentry}
	}

	\begin{document}

	\begin{frame}{reference}
	ref\cite{Yi2014--,MARTIN1996-85-96}
	\end{frame}

	\begin{frame}{reference}

	\printbibliography[heading=bibliography]

	\end{frame}

	\end{document}

**Comment by hushidong** [comment]
see this code: 

`\documentclass{beamer}
\mode<presentation>
\usepackage{graphicx}
\usepackage{xcolor}
\usepackage{listings}
\usepackage[backend=biber,style=numeric]{biblatex}
\usepackage{filecontents}
    \begin{filecontents}{\jobname.bib}
    @Book{Yi2014--,
      Title                    = {Test},
      Address                  = {Address},
      Author                   = {Yi and B and C},
      Publisher                = {Publisher},
      Year                     = {2014}
    }
\end{filecontents}
    \addbibresource{\jobname.bib}

\DeclareFieldFormat{title}{#1}
\DeclareFieldFormat{titlecase}{#1}
\setbeamercolor{bibliography entry author}{fg=red}
\setbeamercolor{bibliography entry title}{fg=green}

\newbibmacro*{title}{%
  \ifboolexpr{
    test {\iffieldundef{title}}
    and
    test {\iffieldundef{subtitle}}
  }
    {}
    {\printtext[title]{%
       \printfield[titlecase]{title}%
%       \setunit{\subtitlepunct}%
%       \printfield[titlecase]{subtitle}
       }%
     %\newunit
     }%
  %\printfield{titleaddon}%
  }

\DeclareBibliographyDriver{book}{%
  \usebibmacro{bibindex}%
  \usebibmacro{begentry}%
  \usebibmacro{author/editor+others/translator+others}%
  \setunit{\printdelim{nametitledelim}}
  \newunit\newblock
  \usebibmacro{title}%
  %\printtext{\texttt{//}}
  \newunit\newblock
  \usebibmacro{publisher+location+date}%
  \newunit\newblock
  \usebibmacro{finentry}
}


\begin{document}
\begin{frame}{reference}
ref\cite{Yi2014--}
\printbibliography[heading=bibliography]
\end{frame}
\end{document}

`

![default](https://user-images.githubusercontent.com/20421795/38318617-569398ee-3862-11e8-9d98-b215e824b834.png)

accoding to 

`\apptocmd{\abx@macro@title}
       {\ifcsundef{abx@field@title}{}{\ifpunct{}{\midsentence\newunitpunct}}%
\newblock\unspace\usebeamercolor[fg]{bibliography entry note}}{}{}`

Is  the dot is after “test”  introduced with `\newunitpunct` but why  is there an additional space after the dot when the `\unspace` is used？

**Comment by hushidong** [comment]
and  I add  code :

`\makeatletter
\AtBeginDocument{%
  \@ifpackageloaded{biblatex}
    {\apptocmd{\abx@macro@title}
       {\renewcommand*{\newunitpunct}{}}{}{}}
{}}
\makeatother`

the entire code is 

`\documentclass{beamer}
\mode<presentation>
\usepackage{graphicx}
\usepackage{xcolor}
\usepackage{listings}
\usepackage[backend=biber,style=numeric]{biblatex}
\usepackage{filecontents}
    \begin{filecontents}{\jobname.bib}
    @Book{Yi2014--,
      Title                    = {Test},
      Address                  = {Address},
      Author                   = {Yi and B and C},
      Publisher                = {Publisher},
      Year                     = {2014}
    }
\end{filecontents}
    \addbibresource{\jobname.bib}

\DeclareFieldFormat{title}{#1}
\DeclareFieldFormat{titlecase}{#1}
\setbeamercolor{bibliography entry author}{fg=red}
\setbeamercolor{bibliography entry title}{fg=green}

\newbibmacro*{title}{%
  \ifboolexpr{
    test {\iffieldundef{title}}
    and
    test {\iffieldundef{subtitle}}
  }
    {}
    {\printtext[title]{%
       \printfield[titlecase]{title}%
%       \setunit{\subtitlepunct}%
%       \printfield[titlecase]{subtitle}
       }%
     %\newunit
     }%
  %\printfield{titleaddon}%
  }

\DeclareBibliographyDriver{book}{%
  \usebibmacro{bibindex}%
  \usebibmacro{begentry}%
  \usebibmacro{author/editor+others/translator+others}%
  \setunit{\printdelim{nametitledelim}}
  \newunit\newblock
  \usebibmacro{title}%
  %\printtext{\texttt{//}}
  \newunit\newblock
  \usebibmacro{publisher+location+date}%
  \newunit\newblock
  \usebibmacro{finentry}
}

\makeatletter
\AtBeginDocument{%
  \@ifpackageloaded{biblatex}
    {\apptocmd{\abx@macro@title}
       {\renewcommand*{\newunitpunct}{}}{}{}}
{}}
\makeatother


\begin{document}
\begin{frame}{reference}
ref\cite{Yi2014--}
\printbibliography[heading=bibliography]
\end{frame}
\end{document}
`

result is:

![default](https://user-images.githubusercontent.com/20421795/38319901-a27bd57a-3865-11e8-8bb1-32c84af08cdb.png)

the additional space removed，but the dot is introduced by what ？

**Comment by hushidong** [comment]
after update the beamer, the space after dot is removed. and by comparison between the `titleuser`  and `title`, I get that the dot is introduced by `\newunitpunct`, but can I change the dot after title to other punctuation? 

if I path `title` using `apptocmd` again, the punctuation does not change.
but if I path `title` using `pretocmd`  again, the punctuation before title is alse changed.

see this example:

`\documentclass{beamer}
\mode<presentation>
\usepackage{graphicx}
\usepackage{xcolor}
\usepackage{listings}
\usepackage[backend=biber,style=numeric,sorting=none]{biblatex}
\renewcommand{\bibfont}{\scriptsize}
\usepackage{filecontents}
	\begin{filecontents}{\jobname.bib}
	@Book{Yi2014--,
	  Title                    = {Test},
	  Author                   = {G MARTINa},
	  Publisher                = {Publisher},
      Location                 = {Address},
	  Date                     = {2014}
	}
@Inbook{MARTIN1996-85-96,
  Title                    = {Test},
  Author                   = {G MARTINb},
  Date                     = {1996},
  Pages                    = {85-96},
  Publisher                = {The Haworth Press},
  Location                 = {Address}
}
\end{filecontents}
	\addbibresource{\jobname.bib}

\DeclareFieldFormat{title}{#1}
\DeclareFieldFormat[inbook,book]{title}{#1}%\isdot\addperiod\nopunct\unspace

\setbeamercolor{bibliography entry author}{fg=red}
\setbeamercolor{bibliography entry title}{fg=green}

\renewbibmacro*{title}{%
  \ifboolexpr{
    test {\iffieldundef{title}}
    and
    test {\iffieldundef{subtitle}}
  }
    {}
    {\printtext{%[title]
       \printfield{title}%[titlecase]
       }%
}%
}

\newbibmacro*{titleuser}{%
  \ifboolexpr{%
	test{\iffieldundef{title}}%
	and%
	test{\iffieldundef{subtitle}}%
  }%
	{}%
	{\printtext{%[title]
	   \printfield{title}%[titlecase]
	 }
}%
}

\DeclareBibliographyDriver{book}{%
  \usebibmacro{bibindex}%
  \usebibmacro{begentry}%
  \usebibmacro{author/translator+others}%
  \setunit{\printdelim{nametitledelim}}
  \newunit\newblock
  \usebibmacro{titleuser}%
  \newunit\newblock
  \usebibmacro{publisher+location+date}%
  \newunit\newblock
  \usebibmacro{finentry}
}

\DeclareBibliographyDriver{inbook}{%
  \usebibmacro{bibindex}%
  \usebibmacro{begentry}%
  \usebibmacro{author/translator+others}%
  \setunit{\printdelim{nametitledelim}}
  \newunit\newblock
  \usebibmacro{title}%
  \newunit\newblock
  \usebibmacro{publisher+location+date}%
  \newunit\newblock
  \usebibmacro{finentry}
}

\makeatletter
\AtBeginDocument{%
  \@ifpackageloaded{biblatex}
    {\pretocmd{\abx@macro@titleuser}
       {\ifcsundef{abx@name@labelname}{}{\let\bbx@tempa\labelnamepunct}%
        \bbx@tempa\newblock\unspace\usebeamercolor[fg]{bibliography entry title}}{}{}
     \apptocmd{\abx@macro@titleuser}
       {\renewcommand*{\newunitpunct}{\addcomma\space}}{}{}%\renewcommand*{\newunitpunct}{}
     \apptocmd{\abx@macro@titleuser}
       {\ifcsundef{abx@field@title}{}{\ifpunct{}{\midsentence\newunitpunct}}%\midsentence\newunitpunct
        \newblock\unspace\usebeamercolor[fg]{bibliography entry note}}{}{}
     \pretocmd{\abx@macro@title}
       {\renewcommand*{\newunitpunct}{\addcomma\space}}{}{}%\renewcommand*{\newunitpunct}{}
       }
{}}
\makeatother

\begin{document}
\begin{frame}{reference}
ref\cite{Yi2014--,MARTIN1996-85-96}
\printbibliography[heading=bibliography]
\end{frame}
\end{document} `

**Comment by hushidong** [comment]
I find the solution to this problem, add a patchcmd to remove the `\newunitpunct` introduced by apptocmd.

then the result is what I want.

`\documentclass{beamer}
\mode<presentation>
\usepackage{graphicx}
\usepackage{xcolor}
\usepackage{listings}
\usepackage[backend=biber,style=numeric,sorting=none]{biblatex}
\renewcommand{\bibfont}{\scriptsize}
\usepackage{filecontents}
	\begin{filecontents}{\jobname.bib}
	@Book{Yi2014--,
	  Title                    = {Test},
	  Author                   = {G MARTINa},
	  Publisher                = {Publisher},
      Location                 = {Address},
	  Date                     = {2014}
	}
@Inbook{MARTIN1996-85-96,
  Title                    = {Test},
  Author                   = {G MARTINb},
  Date                     = {1996},
  Pages                    = {85-96},
  Publisher                = {The Haworth Press},
  Location                 = {Address}
}
\end{filecontents}
	\addbibresource{\jobname.bib}

\DeclareFieldFormat{title}{#1}
\DeclareFieldFormat[inbook]{title}{#1}%\isdot\addperiod\nopunct\unspace

\setbeamercolor{bibliography entry author}{fg=red}
\setbeamercolor{bibliography entry title}{fg=green}

\renewbibmacro*{title}{%
  \ifboolexpr{
    test {\iffieldundef{title}}
    and
    test {\iffieldundef{subtitle}}
  }
    {}
    {\printtext{%[title]
       \printfield{title}%[titlecase]
       }%
}%
}

\newbibmacro*{titleuser}{%
  \ifboolexpr{%
	test{\iffieldundef{title}}%
	and%
	test{\iffieldundef{subtitle}}%
  }%
	{}%
	{\printtext{%[title]
	   \printfield{title}%[titlecase]
	 }
}%
}

\DeclareBibliographyDriver{book}{%
  \usebibmacro{bibindex}%
  \usebibmacro{begentry}%
  \usebibmacro{author/translator+others}%
  \setunit{\printdelim{nametitledelim}}
  \newunit\newblock
  \usebibmacro{titleuser}%
  \newunit\newblock
  \usebibmacro{publisher+location+date}%
  \newunit\newblock
  \usebibmacro{finentry}
}

\DeclareBibliographyDriver{inbook}{%
  \usebibmacro{bibindex}%
  \usebibmacro{begentry}%
  \usebibmacro{author/translator+others}%
  \setunit{\printdelim{nametitledelim}}
  \newunit\newblock
  \usebibmacro{title}%
  \printtext{\texttt{//}}%
  %\newunit\newblock
  \usebibmacro{publisher+location+date}%
  \newunit\newblock
  \usebibmacro{finentry}
}

\makeatletter
\AtBeginDocument{%
  \@ifpackageloaded{biblatex}
    {\pretocmd{\abx@macro@titleuser}
       {\ifcsundef{abx@name@labelname}{}{\let\bbx@tempa\labelnamepunct}%
        \bbx@tempa\newblock\unspace\usebeamercolor[fg]{bibliography entry title}}{}{}
     \apptocmd{\abx@macro@titleuser}
       {\renewcommand*{\newunitpunct}{\addcomma\space}}{}{}%\renewcommand*{\newunitpunct}{}
     \apptocmd{\abx@macro@titleuser}
       {\ifcsundef{abx@field@title}{}{\ifpunct{}{\midsentence\newunitpunct}}%\midsentence\newunitpunct
        \newblock\unspace\usebeamercolor[fg]{bibliography entry note}}{}{}
%     \pretocmd{\abx@macro@title}
%       %{\renewcommand*{\newunitpunct}{\addcomma\space}}{}{}%\renewcommand*{\newunitpunct}{}
%       {\renewcommand*{\newunitpunct}{}}{}{}%\renewcommand*{\newunitpunct}{}
     \patchcmd{\abx@macro@title}{\newunitpunct}{}{}{}
%    \apptocmd{\abx@macro@title}
%       {\midsentence\setunit{\addcomma}}{}{}
       }
{}}
\makeatother

\begin{document}
\begin{frame}{reference}
ref\cite{Yi2014--,MARTIN1996-85-96}
\printbibliography[heading=bibliography]
\end{frame}
\end{document} `

result:

![default](https://user-images.githubusercontent.com/20421795/38343807-97937336-38b8-11e8-8392-63a3d29733ed.png)

Thanks a lot for  your directive illustrations!!!

**Comment by moewew** [comment]
Glad it works now. Does that mean we can close this issue here?

**Comment by hushidong** [comment]
ok, thanks! hzzmail 邮箱：hzzmail@sjtu.org 签名由 网易邮箱大师 定制 在2018年04月05日 15:11，moewew 写道： Glad it works now. Does that mean we can close this issue here? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
