### ISSUE TITLE
labelprefix=@ causes undefined references

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#738]
See https://github.com/plk/biber/issues/223

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=numeric, backend=biber, defernumbers=true]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{sigfridsson,ctan}
\printbibheading
\printbibliography[heading=subbibliography,title={Not internet},nottype=online]
\newrefcontext[labelprefix=@]
\printbibliography[heading=subbibliography,title={Internet},type=online]
\end{document}
```
gives undefined references and nulled-out citation numbers. 

Adding `\makeatletter` as in `\makeatletter\newrefcontext[labelprefix=@]\makeatother` fixes the problem, so this probably has to do with category codes and probably `detokenize`.

**Comment by moewew** [comment]
The problem here is that the labelprefix (`\blx@refcontext@labelprefix`) is part of the internal naming structure which should ideally use only safe characters while at the same time appears in the output where much more should be possible.

@plk Maybe we should completely separate these two functions of `labelprefix` into an internal designator `\blx@refcontext@labelprefix` and the actual output `\abx@field@labelprefix` more aggressively. 
As far as I can see most of the separation is already there: We just need to make sure that
- `\blx@refcontext@labelprefix` only contains safe characters: We could do this by using a counter value.
- Pass on both `\blx@refcontext@labelprefix` and the actual desired `labelprefix` value to Biber in the `.bcf`. Use `\blx@refcontext@labelprefix` to construct the refcontext name, use `labelprefix` to populate `\field{labelprefix}` in the `.bbl`.

**Comment by moewew** [comment]
As it turns out a simple counter is probably not the right way to generate the internal `\blx@refcontext@labelprefix`: We want to be able to re-use refcontexts.

**Comment by moewew** [comment]
@plk Do you have any idea what we could do here? At the moment `labelprefix` is expanded and used as part of an internal designator for the bibliography context. That strongly restricts the possible values it may have and can lead to unexpected behaviour as shown in the MWE. Ideally we would implement a way to use arbitrary text as `labelprefix` and use an internal safe designator for the refcontext.

**Comment by plk** [comment]
Hmm, can't we just `\ makeatletter/\makeatother` during the assignment to `\blx@refcontext@labelprefix` internally? I haven't looked into this closely.

**Comment by moewew** [comment]
That would help with this specific issue but does not help with the bigger picture that the labelprefix value can currently only contain strings that are safe in an `\edef`. With `pdflatex` non-ASCII chars also explode, for example
```
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=numeric, backend=biber, defernumbers=true]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{sigfridsson,ctan}
\printbibheading
\printbibliography[heading=subbibliography,title={Not internet},nottype=online]
\newrefcontext[labelprefix=Ä]
\printbibliography[heading=subbibliography,title={Internet},type=online]
\end{document}
```

The `labelprefix` value is currently being used as an internal identifier for all sorts of things, I have a hunch that that makes it extremely difficult to allow for arbitrary input. Currently my working hypothesis is that we would have to somehow shift to a safe internal name for each `labelprefix` and only use the actual value for typesetting purposes to safe this. But maybe we can also get away with controlling the expansion of `labelprefix` more closely by not going full `\edef` at all times (I'm not sure if and how that is possible).

**Comment by plk** [comment]
I have some ideas. However, I can't get the original case to fail with `@` - it works for me with both pdflatex and lualatex? The `Ä` fails with pdflatex.

**Comment by plk** [comment]
Hmm, it needs a `biblatex` solution as even in biber-only situations, `biblatex` writes `labelprefix` to the `.aux`, which cause problems on reading it again. I tried md5 hashes (`\pdfmdfivesum`) but that doesn't work because of the numbers ...

**Comment by moewew** [comment]
Just something that occurred to me... I initially thought one would want to just prevent any expansion of the `labelprefix` as long as possible. But there are (semi-)legitimate uses for things like `labelprefix=\thechapter` that would be nice to have...

Maybe we can have the user supply a safe name manually if needed. To keep things backwards compatible we could try to use `labelprefix` as internal name if possible, but allow the user to override that with a safe name. The real `labelprefix` could then be passed on detokenized or otherwise made safe to the external files if needed. I didn't check if that would work, though ...

**Comment by plk** [comment]
What's the issue with a counter that you mentioned? It seems like we could use a (romanised) counter which are the keys to a hash to map to the real label.

**Comment by moewew** [comment]
When I initially had the idea of counters I just thought we could blindly count up for each occurence of `labelprefix`. But that does not really work if we want to re-use contexts.

So if I have

```
\newrefcontext[labelprefix=A]
\newrefcontext[labelprefix=B]
\newrefcontext[labelprefix=A]
```
the last refcontext should be the same as the first one. If we blindly count up, however, the numbers and hence the contexts would be different.

**Comment by plk** [comment]
Ok, please try the latest DEV `biblatex`. This now works for me in both Pdftex and luatex:

```
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=numeric, backend=biber, defernumbers=true]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{sigfridsson,ctan,aristotle:anima}
\printbibheading
\printbibliography[heading=subbibliography,title={Not internet},nottype=online]
\newrefcontext[labelprefix=@]
\printbibliography[heading=subbibliography,title={Internet},type=online]
\newrefcontext[labelprefix=Ä]
\printbibliography[heading=subbibliography,title={Internet},type=book]
\end{document}
```
It's done with a roman numeral index saved across runs in the .aux and the counter won't be incremented if there is already an index for the same character etc.

Repeated identical refcontexts with `derfernumbers` will often be a problem as it doesn't make much sense to do that given the compile-time numbering and context resolution. However, putting the second identical context in another refsection fixes that.

One annoying side-effect is that the `assignrefcontext*` commands now must not be used in the preamble as they rely on being called after the index mapping is done for all refcontexts and this basically means after the .aux is read. I don't see much issue with this as they are relatively esoteric commands anyway. If you know a variant of `\@onlypreamble` which does the opposite, I can use to enforce this, let me know.

**Comment by moewew** [comment]
I'll hopefully be able to have a closer look at this a little later. The MWE works fine for me now, but since we are still constructing a control sequence name from the prefix value in
```
\def\abx@labelprefixmap#1#2#3{%
  \csgdef{abx@labelprefixmap@#1@#2}{#3}}
```
we still can't use arbitrary stuff like `\textit{Ä}`. I guess you have to draw the line somewhere.

I'm still thinking about the user-supplied `name` in case `labelprefix` contains evil stuff, maybe I can throw something together and we can see if that would help. It would require user interaction unlike the Roman numbers, but it could hopefully avoid ever building command sequences from dangerous `labelrefix` values.

**Comment by plk** [comment]
I'm happy with `\textit{Ä}` not working, that's a style issue. I'm not sure exactly what you mean by this `name` interface?

**Comment by plk** [comment]
That's a nice trick with the preamble thing - can you merge that and I'll test?

The `labelprefixname` thing - I still don't understand this - why would users want to control this? They only care about `labelprefix` and isn't it better to hide the internals of making this safe?

**Comment by moewew** [comment]
Merged https://github.com/plk/biblatex/commit/4cfa046b09e11b285190485584375ac926a01ddf.

The `labelprefixname` solves one problem: It does away with the need to have a mapping from `labelprefix` to an internal name (the Roman counter). That map is currently the biggest obstacle when we want arbitrary `labelprefix` values, since the `labelprefix` must allow
```
\csdef{abx@labelprefixmap@<refsection>@<labelprefix>}
```
to be definable. If `labelprefix` is something non-expandable that breaks down spectacularly.

My cheap solution is to have the user come up with the safe internal name themselves (if necessary), that would remove the need for the mapping from literal prefix to safe internal name.

The MWE I posted above can deal with `labelprefix=\dag` while the current solution with Roman numerals can not.

**Comment by plk** [comment]
I see. I would really rather users didn't have to care about protecting from such internal issues as they would then have to know what is safe to construct macro names with and that's not a concept which many people would even know about. Which means we would end up with documentation saying "if it breaks, try using a `labelprefixname`" which is a bit ugly. Needs some thinking about. A counter isn't good for this, I agree. If there were some way of generating a safe, unique key from any (detokenized) string, this would be easy. I tried `mdfivesum` but of course numbers are the wrong catcode ...

**Comment by moewew** [comment]
Yeah, it would essentially come down to telling the user to *try this other thing* if the obvious attempt does not work, which is suboptimal.

Naively I'd have said that it should be possible to work around then numbers in MD5 hashes. I'll have a look at that later. But how is the engine support for MD5 sums? https://tex.stackexchange.com/q/252566/35864 suggests it is a bit of a fragmentation nightmare.

**Comment by moewew** [comment]
https://github.com/plk/biblatex/compare/dev...moewew:hashlabelprefix has a solution with MD5 hashes. That means no `.aux` file is needed and we can revert https://github.com/plk/biblatex/commit/4cfa046b09e11b285190485584375ac926a01ddf. I also implemented `labelprefix*` for unexpandable content. This is a bit of 'if X does not work try Y', but it was the best solution I could find to this issue.

Now
```
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=numeric, backend=biber, defernumbers=true]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{sigfridsson,ctan,aristotle:anima,geer,worman}
\printbibheading
\printbibliography[heading=subbibliography,title={Articles},type=article]
\newrefcontext[labelprefix=@]
\printbibliography[heading=subbibliography,title={Internet},type=online]
\newrefcontext[labelprefix*=\dag]
\printbibliography[heading=subbibliography,title={Books},type=book]
\newrefcontext[labelprefix=Ä]
\printbibliography[heading=subbibliography,title={Theses},type=thesis]
\end{document}
```
works as expected.

**Comment by moewew** [comment]
Mhhh, in light of https://github.com/plk/biblatex/issues/740 maybe we should just 'upgrade' `\regexp` to a more generic macro and ask users to protect unexpandable contents. We could then replace `labelprefix*=\dag` with `labelprefix=\regexp{\dag}`...

**Comment by moewew** [comment]
Ahhh, turns out the `\zap@space` is not good for what I had in mind anyway (try `\regexp{\dag a}`), so we can just take good old `\detokenize` and tell people to use that.

So should I remove `labelprefix*` which essentially does `labelprefix=\detokenize{...}` from https://github.com/plk/biblatex/compare/dev...moewew:hashlabelprefix or do we keep it as a convenient shorthand?

**Comment by moewew** [comment]
OK. I submitted https://github.com/plk/biblatex/pull/824 with the suggestions from https://github.com/plk/biblatex/compare/dev...moewew:hashlpm. It implements `labelprefix` with MD5 hashes.

**Comment by plk** [comment]
Tests look fine, thanks for looking at this.
