### ISSUE TITLE
biber conversion from ASCII-TeX to Unicode

### ISSUE THREAD

**Issue by pauloney** [plk/biblatex#739]
This is more a question ... 

Can the routine used by Biber to convert ASCII-TeX into Unicode (in the .bbl file) be used to convert more generic TeX files from ASCII-TeX to UTF-8?

Essentially, I am looking for more information in how and where this translation happens.

Paulo Ney

**Comment by moewew** [comment]
Links to your questions on TeX.SX: https://tex.stackexchange.com/q/427974/35864 and https://tex.stackexchange.com/q/428128/35864

PLK will know much more about this, but I seriously doubt that you can use Biber - or even the methods Biber uses - to convert an entire document. Biber does not parse (La)TeX, Biber uses RegExp to do most of the conversion with simple string replacements. RegExp has no notion of grouping and nested braces. Additionally, Biber does not know about more advanced concepts, environments and macros such as `verbatim`.

Biber is good at converting `.bib` files, which normally contain only little special macros aside from ASCII-macros for UTF-8 chars and a few limited markup commands. Mathematics can already pose quite some challenges.

But in a full document the whole environment and the meaning of macros is much less controlled all bets are off.

**Comment by moewew** [comment]
I think https://github.com/plk/biber/blob/7bb12356ec92206875ddb0af0c0cef2f1b60560c/lib/Biber/LaTeX/Recode.pm and https://github.com/plk/biber/blob/977357d72de2e3c80ef1859d3e8f3ac639b7a5d6/lib/Biber/LaTeX/recode_data.xml are the most relevant for you, I believe.

**Comment by moewew** [comment]
I'm closing this for now as there is nothing more we can do here.

Just one last remark: For a proper conversion of a full document you'd essentially have to parse and execute all TeX commands to be sure you got everything exactly right. I once read 'only TeX can parse TeX' in a comment on TeX.SX and that is the point here, RegEx can't parse all of TeX. The situation seems similar to parsing HTML with RegExp: https://stackoverflow.com/q/1732348, you may/can get away with parsing a limited subset of the language, but the full thing will probably blow up.
