### ISSUE TITLE
Make \DefineBibliographyStrings deal with two (long and abbreviated) strings

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#74]
`\DeclareBibliographyStrings` used in .lbx files deals with two (long and abbreviated) strings, for instance:

``` latex
\DeclareBibliographyStrings{%
  ...
  jourvol          = {{volume}{vol\adddot}},
  ...
}
```

The average user who wants to customize a localized string (but doesn't want to recreate a customized .lbx file) has to make use of `\DefineBibliographyStrings` in premable (or in biblatex.cfg file). But, by contrast to `\DeclareBibliographyStrings`, `\DefineBibliographyStrings` deals only with one string and cannot provide long and abbreviated customized strings:

``` latex
\DefineBibliographyStrings{%
  ...
  jourvol          = {vol\adddot},
  ...
}
```

Hence this user has to choose between these long and short strings, and only one of them will be displayed, regardless the bibliographic/citation style used (providing abbreviated strings or not).

It could be nice to enhance the way `\DefineBibliographyStrings` works to make it deal with two (long and abbreviated) strings.

**Comment by alexreg** [comment]
I came across this issue myself, and agree with @dbitouze here. This should be much easier to do.

**Comment by moewew** [comment]
This was also discussed briefly in https://github.com/plk/biblatex/issues/774. At the time I could not find a way to implement this in a backwards compatible way. If anyone has any idea how to do that reliably, we can definitely revisit this. If not, there is not a lot we can do I'm afraid.

**Comment by alexreg** [comment]
I see. Would there be a problem with just creating a new macro like `DefineBibliographyStringsFull` that supports the abbreviated form too? Or perhaps the existing `DefineBibliographyStrings` macro can even be adjusted to accept *either* one or two strings per key, with the help of xparse or such, and thus backwards compatibility is maintained. Or am I missing soemthing here?
