### ISSUE TITLE
Warning when biblatex used with amsart and hyperref

### ISSUE THREAD

**Issue by ed359** [plk/biblatex#744]
The following document compiles with a warning:
```latex
\documentclass{amsart}
\usepackage{biblatex}
\usepackage{hyperref}
\listfiles
\begin{document}
\end{document}
```
The warning is:
```
Package biblatex Warning: Patching footnotes failed.
(biblatex)                Footnote detection will not work.
```

Changing `amsart` to `article` kills the warning. Also, disabling hyperlinked footnotes by either (a) removing `hyperref` or (b) adding `[hyperfootnotes=false]` kills the warning. 

Edited information from `\listfiles`:
pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018)
amsart.cls    2017/10/31 v2.20.4
biblatex.sty    2018/03/04 v3.11 programmable bibliographies (PK/MW)
hyperref.sty    2018/02/06 v6.86b Hypertext links for LaTeX

The problem is probably something to do with how `amsart.cls` redefines `\@footnotetext`:
```latex
\long\def\@footnotetext#1{%
  \insert\footins{%
    \normalfont\footnotesize
    \interlinepenalty\interfootnotelinepenalty
    \splittopskip\footnotesep \splitmaxdepth \dp\strutbox
    \floatingpenalty\@MM \hsize\columnwidth
    \@parboxrestore \parindent\normalparindent \sloppy
    \protected@edef\@currentlabel{%
      \csname p@footnote\endcsname\@thefnmark}%
    \@makefntext{%
      \rule\z@\footnotesep\ignorespaces#1\unskip\strut\par}}}
```

Also filed on hyperref github: https://github.com/ho-tex/hyperref/issues/61

**Comment by moewew** [comment]
If document classes use non-standard definitions of (for example) footnote commands, `biblatex` may fail to patch them and will duly issue a warning. We must accept that `biblatex` will never be able to patch all document classes sufficiently well.

I'm not sure if it is even worth investigating this, since the `amsart` documentation makes quite clear (§7, p. 18 of the [AMS Author Handbook, Journal Classes](http://mirrors.ctan.org/info/amscls-doc/Author_Handbook_Journals.pdf))
> Bibliographies may be prepared using either `amsrefs` or BibTeX. Methods using other packages, including `biblatex`, are not supported.

**Comment by moewew** [comment]
As it turns out we already have code set up especially for the AMS classes and adding support for hyperref was not too complicated. https://github.com/plk/biblatex/commit/f86db1ca3d984e12a2d8f975b4e77cd818ff5030 should get this working even with `hyperref` and will be in the next release.

**Comment by moewew** [comment]
`biblatex` 3.12 has been released and is available in TeX live 2018 and MikTeX.

The example code in the first post does not throw a warning any more.
