### ISSUE TITLE
[PATCH] authoryear.bbx: add a macro to tell whether a separate date is to be formatted

### ISSUE THREAD

**Issue by CasperVector** [plk/biblatex#752]
As the title.  This helps to simplify boilerplates like [this](https://github.com/CasperVector/biblatex-caspervector/blob/c837e1491ebe318e7c146462ac0f336feb87437c/tex/caspervector-ay.bbx#L30); the `bbx:ifnodate` macro can be used like [this](https://github.com/CasperVector/biblatex-caspervector/blob/c837e1491ebe318e7c146462ac0f336feb87437c/tex/blx-caspervector-base.def#L157).
```diff
diff --git a/tex/latex/biblatex/bbx/authoryear.bbx b/tex/latex/biblatex/bbx/authoryear.bbx
index 0a2a8a74..8424d40f 100644
--- a/tex/latex/biblatex/bbx/authoryear.bbx
+++ b/tex/latex/biblatex/bbx/authoryear.bbx
@@ -25,6 +25,8 @@
   \usebibmacro{date+extradate}}
 
 \def\bbx@opt@mergedate@true{\bbx@opt@mergedate@compact}
+\newbibmacro*{bbx:ifnodate}[2]{#2}
+\renewbibmacro*{date}{\usebibmacro{bbx:ifnodate}{}{\printdate}}
 
 % merge date/issue with date label
 \def\bbx@opt@mergedate@maximum{%
@@ -37,10 +39,9 @@
             \setunit*{\addspace}%
             \printdateextra}
            {\printlabeldateextra}}}}%
-  \renewbibmacro*{date}{%
+  \renewbibmacro*{bbx:ifnodate}[2]{%
     \iflabeldateisdate
-      {}
-      {\printdate}}%
+      {#1}{#2}}%
   \renewbibmacro*{issue+date}{%
     \iflabeldateisdate
       {}
@@ -58,10 +59,9 @@
          \iflabeldateisdate
            {\printdateextra}
            {\printlabeldateextra}}}}%
-  \renewbibmacro*{date}{%
+  \renewbibmacro*{bbx:ifnodate}[2]{%
     \iflabeldateisdate
-      {}
-      {\printdate}}%
+      {#1}{#2}}%
   \renewbibmacro*{issue+date}{%
     \ifboolexpr{not test {\iffieldundef{issue}}
                 or not test {\iflabeldateisdate}}
@@ -80,14 +80,13 @@
     \iffieldundef{labelyear}
       {}
       {\printtext[parens]{\printlabeldateextra}}}%
-  \renewbibmacro*{date}{%
+  \renewbibmacro*{bbx:ifnodate}[2]{%
     \ifboolexpr{
       test {\iflabeldateisdate}
       and
       not test {\ifdateshavedifferentprecision{label}{}}
     }
-      {}
-      {\printdate}}%
+      {#1}{#2}}%
   \renewbibmacro*{issue+date}{%
     \ifboolexpr{
       test {\iflabeldateisdate}
@@ -109,7 +108,7 @@
     \iffieldundef{labelyear}
       {}
       {\printtext[parens]{\printlabeldateextra}}}%
-  \renewbibmacro*{date}{%
+  \renewbibmacro*{bbx:ifnodate}[2]{%
     \ifboolexpr{
       test {\iflabeldateisdate}
       and
@@ -117,8 +116,7 @@
       and
       test {\iffieldundef{extradate}}
     }
-      {}
-      {\printdate}}%
+      {#1}{#2}}%
   \renewbibmacro*{issue+date}{%
     \ifboolexpr{
       test {\iflabeldateisdate}
@@ -142,7 +140,7 @@
     \iffieldundef{labelyear}
       {}
       {\printtext[parens]{\printlabeldateextra}}}%
-  \renewbibmacro*{date}{\printdate}%
+  \renewbibmacro*{bbx:ifnodate}[2]{#2}%
   \renewbibmacro*{issue+date}{%
     \printtext[parens]{%
       \printfield{issue}%
```

**Comment by moewew** [comment]
Thank you for the suggestion.

I must admit I don't quite see the advantage of the new macro. For the standard styles it looks like it would actually make the code more confusing by adding an additional layer of macro calls. Plus we need to be very careful about changes to the standard styles, every change to the macros breaks someone's code - especial name changes like this.

**Comment by CasperVector** [comment]
My main reason behind this proposal is that we had no way to check whether a separate date (apart from the one in the label) was to be formatted, which can be really annoying when one wanted to implement optional punctuation based on this check (like the code in `blx-caspervector-base.def`).
The `date` macro is not renamed, and the `bbx:ifnodate` bibmacro does not clash with any other bibmacro AFAIK.  Nevertheless I understand that quite a few packages already have code that monkey-patches the `\bbx@opt@mergedate@*` macros, which is IMO the main source of confusion in comparison with the addedlayer which is really thin.

**Comment by moewew** [comment]
Actually I'm beginning to understand what this is good for an I'm coming round to liking the idea more.

It still feels a bit weird to me, so I'm a bit torn at the moment. Like you I don't really expect major problems with this change, but I have learned to be cautious.

@plk What do you think?

**Comment by plk** [comment]
In general, I like this approach and the extra abstraction - it makes future changes and extensions easier so I'm ok with implementing this. People patching internal macros is always accompanied with the caveat that they can change.

**Comment by moewew** [comment]
OK, I'll have a closer look at this again.

At the moment I'm leaning towards implementing this idea as something looking more like a `\if....` rather than a bibmacro, but the idea should be the same.

**Comment by moewew** [comment]
A first suggestion for an implementation is at https://github.com/plk/biblatex/pull/810

**Comment by CasperVector** [comment]
Looks good to me; the "negative code" and the cleaner logic are really nice. 
(And I really did not realise the relationship of `issue+date` and `date` macros.)

**Comment by moewew** [comment]
Thank you very much for the suggestion. The idea has been taken up as `bbx:ifmergeddate` and can be used as follows
```
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}
\usepackage{xcolor}

\usepackage[style=authoryear, mergedate=basic, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}

\renewbibmacro{date}{%
  \usebibmacro{bbx:ifmergeddate}
    {\printtext{\color{red}no need to print the date again}}
    {\printtext{\color{green}give us the date}%
     \setunit{\addspace}%
     \printdate}}

\begin{document}
\cite{nussbaum,baez/online,knuth:ct:b,knuth:ct:c}
\printbibliography
\end{document}
```

No backwards compatibility issues are expected, but if there are any please log them in separate issues.

**Comment by dbitouze** [comment]
> `mergedate=basic`

AFAICS, only `true` (and, hence, `false`) value of `mergedate` is (briefly) documented, not `basic`.

**Comment by moewew** [comment]
@dbitouze  Style options like `mergedate` and friends are documented in the style documentation, e.g. http://mirrors.ctan.org/macros/latex/contrib/biblatex/doc/examples/50-style-authoryear-biber.pdf, and not in the main `biblatex` documentation, where only `biblatex`'s own options are documented. Same for `dashed`.

**Comment by dbitouze** [comment]
Okay. An hyperlink to the relevant document would be helpful: I'm not a beginner in `biblatex` but had no idea where the style documentation could be. Okay, I could have a look at:

```
texdoc -l biblatex
```
but that returns 237 results, which is a bit disheartening :)

**Comment by moewew** [comment]
@dbitouze Good idea tracking that in https://github.com/plk/biblatex/issues/838. Suggestions are welcome.

**Comment by dbitouze** [comment]
Thanks!
