### ISSUE TITLE
Wrapper formats for lists and name lists

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#754]
At the moment `\DeclareListFormat` and `\DeclareNameFormat` are applied to each (name) list item separately, this allows for per-item formatting, but not for an overall (name) list wrapper. If one wants to format the entire list one could either format each item and hope that the result is roughly as expected or execute a command at the start of the first entry and at the end of the last entry. But that does not really feel right...

So `\DeclareOuterListFormat`/`\DeclareOuterNameFormat` (suggestions for better names are very much appreciated, theoretically we could also recycle `\DeclareFieldFormat`, but that could cause confusion or backwards compatibility issues in weird set-ups) might come in handy. I had a short look at the code and I think it should be possible to implement a wrapper without undue difficulties.

**Edit** First, simple solution using `\DeclareFieldFormat` is https://github.com/moewew/biblatex/commit/240944da581f102467e2ba2f18a47b94ad303f18 at https://github.com/plk/biblatex/compare/dev...moewew:listwrapper

I can think of one or two very niche uses for this, so the question is whether or not this would be considered interesting enough for the general public to implement.

**Comment by plk** [comment]
I can see the use of this. It would be nice to rename the existing list macro to `\DeclareListItemFormat` and use `\DeclareListFormat` for the new functionality, with suitable warning. Names are easier as we can leave the current one alone and use `\DeclareNamesFormat` for the new functionality.

**Comment by moewew** [comment]
I like `\DeclareNamesFormat`, even though the **`s`** is easy to miss. But I'm wary about changing the meaning of fairly high-level macros like `\DeclareListFormat`. Even though I assume it is not up there with the likes of  `\DeclareFieldFormat` and `\DeclareNameFormat` I fear it could break too many people's documents.

**Comment by moewew** [comment]
A new attempt is at https://github.com/plk/biblatex/compare/dev...moewew:listwrapper. I decided that *wrapper* as in `NameWrapper` and `ListWrapper` would be a natural name for this feature.

I'll prepare a pull request tomorrow if I don't find anything wrong with the commit.
