### ISSUE TITLE
min/maxsortnames?

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#755]
Currently sorting seems to happen according to `min/maxbibname` truncation. Would it be possible to offer, say, `minsortnames` and `maxsortnames`  to control the sorting without changing the display behaviour of names? I can definitely see the appeal of sorting by citation truncation rather than bibliography truncation.

See also https://tex.stackexchange.com/q/434945/35864

**Comment by moewew** [comment]
I'm a bit unsure. In my head all I would do is switch between `cite` and `bib`, but heaven knows what other people might want or need (not related to this exact feature request, but case in point: https://tex.stackexchange.com/q/434952/35864). So I would naturally prefer a fully flexible counter which falls back to `min/maxbibnames` for backwards compatibility. But I don't know what that would entail on the Biber side and for name list disambiguation.

Anyway, there is no need to rush this, I'm just spamming the issue tracker when I come across something so I don't forget about it.

**Comment by plk** [comment]
It's complex to add a new counter for sorting as it's not clear how this interacts with `uniquelist` etc. Much easier to switch between existing counters as they all depend on `uniquelist` in the same way.

**Comment by moewew** [comment]
I see, feared as much. Maybe we could have the new counter interact with `uniquelist` exactly as the others do already. But I don't know enough about Biber to see how that would go.

Out of interest: How does this work at the moment exactly? It seemed to me that sorting is determined by `bibnames`, but I always though `uniquelist` was on `citenames` terms...

**Comment by plk** [comment]
Yes, it could interact with `uniquelist` in the same way but that might not be expected as this new counter doesn't determine anything visible. At the moment, sorting is determined by `bibnames` and `uniquelist`, if used, overrides both `mincitenames` and `minbibnames`.

**Comment by moewew** [comment]
Ah, thank you.

I can see why that would be unintuitive, yes... The only useful thing in my head is basically truncating to `citenames` and there it would make sense to obey `uniquelist` ...

**Comment by samcarter8** [comment]
Having either the choice between bib/citenames for sorting or having an own counter would be useful. 

If this is technically too difficult, an option to sort only by first name would probably sufficient in most cases (sorting by first author was already asked a couple of times on tex.se)

**Comment by plk** [comment]
This should already be possible - have you looked at `\DeclareSortingNamekeyTemplate`?

**Comment by samcarter8** [comment]
@plk Isn't the `\DeclareSortingNamekeyTemplate` for how the sorting takes into account the different parts of a name? Can it also be used to only sort after the first person in an author list?

**Comment by plk** [comment]
No, it can't select just one name. I would need to look into this.

**Comment by plk** [comment]
Please try the latest dev versions of biber/biblatex from SF. There are now new counters `min/maxsortnames` which sorting obeys. By default, it has the same defaults as `min/maxbibnames`.

**Comment by moewew** [comment]
It works brilliantly so far. Thank you very much.

Unfortunately, there is one area I have not given much thought until now: **backwards compatibility**. In older versions sorting would obey `(min|max)bibnames`, bit now it obeys `(min|max)sortnames`. That means that we get different results now if `(min|max)bibnames` is set to a value different from `(min|max)names` and `(min|max)sortnames` is not changed at the same time.
Compare
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber, maxcitenames=1, maxbibnames=4, uniquelist=false]{biblatex}


\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{appleby,
  author  = {Appleby, Humphrey and Hacker, James and Filler Name and Woolley, Bernard},
  title   = {On the Importance of the Civil Service: W},
  date    = {1983},
}
@book{appleby2,
  author  = {Appleby, Humphrey and Hacker, James and Filler Name and Yoolley, Bernard},
  title   = {On the Importance of the Civil Service: Y},
  date    = {1982},
}
@book{appleby3,
  author  = {Appleby, Humphrey and Hacker, James and Filler Name and Zoolley, Bernard},
  title   = {On the Importance of the Civil Service: Z},
  date    = {1981},
}
@book{appleby4,
  author  = {Appleby, Humphrey and Hacker, James and Filler Hame and Zoolley, Bernard},
  title   = {On the Importance of the Civil Service: H},
  date    = {1984},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}
\cite{appleby,appleby2,appleby3,appleby4}
\printbibliography
\end{document}
```
In 3.11
>Appleby, Humphrey, James Hacker, Filler Hame and Bernard Zoolley (1984).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;On the Importance of the Civil Service: H.
>Appleby, Humphrey, James Hacker, Filler Name and Bernard Woolley (1983).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;On the Importance of the Civil Service: W.
>Appleby, Humphrey, James Hacker, Filler Name and Bernard Yoolley (1982).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;On the Importance of the Civil Service: Y.
>Appleby, Humphrey, James Hacker, Filler Name and Bernard Zoolley (1981).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;On the Importance of the Civil Service: Z.

and in 3.12
>Appleby, Humphrey, James Hacker, Filler Name and Bernard Zoolley (1981).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;On the Importance of the Civil Service: Z.
>Appleby, Humphrey, James Hacker, Filler Name and Bernard Yoolley (1982).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;On the Importance of the Civil Service: Y.
>Appleby, Humphrey, James Hacker, Filler Name and Bernard Woolley (1983).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;On the Importance of the Civil Service: W.
>Appleby, Humphrey, James Hacker, Filler Hame and Bernard Zoolley (1984).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;On the Importance of the Civil Service: H.

Maybe `(min|max)sortnames` should be automatically initialised to `(min|max)bibnames` if they have not been set explicitly. Or there should be a separate option to enable them ...

**Comment by plk** [comment]
Yes, I was wondering if it should default to the actual setting of `min/maxbibnames` - that sounds like a better idea.

**Comment by plk** [comment]
Can you try it now? You just need biblatex again, not biber.

**Comment by moewew** [comment]
If I understand correctly this means that `(min|max)sortnames` must always be set *after* `(min|max)bibnames` now. This is not unreasonable, but should be documented. Maybe I can think of a way to avoid this tomorrow, but I assume this would require more machinery, ... not sure if that is worth it.

**Comment by plk** [comment]
Yes, although that's not specific to this issue since `max{cite,bib}names` default to `maxnames` and the order matters there too. This isn't ideal, I agree.

**Comment by moewew** [comment]
Ah yes, that is true. So it is not too bad.

Could you push the changes to `dev` so that SourceForge and GitHub are in sync, please?

**Comment by plk** [comment]
Done.

**Comment by moewew** [comment]
Thank you.

**Comment by moewew** [comment]
Unless I'm mistaken, `\DeclareEntryOption[integer]{maxsortnames}` and `\DeclareEntryOption[integer]{minsortnames}` should be no-ops on the `biblatex` end. Currently they seem to set `(min|max)citanames`
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber, maxcitenames=4, maxbibnames=4, uniquelist=false]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{appleby4,
  author  = {Appleby, Humphrey and Hacker, James and Filler Hame and Zoolley, Bernard},
  title   = {On the Importance of the Civil Service: Z},
  options = {maxsortnames=1},
  date    = {1984},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}
\cite{appleby4}
\printbibliography
\end{document}
```

**Comment by plk** [comment]
Ah yes, please try now.

**Comment by plk** [comment]
Yes, I can't see an easy way to do it either - it will be a pile of ugly conditionals.

**Comment by moewew** [comment]
I guess our best bet is to mention in the documentation that `(min|max)bibnames` sets `(min|max)sortnames` for backwards compatibility reasons and that the `sortnames` must be set after the `bibnames`.
