### ISSUE TITLE
Author disambiguation does not respect {max,min}*names

### ISSUE THREAD

**Issue by CasperVector** [plk/biblatex#756]
As the title:
```
\documentclass{article}
\usepackage[
	style = authoryear, maxnames = 3, minnames = 3,
	maxcitenames = 2, mincitenames = 1
]{biblatex}
\addbibresource{test.bib}

\begin{filecontents}{test.bib}
@book{a,
	author = {A and B and C and D},
	title = {Book I},
	year = {2000},
}
@book{b,
	editor = {A and B and C and E},
	title = {Book II},
	year = {2001},
}
\end{filecontents}

\begin{document}
\parencite{a, b}
\printbibliography
\end{document}
```
produces
```
[Citations]
(A, B, C, and D 2000; A, B, C, and E 2001)
[References]
A, B, C, and D (2000). Book I.
A, B, C, and E, eds. (2001). Book II.
```

**Comment by moewew** [comment]
This is intended behaviour. `biblatex` tries to avoid ambiguous short forms (both entries would come out as "A, B, C et al."). You can turn off this behaviour with `uniquelist=false`, see https://tex.stackexchange.com/q/69028/35864. While you are at it, you may also want to look at `uniquename`: https://tex.stackexchange.com/q/134535/35864. Have a look at the documentation for more in-depth explanation of these features and other values for the options.

**Comment by CasperVector** [comment]
I see; sorry for the disturbance then.

**Comment by moewew** [comment]
No problem. I'd rather see features reported as potential issues than bugs go unnoticed.

**Comment by CasperVector** [comment]
Looks good to me.  Many thanks!

**Comment by moewew** [comment]
Thanks for the quick feedback.
