### ISSUE TITLE
Other scopes for <namepart>inits options?

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#760]
Inspired by https://tex.stackexchange.com/q/435772/35864 I was wondering if it would not make sense to have `giveninits` and friends as entry options and maybe type options.

The `biblatex` side of this is very simple, but I'm not sure what that would mean for Biber. The option is passed on to Biber after all and could influence sorting and `uniquename` I assume.

Sorting seems to be alright, but `uniquename` doesn't quite work even if we set `uniquename` to `full` for these entries.

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber, giveninits=true, uniquename=init]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{appleby,
  author  = {Humphrey Appleby},
  title   = {On the Importance of the Civil Service},
  date    = {1980},
}
@book{appleby:g,
  author  = {Homphrey Ampleby},
  title   = {On the Importance of the Civil Service},
  date    = {1981},
}
@book{bppleby,
  author  = {Humphrey Bippleby},
  title   = {On the Importance of the Civil Service},
  options = {giveninits=false,uniquename=full},
  date    = {1980},
}
@book{bppleby:g,
  author  = {Homphrey Bippleby},
  title   = {On the Importance of the Civil Service},
  options = {giveninits=false,uniquename=full},
  date    = {1981},
}
\end{filecontents}

\DeclareEntryOption[boolean]{giveninits}[true]{%
  \settoggle{abx@bool@giveninits}{#1}}

\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{appleby:g,appleby,bppleby:g,bppleby}
\printbibliography
\end{document}
```

![whyisus](https://user-images.githubusercontent.com/6755835/41199360-b983609e-6c90-11e8-857f-3cc99bfc71b2.png)

**Comment by plk** [comment]
What output would you expect here?

**Comment by moewew** [comment]
I guess I'd have hoped that the two Bippleys would be disambiguated by their full names in citations because I explicitly allowed `uniquename=full`.

Initially I started this issue to discuss whether or not `giveninits` on a per-entry or even per-name option would be viable. Things seemed to work fine on the `biblatex` side, but I was not too sure about Biber and the repercussions for sorting and `uniquename`. So I dragged `uniquename` into this as well.
 
And on second thoughts there are some conceptual issues with this. Should/can Biber track `uniquename` settings per-entry, per-name, ...? What if I happen to have the same author with different `uniquename` settings?  ...

**Comment by plk** [comment]
Right - per-entry is really not viable as `uniquename` is a property relevant only to all names.

**Comment by moewew** [comment]
https://tex.stackexchange.com/q/445514/35864 shows that it can be useful to disable `uniquename` on a per-entry basis. On my machine Biber did not finish calculating `uniquename` and `uniquelist` values for the 3600 names in the `.bib` entry in an acceptable time.

**Comment by plk** [comment]
Yes, please try this with the latest dev versions of biber and biblatex (2.13 and 3.13 respectively). `uniquename` is now possible at namelist and name scope and `uniquelist` is possible at namelist scope.

**Comment by moewew** [comment]
Yup
```
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber, giveninits=true, uniquename=init]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{appleby,
  author  = {Humphrey Appleby},
  title   = {On the Importance of the Civil Service},
  date    = {1980},
}
@book{appleby:g,
  author  = {Homphrey Ampleby},
  title   = {On the Importance of the Civil Service},
  date    = {1981},
}
@book{bppleby,
  author  = {Humphrey Bippleby},
  title   = {On the Importance of the Civil Service},
  options = {giveninits=false,uniquename=full},
  date    = {1980},
}
@book{bppleby:g,
  author  = {Homphrey Bippleby},
  title   = {On the Importance of the Civil Service},
  options = {giveninits=false,uniquename=full},
  date    = {1981},
}
\end{filecontents}

\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{appleby:g,appleby,bppleby:g,bppleby}
\printbibliography
\end{document}
```
works as I hoped it would.

**Comment by plk** [comment]
Sorry, I didn't scroll up - I didn't realise it was you who opened this ...!
