### ISSUE TITLE
Make \ifbibmacroundef available outside of citation command

### ISSUE THREAD

**Issue by maieul** [plk/biblatex#767]
Could it be possible to make \ifbibmacroundef avaiblale outside of citation command? For example, to create package which pahch specific style.

**Comment by moewew** [comment]
That seems like a reasonable request. I'll have a look, it should be possible.

**Comment by moewew** [comment]
This is now implemented with https://github.com/plk/biblatex/commit/34adc2e895ce3c886354378a8ec55913cc5768f6.
