### ISSUE TITLE
Problem with Catalan \smartof

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#770]
Cf. https://github.com/plk/biblatex/pull/769

```latex
\documentclass[catalan]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{aristotle:rhetoric}
\printbibliography
\end{document}
```

gives

![catalssmartofed](https://user-images.githubusercontent.com/6755835/42421671-b04b8254-82d9-11e8-8fd5-ff7117eeeb32.png)

but it should say "d'Edward"

**Comment by moewew** [comment]
In #269 the French smartof was fixed, but the fix was not applied to Catalan. 208871d does this and things seem fine so far.

**Comment by sebasvila** [comment]
@moewew Test seems to show that this fixes the issue. Thanks.
