### ISSUE TITLE
Controversial translation into Polish

### ISSUE THREAD

**Issue by jsbien** [plk/biblatex#771]
`` 
byeditor         = {{wyedytowano}{wyed\adddot}},% FIXME: unsure
``
"Wyed" looks like a mispelled "Wyd.", i.e. "Wydawca" (publisher). To the best of my knowledge neither "wyedytowano" nor "wyed." is actually used in Polish.

I suggest
`` 
byeditor         = {{redaktor}{red\adddot}},% loose translation
``

Thank you very much for your work on BibLaTex!

Regards

Janusz

**Comment by moewew** [comment]
Thanks to https://github.com/plk/biblatex/issues/657 the next version of `biblatex` will have

https://github.com/plk/biblatex/blob/a4d0e9efa2cf16b76b7aebe4c04bbb1e58913fe8/tex/latex/biblatex/lbx/polish.lbx#L104-L105

and

https://github.com/plk/biblatex/blob/a4d0e9efa2cf16b76b7aebe4c04bbb1e58913fe8/tex/latex/biblatex/lbx/polish.lbx#L264

does that look OK for you?

**Comment by moewew** [comment]
Ooops, I just realised that this change has already been released. It was included in version 3.10. The current release is 3.11.

**Comment by jsbien** [comment]
Yes, this is a good solution.

**Comment by moewew** [comment]
Very good. Thank your for confirming that. I'm closing this for now. If you do an update you should already get the new translations.
