### ISSUE TITLE
textnohyphenation and nohyphenation only work paragraph-initially

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#772]
Consider

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}


\begin{document}
regional frantically regional frantically regional frantically regional de frantically  doom

\textnohyphenation{regional frantically regional frantically regional frantically regional de frantically doom}

regional \textnohyphenation{frantically regional frantically regional frantically regional de frantically doom}

\textnohyphenation{regional frantically regional frantically regional frantically regional de frantically} doom

regional \textnohyphenation{frantically regional frantically regional frantically regional de frantically} doom

{\nohyphenation regional frantically regional frantically regional frantically regional de frantically doom}

regional {\nohyphenation frantically regional frantically regional frantically regional de frantically doom}

{\nohyphenation regional frantically regional frantically regional frantically regional de frantically} doom

regional {\nohyphenation frantically regional frantically regional frantically regional de frantically} doom
\end{document}
```

![showtxtsn](https://user-images.githubusercontent.com/6755835/42924010-ab392d6e-8b28-11e8-91b7-964a8a5bf343.png)

`\textnohyphenation` only suppresses the hyphenation effectively if used paragraph-initially. This is no surprise given the definition

https://github.com/plk/biblatex/blob/a4d0e9efa2cf16b76b7aebe4c04bbb1e58913fe8/tex/latex/biblatex/biblatex.sty#L1899-L1903

uses `\lefthyphenmin` which is a paragraph-wide setting.

For single words `\mbox` might be a viable alternative for `\textnohyphenation`, but for text containing white space that might already give subpar results.

From https://tex.stackexchange.com/q/442220/35864

**Comment by svenper** [comment]
FWIW, LuaLaTeX does indeed disable hyphenation (even parts of a single paragraph), but typesets an overfull hbox instead.

![pdf output](https://user-images.githubusercontent.com/15199675/50850372-a0b59e00-1371-11e9-8264-1f4c5239117c.png)

**Comment by moewew** [comment]
Interesting. The overfull hbox is to be expected (and is what pdfLaTeX does as well, if it works): LaTeX usually prefers overfull to underfull lines.

**Comment by moewew** [comment]
A possible solution is at https://github.com/plk/biblatex/pull/890
