### ISSUE TITLE
citereset option does not reset for higher section levels than the specified

### ISSUE THREAD

**Issue by svenper** [plk/biblatex#773]
The `citereset` options should trigger a reset on all `\blx@refpatch@...` commands at that section level *and higher*.

MWE that shows the issue:

```tex
\documentclass{article}
\usepackage[style=authoryear-icomp,citereset=subsection]{biblatex}
\addbibresource{biblatex-examples.bib}
\begin{document}
\section{section 1}
\subsection{subsection 1.1}
\parencite{knuth:ct:a}
\subsection{subsection 1.2}
\parencite{knuth:ct:a}
\section{section 2}
\parencite{knuth:ct:a} (should be reset)
\end{document}
```

![output](https://user-images.githubusercontent.com/15199675/43034010-4ec035d4-8cd4-11e8-996d-ae261bfb5b22.png)

**Comment by moewew** [comment]
Thank you for the report. I can see where you are coming from.

I'll see whether something like `citereset=subsection+` which would reset at `\part`, `\chapter` (if available), `\section` and `\subsection` is possible. I would not want to change the current behaviour of `citereset` because the behaviour is documented and established.

**Comment by moewew** [comment]
A first implementation idea is at https://github.com/plk/biblatex/compare/dev...moewew:persectplus. Testing and comments would be appreciated. You will need Biber 2.12 dev (https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/development/binaries/) to test this.

**Comment by svenper** [comment]
I appreciate the drop-in, thanks. It tests nicely on my end!

My comment would be that `subsubsection`, `paragraph` and `subparagraph` could be included in this function as well, for completeness.

Also somewhat related: some writing styles reset ibid.'s at every paragraph, but since `\par` is not a sectioning command i assume that would be a different problem?

**Comment by moewew** [comment]
Thanks for testing.

Mhhh, theoretically it should be easy to include `\subsubsection`, `\paragraph` and `\subparagraph` (at least for `article.cls` etc.). But I'm wondering whether people really need that. Maybe PL had a reason not to include those sectional headings. Lastly, and that ties in nicely with your last point, `paragraph` may lead people to think that the reset would happen per paragraph (`\par`/empty line paragraph that is), which it won't.

I'd love to have something like `citereset=par`, but I'm not aware of a safe method to execute code at the beginning of each paragraph. See also https://github.com/plk/biblatex/issues/715

**Comment by moewew** [comment]
In `biblatex` 3.12 you can use `citereset=subsection+` to reset the trackers at all sectioning levels of `subsection` or higher.
```
\documentclass{article}
\usepackage[style=authoryear-icomp,citereset=subsection+]{biblatex}
\addbibresource{biblatex-examples.bib}
\begin{document}
\section{section 1}
\subsection{subsection 1.1}
\parencite{knuth:ct:a}
\subsection{subsection 1.2}
\parencite{knuth:ct:a}
\section{section 2}
\parencite{knuth:ct:a} (should be reset)
\end{document}
```

`biblatex` 3.12 has been released and is available in TeX live 2018 and MikTeX as of this morning (UTC).
