### ISSUE TITLE
Capitalized In: vs. in:

### ISSUE THREAD

**Issue by simonreich** [plk/biblatex#776]
Hi,

I am not sure, if this is a bug or feature: It seems that if the last character of the title is capitalized, the following `in:` is not (and vice versa). Since the title is terminated with a `”. `, I would expect `In: ` in both cases.

Any help is appreciated!

Minimal working example:

```tex
\documentclass[]{scrbook}

\usepackage{filecontents}
\begin{filecontents}{literature.bib}
@inproceedings{working,
  author = {Author, A. and Author, B.},
  title = {LASTCHARISNOTCAPITALIZEd},
  pages = {1-12},
  booktitle = {Conference Proceedings},
  organization = {IBBB},
  year = {2018},
  month = {10},
}

@inproceedings{notworking,
  author = {Author, A. and Author, B.},
  title = {LASTCHARISCAPITALIZED},
  pages = {1-12},
  booktitle = {Conference Proceedings},
  organization = {IBBB},
  year = {2018},
  month = {10},
}
\end{filecontents}


\usepackage[]{biblatex}
\bibliography{literature.bib} 

\begin{document}

``In:'' is capitalized: \fullcite{working}

\vspace{2cm}

``in:'' is not capitalized: \fullcite{notworking}

\end{document}
```

Results in:
`“In:” is capitalized: A. Author and B. Author. “LASTCHARISNOTCAPITALIZEd”.
In: Conference Proceedings. IBBB. Oct. 2018, pp. 1–12`

`“in:” is not capitalized: A. Author and B. Author. “LASTCHARISCAPITALIZED”.
in: Conference Proceedings. IBBB. Oct. 2018, pp. 1–12`

My current work around is as follows:
```tex
\renewbibmacro{in:}{%
  \ifentrytype{article}{}{\printtext{In\printunit{\intitlepunct}}}}
```
which will always output `In: `.

**Comment by moewew** [comment]
It is a bug and it is essentially the same as https://github.com/plk/biblatex/issues/295.

One workaround is to add `\@` in the `title` field (or any other field, except for name fields) if it ends in a capital letter.

Another workaround is to use `\frenchspacing`  around the offending `\fullcite`. Note that the bibliography already automatically applies `\frenchspacing`, so the output there is fine.

You can see the same effect for the `IBBB` if you slightly modify the `october` bibstring.

```latex
\documentclass{article}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@inproceedings{working,
  author = {Author, A. and Author, B.},
  title = {NOTCAPITALIZEd},
  pages = {1-12},
  booktitle = {Conference Proceedings},
  organization = {IBBB},
  year = {2018},
  month = {10},
}

@inproceedings{notworking,
  author = {Author, A. and Author, B.},
  title = {CAPITALIZED},
  pages = {1-12},
  booktitle = {Conference Proceedings},
  organization = {IBBB},
  year = {2018},
  month = {10},
}

@inproceedings{fixed,
  author = {Author, A. and Author, B.},
  title = {CAPITALIZED\@},
  pages = {1-12},
  booktitle = {Conference Proceedings},
  organization = {IBBB\@},
  year = {2018},
  month = {10},
}
\end{filecontents}

\usepackage[]{biblatex}
\addbibresource{\jobname.bib} 

\DefineBibliographyStrings{english}{october={oct}}


\begin{document}
\fullcite{working}

\fullcite{notworking}

\fullcite{fixed}

{\frenchspacing
\fullcite{working}

\fullcite{notworking}

\fullcite{fixed}}

\printbibliography
\end{document}
```

**Comment by simonreich** [comment]
Thanks for all the help! If I can be of further assistance, please do not hesitate to contact me. 

I will close this report to keep discussions at one single place at #295.
