### ISSUE TITLE
filename.bbl warning

### ISSUE THREAD

**Issue by ahomansikka** [plk/biblatex#781]
I updated Xubuntu 16.04  LTS to 18.04.1 LTS and no I get a warning

Package biblatex Warning file filename.bbl is in wrong format version - expected 2.9

filename.bbl starts with

% $ biblatex auxiliary file $
% $ biblatex bbl format version 2.6 $
% Do not modify the above lines!

Xubuntu 18.04.1 says I have the latest version of texlive.

**Comment by pauloney** [comment]
Remove the bbl file and run the command again.

Paulo Ney

**Comment by ahomansikka** [comment]
My bad. Updating Xubuntu does not update biber automagically. After updating biber everything works.

**Comment by moewew** [comment]
Just for future reference you may want to keep in mind that the TeX live version from the Ubuntu (and I assume som other Linux distributions) repositories need not be the latest TeX live. In particular Ubuntu's TeX live does not receive the same updates as a vanilla TeX live installed from https://www.tug.org/texlive/ (https://tex.stackexchange.com/q/1092/35864) and is usually frozen at a particular point in time (a few months before the Ubuntu release).

This becomes especially apparent for people on LTS versions, e.g. Ubuntu 16.04 (supported until 2021) ships a version of TeX live 2015 with package updates frozen around March 2016 (see also https://packages.ubuntu.com/search?keywords=texlive).
