### ISSUE TITLE
Mark labelnamepunct as deprecated?

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#782]
Following the discussion in https://chat.stackexchange.com/transcript/message/46303047#46303047 I'm wondering if it would make sense to mark `\labelnamepunct` as deprecated so that people are more inclined to use the context-sensitive `nametitledelim` instead.

**Comment by moewew** [comment]
See https://github.com/plk/biblatex/pull/789

Comments are very welcome.

**Comment by plk** [comment]
Yes, happy to support this.

**Comment by moewew** [comment]
Very well, merged #789.
