### ISSUE TITLE
Abbreviate all journals

### ISSUE THREAD

**Issue by tobiasdiez** [plk/biblatex#795]
I have a bib file in which the journal names are specified in it's full form, e.g. `journaltitle = {Annalen der Physik}` but I want the abbreviated form (e.g, `Ann. Phys.`) to appear in the bibliography. 
I know from a [tex.stackexchange question](https://tex.stackexchange.com/questions/76241/show-journal-abbreviation-in-reference-list-with-biblatex-biber) that I can specify a map to transform the journal to the abbreviated form:
````
\DeclareSourcemap{
  \maps[datatype=bibtex,overwrite=true]{
   \map{
     \step[fieldsource=journaltitle,
           match={Annalen der Physik},
           replace={Ann. Phys.}]
   }
  }
}
````
This is of course tedious to set-up for a larger (and changing) list of references. On the other hand, the JabRef team hosts a [huge collection of journal abbreviations](http://abbrv.jabref.org/journals/). It would be nice if biblatex would support these files and add a package option to globally switch between abbreviated and full form of journals.

**Comment by josephwright** [comment]
I've considered this in the past (you don't need the full set of names, only the keywords plus exceptions), but it gets tedious. Moreover, abbreviation tends to apply to an entire academic field: I'm a chemist, and I never store full journal titles as they are simply not used.

**Comment by moewew** [comment]
I wanted to look into this a couple of months ago, but then decided that it didn't look as if I could get something useful done.

Technically I guess you'd 'only' need http://www.issn.org/services/online-services/access-to-the-ltwa/ and not a journal name database, although the latter might give better results in edge cases.

With the current interface one way to get this done would be to generate the mappings programmatically and feed them to `biblatex` in a separate `.sty` file. I can imagine that working, although I have concerns about performance here: The `.sty` file would be read in each LaTeX run and mappings are written out to the `.bcf` (making it very long).

Another possibility would be to build this into Biber directly. That would avoid carrying around the mappings. But it would require an interface in Biber and a library that takes care of the journal name conversion.

**Comment by tobiasdiez** [comment]
Thanks for your quick responses.

In my opinion, a built-in conversion in biber is preferable due to the performance constraints. In JabRef we used the journal name database because it is relatively simple: you load the abbreviations into a HashTable and then simply perform a hash-based lookup to replace the full journal name by its abbreviation (or the other way around). Usually, this approach has a better performance than a regex-based replacement of known keywords and was easier to implement.

**Comment by moewew** [comment]
I guess that a built-in Biber module is indeed the better option. If you know a Perl programmer who would like to tackle this I'm sure PLK won't mind a bit of help. Otherwise I don't see this very high up the priority list.

**Comment by plk** [comment]
Well, this is not so hard to do but we'd need a database of abbreviations from somewhere, preferably online so we don't maintain it.

**Comment by moewew** [comment]
The JabRef guys already have many lists at http://abbrv.jabref.org/journals/ and there is the List of Title Word Abbreviations for ISO 4 at http://www.issn.org/services/online-services/access-to-the-ltwa/ so the data is there.

**Comment by plk** [comment]
Hmm, ok. The ISSN list would be more general which would indicate that we have an abbreviate option for arbitrary fields. However, I can image this would not be very efficient as it needs a regexp match on individual words against a large hash table. I would have thought that using bibtex string macros and data mapping would be fine for most users.

**Comment by moewew** [comment]
Yes, I'd say performance is the main problem here. The lists are huge (and the ISSN list needs to be processed carefully to avoid wrong replacement for partial words and should probably be language dependent as well).

The disadvantage for user-defined data mapping is that the user would need to set up all possible ISSN replacements manually if they want automatic journal abbreviations. Setting up one RegExp for each cited journal could be a big ask for a large database.

The issue is not particularly pressing since JabRef and other tools can help, though.

**Comment by ElieGouzien** [comment]
Using `jabbrv` and `\DeclareFieldInputHandler` it should be easy.

However, I don't have any idea of how to do it (and i tried several hours), and BibLaTeX's documentation is absolutely useless.
If someone knows how to apply `\JournalTitle{}` from `jabbrv` to all  `journaltitle` fields, it should be a good solution to the issue.

**Comment by moewew** [comment]
What about
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}
\usepackage[style=authoryear, backend=biber]{biblatex}

\usepackage{jabbrv}

\DeclareFieldInputHandler{journaltitle}{%
  \def\NewValue{\JournalTitle{#1}}}

\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{sigfridsson}
\printbibliography
\end{document}
```
----

Suggestions to improve the documentation are very welcome, we all know it is quite the beast, but I feel that the general statement that it is *absolutely useless* goes a bit too far and does not do the incredible hard work that PL and PLK have put into `biblatex` and the documentation justice.

**Comment by ElieGouzien** [comment]
@moewew It perfectly makes the work.
Lot of thanks!

When I have time, I will try at least to add it to doc of `jabbrv`.

------------------------------------------------------

About the documentation, I've certainly been a little excessive (past some hour, I'm sure you can understand), but the documentation of `\DeclareFieldInputHandler` clearly lack the general syntax for using existing value of the field (using `#1` as input is not written).
It might be obvious for BibLaTeX developers, but it's certainly not for the standard user (at least for me).

If I find the time for, I'll try to make a pull request to upgrade the documentation.

**Comment by moewew** [comment]
That's constructive criticism I can work with. How about https://github.com/plk/biblatex/commit/a78e31ed0b33846161e12ce65354cb4bc3a809e6?

**Comment by ElieGouzien** [comment]
@moewew What you added with a78e31e is exactly what was missing. Thanks a lot, I think it will be really useful!

**Comment by ElieGouzien** [comment]
With  compholio/jabbrv#9 closed, this problem might be solved using jabbrv.
