### ISSUE TITLE
Update of finnish.lbx

### ISSUE THREAD

**Issue by ahomansikka** [plk/biblatex#798]
I have updated localisation file finnish.lbx. I added missing translations and fixed typos on old translations. Shound I send the file or just the diff?

**Comment by moewew** [comment]
Thank you very much.

Ideally you would submit a pull request against the `dev` branch. Failing that send the complete `.lbx` to mwemheu@gmail.com. I will then open a pull request and ping you to verify that everything is OK and then we can merge it.

You can test your file by compiling against https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/examples/03-localization-keys.tex with the correct language settings.

**Comment by moewew** [comment]
Oh I forgot. If you translation is not based on the latest version of the file (as found at https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/lbx/finnish.lbx) it would be great if you could have a look at possible conflicts before you submit the file.

**Comment by ahomansikka** [comment]
>  You can test your file by compiling against https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/examples/03-localization-keys.tex with the correct language settings.

I tried with latex and pdflatex. Both say

! Package keyval Error: langhungarian undefined

**Comment by ahomansikka** [comment]
I got it to work when I commented out langhungarian, langlatvian, fromhungarian and fromlatvian.

**Comment by moewew** [comment]
Yeah, these strings are new and if you compile with a release version of `biblatex` (i.e. not one from `dev` here) the strings will be unknown and produce an error.
