### ISSUE TITLE
Estonian dates

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#801]
Cf #800. `estonain.lbx` is ultimately based on `finnish.lbx`. Apparently, in Finnish declension of the month name is crucial for the proper date format. That's why there are two strings for each month (`basicfebruary` and `february`). In `estonain.lbx` these month strings seem to coincide, which would make them (and the additional code handling them) useless. 

Please double-check the output of the following example
```
\documentclass[estonian]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber, mergedate=false, date=short, datecirca=true]{biblatex}
%short, long, terse, comp

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{appleby,
  author  = {Humphrey Appleby},
  title   = {On the Importance of the Civil Service},
  date    = {2018-08-07},
}
@book{bppleby,
  author  = {Humphrey Bppleby},
  title   = {On the Importance of the Civil Service},
  date    = {2018-07-09/2018-07-11},
}
@book{cppleby,
  author  = {Humphrey Cppleby},
  title   = {On the Importance of the Civil Service},
  date    = {2018-06-08/2018-08-09},
}
@book{dppleby,
  author  = {Humphrey Dppleby},
  title   = {On the Importance of the Civil Service},
  date    = {2018-04-03/2019-01-06},
}
@book{eppleby,
  author  = {Humphrey Eppleby},
  title   = {On the Importance of the Civil Service},
  date    = {2018-02},
}
@book{Fppleby,
  author  = {Humphrey Fppleby},
  title   = {On the Importance of the Civil Service},
  date    = {2018~},
}
@book{gppleby,
  author  = {Humphrey Gppleby},
  title   = {On the Importance of the Civil Service},
  date    = {2018-02/2018-05},
}
@book{hppleby,
  author  = {Humphrey Hppleby},
  title   = {On the Importance of the Civil Service},
  date    = {2018-02/2019-05},
}
@book{ippleby,
  author  = {Humphrey Ippleby},
  title   = {On the Importance of the Civil Service},
  date    = {2018/2019},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

For all values of ` date=short`, `long`, `terse`, `comp`.

If anything is wrong, please explain the format of dates in Estonian for me. I would at least need to know the following things. How would you say the date 2018-08-07 in short (like say 7. 8. 2018 in German or 8/7/2018 in American English) and in long form (7. August 2018 or August 7th, 2018 in American)? How would you format long/short date ranges like `2018-07-09/2018-07-11` (e.g. 9.-11. 7. 2018 in short and 9.-11. Juli 2018 in long form), `2018-06-08/2018-08-09`, `2018-04-03/2019-01-06`. Where do you place the BC/AD markers? What about "circa" markers?

**edit** Add more example entries with more dates.

**Comment by kristiank** [comment]
Here's the morphological forms of the months
```latex
january     = {{jaanuar}{jaanuar}},
february    = {{veebruar}{veebruar}},
march       = {{m\"{a}rts}{m\"{a}rts}},
april       = {{aprill}{aprill}},
may         = {{mai}{mai}},
june        = {{juuni}{juuni}},
july        = {{juuli}{juuli}},
august      = {{august}{august}},
september   = {{september}{september}},
october     = {{oktoober}{oktoober}},
november    = {{november}{november}},
december    = {{detsember}{detsember}},

onjanuary   = {{jaanuaril}{jaanuaril}},
onfebruary  = {{veebruaril}{veebruaril}},
onmarch     = {{m\"{a}rtsil}{m\"{a}rtsil}},
onapril     = {{aprillil}{aprillil}},
onmay       = {{mail}{mail}},
onjune      = {{juunil}{juunil}},
onjuly      = {{juulil}{juulil}},
onaugust    = {{augustil}{augustil}},
onseptember = {{septembril}{septembril}},
onoctober   = {{oktoobril}{oktoobril}},
onnovember  = {{novembril}{novembril}},
ondecember  = {{detsembril}{detsembril}},

injanuary   = {{jaanuaris}{jaanuaris}},
infebruary  = {{veebruaris}{veebruaris}},
inmarch     = {{m\"{a}rtsis}{m\"{a}rtsis}},
inapril     = {{aprillis}{aprillis}},
inmay       = {{mais}{mais}},
injune      = {{juunis}{juunis}},
injuly      = {{juulis}{juulis}},
inaugust    = {{augustis}{augustis}},
inseptember = {{septembris}{septembris}},
inoctober   = {{oktoobris}{oktoobris}},
innovember  = {{novembris}{novembris}},
indecember  = {{detsembris}{detsembris}},
```

**Comment by kristiank** [comment]
I would like to learn LaTeX to be able to implement this by myself. It doesn't feel too complicated and there's allready code for the Finnish usecase. Although basically I have tried to include all relevant information here for someone else to do it, if faster than me.

**Comment by moewew** [comment]
Ugh, this is even more complicated than Latvian a few months ago. I'll see what I can come up with.

Unfortunately, there are no learning resources available for the specifics of setting up an `.lbx` file for complicated date handling. There is also little documentation for many of the ad-hoc things that have to happen here. You can have a look at examples like `finish.lbx` and `latvian.lbx` but that is all we have.

**Comment by moewew** [comment]
# `dates=short`

If there is no space in dates such as "01.08.2018" what should be done about line breaking? Is it one inseparable unit? What if the em-dash is added (without spaces or with?) where could things break?

**Comment by moewew** [comment]
# `dates=long`

I can't seem to find the ablative case in the month translations. Are the forms equivalent to another case or do we need translations for these forms as well?

While we are at the topic of the translations. Am I right in thinking `january`: nominative, `onjanuary`: adessive, `injanuary`: inessive. Would it make sense to use the actual names of the grammatical cases instead of prepositions for the bibstrings?

**Comment by kristiank** [comment]
The range would actually need more morphology (two more cases: elative and terminative), so maybe let's don't do that and just use nominative when only month and year is specified in a range. What do you think?

**Comment by kristiank** [comment]
I will do further research on this and try to give you structured examples for each combinations.

**Comment by kristiank** [comment]
Are the formats (short, long, terse and comp) explained somewhere?

**Comment by moewew** [comment]
There is an explanation in the documentation of the `date` option, pp. 52-53 of the manual.

Basically `short` is a short date format - usually all numeric, `long` is a longer format usually with the month name spelled out. Ranges in these two formats are indicated by just putting a range separator between two full dates. `terse` is like `short` with compact ranges, `comp` is like `long` with compact ranges. Compact ranges try to minimise the duplication within a date range.

You can compile the example from above with `american`, `british`, `latvian`, `ngerman` or `dutch` and change the value of the `date` option to see what the formats do.

**Comment by moewew** [comment]
@kristiank Any progress here? We are hoping to release a new version fairly soon (no idea when exactly, we need to address a few things before that and then we need to allow for a bit of external testing and for time to build the Biber binaries, that will probably take at least a week, maybe two) and it would be great if we could get the Estonian dates done for that version. It's not a high priority for me though and it won't block the release, so if we can't get it done now, Estonian dates will have to wait for the release after that.

**Comment by moewew** [comment]
OK. At the moment we are aiming to start the release procedure at the weekend. So if we haven't sorted out the date stuff until then it probably has to wait until the next release.

**Comment by kristiank** [comment]
I'll look into it tonight. Great to hear a new release is coming. Was there anything more lacking in Estonian? I'll try to add the missing translations too, as you pointed out in another thread.

**Comment by moewew** [comment]
Compiling against https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/examples/03-localization-keys.tex does not reveal any missing translations.

http://www.eki.ee/books/ekk09/index.php?p=2&p1=10 suggests there are several ways to write dates in Estonian. If there is no strong preference for one format or the other I would prefer to stick as closely to the status quo of the current output as possible.

**Comment by kristiank** [comment]
### remarks on `dates=terse`
  * [ ] remove space after dots between day-month-year `9.10.2018`
  * [ ] use `Em Dash (U+2014)`
  * [ ] dot instead of `/` when only year and month (dot after month, dot after year)
  * [ ] preferably no linebreaking, if range, then break after Em Dash

**Comment by kristiank** [comment]
### remarks on `dates=long`
  * [ ] use adessive case and append `.a` after year when fully specified date `24. veebruaril 2018. a` (not range)
  * [ ] use nominative case and no `.a` appended otherwise (i.e. when only specified `md` or range)
  * [ ] use `Em Dash (U+2014)` in range
  * [ ] add spaces around the dash in `3. aprill 2018–6. jaanuar 2019.` (space after dash should be more breaking than before dash and those elsewhere)

**Comment by kristiank** [comment]
### remarks on `dates=comp`
  * [x] month in nominative case and no `. a` after year
  * [ ] use `Em Dash (U+2014)` in ranges
  * [ ] add spaces around dash in `3. aprill 2018–6. jaanuar 2019.` (space after dash should be more breaking than before dash and elsewhere)
  * [x] no spaces around dash in `9.–11. juuli 2018.`

**Comment by kristiank** [comment]
The above remarks should be quite close to the status quo, except for:
  * introduce the adessive case (that would justify the code copied from Finnish)
  * remove the `/` that is not justified in Estonian
  * use of `Em Dash` in range (actually `En Dash` could suffice, but Estonian is keen in the distinction between dash and "range dash") 
  * spaces are corrected
  * line breaking mainly after range dash, preferably not after dot
    * also in `long`/`comp` format, don't break after dot but after range dash or month name

**Comment by moewew** [comment]
Is the
> use adessive case and append .a after year when fully specified date *24. veebruaril 2018. a* (not range)

for `long` a must? The fact that this will be given up for date ranges makes things more complicated. (The way date formatting is set up currently the macro printing a date does not know whether it is a range or not, so auxiliary markers would be needed.)

It seems illogical that the whether or not we have a range decides which form for the date we use (but languages are rarely logical).

**Comment by kristiank** [comment]
So by analogy ranges would be `24. veebruaril 2018. a -- 26. veebruaril 2018. a`. (Note the em dash and spaces around it). I think that would be okay.

**Comment by moewew** [comment]
Would it also be OK not to have the "a." and go for "20. aprill 1994" as in http://www.eki.ee/books/ekk09/index.php?p=2&p1=10?

What about month-only dates, are they "veebruaril 2018. a" or "veebruar 2018. a "?

**Comment by moewew** [comment]
About the en-dash/em-dash thing. http://www.eki.ee/books/ekk09/index.php?p=2&p1=10 seems to use en-dashes, Microsoft's Estonian style guide says to use only en-dashes and not em-dashes and in your example you wrote `--` which gives an en-dash (`---` would be an em-dash). Do the dates need em- or en-dashes?

**Comment by kristiank** [comment]
My logic is that the long format would have the month in adessive case, and the case "needs" the `a` appended (it means 'year'). And that then the compact format would use the "case-less" month in nominative.

But okay, for pushing this into the release, we can settle on always having the "20. aprill 1994“ format when months are spelled out with words. And not have the "a" appended.

**Comment by kristiank** [comment]
Sure, let's settle on the en dash. There is no consensus for that, only that dash and range dash should be separate symbols. (The estonian name used for both range dash and another long dash which *is* em dash collide, thats the source for confusion. But en dash is fine for range dash)

**Comment by moewew** [comment]
Unlike for the date formats with "a." I have no (implementation) preference for en- or em-dash, so I'll take what **you** think is more natural and common. I was just confused about your usage of `--` and realised that the link I had used to look up date formats used an en-dash.

**Comment by kristiank** [comment]
I updated the exampled above. I hope it I didn't leave any usecases unanswered.

**Comment by kristiank** [comment]
So let us not change the logic for long and comp for this release. I personally like to see inflected wordforms, but fully spelling out `24. veebruaril 2018. a -- 25. veebruaril 2018. a` kind of looses it purpose when working in a space constrained setting as is bibliography listings. I might look into this in the future if I get time and lust to learn latex and maybe some backing up from the local language institute.

**Comment by kristiank** [comment]
Use en dash. That's also *my* opinion now.

**Comment by moewew** [comment]
Have a look at https://github.com/plk/biblatex/pull/832, please.

**Comment by kristiank** [comment]
Looks good for the coming release. Thank you!

**Comment by kristiank** [comment]
This can be closed now.

**Comment by moewew** [comment]
I'll close the issue along with other addresses issues when 3.12 is released.

**Comment by moewew** [comment]
`biblatex` 3.12 is out now and available in TeX live 2018 and MikTeX. The dates now show as discussed here.

If you think a different date format would be more beneficial, we can discuss this and the possible implementation in a new issue.
