### ISSUE TITLE
Using the same key in multiple \mcites/\defbibentrysets produces warning

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#812]
The following MWE (which is tangentially related to https://tex.stackexchange.com/q/454030/35864, where an unrelated issue is discussed)
```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[mcite=true,backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}
\begin{document}
  \mcite{set1,*sigfridsson,*worman}

  \mcite{set2,*geer,*sigfridsson}

  \printbibliography
\end{document}
```
produces the warning
```
Package biblatex Warning: Biber reported the following issues
(biblatex)                with 'sigfridsson':
(biblatex)                - Field 'entryset' is no longer needed in set member 
entries in Biber - ignoring in entry 'sigfridsson'.
```

Indeed, the mere definition of a set can cause this warning
```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}

\defbibentryset{setA}{sigfridsson,worman}%
\defbibentryset{setB}{geer,sigfridsson}%

\begin{document}
  Lorem
\end{document}
```

**Comment by moewew** [comment]
Admittedly, using the same entry in several sets could give weird results in some places, but it seems benign enough in other situations. The Biber message is particularly cryptic because the user has not used the `entryset` field anywhere.

**Comment by plk** [comment]
This was a small bug - `biber` adds `entryset` to dynamic set members and so if they are in two sets, the second one generates an error because `biber` doesn't require `entryset` manually in the data at all and warns about it. Luckily `biber` distinguishes between fields in the original data and ones it adds during processing so this is fixed now in biber DEV.

**Comment by moewew** [comment]
Works fine so far, thank you.
