### ISSUE TITLE
entrysetcount for children with multiple parents

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#815]
See https://tex.stackexchange.com/q/454219/35864

Consider the following MWE where two sets use the same entries but in a different order
```
\documentclass{article}
\usepackage[utf8]{inputenc} 
\usepackage[T1]{fontenc}    

\usepackage[style=numeric,
    mcite=true,
    subentry,
    backend=biber,
    ]{biblatex}

\usepackage{hyperref}

\addbibresource{biblatex-examples.bib}

\begin{document}        
  This is some nice text I want to cite as a set\mcite{set1,*sigfridsson,*worman}.
  \cite{sigfridsson} and \cite{worman}

  Another set cite\mcite{set2,*worman,*sigfridsson}.
  \cite{sigfridsson} and \cite{worman}

  \printbibliography
\end{document}
```
which produces

> [1] **(a)** Emma Sigfridsson and Ulf Ryde. “Comparison of methods for deriving atomic charges from the electrostatic potential and moments”. In: Journal of Computational Chemistry 19.4 (1998), pp. 377–395. doi: 10.1002/(SICI)1096-987X(199803)19:4<377::AID-JCC1>3.0.CO;2-P; **(a)** Nancy Worman. The Cast of Character. Style in Greek Literature. Austin: University of Texas Press, 2002.
> [2] **(a)** Nancy Worman. The Cast of Character. Style in Greek Literature. Austin: University of Texas Press, 2002; **(b)** Emma Sigfridsson and Ulf Ryde. “Comparison of methods for deriving atomic charges from the electrostatic potential and moments”. In: Journal of Computational Chemistry 19.4 (1998), pp. 377–395. doi: 10.1002/(SICI)1096-987X(199803)19:4<377::AID-JCC1>3.0.CO;2-P.

That is because `entrysetcount` is decided by the last parent-child relationship that was processed in the `.bbl`.

**Comment by moewew** [comment]
One easy solution would be to calculate the `entrysetcount` on the fly when we are within `\blx@entryset`.

```
\def\blx@entryset#1{%
  \blx@ifdata{#1}
    {\blx@entrysetcounter\@ne
     \begingroup
     \blx@imc@clearlist{pageref}%
     \blx@getdata{#1}%
     \edef\abx@field@entrysetcount{\the\blx@entrysetcounter}%
     \blx@setoptions@type\abx@field@entrytype
     \blx@setoptions@entry
     \blx@execute
     \blx@beglangbib
     \blx@begunit
     \blx@anchor
     \blx@entryset@precode
     \blx@driver{\blx@imc@thefield{entrytype}}%
     \blx@entryset@postcode
     \blx@endunit
     \blx@endlangbib
     \endgroup}
    {}%
  \let\do\blx@entryset@i}

\def\blx@entryset@i#1{%
  \blx@ifdata{#1}
    {\advance\blx@entrysetcounter\@ne
     \begingroup
     \blx@resetdata
     \blx@getdata{#1}%
     \edef\abx@field@entrysetcount{\the\blx@entrysetcounter}%
     \blx@setoptions@type\abx@field@entrytype
     \blx@setoptions@entry
     \addtocounter{instcount}\@ne
     \blx@execute
     \blx@beglangbib
     \blx@begunit
     \blx@anchor
     \blx@entryset@precode
     \blx@driver{\blx@imc@thefield{entrytype}}%
     \blx@entryset@postcode
     \blx@endunit
     \blx@endlangbib
     \endgroup}
    {\blx@nounit}}
```

In other situations we would still have to rely on `.bbl`-generated data.

**Comment by plk** [comment]
Hmm, ok - if you want to prepare a merge, I can run the tests.

**Comment by moewew** [comment]
I'll think about this some more to see if there is something more elegant that could be done, but if I find nothing I will prepare a PR.

**Comment by moewew** [comment]
Suggested fix is at https://github.com/plk/biblatex/pull/822
