### ISSUE TITLE
\(auto)cites does not support numeric-comp style

### ISSUE THREAD

**Issue by jiewuza** [plk/biblatex#817]
Here is a MWE
```
\documentclass[british]{article}

\usepackage[sorting=none,backend=biber,autocite=superscript,style=numeric-comp]{biblatex}
\addbibresource{test.bib}

\begin{document}

\autocites{testkey}{testkey2}{testkey3}                     % result: 1,2,3
\autocite{testkey,testkey2,testkey3}                           % result: 1-3

\printbibliography
\end{document}
```

and test.bib:
```
@article{testkey,
author = {Author},
title = {A Test},
journal = {Journal Name},
volume = {44},
number = {5},
pages = {569 - 581},
year = {2018}
}

@article{testkey2,
author = {Author},
title = {A Test},
journal = {Journal Name},
volume = {44},
number = {5},
pages = {569 - 581},
year = {2018}
}

@article{testkey3,
author = {Author},
title = {A Test},
journal = {Journal Name},
volume = {44},
number = {5},
pages = {569 - 581},
year = {2018}
}
```

**Comment by moewew** [comment]
That is expected behaviour. We can't sort across multiple arguments of multi-cite commands like `\autocites` (see https://github.com/plk/biblatex/issues/214, https://tex.stackexchange.com/q/65809/35864) and carrying over the complicated tests of `-comp` styles to the next argument (which is to some extent processed independently of the other arguments) is not trivial.

**Comment by moewew** [comment]
That said, the `authoryear-comp` styles haver rudimentary support also for multicite commands and can compress across arguments, if something like that is possible with little extra work it might be an option here as well. I will investigate, but I can't promise anything and things will still be fundamentally limited by the fact that we can't sort multicites.

**Comment by jiewuza** [comment]
Ok, I see. Thanks.

**Comment by moewew** [comment]
As 
```
\documentclass{article}

\usepackage[sorting=none,backend=biber,style=numeric-comp]{biblatex}
\addbibresource{biblatex-examples.bib}


\makeatletter
\DeclareCiteCommand{\cite}[\mkbibbrackets]
  {\ifnumless{\value{multicitecount}}{2}
     {\usebibmacro{cite:init}%
      \usebibmacro{prenote}}
     {\iffieldundef{prenote}
        {\iffieldundef{postnote}
           {}
           {\usebibmacro{cite:dump}%
            \usebibmacro{cite:init}%
            \setunit{\multicitedelim}}}
        {\usebibmacro{cite:dump}%
         \usebibmacro{cite:init}%
         \setunit{\multicitedelim}%
         \usebibmacro{prenote}}}}
  {\usebibmacro{citeindex}%
   \usebibmacro{cite:comp}}
  {}
  {\ifboolexpr{       test {\ifnumequal{\value{multicitecount}}{\value{multicitetotal}}}
               or not test {\iffieldundef{postnote}}}
     {\usebibmacro{cite:dump}%
      \usebibmacro{postnote}}
     {}}

\DeclareMultiCiteCommand{\cites}[\mkbibbrackets]{\cite}{}
\makeatother


\begin{document}
1 \cites{sigfridsson}{worman}{geer}

2 \cites[380]{sigfridsson}[34]{worman}[12]{geer}

3 \cite[cf.][490]{sigfridsson,worman,geer}

4 \cites{sigfridsson}{geer}

5 \cite{sigfridsson,geer}

6 \autocites{sigfridsson}{worman}{geer}

7 \cites{sigfridsson}[cf][]{geer}{worman}

7a \cites{sigfridsson}{worman}{geer}[cf][]{nussbaum}

7b \cites{sigfridsson}{worman}{geer}[380]{nussbaum}

7c \cites{sigfridsson}{worman}{geer}{nussbaum}

8 \autocite{sigfridsson,worman,geer}

9 \textcites{knuth:ct:a}{knuth:ct:b}{knuth:ct:c}

10 \textcite{knuth:ct:a,knuth:ct:b,knuth:ct:c}

\printbibliography
\end{document}
```
demonstrates it is possible to make `\cites` behave more `comp`-y at the expense of more involved code. At the moment I don't really see that this is a price worth paying: The `comp` feature for `\cites` is fundamentally limited by our inability to sort multicite commands (tracked at https://github.com/plk/biblatex/issues/214) and the possibility to add pre- and postnotes to all citations makes for some delicate edge cases. At the moment my advice would be: If you want fully compressed citations, put all of them in `\cite` and use `\cites` for citations where you want pre- and postnotes for all cited entries. 

For the time being I'm closing this as *won't fix*.

At the moment I doubt this is a highly sought after feature, but I encourage everyone who is interested in this feature to make their voice heard here, so we can gauge the interest. In case many people are looking for this feature despite its expected shortcomings, we can revisit the decision not to act. Regardless of popular demand we should probably look into this again if we can sort multicites.

**Comment by zwz** [comment]
Thank you for your efforts and explanation.
I brought up this feature when I was using this bibstyle (https://github.com/hushidong/biblatex-gb7714-2015, see `Need to do:` in its README) which is quite common for Chinese journal or thesis.
But AFAIK most of Chinese are using bibtex, that is probably why there are few people looking for this feature.

**Comment by jiewuza** [comment]
Thank you for your efforts and explanation.
I brought up this feature when I was using this bibstyle (https://github.com/hushidong/biblatex-gb7714-2015, see Need to do: in its README) which is quite common for Chinese journal or thesis.
But AFAIK most of Chinese are using bibtex, that is probably why there are few people looking for this feature.
