### ISSUE TITLE
Biber warning for missing key

### ISSUE THREAD

**Issue by hvoss49** [plk/biblatex#818]
A bibdata with a missing key:

```
@TechReport{,
  author      = {Bundesgerichtshof},
  title       = {Urteil zu Aktienoptionsprogrammen zugunsten von Aufsichtsräten},
  institution = {Bundesgerichtshof},
  year        = {2004},
}

```

leads to

```
INFO - Found BibTeX data source 'TestBiblatex.bib'
WARN - Invalid or undefined BibTeX entry key in file '/tmp/mk3A05YUTN/TestBiblatex.bib_10281.utf8', skipping ...
ERROR - BibTeX subsystem: /tmp/mk3A05YUTN/TestBiblatex.bib_10281.utf8, line 607, syntax error: found ",", expected one of: number, name (entry type, key, field, or macro name), end of entry ("}" or ")") or quoted string ({...} or "...")
```

is this the intended behaviour that first a warning *and* then an error appears?

**Comment by plk** [comment]
Yes, the error is from the underlying `libbtparse` library and the warning from `biber` which catches these errors and continues (hence it being only a warning).

**Comment by moewew** [comment]
This seems to be a purely Biber-related issue and should therefore probably be logged at https://github.com/plk/biber/issues if it is still relevant. There is not a lot that could be done on the `biblatex` side, so I'm closing this as *invalid* here.

That said I always thought the order of the messages was odd and counter-intuitive. The warning suggests Biber managed to read the entry and then noticed that it has an empty key,  while the later error message seems to suggest a fatal error that aborts the Biber run.
