### ISSUE TITLE
Biblatex 3.8 or Biblatex 3.7 for the dreaded "expected 2.8" issue?

### ISSUE THREAD

**Issue by JoshuaCapel** [plk/biblatex#820]
The wiki here https://github.com/plk/biblatex/wiki/biblatex-and-the-arXiv current says that:
> That means that the .bbl file you upload should be produced by biblatex 3.8/Biber 2.7

So I advised my colleague to download and install biblatex 3.8, but this didn't resolve the "expected 2.8" issue.

After I re-read the wiki I noted that is the previous line says:
> At the moment the arXiv runs biblatex 3.7, which expects .bbl file version 2.8

So after we switched to biblatex 3.7 it worked, so I suspect this first line is a typo.

**Comment by moewew** [comment]
Argh. Yes, thank you very much for spotting this. Corrected in [revision `61d47c7`](https://github.com/plk/biblatex/wiki/biblatex-and-the-arXiv/_compare/2fdf0704570bcbba8b81bf2d7350da9d1fce14a5...61d47c76a74cc8ccbbcfb0abb96390519e42b798). Sorry for the confusion.

**Comment by JoshuaCapel** [comment]
That fine, it was interesting chance to learn more about biber and biblatex.

**Comment by moewew** [comment]
OK, closing this since things should be OK now.
