### ISSUE TITLE
New release is needed (broken Estonian translation)

### ISSUE THREAD

**Issue by AlexDaniel** [plk/biblatex#821]
Last release was on Mar 1 and unfortunately included a syntax error in `estonian.lbx` ([which was fixed later](https://github.com/plk/biblatex/commit/30d925d8b79cf08b96fdead66a31e2af0678bea3#diff-16af56c5dc46222e28d6ee7d5cceb4b6L407)).

More info here: https://github.com/plk/biblatex/pull/790#issuecomment-417842488

> an actual (official and public) release of the package so that downstream users can benefit from the new localisation will take some time and I can give no promise of an ETA at this time. Sorry.

While I understand that it can take some time, I thought I'd create a ticket anyway.

**Comment by moewew** [comment]
We are aware that a new release is needed in the near future. And I'm sorry that it takes so long.

Unfortunately, there are still some issues to sort out before we can release anything. Have a look at https://github.com/plk/biblatex/projects/5 if you want to help. Not everything in the "To Do" column needs to be addressed before we can push out a new release, but we definitely need to clear the "In Progress" queue

**Comment by kristiank** [comment]
Would it be possible to get attribution credits for the Estonian translation? By my name or also by my NGO?

**Comment by kristiank** [comment]
Great. I sympathise with your only-names strategy.

**Comment by moewew** [comment]
`biblatex` 3.12 has been released and is available in MikTeX and TeX live 2018 as of this morning (UTC).
