### ISSUE TITLE
Datetimes. Bibliographic Datetime Format V ISO 8601.

### ISSUE THREAD

**Issue by JohnLukeBentley** [plk/biblatex#831]
@njbart, @plk, @inukshuk, and @moewew.

Have you seen [JohnLukeBentley/open-datetime-standard-bootstrap
/First Draft Uploaded. Does it relate to the ISO standards desirably? #2](https://github.com/JohnLukeBentley/open-datetime-standard-bootstrap/issues/2)? I'm worried that github notifications haven't been getting through to you from that thread; and I'm hoping they might from this thread.

To save you having to read the whole thread. I'm essentially wanting to know if BibliographicDatetimeFormat.pdf (direct download) looks worth developing. It would be better to reply in that thread.

Edit: added link.

**Comment by moewew** [comment]
Can't speak for others, but for me the notifications worked. I just didn't have anything useful to say, so I didn't act on them. I have now replied in https://github.com/JohnLukeBentley/open-datetime-standard-bootstrap/issues/2
