### ISSUE TITLE
Misc entry has both year/date in required an optional fields

### ISSUE THREAD

**Issue by Siedlerchr** [plk/biblatex#833]
Hi,

one JabRef user made us aware of the fact that both the required fields and the optional fields contain the year/date field.  Is this intended?  To me I would think that at least the date/year field should only be in either required or optional fields. 
https://github.com/JabRef/jabref/issues/4388

From the manual: 2.1.1

>Required felds: author/editor, title, year/date
>Optional felds: subtitle, titleaddon, language, howpublished,
>type, version, note, organization, location, date, month, year,
>addendum, pubstate, doi, eprint, eprintclass, eprinttype, url,
>urldate

**Comment by moewew** [comment]
Mhhh, `year`/`date` is apparently so important that it had to be listed twice.

https://github.com/plk/biblatex/blob/3dbc9f12fd2a50156688a858b0dbd3995f89ed1b/tex/latex/biblatex/blx-dm.def#L1369-L1401

shows that `date`/`year` is mandatory, so I'm going to delete them from the optional field list.
 

Thanks for pointing that out.

**Comment by Siedlerchr** [comment]
Yeah we are aware of the 2.3.2 thing, e.g. differentiation between author/editor

**Comment by moewew** [comment]
In particular `biblatex` *usually* displays entries without `date`/`year` fine (but see https://github.com/plk/biblatex/issues/793). The `authoryear` styles (can) even write "n.d." for missing years, so the "required" is more of a *should* in terms of rather than a *must*.

**Comment by Siedlerchr** [comment]
For JabRef it's more an issue of having a list of fields for each entry type and having it either in the required or optional fields - tab. The content is up to the user.

**Comment by moewew** [comment]
Ah, OK if it is only about that, then you should definitely display it in the *required* tab.

**Comment by moewew** [comment]
`biblatex` 3.12 has been released, the documentation has been fixed.
