### ISSUE TITLE
Danish localization, update

### ISSUE THREAD

**Issue by cmondrup** [plk/biblatex#834]
In connection with a Danish language musicology project I've realized that the existing Danish biblatex localization has errors and is incomplete. Hence I've taken the occasion to rework danish.lbx. Before posting my danish version here I've asked for and got comments and proposals from the Danish TeX User group and from a Danish librarian of my acquaintance.

I'm new to github and hope that this is the right place to upload my update 

[danish-localization.zip](https://github.com/plk/biblatex/files/2511366/danish-localization.zip)

**Comment by moewew** [comment]
Thank you very much for your contribution. We are just in the process of releasing a new version of `biblatex`, so chances are this addition will not make it into the next release, it will probably have to wait for the one after that.

I ran your code against https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/examples/03-localization-keys.tex and everything seems fine as far as I can tell. 

There are going to be two new strings `langhungarian` and `fromhungarian` (analogous to all the other `lang...` and `from...` strings), could you tell me their translation as well, please?

Given that your contribution to `danish.lbx` are substantial we can list you in the acknowledgement section in the list of language contributors if you like. Just let us know your name if you want to see it there.

**Comment by plk** [comment]
We have time - feel free to merge to DEV and let me know.

**Comment by moewew** [comment]
OK. That will probably mess up GitHub's release tagging, but I'll merge as soon as the `hungarian` stuff and the acknowledgements are sorted and will let you know.

**Comment by cmondrup** [comment]
Regarding Hungarian:

  langhungarian = {{ungarsk}{ungarsk}},
  fromlanghungarian = {{fra ungarsk}{fra ungarsk}},

I've been reworking danish.lbx thoroughly, thereby looking carefully into the Norwegian (bokmål) localization set. Danish and Norwegian are closely related languages, especially Danish compared to the 'bokmål' branch of Norwegian. The 'nynorsk' Norwegian branch is more different from Danish. I didn't just copy the Norwegian terms, though. In many cases, when I needed to add or adjust existing Danish translations I've chosen other terms for many of the Danish keys.

I think I ought to draw your attention to a number of Danish abbreviated terms. Upon a suggestion from a member of the Danish TeX User Group I doubled the concluding consonant in the plural forms. Examples are:

  page             = {{side}{s\adddot}},
  pages            = {{sider}{ss\adddot}},
  column           = {{spalte}{sp\adddot}},
  columns          = {{spalter}{spp\adddot}},
  line             = {{linje}{l\adddot}},
  lines            = {{linjer}{l\adddot}},
  verse            = {{vers}{v\adddot}},
  verses           = {{vers}{vv\adddot}},
  section          = {{paragraf}{par\adddot}},
  sections         = {{paragraffer}{parr\adddot}},
  paragraph        = {{afsnit}{afsn\adddot}},
  paragraphs       = {{afsnit}{afsnn\adddot}},

The idea origins from a comprehensive Latin-Danish dictionary frequently used in Danish high schools in my youth (I'm born 1947).

In the key set 'Types' I'm missing a key for a 'doctoral thesis'. In Danish university context a 'phdthesis' is on another (less ambitious) level. It's my impression that that may be true for other university contexts like those in Germany (the German term is 'Doktorarbeit') and those in other Scandinavian countries.

I do think that my contribution to danish.lbx is substantial, so it would be OK to list me in the acknowledgement. My name is Christian Mondrup (see https://imslp.org/wiki/Category:Mondrup%2C_Christian).

Which are the steps to 'merge to DEV'

**Comment by moewew** [comment]
@plk I pushed the changes to `dev`. When we release `biblatex` 3.12 can you please make sure that the release tag points to the correct commit? That would probably involve removing the now incorrect tag and pushing it again.

@cmondrup Thank you very much. The changes are at https://github.com/plk/biblatex/commit/5748bd9e23644b6adad0f61d481d5ef80e38b7e3.

Regarding the "doctoral thesis" vs "phd thesis" we are aware that there are cultural and technical differences in the education systems of each country that may not allow a one-to-one translation of all terms. We had a similar issue recently with German (https://github.com/plk/biblatex/issues/774). I don't think we can cater for all educational systems. If people think that the automatically generated string does not do the work justice they can override the `type` of a `@thesis` (or `@phdthesis`) manually. I don't think it would benefit a lot of users if we introduced a new, predefined `doctoralthesis` string, for most people it would probably only add confusion.

Regarding the Norwegian localisation I'm afraid I don't quite understand what you are getting at. Do you mean that you want to submit a correction for those files as well? We are of course always happy with language contributions, but it would be appreciated if things could be cleared with a native speaker beforehand as we have no way to evaluate the merits of suggestions.

Regarding the abbreviations I am again not entirely sure what you are getting at. In the diff I can see that you changed the behaviour from single-letter plurals to double-letter plurals. This is going to be a visible change in document output for a lot of users. Ideally of course this is something that should be avoided, but for localisations the assumption has always been that we are sort of fine with small changes and if this has been thought through and cleared with experts in the field I'm fine with it.

**Comment by plk** [comment]
@moewew - all done and re-uploaded to SF

**Comment by cmondrup** [comment]
> Regarding the Norwegian localisation I'm afraid I don't quite understand what you are getting at. Do you mean that you want to submit a correction for those files as well? We are of course always happy with language contributions, but it would be appreciated if things could be cleared with a native speaker beforehand as we have no way to evaluate the merits of suggestions.

I realize that I've expressed myself clumsily. I just tried to explain that I had a close look at norsk.lbx becuse 1) it's almost complete and 2) my Danish mother tongue is very close to Norwegian. I do **not** intend to suggest any changes to the Norwegian translations.

**Comment by cmondrup** [comment]
Unfortunately there's a bug in my Danish localization:

  langlatvian      = {{litauisk}{litauisk}},
  fromlatvian      = {{fra litauisk}{fra litauisk}},

which should be corrected to

  langlatvian      = {{litauisk}{lettisk}},
  langlatvian      = {{lettisk}{lettisk}},

see the attached update

[danish-localization.zip](https://github.com/plk/biblatex/files/2514154/danish-localization.zip)

Thereby I became aware that the Lithuanian language is missing in the key set:

%  langlithuanian   = {{litauisk}{litauisk}},
%  fromlithuanian   = {{fra litauisk}{fra litauisk}},

Several other languages are also missing, some of the wide spread: Japanese is on the list but Chinese is not. Other 'large' languages like Arabian and Turkish are also missing. That's true as well for not so large European languages like Albanian and Belarusian, and probably numerous other 'large' languages.

**Comment by moewew** [comment]
I assume `fromlatvian` should be
```
fromlatvian      = {{fra lettisk}{fra lettisk}},
```
is that right?

Yes, we don't have keys for all languages. We have keys for all supported languages (i.e. for all languages for which we have an `.lbx` file) and a handful others (I can currently think of only two: Latin, I assume because PL thought that would be useful, and Japanese, not sure why - I think it was added because someone insisted).

**Comment by cmondrup** [comment]
> I assume `fromlatvian` should be
> 
> ```
> fromlatvian      = {{fra lettisk}{fra lettisk}},
> ```
> 
> is that right?

Yes it is

**Comment by moewew** [comment]
@cmondrup OK, correction pushed to dev as https://github.com/plk/biblatex/commit/be3f19276f58ca7a6894358fda1ca2bf54ee0f1b.

@plk I pushed a correction to `dev`, can you please upload a new version to SF and retag.

**Comment by moewew** [comment]
`biblatex` 3.12 includes the changes to `danish.lbx` as discussed here. It has been released and is available in TeX live 2018 and MikTeX now.
