### ISSUE TITLE
Mention and link style documentations in main doc

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#838]
The style documentations explain style-specific options and are often hard to find for new users.

The main documentation should make it more obvious that they exist and that they are a valuable source of information when it comes to style-specific options.

Maybe the style documentations could be moved from to a dedicated folder instead of `examples`, since they are more than just examples...

**Comment by dbitouze** [comment]
> Maybe the style documentations could be moved from to a dedicated folder instead of `examples`, since they are more than just examples...

I fully agree. 

What about a dedicated chapter for that in the main `biblatex`'s documentation? You argued:

> Style options like `mergedate` and friends are documented in the style documentation [...] and not in the main `biblatex` documentation, where only `biblatex`'s own options are documented.

but `mergedate` option could (has to?) be specified as a `\usepackage{biblatex}` option: 
```
\usepackage[style=authoryear, mergedate=basic, backend=biber]{biblatex}
```

and, for the end user, it is rather transparent it is a style and not a core option.

**Comment by moewew** [comment]
A first attempt at documenting style options can be found in https://github.com/plk/biblatex/compare/dev...moewew:styledoc Comments would be very much appreciated.

Initially I would have rejected the argument that it is transparent for a user whether an option is a style option or a package option, since the same is true for options of contributed styles. But since the documentation already documents the style options `isbn`, `doi`, `url` and `eprint` I think it makes sense to have everything at one place, plus almost no one knows the style examples.

**Comment by dbitouze** [comment]
Quite nice, thanks! 

Just one remark: I would tend to put local and external link on the same level and, hence, would define `\seestyleexample` as follows (`\to` could be replaced by, e.g., `:`):

```latex
\newcommand*{\seestyleexample}[1]{%
  \leavevmode
  \marginpar{%
    \raggedright
    \footnotesize
    style example $\to$\\
    \href{file:examples/#1.pdf}{local} or
    \href{https://www.ctan.org/tex-archive/macros/latex/contrib/biblatex/doc/examples/#1.pdf}
    {online}}%
  \ignorespaces}
```
