### ISSUE TITLE
Documentation typo in Labels section

### ISSUE THREAD

**Issue by gusbrs** [plk/biblatex#840]
In the Labels section (section 4.4.5), while describing the `\field`'s options, one of them is the option `names`. The example box, currently lying between pages 200-201, reads:

> name=3 -> Use first 3 names in the name list
> name={2-3} -> Use second and thirds names only
> name={-3} -> Same as 1-3
> etc

That is, "name" in the singular, rather than the option `names`.

**Comment by plk** [comment]
Fixed in 3.13 DEV.
