### ISSUE TITLE
Change announcements

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#842]
In absence of a better notification system, this issue is reserved for **change and release announcements as well as requests for comments on larger changes with potential impact on contributed styles**. The idea is that people can subscribe to the notifications here to keep up to date with significant developments.

Comments are locked to make sure the notifications are low-frequency and avoid the risk of accidental/unwanted 'spamming'. If there is the need to discuss anything, just open a new issue (or comment on the linked issue/pull request, if appropriate.)

**Comment by moewew** [comment]
`biblatex` 3.13/Biber 2.13 are on their way to release.

There is one nominally breaking change that should not affect too many (hopefully no) end users and package authors:
* Per-entry options must now be defined with `\DeclareEntryOption` or the new `\DeclareBiblatexOption` (see below), previously it was possible to use other undocumented internal commands to emulate what the `biblatex` core did.

Among the other more exciting changes are
* The addition of `\DeclareBiblatexOption` as a convenient interface to declare options at multiple levels at once.
* And the application of that command for many standard options to make them available in more contexts. Style authors should feel encouraged to see if their styles can benefit from the new option levels and explore whether their styles can also offer certain options at more levels.
* The entry type `@software` has been promoted to a standard type in the documentation. This has no influence on the output, but should encourage people to use that type in the future.
* The entry type `@dataset` was added. Since no existing driver met the requirements, there is a new dedicated driver for this type. Style authors may want to check out if they want to add a new driver for this entry type instead of heaving it fall back to `@misc`.
* Post- and prenote delimiters are now context sensitive.
* A few customisation options have been added for `\volcite` macros.
* URLs can now be typeset with some additional stretchable space to aid line breaking.
* `@online` entries finally support DOIs.
* The `journaltitle` is typeset with `\isdot`.

Other than that there are small changes to internals, bug fixes and a
few new features.

As always Changes of a technical nature can be found in CHANGES.md <https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES.md>, higher-level changes in the changelog section at the end of the PDF documentation The complete set of changes from 3.12 can be found at <https://github.com/plk/biblatex/compare/v3.12...dev?diff=split&name=dev&w=1>.

Testing would be appreciated. Urgent bugs can (hopefully) be fixed before the release.

**Comment by moewew** [comment]
Due to https://github.com/plk/biblatex/issues/917 there is going to be an emergency bugfix release soon.

Testing to find any other last-minute bugs in 3.13 would be appreciated.

**Comment by moewew** [comment]
The binaries for Biber 2.14 are being built as we speak, so `biblatex` 3.14 is going to be released soon.

The release improves support for `polyglossia` (`polyglossia` version 1.45 or above needed) and adjusts a small detail in sorting to properly support the new version of `biblatex-apa`.

As always, it will need a few days (possibly weeks) until `biblatex` 3.14 actually hits CTAN since we have to wait until all Biber binaries are built. In the meantime testing would be extremely appreciated.

All changes to 3.13a can be found at https://github.com/plk/biblatex/compare/v3.13a...v3.14?diff=split&w=1

**Comment by plk** [comment]
Reference versions of multiscript supporting biblatex 4.0 and biber 4.0 have been uploaded to Sourceforge in the "experimental" folders. This was a huge amount (months) of effort, I have to say, but without a reference version to play with, it is very difficult to get traction on this. There will be bugs and API changes, without a doubt. These versions pass all regression tests cleanly with the current test documents for biblatex and so I don't expect too many backwards compat issues. I have updated the wiki with some outstanding issues. There is a new test doc which is commented (98-multiscript-biber.tex) which shows some usage (needs improvement) and the main documentation PDF should have all the information for all the new moving parts - for an overview, there is a main "Multiscript" section.

The experimental version is slower than the current release and this is unlikely to change fundamentally as multiscript support effectively introduces mutiplicitly at the most basic data layer. Perhaps there will be some tuning to be done however.

**Comment by moewew** [comment]
Some possible changes to the standard styles are up to discussion at https://github.com/plk/biblatex/pull/1000. Input from style authors and interested users would be highly appreciated.

**Comment by moewew** [comment]
`biblatex` 3.15 and Biber 2.15 are on their way to release. Most Biber binaries have already been built, but it may take a few days until everything is finalised an uploaded.

The most interesting changes in `biblatex` 3.15 are 
* Unification of DOI, eprint and URL printing across all drivers <https://github.com/plk/biblatex/issues/981>, <https://github.com/plk/biblatex/pull/1000>.
* Inclusion of `eid` for more entry types <https://github.com/plk/biblatex/issues/847>, <https://github.com/plk/biblatex/pull/1000>.
* New fields `issuetitleaddon` and `journaltitleaddon` <https://github.com/plk/biblatex/issues/996>, <https://github.com/plk/biblatex/pull/1000>.
* A new definition of the `in:` bibmacro tries to avoid undesirable punctuation clashes <https://github.com/plk/biblatex/issues/943>, <https://github.com/plk/biblatex/pull/944>.
* `numeric-comp`'s citation handling was revamped completely. This may result in breaking changes for those who patched into internal macros of that style <https://github.com/plk/biblatex/issues/900>, <https://github.com/plk/biblatex/pull/963>. This change comes with a new `subentrycomp` option as well as some new punctuation commands like `\multiciterangedelim` for easier customisability.
* Case changing macros are now based on `expl3`'s `l3text` if available. This also allows for much saner case protection if desired (`bibtexcaseprotection=false,`).

Other than that there are a few bug fixes and small code enhancements as well as some new lower-level features (file loading hooks).

As always Changes of a technical nature can be found in CHANGES.md <https://github.com/plk/biblatex/blob/master/doc/latex/biblatex/CHANGES.md>, higher-level changes in the changelog section at the end of the PDF documentation The complete set of changes from 3.14 can be found at <https://github.com/plk/biblatex/compare/v3.14...v3.15?diff=split&w=1>. A list of style-related changes that may be easier to digest is at <https://github.com/plk/biblatex/wiki/Changes-to-the-standard-styles> (lower-level code changes that may also affect [style] output are not listed there).

Testing would be appreciated. Urgent bugs can (hopefully) be fixed before the release.

**Comment by moewew** [comment]
`biblatex` 3.16 and Biber 2.16 were released on 2020-12-31.

This was mostly a bugfix release with only a few interesting changes for style developers and end users.
* `\printbibliography` now has a `label` option to issue a `\label` after the heading (https://github.com/plk/biblatex/issues/1036).
* It is now possible to use `\assignrefcontextentries` with named refcontexts.
* `\mkrelatedstring` is now deprecated in favour of `\mkrelatedstringtext` (https://github.com/plk/biblatex/issues/1057),
* `\mainlang` is deprecated and `\textmainlang` should be used instead (https://github.com/plk/biblatex/issues/1057).


As always Changes of a technical nature can be found in CHANGES.md <https://github.com/plk/biblatex/blob/master/doc/latex/biblatex/CHANGES.md>, higher-level changes in the changelog section at the end of the PDF documentation The complete set of changes from 3.14 can be found at <https://github.com/plk/biblatex/compare/v3.15a...v3.16?diff=split&w=1>. A list of style-related changes that may be easier to digest is at <https://github.com/plk/biblatex/wiki/Changes-to-the-standard-styles> (lower-level code changes that may also affect [style] output are not listed there).

**Comment by moewew** [comment]
`biblatex` v3.17 and Biber v2.17 are currently being made ready for release

The releases include a number of smaller changes, the most interesting additions for end users are probably the Romanian (https://github.com/plk/biblatex/issues/1083) and Marathi (https://github.com/plk/biblatex/pull/1060) localisations. Another localisation-related feature is the introduction of bibstring sets (https://github.com/plk/biblatex/pull/1028, https://github.com/plk/biblatex/issues/899, https://github.com/plk/biblatex/issues/555) which allow additional formatting to apply to certain sets of strings in a certain language (this can be used to italicise Latin terms in French, for example).

Possibly critical changes include
* changes to `@xdata` list inheritance (https://github.com/plk/biber/issues/387)
* removal of list support for the first mandatory argument of `\DeclareDelimFormat` (https://github.com/plk/biblatex/pull/1161)
* changes to the code written to auxiliary files (https://github.com/plk/biblatex/issues/1116)
* generalisation of `season` to `yeardivision` (https://github.com/plk/biblatex/issues/1127)

As always Changes of a technical nature can be found in CHANGES.md <https://github.com/plk/biblatex/blob/master/doc/latex/biblatex/CHANGES.md>, higher-level changes in the changelog section at the end of the PDF documentation The complete set of changes from 3.16 can be found at <https://github.com/plk/biblatex/compare/v3.16...v3.17?diff=split&w=1>. A list of style-related changes that may be easier to digest is at <https://github.com/plk/biblatex/wiki/Changes-to-the-standard-styles> (lower-level code changes that may also affect [style] output are not listed there).
