### ISSUE TITLE
Mention polyglossia issues in the docs?

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#845]
Cf. https://tex.stackexchange.com/q/464281/35864

- Should the documentation explain more prominently that language variant detection won't work with `polyglossia`?
- Should `biblatex` issue a warning when `polyglossia` is used to warn users about this even though many won't care about variants?

**Comment by moewew** [comment]
Given the current state of affairs I think it makes sense to not only comment on the issue shortly in the docs, but also to issue a warning when `biblatex` is loaded with `polyglossia`. I stopped short of recommending `babel` directly.

Comments would be welcome, the suggested changes are at https://github.com/plk/biblatex/compare/dev...moewew:polyglosswarndoc

**Comment by moewew** [comment]
Note that `csquotes` dropped the `polyglossia` warning. https://github.com/josephwright/csquotes/issues/4

**Comment by moewew** [comment]
@plk What do you think about the changes in https://github.com/plk/biblatex/compare/dev...moewew:polyglosswarndoc?

I decided to make `biblatex` issue a warning when `polyglossia` is loaded because the variant detection issue can have unintended consequences (for German the output would adhere to pre-1996 orthography and could therefore be seen as 'wrong', especially if the rest of the text follows the new rules - fortunately, there are only very few differences between `german` and `ngerman` at the moment, but that need not be the case in the future; it could also cause issues for the date format in English variants if one is not careful, since `biblatex` will use American style mm/dd/yyyy, but the rest of the document might not). Usually not a lot of people read warnings and some of those who read the warning and decide that it does not apply to them want it gone (cf. https://github.com/josephwright/csquotes/issues/4 or https://github.com/plk/biblatex/issues/451), but I still think it is useful in this case.

Ping back to https://github.com/plk/biblatex/issues/69.

**Comment by plk** [comment]
I think this is fine - I never did get to the bottom of that problem, I believe it needed some changes in `polyglossia` but then `babel` started to pick up steam again and so there was less impetus to fix it ...

**Comment by moewew** [comment]
Very well, merged the changes in https://github.com/moewew/biblatex/commit/78c41fdfd5dfab73baaaf4de7603913a8594780c. We will see how many people complain.

As far as I can see the main problem is that `polyglossia` keeps all the language variant/property information to itself and does not expose it in a way that is usable from the outside. Our problem specifically is that we need to map `polyglossia` languages+properties to '`babel`-equivalent' language names. There is no interface for that. In a rush of hubris I thought it might actually be possible to come up with something useful (on the `polyglossia` side) a while ago (https://github.com/reutenauer/polyglossia/compare/master...moewew:bblnames), but there were problems with situations where even `polyglossia` would not remember its own variant settings (https://github.com/reutenauer/polyglossia/issues/205), plus `polyglossia` development seems to have stalled, so I didn't try to see if this really could go anywhere. Given that `babel` development got going even in areas where it was considered inferior to `polyglossia` I left it at that. For most languages that `biblatex` supports there is little reason to choose `polyglossia` over `babel` even now and hopefully in the future `babel` will catch up with `polyglossia` even for languages where it is trailing at the moment (I assume RTL languages).

**Comment by moewew** [comment]
Slightly bad timing to bring this out now, when `polyglossia` development seems to be picking up steam again, but currently the fundamental issue remains, so the warning has its uses.
