### ISSUE TITLE
Inappropriate capitalization of the initial after a period abbreviating journals 

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#851]
The following MCE points out that, after a period abbreviating a journal, the initial which follows is upper case. This is inappropriate IMHO and is rather new (unfortunately, it's not easy to proceed to a `git bisect` because of the dependance `biblatex`/`biber`).
```latex
\documentclass{article}
\usepackage{csquotes}
\usepackage[style=authoryear]{biblatex}%
\usepackage{filecontents}
%
\begin{filecontents}{\jobname.bib}
@Article{author2000a,
 title = {A Nice Title},
 author = {Uthor, Albert},
 journal = {Can. J. Math.},
 pages = {1-100},
 date = {2000}
}
@Article{author2000b,
 title = {A Nice Title},
 author = {Uthor, Albert},
 journal = {Canadian Journal of Mathematics},
 pages = {1-100},
 date = {2000}
}
\end{filecontents}
\addbibresource{\jobname.bib}
%
\nocite{*}
%
\begin{document}
\printbibliography
\end{document}
```
![test](https://user-images.githubusercontent.com/1032633/50394813-317c5f00-0760-11e9-9df2-74515be52358.png)

**Comment by moewew** [comment]
See https://tex.stackexchange.com/q/170547/35864. The format for `journaltitle` has not changed in the last years (at all?), so I doubt this is a recent phenomenon.

Anyway, I think it makes sense to make
```
\DeclareFieldFormat{journaltitle}{\mkbibemph{#1\isdot}}
```
the default.

**Comment by dbitouze** [comment]
It does the trick, thanks!

**Comment by moewew** [comment]
Great!

Please don't close the issue, I would like to keep it open as a reminder and hub for discussion, whether or not `\isdot` should be the default in the `journaltitle` format.

**Comment by moewew** [comment]
@plk  What do you think? Should we make
```latex
\DeclareFieldFormat{journaltitle}{\mkbibemph{#1\isdot}}
```
the default? I can't think of a situation where one would want the `.` in the `journal(title)` field to be interpreted as a full stop/period, chances are ~high~ almost 100% a `.` is an abbreviation dot (`J. Am. Chem. Soc.` for example).

As a small aside, I don't understand why
```latex
\DeclareFieldFormat{note}{#1\isdot}
```
for example has an `\isdot`. I have also never understood the logic behind
```latex
\DeclareFieldFormat{title}{\mkbibemph{#1}}
\DeclareFieldFormat
  [article,inbook,incollection,inproceedings,patent,thesis,unpublished]
  {title}{\mkbibquote{#1\isdot}}
\DeclareFieldFormat
  [suppbook,suppcollection,suppperiodical]
  {title}{#1}
```

**Comment by plk** [comment]
Agreed - these look like strange inconsistencies and many styles override them anyway. I'll change the test docs if this impacts anything. Will be interesting to see what changes, if anything.

**Comment by moewew** [comment]
Pushed the changes for `journaltitle` at https://github.com/plk/biblatex/commit/9ca6128bcc1969c41955aa6067dc046f6dbdb48e. I'm not touching the other inconsistencies for now.

**Comment by plk** [comment]
Tests seem ok - there were some minor kerning differences but nothing related to this change I think - this is normal with texlive updates over the year  as I'm testing at a low-level with PDF comparisons.

**Comment by moewew** [comment]
`biblatex` 3.13 with the change was released yesterday. The MWE now gives sensible output without additional code.

People who don't like the added `\isdot` can go back to the old behaviour with
```latex
\DeclareFieldFormat{journaltitle}{\mkbibemph{#1}}
```
