### ISSUE TITLE
labelprefix for BibTeX?

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#852]
Cf. https://tex.stackexchange.com/q/467774/35864 and https://tex.stackexchange.com/q/317394/35864

BibTeX does not really support `refcontext`s properly. Since `labelprefix` lives in `refcontext`s now that means that `labelprefix` is essentially unusable with BibTeX.

See
```
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=numeric, backend=bibtex, defernumbers]{biblatex}

\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{sigfridsson,nussbaum,geer}
\newrefcontext[labelprefix=A]
\printbibliography[type=article]
\newrefcontext[labelprefix=B]
\printbibliography[type=book]
\newrefcontext[labelprefix=T]
\printbibliography[type=thesis]
\end{document}
```

Would it be possible to have BibTeX support `refcontext`s at least to some degree? That would mean processing the same entries multiple times. Is that possible?

Alternatively, can we just enable (a less powerful) `labelprefix` for BibTeX? (I did a bit of digging and this should be possible. We could hard-reset all `refcontext`s to the global one and track the `labelprefix` externally with the `.aux` file.)

**Comment by josephwright** [comment]
I think the work here would be massive, even if it's possible. To get BibTeX to process entries multiple times, we'd have to manage all of the data ourselves between runs in the stack: BibTeX itself just gives us a simple 'work through all entries' function.

**Comment by moewew** [comment]
I see that would hardly be worth it, I guess. I was thinking it might be possible to implement several refcontexts similarly to how several refsections are implemented, but I haven't thought that through.

I'll probably just see if there is a cheap way to rescue `labelprefix` for BibTeX and we'll leave it at that.

**Comment by josephwright** [comment]
@moewew Aren't refsections done using multiple `.aux` files? That's not really doable for contexts, I suspect.

**Comment by moewew** [comment]
Yup. As I understand it `refcontext`s have all the data from the current section but with different sorting, labelprefix etc. setting, if we could 'clone' the `.aux` file that might work. But as I said, I haven't really thought it through...

**Comment by moewew** [comment]
`biblatex` 3.13 with the changes is out now. The BibTeX-`labelprefix` emulation doesn't quite produce the same result as Biber's `labelprefix`. In particular the user probably wants to set `resetnumbers` manually.
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=numeric, backend=bibtex, defernumbers]{biblatex}

\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{sigfridsson,nussbaum,geer}
\newrefcontext[labelprefix=A]
\printbibliography[type=article, resetnumbers]
\newrefcontext[labelprefix=B]
\printbibliography[type=book, resetnumbers]
\newrefcontext[labelprefix=T]
\printbibliography[type=thesis, resetnumbers]
\end{document}
```

As it turns out, it was trivial to get the same automatic `resetnumbers` feature going for BibTeX's `labelprefix` as for Biber's, so that will be done in 3.14 - something to look forward to.
