### ISSUE TITLE
No XML output from biber

### ISSUE THREAD

**Issue by sayahna** [plk/biblatex#854]
System: **Linux Mint 19** 
**TeXLive 2018**
Test file: **50-style-authoryear.tex** from biblatex's example bundle;

With following command to generate xml output:

   `biber --output-format=bblxml 50-style-authoryear`

triggered the following error. No output was produced. The system's Perl5 libraries have IO::String module installed which is not read unfortunately. If this String.pm is copied to appropriate folder in /tmp/par-637672/cache-c69.../inc/lib/, it works ok. But this is weird. Is there any way out?

**Error Log**

```
 INFO - This is Biber 2.10
 INFO - Logfile is '50-style-authoryear.blg'
 ERROR - Error loading data source package 'Biber::Output::bblxml': 
 Can't locate IO/String.pm in @INC 
 (you may need to install the IO::String module) 
 (@INC contains: /tmp/par-637672/cache-c69eefcf7af45c44dec592684a863c8f49910910/inc/lib 
 /tmp/par-637672/cache-c69eefcf7af45c44dec592684a863c8f49910910/inc 
 CODE(0x2006640) CODE(0x2006838)) 
 at /tmp/par-637672/cache-c69eefcf7af45c44dec592684a863c8f49910910/inc/lib/Biber/Output/bblxml.pm line 14.
 BEGIN failed--compilation aborted at /tmp/par-637672/cache-c69eefcf7af45c44dec592684a863c8f49910910/inc/lib/Biber/Output/bblxml.pm line 14.
 Compilation failed in require at (eval 353) line 1.
 INFO - ERRORS: 1
```

**Comment by moewew** [comment]
This should actually be logged over at the Biber bugtracker: https://github.com/plk/biber/issues.

I moved this over to https://github.com/plk/biber/issues/245, please continue the discussion there. I will close this report here.
