### ISSUE TITLE
 @suppbook should but is not treated as an alias for @inbook

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#858]
In `biblatex`'s documentation, the `@suppbook` entry type is said to be treated by the standard styles as an alias for `@inbook`:

> [...] The standard styles will treat this entry type as an alias for @inbook.

But this seems to not be the case in fact, as shown by the following MCE:

```latex
\documentclass{article}
\usepackage{biblatex}
\usepackage{filecontents}

\begin{filecontents}{\jobname.bib}
@book{book,
  author    = {Author},
  title     = {Booktitle},
  subtitle  = {Booksubtitle},
  publisher = {Publisher},
  location  = {Location},
  date      = {1995},
}
@inbook{inbook,
  crossref  = {book},
  title     = {InTitle},
  author    = {InAuthor},
  pages     = {5--25},
}
@supbook{supbook,
  crossref  = {book},
  title     = {SupTitle},
  author    = {SupAuthor},
  pages     = {250--300},
}
\end{filecontents}

\addbibresource{\jobname.bib}
\begin{document}
\textcite{inbook,supbook}
\printbibliography
\end{document}
```

which leads to:
```
References
[1] Author. Booktitle. Booksubtitle. Location: Publisher, 1995.
[2] InAuthor. “InTitle”. In: Author. Booktitle. Booksubtitle. Location: Publisher, 1995, pp. 5–25.
[3] SupAuthor. SupTitle. Booksubtitle. Location, 1995.
```

with, certainly, the warning:

>Package biblatex Warning: No driver for entry type 'supbook'.
(biblatex)                Using fallback driver on input line 42.

**Comment by moewew** [comment]
There is a small typo in your MWE. The MWE has `@supbook`, but the type is called `@suppbook` (with two `p`s). If I change to `@suppbook` the output is much closer to `@inbook`.

There is one difference though, `@inbook`s have titles in quotation marks, the title of `@suppbook` is plain without additional formatting. That should probably be fixed in the docs.

**Comment by dbitouze** [comment]
Sigh... sorry for the noise.

**Comment by moewew** [comment]
In the light of https://tex.stackexchange.com/q/268553/35864 there is https://github.com/plk/biblatex/commit/d4f6169d1c6bf00b855caa1c5e0ada9233c98bcb now that should hopefully clarify the exact status of the 'alias' that is referred to in the quoted paragraph. That should help explain the difference one sees in

> [2] InAuthor. “InTitle”. In: Author. Booktitle. Booksubtitle. Location: Publisher, 1995, pp. 5–25.
> [3] SupAuthor. SupTitle. In: Author. Booktitle. Booksubtitle. Location: Publisher, 1995, pp. 250–300.

i.e. that the titles of `@in{collection,book}` are in quotation marks, but those of `@supp{collection,book}` are not.
