### ISSUE TITLE
\DeclareFieldFormat doesn't work in phdthesis

### ISSUE THREAD

**Issue by TeXtnik** [plk/biblatex#862]
I have modified the `title` field to format it as a link to the `url` (or `doi`, ....) of the entry. 

```latex
\newbibmacro{string+doiurljstor}[1]{%
  \iffieldundef{doi}{%
    \iffieldundef{url}{%
      \iffieldundef{googlebid}{%
        \iffieldundef{jstor}{%
          \iffieldundef{arxiv}{%
            #1%
          }{%
            \href{http://arxiv.org/abs/\thefield{arxiv}}{#1}%
          }%
        }{%
          \href{http://www.jstor.org/stable/\thefield{jstor}}{#1}%
        }%
      }{%
        \href{http://books.google.com/books?id=\thefield{googlebid}}{#1}%
      }%
    }{%
      \href{\thefield{url}}{#1}%
    }%
  }{%
    \href{http://dx.doi.org/\thefield{doi}}{#1}%
  }%
}

\DeclareFieldFormat{title}{\usebibmacro{string+doiurljstor}{\mkbibemph{#1}}}
\DeclareFieldFormat[article,incollection,inproceedings,unpublished,inbook,thesis]{title}%
    {\usebibmacro{string+doiurljstor}{\mkbibquote{#1}}}

```

I realize that I had to incluide `thesis` in the `\DeclareFieldFormat` call. If I use `phdthesis`  it doesn't work.
It seems that `\DeclareFieldFormat`  doesn't support the alias entry types. Is this a bug or an known feature?

**Comment by moewew** [comment]
This is expected behaviour. §2.1.2 *Type Aliases* of the documentation says ([`biblatex.tex`, ll. 595-616](https://github.com/plk/biblatex/blob/6a70596af8f014b46f382f989ad2071c5604d855/doc/latex/biblatex/biblatex.tex#L595-L616))
>  These aliases are resolved by the backend as the data is processed. Bibliography styles will see the entry type the alias points to, not the alias name.

So `@phdthesis` being a hard alias for `@thesis` will not work here, because `biblatex` only gets to see `@thesis`.

**Comment by TeXtnik** [comment]
Thanks.
