### ISSUE TITLE
Semi-manual postnote handling

### ISSUE THREAD

**Issue by gusbrs** [plk/biblatex#870]
`biblatex` can take care automatically of postnotes in most regular cases, and provides structure for when this automatism does not produce the desired results, in the form of the macros `\pno`, `\ppno` and `\nopp`. This allows one to fully manually specify the postnote.

However, there are still cases in which one has to resort to these macros, because one wants something else besides the pages in the postnote, which could be less manual. This is specially relevant when using `\mkcomprange`, because then the pages in the range will have to be supplied also manually, that is as compressed (and if one changes range compression settings later on, this will have to be corrected manually, case by case). Besides, one also have to take care in choosing between `\pno` and `\ppno` (granted, not difficult), and the tie, and so on.

But a mid-ground between fully automatic and fully manual could go a long way in streamlining these issues. Suppose a macro `\pnpg` (for "postnote page") be provided, mimicking the `postnote` formatting directive (I use comprange here, because it makes things more interesting):

```
\newrobustcmd*{\pnpg}[1]{\mkcomprange[{\mkpageprefix[pagination]}]{#1}}
```

With it, we could have a postnote `[\pnpg{334-356}, passim]` which would produce expected results. Plus, a single macro could handle all page and page range input in a standardized way, which would also follow results of automatically handled postnotes.

I'm not sure how this could (or if it should) be connected to the `postnote` formatting directive. I also don't know if any recursion issues may be of concern, as the macros involved are running over themselves. But I tested this satisfactorily in a simple document below. Still, even if this naive implementation is somehow problematic, some interface in this direction would be welcome, I think.

```
\documentclass{article}

\usepackage[style=authoryear]{biblatex}

\addbibresource{biblatex-examples.bib}

\DeclareFieldFormat{postnote}{\mkcomprange[{\mkpageprefix[pagination]}]{#1}}

% stands for 'postnote pages'
\newrobustcmd*{\pnpg}[1]{\mkcomprange[{\mkpageprefix[pagination]}]{#1}}

\begin{document}

% trivial case
\autocite[3333-3345]{sigfridsson}

% comp works with other text alongside
\autocite[3333-3345, passim]{sigfridsson}

% comp no longer works with \ppno
\autocite[\ppno~3333-3345, passim]{sigfridsson}

% one could do it manually
\autocite[\ppno~3333-45, passim]{sigfridsson}

% or
\autocite[\ppno~\mkcomprange{3333-3345}, passim]{sigfridsson}

% but nicer, still, would be a semi-manual method
\autocite[\pnpg{3333-3345}, passim]{sigfridsson}

% better yet, a single 'semi-manual' interface, allows for standardized page and
% page ranges input, which will conform to other numbers-only postnotes
\autocite[\pnpg{3333}, passim]{sigfridsson}

\autocite[\pnpg{3333-3345, 3896}, passim]{sigfridsson}

\end{document}
```

Side-note: Both dash normalization and the case `\autocite[3333-3345, passim]{sigfridsson}` above suggest that the sentence "If it fails as well, the postnote is printed as is." in section 3.14.3 of the manual is no longer completely accurate (it may be accurate enough, though).

**Comment by moewew** [comment]
What about
```
\newrobustcmd*{\pnpg}{\printtext[postnote]}
```
That should be safe at least as long as `\pnpg` itself fails the `\ifpages` test.

To the side-note. As far as I can tell the quoted passage describes the usual (=default) behaviour of the `biblatex` standard styles where we have
```
\DeclareFieldFormat{postnote}{\mkpageprefix[pagination][\mknormrange]{#1}}
```
With that setting `\autocite[3333-3345, passim]{sigfridsson}` comes out as '(Sigfridsson and Ryde 1998, 3333–3345, passim)', i.e. without 'p.'/'pp.'.

The behaviour we are seeing in your MWE is slightly different because 
```
\DeclareFieldFormat{postnote}{\mkcomprange[{\mkpageprefix[pagination]}]{#1}}
```
actually first splits the postnote at `,` and `;` and then applies the compression separately on each bit: Naturally that goes through for the numeric-only `3333-3345` but fails (or rather, does nothing) for `passim`. In a last step 'pp.'/'p.' is not added because the resulting string is not a page number. If you had used the starred form `\mkcomprange*[{\mkpageprefix[pagination]}]{#1}` where the post-processor is applied to each split it individually you would have gotten another result (to fully appreciate that, you may want to test something like `333-3345, 4983-4986, 5632, passim`).

**Comment by moewew** [comment]
Implemented in https://github.com/plk/biblatex/commit/e111e83d92edbb4b80ab8747d83a79d2bd4158e2

```latex
\documentclass{article}

\usepackage[style=authoryear]{biblatex}

\addbibresource{biblatex-examples.bib}

\begin{document}
\autocite[3333-3345]{sigfridsson}

\autocite[3333-3345, passim]{sigfridsson}

\autocite[\ppno~3333-3345, passim]{sigfridsson}

\autocite[\ppno~3333-45, passim]{sigfridsson}

\autocite[\ppno~\mkcomprange{3333-3345}, passim]{sigfridsson}

\autocite[\pnfmt{3333-3345}, passim]{sigfridsson}

\autocite[\pnfmt{3333}, passim]{sigfridsson}

\autocite[\pnfmt{3333-3345, 3896}, passim]{sigfridsson}

\autocite[\pnfmt{3333-3345, 3896}]{sigfridsson}

\autocite[\pnfmt{378-381, 383} and more]{sigfridsson}
\end{document}
```

---

For *passim* I wouldn't even use `\pnfmt`. Instead I would define a dedicated command (the bibstring `passim` already exists).
```latex
\documentclass{article}

\usepackage[style=authoryear]{biblatex}

\addbibresource{biblatex-examples.bib}

\newrobustcmd*{\passim}{\addcomma\space\bibstring{passim}}
\NumCheckSetup{\def\passim{}}

\begin{document}
\autocite[3333-3345]{sigfridsson}

\autocite[3333\passim]{sigfridsson}

\autocite[3333-3345\passim]{sigfridsson}

\autocite[\ppno~3333-3345\passim]{sigfridsson}

\autocite[\ppno~3333-45\passim]{sigfridsson}

\autocite[\ppno~\mkcomprange{3333-3345} \passim]{sigfridsson}
\end{document}
```

**Comment by gusbrs** [comment]
@moewew Very nice! Thank you very much.

As to `\passim` that is a good idea for the case. Besides, I was not acquainted with `\NumCheckSetup`, that's a nice little tool. But, first "passim" was meant as just an obvious example for a more general situation (I know you know that) and second, it doesn't seem to go all the way to suffice to substitute for `\pnfmt` (I liked the name, btw).

The difference in result here shows it:

```
\usepackage[style=authoryear]{biblatex}

\addbibresource{biblatex-examples.bib}

\newrobustcmd*{\passim}{\addcomma\space\bibstring{passim}}
\NumCheckSetup{\def\passim{}}

\DeclareFieldFormat{postnote}{\mkcomprange[{\mkpageprefix[pagination]}]{#1}}

\protected\def\pnfmt{\printtext[postnote]}%

\begin{document}

\autocite[3333-3345\passim]{sigfridsson}

\autocite[\pnfmt{3333-3345}\passim]{sigfridsson}

\end{document}
```

**Comment by moewew** [comment]
`biblatex` 3.13 with `\pnfmt` was released yesterday.
