### ISSUE TITLE
\ifentrytype does not match aliases

### ISSUE THREAD

**Issue by CarlOrff** [plk/biblatex#873]
The `\ifentrytype` check does not match type aliases. This looks peculiar to me. Is it desired behaviour?

```latex
\documentclass{article}
\begin{filecontents*}{\jobname.bib}
@BOOK{book:2019,
  title = {Book title},
  date = {2019},
}
@ALIAS{alias:2019,
  title = {Alias title},
  date = {2019},
}
\end{filecontents*}
\usepackage[style=authoryear]{biblatex}
\addbibresource{\jobname.bib}
\DeclareBibliographyAlias{alias}{book}
\AtEveryBibitem{\ifentrytype{book}{TRUE: }{FALSE: }}
\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

**Comment by moewew** [comment]
This is known (and let's say desired) behaviour. See also https://github.com/plk/biblatex/issues/858, https://github.com/plk/biblatex/issues/862 and https://tex.stackexchange.com/q/268553/35864. https://github.com/plk/biblatex/commit/d4f6169d1c6bf00b855caa1c5e0ada9233c98bcb attempts to clarify the behaviour of the different alias solutions, it is a recent addition to the docs and has not made it to the release yet.

**Comment by moewew** [comment]
@CarlOrff Did the explanation above clarify things? Is there something left to document or something that could be improved in the current wordings of the docs? Or is there a feature request that we could formulate based on the current behaviour?

**Comment by moewew** [comment]
Closing this for now for lack of feedback. The mentioned documentation changes for the next release should hopefully clarify the situation enough.

If there is a feature request to be made here or the documentation needs additional improvement, please comment and we can reopen.
