### ISSUE TITLE
Errors about missing }

### ISSUE THREAD

**Issue by krrk** [plk/biblatex#874]
With the latest version on CTAN and from github I'm getting the following errors from xelatex:

```latex
! Extra }, or forgotten \endgroup.
<argument> ...er \blx@nameparser \blx@thedata {}&}
                                                  \blx@endunit 
l.16 ^^I\printbibliography[heading=none]

?
! Missing } inserted.
<inserted text>
                }
l.16 ^^I\printbibliography[heading=none]

?
! Extra }, or forgotten \endgroup.
<argument> ...er \blx@nameparser \blx@thedata {}&}
                                                  \blx@endunit
l.16 ^^I\printbibliography[heading=none]

?
! Missing } inserted.
<inserted text>
                }
l.16 ^^I\printbibliography[heading=none]

?
[2])

! LaTeX Error: \begin{refsection} on input line 11 ended by \end{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.145 \end{document}
```

In my tex file I have the following refsection:
```latex
\begin{refsection}
	\nocite{Rahmanseresht2015}
	\nocite{Assylbekov2012}
	\nocite{Abe2011}

	\printbibliography[heading=none]
\end{refsection}
```

and in the class I'm using ([Awesome-CV with biblatex](https://github.com/aminmkhan/Awesome-CV.git)) biblatex is included as follows:

```latex
\begin{refsection}
	\nocite{Rahmanseresht2015}
	\nocite{Assylbekov2012}
	\nocite{Abe2011}

	\printbibliography[heading=none]
\end{refsection}
```

I've tracked this down to this section of `biblatex.sty` at line 4337 but I have no idea if the problem is here or how to fix it.

```latex
\def\blx@printnames#1#2#3#4{%
  \blx@imc@ifnameundef{#4}
    {\blx@nounit}
    {\blx@getformat\blx@thewrapperformat{nwd}{#1}{#4}%
     \ifdefvoid\blx@thewrapperformat
       {\blx@nounit}
       {\blx@getformat\blx@theformat{nfd}{#1}{#4}%
        \ifdefvoid\blx@theformat
          {\blx@nounit}
          {\blx@begunit
           \blx@namesetup{#2}{#3}{#4}%
           \blx@thewrapperformat{\expandafter\blx@nameparser\blx@thedata{}&}%
           \blx@endunit}}}}
```

**Comment by moewew** [comment]
@krrk Thank you for you report. Unfortunately, I failed to reproduce an issue with the information provided so far. I downloaded the `feature/publications-biblatex` branch (https://github.com/aminmkhan/Awesome-CV/tree/feature/publications-biblatex) of the linked CV template and managed to run the example CV included there successfully except for one error message unrelated to `biblatex` (`! Package keyvalue Error: Unknown option 'vargreek-shape' for package unicode-math-xetex.`).

Would it be possible to show us a *complete*, yet small example that reproduces the problem that you see on your end? In the TeX world this is often called an MWE, see for example https://texfaq.org/FAQ-minxampl, http://www.minimalbeispiel.de/mini-en.html, https://tex.meta.stackexchange.com/q/228/35864.

- In particular the MWE should be a complete TeX document starting with `\documentclass` and with a proper `\begin{document}...\end{document}` document environment.
- Ideally you would try to reproduce the issue with one of the standard classes (`article`) and not with a heavily customised class whose exact version is not on CTAN. If you must use `awesome-cv`, please link to the *exact* version you used and try to remove as much unnecessary stuff from the `.tex` file. If you have made alterations to the `.cls` file, please explain them.
- If you need `.bib` entries to reproduce your issue, please include them as well. You can use the example entries from `biblatex-examples.bib`, they are available on all systems with `biblatex`.
- Make sure the example is *minimal* and actually reproduces the *exact same* error you reported at the beginning.

Please see also items 2 to 6 in https://github.com/plk/biblatex/issues/872#issuecomment-465203228.

I guess it would make sense to add something like this to CONTRIBUTING.md. But as a user I always find CONTRIBUTING.md a bit intimidating, so I tried to avoid it thus far...

**Comment by krrk** [comment]
@moewew Thanks for your reply and sorry for not including a MWE as I was in a bit overwhelmed by the error yesterday. I've hacked together an MWE. I believe the reason you couldn't reproduce the error was because I slightly modified the awesome-cv.cls and my bibentry has over 100 authors. I completely forgot that I took the more difficult path of modifying the class rather than simplifying the bibitem. Anyway here is a MWE [example.zip](https://github.com/plk/biblatex/files/2920560/example.zip).

The code that produces the error is 

```latex
\DeclareNameFormat{author}{%
  \renewcommand*{\multinamedelim}{\addcomma\addspace}%
  \nameparts{#1}%
  \ifthenelse{\value{listcount}=1}
    {\ifblank{\namepartgiven}{}{\namepartgiven\space}%
    \namepartfamily}%
    {\ifblank{\namepartgiven}{}{\namepartgiven\space}%
    \namepartfamily}%
  \ifthenelse{\value{listcount}<\value{liststop}}
  {\addcomma\space}
  {}
  \ifthenelse{\value{listcount}=\value{liststop}}
  {\ifmorenames{\andothersdelim\bibstring{andothers}}}
  {}
}
```

This will not throw an error unless the bibitem has many authors. This code was copied from awesome-cv.cls and I added the last three lines. Without those last three lines the error doesn't occur.

```latex
  \ifthenelse{\value{listcount}=\value{liststop}}
  {\ifmorenames{\andothersdelim\bibstring{andothers}}}
  {}
```

**Comment by krrk** [comment]
I forgot to mention this was working without any errors before I updated texlive2018 so whatever version of biblatex texlive2018 had originally didn't have this issue.

**Comment by moewew** [comment]
Thanks for the MWE.

There is a syntax error in the `\ifmorenames` lines in
```latex
\DeclareNameFormat{author}{%
  \renewcommand*{\multinamedelim}{\addcomma\addspace}%
  \nameparts{#1}%
  \ifthenelse{\value{listcount}=1}
    {\ifblank{\namepartgiven}{}{\namepartgiven\space}%
    \namepartfamily}%
    {\ifblank{\namepartgiven}{}{\namepartgiven\space}%
    \namepartfamily}%
  \ifthenelse{\value{listcount}<\value{liststop}}
  {\addcomma\space}
  {}
  \ifthenelse{\value{listcount}=\value{liststop}}
  {\ifmorenames{\andothersdelim\bibstring{andothers}}}
  {}
}
```

The correct syntax for `\ifmorenames` is

```latex
\ifmorenames
  {<true code>}
  {<false code>}
```
but the code only has `\ifmorenames{<true code>}` and is missing the `{<false code>}` argument. Earlier the code would grab whatever was coming next and pretend that was the `{<false code>}`. But the recent introduction of the wrapper format mean that an additional brace level was added, which makes it harder for TeX to grab something meaningful here. Hence the error.

With
```latex
\DeclareNameFormat{author}{%
  \renewcommand*{\multinamedelim}{\addcomma\addspace}%
  \nameparts{#1}%
  \ifthenelse{\value{listcount}=1}
    {\ifblank{\namepartgiven}{}{\namepartgiven\space}%
    \namepartfamily}%
    {\ifblank{\namepartgiven}{}{\namepartgiven\space}%
    \namepartfamily}%
  \ifthenelse{\value{listcount}<\value{liststop}}
  {\addcomma\space}
  {}
  \ifthenelse{\value{listcount}=\value{liststop}}
  {\ifmorenames{\andothersdelim\bibstring{andothers}}{}}
  {}
}
```
the error is gone.

Note that the code should be using `\ifdefvoid` instead of `\ifblank` and is also otherwise quite a crude approximation of the hard work that the original format does. The definition could also cause spurious spaces due to missing `%`s at the end of lines.

**Comment by krrk** [comment]
Thanks very much for the thorough explanation and I apologize for the noise. I'm not sure what all the reasons for this code are, but I did eliminate one line that sets up the font size, shape and color. I thought the purpose of re-implementing the function was just for that reason. The beginning of that function is shown below with the extra line in there.

```latex
\RequirePackage{xcolor}

\definecolor{darktext}{HTML}{414141}

\DeclareNameFormat{author}{%
  \fontsize{9.4pt}{1em}\bodyfont\upshape\color{darktext}%
  \renewcommand*{\multinamedelim}{\addcomma\addspace}%
```

**Comment by moewew** [comment]
Don't worry about the noise, I'd much rather have a few false positives reported here than real bugs go unnoticed (and this issue is a pretty nice example of how tricky 'wrong syntax' can be in LaTeX, so thank you for that). Please just include a usable MWE from the start with your next report.

---

Yes, in the original `awesome-cv` code there were some font changes involved that my two-line suggestion would not pull off. Nowadays one could use `\DeclareNameWrapperFormat` for that, but that is a recent addition that probably was not available back when the code was devised.

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage[svgnames]{xcolor}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}


\DeclareDelimAlias{finalnamedelim}{multinamedelim}
\DeclareNameAlias{sortname}{given-family}
\DeclareNameWrapperFormat{sortname}{\color{DeepPink}#1}

\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{sigfridsson}
\printbibliography
\end{document}
```

But even back then the `author` field format was quite destructive, something along the lines of
```latex
\DeclareNameFormat{col:family-given}{%
  \color{DeepPink}%
  \ifgiveninits
    {\usebibmacro{name:family-given}
      {\namepartfamily}
      {\namepartgiveni}
      {\namepartprefix}
      {\namepartsuffix}}
    {\usebibmacro{name:family-given}
      {\namepartfamily}
      {\namepartgiven}
      {\namepartprefix}
      {\namepartsuffix}}%
  \usebibmacro{name:andothers}}

\DeclareNameAlias{sortname}{col:family-given}
```
might have been longer, but much safer (cite someone with a 'von' or 'Jr.' part in their name) and more compatible with other standard idioms to control the output.

I should mention that the other `biblatex`-related code in the template is in parts similarly crude and incompatible with `biblatex` standard idioms.
