### ISSUE TITLE
`<option>' undefined in families `blx@opt@typ'

### ISSUE THREAD

**Issue by pcdi** [plk/biblatex#875]
If I try ```\ExecuteBibliographyOptions[book]{eprint=true}``` as per §[3.2.2](http://mirror.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf#subsubsection.3.2.2), I get ```! Package keyval Error: eprint undefined.``` or ```Package xkeyval Error: `eprint' undefined in families `blx@opt@typ'.```

However,
> [**3.1.2.2 Style-specific**](http://mirror.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf#paragraph.3.1.2.2) […] Technically, they are preamble options like those in §[3.1.2.1.](http://mirror.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf#paragraph.3.1.2.1)

so I think ```eprint``` and the other style-specific options mentioned in the documentation should be included in ```blx@opt@typ``` to also behave the same way as the general options.

**Comment by moewew** [comment]
In light of https://github.com/plk/biblatex/pull/866 that would make sense.

The only issue would be if there are custom styles that already say `\DeclareTypeOption[boolean]{eprint}{...}`, because that would clash with our new definitions. A short search in the custom styles installed on my system showed no problematic definition, so we can probably go ahead.

M(n)WE
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\ExecuteBibliographyOptions[book]{eprint=false}

\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{baez/online,wilde}
\printbibliography
\end{document}

```

**Comment by moewew** [comment]
See https://github.com/plk/biblatex/compare/dev...moewew:styleopts. Currently the branch contains those options that were straightforward.

It wasn't quite clear to me what should happen to `dashed` implementation-wise and output-wise, so I left it as is for the moment. Same for the citation tracking options `citepages`, `ibidpage`, `strict` and `pageref`.

**Comment by moewew** [comment]
https://github.com/plk/biblatex/pull/877 has been merged. Most style options that make sense in non-global scope should be available per-type and per-entry in the next `biblatex` release.

**Comment by moewew** [comment]
`biblatex` 3.13 was released yesterday, many options are now available on a per-type and per-entry level. If you are still missing an option on a certain level, please open a new issue, so it can be discussed.
