### ISSUE TITLE
Can the parentheses () be included in the entry key now？

### ISSUE THREAD

**Issue by hushidong** [plk/biblatex#876]
can the parentheses () be included in the entry key now？

A error was reported by @YLXDXX (see https://github.com/hushidong/biblatex-gb7714-2015/issues/50), when the parentheses () appear in the bibtexkey of the entry, an error was raised by biber like:

```
INFO - This is Biber 2.12
INFO - Logfile is 'egtest.blg'
INFO - Reading 'egtest.bcf'
INFO - Using all citekeys in bib section 0
INFO - Processing section 0
INFO - Looking for bibtex format file 'egtest.bib' for section 0
INFO - LaTeX decoding ...
INFO - Found BibTeX data source 'egtest.bib'
WARN - BibTeX subsystem: C:\Users\ADMINI~1\AppData\Local\Temp\CQM6OZvJS8\egtest.
bib_2912.utf8, line 6, warning: "(" in strange place -- should get a syntax erro
r
ERROR - BibTeX subsystem: C:\Users\ADMINI~1\AppData\Local\Temp\CQM6OZvJS8\egtest
.bib_2912.utf8, line 6, syntax error: found "(", expected ","
INFO - WARNINGS: 1
INFO - ERRORS: 1
```

I tested it in texlive 2018 with biblatex 3.12, and got the same error. MWE IS:
```
\documentclass{article}
    \usepackage{ctex}
    \usepackage{xcolor}
    \usepackage{hyperref}
    \usepackage[top=10pt,bottom=10pt,left=1cm,right=1cm]{geometry}

\usepackage[backend=biber,style=numeric]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}

@misc{Euclidean_geometry(hi),
howpublished = {https://zh.wikipedia.org/wiki/abc},
title = {Euclidean geometry},
}

\end{filecontents}
    \addbibresource{\jobname.bib}
    %
    \begin{document}
\nocite{*}
    \printbibliography
    \end{document} 
```

 I read biblatex.pdf and can not find the intruction about the entrykey should not contain a parenthesis. 

but I found the same report in issue: (plk/biblatex#165), this error is induced by the bibtex parser lib.

Though the () were rarely contained in the key, it is really be an error for some cases, so I want to know is there any measures to solve this problem now?

**Comment by moewew** [comment]
I'm not aware of any recent changes in that regard and I see it as unlikely that any changes would happen there. As you mention, this is a documented limitation of the underlying  `btparse` library that Biber uses to read `.bib` entries. See https://metacpan.org/pod/distribution/Text-BibTeX/btparse/doc/btparse.pod under *name*. AFAIK the library is maintained at https://github.com/ambs/Text-BibTeX/issues so you could open an issue there and ask for a change, but I doubt it is going to be done.

There is nothing on the `biblatex` or Biber side that could be done about that, sorry. The only thing we may have to consider is documentation: But even that is tricky, while the piece of information is useful I don't know where in the `biblatex` documentation it should be mentioned.

**Comment by hushidong** [comment]
ok,thanks！

**Comment by moewew** [comment]
https://github.com/plk/biblatex/commit/a8b7bc7ceac182e4c509d1b596fc6a4cb1e38c21 adds a short note in the documentation about this. I couldn't find a good place for it and I doubt it will be easy to find where it is now. But at least we have something now and can point people there if need be and maybe those who are lucky and try the right search terms can find it themselves.
