### ISSUE TITLE
Revised Danish localization

### ISSUE THREAD

**Issue by cmondrup** [plk/biblatex#879]
I suppose I need to open a new issue since the one I opened in 2018 is now closed.

Upon several comments on my Danish localizations I've prepared a revision. The most important change is the plural forms of many abbreviations. In the current version several plural forms were derived from their corresponding singular form by doubling its final consonant. In the revision I've replaced the double consonants with single consonants.  An example is

editor           = {{redakt\o r}{red\adddot}},
editors          = {{redakt\o rer}{redd\adddot}}, 
->
editor           = {{redakt\o r}{red\adddot}},
editors          = {{redakt\o rer}{red\adddot}},

You may see the revised Danish localization in use in my recently published Danish translation of  a modern edition of the thematic catalogue of the composer Georg Gerson. I published the initial edition in German. See [Verzeichnis meiner Compositionen](https://imslp.org/wiki/Verzeichnis_%C3%BCber_200_meiner_Compositionen_(Gerson%2C_Georg))

[danish-localization.zip](https://github.com/plk/biblatex/files/3026945/danish-localization.zip)

**Comment by moewew** [comment]
Thank you very much for your contribution.

Please have a look at https://github.com/plk/biblatex/commit/b37417295ef52184677453dee6c6d4f2d4507403. I changed two small things for the commit:

1. The `å` in `nodate` was replaced with `\aa` to ensure that the document contains only ASCII chars
    ```latex
    nodate           = {{uden årstal}{u.å\adddot}},
    ```
    ```latex
    nodate           = {{uden \aa rstal}{u.\aa\adddot}},
    ```
2. Removed an unnecessary pair of braces around `\o` in `continuator`/`continuators`
    ```latex
    continuator      = {{videref{\o}rer}{videref\adddot}},
    continuators     = {{videref{\o}rere}{videref\adddot}},
    ````
    ````latex
    continuator      = {{videref\o rer}{videref\adddot}},
    continuators     = {{videref\o rere}{videref\adddot}},
    ````

Hope that is OK.

Thank you for opening a new issue. Usually we close issues after the version that handles/resolves them has been released, so #834 was closed after the release of v3.12 in November 2018.

**Comment by cmondrup** [comment]
Of course I agree with the changes.

**Comment by moewew** [comment]
Thank you very much. `biblatex` 3.13 with the changes is available now on CTAN
