### ISSUE TITLE
Page range in Latvian

### ISSUE THREAD

**Issue by vveckaln** [plk/biblatex#882]
Page ranges in Latvian instead of 

lpp. N1\textendashN2

should be displayed as 

N1.\textendashN2. lpp. 

Mind the dot after N1.

See https://tex.stackexchange.com/questions/484179/fix-display-of-page-range-in-bibliography-using-a-babel-language

**Comment by moewew** [comment]
Thanks for reporting this. Note that currently the output is actually

> `lpp. N1\textemdash N2`

i.e. with the longer em-dash and not an en-dash. Indeed, the default range separator in Latvian is set to an em-dash. Should that change globally or only for page ranges?


Are there any other fields where Latvian needs an inverted order of ordinal and string? What about `Volume 5`?

What should the following MWE produce? Is there anything wrong except the page numbers?
```latex
\documentclass[latvian]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@inbook{appleby,
  author  = {Humphrey Appleby},
  title   = {On the Importance of the Civil Service},
  date    = {1980},
  booktitle = {Important Things},
  volume    = {5},
  chapter   = {7},
  pages     = {233-249},
}
\end{filecontents}

\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{appleby,sigfridsson,matuz:doody,coleridge,baez/online}
\printbibliography
\end{document}
``` 

@rhssk Hope it's OK that I ping you. Any comments on this?

**Comment by vveckaln** [comment]
> Sējums 5

 should be 

> 5. sējums

> Nod. 7

should be

> 7. nod.

> lpp. 233-249

should be 

> 233.-249. lpp.

I mention the en dash because it should not be `-` but longer. Could the user be given control if he has chosen to use en dash in the rest of the document in other ranges instead of em dash?

**Comment by moewew** [comment]
OK, so we'll have to copy over all the stuff from the Hungarian localisation module.

It is already possible to choose between en-dash and em-dash with
```latex
\DefineBibliographyExtras{latvian}{%
  \protected\def\bibrangedash{%
    \textendash\penalty\hyphenpenalty}%
}
```

**Comment by vveckaln** [comment]
How to add the dot after the first number in page range 

> N1.-N2.

?

**Comment by moewew** [comment]
That's a bit trickier than in the Hungarian module and will probably need a few deeper changes in the internals. I'm afraid I'll probably not have time to tackle this today or in the next few days, but it is on the list. Maybe someone has a quick solution on TeX.SX that you can use if you need a solution now.

**Comment by vveckaln** [comment]
you threw the fix into my hands:

```
\DefineBibliographyExtras{latvian}{%                                                                                                                                                                        
  \protected\def\bibrangedash{%                                                                                                                                                                             
    .\textendash\penalty\hyphenpenalty}%                                                                                                                                                                    
}
```

**Comment by moewew** [comment]
That might work for page ranges, but would be problematic for cases where `\bibrangedash` is used with non-ordinal ranges (currently `\bibrangedash` is re-used as `\bibdatedash`). You can use it as a workaround for now, but this will not go into the localisation module and you should check the output very carefully.

**Comment by moewew** [comment]
With the changes in https://github.com/plk/biblatex/pull/883
```latex
\documentclass[latvian]{article}
%\usepackage[T1]{fontenc}
%\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@inbook{appleby,
  author  = {Humphrey Appleby},
  title   = {On the Importance of the Civil Service},
  date    = {1980},
  booktitle = {Important Things},
  volume    = {5},
  chapter   = {7},
  pages     = {233-249},
}
\end{filecontents}

\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{appleby,sigfridsson,matuz:doody,coleridge,baez/online}

\cite{sigfridsson}

\cite[lorem]{sigfridsson}

\cite[34-36]{sigfridsson}

\cite[i-iii]{sigfridsson}

\cite[34-]{sigfridsson}

\cite[-36]{sigfridsson}

\cite[34-36,40-56]{sigfridsson}

\printbibliography
\end{document}
```
produces
![schaltsjhhgs](https://user-images.githubusercontent.com/6755835/56431810-6db56b80-62cb-11e9-9230-6193a48b0e6f.png)

does that look right?

**Comment by vveckaln** [comment]
When Roman numerals are used the dot is not necessary:

i - iii lpp. 

The dot is necessary when Arabic numerals are used:

1.-3. lpp.

The rest looks good.

**Comment by moewew** [comment]
Thank you very much for the feedback. https://github.com/plk/biblatex/pull/883/commits/174cfafcab91d4be3881ed6d411209ad5081372c should implement that. The output now looks like

!["i-iii lpp."](https://user-images.githubusercontent.com/6755835/56858604-32770480-697d-11e9-95c9-6d8b5a8d1720.png)

**Comment by vveckaln** [comment]
Looks good.

**Comment by moewew** [comment]
Great! Thank you for the confirmation.

#883 has  been merged and will be in the next release version. (No ETA as of now.) Unfortunately, I can't offer a quick copy-and-paste-able solution since the implementation of the ordinals required changes in internals. That's also the reason why the `.lbx` file will only work together with the correct version of `biblatex.sty` and can not be used as a drop-in replacement for the current release version.

**Comment by moewew** [comment]
`biblatex` 3.13 is available now on CTAN. Please give it a spin.
