### ISSUE TITLE
Latest dev version runs into error

### ISSUE THREAD

**Issue by ashinpan** [plk/biblatex#889]
The latest dev version (updated on 30th April 2019) runs into the following error:

---------------------------------------

(/home/pan/texlive/texmf-local/tex/latex/biblatex/biblatex.def
! Illegal unit of measure (pt inserted).
<to be read again> 
                   m
l.262 \setlength{\biburlbigskip}{0mu plus 3mu}
                                              
?

**Comment by moewew** [comment]
Thank you very much for the report. Unfortunately I can no reproduce the error you show. Where did you get the dev version from? SourceForge? (I tested with the versions I just downloaded from https://sourceforge.net/projects/biblatex/files/development/ and https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/development/binaries/ both are dated 2019-04-30).

Can you please run the following MWE
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{sigfridsson,ctan}
\printbibliography
\end{document}
```
and see if it reproduces the error? If it does, please attach the *full* `.log` file of the run.

If it does not reproduce the error, please show us a short example document that does reproduce the error.

**Comment by ashinpan** [comment]
Your document itself does not produce the error, but it does with \usepackage{todonotes}.  Here is the example: 
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}
\usepackage{todonotes} 
\usepackage[style=authoryear, backend=biber]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{sigfridsson,ctan}
\printbibliography
\end{document}

[test2.log](https://github.com/plk/biblatex/files/3139691/test2.log)

**Comment by moewew** [comment]
Thank you very much for that example.

The problematic package was not `todonotes` itself, it was `calc`. See
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}
\usepackage{calc}
\usepackage[style=authoryear, backend=biber]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{sigfridsson,ctan}
\printbibliography
\end{document}
```

When `calc` is loaded, muglue is not supported in `\setlength` any more. See the `calc` documentation in fn. 3 on p. 4 and a longer discussion on p. 14, see also https://tex.stackexchange.com/q/188215/.

Hence, we go for the more primitive `\biburlbigskip=0mu plus 3mu\relax` instead.

This should be fixed in https://github.com/plk/biblatex/commit/0e6e3c5c5686dcdfea7e9e1feb3617950fb0129c.

**Comment by ashinpan** [comment]
Thanks a lot. Your workaround does fix the issue. But I don't know when your fix can be incorporated into the dev version.

**Comment by moewew** [comment]
The `dev` version on SourceForge is updated manually (and not on a regular schedule). If you want to continue using it, you can just replace `/home/pan/texlive/texmf-local/tex/latex/biblatex/biblatex.def` with https://github.com/plk/biblatex/blob/0e6e3c5c5686dcdfea7e9e1feb3617950fb0129c/tex/latex/biblatex/biblatex.def The fix will be in the `dev` version on SourceForge when it is updated the next time.

**Comment by ashinpan** [comment]
Thanks again. I have already done that. I will close the issue given that it is already fixed by you.
