### ISSUE TITLE
Change language on a per field basis

### ISSUE THREAD

**Issue by svenper** [plk/biblatex#895]
Continued from [this SX question](https://tex.stackexchange.com/questions/444016/change-language-on-a-per-field-basis-part-2-fonts-case-transformation-and-sor), in turn from [this one](https://tex.stackexchange.com/questions/260954/change-language-on-a-per-field-basis). I thought this should at least be noted as an issue, even if I don't really need a solution. In addition to those examples, another use case:

If we have an author with a Turkish name containing `i` writing an English book, and want to print their name in (small) capitals, we need a language change only for the name. 

(Turkish distinguishes dotless `I`&zwnj;`ı` and dotted `İ`&zwnj;`i`, with case transformations not matching English. If the name only contains `ı` or `İ` that's currently fine as they are unambiguous.)

What would be intuitive to me is if the individual fields had companion *langid[opts] fields (e.g. authorlangid, titlelangid, etc.)

```tex
\documentclass{article}
\usepackage{filecontents}
\usepackage{fontspec}
\setmainfont{SourceSerifPro-Regular.otf}
\usepackage{polyglossia}
\setmainlanguage{english}
\setotherlanguage{turkish}
\usepackage{biblatex}
\begin{filecontents}{\jobname.bib}
@book{idot,
  author = {Bilgili},
  title = {English language book},
}
\end{filecontents}
\addbibresource{\jobname.bib}
\def\mkbibnamefamily{\textsc}
\begin{document}
\textturkish{\citeauthor{idot}}
\textenglish{\citeauthor{idot}}
\printbibliography
\end{document}
```

![turk](https://user-images.githubusercontent.com/15199675/58674108-dd445f00-833d-11e9-9290-d0c59f1627b1.png)

**Comment by moewew** [comment]
I'd love to see something like this, but the exact timing of the language switching is extremely tricky and may need to be adjusted depending on the desired outcome. For names in particular it might not be enough to switch the language for the whole name list, you'd actually want to switch the language per name (item) so that the Turkish Bilgili and the English Miller both come out with the respective expected small caps version of `i`.

```latex
\documentclass{article}

\usepackage{libertine}

\usepackage{polyglossia}
\setmainlanguage{english}
\setotherlanguage{turkish}

\usepackage{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{idot,
  author = {Bilgili},
  title  = {English language book},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\renewcommand\mkbibnamefamily{\textsc}

\begin{document}
\textturkish{\citeauthor{idot}}

\textenglish{\citeauthor{idot}}

\printbibliography
\end{document}
```

Since `*langid` fields would need to be added to the data model, I think I'd prefer something like named field annotations instead.

Related-ish: https://github.com/plk/biblatex/issues/757

**Comment by jspitz** [comment]
Another case where this is needed are multi-language volumes. Consider the following case:

```tex
\documentclass{article}
\usepackage{libertine}
\usepackage[english,ngerman]{babel}
\usepackage[style=apa]{biblatex}
\begin{filecontents}{\jobname.bib}
@collection{AntosNiehrSpitzmueller:HSW10,
	editor = {Gerd Antos and Thomas Niehr and Jürgen Spitzmüller},
	title = {Handbuch Sprache im Urteil der Öffentlichkeit},
	publisher = {De Gruyter},
	address = {Berlin and Boston},
	year = {2019},
	langid = {ngerman}
}

@incollection{Preston:FolkLing19,
	author = {Dennis R. Preston},
	crossref = {AntosNiehrSpitzmueller:HSW10},
	pages = {140--164},
	title = {Folk Linguistics and the Perception of Language Variety},
	langid = {english}
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\cite{AntosNiehrSpitzmueller:HSW10,Preston:FolkLing19}
\printbibliography
\end{document}
```

This comes out with wrong booktitle-casing for the `@incollection` entry:
![image](https://user-images.githubusercontent.com/4538783/72679077-0754b800-3aac-11ea-8301-a238db93cb63.png)

I know this can be worked-around by brace protection, but ideally, the language of the boo title field should be settable.

**Comment by jspitz** [comment]
(and of course hyphenation cannot be fixed by case protection)

**Comment by plk** [comment]
I am looking at this in the multiscript branch currently and will report it here when there is something working there. It's not trivial to do this in the current biber/biblatex versions. The multiscript version will have a dedicated data annotation for language switching.

**Comment by plk** [comment]
This is now possible in the multiscript branch of biber/biblatex (found in the experimental) folders on SF. Your example works as it should, I believe. This branch also supports lang switching on a per-list item basis to address the other examples in this thread. As you mentioned, this is based on a dedicated data annotation (see PDF docs for the experimental v4.0 branch)

**Comment by jspitz** [comment]
So, just out of curiosity, did I get it right from the `biblatex 4.0` manual that the above example would need this?
```tex
title = {Handbuch Sprache im Urteil der Öffentlichkeit},
title+an:langtags = {=de},
```

**Comment by plk** [comment]
`langtags` is now `mslang` in the latest upload by the way ...

But no, you won't need that in this case as biber will automatically add the annotations for crossrefed fields which differ in the inferred `langid` from the parent entry.

**Comment by jspitz** [comment]
> But no, you won't need that in this case as biber will automatically add the annotations for crossrefed fields which differ in the inferred `langid` from the parent entry.

Oh, how cool!

**Comment by plk** [comment]
I should also point out the multiscript, in your crossref case, will do more than just make sentence casing work (which is a somewhat special subsystem in biblatex), it will also (optionally) make the inherited german fields automatically be wrapped in a babel/polyglossia german hyphenation environment or full language environment (depending on the setting of the `autofieldlang` option) and optionally use the german biblatex bibstrings (depending on the setting of the `autofieldlangstrings` option). These options also influence automatic language switching for specific items in lists and names.

**Comment by jspitz** [comment]
Thanks. That's really a significant improvement not only to multiscript, but also to multiligual references.

**Comment by plk** [comment]
multiscript version 4.0 of both biblatex and biber are in TL now as `biblatex-ms` and `biber-ms` to try.

**Comment by lodumont** [comment]
I am having issues using annotations and the ```mslang``` tag (see [this question](https://tex.stackexchange.com/questions/713725/change-language-for-specific-fields-using-biblatex-ms)).

In a document written in French and including references in English, I am observing differences between the annotation system and a manual encapsulation of some fields in the ```otherlanguage``` environment provided by ```babel```.

```
\documentclass[a4paper,12pt]{article}

\usepackage{fontspec}
\usepackage[english, french]{babel}
\usepackage{csquotes}

\begin{filecontents}[force]{\jobname.bib}
@article{Coles59a,
    author = {Coles, John M.},
    date = {1959/1960},
    doi = {10.9750/psas.093.16.134},
    journal = {\begin{otherlanguage}{english}Proceedings of the Society of Antiquaries of Scotland\end{otherlanguage}},
    pages = {16-134},
    title = {\begin{otherlanguage}{english}Scottish Late Bronze Age Metalwork: Typology, Distribution and Chronology\end{otherlanguage}},
    volume = {93}}
}

@article{Coles59b,
    author = {Coles, John M.},
    date = {1959/1960},
    doi = {10.9750/psas.093.16.134},
    journal = {Proceedings of the Society of Antiquaries of Scotland},
    journal+an:mslang = {=en},
    pages = {16-134},
    title = {Scottish Late Bronze Age Metalwork: Typology, Distribution and Chronology},
    title+an:mslang = {=en},
    volume = {93}}
}
\end{filecontents}


\usepackage[style=authoryear, autofieldlang=other, dashed=false]{biblatex-ms}
        
\addbibresource{./\jobname.bib}

\begin{document}

\nocite{*}

\printbibliography

\end{document}
```

The output is:

<img width="592" alt="tmXeW" src="https://github.com/plk/biblatex/assets/61599071/b26b0d8d-e7d3-4b5d-a57e-eb91fcb8c8e5">

As you can see, the first reference is typeset correctly: the document is in French but English rules applied to the title of the article (no extra non-breaking space added before the colon). On the other hand, the second reference's title is typeset according to the French rules. How can I fix this behaviour?

I am using an up-to-date MacTeX 2024 distribution with ```biblatex-ms``` and ```biber-ms``` 4.0.

My ```.aux``` file looks like that:

```
\relax 
\providecommand\babel@aux[2]{}
\@nameuse{bbl@beforestart}
\abx@aux@refcontext{nyt/global//global/global}
\abx@aux@nociteall
\babel@aux{french}{}
\abx@aux@page{1}{1}
\babel@aux{french}{}
\babel@aux{french}{}
\babel@aux{french}{}
\babel@aux{english}{}
\babel@aux{french}{}
\babel@aux{french}{}
\babel@aux{french}{}
\babel@aux{english}{}
\babel@aux{french}{}
\babel@aux{french}{}
\abx@aux@page{2}{1}
\babel@aux{french}{}
\babel@aux{french}{}
\babel@aux{french}{}
\babel@aux{french}{}
\babel@aux{french}{}
\babel@aux{french}{}
\abx@aux@read@bbl@mdfivesum{253A7D387EAD16DA136038CCD81D250A}
\abx@aux@defaultrefcontext{0}{Coles59a}{nyt/global//global/global}
\abx@aux@defaultrefcontext{0}{Coles59b}{nyt/global//global/global}
\gdef \@abspage@last{1}
```

And here is the ```.bbl``` file produced by ```biber-ms```:

```
\refsection{0}
  \datalist[entry]{nyt/global//global/global}
    \entry{Coles59a}{article}{}
      \name[default][fr-fr]{author}{1}{}{%
        {{un=0,uniquepart=base,hash=c4358b6a0351f56cc2935f5f1b4a4b37}{%
           family={Coles},
           familyi={C\bibinitperiod},
           given={John\bibnamedelima M.},
           giveni={J\bibinitperiod\bibinitdelim M\bibinitperiod},
           givenun=0}}%
      }
      \namepartms{author}{1}{%
          familydefaultfr-fr={Coles},
          familydefaultfr-fri={C\bibinitperiod},
          givendefaultfr-fr={John\bibnamedelima M.},
          givendefaultfr-fri={J\bibinitperiod\bibinitdelim M\bibinitperiod}
      }
      \strng{namehash}{c4358b6a0351f56cc2935f5f1b4a4b37}
      \strng{fullhash}{c4358b6a0351f56cc2935f5f1b4a4b37}
      \strng{bibnamehash}{c4358b6a0351f56cc2935f5f1b4a4b37}
      \strng{authordefaultfr-frbibnamehash}{c4358b6a0351f56cc2935f5f1b4a4b37}
      \strng{authordefaultfr-frnamehash}{c4358b6a0351f56cc2935f5f1b4a4b37}
      \strng{authordefaultfr-frfullhash}{c4358b6a0351f56cc2935f5f1b4a4b37}
      \field{extraname}{1}
      \field{sortinit}{C}
      \strng{sortinithash}{4d103a86280481745c9c897c925753c0}
      \field{extradate}{1}
      \field{extradatescope}{labelyear}
      \field{labeldatesource}{}
      \fieldmssource{labelname}{author}{default}{fr-fr}
      \fieldmssource{labeltitle}{title}{default}{fr-fr}
      \field{endyear}{1960}
      \field[default][fr-fr]{journaltitle}{\begin{otherlanguage}{english}Proceedings of the Society of Antiquaries of Scotland\end{otherlanguage}}
      \field[default][fr-fr]{title}{\begin{otherlanguage}{english}Scottish Late Bronze Age Metalwork: Typology, Distribution and Chronology\end{otherlanguage}}
      \field{volume}{93}
      \field{year}{1959}
      \field{enddateera}{ce}
      \field{dateera}{ce}
      \true{nocite}
      \field{pages}{16\bibrangedash 134}
      \range{pages}{119}
      \verb{doi}
      \verb 10.9750/psas.093.16.134
      \endverb
    \endentry
    \entry{Coles59b}{article}{}
      \name[default][fr-fr]{author}{1}{}{%
        {{un=0,uniquepart=base,hash=c4358b6a0351f56cc2935f5f1b4a4b37}{%
           family={Coles},
           familyi={C\bibinitperiod},
           given={John\bibnamedelima M.},
           giveni={J\bibinitperiod\bibinitdelim M\bibinitperiod},
           givenun=0}}%
      }
      \namepartms{author}{1}{%
          familydefaultfr-fr={Coles},
          familydefaultfr-fri={C\bibinitperiod},
          givendefaultfr-fr={John\bibnamedelima M.},
          givendefaultfr-fri={J\bibinitperiod\bibinitdelim M\bibinitperiod}
      }
      \strng{namehash}{c4358b6a0351f56cc2935f5f1b4a4b37}
      \strng{fullhash}{c4358b6a0351f56cc2935f5f1b4a4b37}
      \strng{bibnamehash}{c4358b6a0351f56cc2935f5f1b4a4b37}
      \strng{authordefaultfr-frbibnamehash}{c4358b6a0351f56cc2935f5f1b4a4b37}
      \strng{authordefaultfr-frnamehash}{c4358b6a0351f56cc2935f5f1b4a4b37}
      \strng{authordefaultfr-frfullhash}{c4358b6a0351f56cc2935f5f1b4a4b37}
      \field{extraname}{2}
      \field{sortinit}{C}
      \strng{sortinithash}{4d103a86280481745c9c897c925753c0}
      \field{extradate}{2}
      \field{extradatescope}{labelyear}
      \field{labeldatesource}{}
      \fieldmssource{labelname}{author}{default}{fr-fr}
      \fieldmssource{labeltitle}{title}{default}{fr-fr}
      \field{endyear}{1960}
      \field[default][fr-fr]{journaltitle}{Proceedings of the Society of Antiquaries of Scotland}
      \field[default][fr-fr]{title}{Scottish Late Bronze Age Metalwork: Typology, Distribution and Chronology}
      \field{volume}{93}
      \field{year}{1959}
      \field{enddateera}{ce}
      \field{dateera}{ce}
      \true{nocite}
      \field{pages}{16\bibrangedash 134}
      \range{pages}{119}
      \verb{doi}
      \verb 10.9750/psas.093.16.134
      \endverb
      \annotation[default][fr-fr]{field}{journaltitle}{mslang}{}{}{0}{en}
      \annotation[default][fr-fr]{field}{title}{mslang}{}{}{0}{en}
    \endentry
  \enddatalist
\endrefsection
\msforms{default}
\msentrylangs{fr-fr}
\mslangs{fr-fr}

\endinput
```
