### ISSUE TITLE
skipbiblist's description: typo in the manual 

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#896]
The manual of `biblatex` version 3.12 says, in the `skipbiblist`'s description p. 66:

>If this option is enabled, the entry is excluded from and bibliography lists.

I guess there is a typo in this sentence.

**Comment by plk** [comment]
This is already corrected on the DEV branch.

**Comment by moewew** [comment]
Specifically in https://github.com/plk/biblatex/commit/ce90ae04653bfd17f0934ec69d3c3561d0555da2
