### ISSUE TITLE
Date ranges with a mix of months and seasons leads to inconsistent results

### ISSUE THREAD

**Issue by danielshub** [plk/biblatex#898]
In the case where a date range starts with a month and ends with a season, the end season is dropped. Similarly, when the range starts with a season and ends with a month, the end month is dropped. While odd, I would expect `2018-21/2019-12` to produce something like "Spr 2018 -- Dec 2019" while I get "Spr 2018 -- 2019". Similarly, I would expect `2018-12/2019-21` to produce "Dec 2018 -- Spr 2019" while I get "Dec 2018 -- 2019".

```latex
\documentclass{article}
\usepackage[style=numeric]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@article{ms,
  author       = {Doe, John},
  title        = {Month First},
  journaltitle = {My main journal},
  date         = {2018-12/2019-21},
}
@article{sm,
  author       = {Doe, John},
  title        = {Season First},
  journaltitle = {My main journal},
  date         = {2018-21/2019-12},
}
@article{ss,
  author       = {Doe, John},
  title        = {Seasons},
  journaltitle = {My main journal},
  date         = {2018-21/2019-21},
}
@article{mm,
  author       = {Doe, John},
  title        = {Months},
  journaltitle = {My main journal},
  date         = {2018-12/2019-01},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\cite{ms}

\cite{sm}

\cite{ss}

\cite{mm}

\printbibliography
\end{document}
```

**Comment by moewew** [comment]
Thank you very much for reporting this.

Fortunately, this seems to be resolved by correcting only a few oversights in the code: https://github.com/plk/biblatex/commit/c33c966736762a6158830512f65f5a54c745952b.

**Comment by moewew** [comment]
`biblatex` 3.13 with a fix for this issue is available on CTAN now. The MWE produces more sensible output with 3.13.
