### ISSUE TITLE
Allow nocite in bibliography?

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#901]
https://tex.stackexchange.com/q/497542/35864 reminded me of the fact that `\nocite` is not processed in a bibliography context.

Given that other citations are processed in the bibliography (even if that can be quite dangerous) it seems odd that `\nocite` would be disabled explicitly.

Apparently that restriction has been present since at least version 1.0 of `biblatex` (it wasn't present in 0.8, but I don't have all versions in between, and even if I did, I'm not sure if it even helped to find when exactly this was changed), so I'm wary to change this without further deliberation, so if anyone has any thoughts input would be appreciated.

**Comment by plk** [comment]
Hmm, I have some memory that this was quite a deep and difficult issue when I looked into it before. Do you have a MWE?

**Comment by moewew** [comment]
I guess there must have been an issue, otherwise the test would not have been introduced. But this is from so long ago that I didn't manage to find any documentation on this.

An MWE with `\nocite` and a faked `\nocite` that works in the bibliography
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\makeatletter
\newcommand*{\nociteinbib}{\blx@nocite@do}
\makeatother

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{appleby,
  author  = {Humphrey Appleby},
  title   = {On the Importance of the Civil Service \nociteinbib{sigfridsson}},
  date    = {1980},
}
@book{bppleby,
  author  = {Humphrey Bppleby},
  title   = {On the Importance of the Civil Service \nocite{worman}},
  date    = {1981},
}
\end{filecontents}

\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{appleby,bppleby}
\printbibliography
\end{document}
```

**Comment by plk** [comment]
I have taken out that test and all test files are identical at least. I have no idea why that is there and I don't recall putting it there - probably work doing a VC search but let's see what happens ... we may have to put the test back but this time we'll know why and can comment it ...
