### ISSUE TITLE
xdata and sourcemapping behavior is pretty strange

### ISSUE THREAD

**Issue by dougalsutherland** [plk/biblatex#905]
There seems to be some unintuitive behavior in the relative ordering of inheriting fields with `xdata` and altering them with a sourcemap:

```latex
\RequirePackage{filecontents}
\begin{filecontents*}{\jobname.bib}
    @xdata{xdata-n, year={2000}, journal = {No xdata note}}
    @xdata{xdata-y, year={2000}, journal = {With xdata note}, note={Xdata note.}}

    @article{n-n, title={No paper note.}  , xdata={xdata-n}}
    @article{n-y, title={No paper note.}  , xdata={xdata-y}}
    @article{y-n, title={With paper note.}, xdata={xdata-n}, note={Paper note!}}
    @article{y-y, title={With paper note.}, xdata={xdata-y}, note={Paper note!}}
\end{filecontents*}

\documentclass{article}
\usepackage[style=draft]{biblatex}
\addbibresource{\jobname.bib}
\DeclareSourcemap{
    \maps[datatype=bibtex,overwrite]{
        \map{
            \pertype{article}
            \step[fieldset=note, fieldvalue={\space{}Sourcemap note.}, append]
        }}}

\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

I'd expect one of the two following things to happen:

## Reasonable scenario 1

1. All `@article` entries get `Sourcemap note.` appended to their `note` (creating it if it doesn't exist).
2. `xdata` inheritance "resolves" – but every entry already has a `note`, so nobody inherits that.

This would give:
> n-n “No paper note.” In: No xdata note (2000). Sourcemap note.
> n-y “No paper note.” In: With xdata note (2000). Sourcemap note.
> y-n “With paper note.” In: No xdata note (2000). Paper note! Sourcemap note.
> y-y “With paper note.” In: With xdata note (2000). Paper note! Sourcemap note.

## Reasonable scenario 2

1. `xdata` inheritance "resolves," giving everyone but `n-n` a `note`.
2. All `@article` entries get `Sourcemap note.` appended to their `note`.

This would give:
> n-n “No paper note.” In: No xdata note (2000). Sourcemap note.
> n-y “No paper note.” In: With xdata note (2000). Xdata note. Sourcemap note.
> y-n “With paper note.” In: No xdata note (2000). Paper note! Sourcemap note.
> y-y “With paper note.” In: With xdata note (2000). Paper note! Sourcemap note.

## What actually happens

> n-n “No paper note.” In: No xdata note (2000). Sourcemap note.
> n-y “No paper note.” In: With xdata note (2000). Xdata note.
> y-n “With paper note.” In: No xdata note (2000). Paper note! Sourcemap note.
> y-y “With paper note.” In: With xdata note (2000). Xdata note.

It seems like what's happening is:
1. `xdata` inheritance happens, but with a "pointer" to the xdata's note if it has one.
2. Articles that aren't inheriting a note get altered by the sourcemap. Articles with a note "pointer" are unaffected by the sourcemap.

I don't know whether this is a "bug", but it's definitely pretty unintuitive for me, and I couldn't find any explanation for this in searching around, so hopefully this at least useful if someone else runs into this in the future. (https://github.com/plk/biblatex/issues/19 was very useful in realizing my sourcemap was originally affecting `@xdata` entries, which I didn't even consider would happen, but it still took a lot of experimenting to figure out what was actually happening.)

(In my real use case, I was trying to add to `keywords` for everything in a particular bib file with `\perdatasource`, but some of them inherit from xdata entries which have different `keywords` in a different bib file. I found a different scheme to do what I needed, but I think this behavior makes doing what I wanted impossible....)

**Comment by plk** [comment]
Sourcemaps happen before anything else, as the data is being read. `XDATA` processing comes later and is relatively simple - it just overwrites by design. Typically, you would use `XDATA` to populate fields which were not in the targets as it's like the `CROSSREF` field but a bit more functional. This means that your observations about what happens are correct and by design.

**Comment by dougalsutherland** [comment]
Unless I’m missing something, it doesn’t seem like data processing really comes entirely later than the sourcemap – that would be “reasonable scenario 1”. The thing I find confusing is the way they seem to be kind of interleaved.

**Comment by plk** [comment]
Honestly, sourcemapping happens first ... scenario 1 can't be the result because later XDATA will overwrite the `NOTE` fields.

**Comment by dougalsutherland** [comment]
Ohhhhhhh - I'm sorry, I thought that xdata didn't override existing fields on an entry, but now I see that they do. So it's actually scenario 1, I just misunderstood how xdata works (because my sourcemap entries as I initially played with it were hitting the xdata entries too).

That's actually kind of an issue for me, and I'll have to think how to reorganize my scheme, but there's no issue with this interaction then. Thanks!
