### ISSUE TITLE
Add optional timestamp field

### ISSUE THREAD

**Issue by 927589452** [plk/biblatex#908]
As explained [here](http://discourse.jabref.org/t/biber-datamodel-compability/1699) a `timestamp` field (which is already provided by bibliography managment tool) as an optional data field could have a use like
> showing the citations in order of finding them

I would love to provide a PR, if you like this

**Comment by moewew** [comment]
With Biber the `biblatex` data model is customisable, so you can easily add this field to the output or to sorting schemes.

Usually we only add new fields to the data model, the bibliography output or sorting templates if they either (1) require interesting changes to `biblatex` internals or (2) are highly requested. See for example https://github.com/plk/biblatex/issues/122, https://github.com/plk/biblatex/issues/156, https://github.com/plk/biblatex/issues/256, https://github.com/plk/biblatex/pull/766, https://github.com/plk/biblatex/pull/907. We've been fairly conservative in the past with adding new fields and I would like to continue this policy. We know that the standard data model can't cover all needs users may have and I'd rather we have a usable, compact and understandable system that covers the need of roughly 80% of users really well, than adding all sorts of bells and whistles to try and cover every eventuality and every possible niche usage people may have in mind.

**Comment by 927589452** [comment]
It seems like all those and mine could use an extending .xml scheme to support the tools;

I would suggest a user defined template ( to support the tool mode too) like this:
(sorry if this does already exist and i didn't find it)

```
<?xml version="1.0" encoding="UTF-8"?>
<config>
    <fields>
      <field fieldtype="field" datatype="literal">annotation</field>
    </fields>
    <entryfields>
      <field>annotation</field>
    </entryfields>
</config>
```

This should stay more or less easy to maintain, even through change of biblatex, while keeping ones own biber-tool.cfg might run out of sync with biblatex

An Idea could be to add a biblatex version header to the xml, so biber can warn, if the main data model changed in an uncompatible way

**Comment by moewew** [comment]
I'm not quite sure if I understand what you are getting at, but from the `biblatex` side one would normally use `.dbx` files to extend the data model.
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage{filecontents}
\begin{filecontents}{timestamp.dbx}
\DeclareDatamodelFields[type=field, datatype=literal]{
  timestamp}

\DeclareDatamodelEntryfields{
  timestamp}
\end{filecontents}


\usepackage[style=authoryear, backend=biber, datamodel=timestamp]{biblatex}


\renewbibmacro{finentry}{%
  \newunit\newblock
  \printfield{timestamp}%
  \finentry
}

\begin{filecontents}{\jobname.bib}
@book{appleby,
  author    = {Humphrey Appleby},
  title     = {On the Importance of the Civil Service},
  date      = {1980},
  timestamp = {blub},
}
\end{filecontents}

\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{sigfridsson,appleby}
\printbibliography
\end{document}
```

If you want a `.conf` file for Biber that can be used in `--tool` mode as well you'd end up with something similar to the file described in https://tex.stackexchange.com/q/415028/35864 (this is pretty much what you suggest already, so I'm a bit confused ...).

**Comment by 927589452** [comment]
> If you want a .conf file for Biber that can be used in --tool mode as well you'd end up with something similar to the file described in https://tex.stackexchange.com/q/415028/35864 (this is pretty much what you suggest already, so I'm a bit confused ...).

The line, which makes it hard to keep up with the orginal biblatex configuration is
>  Copy that (yes, all that) in your clean-bibfiles.conf, just below your sourcemap specifications, as you had them originally defined.

I want to suggest an "extends file", which is merged based on the xml structure;
so if this is the original config
```
<?xml version="1.0" encoding="UTF-8"?>
<config>
    <fields>
      <field fieldtype="field" datatype="literal">timestamp</field>
      <field fieldtype="field" datatype="literal">someother</field>
    </fields>
    <entryfields>
      <field>timestamp</field>
      <field>someother</field>
    </entryfields>
</config>
```

and this is the user provided file
```
<?xml version="1.0" encoding="UTF-8"?>
<config>
    <fields>
      <field fieldtype="field" datatype="literal">source</field>
      <field fieldtype="field" datatype="othertype">someother</field>
    </fields>
    <entryfields>
      <field>source</field>
      <field>someother</field>
    </entryfields>
</config>
```

the file which is internally used is
```
<?xml version="1.0" encoding="UTF-8"?>
<config>
    <fields>
      <field fieldtype="field" datatype="literal">timestamp</field>
      <field fieldtype="field" datatype="literal">source</field>
      <field fieldtype="field" datatype="othertype">someother</field>
    </fields>
    <entryfields>
      <field>timestamp</field>
      <field>someother</field>
      <field>source</field>
    </entryfields>
</config>
```

eg a defined merge behaviour as in a user provided field probably should supercede a default field and a merge for non existing types etc.

this would make the using the tool mode with custom data models much easier i think

**Comment by moewew** [comment]
Ah, I see. I agree that would be more convenient. I'm not sure if it is easily possible with the current Biber set-up to allow for 'data model extension' `.conf`s, though. 

In any case I suggest you open a new issue with a feature request at the Biber bugtracker: https://github.com/plk/biber/issues, since this is nothing `biblatex` can help with.

**Comment by 927589452** [comment]
I opened an issue at the `biber` project;
thanks pointing me there
