### ISSUE TITLE
blockcquote fails to print parentheses around the citation

### ISSUE THREAD

**Issue by ashinpan** [plk/biblatex#912]
I am using the latex biblatex (3.13) (authoryear style) and csquotes (5.2e) together. I have found that blockcquote fails to print parentheses around the citation at the end of the blockquote. I don't know if this is a bug of biblatex or of csquote.

What follows is a minimal file.

--------------------------

```latex
\documentclass[12pt,a4paper]{article}

\usepackage{csquotes}
\usepackage[style=authoryear,backend=biber]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@incollection{vibhat,
  options   = {useeditor=false},
  title     = {Vibhatyattha},
  pages     = {127-131},
  address   = {Rangoon, MM},
  editor    = {{Tun Sein}, U and {Sein Oak}, U and {Win Phe}, U and {Tin Myint}, U},
  publisher = {Icchasaya},
  booktitle = {15 Grammatical Manuals},
  year      = 1965
}

\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\blockcquote[7]{vibhat}{%
No one was in a position to record or reproduce the Buddha’s sermons as he uttered them. The texts preserved did not just drop from his lips; they must be products of deliberate composition—in fact, they were composed to be memorized. This inevitably introduces a certain formalization: such features as versification, numbered lists, repetition and stock formulae are all aids to memory.}

\printbibliography%[heading=secondary]
\end{document}
```

**Comment by moewew** [comment]
Are you really using the as of yet unreleased version 3.13 of `biblatex`? The released version on CTAN is 3.12. We are currently in the process of releasing 3.13, but it isn't official yet?

Anyhow, did this code use to produce parentheses around the citation in earlier versions?  My `csquotes.cfg` has
```latex
\SetCiteCommand{\cite}
```
which is consistent with the output you get. So I'm not sure if this is really a bug at all.

**Comment by ashinpan** [comment]
@moewew  With biblatex authoryear style, "autocite" command always produces a citation with parenthesis around it. Therefore, I expected the same behavior with blockcquote. And my expectation had worked until biblatex 3.12. This is why I think this is a bug.

**Comment by moewew** [comment]
Mhh, I ran your example with `biblatex` 3.12 and the pre-release version of `biblatex` 3.13 and got no parentheses with both versions. Are you sure it worked with 3.12?

There is no indication that `csquotes` uses `\autocite` (I personally think using `\autocite` would be a great idea, but this is not the point) in fact everything suggests it has always used the plain `\cite` command.

**Comment by ashinpan** [comment]
Then, I must be misremembering things. Anyhow, I do agree that using \autocite should be a great idea. I am closing the issue now.
