### ISSUE TITLE
Documentation of inheritance strategy incomplete / unclear

### ISSUE THREAD

**Issue by sfo** [plk/biblatex#919]
In Appendix B, the documentation gives a list of how fields are inherited from one entry to another in a crossref-relationship. However, the documentation does not state, what the following things mean:
1. There are squares for source and target types in the first row. What do they mean? I assume this means 'any'. But in this case, maybe an asterisk symbol would be a better choice.
2. Sometimes, for target fields, there are dashes. Does that mean there is no inheritance? This would mean that no target field is allowed to request the value of the specified source field, correct?
3. Then, what does an empty target field cell mean?
4. What about fields, that are not included in the list? At least biber seems to handle some fields differently.
    1. Target fields inherit the value of the source field with the same name. So, all _InProceedings_ entries without title would inherit the _Proceedings_' title? (biber does not do that, the title stays empty)
    2. There is no inheritance for non-mentioned fields. So no _InProceedings_ entry would inherit the _Proceedings_' year, location, etc.? (biber does this, the year and location gets populated with values from the referenced entry)

I skipped through the referenced sections ($$ 2.4.1 and 4.5.11) but could not find a clear answer to my questions.

**Comment by moewew** [comment]
1. Yes, this indeed means 'any', and it is supposed to be an asterisk, but apparently the font doesn't have it, so we get the box.
2. Yes, dashes mean that there is no inheritance of the source field to any field in the target entry. I wouldn't talk about the target *requesting* (missing) fields, I would say it *inherits* fields, but the result should be the same.
3. Empty target cells should contain a dash. The missing dashes are typos, the code for the table is a bit fiddly and so I assume not adding the dashes was a simply oversight.
4. Everything that is not listed explicitly will be inherited straight through.
   1. In your example `@inproceedings` will inherit the `title` of its parent `@proceedings` as `booktitle`. But this *is* listed in the table.
    2. Indeed, the `@inproceedings` inherits its parents `year`, `location`, `publisher` etc.

Of course inheritance in all cases happens only if the relevant target field isn't populated already.


This is just a simplified copy of the example from `biblatex-examples.bib`

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@collection{westfahl:frontier,
  editor       = {Westfahl, Gary},
  title        = {Space and Beyond},
  date         = 2000,
  subtitle     = {The Frontier Theme in Science Fiction},
  publisher    = {Greenwood},
  location     = {Westport, Conn. and London},
}
@incollection{westfahl:space,
  author       = {Westfahl, Gary},
  title        = {The True Frontier},
  subtitle     = {Confronting and Avoiding the Realities of Space in {American}
                  Science Fiction Films},
  pages        = {55-65},
  crossref     = {westfahl:frontier},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\cite{westfahl:space}
\printbibliography
\end{document}
```
results in the `.bbl` data (uninteresting fields omitted)
```latex
\entry{westfahl:space}{incollection}{}
  \name{author}{1}{}{%
    {{un=0,uniquepart=base,hash=dd4c0e40628e106b641ac3b9ce2e8b18}{%
       family={Westfahl},
       familyi={W\bibinitperiod},
       given={Gary},
       giveni={G\bibinitperiod},
       givenun=0}}%
  }
  \name{editor}{1}{}{%
    {{hash=dd4c0e40628e106b641ac3b9ce2e8b18}{%
       family={Westfahl},
       familyi={W\bibinitperiod},
       given={Gary},
       giveni={G\bibinitperiod}}}%
  }
  \list{location}{2}{%
    {Westport, Conn.}%
    {London}%
  }
  \list{publisher}{1}{%
    {Greenwood}%
  }
  \field{booksubtitle}{The Frontier Theme in Science Fiction}
  \field{booktitle}{Space and Beyond}
  \field{subtitle}{Confronting and Avoiding the Realities of Space in {American} Science Fiction Films}
  \field{title}{The True Frontier}
  \field{year}{2000}
  \field{dateera}{ce}
  \field{pages}{55\bibrangedash 65}
  \range{pages}{11}
\endentry
```

If there are any doubts, the rules are defined in `biblatex.def`

https://github.com/plk/biblatex/blob/bcc7970e4020533cf9cf430b222b5699c1bd92f1/tex/latex/biblatex/biblatex.def#L1644-L1744

It should be noted that this is only the *defult* inheritance setup and that users and styles may defined additional or entirely different rules as well.

---

I pushed https://github.com/plk/biblatex/commit/bef30b31ce19ec80836375b20ce9723b973d6508 with some changes to the table.

1. The boxes should now be asterisks again.
2. There are no empty cells any more, they now contain dashes.
3. I also included a line for the generic inheritance as 

    | Source Type  | Target Type | Source Field | Target Field|
    | -------------- | ------------- | ------------- | ------------ |
    | *  | * | * | * |
 
  I decided to add this as the first line, but depending on how people read the list it might be more intuitive to have this at the end of the table. WDYT?

**Comment by sfo** [comment]
Thanks for clarification and the patch. 

Personally, I'd prefer to have the all asterisk row at the bottom of the table, because from a simple rule matching perspective, one may apply the first rule that matches, instead of going through all the possibilities.

**Comment by moewew** [comment]
Fair enough, moved the row to the end of the table.
