### ISSUE TITLE
uniquelist only works with uniquename

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#924]
Inspired by https://golatex.de/viewtopic,p,108282.html.

Consider
```latex
\documentclass[a4paper,12pt]{article}
\usepackage[utf8]{inputenc}
\usepackage[ngerman]{babel}
\usepackage[T1]{fontenc}
\usepackage{lmodern}

\usepackage[backend=biber,
  style=numeric,
  maxcitenames=2,
  uniquelist=true, uniquename=false,
]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@article{Cai_Ma,
  author    = {Cai, Lixiong and Ma, Baoguo and Qu, Xian},
  title     = {Mechanical and hydration characteristics of autoclaved
               aerated concrete (AAC) containing iron-tailings:
               effect of content and fineness},
  journal   = {Construction and Building Materials},
  year      = {2016},
  volume    = {128},
  pages     = {361--372},
}
@article{Cai_Li,
  author    = {Cai, Lixiong and Li, Xiangguo and Ma, Baoguo},
  title     = {Mechanical and hydration characteristics of autoclaved
               aerated concrete (AAC) containing iron-tailings:
               effect of content and fineness},
  journal   = {Construction and Building Materials},
  year      = {2016},
  volume    = {128},
  pages     = {361--372},
}
\end{filecontents}
\addbibresource{\jobname.bib}


\begin{document}
\textcite{Cai_Ma}

\textcite{Cai_Li}

\printbibliography
\end{document}
```
The example produces
> Cai u.a. [2]
> Cai u.a. [1]

with `biblatex` 3.13. In 3.12 it used to produce

> Cai, Ma u.a. [2]
> Cai, Li u.a. [1]

In `biblatex` 3.13 the `uniquelist` feature in the example works only if the `uniquename` feature is explicitly enabled. I would expect `uniquelist` to work independent of the `uniquename` setting.

**Comment by plk** [comment]
That's going to take some investigation - quite some surgery was done to this for v2.13 to generalise options to refsections. Will look into it. At least it shows my test suite has a case missing ...

**Comment by plk** [comment]
Please try 2.14 DEV. This should be fixed - it a was a bit obscure of a bug not directly related to the `uniquename` setting but certainly related.

**Comment by moewew** [comment]
The example works very well now, thank you.
