### ISSUE TITLE
New \addcolon-like command that disables French colon spacing

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#925]
From https://github.com/josephwright/biblatex-phys/issues/16

In some instances it might be useful to have an `\addcolon`-variant that does not obey the French typography rules even if French is enabled.

Something like
```latex
\documentclass{article}
\usepackage{csquotes}
\usepackage[french]{babel}
\usepackage[style=phys,articletitle=false,eprint=true]{biblatex}

\makeatletter
\DeclareFieldFormat{eprint:arxiv}{%
  \let\FDP@colonspace\empty
  \csuse{NoAutoSpacing}%
  \ifhyperref
    {\href{https://arxiv.org/\abx@arxivpath/#1}{%
        arXiv\addcolon
        \nolinkurl{#1}%
        \iffieldundef{eprintclass}
          {}
          {\addspace\UrlFont{\mkbibbrackets{\thefield{eprintclass}}}}}}
    {arXiv\addcolon
      \nolinkurl{#1}%
      \iffieldundef{eprintclass}
        {}
        {\addspace\UrlFont{\mkbibbrackets{\thefield{eprintclass}}}}}}
\makeatother

\addbibresource{biblatex-examples.bib}

\begin{document}
\nocite{baez/article}
\printbibliography
\end{document}
```

We need

1. a good name,
2. to find a stable implementation ideally for both `babel` and `polyglossia`,
3. to check if other languages do similar things.

**Comment by jspitz** [comment]
I'd prefer a more general name than `\addcolonnonfrench`, e.g. `\addnonspacedcolon`, since spacing is not only done for French (in polyglossia for instance also for ecclesiastic Latin and Sanskrit)

**Comment by moewew** [comment]
Mhh, good point. I liked the analogy with `\nonfrenchspacing`, but this is something slightly different anyway...

I'm beginning to think maybe this whole macro was a bad idea. It is quite tricky to work against all possible modifications to colons that a language module might throw at us. On that note: Can the colon spacing in `polyglossia`'s ecclesiastical Latin or Sanskrit be turned off?

**Comment by jspitz** [comment]
> Can the colon spacing in `polyglossia`'s ecclesiastical Latin or Sanskrit be turned off (locally)?

Not yet. This feature might be added eventually. 

With polyglossia, a probably safe way would be to use `\foreignlanguage{latex}{:}`. The latex language is an internal language which is always loaded by polyglossia. It more or less conforms to English.

**Comment by moewew** [comment]
> > Can the colon spacing in `polyglossia`'s ecclesiastical Latin or Sanskrit be turned off (locally)?
>
> Not yet. This feature might be added eventually. 

Oh bother. It would have been too easy if `\NoAutoSpacing` would be available in all languages that mess with spacing.

> With `polyglossia`, a probably safe way would be to use `\foreignlanguage{latex}{:}`.

Thanks for that suggestion. I was hoping I could get away with something that works with both `babel` and `polyglossia`, but I guess that was never going to happen.

---

Still not sure if maybe we should back out and just remove this macro. The mess it is to implement and maintain seems hardly worth the limited use cases it is going to have.

**Comment by jspitz** [comment]
> Still not sure if maybe we should back out and just remove this macro. The mess it is to implement and maintain seems hardly worth the limited use cases it is going to have.

FWIW I tend to agree.

**Comment by moewew** [comment]
I reverted https://github.com/plk/biblatex/commit/f6b081700b74d2b3f02805f4fe4581d6aaf29f74 in https://github.com/plk/biblatex/commit/97a983b31dcea1101981ab26568eeaa31e07ae2d. Currently it is too messy to implement a stable solution that works across all language modules. Setting this to *wontfix* for now.
