### ISSUE TITLE
Give more useful error for biblatex-generated aux files

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#926]
Via https://tex.stackexchange.com/q/510145/35864

If a document is compiled with `\usepackage{biblatex}` and that call is later removed, there will be some leftover commands in the `.aux` file that trigger undefined control sequence errors. Since the names point to internal macro names, the errors are not all that helpful in figuring out the cause of the error and the solution.

* Is it possible to let a `biblatex`-generated `.aux` run without errors even when `biblatex` is not loaded? (Short of flooding the `.aux` with `\providecommand`s or `\ifcsundef`s)?
* If that is not possible, should we at least add a `\@ifpackageloaded` test at the beginning as in the `.bbl` file?

**Comment by moewew** [comment]
@josephwright Does the LaTeX team (or you) have an opinion here? Would it be appropriate to add `\@ifpackageloaded{biblatex}` with a suitable warning or error message to the `.aux` file? Should we instead try to suppress errors with `\providecommand`s? Or should we not bother and hope that users get the hint and delete the `.aux` themselves?

**Comment by josephwright** [comment]
I think if you remove a major package, you are really on your own with the `.aux` file. You could add a section to the manual (and perhaps add a TeX-sx question/answer) giving a 'hint'.

**Comment by dbitouze** [comment]
>I think if you remove a major package, you are really on your own with the `.aux` file.

Apart from `biblatex`, I don't know any major packages that are blocking the next compilation if they are removed.

**Comment by moewew** [comment]
`babel` comes to  mind, but also `polyglossia`

```latex
\documentclass[british]{article}

\usepackage{babel}

\begin{document}
Lorem
\end{document}
```

Essentially everyone who writes to the `.aux` file and uses package-specific commands.

**Comment by moewew** [comment]
I guess I will close this as 'wontfix' then. If anyone feels strongly about this and ideally has an idea what we should do, feel free to comments, then we can reopen this.

**Comment by user202729** [comment]
I just come across this. Personally I think anything that can be done that makes the program better (i.e. more convenient for the user) while otherwise having no disadvantage, should be implemented.

You already listed the options possible.

1. add appropriate `\providecommand\…` and `\@nameuse`.

	I don't think cluttering the aux is particularly bad, nobody look at it anyway and the overhead is < 2×.

	**The only disadvantage I can think of is that it's slightly harder to maintain the package for you.**
	But not that much I think (with the appropriate abstraction you don't even need to duplicate any code)

	Worth noting that babel has since then fixed the issue with `\providecommand` and `\@nameuse`:

	```tex
	\providecommand\babel@aux[2]{}
	\@nameuse{bbl@beforestart}
	\babel@aux{british}{}
	```

2. if `biblatex` package disappear, stop reading the rest of the aux file.

	I think this is quite easy to implement, just add something like the following to the start of the aux file:

	```tex
	\@ifpackageloaded{babel}{}{\endinput}
	```

	Again, **I can't think of any disadvantage on your side**, and even the disadvantage on the user's side is minimal (worst case is one more compilation pass on that time, but if biblatex is removed then you'd likely need some more compilation passes anyway)

3. add warning for the user with `\@ifpackageloaded`.

	**I can't think of any disadvantage on the maintainer (your) side**, only that of the user (need to manually trigger recompilation).

Your pick. If you find implementing (1) difficult you can stick with (2) (although I can try to help).
