### ISSUE TITLE
Handling of multiple publishers and locations

### ISSUE THREAD

**Issue by denismaier** [plk/biblatex#932]
Is there a way to handle multiple publishers and locations in a way where publishers and locations are treated as belonging together? So that we can have "Location A: Publisher A; Location B: Publisher B" in the bibliography? If the answer is no: Could this be implemented somehow?

**Comment by moewew** [comment]
You may be interested in dcpurton's `biblatex-sbl` style that does something like that

https://github.com/dcpurton/biblatex-sbl/blob/8019fd7eb3a781585f61a66998c3a6024ad21071/latex/biblatex-sbl.def#L1942-L2091

**Comment by denismaier** [comment]
Interesting. Didn't know that. What about adding this to the standard styles? Or, perhaps there is an easier way, if we change field formats? Something like the extended name format. Or would working with field annotations be an option?
I know this would be a big change, but anyway...

**Comment by moewew** [comment]
I don't think we can change the behaviour of the standard styles with respect to `publisher` and `location` here. The current behaviour has been with us all along and changing it would break backwards  compatibility quite a bit. (Though I would accept the argument that the number of affected users is probably going to be quite small.) At least the way `biblatex-sbl` handles this is purely on the style level and so adding that code to the standard styles but not using it seems ... unnecessary and just bloats the files.

----

Something like an extended name format sounds attractive here since a multi-level/dimension data model seems to be a better fit for this task. Then it would be easier to model the dependency between the data, for example
```
publisher:
  - Publisher A
    location: Location A
  - Publisher B
    location: Location B
  - Publisher C
    location: Location C
```

But that would not only require a major overhaul of how we do things at the moment (and lots of weork to preserve backwards compatibility) but also a solid idea of what to implement in the first place.

---

In a way the annotation feature is a simplified version of a more complex extended name/data format and it could be used here.

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\DeclareListFormat{publisher}{%
  \usebibmacro{list:delim}{#1}%
  \hasitemannotation[publisher][location]
    {\getitemannotation[publisher][location]%
     \addcolon\space}
    {}%
  #1\isdot
  \usebibmacro{list:andothers}}

\renewbibmacro*{publisher+location+date}{%
  \printlist{publisher}%
  \setunit*{\addcomma\space}%
  \usebibmacro{date}%
  \newunit}

\begin{filecontents}[force]{\jobname.bib}
@mvbook{nietzsche:ksa,
  author       = {Nietzsche, Friedrich},
  title        = {Sämtliche Werke},
  date         = 1988,
  editor       = {Colli, Giorgio and Montinari, Mazzino},
  edition      = 2,
  volumes      = 15,
  publisher    = {Deutscher Taschenbuch-Verlag and Walter de Gruyter},
  publisher+an:location = {1="München";2="Berlin"},
  langid       = {german},
  subtitle     = {Kritische Studienausgabe},
}
\end{filecontents}

\addbibresource{\jobname.bib}


\begin{document}
\cite{nietzsche:ksa}
\printbibliography
\end{document}
```

One obvious drawback here (I'm sure there are more) is that now `location` is not parsed as a list any more, so 
```
  publisher+an:location = {1="München";2="Berlin and New York and Wanne-Eickel"},
```
won't work as one might hope.

**Comment by denismaier** [comment]
Thanks for your detailed response.

My favorites would be option 2 (extended publisher format) or 3 (annotations), but if we can't represent multiple locations for a single publisher with option 3, then this would rule out this option. Or what about this:

```
publisher    = {Deutscher Taschenbuch-Verlag and Walter de Gruyter},
publisher+an:location = {1="München";2.1="Berlin";2.2="New York";2.3="Wanne-Eickel"},
```

Would that be feasible somehow?

Option 2 seems clearly the superior and more structured approach, but I totally understand that this would entail much work and would also need a clear and solid concept.

**Comment by plk** [comment]
I am open to having multiple literal annotations - this is currently a limitation. You can still do this though currently:

```
publisher+an:location = {1="München";2=berlin,newyork,wanne-eickel},
```

and then do a bit of work with the annotation macros to print what you want. I suppose what you really want is:

```
publisher+an:location = {1="München";2="Berlin","New York","Wanne-Eickel"},
```

**Comment by denismaier** [comment]
Yes, that looks really good. Especially:
```
publisher+an:location`` = {1="München";2="Berlin","New York","Wanne-Eickel"},
```

**Comment by plk** [comment]
I looked at this and there is very little gain in implementing this explicitly - it's easy to just to this:

```
publisher+an:location`` = {1="München";2="Berlin,New York,Wanne-Eickel"},
```

and they split CSV value of the literal annotation in the style with the usual `\docsvlist` macro.

**Comment by denismaier** [comment]
Ok. So what should be done about this? Is there a way to add this to the standard styles without breaking to much? Obviously, we would still want to allow for regular `location` fields.  But I have the impression that this way is clearly superior.

**Comment by moewew** [comment]
Here is a solution that loops through the CSV field as PLK suggested
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\makeatletter
\newrobustcmd*{\blx@csvtoblxlist@i}[2]{%
  \csappto{abx@list@#1}{{#2}}%
  \advance\blx@tempcnta\@ne}

\newrobustcmd*{\blx@csvtoblxlist}[2]{%
  \blx@tempcnta\z@
  \cslet{abx@list@#2}\@empty
  \forcsvlist{\blx@csvtoblxlist@i{#2}}{#1}%
  \ifltxcounter{#2}
    {}
    {\newcounter{#2}%
     \newtoggle{abx@bool@more#2}}%
  \csname c@#2\endcsname\blx@tempcnta\relax}

\DeclareListFormat{publisher}{%
  \usebibmacro{list:delim}{#1}%
  \hasitemannotation[publisher][location]
    {\letcs\blx@thispublisherlocation{abx@annotation@literal@item@publisher@location@\the\value{listcount}}%
     \expandafter\blx@csvtoblxlist\expandafter{\blx@thispublisherlocation}{publisherlocation}%
     \begingroup
     \printlist{publisherlocation}%
     \endgroup
     \addcolon\space
     }
    {}%
  #1\isdot
  \usebibmacro{list:andothers}}
\makeatother

\renewbibmacro*{publisher+location+date}{%
  \printlist{publisher}%
  \setunit*{\addcomma\space}%
  \usebibmacro{date}%
  \newunit}

\begin{filecontents}[force]{\jobname.bib}
@mvbook{nietzsche:ksa,
  author       = {Nietzsche, Friedrich},
  title        = {Sämtliche Werke},
  date         = 1988,
  editor       = {Colli, Giorgio and Montinari, Mazzino},
  edition      = 2,
  volumes      = 15,
  publisher    = {Deutscher Taschenbuch-Verlag and Walter de Gruyter},
  publisher+an:location = {1="München";2="Berlin,New York,Wanne-Eickel"},
  langid       = {german},
  subtitle     = {Kritische Studienausgabe},
}
\end{filecontents}

\addbibresource{\jobname.bib}


\begin{document}
\cite{nietzsche:ksa}
\printbibliography
\end{document}
```

I can absolutely not see a good user-side interface for any of this, so unless somebody steps forward with an idea, I'm afraid there is not going to be any progress here any time soon.

**Comment by moewew** [comment]
Closing this for now.

I don't think we can change the standard styles (for output-related backwards compatibility as well as customisation-related backwards compatibility).

The idea of interleaved data fields sounds interesting, but for an implementation into the core it would need a good specification for a user-facing interface (if anyone has in idea, feel free to comment here).

For now there are the solutions from `biblatex-sbl` linked above as well as the field annotation idea shown above.
