### ISSUE TITLE
Change to default ANNOTATION field driver

### ISSUE THREAD

**Issue by plk** [plk/biblatex#933]
It's common in annotated bibliographies to cite other works in the annotation. This is a problem in some cases as in the bibliography, the toggle `blx@bibliography` is true and this sets `max/minnames` counters to `max/minbibnames`. This breaks the citations of other works if max/minnames is different for cites and bibliography. It's also unintuitive as one expects citations to obey max/mincitenames but they actually obey max/minbibnames. I would suggest changing the default annotation driver to:

```
\newbibmacro*{annotation}{%
  \togglefalse{blx@bibliography}%
  \iffieldundef{annotation}
    {\printfile[annotation]{\bibannotationprefix\thefield{entrykey}.tex}}
    {\printfield{annotation}}%
  \toggletrue{blx@bibliography}}
```

Which gives intuitive results. @moewew - thoughts?

**Comment by moewew** [comment]
Citations in bibliographies are a nuisance (see also https://github.com/plk/biblatex/issues/904).

Currently `\cite` commands detect that they are used in a bibliography context and then prefer some `bib`  settings over `cite` settinsg (in particular with `(min|max)(bib|cite)names`). This is not something I find particularly intuitive and I would like to get rid of that inconsistency. But there are some styles that use special `\cite...` commands to produce parts of the bibliography output (I'm mainly thinking of `biblatex-chicago` here). While I initially thought this was a clever idea when I first saw it, I think that nowadays there should be no reason to use `\cite...` commands any more: It should be possible to get this done more efficiently with bibmacros and `\entrydata` if needed. ... So I'm not sure if we can do something here.

I'm not particularly fond of throwing internal toggles like `blx@bibliography` into the definition of `annotation`, but I think this would be the simplest way out of this impasse. Maybe we could at least keep the change to the toggle local with a group or by shoehorning it into the field format instead?

```latex
\DeclareFieldFormat{annotation}{\togglefalse{blx@bibliography}#1}
```

(If we used a field format the user who overwrites the format would be responsible for making sure the toggle has the value they expect - not sure if that's better or worse).

**Comment by plk** [comment]
I was thinking that not using the format made this internal less visible and I can't see any reason why anyone would want to change it. The toggle `blx@bibliography` does little else but control the max/minnames aliasing anyway.

Did you mean that `\cite` commands are forcing `min/maxbibnames` in a bibliography? That is very unintuitive. Forcing `min/maxcitenames` would be more intuitive to me.  However, `ANNOTATION` seems a clear case - it is the main source for cites in the bibliography and they should adhere to the citation style. I came across this explicit requirement as I am going through the APA 7th edition to update the style (a lot of work ...) and this comes up (p. 308) where the citation style is clearly required in annotations and this absolutely needs `min/maxcitenames` and not `min/maxbibnames`.

**Comment by moewew** [comment]
Mhh yes, the field format may not be the right place for that either. I guess
```latex
\newbibmacro*{annotation}{%
  \begingroup
  \togglefalse{blx@bibliography}%
  \iffieldundef{annotation}
    {\printfile[annotation]{\bibannotationprefix\thefield{entrykey}.tex}}
    {\printfield{annotation}}%
  \endgroup}
```
is the least bad of all possible options.

---

> Did you mean that `\cite` commands are forcing `min/maxbibnames` in a bibliography? That is very unintuitive.

I'd have to look into this in more details (I probably won't be having time for that until after the weekend) but I think `\cite` commands explicitly don't set the `blx@citation` flag when they are called if `blx@bibliography` is already true

https://github.com/plk/biblatex/blob/a1a5a78c9d00ae69e062c9dbcf3e57dfbccc6a8e/tex/latex/biblatex/biblatex.sty#L11434-L11446

Conversely, if we are in a citation context, we don't toggle true `blx@bibliography`

https://github.com/plk/biblatex/blob/a1a5a78c9d00ae69e062c9dbcf3e57dfbccc6a8e/tex/latex/biblatex/biblatex.sty#L9402-L9411

`blx@bibliography` switches between `...citenames` and `..bibnames` as you say

https://github.com/plk/biblatex/blob/a1a5a78c9d00ae69e062c9dbcf3e57dfbccc6a8e/tex/latex/biblatex/biblatex.sty#L7168-L7192

This means that `\cite` does not obey `(max|min)citenames` in the bibliography and takes the surrounding `(max|min)bibnames`. In a way one could say that it forces the bibliography name settings if used in the bibliography, yes.

**Comment by plk** [comment]
That's clearer, thanks - I'm somewhat drowning in APA nonsense requirements currently (`Author Sr` sorts before `Author Jr` because they are clearly "older"! - that's a real, explicit requirement ...). Given that, as you say, some people actually want bib context for cites, I suppose annotations are safe at least as this is a relatively clear case ...

**Comment by moewew** [comment]
@plk Do you want the `annotation` bibmacro changed in `biblatex.def` for standard `biblatex` as well, or are you OK with redefining the macro in `biblatex-apa`?

**Comment by plk** [comment]
Yes, I think that makes sense since you wont' have a biblipgraphy in an annotation but you might well have cites.

**Comment by moewew** [comment]
OK, done in https://github.com/plk/biblatex/commit/9bec83636d27845f1174133dbaeedd04e279723f.
