### ISSUE TITLE
\MakeSentenceCase and starred macros

### ISSUE THREAD

**Issue by jspitz** [plk/biblatex#941]
This was moved here from https://github.com/josephwright/csquotes/issues/16.

`\MakeSentenceCase` apparently fails to handle content which includes starred commands. A case in point is `\enquote*`. See the following MWE with `biblatex-apa`:
```tex
\documentclass{article}

\begin{filecontents}{enquoting.bib}
	@article{test,
		title = {\enquote*{Enquoted Title}},
		journal = {A Journal},
		author = {John Doe},
		year = {2017},
		pages = {1-116},
	}
\end{filecontents}

\usepackage[english]{babel}
\usepackage{csquotes}
\usepackage[style=apa]{biblatex}
\addbibresource{enquoting.bib}

\begin{document}

\cite{test}

\printbibliography
	
\end{document}
```

This yields:
```
! Argument of \csq@qclose@ii has an extra }.
<inserted text> 
                \par 
l.27 	
```
and
```
! Paragraph ended before \csq@qclose@ii was complete.
<to be read again> 
                   \par 
l.27 
```

The following fixes the problem for me, but I am not sure it's the recommended fix:
```diff
diff --git a/tex/latex/biblatex/biblatex.sty b/tex/latex/biblatex/biblatex.sty
index 97f5c984..731571f3 100644
--- a/tex/latex/biblatex/biblatex.sty
+++ b/tex/latex/biblatex/biblatex.sty
@@ -4054,6 +4054,9 @@
   \futurelet\@let@token\blx@mksc@eval}
 
 \def\blx@mksc@eval{%
+  \ifx\@let@token*
+    \expandafter\blx@mksc@cs
+  \fi
   \ifx\@let@token\blx@mksc@end
     \expandafter\blx@mksc@end
   \fi

```

**Comment by jspitz** [comment]
Simpler MWE:
```tex
\documentclass{article}
\usepackage[english]{babel}
\usepackage{csquotes}
\usepackage{biblatex}

\begin{document}
	
\MakeSentenceCase{\enquote*{Text}}

\end{document}
```

**Comment by jspitz** [comment]
(in the long run, should there be any plans to move `biblatex` towards `latex3`, it could be considered rewriting `\MakeSentenceCase` on top of `\tl_mixed_case:n`)

**Comment by josephwright** [comment]
There are some things going on with the `expl3` case functions: expect stable versions with new names soon-ish, probably as part of LaTeXe 2020-02-02 .

**Comment by jspitz** [comment]
OK. BTW @josephwright I quickly tested and saw that `\tl_mixed_case:n` won't produce the correct result with `\enquote*` (as opposed to unstarred `\enquote`)
```tex
\ExplSyntaxOn	
\tl_mixed_case:n{\enquote*{Text~ Text}}
\ExplSyntaxOff
```
produces `'text text'` rather than `'Text text'`. Is this expected?

**Comment by moewew** [comment]
I guess in the long (or maybe not so long) run we should switch to LaTeX3 here (and in other places).

@josephwright I seem to remember you did something with the sentence casing a while ago. Does https://github.com/moewew/biblatex/commit/a6f312751c9784115d72fe65ab47e6bf93b311c5 (a slightly modified version of what @jspitz suggested above) look right? (I'd normally not touch that code with a barge pole, but since @jspitz provided a fix, I thought I'd try my best.)

**Comment by josephwright** [comment]
The upcoming update for `\tl_mixed_case:n` should handle `\csquotes*`: hopefully early in the new year.

**Comment by josephwright** [comment]
@moewew change looks OK to me, but yes, much better to shift to the L3 code: I suggest look at this after 2020-02-02 kernel release (big stuff coming).

**Comment by moewew** [comment]
@josephwright Thank you very much! Merged https://github.com/plk/biblatex/commit/a6f312751c9784115d72fe65ab47e6bf93b311c5.

@jspitz Thank you also to you for the suggested fix.

**Comment by jspitz** [comment]
Thanks all for addressing this so fast!

**Comment by moewew** [comment]
For https://github.com/plk/biblatex/issues/960 I pushed an extremely preliminary drop-in replacement for `biblatex`'s case functions to https://github.com/plk/biblatex/compare/dev...moewew:l3text. We will definitely have to think about the issues mentioned in https://github.com/plk/biblatex/issues/960#issuecomment-575914507. Comments are appreciated.

**Comment by jspitz** [comment]
Regarding https://github.com/plk/biblatex/issues/960#issuecomment-575914507 I think that many people will rely on brace protection in their existing bib databases. Most importantly in cases where English titles get sentence-cased and people protect words that must not be lower-cased (such as [language] names).

So in order to not break documents I'd very strongly opt for maintaining brace protection. In the long run, I'd argue in favor of implementing for some sane semantic markup for case protection (as I did in another ticket).

**Comment by moewew** [comment]
@jspitz Thank you for the comment (I copied it over to #960). In order to avoid two concurrent discussions about the same thing in different issues I will lock the conversation here and encourage everyone who wants to have a say in the `\MakeSentrenceCase` issue to make their voice heard at #960.

In case people want to say something specifically about this issue, open a new issue or otherwise give me a shout.
