### ISSUE TITLE
Error message for unsupported languages

### ISSUE THREAD

**Issue by wehro** [plk/biblatex#945]
With the following document, I get the following error message.
```
\begin{filecontents}{Literatur.bib}
@mvbook{AH,
	shorthand = {\textsc{ah}},
	editor = {Guido Maria Dreves and Clemens Blume},
	title = {Analecta hymnica medii ævi},
	volumes = 55,
	location = {Lipsiæ},
	year = {1886--1926}
}
\end{filecontents}

\documentclass{article}
\usepackage{polyglossia}
\usepackage{biblatex}
\setmainlanguage{latin}
\addbibresource{Literatur.bib}

\begin{document}
\cite{AH}
\printshorthands
\end{document}
```

```
Package biblatex Warning: Language 'latin' not supported.
(biblatex)                Using fallback language 'english' on input line 18.

(/usr/local/texlive/2019/texmf-dist/tex/latex/biblatex/lbx/english.lbx)
(./Hymnarium.bbl)
! Undefined control sequence.
<argument> \biblistname 
                        
l.21 \end
         {document}
```
The warning concerning the unsupported language is as expected because biblatex does not support Latin so far.
But the error message `Undefined control sequence` should not appear.

**Comment by moewew** [comment]
Thanks for reporting this.

`\biblistname` is used by `biblatex` just like `\bibname` and `\refname`. But while the latter two are usually defined by `babel`/`polyglossia` isn't, it might end up completely undefined if no `.lbx` file was loaded. In theory that shouldn't happen as the warning says
```
Using fallback language 'english' on input line 18.
```
But that bit of the warning doesn't seem to be correct any more.

I'm not sure what would be more useful there
* falling back to `english` for unsupported languages, or
* not loading anything and falling back to bold bibstrings.

If we make `biblatex` load a fallback language the issue should go away, otherwise we need to explicitly define a fallback for `\biblistname` (only in `biblatex` context or globally?).

**Comment by moewew** [comment]
@plk What do you think? 

Should we
* restore the automatic fallback to the main document language/English, or
* not load anything and fall back to bold strings and warnings (in that case a user can get back an arbitrary existing language with `\DeclareLanguageMapping{latin}{english}`)?

**Comment by plk** [comment]
I incline towards the latter - the former is more like a silent failure.

**Comment by moewew** [comment]
That would be my preference as well, but I'm wondering how many people relied on `biblatex` silently (well, with a warning to be fair, but who reads log files anyway) remapping unknown languages to English.

**Comment by plk** [comment]
I doubt it’s many as such users tend to see when something is wrong, which would be obvious. I’d rather give sone sign than gove then clearly wrong output ...

**Comment by moewew** [comment]
Good. I'll see to it.

This would probably just mean that we provide a dummy `\biblistname` and leave the rest as is.

----

If people complain, we can get English fallback as follows

```latex
% usually \blx@maplang is called as
% \blx@maplang{<language>}{<replacement language>}
% for easier expansion control this command has
% {<replacement language>}{<language>}
\newcommand*{\blx@maplang@and@execute@switched}[2]{%
  \blx@maplang{#2}{#1}%
  \csuse{abx@extras@#1}%
  \csuse{abx@strings@#1}}

% {<language>}
\def\blx@langsetup#1{%
  \blx@lbxinput{#1}
    {\edef\blx@languagename{#1}}
    {\blx@warning
       {Language '#1' not supported.\MessageBreak
        Using fallback language '\blx@languagename'}%
     \blx@lbxinput{\blx@languagename}
       {\expandafter\blx@maplang@and@execute@switched
          \expandafter{\blx@languagename}{#1}}
       {\blx@err@nolang{\blx@languagename}}}}
```

**Comment by moewew** [comment]
Done in https://github.com/plk/biblatex/commit/10dced5f406d4acfe6e809261968f83b28e336b9. There is no functional change to 3.14, just an adjustment to make sure it is documented that `biblatex` uses dummy defs and not English.

**Comment by plk** [comment]
Feel free to merge.

**Comment by moewew** [comment]
Done.
