### ISSUE TITLE
Other datatype support for \addbibresource

### ISSUE THREAD

**Issue by zwz** [plk/biblatex#950]
Those days I encounter more and more websites that do not provide bibtex format of bibliographies, but ris or endnote format instead.

And then I find [biblatex-cheatsheet.pdf](https://ctan.org/pkg/biblatex-cheatsheet), which shows that one can use `ris`, `endnote` datatype in `\addbibresource`.  I am quite excited  as it is a perfect solution. However, in the latest biblatex's document, I cannot find them.

IMHO, it brings a lot of convenience if biblatex supports those datatype inherently. So I am just wondering why and from which version (I may switch to the old version) they are not supported any more.

**Comment by plk** [comment]
These formats were removed quite some time ago as they are fairly terrible formats which nobody was using. Particularly with upcoming multiscript support, which these formats cannot do, the decision was taken to remove them. This is literally the first time anyone has mentioned them in years ...

**Comment by zwz** [comment]
What do you mean by multiscript support?

**Comment by plk** [comment]
Multiple forms/languages for fields and within fields:

https://github.com/plk/biblatex/wiki/Multiscript-Design-Notes

biblatex will be able to auto-switch babel/polyglossia languages per-entry/per-field/per-list item and entries will be able to contain more than one script alternate of fields.

**Comment by zwz** [comment]
Good to know it.
Then I guess I have to find some tools to convert those formats.

**Comment by zwz** [comment]
I find bibutils converts those formats into an XML-intermediate bibliography format MODS.
Would MODS be supported in the future?

**Comment by plk** [comment]
Unlikely - but bibutils can convert from MODS to bibtex so that should be fine.

**Comment by zwz** [comment]
But I find that some types of bibliography, for example patent, are not supported by bibtex.

**Comment by moewew** [comment]
@zwz Do you mean BibTeX or `biblatex`?

If you mean BibTeX, then we have to distinguish two things

1. The BibTeX data format (`.bib` files)
2. BibTeX styles

The BibTeX data format easily supports basically anything you can write in its general format. For patents, you could just write
```latex
@patent{laufenberg,
  author       = {Laufenberg, Xaver and Eynius, Dominique and Suelzle, Helmut
                  and Usbeck, Stephan and Spaeth, Matthias and Neuser-Hoffmann,
                  Miriam and Myrzik, Christian and Schmid, Manfred and Nietfeld,
                  Franz and Thiel, Alexander and Braun, Harald and Ebner,
                  Norbert},
  title        = {Elektrische Einrichtung und Betriebsverfahren},
  number       = 1700367,
  date         = {2006-09-13},
  holder       = {{Robert Bosch GmbH} and {Daimler Chrysler AG} and {Bayerische
                  Motoren Werke AG}},
  type         = {patenteu},
}
```
(taken from `biblatex-examples.bib`).

But for the output in the bibliography it is relevant if (and how exactly) the bibliography style you are going to use supports the entry type. The styles have complete control over which entry types they support, which fields they read and what output they produce. The BibTeX documentation has established a core of commonly used entry types and fields that are supported by almost all styles. But for less commonly used types and fields there is a lot of variation in the BibTeX style world: Some older styles don't know an `@online` type and don't have a `url` field. Some newer styles do.

A short grep on my installed BibTeX styles shows that there are only a few with support for a `@patent` type. I found styles of the `abntex2`, `achemso`, `din1505`, `gost`, `ieeetran` and `rsc` bundles.


---

I don't quite understand how this is related to the initial question of datatype support.

**Comment by zwz** [comment]
Thank you for your explanation.

Well, what I mean is that if I have a `patent` entry in `ris` format, and I convert it to bibtex by bibutils (through `ris2xml | xml2bib`), it becomes a `misc` entry.

I do know that bibtex format is powerful, but lacks such utilities to make it be more easily adopted.

**Comment by moewew** [comment]
I guess one can configure bibutils to keep `patent` a `@patent` (but I wouldn't know how, sorry). Again, I'm guessing but I'd have thought that the exact situation I described above (most BibTeX styles not supporting `@patent`) is the reason for producing a `@misc` entry here instead of going for `@patent`.

**Comment by zwz** [comment]
I could not find such configuration, either. In fact, xml2bib reports
```
xml2bib: Cannot identify TYPE in reference 1  laufenberg (defaulting to @Misc)
```

I got your meaning. But patent TYPE is just one example.

**Comment by moewew** [comment]
Closing this as *wont fix*. As discussed above it is too painful to support other data formats in the backend for too little gain. If you have data in RIS or endnote format it should be possible to convert it to `.bib` via some external tools. While I assume that for most uses a conversion is possible quite smoothly I expect there are edge cases where one format simply doesn't support all the features of another format, so manual checking is probably required (that is also why I think that directly supporting those formats in Biber is tricky: you will have to deal with cases where the data models don't match).

**Comment by plk** [comment]
Just to be clear, biber did used to support RIS and Endnote XML format but it was hardly ever used, the maintenance was a pain and the datamodel for those formats is so primitive that they couldn't be used with most biber features.
