### ISSUE TITLE
Brackets in `title` key of `\printbibliography` not correctly handled.

### ISSUE THREAD

**Issue by Skillmon** [plk/biblatex#952]
The current implementation of `biblatex` often uses delimited arguments with unknown content without further precautions (e.g., it uses `\foo[#1]` to forward argument `#1` to a macro `\foo` that grabs its argument delimited by `[]`). This can lead to problems when `#1` contains a closing `]`. One example of this issue is, if one provides the following argument to `\printbibliography`:

```latex
\printbibliography[title={Title [Title]}]
```

The braces will be stripped by the key=val-parser (which is the normal behaviour), but `Title [Title]` will later be forwarded as is to `\blx@head@bibliography` as the optional argument without further precautions, so that the argument will be given as

```latex
\blx@head@bibliography[Title [Title]]
```

instead of

```latex
\blx@head@bibliography[{Title [Title]}]
```

**Comment by moewew** [comment]
Thanks for tracking down the issue.

MWE from https://tex.stackexchange.com/q/522902/35864 for proper testing
```latex
\documentclass[]{article}

\usepackage{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{sigfridsson}.

\printbibliography[title = {Test [Test]}]
\end{document}
```

**Comment by Skillmon** [comment]
@moewew note that I did not too much digging, I don't know whether there will be other issues in the way this is handled, but that's the one which caught my attention, and since there are many occurrences in `biblatex.sty` that use `[#1]` or similar, I quick-fixed this in that pull request.

**Comment by moewew** [comment]
`biblatex` 3.15 with the more defensive bracing has been released and is available in both TeX live and MikTeX. 

The MWE posted above compiles fine now. Thanks everyone.
