### ISSUE TITLE
typo in german.lbx

### ISSUE THREAD

**Issue by oscar-0** [plk/biblatex#954]
Line 266 in  biblatex/tex/latex/biblatex/lbx/german.lbx currently reads

  bycontinuator    = {{fortgef\"urt von}{fortgef\adddotspace von}},

but should read

  bycontinuator    = {{fortgef\"uhrt von}{fortgef\adddotspace von}},

instead, i.e. the missing "h" should be added.

**Comment by moewew** [comment]
Oh, how embarrassing. It's been like that for at least nine years and in all the time no one noticed that.

Do you want to open a pull request with the changes or would you rather have me add the "h"?

**Comment by oscar-0** [comment]
Sounds like you adding the "h" is the more straightforward approach?

**Comment by moewew** [comment]
Sure. I just didn't want to "snatch" the fix from you in case you were interested in contributing it directly to the source yourself.

**Comment by moewew** [comment]
Fixed in https://github.com/plk/biblatex/commit/4eddcae90b097cf65184fb42eb20b80ab2030094.

**Comment by moewew** [comment]
`biblatex` 3.15 with the fix is available now in MikTeX and TeX live.
