### ISSUE TITLE
Concatenated Editor Roles, Expressed as Functions: weird for some strings 

### ISSUE THREAD

**Issue by dbitouze** [plk/biblatex#956]
Some of the concatenated editor roles, expressed as functions, such as `editortr`, are not problematic because "editor" and "translator" both represent human beings.

By contrast, some other ones look a bit weird because, e.g. for `editorin` ("editor and introduction"), `03-localization-keys.tex` says "Used if editor/introduction are identical" but:

- "editor" does represent human being,
- "introduction" does*n't* represent human being.

In this case, wouldn't "edition and introduction" (followed by a necessary "by") be better than "editor and introduction"?

**Comment by moewew** [comment]
Strings like `editor`, `editorin` usually appear after the respective name, either separated with a comma or in parentheses

> Emma Sigfridsson, editor

> Emma Sigfridsson (editor and introduction)

These aren't complete English sentences, so I wouldn't hold these strings to the same standard as I would in the sentence

> Emma Sigfridsson is an editor

where

> *Emma Sigfridsson is an editor and (an) introduction

would be odd to say the least.

The German strings indeed do something like you suggest, they have

https://github.com/plk/biblatex/blob/35a50374b5545d36c9a2c760c75b6d9a5554d73c/tex/latex/biblatex/lbx/german.lbx#L95

but

https://github.com/plk/biblatex/blob/35a50374b5545d36c9a2c760c75b6d9a5554d73c/tex/latex/biblatex/lbx/german.lbx#L132-L133

You can't see that in the abbreviated forms, which is probably what most people use (and conveniently avoids gender issues).

I'm not a native speaker, but for English the "edition" in

> edition and introduction

sounds very odd to me.

I'm not really fond of fondling with these things just for semantic uniformity. I think the combined strings are more of a gimmick anyway (https://github.com/plk/biblatex/issues/390, https://github.com/plk/biblatex/issues/77). Do you have data points that show that these strings should be different in English? Or were you asking about French or other language strings? (I won't say anything about languages other than English or German. I should note that if there is no way to make these strings sound good in other languages, the strings can just be dropped, in which case no concatenation takes place.)

**Comment by dbitouze** [comment]
>Strings like editor, editorin usually appear after the respective name, either separated with a comma or in parentheses

    Emma Sigfridsson, editor

    Emma Sigfridsson (editor and introduction)

Ah, OK.

>These aren't complete English sentences, so I wouldn't hold these strings to the same standard as I would in the sentence

    Emma Sigfridsson is an editor

>where

    *Emma Sigfridsson is an editor and (an) introduction

>would be odd to say the least.

I see.

>The German strings indeed do something like you suggest, they have

    editor           = {{Herausgeber}{Hrsg\adddot}}, 

>but

     editorin         = {{Herausgabe und Einleitung}% 
                        {Hrsg\adddot\ und Einl\adddot}}, 

>You can't see that in the abbreviated forms, which is probably what most people use (and conveniently avoids gender issues).

Indeed.

>I'm not a native speaker, but for English the "edition" in

    edition and introduction

>sounds very odd to me.

I'm not a native speaker either, and my English is certainly not as good as yours so I trust you (though "Emma Sigfridsson (editor and introduction)" sounds very odd to me since reading this I have the impression that Emma _is_ an _introduction_ :)

>Do you have data points that show that these strings should be different in English?

No. I stumbled upon these strings when looking at `03-localization-keys.pdf`.

>Or were you asking about French or other language strings?

Mostly with French translations in mind but, even in English, I cannot conceive Emma being an introduction :)

> (I won't say anything about languages other than English or German. I should note that if there is no way to make these strings sound good in other languages, the strings can just be dropped, in which case no concatenation takes place.)

No, no need to drop them. I'll just revise the French translations in the spirit of German ones.

**Comment by moewew** [comment]
OK. The changes for French are merged in https://github.com/plk/biblatex/pull/957. I'll mark this as fixed now. If anyone else wants to have a go at the combined string in their native language, feel free. But I don't think we need to make this a priority.

**Comment by moewew** [comment]
`biblatex` 3.15 with the changes from #957 has been released and is available in both MikTeX and TeX live.

Let's close this issue for now. We may want to revisit the role strings if at some point we (have to) overhaul the whole localisation system. For now I think we can just try and translate things so that they don't sound too awkward.
