### ISSUE TITLE
Remove extradate?

### ISSUE THREAD

**Issue by thesiswriter1** [plk/biblatex#959]
hey guys,

is there an option to easily disable the extradate? Basically I don't want to append any letters to the year even if I have multiple sources from one author

**Comment by moewew** [comment]
There is a very similar question on TeX.SX at the moment: https://tex.stackexchange.com/q/523786/35864.

Without additional details about your citation and bibliography setup I don't feel comfortable suggesting anything as usually the `extradate` info is there for a reason and just removing it can render the bibliography unusable.

**Comment by thesiswriter1** [comment]
@moewew yeah, that's me, I provided a mwe there now, thanks for helping out!

comment:
> @moewe thanks for explaining! I created this: https://github.com/thesiswriter1/mwe-latex - The sources are in the literatur/literatur.bib file and the kapitel/example.tex shows an example of it. I am importing biblatex in the thesis_main.tex file and provided additional configuration (taken from the template) at skripte/modsBiblatex2018.tex

**Comment by moewew** [comment]
OK, I guess this is more of a question for TeX.SX than a bug report or feature request here. I'm closing this issue, but will see what I can do over at TeX.SX. If it turns out that there is a bug or a useful feature request to be formulated, we can open a new issue with an MWE.
