### ISSUE TITLE
\mkpageprefix misbehaves as postprocessor of \mkcomprange etc.

### ISSUE THREAD

**Issue by alex-ball** [plk/biblatex#962]
Since commit 9dc5452b41 (in which the second optional argument to `\mknormrange` and friends was introduced), `\mkpageprefix` does not work properly when used as the postprocessor argument to `\mkcomprange`, `\mknormrange` or `\mkfirstpage`.

Somewhat contrived MWE:

```tex
\documentclass{article}
\usepackage[british]{babel}
\usepackage{csquotes}

\usepackage[backend=biber]{biblatex}
\DeclareFieldFormat{postnote}{%
  \ifentrytype{collection}%
    {\mkpageprefix{#1}}%
    {\mkcomprange[\mkpageprefix]{#1}}%
}

\addbibresource{biblatex-examples.bib}

\begin{document}
Uncompressed \cite[203-204]{matuz:doody}.
Compressed \cite[3027-3028]{aksin}.
\end{document}
```

Expected result: both postnotes should have "pp." before the page ranges.

Actual result: the compressed range does not have "pp." before the page range.

I have used `\tracingmacros` to look at what is going, and it seems to be failing at the `\ifnumerals` test:

```tex
\@->\spacefactor \@m {}

\bibrangedash ->

\@->\spacefactor \@m {}

\@secondoftwo #1#2->#2
#1<-\bibstring {pages}\ppspace 
#2<-\def \pno {\bibstring {page}}\def \ppno {\bibstring {pages}}
```

An isolated version of the same test, i.e.

```tex
\makeatletter
\blx@blxinit
\ifnumerals {\@firstofone {3027}\bibrangedash \@firstofone {8}}%
{Test is numeric.}{Test is not numeric.}
\makeatother
```

works as normal:

```tex
\@firstofone #1->#1
#1<-

\bibrangedash ->

\@firstofone #1->#1
#1<-

\@firstoftwo #1#2->#1
#1<-Test 2 is numeric.
#2<-Test 2 is not numeric.
```

I'm afraid that it gets a bit too TeXnical for me at that point.

**Comment by moewew** [comment]
Thank you very much for reporting this bug and also for pinpointing where I broke stuff. I can't promise that I'll be able to find and fix the issue quickly, but I will have a look at the MWE later.

**Comment by moewew** [comment]
https://github.com/plk/biblatex/commit/c5c6e3ae8af8cedf1b53b19beddacaf9eb9beca4 expands things a bit more and gets rid of the `\@firstofone`s and avoids the issue.

But I should still have a look at `\ifnumerals`...

**Comment by moewew** [comment]
It appears that the `\ifnumerals` test fail could also have been prevented by using an explicit ```\catcode`\@=11``` instead of `\makeatletter` (I have absolutely no idea why, but I'm wondering if it might have to do with the `\makeatletter` changes mentioned in https://www.overleaf.com/blog/tex-live-2019-upgrade-january-2020 - I couldn't find any more on that though). See https://github.com/plk/biblatex/commit/be01929019cdf7cf7b672241cfef08831eff091c.

Each of the two fixes seems to resolve the issue individually, but having them both should hopefully do no harm.

**Comment by moewew** [comment]
`biblatex` 3.15 with the fix for this issue has been released and is available in the two big TeX distributions and on CTAN.

The MWE from above shows 'pp.' for both page ranges as desired (at least that's what I think the output we expect. If not just open a new issue.).
