### ISSUE TITLE
Check compatibility with newest babel

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#964]
`babel` 3.39 has locale loading on the fly: https://github.com/latex3/babel/wiki/What's-new-in-babel-3.39

Check that things still work as expected. I also seem to recall that I heard `babel`'s `ini` files work differently than `.ldf` files. We probably need to check that as well.

**Comment by moewew** [comment]
Consider the following example
```latex
\documentclass{article}

\usepackage[english]{babel} % all English
%\usepackage[russian,spanish,english]{babel} % switched languages

\babelfont[russian]{rm}{Linux Libertine O}

\usepackage{csquotes}
\usepackage[style=authoryear]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
English \autocite[380]{sigfridsson}.

\foreignlanguage{russian}{Русский \autocite[381]{sigfridsson}}.

\foreignlanguage{spanish}{Español \autocite[382]{sigfridsson}}.
\end{document}
```
When the languages are loaded explicitly, the language switching in `\foreignlanguage` works, otherwise not.

I'm not sure what the more reasonable outcome here is (the `babel` doc says that this new feature is for mostly monolingual documents), but surely this difference is not great.

**Comment by plk** [comment]
I also tried this and I'm not sure how this is supposed to work either - I still see warnings about languages not loaded too which I would assume wouldn't be the case if they are dynamically loaded.

**Comment by moewew** [comment]
Mhh, as far as I can tell the `babel` side of things works fine and does not produce any warnings. (The example with `\babelfont` needs LuaLaTeX or XeLaTeX, but if it and the Russian bit is dropped from the MWE it works also with pdfLaTeX). If I understand correctly, only `\foreignlanguage` works with the new on-the-fly loading, `\selectlanguage` doesn't.

I don't quite understand yet why the `biblatex` language switching happens in one case and not in the other.

I guess it would be more logical if `biblatex` did *not* switch languages inside `\foreignlanguage`, but I think it has been doing that for a long time now, so I'm not sure if we can change that now.

**Comment by moewew** [comment]
I think the MWE in https://github.com/latex3/babel/issues/55 can explain what we are seeing here.

 `\foreignlanguage` does not call `\select@language` (where we hook into to load language definitions and set `\currentlang`), but only `\extras<language>`. If the language was loaded before, we have already loaded the language and populated `\extras<language>`. But if the language wasn't loaded before, this will not happen and so language extras do not contain any `biblatex` language switch instructions.

**Comment by moewew** [comment]
The inconsistency shown in the second post above should be fixed in https://github.com/plk/biblatex/commit/02d50647aa4b0000e33be2eaa6b83ee6adcd738b.
