### ISSUE TITLE
Add role for 'supervisor' as name/editortype

### ISSUE THREAD

**Issue by LukasCBossert** [plk/biblatex#966]
I am aware of the discussion in SE: https://tex.stackexchange.com/questions/184848/how-to-add-the-name-of-the-supervisor-in-a-thesis-field
But since libraries have the information of the supervisor in their data it would be nice to use/show it properly.

e.g. [http://publications.rwth-aachen.de/record/773183](http://publications.rwth-aachen.de/record/773183/export/hx?ln=de)
```
@PHDTHESIS{Rosenhain:773183,
      author       = {Rosenhain, Stefanie},
      othercontributors = {Kießling, Fabian and Strnad, Pavel},
      title        = {{V}alidation and qualience-mediated computed tomography
                      indeep tissue regions},
      school       = {RWTH Aachen University},
      type         = {Dissertation},
      address      = {Aachen},
      reportid     = {RWTH-2019-10956},
      pages        = {1 Online-Ressource : Illustrationen},
      year         = {2019},
      note         = {Veröffentlicht auf dem Publikationsserver der RWTH Aachen
                      University 2020; Dissertation, RWTH Aachen University, 2019,
                      Kumulative Dissertation},
...
      cin          = {811003-3},
      ddc          = {610},
      cid          = {$I:(DE-82)811003-3_20140620$},
      typ          = {PUB:(DE-HGF)11},
      doi          = {10.18154/RWTH-2019-10956},
      url          = {http://publications.rwth-aachen.de/record/773183},
}
```
Note that the RWTH uses the non-existant field `othercontributors` for the supervisors.

@josephwright has a point with his [comment](https://tex.stackexchange.com/questions/184848/how-to-add-the-name-of-the-supervisor-in-a-thesis-field#comment427497_184848) but I think there already is the defined role of an [`organizer` in `biblatex`](https://ctan.net/macros/latex/contrib/biblatex/doc/biblatex.pdf#paragraph.4.9.2.2) who probably did not write the book etc. as well.

**Comment by moewew** [comment]
I guess we *could* add a `supervisor` (plus `supervisors` and `bysupervisor`) bibstring, but I don't want to add a specific field to the data model and I definitely don't want to add `othercontributors` to the data model.

I wasn't too happy about adding `organizer` either (because I didn't want to create a precedent and I didn't really see the point, see https://github.com/plk/biblatex/issues/543).

**Comment by LukasCBossert** [comment]
I get your point and starting to add `supervisor` et al. is quite a slippery slope. So I will do some postprocessing with the data I get from the library and change `othercontributors` (very misleading field name) to whatever I need it to be).

**Comment by moewew** [comment]
Well, I won't flat out refuse to add any new bibstrings, but I would like to strike a balance between adding too many strings that the majority of people won't even want to use and useful inclusions that help people create accurate, useful and complete bibliography entries.

From the programming point of view adding a bibstring is incredibly simple, it's just a few lines. The real work is delegated to the translators: Usually those missing strings are only picked up in more or less periodical reviews by language contributors.

We usually don't add new *fields* unless absolutely necessary (or unless there is a new core feature to be implemented).

**Comment by moewew** [comment]
I'll mark this as *wontfix* for now. If it turns out that many people need or want a `supervisor` bibstring, for example because many established reference guides ask for one, we can implement it (quite easily), but until then I would like to avoid bibstring bloat.

**Comment by LukasCBossert** [comment]
That is absolutely fine. Coping with the `supervisor`-issue and handling bibtex-entries like the one posted I learned how to use `biber --tool`. With a custom made config-file it is very easy to adjust such entries.

**Comment by pauloney** [comment]
I find that to be a slippery-slope! Names of advisors to theses are
mis-used in several different subjects. In Mathematics, Physics,
Astronomy... they are squarely ignored (as it should be, see remarks on CMS
a bit down). On the other side of the spectrum in brazilian Economics
establishments, they are sometimes listedx as CO-authors.

The CMS recommends NO mentioning of the advisor name:

    https://libguides.wvu.edu/c.php?g=418946&p=2855335

It is, after all, a work by the student.

If needs to be, it can be inserted as an observation.

Paulo Ney
