### ISSUE TITLE
Can we use babel/polyglossia hooks to avoid patching

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#970]
See for example https://tex.stackexchange.com/q/529984/35864 (https://github.com/plk/biblatex/commit/06913511f881172a0878cc19a6e5677af5885e74) and Ulrike's comment https://tex.stackexchange.com/questions/529984/document-with-custom-bibliography-driver-compiling-with-babel-3-33-and-biblatex/529993?noredirect=1#comment1341156_529993.

It would be nice if we could avoid patching language selection macros. Maybe we can use existing hooks or ask for new hooks instead. Before I do that I need to understand exactly why we need to patch internal `babel`/`polyglossia` commands in the first place.

**Comment by jbezos** [comment]
> It would be nice if we could avoid patching language selection macros. 

Indeed. There are several hooks in `babel`. I'm not sure what you need, but if none of the existing hooks is useful for you, I'm willing to add a new one. Please, make a feature request. I'm working on a new version to be release in a few weeks, so I could add it.

**Comment by moewew** [comment]
> I'm not sure what you need, but if none of the existing hooks is useful for you, I'm willing to add a new one. Please, make a feature request. I'm working on a new version to be release in a few weeks, so I could add it.

Great! As I wrote above I'll need some time to figure out what we actually need, but once I've done that I'll be sure to open a feature request.

**Comment by moewew** [comment]
I opened https://github.com/latex3/babel/issues/55 with what I hope is an accurate description of what we need.

**Comment by moewew** [comment]
`babel` hooks were surprisingly easy: https://github.com/plk/biblatex/commit/02d50647aa4b0000e33be2eaa6b83ee6adcd738b. (Plus `\AddtoBabelHook` has been with us for so long that we can just remove the old code without backwards compatibility problems.)

Will have to wait and see if we can get rid of `\pretocmd` for `polyglossia` as well.

**Comment by plk** [comment]
@moewew - that's very good news - the patching was always a bit messy

**Comment by moewew** [comment]
There is a real (in the `etoolbox` sense) and documented hook in `polyglossia` now so we can avoid `\pretocmd` now and only need the much simpler `\preto`.

**Comment by moewew** [comment]
In https://github.com/plk/biblatex/pull/1018/commits/db0b57087611155a88eb28442ac24aa7bab84af1 we switch from the `beforeextras` to the `afterreset` `babel` hook. Fingers crossed that everything still works.
