### ISSUE TITLE
Please consider adding a License field for ONLINE 

### ISSUE THREAD

**Issue by jimhefferon** [plk/biblatex#971]
For lots of online items this is a relevant point. It should take a URL.

**Comment by moewew** [comment]
You can add new fields to the data model if you need them. For example (only slightly modified from my answer to https://tex.stackexchange.com/q/451197/35864)
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\begin{filecontents}{license-lit.dbx}
\DeclareDatamodelFields[type=field,datatype=literal]{license}
\DeclareDatamodelEntryfields[software]{license}
\end{filecontents}

\usepackage[style=authoryear, backend=biber, datamodel=license-lit]{biblatex}

\NewBibliographyString{license}
\DefineBibliographyStrings{english}{%
  license = {license},
}
\DefineBibliographyStrings{german}{%
  license = {Lizenz},
}

\DeclareFieldFormat{license}{\bibstring{license}\addcolon\space#1}
\renewbibmacro{addendum+pubstate}{%
  \printfield{license}%
  \newunit\newblock
  \printfield{addendum}%
  \newunit\newblock
  \printfield{pubstate}}

\begin{filecontents}{\jobname.bib}
@software{wpf,
  author  = {{Xceed}},
  title   = {Extended WPF Toolkit},
  url     = {https://github.com/xceedsoftware/wpftoolkit},
  license = {Ms-PL},
}
\end{filecontents}

\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{sigfridsson,wpf}
\printbibliography
\end{document}
```
Or if you want a URL
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\begin{filecontents}{license-url.dbx}
\DeclareDatamodelFields[type=field,datatype=uri]{license}
\DeclareDatamodelEntryfields[online]{license}
\end{filecontents}

\usepackage[style=authoryear, backend=biber, datamodel=license-url]{biblatex}

\NewBibliographyString{license}
\DefineBibliographyStrings{english}{%
  license = {license},
}
\DefineBibliographyStrings{german}{%
  license = {Lizenz},
}

\DeclareFieldFormat{license}{\bibstring{license}\addcolon\space\url{#1}}
\renewbibmacro{addendum+pubstate}{%
  \printfield{license}%
  \newunit\newblock
  \printfield{addendum}%
  \newunit\newblock
  \printfield{pubstate}}

\begin{filecontents}{\jobname.bib}
@online{sloth,
  author   = {Christian Mehlführer},
  date     = {2007-02-07},
  title    = {Three-toed-sloth},
  subtitle = {Picture taken in the {Cahuita National Park} in the southeast of {Costa Rica}},
  url      = {https://commons.wikimedia.org/wiki/File:MC_Drei-Finger-Faultier.jpg},
  license  = {https://creativecommons.org/licenses/by/2.5/deed.en},
}
\end{filecontents}

\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{sigfridsson,sloth}
\printbibliography
\end{document}
```

Our stance towards adding new fields to the standard data model is rather conservative. We know that core `biblatex` can't cover every use case. And thanks to the extensible data model, the core and standard styles don't need to cover everything. The standard styles should be a solid base that serves the most common use cases.  Unless there is (1) a huge demand and a clear specification how things should be implemented or (2) an exciting new feature that requires `biblatex` core changes, we usually don't want to clutter the data model with even more fields.

See also #72, #122, #156, #220, #224, #256, #272, #776, #880, #907, #908, #969.

**Comment by moewew** [comment]
I'm closing this as *won't fix* **for now**. As mentioned above, the standard data model can not fully cover everybody's wishes; it is intended to be a solid basis that works for most uses.

If it turns out that this is a very important feature, we can reconsider adding a `license` field at any time. So if you need it, please comment here, in particular if you can find bibliography style guides that require such a field or if there is a strong prevalence of such a field in published works.

**Comment by jimhefferon** [comment]
OK, thank you for looking at it.

Jim

________________________________________
