### ISSUE TITLE
\UndefineBibliographyExtras causes bad language commands behaviour

### ISSUE THREAD

**Issue by ndlecic** [plk/biblatex#982]
At some point after 2018, this code:
```latex
\documentclass{article}
\usepackage{polyglossia}
\setdefaultlanguage{russian}
\setotherlanguage{english}
\setmainfont{CMU Serif}
\usepackage[style=gost-authoryear]{biblatex}
\UndefineBibliographyExtras{russian}{\bibrangedash}
\begin{document}
123\par
\textrussian{123}\par
\textenglish{123}
\end{document}
```
without invoking `biber` results in this:
![extra dashes](http://anthesphoria.net/tmp/123.png)
These dashes are obviously a bad thing to happen. Could you please take a look what happened?

**Comment by moewew** [comment]
Mhhh. That is more or less what I would expect to happen. `\UndefineBibliographyExtras` must not contain any code that might print anything.

What was that code supposed to do?

**Comment by ndlecic** [comment]
> Mhhh. That is more or less what I would expect to happen. `\UndefineBibliographyExtras` must not contain any code that might print anything.
> 
> What was that code supposed to do?

Well, it was supposed to precede something like this:
```latex
\DefineBibliographyExtras{russian}{%
    \protected\def\bibrangedash{%
        \textendash\penalty\hyphenpenalty}% %breakable dash
}
```
Prior to biblatex 3.11 such a `\UndefineBibliographyExtras` didn't cause any harm.

**Comment by moewew** [comment]
Ah, in that case the correct code would have been
```latex
\DefineBibliographyExtras{russian}{%
  \savecommand\bibrangedash
  \protected\def\bibrangedash{%
    \textendash\penalty\hyphenpenalty}% %breakable dash
}
\UndefineBibliographyExtras{russian}{\restorecommand\bibrangedash}
```
but since all `.lbx` files should declare `\bibrangedash`, it is enough to just say
```latex
\DefineBibliographyExtras{russian}{%
  \protected\def\bibrangedash{%
    \textendash\penalty\hyphenpenalty}% %breakable dash
}
```
without any `\UndefineBibliographyExtras` for `\bibrangedash`.

---

```latex
\UndefineBibliographyExtras{russian}{\bibrangedash}
```
was always wrong and probably just didn't lead to any issues in the MWE since older versions of `biblatex` were severely broken with `polyglossia` to the point that some things just didn't work at all. With `babel` this would always have yielded issues.

**Comment by ndlecic** [comment]
> Ah, in that case the correct code would have been
> [...]

I see, thanks. 

> older versions of `biblatex` were severely broken with `polyglossia` to the point that some things just didn't work at all. With `babel` this would always have yielded issues.

Well, `biblatex`+`polyglossia` used to work for me without major problems since 2016. In that case, I guess it was just a lucky combination of parameters.
