### ISSUE TITLE
biblistfilter doesn't work when printing both unfiltered and filtered list

### ISSUE THREAD

**Issue by dcpurton** [plk/biblatex#989]
Printing a biblist with a filter does not work when a second list with the default filter is also printed.

# MWE

```TeX
\documentclass{article}

\begin{filecontents}[overwrite]{\jobname.bib}
@book{a,
  title = {First Title},
  shorthand = {FT},
  keywords = {a}
}
@book{b,
  title = {Second Title},
  shorthand = {ST}
}
\end{filecontents}

\usepackage{biblatex}
\addbibresource{\jobname.bib}

\DeclareBiblistFilter{a}{
  \filter[type=keyword, filter=a]
}

\begin{document}

\nocite{*}

\printbiblist{shorthand}

% Only filters when previous line is commented out
\printbiblist[biblistfilter=a]{shorthand}

\end{document}
```

This (unexpectedly) produces:

![tex088](https://user-images.githubusercontent.com/6268044/79067388-f8258500-7cfd-11ea-8f56-be3f3e532c33.png)

If I comment out `\printbiblist{shorthand}`, then I get the expected:

![tex088](https://user-images.githubusercontent.com/6268044/79067404-2014e880-7cfe-11ea-8b7c-d988bf71754e.png)

There are other related quirks I have discovered, but the fix might be the same for them all.

**Comment by moewew** [comment]
@plk I have a hunch that the problem here is that the `biblistfilter` should be part of the `datalist` name.

**Comment by moewew** [comment]
Also: Thank you @dcpurton for reporting this and happy Easter everybody.

**Comment by plk** [comment]
This needs a minor adjustment to, I think , refcontext name construction internally - luckily, there was already something envisaged for this - please try the latest biblatex 3.5 DEV version - you don't need to update `biber` if you have the latest DEV version.

**Comment by moewew** [comment]
I noticed that now `\setkeys{blx@biblist2}{#1}` is called before `\setkeys{blx@biblist1}{#1}` that appears a bit odd.

**Comment by plk** [comment]
It's called before and after ... I will likely clean that up and divide the options setting into three parts but this bug shows the need to get the bibfilter first and that is in `biblist2`, parts of which need setting after `biblist`. Can't hurt resetting after 1 again but looks odd, agreed.

**Comment by moewew** [comment]
If I'm not mistaken `biblist1` is a no-op currenly anyway, so it probably doesn't matter too much, so I would probably just call `biblist1` and `biblist2` once and move them so that `biblist1` is called before `biblist2`. But I can't be sure I'm not missing anything.

**Comment by plk** [comment]
`biblist1` shouldn't be a no-op - it sets the section which we need before most things in `biblist2`. What I'll likely do if this bugfix works is to move the bibfilter option into `biblist1`. This was just a quick test to see if the general idea of making the first component of the refcontext unique by using the filter name instead of the sorting scheme name works.

**Comment by dcpurton** [comment]
Thanks! Your patch works in my other slightly different test case too.

**Comment by moewew** [comment]
Oh yes, sorry you are right, I missed the `{%` at the end of `\define@key{blx@biblist1}{section}{%` in my search output. I'm glad I didn't try to fix the order of the calls as I would have probably messed something up.

**Comment by plk** [comment]
Now it's confirmed and I have run the test suite, filter is set now in `biblist1` as it has no dependencies on the section and there is no extra `biblist2` setkeys. DEV version updated on SF.

**Comment by moewew** [comment]
`biblatex` 3.15 with the fix has been released and is available in MikTeX and TeX live now.
