### ISSUE TITLE
Org-mode citation syntax

### ISSUE THREAD

**Issue by gusbrs** [plk/biblatex#993]
I'd like to call your attention for a recent discussion in the Org mode mailing list regarding an old topic there, which is Org's citation syntax. This discussion, as far as I'm aware, went on intensively between 2012-2015 or thereabouts, and implementation advanced significantly in the `wip-cite` branch. After that, things mostly stalled, but discussion was taken up by a recent message from Bruce D'Arcus (https://lists.gnu.org/archive/html/emacs-orgmode/2020-04/msg00100.html, you can follow the thread from there), and it seems things are pointing for the branch to be merged.

Org mode is many things, and among them it is a light markup language which allows one to author documents which can be exported to different formats, including pdf, html, odt and others still through both its built-in exporter, and `pandoc`. In this dimension, it is similar to markdown, but richer and more flexible and powerful.

One of the core export formats is PDF which, as expected, is done by a conversion to LaTeX, and through `latex` (or other engine of choice) to PDF.

Given the multiple output formats, support for CSL is being taken very seriously in the discussions, and `pandoc` interface within this. But, given the importance of LaTeX, and biblatex, also support for the latter is regarded as a key requirement in the syntax which is being discussed/proposed (see https://lists.gnu.org/archive/html/emacs-orgmode/2020-04/msg00190.html, for context, Nicolas Goaziou is one of the most active Org devs and, as far as I know, one of the main responsibles for syntax and parsing).

There's a number of biblatex users which have taken part in the discussion. But I do believe a feedback from biblatex's developers would be appreciated there. (Speaking for myself, it certainly would). I also believe that a polished support for biblatex in Org mode is in the interests of biblatex as a project, as it would both allow to broaden the user base to those less inclined to the daunting aspects of LaTeX and would allow folks to author documents which enjoy the feature richness of biblatex and export them to other formats as required with relative ease.

**Comment by moewew** [comment]
I've had a short skim through the recent messages in the archive, but I didn't see anything useful that I (we?) could add to the discussion at this point. Plus I only have a vague idea of the whole Org mode citation syntax and of the discussion at this point, so I don't think if it would be useful or appreciated if I were to butt in from the side.

If concrete questions, feature requests or bug reports for `biblatex` emerge I would of course be more than happy to see what I can do.

@plk Anything you would like to say?

**Comment by plk** [comment]
No - I also looked at it but couldn't see anywhere where we could currently have an input. If it is a question of supporting input/output formats in `biber`, then I can get more involved but my past experience with this is that I have added such things (Endnote, RIS etc) and nobody uses them.

**Comment by gusbrs** [comment]
Ok, I understand. And thank you very much for taking the time to consider it.

Feel free to close this.

**Comment by moewew** [comment]
OK, let's close this for now. If you have an eye on the discussion anyway, feel free to alert us if something interesting comes along. I might check the mailing list archives now and again when I'm bored, but that probably means that I won't see things in real time as they develop.

**Comment by gusbrs** [comment]
OK, and if you'd like some information on the matter you think I might be able to provide, do not hesitate to ask. In particular, I did some mailing list digging on the issue a couple of years back and I did keep a collection of links of threads I found interesting then. It's nothing organized, the information is scattered, and the discussion was really long. Mailing lists, you know how it is. But if you'd like me to share these links, let me know.

**Comment by gusbrs** [comment]
@plk and @moewew I though you might want to know that the new citation syntax for Org mode has recently been merged, with very good support for `biblatex`.

A summary of the results can be found at https://blog.tecosaur.com/tmio/2021-07-31-citations.html

(This is just a follow up comment on this. Nothing being asked or suggested, just bringing the good news in case you are interested.)
