### ISSUE TITLE
urldate is shown as publication date if the latter is missing

### ISSUE THREAD

**Issue by adriangoransson** [plk/biblatex#995]
I have the reference below to an online encyclopedia. There is no publication date but I still want to show the access date. However by doing so the citation shows up incorrectly as `Author (2020)`.

```
@online{ne_delning_definition,
    Author={Nationalencyklopedin},
    Title={Delningsekonomi},
    URL={http://www.ne.se/uppslagsverk/encyklopedi/lång/delningsekonomi},
    urldate={2020-04-07},
}
```

I've used a `\DeclareLabeldate` workaround described in [this SE answer](https://tex.stackexchange.com/a/525164) but it feels hacky. Is there a better solution?

**Comment by moewew** [comment]
If you don't want the `urldate` considered for `labeldate` generation (which is understandable) the `\DeclareLabeldate` declaration shown in David Purton's TeX.SX answer is the standard way to resolve this
```latex
\DeclareLabeldate{%
  \field{date}
  \field{year}
  \field{eventdate}
  \field{origdate}
  \literal{nodate}
}
```
Just for comparison, the original definition in `biblatex.def` is
https://github.com/plk/biblatex/blob/e2c956bc377bf0652ac405fcb5a9ed4508056bba/tex/latex/biblatex/biblatex.def#L1350-L1357

`\DeclareLabeldate` is the intended interface for these sort of things, so it shouldn't feel hacky.

**Comment by moewew** [comment]
The question seems to be answered, so I'm closing this for now.

Feel free to open a new issue if you want to formulate a feature request out of this (or a bug report). Note that for questions TeX.SX (https://tex.stackexchange.com/questions) is usually a better place than the bug tracker.
