### ISSUE TITLE
Spaces in abbreviations in german.lbx

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#997]
Because of the discussion in https://github.com/plk/biblatex/pull/994 I checked out the situation with respect to spaces and dots in `german.lbx` and found that many strings use `.\,`

https://github.com/plk/biblatex/blob/200e3cf74e375d3f4082dc36cbbd0f878c921847/tex/latex/biblatex/lbx/german.lbx#L349

https://github.com/plk/biblatex/blob/200e3cf74e375d3f4082dc36cbbd0f878c921847/tex/latex/biblatex/lbx/german.lbx#L359-L360

but `nodate` has

https://github.com/plk/biblatex/blob/200e3cf74e375d3f4082dc36cbbd0f878c921847/tex/latex/biblatex/lbx/german.lbx#L374

and the other date-related strings have

https://github.com/plk/biblatex/blob/200e3cf74e375d3f4082dc36cbbd0f878c921847/tex/latex/biblatex/lbx/german.lbx#L543-L546

I haven't had a look at my printed Duden yet, but a little Googling suggests that `.\,` is what most people would recommend.

@jspitz Do you have any insight here?

---

Then there is 

https://github.com/plk/biblatex/blob/200e3cf74e375d3f4082dc36cbbd0f878c921847/tex/latex/biblatex/lbx/german.lbx#L424

but

https://github.com/plk/biblatex/blob/200e3cf74e375d3f4082dc36cbbd0f878c921847/tex/latex/biblatex/lbx/german.lbx#L442

and

https://github.com/plk/biblatex/blob/200e3cf74e375d3f4082dc36cbbd0f878c921847/tex/latex/biblatex/lbx/german.lbx#L443-L444

**Comment by jspitz** [comment]
I'd say it depends whether it's an established abbreviation which most people would write with no space. These I would set with thinspace (this includes `o.\,D.` above). I would use a normal (non-breaking) space with `s.~auch` and `s.~Anm.` But I am not a typographer and I understand this is more a matter of taste (I've consulted "Detailtypographie" by Forssman/de Jong, but they are not very clear on this either).

**Comment by moewew** [comment]
@jspitz Thanks for the input.


That sounds like a good approach. Thin spaces make sense in short multi-letter abbreviations, `s.~auch` also looks sensible. For longer abbreviations one could also consider `\adddotspace` instead of `\addnbspace`/`~`, which uses `abbrvpenalty` to discourage but not completely rule out line breaks.

I'll see if I can come up with a pull request for this in the next days and we can discuss the finer points then (if people are interested).

**Comment by moewew** [comment]
Pull request with the changes I had in mind is at https://github.com/plk/biblatex/pull/999, suggestions and comments are very welcome.
